### ISSUE TITLE
ledger-api-test-tool:  ensure semantic tester can check multi-participant workflows

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#1000]
Ensure semantic tester can check multi-participant workflows (requires to provide it with a topology configuration stating what party is hosted at what Ledger API)

See parent: https://github.com/digital-asset/daml/issues/146

**Comment by timw-da** [comment]
Current design for this is that we implement a LedgerContext that supports multi-plexing ledger api servers, e.g. "MultiLedgerContext". This ledger context has a default party, but also allows access via a specific party's server e.g. forParty("Alive"). The MultiLedgerContext will be available as an additional remote fixture, e.g. "MultiRemoteAPI".
