### ISSUE TITLE
REPL needs manual import of DA.TextMap

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#10073]
I've got a template that uses `DA.TextMap`:

```
template Bar
  with
    p : Party
    matrix : [TextMap Foo]
  where
    signatory p
```

When I start the repl with my usual command `daml repl .daml/dist/large-contract-0.0.1.dar -i large-contract --ledger-host localhost --ledger-port 6865`, and try to do anything with `Bar`, I get this error:

```
File:     Line2.daml
Hidden:   no
Range:    6:21-6:43
Source:   typecheck
Severity: DsError
Message:
  Line2.daml:6:21: error:
  Not in scope: type constructor or class ‘DA.Internal.LF.TextMap’
  No module named ‘DA.Internal.LF’ is imported.
```

Adding `DA.TextMap` manually via `:module + DA.TextMap` fixes this, but it's surprising to me that that is necessary, and I don't think the error message would lead many users to that conclusion.

**Comment by cocreature** [comment]
What exactly are you trying to do? If you want to construct a text map you need to import the module. That’s expected.
If you do something like `let x = Bar alice []` you don’t need to import it and a quick test confirms that.

**Comment by bame-da** [comment]
Construction works. I have a function `genMatrix: Int -> Int -> [TextMap Foo]`. `let matrix = genMatrix 10 10` doesn't cause an error, but `:json matrix` or `submit alice do createCmd Bar with p = party; matrix` does.

At no point am I handling a `TextMap` value directly in the REPL.

**Comment by bame-da** [comment]
Here's my Daml model:

```
module Main where
import Daml.Script
import DA.TextMap

data Foo = Foo with
  i : Int
  t : Text
  m : TextMap Int
    deriving (Show, Eq)

genFoo : Int -> Int -> Foo
genFoo size num = Foo with
    i = offset
    t = show offset
    m = genMap
  where
    offset = num
    genMap = DA.TextMap.fromList
      (map (\n -> (show n, n)) [offset..(offset + size -1)])

genMatrix: Int -> Int -> [TextMap Foo]
genMatrix size fooSize = map genMap [1..size]
  where
    genMap n =
      let
        offset = (n - 1) * size
      in DA.TextMap.fromList
        (map (\m -> (show (offset + m), genFoo fooSize (offset + m))) [1..size])

template Bar
  with
    p : Party
    matrix : [TextMap Foo]
  where
    signatory p
```

Then in REPL:

```
daml> let alice = partyFromText "Alice"
daml> let matrix = genMatrix 5 5
daml> submit alice do create Bar with p = alice; matrix
File:     Line2.daml
Hidden:   no
Range:    6:30-6:52
Source:   typecheck
Severity: DsError
Message:
  Line2.daml:6:30: error:
  Not in scope: type constructor or class ‘DA.Internal.LF.TextMap’
  No module named ‘DA.Internal.LF’ is imported.
```

**Comment by cocreature** [comment]
I see, this is because we need a type annotation for previous bindings in the code we generate which means we need the type in scope somehow. We try to be clever and figure out which import allows us to reference the type but if it’s not available without an import we fall over. Not impossible to fix but a bit tricky.
