### ISSUE TITLE
`daml ledger upload-dar` does not resolve localhost to 127.0.0.1 when proxy / firewall is set (GRPCIOTimeout)

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#10081]
Please see
https://discuss.daml.com/t/daml-ledger-upload-dar-gives-grpciotimeout/2743/4

**Comment by cocreature** [comment]
As mentioned in the forum thread, there probably isn’t anything we can do here. This comes from the underlying gRPC C++ library which is out of our control.

**Comment by richardkapolnai-da** [comment]
Makes sense, thank you for the explanation.
If this comes up later, we may raise something there.
