### ISSUE TITLE
Avoid generating hi and hie files as part of daml build

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#1009]
`daml build` currently creates `.hi` and `.hie` files for each `.daml` file. It would be nice if we can avoid this because it pollutes the solution folders.

**Comment by neil-da** [comment]
Fine to generate them, they should just be in a different directory.

**Comment by robin-da** [comment]
On it.

**Comment by cocreature** [comment]
Closing since #1074 has been merged.
