### ISSUE TITLE
Make assertMsg give better information for ==

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#101]
Everyone writes `assertMsg "test" $ a == b`, which unfortunately means the error message doesn't say what `a` or `b` are. We have `===` which fixes this but doesn't have a textual message. Should we have `assertMsgEq` which takes the message and `a` and `b` separately? Should we HLint assertMsg to assertMsgEq? Seems to be a common thing that comes up.

CC @silvanv-da

**Comment by cocreature** [comment]
Hasn’t come up in ages so closing as no longer relevant.
