### ISSUE TITLE
folder structure lost in dar package

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#1010]
The folder structure is lost in a dar package generated via `daml build`. E.g. if the daml files are located in a folder called `Foo`, the `Foo` folder is dropped in the dar package.

**Comment by neil-da** [comment]
Why do you want to keep that folder structure?

**Comment by robin-da** [comment]
@neil-da I think the name resolution doesn't work if the directory structure is not correct.

**Comment by neil-da** [comment]
Is this the problem that the module `Foo.Bar` doesn't end up in `Foo/Bar.*`? If we had `Foo.Bar` and Baz.Bar` would they conflict? That should be fixed.

**Comment by robin-da** [comment]
@neil-da Yes, I think that's the problem.
