### ISSUE TITLE
Avoid collisions with Java’s new Record type

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10130]
Our Java binidngs currently use `Record` which collides with the `Record` type introduced in Java 14.

While this doesn’t make it impossible to use, you have to fully qualify our `Record` type since Java has no mechanism to alias imports which is a rather shitty ux.

To fix this we could consistently prefix all our daml-lf builtin types with `DamlLf`, e.g., `DamlLfRecord` and deprecate the old types.

**Comment by stefanobaghino-da** [comment]
Bike-shedding time: should we use `DamlLf` or just `Daml`? `DamlLf` is somehow more accurate (`LedgerApi` would probably be the pedantically accurate one), but I find, say, `DamlList` to be easier to read and digest without necessarily knowing about Daml-LF.

**Comment by cocreature** [comment]
I’d go for `DamlLf` but I don’t feel strongly about it at all so happy to be overruled.

**Comment by stefanobaghino-da** [comment]
Just had a quick look at the code, we already have `DamlList`, `DamlOptional` and so on, while we also have `Int64` and `Bool`.

Should we then keep this change minimal and just rename `Record` to `DamlRecord`?

**Comment by cocreature** [comment]
ah yeah then that probably makes sense.

**Comment by stefanobaghino-da** [comment]
Ok, seems fairly quick, I'll take care of this.
