### ISSUE TITLE
Create DAML Assistant integration test for quickstart-scala template

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#1015]

**Comment by associahedron** [comment]
I added a test that runs `daml build` on quickstart-scala (as part of the `daml clean` tests). Is there a another compilation step/test for the scala part, so we can get this done?

**Comment by leo-da** [comment]
@associahedron Thanks a lot!
See https://github.com/digital-asset/daml/blob/master/language-support/scala/examples/quickstart-scala/README.md

The following sbt command should finish with `0` error code:
```
sbt "application/runMain com.digitalasset.quickstart.iou.IouMain localhost 6865"
```

**Comment by gerolf-da** [comment]
Considering our move to create-daml-app and using first and foremost the HTTP JSON API, I think we close this. What do you think, @leo-da?

**Comment by stefanobaghino-da** [comment]
@leo-da is still a valid ticket? If not, can you close this please?

**Comment by leo-da** [comment]
yep, I don't think there are any plans to support quicstart-scala templates
