### ISSUE TITLE
Referencing contract keys by hash instead of value

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10159]
Currently contract keys are referenced via `GlobalKey` pretty much everywhere. `GlobalKey` consists of template id, contract key value and the hash (which can be derived from the value).

This means we have to send contract keys around in a bunch of places which is a bunch of unnecessary transfer & encoding/decoding costs. `GlobalKey` also does not have a version so to seralize it properly you need to query the engine for the version of the corresponding template.

There are a few places where we currently use `GlobalKey`:
1. `Engine.submit` expects a contract key in `ExerciseByKey` commands. Those commands come from the ledger API so they will always have a value even with the changes here.
2. LF transactions in various nodes. We could drop it there.
3. Commands passed to `reinterpret`. These have to match up with the transactions since they are built from transaction nodes so either drop it in both or drop it in none.
4. `PartialTransaction`s `keys` and `globalKeyInputs` fields. For submission we could always have a value here and probably want one for error reporting For validation, we cannot get values for keys coming from root commands but for everything else. So in the end, the key value has to be optional.
5. Speedy/Engine errors: Those should have values during submission & in the scenario service. Those should have values during submission and in the scenario service. I’d say during validation they must at least have the key hash.
6. Validation errors: In KVUtils that’s `InconsistentKeys` which does not currently include the actual key that was inconsistent so it wouldn’t be directly affected.

So in summary with this proposal we make the value optional everywhere except for `Transaction` (ofc only for new versions) and potentially reinterpret commands which do not have a value. We always track the key everywhere.

From an implementation pov I don’t see big issues here. My primary concern is around validation errors. I’m less concerned about the malicious submitter case that causes an error in speedy and more concerned about the `InconsistentKeys` errors. As mentioned above, currently we do not expose the key so this is not an issue. However, if we drop the value we block ourselves from changing this in the future. We had a bug very recently where one of our customers ran into this and even with our help, it was extremely hard to track down what was actually racy. Having the key in the error message would have been very helpful there. I think we should make a very deliberate decision on whether we accept the lack of key values in those errors and if so, if we want to have some separate mechanism of going from key hash -> key value, e.g., a ledger API endpoint.

**Comment by cocreature** [comment]
@andreaslochbihler-da How does canton currently report `InconsistentKeys` errors? Do you include the key value, key hash or nothing like kvutils? And is including the key value fine? My understanding is that we do not leak anything by showing the key that we had a mismatch on (but we could leak something if we show the contracts the key is assigned to). Am I missing something?

And assuming showing the key value is fine, do you think the concern about being able to identify which key was racy is valid?

**Comment by remyhaemmerle-da** [comment]
I do not think 2 is right. 
We do not use `GlobalKey`  in Node we use `KeyWithMaintainer` wich do not contains the hash but the value. 
We could still use GlobalKey instead the Value, though.

**Comment by andreaslochbihler-da** [comment]
> @andreaslochbihler-da How does canton currently report `InconsistentKeys` errors?

Consistency issues around keys are reported as a `ConsistencyRejection` where the Canton error code gives more details about the type of errors (inactive contract, already assigned key, ...). The error message also includes the pretty-printed `GlobalKey`s for which the contract was found. Pretty-printing shows the template ID and a shortened hex of the key hash. Canton doesn't pretty-print the key value.

> And is including the key value fine? My understanding is that we do not leak anything by showing the key that we had a mismatch on (but we could leak something if we show the contracts the key is assigned to). Am I missing something?

A key inconsistency leads to a rejection and that should reported only back to the submitting party, so we only have to worry about leaking anything to the submitting party. However, the submitting party can invert the hash to a value using their background knowledge (all contracts they have ever seen). We would leak something if we were to reveal the conflicting contract ID though (e.g. if the submitter is not a stakeholder of the conflicting contract).

> And assuming showing the key value is fine, do you think the concern about being able to identify which key was racy is valid?

It certainly helps with debugging. Adding an inversion endpoint for hash->value option sounds like a reasonable idea, but we must be aware that such an inversion isn't simple in all cases (e.g., if the participant hasn't seen a contract with the key).

**Comment by andreaslochbihler-da** [comment]
> We do not use `GlobalKey` in Node we use `KeyWithMaintainer` wich do not contains the hash but the value.

That's probably one of the difficult parts. In a `LookupByKey` node that doesn't find a contract, you can't construct a `KeyWithMaintainer` value for the node because Daml engine doesn't know the key value if we only pass in the hash to `reinterpret`.

> We could still use GlobalKey instead the Value, though.

Do you mean that we get rid of `KeyWithMaintainer` and replace it with `GlobalKey`?


For `resubmit`, we probably want to pass in the following information:
* contract key hash
* template ID
* the set of maintainers (for the authorization check)

This however means that Daml engine can't verify that the set of maintainers is correct for the key, which is something we currently rely on in Canton (FYI @oliverse-da). We'll need to think more how to avoid this problem.

**Comment by remyhaemmerle-da** [comment]
> Do you mean that we get rid of KeyWithMaintainer and replace it with GlobalKey?
I was meaning to have a `GlobalKeyWithMaintainer` instead. 

It just a though. 

My current plan is: 
1. Drop the value from the `GlobalKey`
2. Create a special version of reinterpret that work with hash instead of value for key.


Dropping Key value form the transaction nodes is a much more complicate story, so I would like we focus on the two points above first.

**Comment by andreaslochbihler-da** [comment]
>     2. Create a special version of reinterpret that work with hash instead of value for key.

As I wrote above, you probably need the set of maintainers in addition to the hash of the key so that you can check the autorization? So if you change that, the new version of reinterpret will provide weaker guarantees than the current version (no check that the given maintainers are actually the maintainers of the key). Is that right?

**Comment by remyhaemmerle-da** [comment]
I  mean dropping **only** the value of the key in reinterpret. If we need the maintainers we I dot not plan to remove them.

**Comment by cocreature** [comment]
> Dropping Key value form the transaction nodes is a much more complicate story, so I would like we focus on the two points above first.

I don’t think you can treat the value in `reinterpret` separately from the value in transactions:
1. If you drop it from `reinterpret`, speedy cannot produce a transaction containing the key value since it doesn’t have access to it.
2. If you drop it from transactions, users like Canton cannot construct a command containing the key value.

So you really have to drop it in both or neither.

**Comment by remyhaemmerle-da** [comment]
> 1. If you drop it from reinterpret, speedy cannot produce a transaction containing the key value since it doesn’t have access to it.
Yes, for failing lookup by Key.

**Comment by cocreature** [comment]
We decided to not pursue this for now. It adds a fair amount of complexity and can make error messages worse and in the end it doesn’t seem to solve all that much.
