### ISSUE TITLE
IllegalStateException: "Transaction in ACS" w/ in-memory JSON API

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#10161]
Retrieving the set of active contracts for a given query when using the in-memory JSON API could end up triggering a sporadic `IllegalStateException` to be thrown with the message `"Transaction in the ACS"`.

**Comment by stefanobaghino-da** [comment]
This is likely caused by the `conflation` flow which is invoked when filtering and converting results coming from the ACS query to match the JSON API query. It ultimately calls the `append` method on `ContractStreamStep`, which can cause the `Acs` and `LiveBegin` objects to be merged in a `Txs`, which raises the exception.

The most straightforward solution is to _expect_ a `Txs` there and act accordingly.

Relevant call stack:

`getTransactionSourceForParty` (`fetchAndPrefilterAcs` called on line 637, exception thrown on line 668): https://github.com/digital-asset/daml/blob/a304650169bec1e73db0cc9df1f7c07d04d578f8/ledger-service/http-json/src/main/scala/com/digitalasset/http/WebSocketService.scala#L633-L669

`fetchAndPrefilterAcs` (`convertFilterContracts` called on line 601): https://github.com/digital-asset/daml/blob/a304650169bec1e73db0cc9df1f7c07d04d578f8/ledger-service/http-json/src/main/scala/com/digitalasset/http/WebSocketService.scala#L574-L603

`convertFilterContracts` (`conflation` called on line 797): https://github.com/digital-asset/daml/blob/a304650169bec1e73db0cc9df1f7c07d04d578f8/ledger-service/http-json/src/main/scala/com/digitalasset/http/WebSocketService.scala#L772-L798

`conflation` (`append` called on line 153): https://github.com/digital-asset/daml/blob/a304650169bec1e73db0cc9df1f7c07d04d578f8/ledger-service/http-json/src/main/scala/com/digitalasset/http/WebSocketService.scala#L140-L154

`append` (root cause on lines 27-28): https://github.com/digital-asset/daml/blob/a304650169bec1e73db0cc9df1f7c07d04d578f8/ledger-service/http-json/src/main/scala/com/digitalasset/http/util/ContractStreamStep.scala#L24-L42

**Comment by stefanobaghino-da** [comment]
I'm also wondering if the `conflation` of anything apart from two `Txs` objects should be allowed.

**Comment by stefanobaghino-da** [comment]
I suspect that by splitting the live and non-live messages this issue could be solved at the source.

**Comment by stefanobaghino-da** [comment]
From what I can read, it appears that the React bindings do not expect this guarantee (no `else` separating the conditions): https://github.com/digital-asset/daml/blob/65dfba44c976b1680272fc083eb517cd49ad6301/language-support/ts/daml-ledger/index.ts#L679-L691

I'll be pushing a fix shortly, thanks for the feedback.

**Comment by garyverhaegen-da** [comment]
That does seem to mean we could get a `change` event _before_ the first `live` event though. Should we swap the two if statements, so that at the user level we always get the `live` event first? I'm not entirely sure whether that's a _guarantee_ at the moment, but it does seem like a natural expectation people might have, and that one would be in the users' code.

**Comment by S11001001** [comment]
@garyverhaegen-da I think that would violate the intentions of the live event. It's supposed to arrive when you're "done loading", not when you're almost done loading but there's just one more block.

**Comment by garyverhaegen-da** [comment]
🤔 It's been some time since I last looked at the binding, but I understood it as "connection established", not "done loading". I suppose I must have been confused.

**Comment by stefanobaghino-da** [comment]
>  It's been some time since I last looked at the binding, but I understood it as "connection established", not "done loading". I suppose I must have been confused.

Probably "all the events coming from the ACS have been transmitted" is a more verbose but more telling way to see it. 🙂
