### ISSUE TITLE
Install script for windows SDK

### ISSUE THREAD

**Issue by ashfaq-shaik** [digital-asset/daml#1030]
DAML's windows SDK archive consists of a shell script `install.sh`

I would suggest adding `install.bat` with below code

`%cd%/daml/daml install %cd% --activate`

This is the windows equivalent of 'install.sh'

**Comment by cocreature** [comment]
Hi! For Windows, we recommend that you use the installer https://github.com/digital-asset/daml/releases/download/v0.12.16/daml-sdk-0.12.16-windows.exe

**Comment by ashfaq-shaik** [comment]
@cocreature 

Thanks for the response

I tried installing with this installer, but it ends up asking for elevated privileges on Windows 10. So I preferred to use the archive directly, as I assume the installer only copies files to certain locations

**Comment by cocreature** [comment]
Sounds reasonable, do you want to make a PR that adds `install.bat`? If not, I’ll take care of it myself.

**Comment by ashfaq-shaik** [comment]
Created PR for this. https://github.com/digital-asset/daml/pull/1032

**Comment by cocreature** [comment]
Fixed by #1032, thanks again @ashfaq-shaik! We also changed the installer so that in future releases it will no longer require elevated privileges.
