### ISSUE TITLE
Windows: 'daml version' fails when not connected to the internet

### ISSUE THREAD

**Issue by ashfaq-shaik** [digital-asset/daml#1031]
**Context**: Running daml SDK on windows and having no network connectivity. 

**Issue**: Executing `daml version` results in an error

`C:\Users\shaika>daml version`
`daml.exe: HostCannotConnect "github.com" [Network.Socket.connect: <socket: 740>: failed (Connection timed out (WSAETIMEDOUT))]`

- daml cli tries to call home for a version check and fails on a network timeout. 
- This should not be treated as an error and should fall back to `warn` 
- cli should output current installed version

**Comment by associahedron** [comment]
Thanks for the bug report! Agree it's a bug, working on a fix now.

**Comment by associahedron** [comment]
The PR #1038 fixes this bug. This will be in the next release.

**Comment by ashfaq-shaik** [comment]
Thank @associahedron
