### ISSUE TITLE
Limit length of template ids

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10358]
Currently, Daml-LF imposes no limit on template ids, i.e., the 3 tuple (package id, modulename, entity name).

In practice, package ids are and have always been sha256sums and therefore limited to 64 characters so we could add that restriction in daml-lf without much trouble.

Module names and entity names are more tricky. When running on PostgreSQL, I believe both the JSON API and the participant ill actually support fairly arbitrary lengths.

However, on Oracle the situation is a bit different: Oracle doesn’t like arbitrary length strings so we add a bunch of random limits.

For the participant that limit is 4000 characters for the whole template id in the format `pkgid:module:entity` which is just the max string lenght on Oracle by default. For the JSON API, we have a limit of 1562 characters on the module name and on the entity name (separately) and a 64 char limit on the package id. The reason for that limit is that we have a `unique (pkgid, module, entity)` constraint and Oracle has a max size restriction on the things contributing to indices and constraints.

My suggestion would be to limit module name and entity name (including choice names and other identifiers) to length 1000 each (as a somewhat understandable length as opposed to 1562 and to have a bit of leeway) and enforce this in daml-lf.

The big question here is backwards compatibility. There are two options I see:

1. Restrict this for older lf versions as well. This will break a ledger that already has such templates. I think that’s highly unlikely but it is possible. There would also be no remedy in this case. You cannot prune packages so there is no solution like upgrading on the old ledger to something with shorter names.
2. Restrict this only for newer lf versions. In that case, a ledger running on Oracle should probably forbid old lf versions.

I have a slight preference for 1 since I think the risk is acceptable but ymmv.

cc @gerolf-da @vivd-da @bame-da @remyhaemmerle-da @sormeter

**Comment by S11001001** [comment]
In terms of string length, 1024 is no less arbitrary than 1562. We can put an end to this glorious/ignominious programming tradition right now.

Leeway is fine, but 538?

I would prefer (2) by the way.

**Comment by cocreature** [comment]
I don’t really care what we choose, we can also go with 1k or something else. I’ll take something that’s reasonably easy to remember over "whatever weird limit Oracle came up with" Powers of 2 or powers of ten seem like a nice choice in that regard so 1k, 1024 or maybe 1500 would all be reasonable.

**Comment by remyhaemmerle-da** [comment]
Note that to store a string of 1024 character you will need at least 1 bytes more (for the final '\0' if you encode using C convention). 
If you encode using java/protobuf convention you will need 4 bytes more to store the length. 
So 1020 is probably better :zany_face:

**Comment by cocreature** [comment]
In that case, maybe just 1k or something :)

**Comment by cocreature** [comment]
Thinking about it more, 2 does allow for migration in the following form:

1. You start with a package over the length limits in LF 1.14 on a Postgres based ledger.
2. You upgrade to a ledger with support for LF 1.15 which has the length restriction.
3. You write a migration to LF 1.15 models with shorter names.
4. At that point you could migrate to a ledger which only supports LF 1.15.

I’m somewhat warming up to option 2 even though I still prefer 1.

**Comment by remyhaemmerle-da** [comment]
I definitively prefer 1.

**Comment by cocreature** [comment]
There is also a question of how far we want to extend this. We clearly need module names and we need template names. Do we want to restrict all daml-lf entity names or just temlates? Doing it consistently seems easier but also more potential for breakage.
