### ISSUE TITLE
Mirroring SDK releases.

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#1035]
We should try to get SDK releases mirrored somewhere so we don't have to download them from GitHub every time e.g. when GitHub is down or slow.

(cc @garyverhaegen-da )

**Comment by neil-da** [comment]
I think we should dive a bit deeper. Why was it so slow to download from one location? Do we really need tolerance for github going down?

**Comment by dasormeter** [comment]
This is a challenge whatever we choose as the distribution mechanism (github or other website, maven central, bintray, brew, hackage, npm central, artifactory, etc) -- all have had reliability problems at various times over the last two years and i don't think any one of them will ever be 100% available.

What is our desired SLA?  Will it suffice to have a fallback mechanism that can be invoked manually?

**Comment by neil-da** [comment]
Our SLA is up to us - no commitments for something open source and free. I think GitHub is probably just fine. I'm also thinking that for measuring download counts having fewer locations makes it easier to aggregate, so GitHub alone is attractive in that sense.

**Comment by circlespainter** [comment]
Any plans to reduce the size of the SDK and/or to modularize it or to introduce a package management system? Bandwidth has greatly improved these days but still, 650+ MB is not such a small download.

**Comment by associahedron** [comment]
Hi @circlespainter, thanks for the question. We just reduced the size to about 210 MB by doing some deduplication of dependencies. (See #3678)

**Comment by hurryabit** [comment]
@cocreature @garyverhaegen-da Do we have any plans for this in the near future? Do we have an idea how urgent it is at all?

**Comment by cocreature** [comment]
No concrete plans atm. It does come up occasionally when github is down or slow for someone but so far it hasn’t seemed all that urgent to address.

**Comment by garyverhaegen-da** [comment]
The main blocker so far has been the desire to track download counts, which makes it a lot harder to add mirrors, especially the good kind with CDNs and caches and the like.

**Comment by garyverhaegen-da** [comment]
As a data point, I just installed the latest snapshot:
```
$ time daml install 1.6.0-snapshot.20200908.5166.0.1623baec
Installing SDK version 1.6.0-snapshot.20200908.5166.0.1623baec
Downloading SDK release.
[======================================================================================================================================================] 100%
daml install 1.6.0-snapshot.20200908.5166.0.1623baec  20.60s user 8.02s system 3% cpu 14:31.96 total
$ 
```
I think we should try to do better.

**Comment by stefanobaghino-da** [comment]
@garyverhaegen-da I just assigned this to you, do with this whatever you think it makes sense.

**Comment by garyverhaegen-da** [comment]
As far as I'm aware it's still a requirement from product (cc @bame-da) that all of the artifacts be downloaded from GitHub and only GitHub. As long as that doesn't change, I don't know how we could make any progress on this.

**Comment by garyverhaegen-da** [comment]
I should add that, from my personal, anecdotal evidence, GitHub downloads have become a lot more reliable and a lot faster than when this issue was first opened, despite the size of the SDK skyrocketing in the meantime. I feel a lot less pressure to "solve" this these days.
