### ISSUE TITLE
JSON API schema: table prefixes (or suffixes)

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#10390]
The JSON API is designed for running behind a load balancer (with a sticky bit on user credentials). It is also designed to have a per-instance db-backed cache.

This creates a situation where an operator might want to start N instances of the JSON API behind a load balancer. Currently, this would require said operator to supply a different JDBC URL to each JSON API instance to make them point to, at the very least, separate logical DBs (PostgreSQL schemas). This makes scaling unnecessarily difficult.

In order to work around that, I think we should have a CLI argument to the JSON API that sets a prefix (or suffix, or infix) on all table names. This would effectively namespace each JSON API instance, and make it possible to run multiple JSON API instances against the same logical DB, using the same set of credentials.

If the CLI flag is not set, its value should be generated randomly at startup (a slowdown at startup seems a better default than accidentally ending up with multiple JSON API instances writing on the same tables).

**Comment by cocreature** [comment]
We should make sure that we do this somewhat consistently with how the ledger API server handles this.

**Comment by garyverhaegen-da** [comment]
For future reference I'd like to note that this ticket was written under the apparently-false assumption that multiple JSON API instances need separate sets of tables. I did not check that assumption.

@S11001001 pointed out that the JSON API is indeed designed such that multiple instances _can_ connect to the same database and use the same set of tables without any issue.
