### ISSUE TITLE
add Map to DAML-LF 

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#104]
we wanted to add `Map`s to DAML-LF for a long time. now we're ready!

the proposal is simple, add a `Map` type to DAML-LF, which is an unordered, `Text`-keyed map.

concretely, we'd have

```
Map : * -> *
MAP_EMPTY : forall a. Map a
MAP_INSERT : forall a.  Text -> a -> Map a -> Map a
MAP_LOOKUP : forall a. Text -> Map a -> Optional a
MAP_DELETE : forall a. Text -> Map a -> Map a
MAP_TO_LIST: ∀ α. Map α → List ⟨key: Text, value: α⟩
MAP_SIZE : forall a. Map a -> Int64
```

**Comment by martin-drhu-da** [comment]
Map is in DAML-LF now. The exposure in surface is tracked in https://github.com/digital-asset/daml/issues/409.
