### ISSUE TITLE
Next steps in the GSG

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10419]
Currently the GSG leaves people a bit on their own when it comes to what they should do next. Instead we should provide concrete suggestions, specifically the proposal is the following:

1. Move the "testing your app" somewhere to "building applications" and make it clear that this is only about doing e2e webui tests.
2. Provide 4 possible next steps (order and title/description to be determined)
    1. Deploying your app to Daml Hub linking to a section that still needs to be created
    2. Model automation/triggers linking to the current daml triggers section
    3. Model testing/daml script linking to the current daml script section
    4. In-depth Daml language intro linking to the existing section
3. The Daml script section will be changed to build upon the model in the getting started guide. Potential additional information that doesn’t quite fit but shouldn’t be lost can go in a subsection or at the end.
4. The Daml trigger section will be changed to build upon the model in the getting started guide. Potential additional information that doesn’t quite fit but shouldn’t be lost can go in a subsection or at the end.

The connect engineering teams will start with 1,3 and 4. We’ll do 2 together with @nemanja-da and team once he is back from vacation.

**Comment by garyverhaegen-da** [comment]
Any news on this? 1 and 4 are done (resp. #10479 & #10509), and I don't think I'm the best person to address 3, but could give it a shot if we still think it needs to be done.

@nemanja-da any progress on 2? Do we still need/want to do any of this, or are we happy with the current state?

**Comment by nemanja-da** [comment]
@garyverhaegen-da would wait with writing 2. as we're merging the docs and getting-started with Canton as part of the next steps might also make sense. I'm not sure to what extent things are clear when it comes to how that will play out (Canton<->Daml docs integration) and that's why I'm suggesting that we wait a bit. 

cc: @davidrichards-da @carrielaben-da

**Comment by davidrichards-da** [comment]
I agree with Nemanja to wait.  There's a broader work stream going on to tackle the docs generally so I wouldn't want any work wasted.  @carrielaben-da, you should consider these next steps for the getting started guide in any docs changes that are considered.

**Comment by garyverhaegen-da** [comment]
This doesn't seem to be planned anymore. @carrielaben-da please reopen if I'm wrong.
