### ISSUE TITLE
daml ledger export: dalf version range 

### ISSUE THREAD

**Issue by maxdeliso-da** [digital-asset/daml#10435]
Testing the ledger export tool, I've noticed that no `--package` line is included in the build options of the export project, for daml lf version 1.6.

For instance:

```
$ daml damlc inspect deps/5a0b927351495179521a6f637142d9fb77eb78a701734e980ab8fb21e0fc531d.dalf | head
package 5a0b927351495179521a6f637142d9fb77eb78a701734e980ab8fb21e0fc531d
daml-lf 1.6

module Chess where
record @serializable AcceptDraw = {game : ContractId Chess:Game}
record @serializable DrawProposal =
  {gameId : Types:GameId; proposer : Party}
record @serializable Forfeit = {}
record @serializable ClaimDraw = {}
record @serializable Move = {move : Types:ChessMove}
```

Exporting a ledger that contains contracts with this lf version results in build failures of the export project due to the package being hidden:

```
$ daml build
Compiling export to a DAR.
File:     Export.daml
Hidden:   no
Range:    6:18-6:23
Source:   not found
Severity: DsError
Message: 
  Could not load module 'Chess'
  It is a member of the hidden package
  '5a0b927351495179521a6f637142d9fb77eb78a701734e980ab8fb21e0fc531d'.
  You can run ':set -package 5a0b927351495179521a6f637142d9fb77eb78a701734e980ab8fb21e0fc531d' to
  expose it.
  (Note: this unloads all the modules in the current scope.)
```

These issues do not recur for newer lf versions, where a metadata key is added to the dalf file that identifies the package.

This issue is to ask for clarification on what range of daml lf versions is expected to be exportable using the tool.

**Comment by cocreature** [comment]
@aherrmann-da Any idea how hard it would be to support older LF versions? Either way, we should at least provide a better error message.

**Comment by aherrmann-da** [comment]
@cocreature I think in cases where a package has no metadata we could add flags of the form `--package=5a0b927351495179521a6f637142d9fb77eb78a701734e980ab8fb21e0fc531d` to `daml.yaml` instead.
