### ISSUE TITLE
Data Bounds Incorrectly Designated (9999-99-99)

### ISSUE THREAD

**Issue by quid-agis** [digital-asset/daml#10449]
In the DA_SDK.pdf, page 259/577:

#### 3.3.1.7 Date

> The dates must be between the bounds specified by Daml-LF and ISO 8601, [0001-01-01, 9999-99-99].

Shouldn't this be:

> The dates must be between the bounds specified by Daml-LF and ISO 8601, [0001-01-01, 9999-12-31].

Or is this only a Numerical format, and that the implied use would correctly be 9999-12-31?

**Comment by realvictorprm** [comment]
I think you're right as the format here seems to be `JJJJ-MM-TT`. Good catch :smile:

**Comment by quid-agis** [comment]
> I think you're right as the format here seems to be `JJJJ-MM-TT`. Good catch smile

Took me a bit to work out that `JJJJ-MM-TT` is the German equivalent of `YYYY-MM-DD` :de: :+1:

**Comment by garyverhaegen-da** [comment]
Not fixed yet; we tend to keep issues open until they're fixed (or we decide not to fix them).
