### ISSUE TITLE
Docs for manual install and GPG server are outdated

### ISSUE THREAD

**Issue by nycnewman** [digital-asset/daml#10448]
Docs reference a soon to be deprecated GPG server: https://docs.daml.com/getting-started/manual-download.html

Need to switch to https://keys.openpgp.org

**Comment by realvictorprm** [comment]
The server doesn't seem to be reachable from Europe anymore, just tried it.
From what I see here, it has already been taken down (well, the DNS records at least)?

![image](https://user-images.githubusercontent.com/25414896/127827774-366e476a-ab51-4205-b9da-267e0e2f28e2.png)
