### ISSUE TITLE
add enum types to DAML-LF

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#105]
variants are kinda icky in many situations. i propose we add a new datatype definition along with `record` and `variant`, `enum`:

```
enum T = V_1 | ... | V_n
```

which carves out explicitly variants with no arguments. this is worth doing because we can encode as strings, which is _a lot_ more compact and intuitive both on the ledger API and in json etc.

**Comment by remyhaemmerle-da** [comment]
The plan is as follow: 

- [ ] add enum type in to daml-lf 1.dev (proto / engine / values )
- [ ] compiler generate enum-type
- [ ] java codegen support
- [ ] scala codegen support
- [ ] support for js binding
- [ ] sandbox support  
- [ ] extractor support
- [ ] navigator support
- [ ] update spec
- [ ] bump version
