### ISSUE TITLE
dlik: include a direct link to the DAML Integration Kit in docs.daml.com

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#1056]
@clasoncjDA mentioned that he'd like the DAML Integration Kit to be more prominently reachable; and ideally not being hidden behind a big fat warning sign. We want to encourage third-parties to integrate DAML into their ledgers.

This requires input from @bethaitman on how to do this best.

**Comment by bethaitman** [comment]
Addressing in #1101.
