### ISSUE TITLE
Semantic tests using DAML scenarios

### ISSUE THREAD

**Issue by timw-da** [digital-asset/daml#107]
The current SemanticTests.daml contains only a few scenarios and should be expanded to cover a much greater range of our semantics:

- [x] Consistency - for a transaction, internal consistency rules 1 and 2
- [x] Authorization - for a commit, authorization rules 1 and 2
- [x] Privacy - test projections
- [x] Divulgence

Note that DAML model conformance and fuzz tests will likely need a separate suite of tests.

**Comment by meiersi-da** [comment]
This is done.
