### ISSUE TITLE
Propagate typeclass instances in data-dependencies

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10773]
In Haskell (and Daml) typeclass instances are transitively propagated throughout all imports.
However, `data-dependencies` currently only reconstruct the minimal set of imports required to get things to typecheck meaning that they lose information on what instances where available.
We should store the modules that were imported and reconstruct imports for that in `data-dependencies` to make sure that this doesn’t break code.
Note that this only matters for orphan instances but unfortunately people use those.

**Comment by akrmn** [comment]
Hi @cocreature, I'll share my findings so far:

This task can be split in three parts:
1. Encoding/decoding the set of required imports, this code will live at `DA.Daml.LFConversion.MetadataEncoding`. 
    - This is fairly simple given the existing helper functions for encoding/decoding similar information to types.
2. Picking up the encoded set of imports in `DA.Daml.Compiler.DataDependencies` and adding it to the `hsmodImports` field in `generateSrcFromLf`
    - Also simple, especially given the existing `modRefImport` function.
3. Generating the encoded imports in `DA.Daml.LFConversion.convertModule`
    - This is where it gets complicated, in particular getting the instances in scope at the module being processed. So far, I've tried:
      - `md_insts` field of `details :: ModDetails` argument: only includes instances defined _in the current module_.
      - `md_exports` field of `details :: ModDetails` argument: this includes functions, datatypes and classes, but not instances.
      - I also tried adding a parameter `visibleInstances :: [ClsInst]` to `convertModule`, and providing it as the result of calling [`hptInstances`](https://hackage.haskell.org/package/ghc-8.10.2/docs/HscTypes.html#v:hptInstances) on the available `hsc :: HscEnv`. Note that one of the callsites of `convertModule`, `generateRawDalfRule`, didn't have an available `hsc`, so I added a line 
      
        ```haskell
        hsc <- hscEnv <$> use_ GhcSession file
        ```
        However, on running this the value of `visibleInstances` turned out to be an empty list. I added some trace lines and noticed that the callstack goes through `generateRawDalfRule`, so perhaps just adding the `hsc` line isn't enough. The docstring for `generateRawDalfRule`, 

        ```haskell
        -- Generates the DALF for a module without adding serializability information
        -- or type checking it.
        ```
        makes me think that this is somewhat intentional, and that `generateRawDalfRule` shouldn't perform too much work, but I'm not sure how to reconcile that with what we need.
   -  I believe you also suggested using the `mg_inst_env` field of `ModGuts`, but I haven't been able to get my hands on a `ModGuts` value.
