### ISSUE TITLE
Missing definition  exception after Archive choice from skeleton quickstart

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#1090]
Steps to Reproduce

daml new quickstart skeleton
daml start

Open web browser to http://localhost:7500/contracts/, choose Alice
Go to Contracts tab, choose the one active contract, choose the Archive action

In the console Navigator log you will see an error appear such as 

```
missing definition: Identifier(414ec854f633d4c4d3bf60c2ec944c7b2f424c33b1e5b9b9898f04e539f1a260,Main:Asset.$Archive)
reloaded packages
```
From a cursory look this seems to be coming from this line of code in daml-lf interpreter
https://github.com/digital-asset/daml/blob/63960bfa85b83054d66d4f412416d740587b2824/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Speedy.scala#L103-L123

**Comment by hurryabit** [comment]
It looks like the contract gets archived properly. My understanding is that the message is not an error but a debug message triggered by the fact that sandbox loads packages lazily. @bitonic can you confirm this?

**Comment by bitonic** [comment]
this looks like stale debugging output. i'll remove it. thanks for the report.

**Comment by stefanobaghino-da** [comment]
@dasormeter is this still a valid ticket?

**Comment by cocreature** [comment]
Closing this has been fixed
