### ISSUE TITLE
Consider preserving "fetched by interface" info in Fetch and Exercise nodes

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10915]

**Comment by sofiafaro-da** [comment]
If we only have fixed choices, the choice name implies already whether something was exercised by interface. (If it's a fixed choice, it's always exercised by interface. Otherwise, it is a template-specific choice.)

**Comment by cocreature** [comment]
As discussed, while you’re completely right preserving the information means we can make the distiniction locally rather than having to look in the package which generally fits in well with how we handle other things like LF versions so we should follow that approach here.

**Comment by sofiafaro-da** [comment]
We can also add `by_interface` in create nodes. I'm not sure that it's required for validation (even taking projections into account) but it might be good to keep track of it anyway.

**Comment by cocreature** [comment]
I’m in favor of storing it there as well. I don’t think we need it for validation but better store more than less.
