### ISSUE TITLE
Test coverage for Daml interfaces

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10917]
- [ ] #11698
- [x] Scala Daml-LF decoder unit tests
- [x] Scala Daml-LF parser implement & add test
- [x] Scala Daml-LF encoder implement & add test
- [ ] Maybe tests at the speedy level
- [ ] #13332
- [x] Tests for engine preprocessor
- [x] Tests for `by_interface` in the transaction coder.
- [ ] #13333
- [ ] #13334
- [ ] #13335
- [x] Test Typing of requires fields (in particular for check errors `EMissingRequiredInterface`, `EWrongInterfaceRequirement`, `ENotClosedInterfaceRequires`).

**Comment by sofiafaro-da** [comment]
Closing this issue in favor of all the smaller ones.
