### ISSUE TITLE
Unexpected message when running daml navigator for skeleton sample project

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#1091]
Run `daml new quickstart skeleton` to create a new project.
cd to that quickstart directory and run
`daml navigator -- server localhost 6865 --port 7500         `                                                                                                                                                               

Displays error: `No configuration file found! A configuration template file will be created at ui-backend.conf, please edit it and restart Navigator`

**Comment by hurryabit** [comment]
@associahedron @bethaitman @rautenrieth-da Where do we want to fix this issue, in the navigator or in the quick start template?

**Comment by bethaitman** [comment]
That's interesting, I didn't know that file was required. What does it do? If we definitely need it, then it should be added to the skeleton template; if it's legacy, then maybe we can move away from it.

**Comment by associahedron** [comment]
> @associahedron @bethaitman @rautenrieth-da Where do we want to fix this issue, in the navigator or in the quick start template?

This is not related to the quickstart template, but the skeleton template.

We should remove the ui-backend.conf requirement -- navigator should read daml.yaml directly.

**Comment by cocreature** [comment]
Depending on when @rautenrieth-da is able to add this to navigator, we could use the logic that we already have in `daml-helper` for generating this file in `daml start` and add it to `daml navigator` to fix this issue in the short term.

**Comment by associahedron** [comment]
Sounds like a good temporary workaround @cocreature

**Comment by associahedron** [comment]
Went with adding ui-backend.conf to the skeleton template instead of convoluting the navigator logic in daml-helper.

**Comment by rautenrieth-da** [comment]
The workaround has been merged, supporting the new SDK Assistant config in Navigator is tracked by #1128 - should we close this issue?

**Comment by cocreature** [comment]
Sounds good :+1:
