### ISSUE TITLE
Make `daml install` not fail if version is already installed.

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#1093]
Often you just want to make sure that a given version is installed without relying on which versions are already installed. `daml install` will currently fail if the version is already installed so you need to be careful to only run it for versions that are not already installed. You can run `daml install --force` but that needlessly reinstalls the SDK. We should have a `daml install --ensure` flag that will succeed if the given version is already installed and installed it otherwise.

cc @associahedron @stefanobaghino-da

**Comment by neil-da** [comment]
Why not just make `daml install` always operate like it is passed the `ensure` flag? Just because the installation is a no op, doesn't mean it should fail. When would someone want the no-ensure behaviour?

**Comment by cocreature** [comment]
Sounds like a good idea to me but I’d like @associahedron to weigh in given that he implemented the current behavior.

**Comment by associahedron** [comment]
That seems like a better default than the current behavior. I'll go ahead and change it.
