### ISSUE TITLE
daml command to list available versions.

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#1094]
It would be nice if there was an easy way to list the available versions in the assistant, e.g., `daml list --available`.

**Comment by cocreature** [comment]
cc @associahedron @stefanobaghino-da

**Comment by associahedron** [comment]
As discussed, a functionality like this would require hosting a list of releases ourselves. That seems like a very useful thing to have, so i'll open an issue, but it goes beyond changing the assistant.

I'd also like to mention that I'm not planning to add a `daml list` command, but to change the default behavior of `daml version`. This could be `daml version --all` or something.

**Comment by neil-da** [comment]
I'm not convinced this feature is useful. Given weekly releases we'll have 50 by the end of the year - I don't see much value in that. Also, why do people want a list? So they can iterate through versions? Why? And the cost of hosting such a list seems more than I want to bear, for little value.
