### ISSUE TITLE
Make wall clock time default in Trigger service

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#10957]
Trigger service defaults to _static time_ while Sandbox defaults to _wall clock time_. This behavior can cause configuration troubles for a user who intuitively would expect consistent default time.

Repro:
```
$ daml trigger-service --help | grep "static time"
  -w, --wall-clock-time    Use wall clock time (UTC). When not provided, static time is used.
$ daml sandbox --help | grep "static time"
  -s, --static-time        Use static time. When not specified, wall-clock-time is used.
```

**Comment by cocreature** [comment]
I’ve discussed it with @bame-da. He’s perfectly fine with making this a breaking change. The fact that it defaulted to static time was a mistake, I didn’t even realize that was the default.

**Comment by stefanobaghino-da** [comment]
I was about to ask him actually, thanks for stepping in. I think I can take care of this myself.
