### ISSUE TITLE
Host a regularly updated list of SDK releases.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1097]
SDK release data is only generally available through the github API which has strict rate limits. To allow users and developers to get a list of available versions (see #1094) we should host a list of SDK versions somewhere that gets updated regularly.

There is also some use to capturing metrics (dowload_count field for each release artifact) along with the version numbers.

These are all obtained from the same GitHub API calls, so it seems like a script that runs regularly and puts this data in a `versions` file on a server somewhere would be enough.

cc @cocreature  @gaverhae  @bame-da

**Comment by neil-da** [comment]
Unconvinced the benefit is worth the cost...

**Comment by garyverhaegen-da** [comment]
The docs drop-down is going to rely on a JSON file of the form:
```json
{"version string to display": "docs path prefix", ...}
```
hosted at `docs.daml.com/versions.json`.

I don't think it'd be crazy to say the version path should be `/<version>` (and that should probably also be the version name), so the assistant could rely on that same file?

**Comment by associahedron** [comment]
That sounds reasonable.

**Comment by associahedron** [comment]
@garyverhaegen-da With #1116 and once #1126 passes, this versions.json will become available? Thanks :-)

**Comment by garyverhaegen-da** [comment]
It's now generated and kept up to date every hour, but I still need to get the DNS changed.

**Comment by associahedron** [comment]
This is done! https://docs.daml.com/versions.json
