### ISSUE TITLE
daml-assistant: thin daml assistant.

### ISSUE THREAD

**Issue by fmota-da** [digital-asset/daml#11]
We're moving toward a new assistant called `daml`, instead of `da`, that redirects commands in the style of `git`. Each sdk version release will ship with a set of tools, called `daml-compile`, `daml-upgrade`, `daml-doctor`, `daml-uninstall`, etc. When the user invokes the `daml` command, for example `daml compile Foo.daml`, the assistant will find the appropriate version of the `daml-compile` tool and invoke that with the argument `Foo.daml`.

There will be a `.daml` folder in the user home folder on unix, and appropriate location on Windows. The `.daml` directory will look like:

```
.daml/
  |- config.yaml
  |- sdk/
       |- 0.12.1/
            |- bin/
                 |- daml
                 |- daml-compile
                 |- daml-upgrade
                 |- ...
            |- ...
       |- 0.12.0/
            |- bin/
                 |- daml
                 |- daml-compile
                 |- daml-upgrade
                 |- ...
            |- ...
```

The `daml` command is only responsible for:

1. Finding the current project by going up the current directory path and finding a `da.yaml` file. 
2. Selecting the appropriate version of the sdk to use (based on `da.yaml`, or latest version if not found).
3. Invoking the appropriate `daml-something` command with the arguments it was given, and with additional environment variables:

    - DAML_HOME = the absolute path of `.daml` folder
    - DAML_PROJECT = the absolute path of the project folder (if it exists)
    - DAML_SDK = the absolute path of the chosen `sdk` version folder
    - DAML_SDK_VERSION = the version number of the chosen `sdk` version

The invoked `daml-something` tools should read the `$DAML_HOME/config.yaml` and `$DAML_PROJECT/da.yaml` files directly for configuration.

------------

# Packaging and releasing

We want each SDK version be a single tarball (or zip file). The daml tools, and the `daml` assistant itself, will be part of the SDK tarball.

We want to be able to move away from relying on Bintray for distributing the SDK. The latest version of the SDK tarball should be made available through some consistent URL for each platform (e.g. `daml.com/sdk/latest-linux.tar.gz`) that redirects to the latest version.

`$DAML_HOME/config.yaml` will be configured with this URL, and `daml-upgrade` will fetch a new version when it becomes available.

Separately, we will need an installer script for each platform, and to incorporate this installer script with existing software distribution channels (such as `brew` and `apt-get`). Ideally the installer simply downloads the tarball, expands it to the right place, writes a basic `$DAML_HOME/.config.yaml`, puts `daml` in the PATH, and you're good to go.

------------

TBD: 

1. Should there be a `$DAML_HOME/bin` folder? Or should `daml` be installed somewhere in the PATH? Or something else? Or both?

2. Should the `$DAML_SDK` directory be readonly?
    - Except for tools that manage SDK versions, such as `daml-upgrade` and `daml-uninstall`, of course.

3. If a `daml-something` tool is invoked directly, without the environment variables above, should the tool attempt to determine the flags itself? Or give an error?

    - Part of the `daml-assistant` project should be a Haskell library that makes it easy to determine these variables if they aren't passed directly, and this is what `daml` will use, so there is uniformity.

4. If YES to 3, and the current tool is from the wrong SDK version for the current project (based on `da.yaml`), should the tool go ahead and silently invoke the appropriately versioned tool instead? Should this be an error? A warning?

**Comment by associahedron** [comment]
This has been released internally. Closing this ticket.
