### ISSUE TITLE
Exception where clause produces warning "Defined but not used: ‘this’"

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#11004]
Daml exceptions with a `where` clause produces warning `Defined but not used: ‘this’`, when warnings are enabled for unused variables.

Reproduce with these two files:
- daml.yaml
```
sdk-version: 1.16.0
name: daml-intro-8
source: daml
version: 1.0.0
dependencies:
  - daml-prim
  - daml-stdlib
build-options:
  - --ghc-option
  - "-Werror -Wall"
```
- daml/Intro/Exceptions.daml
```
module Intro.Exceptions where

import DA.Exception

exception E
  with
    f: Text
  where
    message "E: " <> f
```

**Comment by cocreature** [comment]
thanks, that’s definitely something we should fix although I’d consider it relatively low priority given that the warning is not on by default.

**Comment by richardkapolnai-da** [comment]
> thanks, that’s definitely something we should fix although I’d consider it relatively low priority given that the warning is not on by default.

Sure. I hope we find a workaround to be documented here: https://discuss.daml.com/t/how-to-disable-all-warnings-for-one-file-only/3197

**Comment by dylant-da** [comment]
Checked, this is still an issue, added to backlog

**Comment by samuel-williams-da** [comment]
Disabling the warning on a whole file basis doesn't seem ideal, we could disable the warning for the word "this" across the board, which is a bit better.
Ideally we'd simply not generate the `this@...` for `HasMessage` instances that don't use it, but that requires iterating the AST for the message body, which could get messy (unless something nice for this already exists)
What do you think @dylant-da ?
