### ISSUE TITLE
Nightly SDK releases

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11066]
Mainly to ease our own testing and to make releases a bit smoother in general, we should add fully automated nightly SDK releases. Being fully automated means they also skip manual testing.

The process would roughly work as follows. Each night, an automated job kicks in and runs through the following steps for the latest commit on `main`:

1. Build exactly the artifacts we build for the current weekly releases with the existing name scheme for snapshots.
2. For Maven & NPM upload them to the regular repositories.
3. For the SDK tarball, GH releases gets too noisy since that is still where we direct at least our Windows users to so uploading them to a GCP bucket seems nicer.
4. EE artifacts can keep being uploaded to artifactory.

Each week, we test one of the nightly snapshots manually and as part of that upload it from the GCP bucket to GH releases.

We keep infrastructure for triggering releases manually for arbitrary commits similar if not identical to what we have right now.

There are a few open questions:

1. What do we do about the compatibility tests? One option would be to only run them on the weekly tested snapshots.
2. How does the process work for marking a release as tested? I think it would be nice if that only moved the artifacts from GCP to GH releases and didn’t require rereleasing anything else.
3. Do we need to modify our existing process for manual releases or can we keep that untouched?

**Comment by stefanobaghino-da** [comment]
Yes, please.

**Comment by victormueller-da** [comment]
I still would like to have a button for deploying docker images on the fly.

**Comment by cocreature** [comment]
> I still would like to have a button for deploying docker images on the fly.

I’m not following, we already have infrastructure for cutting releases from arbitrary points and the goal here is not to get rid of this but to add additional automatic releases.

**Comment by garyverhaegen-da** [comment]
Thanks for writing all that down! Couple additions:

- It would be nice if we modified the get.daml.com script and the assistant to be able to install nightlies.
- We'll need to add some caching to the check_releases job before doing this.
- One of the hurdles to automating releases at the moment is there is no automated way to decide on the release number. I'm currently leaning towards having nightlies numbered `0.0.0-snapshot-...`.
- In that new world, I'm not sure it still makes sense to push non-stable releases to GitHub at all. What do we gain by that? It seems simple enough to tell people who want to try snapshots to first install the assistant then run `daml install`. It seems unlikely anyone wants to _start with_ a snapshot.
- We've had various troubles with GH as a release hosting mechanism in the past, and the main reason we have not moved releases to GCS yet is that GCS has no download count. I think we'll need to clear that up before proceeding (i.e. is it OK to lose visibility on download counts for snapshots?).
- Do we publish docs for those nightlies? SDK Docker image?

That's all I can think of right now, but I'll come back if something else pops up.

**Comment by realvictorprm** [comment]
> > I still would like to have a button for deploying docker images on the fly.
> 
> I’m not following, we already have infrastructure for cutting releases from arbitrary points and the goal here is not to get rid of this but to add additional automatic releases.

Well I currently hestitate to do a snapshot release with testing for just getting an up to date sdk docker image :/

**Comment by cocreature** [comment]
Ah right, I forgot to add the assistant integrtaion above. I think as a first step, we could skip that. You can still extract the tarball and install from that. This has a few advantages all mainly centered around there still being a set of GH releases for which we do not change what we do right now:
1. we still get download counts for those
2. check_releases could only operate on those.
3. we can publish docs for those.

I don’t have strong feelings on this by any means, it just seems like it might be a cheaper intermediate step.

> One of the hurdles to automating releases at the moment is there is no automated way to decide on the release number. I'm currently leaning towards having nightlies numbered 0.0.0-snapshot-....

I guess the issue here is that we don’t know when to switch release lines right? So the same issue we have for numbering the autorelease PRs. Maybe it’s reasonable to add a file to the repo with the release for main that we bump when we branch off? Worst case we number 1-2 days wrong after branching off. I do see value in being able to reasonably easily tie the version number to a point between stable releases.

> Well I currently hestitate to do a snapshot release with testing for just getting an up to date sdk docker image :/

1. With this proposal you could just wait a day and you’ll get a new image without doing any work.
2. We could consider not requiring testing of all manual releases given that we don’t do it for nightly. But I think this is really a separate discussion so I’d like to not sidetrack this issue.

**Comment by garyverhaegen-da** [comment]
> I do see value in being able to reasonably easily tie the version number to a point between stable releases.

The snapshot version number includes "number of commits", so as long as we have at least the RCs on GitHub (and I think it would be reasonable to _only_ have the RCs (and stables) on GitHub in that new model), it's still very easy to place a nightly in-between releases.
