### ISSUE TITLE
convert http.domain into a package object/package pair, like in fetch-contracts

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#11151]
#11057 needed to split part of [http.domain](https://github.com/digital-asset/daml/blob/1e9089552fcbba156f773c938e00991d45b1c6f7/ledger-service/http-json/src/main/scala/com/digitalasset/http/domain.scala) into a separate library, but did so not in a plain `object domain`, but [as a `package object`/`package` pair](https://github.com/digital-asset/daml/blob/1e9089552fcbba156f773c938e00991d45b1c6f7/ledger-service/fetch-contracts/src/main/scala/fetchcontracts/domain.scala#L18-L38).

The reason for this `object domain` is that it is clearer to put all the domain type definitions in one file than split into a bunch.  But it only _needs_ to be a value rather than a first-class package if you wish to treat Java's requirements about file organization as gospel.  We don't need to do that, and indeed don't for the new `fetchcontracts.domain` linked above.

The cleanup here is, as with `fetchcontracts.domain`, to place `class`es, `trait`s and `object`s in the `package`, and everything else in the `package object`.

**Comment by stefanobaghino-da** [comment]
Given that Scala 3 doesn't use `package object`s anymore, I'm not sure this would be time well spent in the longer term.

**Comment by S11001001** [comment]
@stefanobaghino-da The end desirable state (and the one enabled by Scala 3) is that all elements are within the `package`. Because the change suggested here places everything possible within the `package` and only places elements that you need Scala 3 for in the `package object` (which you naturally just move to the `package` in Scala 3), this brings us closer to that state.
