### ISSUE TITLE
Prevent "Terminate batch job? (Y/N)" prompt on Windows.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1122]
The last item from #965. Current thinking is that to avoid this we need to replace the "linking batch script" on Windows with an executable that will redirect to the correct version of the assistant. Unfortunately this has additional consequences:

- How does the executable know which version of the SDK it is pointing at? Does it get baked into the executable and distributed with the SDK? Do we just copy the assistant executable (but how does it know its own version?)? Does it always link to the latest installed version? Or is this information stored somewhere it can find?
- Handling uninstalls / upgrades on Windows, with the prohibition on modifying or deleting running programs.
- Do we copy this behavior on Linux/Mac? I'm in favor of a uniform approach across platforms where possible, but symlinks work well on Linux/Mac.
- Adapting daml-sdk-head to work with executable.

**Comment by hurryabit** [comment]
@associahedron Is that still an issue?

**Comment by cocreature** [comment]
After learning what a nightmare process management on Windows is, I’d rather keep this for now since we never had a user complain about this. Feel free to reopen if this becomes an issue.
