### ISSUE TITLE
daml interfaces: Expose Archive as virtual choice in interfaces.

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#11232]
Every template has an Archive choice but it currently isn't exposed in interfaces. We should add Archive as a virtual choice in every interface in damlc, and implement a HasArchive instance for every interface type.

(Then, once we have archive, we can implement preconsuming/postconsuming fixed choices for interfaces.)

**Comment by sofiafaro-da** [comment]
Can we close this for now? We don't have virtual choices any more.

**Comment by cocreature** [comment]
I think we actually wanted to expose it as a fixed choice and I just messed up the interface name :thinking: Still agree on closing it for now
