### ISSUE TITLE
Drop scenarios from the user-facing SDK

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11316]
For 2.0 we want our users to use Daml Script instead. We have lots of tests and internals that rely on scenarios so as a first step, we should only drop it from the user facing SDK.

I’d suggest the following steps:
1. Add a hidden flag to damlc to control whether scenarios are supported or not. If scenario support is off we error out when compiling scenarios with an error message suggesting to users to use Daml Script instead. It’s fine if that flag is available to users in the resulting SDK as long as it does not show up in `--help`. We can start with keeping scenario support on by default and then gradually switch it off in places until we can flip the default.
2. The script/scenario service should gain a flag that enables/disables scenario support. If it is disabled we reject grpc requests to start scenarios (but continue accepting requests for scripts). Apart from tests the script service is always started from damlc so it should pass that flag depending on its own mode.

We can then later start switching over our own tests and eventually kill that flag but we don’t have to do that on a 2.0 timeline.

**Comment by akrmn** [comment]
Questions:
1. Regarding

   > Add a hidden flag to damlc
   
   I'm currently looking at `compiler/damlc/lib/DA/Cli/Damlc.hs`, and it seems that we have a few subparsers for the different commands allowed by `damlc`. Which commands should get the new flag?

2. Also regarding

   > Add a hidden flag to damlc

   I noticed that the datatype `Options` at `compiler/damlc/daml-opts/daml-opts-types/DA/Daml/Options/Types.hs` has a field `optScenarioService`, which sounds related. Am I correct in understanding this issue as asking for a separate flag toggling support for services, regardless of whether the scenario _service_ is running?
   
3. Regarding

   > If scenario support is off we error out when compiling scenarios

   Where would be the best place to check if a scenario is being compiled? 

These are all for the first step you suggested, I think I can tackle your second step as it is.

**Comment by cocreature** [comment]
> 1. I'm currently looking at `compiler/damlc/lib/DA/Cli/Damlc.hs`, and it seems that we have a few subparsers for the different commands allowed by `damlc`. Which commands should get the new flag?

All of them, we have a shared `optionsParser`.



> 2\. Also regarding
>         > Add a hidden flag to damlc
>         
>         
>         I noticed that the datatype `Options` at `compiler/damlc/daml-opts/daml-opts-types/DA/Daml/Options/Types.hs` has a field `optScenarioService`, which sounds related. Am I correct in understanding this issue as asking for a separate flag toggling support for services, regardless of whether the scenario _service_ is running?

The naming here is slightly confusing. The scenario and the script service are the same thing. We want to keep supporting scripts so it has to be running but we want to stop supporting scenarios so we need a separate flag. Feel free to rename `optScenarioService` to `optScriptService` or something like that.



> 3\. Regarding
>         > If scenario support is off we error out when compiling scenarios
>         
>         
>         Where would be the best place to check if a scenario is being compiled?

Good question, I’d probably do it in the LF conversion.

**Comment by akrmn** [comment]
Thank you, that was very quick! 

> All of them, we have a shared `optionsParser`.

Ah perfect, I wasn't sure if that was the best since the `scenarios` flag for the scenario service was handled separately

> Feel free to rename `optScenarioService` to `optScriptService` or something like that. 

Hm maybe, though the service itself is under `compiler/scenario-service`, so probably better to leave it for later - or even keep the name for the service and keep "Script" for the scripts themselves.

> I’d probably do it in the LF conversion

Perfect! I'll try that approach

**Comment by lucianojoublanc-da** [comment]
Have you considered unifying the API, e.g. rename `submit createCmd` -> `submit create`? Is this even possible?

I think it would make it much simpler for users to switch over to scripts.

**Comment by cocreature** [comment]
We can’t do that. We need the restrictions that `Commands` is only an `Applicative` and is not completely opaque like `Update` is.

**Comment by cocreature** [comment]
Let’s keep this open until we flipped the default.

**Comment by akrmn** [comment]
shall we close now that https://github.com/digital-asset/daml/pull/12484 is merged?

**Comment by cocreature** [comment]
Yep, thanks a lot for taking care of this!
