### ISSUE TITLE
Build & test on not-yet supported Java versions, e.g. Java 17

### ISSUE THREAD

**Issue by adriaanm-da** [digital-asset/daml#11339]
- [ ] make Java version configurable in CI for building and testing
- [ ] run the whole build + tests on Java 17 on a nightly/weekly basis
- [ ] hybrid scenario: build on Java 11 and test on Java 17

**Comment by garyverhaegen-da** [comment]
Haven't heard any request for this in over 6 months, and I don't personally think this is useful. Java backwards compatibility is well established and we set the expected version in production Docker images anyway.
