### ISSUE TITLE
Restructure interface desugaring

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11341]
----------- in Desugar:
```

class Implements ty int where … toInterface, fromInterface
```

----- where Interface is defined:
```
Interface Token where
   getAmount : Int 

instance Implements Asset  Token
Instance Implements Token Token
```
 -- 
```
getAmount : Implements ty Token => ty -> Int
getAmount t = primitiveInterface @Token “getAmount (toInterface t)
```

------ implementation of interface:

```
instance Implements Asset Token where
   … toInterface
```

_method_Asset_Token_getAmount  : (...)

**Comment by akrmn** [comment]
@cocreature I think we discussed this in person but it's not clear to me from the text of the issue. It seems like there should still be a generated class to hold the methods of the interface, that is,

```
interface Token where
  getAmount : Int
```

Should result in

```
instance Implements Token Token where ...

class IsToken t where
  getAmount :: t -> Int
```

right?

**Comment by cocreature** [comment]
I don’t think we need this class. The idea was to desugar it as top-level methods:
```
getAmount : Implements ty Token => ty -> Int
getAmount t = primitiveInterface @Token “getAmount (toInterface t)
```

**Comment by akrmn** [comment]
My question was more about the implementations, since they will each define the methods in different ways. As discussed offline, however, we can simply encode those implementations as `_implements_<Interface>_<Type>_<Method>` values, or similar, thus avoiding the need to use a class for overloading.
