### ISSUE TITLE
Hook bug with create-daml-app & React 17.0.0 

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#11358]
I updated the following dependencies in the package.json  of the ui in  `create-daml-app`

- react: 17.0.0
- react-dom:17.0.0
- semantic-ui-react: "^2.0.0"
- @types/react-dom : "^17.0.0"

then follow the instructions and when logging into the UI, I get the error:

>Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

pointing to the quote [here](https://github.com/digital-asset/daml/blob/main/language-support/ts/daml-react/createLedgerContext.ts#L86) with the JS output. My quick scan of the React [Changelog](https://github.com/facebook/react/blob/main/CHANGELOG.md#1700-october-20-2020) does not reveal anything nor the React [Context documentation](https://reactjs.org/docs/context.html#when-to-use-context).

**Comment by garyverhaegen-da** [comment]
Likely solved by #11463, but I'd personally prefer waiting until we have a snapshot to test with before declaring this closed.

**Comment by stefanobaghino-da** [comment]
Looks like we can close this now: https://github.com/digital-asset/daml/pull/11463#issuecomment-959806979
