### ISSUE TITLE
[FEATURE REQUEST] Expose controllers in Daml

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11362]
Currently we have functions for getting the signatories of a template but we have nothing to get the controllers of a choice. I think this can be handy in a few places so we should add it. Type needs to be something like this
```
controllers : Choice t c r => t -> c -> [Party]
```
and should probably be exposed via a `HasController` typeclass.

**Comment by akrmn** [comment]
@cocreature, this is now available in HEAD; we went with `choiceController` instead of just `controller` to match `choiceObserver` (which would have clashed with the existing function to get a _template_'s observers)

```haskell
choiceController : HasChoiceController t c => t -> c -> [Party]
choiceObserver : HasChoiceObserver t c => t -> c -> [Party]
```

**Comment by cocreature** [comment]
nice thanks!

**Comment by samuel-williams-da** [comment]
@cocreature We found this feature was giving issues when having a 2.dev package depend on a 2.1 package (which Carl needed to test some features destined for CN)
Given this feature is only on 2.dev, am I safe to assume you're not using it? Such that we can disable it for now, and fix it properly later (potentially still in 2.1)

**Comment by moritzkiefer-da** [comment]
yes that's fine
