### ISSUE TITLE
Add NatSyn to the list of stable packages

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11373]
We should add the new NatSyn module to https://github.com/digital-asset/daml/blob/main/daml-lf/language/src/main/scala/com/digitalasset/daml/lf/language/StablePackages.scala.

This needs some slight changes to how things currently work. First, we should tackle #11371. Second, we should version the stable packages meaning that the list of stable packages depends on the LF version. Just like LF itself, the list of stable packages for a given version should stay stable. For this module this means we should consider it a stable module for LF 1.dev but not for 1.14 (where we don’t need it since it doesn’t need to bypass the check).

**Comment by akrmn** [comment]
Closing since AFAICT this was done as part of #11293
