### ISSUE TITLE
Suggested feature: export/import

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1137]
I think the utility of the web IDE could be massively improved if it had an easy option to export the current project as one zip file containing all of the user's file. As another step, it could also be made able to load a project from a zip file.

This would enable (at least) two interesting use-cases:
- A user could save their work and keep working on it later, and
- Workshops and other demos could have some starter code prepared.

It may be steering away from what we want the webide to be, though.

**Comment by neil-da** [comment]
VS Code is moving to having open from a git repo, which is a much better import than a zip file.

**Comment by hurryabit** [comment]
The webide is no longer part of this repo.

@da-tanabe You might take inspiration from this proposal.
