### ISSUE TITLE
Move definition of `data TextMap` in the correct module

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#1142]
It is not clear yet, what the correct module is, either `DA.TextMap` or `DA.Internal.LF`. The definition should also change to
```haskell
data TextMap = TextMap Opaque
```
but this will only be possible once we don't support DAML-LF versions without `TextMap` anymore and hence can erase the type definition during conversion to DAML-LF.

**Comment by neil-da** [comment]
Sounds like you need CPP in the base libraries...

**Comment by hurryabit** [comment]
If we drop support for older DAML-LF version, we're also good.

**Comment by neil-da** [comment]
I'm happy to aggressively remove support for old LF.
