### ISSUE TITLE
[BUG] Java Codegen collision module name collision check is missing deduplication

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11457]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**Affected Daml version**

1.17.0 (still present in HEAd)

**Bug description**

The Java codegen has a check to detect if two packages have modules with colliding module names. However that check does not deduplicate on package ids. This means that if you pass in two DARs and they depend on the same package you will get a collision even though there is none.

**To reproduce**

1. `daml new foobar && cd foobar && daml build`
2. `daml new foobar2 && cd foobar2 && daml build`
3. `bazel run //language-support/codegen-main -- java ~/foobar/.daml/dist/foobar-0.0.1.dar ~/foobar2/.daml/dist/foobar2-0.0.1.dar --output-directory ~/tmp`
4. You’ll observe the following error
```
Error generating code: Duplicate module GHC.Stack.Types found in multiple packages a4823eac9963532abb3e16e4f42c852914d2c4223afaea98deb0f9fc3810a6d1, a4823eac9963532abb3e16e4f42c852914d2c4223afaea98deb0f9fc3810a6d1. To resolve the conflict rename the modules in one of the packages via `module-prefixes`.
```

**Expected behavior**
No error

**Additional context**
The relevant code is in here: https://github.com/digital-asset/daml/blob/bf00956143f2d72ee01eb3d9e1052ac6c3a24408/language-support/java/codegen/src/main/scala/com/digitalasset/daml/lf/codegen/CodeGenRunner.scala#L65. This returns a list of interfaces which can contain duplicates. I think we should eliminate those in there.

There is actually also another bug in here: We don’t detect collisions in the DAR prefix in https://github.com/digital-asset/daml/blob/bf00956143f2d72ee01eb3d9e1052ac6c3a24408/language-support/java/codegen/src/main/scala/com/digitalasset/daml/lf/codegen/CodeGenRunner.scala#L77.

**Comment by chunlokling-da** [comment]
> Expected behavior
> No error

@cocreature  if I understand correctly. After the deduplication fix is done, we should still still got a collision error. The collision is due to the same module names between the package from foobar and the one from foobar2, right?

```
Error generating code: Duplicate module Main found in multiple packages b93b8bfb295291b7c2447a0f96ccc61abdc99da0b411822f4058f68b34eb0788, d87561b0efaf25d7f322618dd4e9625ef153e76f10f812f9c92d78d18bd16426. To resolve the conflict rename the modules in one of the packages via `module-prefixes`.
```

**Comment by chunlokling-da** [comment]
> There is actually also another bug in here: We don’t detect collisions in the DAR prefix in
I will create a new issue to capture it

**Comment by cocreature** [comment]
> if I understand correctly. After the deduplication fix is done, we should still got a collision error. The collision is due to the same module names between the package from foobar and the one from foobar2, right?

Yes that’s right. You need to rename one of those or add modulePrefixes or whatever.

> Do you mean by, for each packageId, there should not be more than 1 prefix configured?

iirc the prefix affects all packages in a DAR so dependencies should be included. But it’s been a while since I looked into this so I could be off there.

**Comment by cocreature** [comment]
I'd expect that to produce an error.

**Comment by chunlokling-da** [comment]
Even though there will be no java class generated from those common packages? e.g. the module `GHC.Stack.Types` in your example.

**Comment by cocreature** [comment]
Why do you expect there to be no java class generated? Because there are no serializable types in there? If so, I'd be fine with delaying the check until we generate a file. What I'd like to avoid is that we define two prefixes for a file that we actually do generate and we somewhat arbitrarily chose one of the two.
