### ISSUE TITLE
Document contract keys

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#115]
We should describe contract keys in the SDK doc.

Depends on #1065 and #1144.

**Comment by bethaitman** [comment]
After a discussion with @bitonic and @hurryabit this morning, here are my notes on what I think this requires. Please let me know what you think and what I've missed!

### Explaining contract keys

- Contract keys are an optional addition to templates. They allow users to specify a way of uniquely identifying instances of that contract: that can be a single parameter to the template or a combination of parameters (eg, in a tuple).

  What you can specify is pretty flexible. There are some restrictions on what can be a key, but we didn't cover those.
- If you specify a contract key for a template, you must also specify `maintainer(s)` (similar to how you specify signatories or observers). It's the responsibility of the maintainers to make sure that the the key for a contract instance is unique. (I still don't fully understand when/how this works, what the user actually needs to do here. I assume this fails at contract creation time?)
- Contract keys introduce two new functions, `fetchByKey` and `lookupByKey` that are an alternative to the currently-used `fetch`. You need authorization from the maintainers to run these, which can be provided through them being a signatory or them submitting the command/being a controller for the choice.

  For `fetchByKey`, at least one of the maintainers must authorize. If the fetch fails, it doesn't guarantee that a contract with that key doesn't exist, just that you can't see one. 

  For `lookupByKey`, _all_ of the maintainers must authorize. If the lookup fails, this guarantees that no contract (with these maintainers?) has this key.

### What pages this affects in the docs

- DAML reference

  - [Template structure](https://docs.daml.com/daml/reference/structure.html)
  - [Template reference](https://docs.daml.com/daml/reference/templates.html)
  - [Update reference](https://docs.daml.com/daml/reference/updates.html)
  - This might be a big enough feature that it's worth having its own page about it. Not sure yet. 
- [DAML patterns](https://docs.daml.com/daml/patterns.html)

  I think we should write a pattern/generic example showing good usage of contract keys, including plenty of scenarios to demonstrate what works and what doesn't
- [The ledger model](https://docs.daml.com/concepts/ledger-model/index.html)

  I do *not* know the ledger model well at all, but someone who understands this well will need to update it.
- Review our existing [examples](https://docs.daml.com/examples/examples.html) to see if any of them could benefit from contract keys.
- Does this affect application development _at all_, or is there nothing to say there?

**Comment by bitonic** [comment]
@bethaitman , thanks for the notes.

@andreaslochbihler-da , regarding the ledger model, hadn't we already updated it to contain contract keys?

**Comment by andreaslochbihler-da** [comment]
Well, we have a write-up how contract keys would fit in, but that has not yet been integrated into the main ledger model text (because contract keys were not officially part of DAML when I wrote that). The write-up is currently in the Canton repo at https://github.com/DACH-NY/canton/blob/master/docs/src/sphinx/proposals/ledger-keys.rst. When you update the SDK documentation, we should also properly incorporate this into the ledger model docs.

**Comment by andreaslochbihler-da** [comment]
I can help with updating the ledger model. When should this happen?
