### ISSUE TITLE
Versioning daml build package database by the SDK version.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1152]
(confirmed with @robin-da)

If someone attempts to run daml build in the same project on two different SDK versions concurrently, they will interfere with each other as they both try to initialise the package database with two different versions of the SDK packages. This limits how creative we can be with upgrades, e.g., it would be too dangerous to test a new SDK version in the background before recommend an upgrade.

One general way to solve this (and related problems) is to include the SDK version in the package database path or keys, preventing different SDK versions from interfering with each other.

**Comment by neil-da** [comment]
I'd much rather this separation in the file paths, so these pieces are 100% distinct.

**Comment by associahedron** [comment]
So, currently `daml build` uses the DAML-LF version in the path to the package database, but not the SDK version. I guess this isn't resolved, then, since different SDK versions could result in different packages even if the DAML-LF version stays the same.

**Comment by cocreature** [comment]
We clean the package db on every build so this is no longer an issue. Once we stop doing that, we need to make sure that the SDK version is taking into account when clearing the package db but that’s part of #4413
