### ISSUE TITLE
Consistently reject exercise on interface choices via template id in LF

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11558]

**Comment by remyhaemmerle-da** [comment]
Fixed by #11584.

**Comment by cocreature** [comment]
probably deserves a bullet point in #10917

**Comment by remyhaemmerle-da** [comment]
create  #11698 and add a coment there.

**Comment by cocreature** [comment]
@remyhaemmerle-da given that you created #11698 to cover testing, should we close this for now?

**Comment by cocreature** [comment]
Closing, @remyhaemmerle-da please reopen if there’s something left in here.
