### ISSUE TITLE
Tests do not deal with ports well

### ISSUE THREAD

**Issue by gleber-da** [digital-asset/daml#1156]
I have just gotten the following error:
```
[31m  com.digitalasset.ledger.server.LedgerApiServer.LedgerApiServer$UnableToBind: LedgerApiServer was unable to bind to port 39803. User should terminate the process occupying the port, or choose a different one.[0m
[31m  Cause: java.net.BindException: Address already in use[0m
```
in https://dev.azure.com/digitalasset/daml/_build/results?buildId=5552&view=logs

Given that ports are shared resources of the environment, ports in the tests should be handled as an unreliable shared resource:
- any port used in the test should be selected dynamically at test run time;
- any port allocation should be retried reasonable number of times.

Few options:
1. Make the server bind on port 0, so that the server chooses the port; next the server should report the chosen port to outside world, see [example](https://github.com/digital-asset/daml/blob/e73ad8b95704fcf3af5b6d7aa5e6a6e6209305ed/bazel_tools/client_server_test/tests/server.scala#L23) for example

2. Let the test suite select a port itself via [any mechanism](https://unix.stackexchange.com/questions/55913/whats-the-easiest-way-to-find-an-unused-local-port) and pass it to the server under test, but this can always fail, hence *needs to be retried*.

3. (Advanced) Let the test suite select a port and than hand it over to the server under test (requires non-trivial changes in a server), see https://gist.github.com/majek/2500291 for options.

**Comment by associahedron** [comment]
(I believe this is somewhat related: Option 1 above is something we want both sandbox and navigator to do to make `daml start` work better, and improve the related integration tests. Tracked in issue #833.)

**Comment by cocreature** [comment]
I don’t see this getting addressed so closing
