### ISSUE TITLE
[Engine] Stack safety in Daml Engine (Speedy)

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11561]
We have roughly 4 main areas where we have to worry about stack safety here:
1. Transaction depth, afaik we’re already stack safe here but we should add some tests.
2. Serializable value depth, we have a limit of 100 and we test for that so should be good.
3. SValue (runtime values) depth, no limit but afaik we’re stack safe here. Should have some tests for it though.
4. Daml-LF expression depth, this is the main one we need to address. We do have a limit of 1k here but that is high enough that we have to worry about stack safety.

As a first step we should tackle the speedy compiler since that is the primary culprit and also probably one of the more difficult ones. To start with let’s migrate one pass to something that explicitly maintains a stack (no cps’ing) and test the performance impact on a large project.

If that does turn out to be too slow we could consider doing some form of outlining in speedy where we pull out expressions to the top-level either into actual functions or some special expressions and thereby limit the depth to something where we can afford to do recursive calls.

(25/3/22)
In the end, all the notes on this issue relates to making the speedy compilation pipeline stack-safe.
I'm going to adjust the title to reflect that

**Comment by cocreature** [comment]
cc @remyhaemmerle-da

**Comment by nickchapman-da** [comment]
Status: stack safety in speedy compiler:
Of the 4 phases of the speedy compiler:
- We have definite stack safety in phases 1 and 2 (with thorough testing)
- We probably have stack safety in phase 3 (but we are lacking thorough testing)
- the final validation phase is *not* stack safe,

It is probably not much work to make phase 4 be stack safe. But I wonder if a better option might be to just throw it away. I think this validation phase achieves almost nothing, and it surely costs something. I will run some performance numbers.

**Comment by remyhaemmerle-da** [comment]
>  But I wonder if a better option might be to just throw it away. I think this validation phase achieves almost nothing, and it surely costs something. I will run some performance numbers.

I am not very familiar with this phase, but would i make sens to make it optional and run it only for all out tests ?

**Comment by nickchapman-da** [comment]
Performance cost of validation phase: about 1.5% of speedy compilation time.

`bazel run daml-lf/interpreter:speedy-compilation-benchmark -- -f 2 -wi 10 -i 10 -bm avgt -p darPath=<prod.dar>`

with validation
```
Result "com.daml.lf.speedy.SpeedyCompilationBench.bench":
  2.365 ±(99.9%) 0.055 s/op [Average]
  (min, avg, max) = (2.276, 2.365, 2.533), stdev = 0.064
  CI (99.9%): [2.309, 2.420] (assumes normal distribution)
```

without validataion
```
Result "com.daml.lf.speedy.SpeedyCompilationBench.bench":
  2.332 ±(99.9%) 0.054 s/op [Average]
  (min, avg, max) = (2.221, 2.332, 2.428), stdev = 0.062
  CI (99.9%): [2.278, 2.386] (assumes normal distribution)
```

**Comment by nickchapman-da** [comment]
> I am not very familiar with this phase, but would i make sens to make it optional and run it only for all out tests ?

perhaps. but my instinct is to kill it.

**Comment by nickchapman-da** [comment]
We now have stack safety thoughout the full speedy compilation pipeline.

**Comment by nickchapman-da** [comment]
Perhaps we should create separate issues for the remaining (non speedy) places where we are not stack safe ?

**Comment by nickchapman-da** [comment]
By varying the number of fields, the following test demonstrates remaining stack-overflow issues at various stages in our pipeline prior to speedy compilation:

```
~/daml/daml-lf/tests/scenario/stable/many-fields/Test.daml
```

The value of N in the test is currently set as 124, and everything works fine.

The fields are numbered with suffixes from 0 to N, so in fact we test N+1 fields.

Here is a table of results for some increased values of N:

```
N
124 -- ok (current value)
125 -- ok

127 -- ok
128 -- flaky type check overflow

129 -- type-checking overflow

149 -- type-checking overflow
159 -- decode overflow
169 -- com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.

199 -- com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.
```

**Comment by remyhaemmerle-da** [comment]
> Perhaps we should create separate issues for the remaining (non speedy) places where we are not stack safe ?

Good idea. and we could rename this one Speedy compilation. 
I already #13410 create for the type checking

**Comment by nickchapman-da** [comment]
I added an issue for `protobuf` decoding: #13418

**Comment by nickchapman-da** [comment]
What else is there apart from type-checking and protobuf decoding?

**Comment by remyhaemmerle-da** [comment]
We have to double check that all recursive processings for (LF or Speedy) values are safe. 
Normally: 
- We have tail resurrection (example Value Equality/Ordering) 
- We bound or recursion (example in SValue#toValue)
- We make sure the value have a depth of at most 100.

**Comment by nickchapman-da** [comment]
I split the work for value processing to a new issue
