### ISSUE TITLE
'self' is undocumented

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#11565]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**What is the problem you want to solve?**
The `self` construct is almost completely undocumented. As far as I can find, [this](https://docs.daml.com/daml/reference/templates.html#template-local-definitions) is the only correct reference.

**What is the solution you would propose?**
I think it would be nice if it was described when we're first taught about [`this`](https://docs.daml.com/daml/reference/templates.html#template-local-definitions). But maybe a general section for both constructs would be appropriate.

**Comment by garyverhaegen-da** [comment]
cc @carrielaben-da

I think a section "`this` and `self`" right before the "Template-local definitions" one would make sense.

**Comment by garyverhaegen-da** [comment]
@leonidr-da As the person who filed this ticket, would you mind taking a look at #14028 and report here what's still missing to consider resolved?

**Comment by leonidr-da** [comment]
Looks good., thank you.
