### ISSUE TITLE
Adopt rxjava bindings to V2 error codes

### ISSUE THREAD

**Issue by mziolekda** [digital-asset/daml#11587]
rxjava bindings need to be adopted to the new self-support error codes.
Here is an example place that hes been identified recently: https://github.com/digital-asset/daml/blob/3bed7a9b4f921b9e0ad972edcccf5d87c2ef1522/language-support/java/bindings-rxjava/src/test/scala/com/daml/ledger/rxjava/grpc/helpers/TransactionsServiceImpl.scala#L58

**Comment by stefanobaghino-da** [comment]
> rxjava bindings need to be adopted to the new self-support error codes. Here is an example place that hes been identified recently:
> 
> https://github.com/digital-asset/daml/blob/3bed7a9b4f921b9e0ad972edcccf5d87c2ef1522/language-support/java/bindings-rxjava/src/test/scala/com/daml/ledger/rxjava/grpc/helpers/TransactionsServiceImpl.scala#L58

Thanks. Can you give a couple of pointer on what is needed for this to happen so to make the process faster?

**Comment by stefanobaghino-da** [comment]
@mziolekda Still waiting for input on your side. The more input is there, the easier it will be to make sure we're not forgetting something.

**Comment by stefanobaghino-da** [comment]
@mziolekda Still no information from you. The line that you mentioned is a mock in a test which is not hit (and would give zero actionable data if we used it), so no need to adapt that. https://github.com/digital-asset/daml/pull/11510 doesn't mention anything else that was assigned to the Application Runtime team.

If you have anything that needs to be covered, I'm listening. If I cannot find anything and I won't receive any further information, I'll close this ticket.

**Comment by stefanobaghino-da** [comment]
@mziolekda After an exchange with @tudor-da is looks like the only work needed for the Java bindings tests to work has been dealt with as part of https://github.com/digital-asset/daml/pull/11223 and the self-service error codes can be returned verbatim through the bindings to the client, so no extra work needed. Closing.
