### ISSUE TITLE
[FEATURE REQUEST] Make JSON API DB connection pool configurable

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#11595]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**What is the problem you want to solve?**
Allowing to adjust the configuration of the database connection pool set up by the HTTP JSON API server.

**What is the solution you would propose?**
Add options that can be provided through the CLI to configure several parameters for the connection pool.

**Describe alternatives you've considered**
Unfortunately there are no viable alternatives to the hard-coded configuration.

**Additional context**
We are currently using HikariCP 3.2.0 as our library to manage a connection pool. [Here](https://github.com/brettwooldridge/HikariCP/tree/HikariCP-3.2.0#configuration-knobs-baby) are some available configuration keys.

**Comment by stefanobaghino-da** [comment]
@akshayshirahatti-da Can you have a look at the available configuration keys (a link to the HikariCP docs is in the description) and summarize which one would better serve a customer in production? We don't need to allow to configure everything from day one. At the very least the size and timeout should be configurable, but feel free to suggest further improvements.

**Comment by stefanobaghino-da** [comment]
@akshayshirahatti-da Can you please update the status of this ticket? It's easy to do it automatically in a PR by adding the reference to the closed ticket: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by akshayshirahatti-da** [comment]
Merged in #11621
