### ISSUE TITLE
[FEATURE REQUEST] Backport database connection pooling to 1.11.x

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#11596]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**What is the problem you want to solve?**
Enabling database connection pooling to be used for users of 1.11.x releases.

**What is the solution you would propose?**
Backporting the existing solution from `main` to `release/1.11.x`.

**Describe alternatives you've considered**
Upgrading, but that's not feasible in certain environments.

**Additional context**
This should be done after the connection pool has been made configurable as part of the work of #11595.

**Comment by stefanobaghino-da** [comment]
Is this fixed as well or is the backport still being worked on?

**Comment by akshayshirahatti-da** [comment]
Merged in #11615
