### ISSUE TITLE
[FEATURE REQUEST] Improve performance of querying by payload when using the HTTP JSON API query store on PostgreSQL

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#11603]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**What is the problem you want to solve?**
If many contracts are stored on the Ledger API, it may take a long time for all contracts to be scanned for the ones matching a query to be found, if some field of the contract is part of the query.

When used on Oracle, a parameter allows to disable contract payload indexing. That key should also be available on PostgreSQL to allow users to not create a full index on all contract payload fields (which in one way or the other is going to cause some trade-off between read and write performance).

**What is the solution you would propose?**
There's a solution proposed as part of #11591, I further suggest to have a better look at GIN indexes on PostgreSQL.

**Describe alternatives you've considered**
I haven't found possible alternative apart from the one described 

**Additional context**
This is part of #10310

**Comment by stefanobaghino-da** [comment]
In order for this ticket to be considered closed, the changes must also be backported to `release/1.11.x`.

**Comment by stefanobaghino-da** [comment]
@S11001001 thanks for fixing the title, I copy/pasted too hard.

**Comment by S11001001** [comment]
@stefanobaghino-da I was going to close as dupe until I scanned the description 🙂

**Comment by S11001001** [comment]
We might just be trying to reinvent the wheel here. Because [our PG query generator does everything it can to produce a `@>` directly against the `payload`](https://www.postgresql.org/docs/9.6/datatype-json.html#JSON_INDEXING) and express as much of the query as it can that way (e.g. excluding ranges).

**Comment by stefanobaghino-da** [comment]
@S11001001 I don't understand your latest message because I don't have enough context. Can you expand on that, please?

**Comment by S11001001** [comment]
@stefanobaghino-da As section 8.14.4 of the above-linked explains, the GIN operator classes support indexed `@>` conditions.

The way we compile queries expresses as much as possible as a single condition of the form `payload @> {...}`; naturally we cannot express every query this way, such as range queries, but most sub-element equality tests fit in this form, including nested records and variants, and in case of things like range queries we still do what we can to put *the remainder* of conditions in the single `payload @> {...}` form.

**Comment by stefanobaghino-da** [comment]
So the message above means that #11591 would be an ad hoc, informally-specified, bug-ridden, slow implementation of half of GIN indexes?

**Comment by S11001001** [comment]
or, possibly, an ad hoc, informally-specified, bug-ridden, fast implementation of half of GIN indexes

**Comment by stefanobaghino-da** [comment]
The performance investigation has been unfruitful as the existing index on template identifiers seems to be sufficient.
