### ISSUE TITLE
Run Navigator GraphQL code generation in Bazel

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#1160]
Navigator includes code generation to generate TypeScript definitions for GraphQL API responses from a given query and the corresponding schema.

These definitions are updated manually using `make update-graphql-types` in `navigator/frontend` and checked in. This was done to avoid setting up the frontend project to be aware of the generated files which are stored by Bazel outside of the project tree.

We should investigate whether it would be feasible to generate these files with Bazel, and if not, add a test to check that the checked in files are up to date.

Example generated file: https://github.com/digital-asset/daml/blob/master/navigator/frontend/src/api/Queries.ts
Code generation script: https://github.com/digital-asset/daml/blob/master/navigator/frontend/Makefile#L31

**Comment by neil-da** [comment]
@garyverhaegen-da @nickchapman-da if you so fancy a nice introduction to Bazel.

**Comment by rautenrieth-da** [comment]
I suspect that 95% of the work will be making sure the TypeScript compiler and VSCode work correctly with the generated files. Those files contain type definitions used by IntelliSense, and node/npm tools generally do not like the Bazel environment (in particular, symbolic links and files outside of the project root are bad).

For scala projects, we have `bazel-project-view` and the Blaze IntelliJ studio extension, I'm not sure there is something comparable for VSCode.

**Comment by stefanobaghino-da** [comment]
Should be closed if #13177 gets confirmed and implemented.

**Comment by garyverhaegen-da** [comment]
It's been over three years, if there was any interest in doing this there would have been at least some movement.
