### ISSUE TITLE
Fixed choices are not generated properly in the typescript codegen

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11608]
In https://github.com/digital-asset/daml/blob/f722cf13cda26fe1bb573004416ac944cf334789/language-support/ts/codegen/tests/ts/build-and-lint-test/src/__tests__/test.ts#L351 `buildAndLint.Main.Asset.Transfer` is `undefined`. It looks like somewhere we’re just not generating the code for the choice at all so the selector returns `undefined`

**Comment by robin-da** [comment]
I added support for fixed choices in the TS codegen. However, the tests are still failing because the JSON API does not like interface template IDs.

**Comment by cocreature** [comment]
Closing in favor of https://github.com/digital-asset/daml/issues/12689 so we have more descriptive issues.
