### ISSUE TITLE
[FEATURE REQUEST] Improve performance of querying by template identifier when using the HTTP JSON API query store on PostgreSQL

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#11600]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**What is the problem you want to solve?**
If many contracts are stored on the Ledger API, it may take a long time for all contracts to be scanned for the ones with the proper template identifier to be found, if the template identifier is part of the query (which is a common pattern).

**What is the solution you would propose?**
Add an index to the PostgreSQL-backed query store that targets the column that is used to filter contracts by their template identifier.

**Describe alternatives you've considered**
Possibly sharding JSON API servers by template identifier, but that is not feasible in all environments and requires extra-complexity on the deployment & operation side.

**Additional context**
This is part of #10310

**Comment by stefanobaghino-da** [comment]
In order for this ticket to be considered closed, it must be also backported to `release/1.11.x`.

**Comment by stefanobaghino-da** [comment]
We already have an index on template identifiers. A customer reported that queries involving a template identifiers that only has a small number of active contracts are slow. Do we have an idea of whether it's reasonable to think that this could be due to the query store? Could it be because the index that covers template identifiers is not used when a query involves party identifiers as well?

**Comment by S11001001** [comment]
The current indices deliver query plans as follows (specifically pre-#11683):

```sql
explain  SELECT contract_id, tpid  tpid, key, key_hash, payload, signatories, observers, agreement_text
                FROM some_nice_prefix_contract AS c
                WHERE ((signatories || observers) && '{"Alice_93a690c3-fe9c-4e84-b360-3fc930b9679e"}'::text[])
                      AND ((1 = tpid  AND (payload @> '{}'::jsonb)) );
                                                           QUERY PLAN                                                            
---------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on some_nice_prefix_contract c  (cost=4.16..9.52 rows=1 width=232)
   Recheck Cond: (1 = tpid)
   Filter: ((payload @> '{}'::jsonb) AND ((signatories || observers) && '{Alice_93a690c3-fe9c-4e84-b360-3fc930b9679e}'::text[]))
   ->  Bitmap Index Scan on some_nice_prefix_contract_tpid_idx  (cost=0.00..4.16 rows=2 width=0)
         Index Cond: (1 = tpid)
```

So satisfying this mainly regards taking care that #11602 doesn't break this index usage.

**Comment by S11001001** [comment]
> Could it be because the index that covers template identifiers is not used when a query involves party identifiers as well?

All queries involve both template = checks and party-set intersection checks, without exception.

**Comment by stefanobaghino-da** [comment]
> > Could it be because the index that covers template identifiers is not used when a query involves party identifiers as well?
> 
> All queries involve both template = checks and party-set intersection checks, without exception.

That's why I'm asking. Can you help me understand the execution plan above? How many contracts are in the query store? If I'm reading it correctly there's very little data involved and the index on the surrogate template identifier column is only used after applying the filter for payload and parties. Is that correct? What is the execution plan when querying for a template identifier with a low cardinality in a very large contracts table (the slow query reported by the customer matches less than 10 contracts by template identifier in a contracts table in the tens of thousands of items).

**Comment by stefanobaghino-da** [comment]
The performance investigation has been unfruitful as the existing index on template identifiers seems to be sufficient.
