### ISSUE TITLE
daml assistant should embed/serve SDK documentation

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1161]
I think this could be done small-ish small steps that each add value, though some may be simple enough that they could be merged:

1. Embed the HTML documentation in the SDK tarball (that may already be the case) and have a command from the assistant to spit it out, e.g. `daml docs 0.12.17 --pdf docs.pdf` and `daml docs 0.12.17 --html some-folder`.
1. Have the assistant itself be able to serve the SDK docs (embedded in the tarball) as a web server, as that's the most convenient way to see HTML files: `daml serve-docs --port 6666`. If run from a project, pick up the SDK version from the daml.yml file, with cli flag to override.

See #1172 for adding a command to compile the docs of the current project.

In addition to documentation, we could also host a specialized Hoogle instance that includes all the loaded libraries.

**Comment by neil-da** [comment]
Why not just point people at `docs.daml.com`? Isn't that a much easier thing to do? What's the disadvantage?

**Comment by associahedron** [comment]
`daml docs` is a command we should expose primarily for generating project documentation. If it's capable of serving stdlib docs as well, that's certainly fine by me. 

@neil-da The two advantages I can think of serving stdlib docs are serving offline people, and serving docs for older SDK versions we no longer track on the website. Both are somewhat low value IMO.

**Comment by neil-da** [comment]
Developers usually have internet access, but those that do have the PDF docs, which are adequate for them (since they're already having a very bad time without the internet anyway).

**Comment by garyverhaegen-da** [comment]
Again ultimately steps 1 & 2 were mostly meant to have useful stepping stones towards 3+; I like having deliverable partial features that can be done in short PRs to minimize branching. Maybe I'm vastly overestimating the work required for 3.

**Comment by bethaitman** [comment]
Agree with Neil - I don't quite see the need for providing docs locally. If we were getting users complaining that they couldn't get hold of the docs, then it would seem sensible, but I haven't heard that feedback.

**Comment by associahedron** [comment]
IMO, the correct order of incremental progress is:

1. Implement a command to compile the current project's docs.
2. Preview the docs in a browser with the same command.
3. Incorporate this command into the IDE.
4. Optionally, add a flag to serve stdlib docs as well.

**Comment by cocreature** [comment]
Compiling documentation of the current project has been moved to #1172 so let’s use this issue to only cover SDK docs (the two issues are mostly orthogonal.)

**Comment by associahedron** [comment]
Closing this in favor of #1172 due to low general enthusiasm for serving sdk docs locally. (We can always revisit this later.)
