### ISSUE TITLE
On Windows, `daml install --force` cannot override the active SDK

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#1164]
On Windows, you cannot remove the executable that is currently running so we cannot remove `daml/daml.exe` and the install fails.

cc @associahedron

**Comment by associahedron** [comment]
Time to come up with a convoluted plan for Windows...

**Comment by associahedron** [comment]
There's two things competing here:

- If we run the assistant executable from the sdk folder, we can't replace or remove the sdk folder, leading to this issue exactly.
- If we run the assistant executable from `$DAML_HOME/daml/bin` folder, we can't overwrite that, leading to this same issue but with `--activate` (which seems way worse to me).

I can think of two solutions:

- Don't attempt to delete or overwrite `$DAML_SDK/daml/` even with --force.
- Copy and run the assistant executable from a third folder, which `$DAML_HOME/bin/daml` automatically invokes, and never overwrite a running executable. This also solves our "Terminate Batch Job? (Y/N)" problem if implemented properly.

**Comment by neil-da** [comment]
Another approach is leave a marker to a running executable saying next time do some upgrade action - essentially deferring it. Yet another approach is there is a copy on reboot flag, but that means you need to reboot to finish an upgrade, which sucks.

I think the forwarding executable plan might work, but we'd need to spec precisely what it does so we can critique it at the design stage.

**Comment by associahedron** [comment]
I would prefer not to require reboots on upgrade, but also a comment on this stackoverflow post suggests you need admin privileges to use the "move file on reboot" function. https://stackoverflow.com/questions/1606140/how-can-a-program-delete-its-own-executable

Let me make a more detailed proposal then. I appreciate feedback on this.

On Windows, we maintain a third folder. Let's call this folder `$F` for the sake of this proposal. It could just be `$DAML_HOME\exes`. Then the idea is:

* When installing and activating a version of the assistant, we copy the executable from the sdk folder into `$F` with a new name: `$F\daml-$TIMESTAMP-$SDKVERSION.exe` or similar. The `$TIMESTAMP` is a unix timestamp (or similar) so we know what the latest "activated" version of the assistant is, and to avoid overriding existing executables in `$F`, and the `$SDKVERSION` is so we know what SDK version it came from (to determine the $DAML_ASSISTANT_VERSION when running the installed assistant).

* When the user types `daml`, it runs an executable at `$DAML_HOME\bin\daml`, which in turn runs `$F\daml-$TIMESTAMP-$SDKVERSION.exe` and redirects everything. We do not touch `$DAML_HOME\bin\daml` during upgrades, only during initial installs.

* When performing installs, we remove any outdated `$F\daml-$TIMESTAMP-$SDKVERSION.exe`.

This should allow both `--force` and `--activate` to work and get around issue #1122. The downsides I see (compared to the current situation):

1. It's more complicated.
2. We can't upgrade the `$DAML_HOME\bin\daml` executable. If there is a bug in this executable, we have to ask users to run the windows installer again to nuke their existing installation.

**Comment by cocreature** [comment]
Just to be clear: This is only an issue when `--force` installing over an existing installation. Upgrades seem to work just fine (overwriting the `daml.cmd` wrapper does not cause any issues afaict). So given that a force install is not something that we expect users to have to do, this doesn’t need an urgent fix.

I am a bit worried that your proposed solution adds a lot of complexity that is only exercised on Windows so it has a relatively high chance of breaking without anyone noticing it before a release (simply because far fewer people test on Windows). Given that as I mentioned above only `--force` installs suffer from this, I don’t think the complexity is worth it for fixing this issue on its own. Now #1122  is something that we should fix but we also can get away with a far simpler solution (e.g. have a sinlge forward executable that reads a text file that effectively emulates symlinks). So I wonder if for now, the more sensible solution is to leave this as a wontfix and only detect this case and output instructions for how users can fix it (if someone manages to gets themselves into the position where they need a --force install, it doesn’t seem unreasonable to ask them to delete a directory manually).

**Comment by associahedron** [comment]
The complexity is to avoid creating other problems (e.g. breaking --activate) and fixing #1122 simultaneously. I get not wanting to support `--force` on Windows, but I'm also worried we'll end up with a half-baked Windows solution (compared w/ Linux + Mac).

We could also remove `--force` entirely from all platforms. We're already not mentioning it in normal operation (only through `daml install --help`) because there's no reason we expect users to actually need `--force`. It used to be that you couldn't activate a version if it was already installed without `--force` but that's no longer the case. The only case where `--force` is useful is when you have two different SDK tarballs with the same version number, and that should only happen with HEAD, which is taken care of manually on Mac and Linux (& there isn't daml-sdk-head on windows yet).

**Comment by cocreature** [comment]
As I mentioned above, upgrading including `--activate` works fine. Overwriting the `daml.cmd` wrapper does not appear to cause any issues.

**Comment by associahedron** [comment]
Yes, I know. Reread my response?

**Comment by cocreature** [comment]
Sorry, I interpreted your response as suggesting that `--activate` is currently broken rather than a worry about breaking it by going for another solution.

I’d be fine with removing `--force` but it also does seem to be useful for development so I’m a bit split here. Another solution would be to use your proposed solution but use it on all platforms instead of only on Windows. That way it would see more testing and we are less likely to break it accidentally.

**Comment by neil-da** [comment]
Does this need a chat the three of us? It seems subtle and interrelated points that might be best chopped up in person. I'm worrying a lot about the complex, the workflows we are trying to support, and the fact that a reasonable chunk of this will be nearly impossible to change after the first version.

**Comment by associahedron** [comment]
In face of the complexity of any "proper" solution to this on Windows, and given how it would cause divergence between the Unix & Windows versions for little benefit, I'm thinking we should just give an error message that suggests an alternative course to the user:

```
Cannot overwrite active installation. To proceed with reinstallation,
please download and run the windows installer from

https://github.com/digital-asset/daml/releases/tag/latest
```

This will at least give the user a "self-service" solution to reinstalling the SDK, not a dead end. (And it will nuke their existing installation, which is arguably a good thing if the user needs to resort to --force. And it will upgrade their installation in the process.) Note that `--force` would still work for non-active SDK versions.
