### ISSUE TITLE
Failed to install DAML Studio extension from current SDK.

### ISSUE THREAD

**Issue by bbbwwic** [digital-asset/daml#11684]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**Affected Daml version**
1.17.1.

**Bug description**
When I enter "daml studio" in terminal, it failed to launch the daml studio, I have already install the visual studio code. 
The feedback is: "/bin/sh: code: command not found

Failed to install DAML Studio extension from marketplace.
Installing bundled DAML Studio extension instead.
/bin/sh: code: command not found

Failed to install DAML Studio extension from current SDK.
Please open an issue on GitHub with the above message.
https://github.com/digital-asset/daml/issues/new?template=bug_report.md
/bin/sh: code: command not found

Failed to launch DAML studio. Make sure Visual Studio Code is installed.
See https://code.visualstudio.com/Download for installation instructions."

**To reproduce**
Add here the steps to reproduce the faulty behavior:
1. start such and such service '...'
2. create contract that '....'
3. exercise choice that '....'
4. see error

**Expected behavior**
Enter here a clear and concise description of what you expected to happen.

**Additional context**
Add here any other context about the problem here.
This includes but is not limited to:
- OS information: Mac iOS
- Daml code relevant to reproduce the faulty behavior
- logs in textual format containing relevant information
- for Navigator or the documentation: screenshots

**Comment by nycnewman** [comment]
Please resend your notice to security@digitalasset.com as the DA Security Team has not received any such message. 

However in this instance it looks like the shell is complaining that it cannot find the "code" command which is used to start up VS Code (core basis of Daml Studio). Check that you see the following file: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code. I have tested on my MacOS laptop and daml studio works as expected. You may also want to try reinstalling Visual Studio Code.

**Comment by bbbwwic** [comment]
> Please resend your notice to [security@digitalasset.com](mailto:security@digitalasset.com) as the DA Security Team has not received any such message.
> 
> However in this instance it looks like the shell is complaining that it cannot find the "code" command which is used to start up VS Code (core basis of Daml Studio). Check that you see the following file: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code. I have tested on my MacOS laptop and daml studio works as expected. You may also want to try reinstalling Visual Studio Code.

Thanks for your concerning. Since I do not think this related with any security issue so I did not send this notice to security team. I will try to reinstall Visual Studio Code. Thanks

**Comment by cocreature** [comment]
Take a look at https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line to make sure vscode is installed in PATH.

**Comment by stefanobaghino-da** [comment]
> Please resend your notice to [security@digitalasset.com](mailto:security@digitalasset.com) as the DA Security Team has not received any such message.
> 
> However in this instance it looks like the shell is complaining that it cannot find the "code" command which is used to start up VS Code (core basis of Daml Studio). Check that you see the following file: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code. I have tested on my MacOS laptop and daml studio works as expected. You may also want to try reinstalling Visual Studio Code.

@nycnewman The message is part of the issue templates. It's there to make sure people are aware that if they are opening a ticket with security implications, they are aware of the information. That's why the line says

> **if** this is a bug that has security implications
