### ISSUE TITLE
Use native installers

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#117]
Includes #223, #331, #332

**Comment by cocreature** [comment]
We have a native Windows installer now and a fairly simple `curl … | sh` command to install on Linux and MacOS. I’ll leave this open in case we want to add MacOS and Linux installers but I’d say that’s relatively low priority.

**Comment by neil-da** [comment]
I think this is actually pretty well sorted - the get pattern is becoming pretty standard and allows us to update at speed. Closing for now.
