### ISSUE TITLE
Check types on exercise/fetch by template for interface choices

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11703]
Both in Daml and over the ledger API you can exercise a choice from an interface by template id,e.g.,
```
exercise (cid : ContractId InterfaceImpl) InterfaceChoice
```
However, currently we only check that `cid` corresponds to a template that implements the interface, we do not check that it is `InterfaceImpl`. So someone can pass a cid of a different template that implements the interface and things will succeed.

This is at best confusing and at worse a potential attack vector so we need to fix this.

This is slightly tricky since we desugar such a choice as
```
instance IsToken t => HasExercise t GetRich (ContractId Token) where
  exercise cid = GHC.Types.primitive @"UExerciseInterface" (toTokenContractId cid)
```
This means that we generate the same call regardless of whether we call by interface or by template. We also don't have the ability to create a monomorphic `HasExercise` instance for each template, since the desugarer doesn't know which fixed choices are available (and they may not even be in scope).

To fix this, we should be able to change the primitive for `UExerciseInterface` to accept an optional typerep and validate against that.

Another option would be to accept a boolean predicate on the template payload that we evaluate between the fetch & the exercise. However, if we want to make failures of that catchable we have to record a fetch in the case of failure to track transaction inputs which is somewhat tricky.

so for now, the typerep solution seems like the better option.

**Comment by sofiafaro-da** [comment]
This is done! Thanks to @akrmn for merging the final PR into ghc :)

**Comment by sofiafaro-da** [comment]
There's even a test: https://github.com/digital-asset/daml/blob/main/compiler/damlc/tests/daml-test-files/InterfaceTypeRepCheck.daml
