### ISSUE TITLE
Parts of stdlib should use CanAbort instead of ActionFail 

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#11709]
Per the discussion here https://discuss.daml.com/t/to-abort-or-to-fail/3012/6, I think that  the  `Total` functions, such as [fromSomeNote](https://docs.daml.com/daml/stdlib/DA-Optional-Total.html#function-da-optional-total-fromsomenote-26318) should have the `CanAbort` typeclass instead of `ActionFail`.

**Comment by cocreature** [comment]
this is somewhat breaking so SDK 2.0 might be a good opportunity for this.
