### ISSUE TITLE
Inconsistent package ids when using imported libraries

### ISSUE THREAD

**Issue by tristan-da** [digital-asset/daml#1180]
Given:

`FooModule.daml`:
````
daml 1.2
module FooModule where

data Foo = Foo
  with
    name: Party
  deriving (Show, Eq)
````

`BarModule.daml`:
````
daml 1.2
module BarModule where

data Bar = Bar
  with
    name: Party
  deriving (Show, Eq)
````

`LibraryModules.daml`:
````
daml 1.2
module LibraryModules where

import FooModule
import BarModule
````

`daml.yaml`:
````
sdk-version: 0.12.17
name: FooBar
source: LibraryModules.daml
parties:
  - Alice
  - Bob
version: 1.0.0
exposed-modules:
  - FooModule
  - BarModule
dependencies:
  - daml-prim
  - daml-stdlib
````

Running the following commands several times will yield different package ids (one of two possible values in this simple case, more possible values in more complex cases):
````
daml build
daml damlc inspect-dar dist/FooBar.dar | grep FooBar | tail -1
````

**Comment by hurryabit** [comment]
I can reproduce this. I can actually produce 4 different hashes. All differences I can spot are cause by GHC using different names for internal variables. For instance, I get
```
package 52af387d73cde25f303f240f4999584695518b081500c9f80c94a830497f98e9 where
...
    def $WFoo : Party -> FooModule:Foo =
      \(dt_aXq : Party). FooModule:Foo {name = dt_aXq}
...
    def $WBar : Party -> BarModule:Bar =
      \(dt_aXr : Party). BarModule:Bar {name = dt_aXr}
```
and
```
package 2d753284a5779e984fafb0ce27f45e4c16e590d95a79539f089e7acaca0970ca where
...
    def $WFoo : Party -> FooModule:Foo =
      \(dt_aXr : Party). FooModule:Foo {name = dt_aXr}
...
    def $WBar : Party -> BarModule:Bar =
      \(dt_aXq : Party). BarModule:Bar {name = dt_aXq}
```

My best guess is that the generation of internal names depends on the order in which shake compiles the individual modules. @neil-da how deterministic is shake in picking this order?

**Comment by neil-da** [comment]
With optThreads=1 Shake uses a deterministic thread pool. Whether that goes all the way through to deterministic output is unclear, but it was meant to...

**Comment by hurryabit** [comment]
I cannot reproduce this with `damlc compile`. It's probably not shakes fault hence.
