### ISSUE TITLE
DAML compiler accepts invalid template 

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#1194]
The following (invalid) template definition compiles successfully:

```
template X
  with
    x: Text
  where
```

BUT, running a scenario that tries to create a contract of template `X` fails with an error:
```
main = test do
  p <- getParty "party"
  
  submit p do create X with x = "bla"
  

Scenario execution failed on commit at Foo:12:3:
  Aborted:  <no location info>: No instance nor default method for class operation signatory
Last source location: Control.Exception.Base:54:86
```

Considering that a template without a `signatory` definition is invalid to begin with, the compiler mark this as an error. I'd be curious as to why the missing `signatory` definition is not caught during the compilation.

**Comment by neil-da** [comment]
I'm going to see if turning on warnings for missing type class methods will catch this, which would be an easy fix.

**Comment by neil-da** [comment]
With the warning I'll add we get:

```
/Users/neil/projects/quickstart/daml/Main.daml:1:1: warning:
    • No explicit implementation for
        ‘DA.Internal.Template.signatory’
    • In the instance declaration for
        ‘DA.Internal.Template.Template Main.X’Typechecker
```

So the warning is in the wrong place (no location info), one for @shayne-fletcher-da to fix. With that warning in the right place I'm happy enough to say that this issue is fixed.

**Comment by hurryabit** [comment]
I think in the long run we should enforce that every `template` has a `signatory` clause. I don't imagine this to be really hard.

**Comment by neil-da** [comment]
Hmm, fair point - might as well declare them invalid.

**Comment by shayne-fletcher-da** [comment]
> I think in the long run we should enforce that every `template` has a `signatory` clause. I don't imagine this to be really hard.

I actually thought we already did.

**Comment by neil-da** [comment]
I turned the warning of missing methods into an error, so the end state here might be sufficient.

**Comment by neil-da** [comment]
I suggest the remainder of this ticket is a test case for `template` and fixing the location information.

**Comment by rohanjr** [comment]
I solved this issue with the revamped template desugaring.
