### ISSUE TITLE
Add an API to produce action node stats of a transaction

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11961]
To support ledger metering, we need to be able to count the number of actions split by action type that are in a transaction.
We care only about actions so rollback nodes themselves do not count. However, actions below a rollback node do.

In addition to splitting by action type, we also want to split consuming vs non-consuming and byKey vs non-by key.

As a rough sketch the resulting API should allow you to get something like this back from a transaction. I expect the actual API will probably do some grouping to make this a bit nicer and obviously we can bikeshed the names.
```
case class TransactionStats(
  creates: Int,
  consumingExercises: Int,
  nonconsumingExercises: Int,
  consumingExerciseByKeys: Int,
  nonconsumingExerciseByKeys: Int,
  fetches: Int,
  fetchByKeys: Int,
  lookupByKeys: Int,
)
```

It is acceptable to traverse the transaction at least initially. Eventually, we could consider if we want to compute this as part of interpretation to avoid having to retraverse.

Note from @remyhaemmerle-da:

We might want to separate rolled back events from non-rolledback events. Aggregating them back together is easy, splitting them is not.

**Comment by mziolekda** [comment]
Looks reasonable, maybe with the exception of typo in `consumingExerciseByKeyss`

**Comment by cocreature** [comment]
> maybe with the exception of typo in `consumingExerciseByKeyss`

fixed :)

**Comment by simonmaxen-da** [comment]
For completion it would also be good to have the number of rollback nodes.
