### ISSUE TITLE
`daml build` doesn't show warnings

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#1198]
Take the quickstart example. Add `import DA.List`. Observe that in the IDE there is a warning. `daml build` shows no warnings.

**Comment by associahedron** [comment]
`daml build` just calls `damlc build`, which calls `damlc package-new`, so that's where the problem lies, I believe.

cc @robin-da

**Comment by associahedron** [comment]
@DavidM-D is looking into why none of our CLI tools print warnings.

**Comment by neil-da** [comment]
I fixed this in `daml test` quite recently. https://github.com/digital-asset/daml/blob/master/daml-foundations/daml-tools/da-hs-daml-cli/DA/Cli/Damlc/Test.hs#L46 is the magic line - just change the event watching to pass printDiagnostics.
