### ISSUE TITLE
Use native installation paradigm for DAML (brew for OSX)

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#12]
At present, to download DA binary artifacts, standard commands to install binaries are not available to developers.  To lower the barrier to entry we want to enable standard installation approaches that are familiar to developers in particular languages idiomatic to the OS and environment:

### OSX 
`brew cask create daml`

```
cask 'daml' do
  version '110'
  sha256 '2ca6cc3741e7bec3f9efe06eb485ce7a5052a697d5bffa7d9608d624dc2ff0bf'

  url 'https://bintray.com/digitalassetsdk/DigitalAssetSDK/download_file?file_path=com%2Fdigitalasset%2Fda-cli%2F110-f42c34eba1%2Fda-cli-110-f42c34eba1-osx.run'
  name 'Digital Asset SDK da-cli'
  homepage 'https://bintray.com/digitalassetsdk/DigitalAssetSDK/da-cli'

  app 'DAML'
end
```

### Using Brew Detail and Reference
https://engineering.innovid.com/distributing-command-line-tools-with-homebrew-d03e795cadc8
https://kylebebak.github.io/post/distribute-program-via-homebrew
https://docs.brew.sh/Acceptable-Formulae

### Related Issues
#331 #332

**Comment by neil-da** [comment]
I think the install script with curl works really nicely and lets us update quickly, so closing until we get real external demand.
