### ISSUE TITLE
Handle user token alongside claim tokens in the JSON API

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#12022]
Reference design document for the overall user management service: https://docs.google.com/document/d/1o6gAgAVNji5-kR2xX82h4M0gINIJs3pgDj2IDGew-E0/edit

The user management service is described by the gRPC definition added in https://github.com/digital-asset/daml/pull/11818 and refined in https://github.com/digital-asset/daml/pull/11908.

A _claim token_ is a JWT in the current form of tokens accepted by the Ledger API where claims are laid out explicitly in the token itself.

A _user token_ is a JWT in the form expressed by the user management service design document linked above. The `sub` field (which is a default field in the [JWT specification](https://datatracker.ietf.org/doc/html/rfc7519)) specifies the user. The user is used to resolve the claims to fill in the necessary fields on the JSON API throught the user management service.

The user management service will need to be mocked until https://github.com/digital-asset/daml/issues/12014 is closed.

The user management service client already exists on the Scala bindings, added as part of https://github.com/digital-asset/daml/issues/12009.

### Acceptance criteria

- [ ] The HTTP-JSON API accepts _user tokens_, resolve their claims and fill in the fields required
- [ ] When using the _user tokens_ ~only the primary party of the user is filled in as the `actAs` party~ the full set of claims resolved for that user is filled in into the request
- [ ] The `actAs` and `readAs` party can otherwise be overridden by the existing mechanism
  - the streaming endpoints are not yet capable of overriding `actAs` and `readAs`, this is a known limitation and is out of scope as part of this ticket
- [ ] The old _claim tokens_ are still accepted by the HTTP-JSON API

**Comment by stefanobaghino-da** [comment]
Editing the description to provide better context and guidance to the ultimate ticket assignee.

**Comment by stefanobaghino-da** [comment]
Description edited: @meiersi-da @S11001001 @realvictorprm can you double check the validity of the description, please?

@realvictorprm In particular, this is going to be your next task.

**Comment by realvictorprm** [comment]
Many thanks, will take a look!

Stefano Baghino ***@***.***> schrieb am Mi., 8. Dez. 2021,
09:20:

**Comment by cocreature** [comment]
I would have expected that we use all claims in the token rather than the primary party for a few reasons:

1. This seems closer to how we currently use all claims in the token so easier migration path: A new-style token is exactly equivalent to an old-style token with the same readAs & actAs claims.
2. It means explicit party specifications only ever restrict the claims which seems somewhat simpler than being able to both extend & restrict claims that way.

More generally my intuition is that the primary party is used by tools that need to act as a single party but tools like the JSON API that already support multiple parties just use the actual claims.

I don’t feel super strongly about this though, just wanted to expand on why it does not match my intuition.

**Comment by S11001001** [comment]
@stefanobaghino-da I only have one concern, that the user token's validity is confirmed by the ledger server just as the claim token currently is.

Here is an example: suppose you [currently] query with a JWT with party foo against a configured query store. Technically, we may have the cached contracts already to respond to the request. *However*, we

1. always update first, with the given JWT as authorization
2. fail to the client without doing any DB querying if that update fails

So the participant server still serves as gatekeeper, even for our own data.

1. May this invariant be compromised in any way by the use of user tokens?
2. If so, what special extra steps need to be taken to ensure that the participant continues to serve as gatekeeper? (For example, this is why we do a party-subset check on readAs compared to the claim token for queries.)

**Comment by stefanobaghino-da** [comment]
> I would have expected that we use all claims in the token rather than the primary party for a few reasons:
> 
> 1. This seems closer to how we currently use all claims in the token so easier migration path: A new-style token is exactly equivalent to an old-style token with the same readAs & actAs claims.
> 2. It means explicit party specifications only ever restrict the claims which seems somewhat simpler than being able to both extend & restrict claims that way.
> 
> More generally my intuition is that the primary party is used by tools that need to act as a single party but tools like the JSON API that already support multiple parties just use the actual claims.
> 
> I don’t feel super strongly about this though, just wanted to expand on why it does not match my intuition.

It's a valid point, thanks for raising this. I don't have a strong opinion on my proposal either, so I would simply leave the decision to either @davidrichards-da or @bame-da.

**Comment by stefanobaghino-da** [comment]
> @stefanobaghino-da I only have one concern, that the user token's validity is confirmed by the ledger server just as the claim token currently is.
> 
> Here is an example: suppose you [currently] query with a JWT with party foo against a configured query store. Technically, we may have the cached contracts already to respond to the request. _However_, we
> 
> 1. always update first, with the given JWT as authorization
> 2. fail to the client without doing any DB querying if that update fails
> 
> So the participant server still serves as gatekeeper, even for our own data.
> 
> 1. May this invariant be compromised in any way by the use of user tokens?
> 2. If so, what special extra steps need to be taken to ensure that the participant continues to serve as gatekeeper? (For example, this is why we do a party-subset check on readAs compared to the claim token for queries.)

Good point. I believe the validity of the token (against the `exp` field) will still be checked by the participant just as it does now, but I would like to ask @meiersi-da and @mziolekda for a confirmation.

**Comment by bame-da** [comment]
> It's a valid point, thanks for raising this. I don't have a strong opinion on my proposal either, so I would simply leave the decision to either @davidrichards-da or @bame-da.

The idea is that setting up a user with party sets for actAs and readAs on the API server and issuing a user token is equivalent to issuing a token with direct readAs and actAs claims. So in my opinion, unless the caller has specified actAs or readAs sets, queries and submissions should be made with the complete set of parties the token gives access to.

**Comment by stefanobaghino-da** [comment]
> > It's a valid point, thanks for raising this. I don't have a strong opinion on my proposal either, so I would simply leave the decision to either @davidrichards-da or @bame-da.
> 
> The idea is that setting up a user with party sets for actAs and readAs on the API server and issuing a user token is equivalent to issuing a token with direct readAs and actAs claims. So in my opinion, unless the caller has specified actAs or readAs sets, queries and submissions should be made with the complete set of parties the token gives access to.

Thanks, I updated the description accordingly. /cc @realvictorprm

**Comment by meiersi-da** [comment]
> Good point. I believe the validity of the token (against the `exp` field) will still be checked by the participant just as it does now, but I would like to ask @meiersi-da and @mziolekda for a confirmation.

Yes, the server checks the token's `exp` field on every request. In general, the server code remains the same wrt checking token validity. The only thing that changes is that a user tokens are supported in addition, and their associated rights are resolved by the server before checking a request authorization against these rights.

**Comment by stefanobaghino-da** [comment]
Thanks for confirming, Simon.
