### ISSUE TITLE
Discuss whether to move maven repo config to pom.xml

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1207]
Our Installation instructions currently instruct users to install Maven and change their global `settings.xml` file to include our Bintray repos.
I think it would be better to remove the settings.xml part and instead have a sample pom.xml that shows how to wire up repos, bindings, and codegen.

**Comment by gerolf-da** [comment]
I just ran `mvn clean compile` with an empty local maven repository and an empty `~/.m2/settings.xml` file successfully. So 👍  for removing the custom `settings.xml` instructions.

**Comment by bame-da** [comment]
That was on the quickstart project, I assume? I think we also need changes here: https://docs.daml.com/app-dev/bindings-java/index.html#getting-started

**Comment by bame-da** [comment]
nvm, should have looked at your PR first ;)
