### ISSUE TITLE
daml doc omits documentation in the presence of INLINE pragmas

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#1208]
Of the following three declarations, only the first one includes documentation for `f`:
```
class C a  where
    {-# INLINE f #-}
    -- | doc for f
    f : a -> a
```
```
class C a  where
    -- | doc for f
   {-# INLINE F #-}
    f : a -> a
```
```
class C a  where
    -- | doc for f
    f : a -> a
    {-# INLINE f #-}
```

This is rather confusing and interacts badly with our current practice of copying parts of the Haskell standard library. We should either fix this or make `INLINE` pragmas an error since they have no effect in DAML anyway afaik.

**Comment by associahedron** [comment]
I'm in favor of making `INLINE` pragmas an error if they just get ignored anyway.

**Comment by hurryabit** [comment]
If it is not too hard, I'd prefer to not fail on `INLINE` pragmas. We're still considering to compile some parts of DAML as Haskell. If/when we do this, the pragmas will become useful again.

**Comment by neil-da** [comment]
I'd be tempted just to grep the stdlib and delete INLINE from there, without banning INLINE pragmas, and without changing haddock in any way.

**Comment by neil-da** [comment]
No longer any INLINE pragmas, so not a big deal since #1233. My inclination would be to close this issue.

**Comment by cocreature** [comment]
Sounds good, we can always revisit it if we want to use INLINE pragmas. I doubt it will be hard to fix.
