### ISSUE TITLE
Meta: DAML Integration Toolkit Roadmap

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#121]
The roadmap for the DAML Integration Kit is now part of its documentation: see https://github.com/digital-asset/daml/blob/master/docs/source/daml-integration-kit/index.rst#status-and-roadmap

**Comment by meiersi-da** [comment]
@stefanobaghino-da : thanks for raising this. It seems that @gerolf-da removed the docs for the integration kit in 5592092cc718a25e5380380a18f3df3db45dd197.

@gerolf-da : where would you expect the docs for DAML Integrations to land with the Ledger API server proper?

**Comment by meiersi-da** [comment]
Note from discussion with @gerolf-da : will take it up with DAML on X team to see which parts of the docs to revive how.

**Comment by meiersi-da** [comment]
The link will be unbroken once the changes in #3292 have been released.

**Comment by gerolf-da** [comment]
Closing this as not relevant.
