### ISSUE TITLE
ledger api server: make ledger-id field optional in requests

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#12145]
The reason for making it optional is that for Canton there is only one global virtual ledger, so there's no need to identify that one ledger. Restrictions to specific participant nodes still work, and are recommended to be used where previously a ledgerId was used on purpose.

**Comment by stefanobaghino-da** [comment]
@mziolekda @meiersi-da I believe this was already fixed. Can you please confirm and possibly link this ticket to the PR that closed it?

**Comment by meiersi-da** [comment]
Thanks @stefanobaghino-da . This was solved in https://github.com/digital-asset/daml/pull/12243
