### ISSUE TITLE
Engine: Disabling Validation result in suboptimal compilation of structural record operations.

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#12153]
Ast expressions `EStructProj`and `EStructUpd`  are compiled deferentially depending on the variable field `var fieldIndex: Optional[Int]`.
- If `fieldIndex` is undefined the lookup of the field to update/project is done by name (i.e. linear in number of the structural  record fields) 
- If  `fieldIndex` is defined to an integer `idx`, this later is used as the field index to look up, resulting in constant time operation).

This field is undefined by default and is only set by the type checking pass. 
Therefore when the validation is skipped (by setting the field  `packageValidation`  to `false` in the `EngineConfig`), the compilation of  structural record of projection and update is sub-optimal.

**Comment by remyhaemmerle-da** [comment]
Thanks for that Martin !  ;)

**Comment by cocreature** [comment]
Do you have a good idea of what we can do about this? Originally we didn’t handle this case at all which crashed the scenario service which is clearly crap. Martin’s fix was then to compile it to a slower version.

Ideally we’d make validation fast enough that we can turn it on everywhere and never hit the slow case but I’m not sure that’s realistic.

**Comment by remyhaemmerle-da** [comment]
Here are some ideas on top of my head. Not sure if any of those are good.

1. We optimize the lookups by name in `com.daml.lf.Struct`. It should be possible to go form linear to logarithmic because fields  in `Struct` are sorted. Ideally logarithmic lookup is good enough, and we drop the current constant time optimization, and have all operation logarithmic. 

2. We require in a new LF version, that the compiler gives the field index (together or instead) of the filed name. 

3. We keep the type checking but disable other validation steps when `packageValidation` is set to `false`. I assume the type checking is the slowest phase, so I am not sure this is very useful.  

4. We implement a hopefully "cheap" pass that infer the types an set those field without doing a full type checking. 
  a. Hopefully this is fast enough. 
  b. We can possibly make this phase lazy, in the sens we trigger it only when we encounter one of those operations when compiling a Definitions and run the inference only on those definitions.

**Comment by remyhaemmerle-da** [comment]
An alternative to 1, is to keep in `SValueStruct` a lookup map (Map[Name, Int]) to get in constant time the field index given its name. However, we should take care to share those loop map and not constructing each time we have to build a `SValueStruct`.

**Comment by cocreature** [comment]
I think I missed an important point here: We don’t just hit this in the scenario service, we also hit it when we disable validation on the participant (because it’s redundant). Is that correct?

**Comment by cocreature** [comment]
I don’t think we can afford to slow down 1.14 so option 2 means we still have to deal with this in some form for 1.14.

**Comment by sofiafaro-da** [comment]
> An alternative to 1, is to keep in `SValueStruct` a lookup map (of type HashMap[Name, Int]) to get in constant time the field index given its name. However, we should take care to share those loop map and not constructing each time we have to build a `SValueStruct`.

I think this would be best. These lookup maps can be created during compilation of `EStructCon` and just passed along from then on in `SValueStruct`. You never have to modify or create new maps after compilation.

**Comment by remyhaemmerle-da** [comment]
> I think I missed an important point here: We don’t just hit this in the scenario service, we also hit it when we disable validation on the participant (because it’s redundant). Is that correct?

Yes. Participant can validate the packages before they are uploaded and then complelty skip validation in the Engine.

**Comment by remyhaemmerle-da** [comment]
> I don’t think we can afford to slow down 1.14 so option 2 means we still have to deal with this in some form for 1.14.

We can still force type checking for LF =< 1.14

**Comment by remyhaemmerle-da** [comment]
> I think this would be best. These lookup maps can be created during compilation of `EStructCon` and just passed along in the `SValueStruct`. You never have to modify or create new maps after compilation.

**Comment by cocreature** [comment]
> We could still force type checking for LF =< 1.14, independently of the value of the `packageValidation` flag.

fair but then we still slow down the scenario service and it seems pretty fishy logic in general to force validation only for certain LF versions.

**Comment by sofiafaro-da** [comment]
Another option is to do the slow linear lookup when executing `EStructProj`, but then cache the result. It should always be the same indexx.

**Comment by remyhaemmerle-da** [comment]
> I think this would be best. These lookup maps can be created during compilation of `EStructCon` and just passed along in the `SValueStruct`. You never have to modify or create new maps after compilation.

Exactly. in the same way we handle the field `fieldNames` in  ~`SValueStruct`~  `SStruct`.

This is relatively cheap to implement. @cocreature Do you think asking `team-kv-participant` to run their usual benchmark on a branch that implement this idea is enough to check for performance regression ?

**Comment by cocreature** [comment]
Sounds sensible to me.

**Comment by remyhaemmerle-da** [comment]
> Another option is to do the slow linear lookup when executing EStructProj for the first time, but then cache the index and reuse it after the first execution. It should always be the same index.

This is also an interesting idea (that can be combine with 1).

**Comment by remyhaemmerle-da** [comment]
>This is also an interesting idea (that can be combine with 1).

First lookups are logarithmic, following ones are constants. 
On the other, this make the first call slow, what we exactly try to speed up by skipping validation.

**Comment by sofiafaro-da** [comment]
> On the other, this makes the first call potentially slow, what we exactly try to speed up by skipping validation.

If you combine with 1, it's the same as 1 for the first call, constant time afterwards.

**Comment by sofiafaro-da** [comment]
What I meant to say: *If you combine with the hashtable lookup approach, it's the same as a hashtable lookups for the first call, and constant time afterwards.

**Comment by remyhaemmerle-da** [comment]
> If you combine with the hashtable lookup approach, it's the same as a hashtable lookup for the first call, and constant time afterwards

I completely agree.

I was just trying to underline, that the interpretation of the command made by a freshly started engine can still be *theoretically* way slower than once the engine have been warmup. One of the main objectives of the validation omission was to make the processing of the first commands as fast as possible, so the solution you propose may *theoretically* defeat the purpose of package validation ommision.

Hopefully, in normal condition the interpretation of a command using logarithmic lookups is still way faster than the compilation of packages, so this is not an *practical* issue.

**Comment by remyhaemmerle-da** [comment]
fixed by 12338
