### ISSUE TITLE
[BUG] Script service timeout errors

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12194]
**Affected Daml version**
1.18.0 and newer

**Bug description**

Since 1.18 a lot of users seem to be getting timeouts in vscode, see https://discuss.daml.com/t/scenariobackendexception-in-daml-studio-error-again/3546/16.

**Comment by cocreature** [comment]
@akrmn https://discuss.daml.com/t/daml-repl-error-berrorclient-clientioerror-grpciotimeout/3599/9?u=cocreature looks related and potentially easier to debug & bisect (no LSP involved). The repro still doesn’t work for me though but that would match up my suspicion that it’s macos related.

**Comment by akrmn** [comment]
so far I haven't been able to reproduce either, I tried both Shaul's example and the "Fix my bike" tutorial. Thanks for the other thread, it does seem related indeed. I'll check it out next and update you later

**Comment by akrmn** [comment]
as discussed elsewhere, I wasn't able to reproduce with `DAML_SDK_VERSION=1.18.0 daml repl < <(sleep 200; echo 'map (2*) . join $ [[1,2,3],[4,5,6]]')` either :(

**Comment by cocreature** [comment]
I’d suggest adding logging to the client and server side of the grpc connection to the scenario service and then we can ask people that can reproduce this to rerun it with the logs. If you do want to play around with changing the timeout it’s defined in https://github.com/digital-asset/daml/blob/7c011cfb389fc3f29a23b3479159c0532b3b5b3f/compiler/scenario-service/client/src/DA/Daml/LF/ScenarioServiceClient/LowLevel.hs#L74

**Comment by cocreature** [comment]
I’d recommend that we first try to repro against 1.18.0 and not HEAD just to make sure we didn’t accidentally fix it there.

**Comment by akrmn** [comment]
couldn't repro on 1.18.0 obtained from https://docs.daml.com/getting-started/installation.html#mac-and-linux

**Comment by cocreature** [comment]
So to summarize, this is what we found out:

1. The issue got introduced by #11031 which switched to the nix-built gRPC which is dynamically linked.
2. It only arises when you use the damlc-dist tarball (and therefore also the SDK tarball). It does not arise when run via `bazel run damlc`. The difference between the two is how we link dynamic libraries specifically grpc.
3. It only is an issue on Monterey not on older MacOS versions (and therefore also not on other platforms).
4. The REPL command seems pretty reproducible but it only happens after a certain delay which seems around 2min. Daml studio seems to behave similarly, things work for a while and then stop working.
5. Reverting to the bazel-built grpc fixes things (so it’s not an issue in the grpc version).

I’d recommend that we do the following:
1. Merge the revert immediately given that this is a pretty bad bug. I’ll check with product if we’ll cut an 1.18.1 for this.
2. From there on we then need to find a solution that allows our macos devs to use ghci. We have two options here: Either we get the bazel-built grpc to work with ghci or we switch back to the nix-built one and fix the issue somehow. My preference is for the former since i think overall, this is a more sensible and simpler setup. So I’d suggest the following steps:
3. First, on current main with the bug get the output from `package-app.sh` and link it here just so we can see if there’s any quick fix for the nix-built one.
4. Check what the current error is that we get on ghci, assuming it still fails and hasn’t been fixed by any changes in the meantime. Record the error here.
5. If we still get the error, I’d try to upgrade to GHC 9.0.2 first. There is a reasonable chance things have changed there and maybe even been fixed so I’d rather debug on that. Ping me on Slack if you have questions for how to do this.
6. Check the error on GHC 9.0.2 and figure out a solution hopefully?

Does that seem sensible @akrmn?

**Comment by akrmn** [comment]
it does! thank you for the great summary. I'll merge the revert now since we've got confirmation that it fixes the issue for Gary

**Comment by akrmn** [comment]
unclosing, since we're not 100% sure why the fix works/why it's needed

**Comment by akrmn** [comment]
> 4. Check what the current error is that we get on ghci, assuming it still fails and hasn’t been fixed by any changes in the meantime. Record the error here

It looks like a linking problem, with quite a few symbols with duplicate definitions:

```
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   ___clang_call_terminate
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN4absl12lts_2021032413InlinedVectorIN9grpc_core13ServerAddressELm1ENSt3__19allocatorIS3_EEED1Ev
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN9grpc_core14MakeOrphanableINS_18ChildPolicyHandlerEJNS_19LoadBalancingPolicy4ArgsEPNS_9TraceFlagEEEENSt3__110unique_ptrIT_NS_16OrphanableDeleteEEEDpOT0_
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN9grpc_core33ConnectivityStateWatcherInterface6OrphanEv
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN4absl12lts_2021032413InlinedVectorIN9grpc_core13ServerAddressELm1ENSt3__19allocatorIS3_EEEaSEOS7_
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN9grpc_core13RefCountedPtrINS_9XdsClientEED1Ev
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN9grpc_core4JsonD2Ev
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN4absl12lts_2021032413InlinedVectorIN9grpc_core6XdsApi9EdsUpdate8PriorityELm2ENSt3__19allocatorIS5_EEEaSEOS9_
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN4absl12lts_2021032423inlined_vector_internal15DestroyElementsINSt3__19allocatorIN9grpc_core12XdsBootstrap9XdsServerEEEPS7_mEEvPT_T0_T1_
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN9grpc_core4JsonC1EPKcb
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN9grpc_core14MakeRefCountedINS_29AwsExternalAccountCredentialsEJNS_26ExternalAccountCredentials7OptionsENSt3__16vectorINS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS9_ISB_EEEERPP10grpc_errorEEENS_13RefCountedPtrIT_EEDpOT0_
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN17grpc_auth_contextD2Ev
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN23grpc_server_credentialsD0Ev
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN32grpc_tls_certificate_distributor15CertificateInfoD2Ev
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN4absl12lts_2021032413InlinedVectorIN9grpc_core14PemKeyCertPairELm1ENSt3__19allocatorIS3_EEEaSEOS7_
```

Full output: [da-ghcid.out.txt](https://github.com/digital-asset/daml/files/7821661/da-ghcid.out.txt)

**Comment by akrmn** [comment]
> 3. First, on current main with the bug get the output from package-app.sh and link it here just so we can see if there’s any quick fix for the nix-built one. I’d also like to see a directory listing of the damlc tarball on macos.

Output from `package-app.sh` on `origin/main` d4ebce6f4446c9f4744ed610cfb83161a8640d16: [package-app-main.out.txt](https://github.com/digital-asset/daml/files/7821710/package-app-main.out.txt).

Contents of the damlc tarball:
```
damlc
├── damlc
├── lib
│   ├── libc++.1.0.dylib
│   ├── libc++abi.dylib
│   ├── libcharset.1.dylib
│   ├── libffi.8.dylib
│   ├── libiconv-nocharset.dylib
│   ├── libiconv.dylib
│   └── libncursesw.6.dylib
└── resources
    ├── d3.min.js
    ├── d3plus.min.js
    ├── daml-base-anchors.json
    ├── dlint.yaml
    ├── ghc-pkg
    ├── ghcversion.h
    ├── hpp
    ├── lib
    │   ├── libHSCabal-3.2.1.0-ghc8.10.7.dylib
    │   ├── libHSarray-0.5.4.0-ghc8.10.7.dylib
    │   ├── libHSbase-4.14.3.0-ghc8.10.7.dylib
    │   ├── libHSbinary-0.8.8.0-ghc8.10.7.dylib
    │   ├── libHSbytestring-0.10.12.0-ghc8.10.7.dylib
    │   ├── libHScontainers-0.6.5.1-ghc8.10.7.dylib
    │   ├── libHSdeepseq-1.4.4.0-ghc8.10.7.dylib
    │   ├── libHSdirectory-1.3.6.0-ghc8.10.7.dylib
    │   ├── libHSfilepath-1.4.2.1-ghc8.10.7.dylib
    │   ├── libHSghc-boot-8.10.7-ghc8.10.7.dylib
    │   ├── libHSghc-boot-th-8.10.7-ghc8.10.7.dylib
    │   ├── libHSghc-prim-0.6.1-ghc8.10.7.dylib
    │   ├── libHSinteger-simple-0.1.2.0-ghc8.10.7.dylib
    │   ├── libHSmtl-2.2.2-ghc8.10.7.dylib
    │   ├── libHSparsec-3.1.14.0-ghc8.10.7.dylib
    │   ├── libHSpretty-1.1.3.6-ghc8.10.7.dylib
    │   ├── libHSprocess-1.6.13.2-ghc8.10.7.dylib
    │   ├── libHSrts-ghc8.10.7.dylib
    │   ├── libHStemplate-haskell-2.16.0.0-ghc8.10.7.dylib
    │   ├── libHSterminfo-0.4.1.4-ghc8.10.7.dylib
    │   ├── libHStext-1.2.4.1-ghc8.10.7.dylib
    │   ├── libHStime-1.9.3-ghc8.10.7.dylib
    │   ├── libHStransformers-0.5.6.2-ghc8.10.7.dylib
    │   ├── libHSunix-2.7.2.2-ghc8.10.7.dylib
    │   ├── libcharset.1.dylib
    │   ├── libffi.8.dylib
    │   ├── libiconv-nocharset.dylib
    │   ├── libiconv.dylib
    │   └── libncursesw.6.dylib
    ├── pkg-db_dir
    │   ├── 1.14
    │   └── 1.dev
    ├── repl-service.jar
    ├── scenario-service.jar
    └── stable-packages
        ├── daml-prim
        └── daml-stdlib
```

**Comment by cocreature** [comment]
> It looks like a linking problem, with quite a few symbols with duplicate definitions:

interesting, that’s at least easier to look into that random segfaults which I remembered. I’d still suggest we upgrade to 9.0.2 first though.

**Comment by cocreature** [comment]
Closing in favor of #12452 since the issue title isn’t really reflecting the issue we have anymore. Thanks a lot for fixing this @akrmn
