### ISSUE TITLE
Reduce the Azure Pipeline build times

### ISSUE THREAD

**Issue by jonas-chevalier-da** [digital-asset/daml#122]
A noop build takes 33min. Break down:
* 8min: download the nix closures from the binary cache (aka dev-env)
* 25m: the bazel ./build.sh

It would be good to figure out why the builds are taking so long.

**Comment by aherrmann-da** [comment]
I compared a local build with the Azure execlog. There are a few inhermeticities, but the vast majority of time was spent fetching from cache. For me a clean build from remote cache took 17min. Once the disk cache was populated it went down to ~5min.

**Comment by aherrmann-da** [comment]
@jonas-chevalier-da 
> Is it possible to force bazel to linearize the builds?

Bazel takes the `-j` flag.
```
--jobs [-j] (an integer, or a keyword ("auto", "HOST_CPUS", "HOST_RAM"), optionally followed by an operation ([-|*]<float>) eg. "auto", "HOST_CPUS*.5"; default: "auto")
    The number of concurrent jobs to run. Takes {@value FLAG_SYNTAX}. Values
    must be between 1 and5000 values above 2500 may cause memory issues. "auto"
    calculates a reasonable default based on host resources.
      Tags: host_machine_resource_optimizations, execution
```

**Comment by cocreature** [comment]
Closing since this ticket hasn’t seen any interest recently and a lot of things have changed since.
