### ISSUE TITLE
[BUG] Separate Maven Central Staging profile id for com.digitalasset

### ISSUE THREAD

**Issue by nycnewman** [digital-asset/daml#12202]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

# Affected Daml version

Latest version to publish to Maven Central

# Bug description

Enter here a clear and concise description of what the bug is.

The Upload.hs needed to be fixed as part of move to s01.oss.sonatype.org However it adds a single value for staging profile ID. Needs to support a second value of "5fcdf3c9972bd4"

# To reproduce

Attempt to publish to com.digitalasset will fail

# Expected behavior

Enter here a clear and concise description of what you expected to happen.

Will allow publishing to com.digitalasset if we chose to in future.

# Additional context

Add here any other context about the problem here.
This includes but is not limited to:
- OS information
- Daml code relevant to reproduce the faulty behavior
- logs in textual format containing relevant information
- for Navigator or the documentation: screenshots

**Comment by cocreature** [comment]
fixed by https://github.com/digital-asset/daml/pull/12203 , if we don’t publish to com.digitalasset we cannot use the wrong profile id :)
