### ISSUE TITLE
[BUG] Navigator does not show all contracts

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#12218]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

# Affected Daml version

1.18.0

# Bug description

After running a lot of trades on Sandbox, Navigator doesn't show any active assets anymore, but Daml Repl does.

# To reproduce

Add here the steps to reproduce the faulty behavior:
1. Write a simple settlement application
2. Write triggers to put through lots and lots of trades
3. Halt automation
4. Look at active Assets in Navigator and Repl

None shown in Navigator (but 100s of archived ones...)
![image](https://user-images.githubusercontent.com/40762178/146820417-17a19271-d6d8-4417-965f-f81da0017ab8.png)

Correct six shown in Repl:

```
daml> listKnownParties
[PartyDetails {party = 'party-33195da8', displayName = Some "Bob", isLocal = True},PartyDetails {party = 'party-66669ef3', displayName = Some "Alice", isLocal = True},PartyDetails {party = 'party-84d2d630', displayName = Some "Bank", isLocal = True},PartyDetails {party = 'party-d98b36bb', displayName = Some "Street", isLocal = True}]
daml> query @Asset (partyFromText "party-66669ef3")
[(0037f9dcade884b98ffa133e83e6a2b2ae9127fa3db06fd557a531806f427a3be6,Asset {issuer = Set ['party-84d2d630'], symbol = "Security B", owner = Set ['party-66669ef3'], reference = None, quantity = 1051.8072747682, observers = Set []}),(0052833dda8acdcf8f5a10ee53b10b0581259ef6496c25ea2c0e378c57664a1f29,Asset {issuer = Set ['party-84d2d630'], symbol = "Security A", owner = Set ['party-66669ef3'], reference = None, quantity = 973.7719884059, observers = Set []}),(0033e862c38797ba6d681cc4cbea9357c8976862e64e7550eab5394676449d8941,Asset {issuer = Set ['party-84d2d630'], symbol = "Security A", owner = Set ['party-66669ef3'], reference = None, quantity = 1.5002758258, observers = Set []}),(00187996d9b6fb8e99d9e08a0f0656e804342130d7179fc2388df9473807207388,Asset {issuer = Set ['party-84d2d630'], symbol = "USD", owner = Set ['party-66669ef3'], reference = None, quantity = 999975.453109953, observers = Set []}),(00f1bc1650a52955683c1490333a4dcf53abea0bcc4aee05e94d2b46961be487de,Asset {issuer = Set ['party-84d2d630'], symbol = "Security B", owner = Set ['party-66669ef3'], reference = None, quantity = 1.245524, observers = Set []})]
```

# Expected behavior

Navigator should show the six asset contracts.

**Comment by cocreature** [comment]
are you sure it isn’t just a matter of time? Navigator streams from ledger begin so it can potentially get very very slow if you have lots and lots of trades.

**Comment by bame-da** [comment]
The numbers shown on the Templates screen are no longer moving. And there is no point in time on the ledger when there should be zero active assets.

**Comment by cocreature** [comment]
thx for the clarification. Could you share the example you used to reproduce this?

**Comment by bame-da** [comment]
1. Check out this repo/branch: https://github.com/DACH-NY/asset-refapp/tree/trade-sharder
2. Follow //SettlementDemo/Readme.md to build and run the demo
3. Log into Navigator as "Bank" and go to the Templates screen. Observe the crazy numbers of Asset contracts (I assume they include archived?)
4. After a while, stop the automation.
5. Click on the little hand symbol with the numbers to see only Asset contracts, or go to this URL with the package id appropriately amended: http://localhost:7500/templates/Asset:Asset@27b38c29e1207bb3b3fcd4dc7936664e025a9ec56a69e1fcd6673194a25169bf/contracts/
6. Untick "Include archived". Observe some random small selection of assets, if any.
7. Run Daml Repl using the command in the readme. Get the issuer/bank party id from `listKnownParties` or the output of the setup script
8. Look at the output of `query @Asset issuer` and observe a completely different number of assets.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
