### ISSUE TITLE
`damlc clean` command to clean up package database and dist folder.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1223]
For #644 I was thinking of implementing a `daml clean` command in daml-helper but this really belongs in `damlc`, which generates all the artifacts. Then once it's available it can be exposed in the assistant through the usual means (changing `releases/sdk-config.yaml`).

This command should remove any build artifacts -- `.package-db` and `dist/`.

It should fail if run outside a project. It should succeed if there are no build artifacts present (like `rm -f`).

cc @robin-da

**Comment by neil-da** [comment]
I'd have thought that there should be some convention for where generated stuff goes, e.g. in `dist` or something like that, and then `daml clean` would clear out all generated stuff. That includes compiler generated stuff for now, but one day it might include other stuff.
