### ISSUE TITLE
Better update-check logic in daml-assistant.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1225]
via @neil-da: The "latest version" data should persist even if the automatic update check is disabled. There should also be a command that ensures this data is up-to-date.

via me: The automatic update check should not block the rest of the assistant from doing its job, it should run asynchronously in the background and update the stored data.

via me from the future: We should get versions.json from docs.daml.com (see #1097) instead of relying on hacky github redirection to get the latest available version. We can always use the hacky github redirection trick as a backup.

**Comment by neil-da** [comment]
via future me: the complexity required for doing two approaches with a backup probably isn't worth it.

current me: i love the github redirection trick, it's super cool. although that's not necessarily the engineer part of me that should be listened to.

**Comment by associahedron** [comment]
the future is now :-) time to implement this.
