### ISSUE TITLE
[FEATURE REQUEST] Make the acting party available in the Trigger init and update functions

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#12277]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

### What is the problem you want to solve?

As per https://discuss.daml.com/t/do-daml-triggers-give-any-guarantees-on-how-often-the-rule-is-called/3662/2, I would like to keep my precise state as custom state in a Daml trigger. My state is filtered on the acting party so I need to know the acting party in the update function. Unfortunately, I only have access to the acting party in the rule function and afaict, there is no guarantee that the rule is called before the update. Therefore I cannot adequately build my sate.

### What is the solution you would propose?

Add a function `getParty` to all the trigger actions. At a minimum to TriggerUpdateA.

### Describe alternatives you've considered

1. Guarantee that the rule is called before the first update so I can write the party to my custom state. I like that less as I then have to store it myself.
2. Add the party as a function argument as for the rule. Seems inconsistent with all other provided state.

### Additional context

Add here any additional context about the feature request.

**Comment by cocreature** [comment]
@bame-da is this a duplicate of #12125 or am I missing something here?

**Comment by bame-da** [comment]
Oh yes, apologies.
