### ISSUE TITLE
Sandbox is slow to spin up, and slow to respond to first submit.

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#1230]
It takes about 1.5s for the initial spin up (until the "listening on port" message is printed). Then, it takes another 1.5s to respond to the first call to the command submission service. (Following submissions are much quicker at around 1/100s). The lag of 1.5s for the first submit is not reduced even if we pause for a few second between spinup & submit.

These numbers were discovered while writing unit tests for the haskell ledger bindings.  To get isolation, it is convenient to spin up a new sandbox for each test.

**Comment by bitonic** [comment]
@nickchapman-da those number are not unexpected: JVM applications are notoriously slow to start (1.5 seconds seems perfectly in line with the sad status quo), and packages are loaded lazily, which means that we'll compile the relevant package when the first message arrives.
