### ISSUE TITLE
Packages loaded to run scenarios are discarded after compilation

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#1238]
In order for a scenario to be ran, the engine loads and compiles the relevant packages to its internal representation. This is then discarded, meaning that the packages need to go through the same compilation phase again when commands are issued.

Keeping the internal representation after the scenario evaluation could improve sandbox startup latency, in particular when testing.

**Comment by bitonic** [comment]
#1248 fixed this.
