### ISSUE TITLE
Fold `damlc compile` into `damlc build` with flags.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1242]
Suggested by @neil-da  and @cocreature : 

> 
> neil   [3 days ago]
> Can anyone explain why we have `daml build` and `daml compile` that do different things?
> 
> 
> not-fran   [3 days ago]
> We don't have `daml compile`? Last I checked.
> 
> not-fran   [3 days ago]
> Are you on an older SDK version (pre 0.12.15)?
> 
> neil   [3 days ago]
> `damlc compile`?
> 
> not-fran   [3 days ago]
> `damlc build` knows about DAML projects and takes care of packaging (it's just `daml build`), I think `damlc compile` is a lower level interface. (@robin knows)
> 
> robin   [3 days ago]
> `damlc compile` doesn't initialize the package db
> 
> moritz.kiefer   [3 days ago]
> and it produces a dalf instead of a dar
> 
> moritz.kiefer   [3 days ago]
> `damlc build` is roughly initialize package db, call compile to build a dalf, wrap the dalf in a fat dar
> 
> moritz.kiefer   [3 days ago]
> I’d argue that having `compile` is useful at the very least for debugging but the name sucks
> 
> neil   [3 days ago]
> Build --dalf seems more reasonable
> 
> moritz.kiefer   [3 days ago]
> sounds good and maybe a `--initialize-package-db=no` flag

**Comment by cocreature** [comment]
#1291 addresses part of this but we decided to keep `damlc compile` for now as an internal command since it can be useful for testing and replicating that functionality in `damlc build` leads to an awkward interface.
