### ISSUE TITLE
ledger-api-test-tool gets stuck at exit, unless GC is forced

### ISSUE THREAD

**Issue by gleber-da** [digital-asset/daml#1243]
This is an instance of
https://github.com/scalatest/scalatest/issues/1175

Worked around by forcing GC at the end of the tool run. There are no public APIs in scalatest to make this work reliably otherwise.

**Comment by gleber-da** [comment]
@gaboraranyossy-da @gerolf-da @dajmaki

**Comment by stefanobaghino-da** [comment]
No longer a valid ticket, closing.
