### ISSUE TITLE
docs: change https://docs.daml.com/app-dev/bindings-java/index.html to explain how to authorize requests

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#12441]

**Comment by stefanobaghino-da** [comment]
@meiersi-da What did you mean here exactly? The fact that one is using user or claims token is completely transparent to the bindings. Or am I missing something?

**Comment by stefanobaghino-da** [comment]
> You are right. The page reads well as is. Sorry for the noise.

Nothing to be sorry for, thanks for the clarification.
