### ISSUE TITLE
[BUG] interfaces `implements` keyword doesn't accept qualified name

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/daml#12470]
sdk-version: 2.0.0-snapshot.20220110.8812.0.3a08380b

For instance

```haskell
template Currency
  with
    denomination : Text
    issuer : Party
    investors : Parties
  where
    signatory issuer
    implements Issuable where
```
works fine, however `implements Issuable.I where` or `implements Issuable.Issuable where` doesn't.

```shell
error: parse error on input ‘Issuable.I’
```

**Comment by cocreature** [comment]
@akrmn could you please look into that after the serializability checks?

**Comment by akrmn** [comment]
@lucianojoublanc-da this should be working in HEAD now
