### ISSUE TITLE
package management tooling

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#125]
### Package management tooling

This is a stub to collect ideas on how to provide daml package management tooling and infrastructure.

We need a solution to

- Tooling to install daml packages created by the user to a local package database
- Provide a daml package repository
- Tooling to install daml packages to a local package database from a remote repository

We need to keep in mind that we will have to provide a solution to upgrade existing contracts in a system.

**Comment by cocreature** [comment]
Parts of this have been addressed and parts of it have been merged into other issues so I’m closing this.
