### ISSUE TITLE
Transaction service accepts requests without parties and returns an empty stream

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#1250]
The transaction service currently accepts a `SubmitRequest` with a [filter](https://docs.daml.com/app-dev/grpc/proto-docs.html#com-digitalasset-ledger-api-v1-transactionfilter) with an empty set of parties and returns an empty stream. Probably a better approach would be requiring at least one party to be there to subscribe to and return an error if it's not there, rather than opening (and possibly keeping it that way) an empty stream. This would ensure that the user gets an immediate feedback, rather than (possibly mistakenly) subscribing to a feed that will always be empty.

Another possible approach could be changing the semantics of an empty set of parties to mean "subscribe to all transactions over which I have visibility", but I'm not sure this would be desirable.

**Comment by bitonic** [comment]
I'd be OK with this, @gaboraranyossy-da and @gerolf-da should weigh in.

**Comment by gerolf-da** [comment]
Sure, as of right now, there is no situation where a request with no party filter would ever return any data. Question is whether we want to reject the request with BAD_REQUEST (my preferred method) or simply respond with an empty stream that is also closed (yet again slightly surprising behavior).

**Comment by gaboraranyossy-da** [comment]
I vote for BAD_REQUEST

**Comment by stefanobaghino-da** [comment]
BAD_REQUEST it is then, a PR is coming soon, thanks for the input. :pray:

**Comment by stefanobaghino-da** [comment]
I don't see a `BAD_REQUEST`, maybe you were referring to this? Seems apt.
```
    /**
     * Client specified an invalid argument.  Note that this differs
     * from FAILED_PRECONDITION.  INVALID_ARGUMENT indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     */
    INVALID_ARGUMENT(3),
```
