### ISSUE TITLE
bug: unexpected 'expected serializable type'

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#12665]
Reported by @GeorgSchneider 

the serializability check complains about unserializable interfaces even inside a `ContractId`, which should be serializable.

```
ScenarioBackendException {scenarioNote = "Failed to create scenario context", scenarioBackendError
  = BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusInternal (StatusDetails {unStatusDetails
  = "java.lang.IllegalArgumentException: validation error in data type
  Daml.Finance.Derivative:Instrument: expected serializable type:\r\n * reason: unserializable data
  type Daml.Finance.Interface.Issuable:Issuable\r\n * found: Daml.Finance.Derivative:Instrument\r\n
```

https://github.com/DACH-NY/sales-eng/tree/experimental
sdk-version: `2.0.0-snapshot.20220127.9042.0.4038d0a7`

**Comment by cocreature** [comment]
Can you reproduce this with `daml build` and then loading the resulting DAR into a sandbox?

**Comment by akrmn** [comment]
The problem turned out to be that the Haskell serializability checks were in `2.0.0-snapshot.20220127.9042.0.4038d0a7` but the corresponding Scala checks weren't. Testing the same repository on daml HEAD showed no serializability errors, so the reporter is simply advised to stay on a working snapshot until the next one is released.
