### ISSUE TITLE
Support pagination for user management in Daml Script

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12663]
https://github.com/digital-asset/daml/pull/12610#discussion_r794432158 introduces pagination in the ledger API. We need to figure out what we do in Daml Script.

Intuitively, I’d suggest to rename `listUsers` to `listAllUsers` and handle pagination by concatenating all pages in the grpc client.
We can think about exposing a paginated API post 2.0.

**Comment by cocreature** [comment]
@nickchapman-da can you please take a look at this? wdyt of my `listAllUsers` suggestion?

**Comment by nickchapman-da** [comment]
> @nickchapman-da can you please take a look at this? wdyt of my `listAllUsers` suggestion?

Makes sense. Quite a few files are touched so I'll do it in a separate PR.

**Comment by cocreature** [comment]
Closing this for now, I think this covers everything we need for 2.0. If we want to expose pagination at som epoint, we can do that in a separate issue.
