### ISSUE TITLE
Add linter based on HLint

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#1266]
We should add a linter to DAML based on HLint. That involves:

* [X] Convert upstream HLint to parse using ghc-lib-parser.
* [ ] Convert upstream HLint to use the GHC parse tree.
* [ ] Provide an HLint API on the GHC parse tree.
* [ ] Write a command line tool to run HLint on DAML.
* [ ] Add DAML specific hints.
* [ ] Integrate into the IDE.

This work is actively in progress, but involves a number of moderately large engineering steps.

**Comment by cocreature** [comment]
Fixed thanks to @shayne-fletcher-da!
