### ISSUE TITLE
Add signatories and observers to `CreatedEvent`s in API

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1269]
In order to know whether I need to disclose a contract to a counter-party or not, I need to know whether the counter-party is already an observer. Since `signatory` and `observer` in DAML take arbitrary expressions, computing the observers of a contract instance in the application layer is difficult. I would therefore like to receive them as part of the `CreateEvent` of the instance.

**Comment by bame-da** [comment]
As discussed, @stefanobaghino-da

**Comment by gyorgybalazsi** [comment]
Hi guys, I'm glad this issue has already been opened. Do you plan to include into it the feature that the Navigator UI displays the observers to a contract? I'd like to see that feature for a project of mine.

**Comment by stefanobaghino-da** [comment]
That would be the idea, yes, thanks for bringing this up.

**Comment by stefanobaghino-da** [comment]
@gyorgybalazsi Took a while, should be available from the next release (current is 0.13.7).

**Comment by gyorgybalazsi** [comment]
@stefanobaghino-da cool, will check it out asap!
