### ISSUE TITLE
Add choices with controllers to `CreatedEvent` in API

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1271]
I would like to indicate which actions a user can take in the API. e.g., I would like to only show those choices in the Navigator that the logged in party is actually authorised to exercise.
Right now, that would require me to replicate the `controller` expressions in my application code. I'd much rather get a list of available choices with their respective controllers as part of the `CreateEvent`.

For flexible controllers, this is not possible, but we should do this on a best-effort basis, giving the list of controllers for `controller (f this) can` syntax.

**Comment by bame-da** [comment]
@stefanobaghino-da as discussed.

**Comment by hurryabit** [comment]
For a choice whose controllers depend on the choice argument, we should always assume it is exercisable by the party logged into navigator. Also, choices with more than one controller are never exercisable over the Ledger API.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
