### ISSUE TITLE
Request for Updated Daml Release Version in Documentation

### ISSUE THREAD

**Issue by benm-da** [digital-asset/daml#12728]
I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

### What is the problem you want to solve?
Referring to [Manually Installting the SDK](https://docs.daml.com/getting-started/manual-download.html), the current documents reference "the latest release (1.4.0 at the time of writing)."

### What is the solution you would propose?
Upgrade the relevant Daml documentation to reflect the current stable version: 1.18.1

### Additional context
The instructions are also MACOS specific, and while that is the dominant Development platform internally, versions of GNU/Linux are common externally for developers, professional or not.

Accordingingly, in addition to the potential `daml-sdk-1.8.1-macos.tar.gz` and `daml-sdk-1.8.1-macos.tar.gz.asc` code references, could we please also get the Linux equivalents?

**Comment by cocreature** [comment]
I don’t think we need to update this. The instructions aren’t specific to any given version. We specifically included "at the time of writing" so we don’t have to update this each release.

I think making it explicit how things work outside of macos is defintely worth doing but please open a separate issue for that.

**Comment by benm-da** [comment]
Noted. I will open a seperate issue for the non-MACOS query.
