### ISSUE TITLE
DAML-on-X integration steps

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#1273]
(all the class / trait names below are provisional)

We have three traits:

* `WriteService`: allows to submit transactions;
* `ReadService`: streams out ledger updates;
* `IndexService`: allows to read data in a way that lets us implement the Ledger API.

The first milestone is to make sure that the Ledger API server is implemented _only in terms of `WriteService` and `IndexService`_. Note that the `ReadService` is not relevant for the Ledger API itself, but just to be able to decouple the `WriteService` and the `IndexService` (more on this later).

The first step towards integration with DAML-on-X is to implement:

* [x] Have the Ledger API service to work _only_ in terms of `WriteService` and `IndexService`.
* [x] `InMemoryWriteAndIndex`: implements `WriteService` and `IndexService` backed by a single in-memory data structure. It will power the default mode of operation of the sandbox.
* [x] `PostgresWriteAndIndex`: implements `WriteService` and `IndexService` backed by a single Postgres database. It is the all-in-one backend with Postgres, which will power the Postgres-backend sandbox;
* [x] Allow the user to choose between `InMemoryWriteAndIndex` and `PostgresWriteAndIndex`.

related PRs: #1193 #1240 #1278 #1314 #1362 #1403 #1426 #1465 #1476 #1524 #1555 

UPDATE: the final class implementing what's above is [SandboxIndexAndWriteService](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/SandboxIndexAndWriteService.scala).
***
The second step is concerning separating the `WriteService` and `ReadService` from the `IndexService`:

* [x] `PostgresIndexer`: takes a `ReadService` and writes to a database that will be used by `PostgresIndex`;
* [x] `PostgresIndex`: implements `IndexService` on top of the database written by the `PostgresIndexer`.

related PRs: #1978, #2262
To test the `PostgresIndexer` and `PostgresIndex` we'll use the reference implementation of the read / write service from DAML-on-X.

Blocking issues:
* #2065: Recover from failures in `PostgresIndexer`

Note that in the future, we might want to implement a `PostgresRead` and `PostgresWrite` where all the synchronization is done on the database. This would allow horizontal scaling of ledger API servers backed by posgres since there would be no synchronization done in memory.
***
The third step concerns the replacement and decommissioning of the Ledger API server

- [x] replace `//ledger/api-sever-damlonx` with Sandbox-based ledger API server
- [ ] enable all tests in Ledger API test tool and fix problems with both Sandbox and `//ledger/api-server-damlonx/reference` implementation
- [x] also run test tool against sandbox and remove the tests run by the test tool from the Sandbox IT suite

**Comment by meiersi-da** [comment]
AFAIK, the last steps have not yet been completed. However, they are also captured in #2557 in additional detail. I'd vote to use that one to complete the tracking of these steps.

@gerolf-da are there other steps in this issue apart from the last ones that are missing?

**Comment by gerolf-da** [comment]
@meiersi-da: the only thing that's missing is to port all the remaining integration tests. As far as I can tell, all the tests that have been ported already are run against the daml-on-x reference server as well as the sandbox in various configurations (static-time vs. wall-clock, h2 vs. postgres vs. in-memory).

**Comment by meiersi-da** [comment]
Thanks @gerolf-da . In favor of clarity, could you add the description of this ticket, or link to a ticket that tracks the remainder of the integration tests being ported?

**Comment by stefanobaghino-da** [comment]
#1373 tracks the most relevant ones. We do not have a ticket to track them all at the moment, but I would suggest opening a ticket for individual test suites once we are done porting those tracked there. Coupled with a milestone it would make it easy to track the progress.

**Comment by meiersi-da** [comment]
Thanks @stefanobaghino-da . I've just seen that the milestone you are talking about already exists here: https://github.com/digital-asset/daml/milestone/16

I've added #2557 to milestone: https://github.com/digital-asset/daml/milestone/15

And close this issue, as the only remaining part is #2557.
