### ISSUE TITLE
[FEATURE REQUEST] ListKnownPartiesRequest does not work well with large numbers of parties

### ISSUE THREAD

**Issue by daravep** [digital-asset/daml#12738]
The party management endpoint allows me to fetch all known parties on a participant node. 

```
message ListKnownPartiesRequest {
}
```

However, on a node with 120k parties, I do get the expected

```
2022-02-03 13:40:52,420 [⋮] ERROR c.d.c.p.PerformanceRunner:participant2 - Terminated with an exception
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 16000679
```

as there are too many parties registered. As the return value of such a request can be potentially unbounded, I would request the following change additional query arguments:

```
message ListKnownPartiesRequest {
   string filterParty = 1;   
   int32 limit = 2; // default to 100
}
```

The response should include an additional flag to indicate if the limit was reached (and that the response would have returned more if it could)

This change would support running nodes with many parties.

**Comment by cocreature** [comment]
That’s just one of the solutions discussed in there. I’d rather group issues by problem we’re trying to solve not by possible solution before having agreed on which one we take.

**Comment by daravep** [comment]
Okay. Then I'll close this in favour of https://github.com/digital-asset/daml/issues/10283
