### ISSUE TITLE
Add coerce for contract ids to DAML-LF

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#1277]
For the implementation of generic templates, we need two changes to DAML-LF:
1. We need to add a builtin `coerceContractId :: ContractId a -> ContractId b`. This is fine since we have a runtime type check for contract ids anyway.
2. We need to make `ContractId a` serializable whenever `a` is serializable. Currently, `a` also has to be a concrete template type. This change is fine since contract id values are always serializable, regardless of the `a`. We need to make sure that the `a` is serializable for code gens nevertheless.

**Comment by S11001001** [comment]
Issue #1325 details Scala codegen changes for ContractIds like in #1315.

**Comment by hurryabit** [comment]
This is related to #1387.
