### ISSUE TITLE
Write a nice generic swap using interfaces

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12792]
To address feedback from sales engineering.

**Comment by sofiafaro-da** [comment]
The main issue here is how to identify an asset in a safe way. I.e. if someone gives you an asset generically, how do you know that it represents what you expect it to represent. Ultimately I think there are two options,

1. Use a separate "asset type" or "asset factory" interface to validate the asset. Thus the swap would contain a reference to this separate contract, that acts as a "signed dictionary".

2. Use the TypeRep of the asset (obtained from interfaceTypeRep), plus some "specification data" provided by the asset itself, to validate the asset.

Option 2 seems a bit simpler for the implementer of the asset, and generally safer, so I'll expand on that.

First we need a type for specification data, `Spec`. Ideally this could represent any serializable value (and we may want to implement that in the future), but for now we can get away with an ADT like this:

```Haskell
data Spec = SInt Int | SText Text | SList [Spec]
```

Then, the `Asset` interface provides a method to extract the `Spec` from a given `Asset`:

```
interface Asset where
    ...
    assetSpec : Spec
    ...
```

For example, if the Asset was cash, the Spec could be the currency,

```
template Cash with
   ...
   ccy : Text
   ...
 where
   ...
   implements Asset where
       ...
       let assetSpec = SText ccy
       ...
```

I.e. the spec is used to distinguish non-interchangeable assets.

Then, if you are using the `Asset` interface and you want to identify a specific asset, you need to store two things: something that identifies the asset's type, and the Spec. Currently there isn't a way to serialize TypeReps directly, but we can easily implement something that would work for this use case -- a way to extract the template ID (as a string) from a TemplateTypeRep. So in practice, you are defining an Asset ID as a combination of a template ID (here a string) and a Spec:

data AssetID = AssetID
  { assetIdTemplate : Text
  , assetIdSpec : Spec
  }

**Comment by sofiafaro-da** [comment]
Here's a worked out example of using `AssetId` to transfer an asset's ownership. This is kind of like a reverse "propose-accept". I.e. party A makes a Request, and party B fulfills it. 

```
template Request with
    requester : Party
    fulfiller : Party
    assetId : AssetId
    amount : Int
 where
    signatory requester
    observer fulfiller
    choice Fulfill : ContractId Asset with
        asset : ContractId Asset
      controller fulfiller
      do
          assetData <- fetch asset 
          assert (assetMatches assetId assetData)
          exercise asset (Transfer requester)
```

This assumes that `Asset` interface has a `Transfer` choice that allows the asset's owner to assign a new owner. The point of using `Request` instead of just exercising `Transfer` directly is that the `Request` has buy-in from the new owner, who is now in the authorization context, whereas exercising a `Transfer` directly would fail authorization checks. (Assuming owner is a signatory of course.)
