### ISSUE TITLE
scenario client should ask for full Scala validation in case of CI test

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#128]
Currently the scenario service runs only a subset of the validations when loading package/modules:

- We do not want type check because it is slow and duplicated in Haskell side
- We do not want serializability check because the inference is not properly propagate to the engine (in case of scenario)
- We want collision check because it is not done on Haskell side.

Those assumptions are fair for the user experience of an IDE user.  However we should activate those validations for the CI tests that are based on the Scenario service. 

The flag added a flag `ligthValidation` in the protobuf `UpdateContextRequest`  parametrize the set of validations the scenario service runs on the modules/packages is asked to load.

The Scenario client should use this flag to ask for 
- *full validation* in case of CI tests and (`ligthValidation` flag off)
-  *light validation* in case of IDE integration(`ligthValidation` flag on)

In case of *full validation*, the compiler should also be amended to perform beforehand the serializability inference, as it is not done currently.

**Comment by remyhaemmerle-da** [comment]
Any timeline for fixing this small issue ?

**Comment by cocreature** [comment]
@remyhaemmerle-da sorry about that. I somehow lost track of this issue. I’ll try to get to it this week.

**Comment by cocreature** [comment]
This has been fixed.
