### ISSUE TITLE
Simplify exercise by interfaces primitives

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12821]
Currently, the exercise by interface primitives does a few things in addition to the original primitive.

1. First, it has to figure out the underlying template id. This is essential so no way around this.
2. Second, if the optional template id is provided it checks that it matches the template of the interface implementation. This is used when exercising a choice defined in an interface via a template id either via the ledger API or in Daml itself. This is checked before evaluating signatories & controllers.
3. Lastly, we have the user-defined guard which is evaluated after the signatories but before checking authorization.

This is a lot of complexity to maintain & test. To simplify this, we’d like to change this as follows:

Drop 2 completely. Instead the compiler will do the typerep check as part of the guard. We should also move the guard before signatories & friends evaluation.

To keep the same errors that we get for contract type mismatches, we can add a special primitive to LF that allows checking the types and if not produces that error.

**Comment by sofiafaro-da** [comment]
The LF primitive has been simplified. What is left is #13277 to handle cleanup in speedy.
