### ISSUE TITLE
user token testing for json-api

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#12829]
json-api is somewhat special since it cares about the claims satisfied by a token; it does not simply pass every token through to the participant server.  Generally how this works is that it tries to parse a token as a claims token, and if that fails, passes the token to the user management service to retrieve the details instead.

As such, if the user management service isn't available, and you attempt to use a user token, you'll get a similar error to if you tried to contact the user management service directly on a participant server that doesn't have it.

#12075 includes tests for the `create` command and useful tools in `HttpServiceIntegrationTestUserManagement.scala`.  Because the way user tokens are handled in requests is uniform as mentioned above, this is sufficient for broad coverage, but that file can be used as a source of tools and ideas for expanding coverage as described below.

One oddity is that in `GET /user` and `GET /user/rights`, if you pass a claim token, the `applicationId` will be used as the `"sub"` used with the user management service. It's arguable that these endpoints simply shouldn't work with claim tokens at all, but it seems of little concern either way, since these endpoints are meant for working with user tokens in the first place.

Some interesting areas to test that we don't seem to have coverage of yet:

* [x] #13105
  * the `customDecodeAndParsePayload` function should probably be deleted
* [x] #12907
  * includes the widely-used `AbstractHttpServiceIntegrationTestFuns#jwt`
  * that should yield a large amount of coverage at the unfortunate expense of doubling many tests
  * possibly only the especially claims-metadata-sensitive endpoints (POST `fetch`, `query`) should be doubled this way
  * certainly a PR all its own, `jwtForParties` might use user management itself to set up each bespoke user token
* [x] #13112
  * #12922 included some `FailureTests` porting that was reverted to help the PR size; restore that and duplicate tests as that PR did

**Comment by realvictorprm** [comment]
I'll try to take care of this.

**Comment by stefanobaghino-da** [comment]
As mentioned, please finish taking care of your open tasks before picking up new ones.

**Comment by S11001001** [comment]
@realvictorprm I encourage skepticism about the value of particular tests, as I merely enumerated ideas that came to me at a glance, and of course ideas that I might have missed.

That said, with some experience with #12830 and #12831, some potentially useful framing ideas:

1. What will the tests look like if we delete claim token support, and all claim-token-dependent tests as well?
2. If a test only works with claim tokens, and we eliminate that test (because of removing claim tokens), do we still have good coverage of the related feature? If not, that's a pretty good indication that it deserves a port/dupe.
3. If a tricky test is nonetheless valuable, is there a way to isolate it so that easier-to-port tests can get working now, and we can consider the trickier cases later?

`inClaims` and #13076 are borne of this thinking. If you don't think a test port passes the bar, by all means exclude or delay it.

**Comment by realvictorprm** [comment]
Going through your points my current observation is that with the current implementation I've separated custom token and user token specific tests leading to only a single tests which had to be separated out of the class with all tests.

As soon as we remove support for the custom tokens we should in theory only have to change from which base trait the other tests inherit to the one implementing everything for user tokens. This doesn't count for all tests yet but almost all most relevant (i.e. the FailureTests still need to be decoupled).

**Comment by realvictorprm** [comment]
I unassigned myself here because my work on the ticket is done and has been reviewed with Stephen tackling the last task https://github.com/digital-asset/daml/issues/13112 we created after talking with each other.

**Comment by realvictorprm** [comment]
Forgot unassigning myself here, @S11001001 if you are fine it please assign yourself here as only the PR you are working on is left for this ticket right now.
