### ISSUE TITLE
allow trailing commas / semicolons in record definitions

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#1282]
@hurryabit at some point in the last few months we seem to have lost the ability to specify record fields with trailing semicolons. Was this intended?

Like this:

```
quux with
  bar;
  baz = foo;
```

**Comment by neil-da** [comment]
@shayne-fletcher-da @rohanjr are currently specifying this precisely and figuring out what should be allowed. I would have thought trailing `;` was OK, but not particularly recommended.

**Comment by bitonic** [comment]
@neil-da i would reccomend it, it minimizes diff noise.

**Comment by neil-da** [comment]
@bitonic I don't see how it minimizes diff noise? It's not required on any of the lines.

**Comment by bitonic** [comment]
@neil-da if you have

**Comment by neil-da** [comment]
@bitonic if you have

```
foo with
  bar = 42
```

and you modify to

```
foo with
  bar = 42
  baz = "blah"
```

only one line changes, and you have less syntactic noise.

**Comment by neil-da** [comment]
Agreed, we should advise against semicolons. However, I think it maybe probably should work anyway, so still worth investigating.

**Comment by shayne-fletcher-da** [comment]
Wasn't intended and I suspect, never was supported. I don't expect it will be hard to add - will lead to a bit of verbosity in the grammar but nothing major.

**Comment by shayne-fletcher-da** [comment]
Fyi, the structure of the rules (for `fielddecls` and `fbinds` in these contexts) is probably is along these lines
```
    -- Equivalent to: ';'* (x ';'+)* x?  (can be empty, permits leading/trailing semis)
    xs : xs ';' x
       | xs ';'
       | x
       | {- empty -}
```
Other possibilities are enumerated in the note `[Parsing lists]` in `Parser.`.

We do still have the open question of the intermingling of the `,` and `;` syntaxes though. Consideration of that should probably be made before jumping in.

**Comment by rohanjr-da** [comment]
Another question is whether we allow leading semicolons as well. They seem to be allowed in `do` blocks. You could argue for them using the same reason @bitonic said, for those who use the leading punctuation style, e.g.
```
do {
  ; putStrLn "hello"
  ; putStrLn "world"
  }
```
On the other hand, we might want to be consistent with traditional record syntax, where leading and trailing commas do not parse.

We should specify some reasonable behaviour, probably once a verdict is made on https://github.com/ghc-proposals/ghc-proposals/pull/231. However I think these questions are the reason that `with` syntax exists: to get rid of the punctuation noise altogether.

**Comment by hurryabit** [comment]
I think people only use leading commas in Haskell because it doesn't allow for trailing commas. Otherwise people would probably write
```haskell
daa Foo = Foo {
    f1 : T1,
    f2 : T2,
  }
```
Thus, I'm against allowing leading commas (and semicolons).

**Comment by cocreature** [comment]
Don’t think this is a good use of our time, feel free to reopen if you disagree.
