### ISSUE TITLE
Fix auth0 docs to work with Daml 2.0’s create-daml-app

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12849]
We have some docs for setting up auth0 in https://docs.daml.com/ops/connect/auth0.html as well as support in create-daml-app for working with auth0. However, a few things changed in 2.0 that we need to adapt to:

Required for 2.0:

1. The docs still reference old daml sandbox commands which don’t work with a Canton sandbox.
2. create-daml-app now relies on having a public party that all users can readAs. We need to issue tokens to allow for that as well as change create-daml-app to figure out the id of that public party.

Desirable for 2.0:
1. Ideally, we’d also switch to issuing user tokens instead of the custom Daml-style tokens.

**Comment by cocreature** [comment]
https://github.com/digital-asset/daml/pull/12878 was the last big change we needed in create-daml-app so you should be able to do the auth0 work without making too many changes. For daml-hub I needed to use a separate token for the public party so if that makes things easier via auth0 we can do that as well instead of issuing actAs for the user party & readAs for the public party in a single token.

**Comment by ray-roestenburg-da** [comment]
@stefanobaghino-da sounds good to me to remove docs that simply do not work, and revisit these later.

**Comment by garyverhaegen-da** [comment]
I agree that temporarily removing these pages seems like the best path forward.

**Comment by stefanobaghino-da** [comment]
To make sure we can keep track of everything I've broken this down into
- https://github.com/digital-asset/daml/issues/13045
- https://github.com/digital-asset/daml/issues/13038
- https://github.com/digital-asset/daml/issues/13039

**Comment by stefanobaghino-da** [comment]
I'll update the ticktets mentioned above to reflect the decision took by @bame-da and @davidrichards-da to keep the documentation in for this version, put it in early access and specify it refers to version 1.18.

**Comment by cocreature** [comment]
I think we should still drop the code from create-daml-app though. Saying it refers to 1.18 doesn’t make sense there.

**Comment by cocreature** [comment]
Just to be clear, I’m saying it’s fine for the helm chart and the auth0 docs to do what product suggested. It simply doesn’t work for create-daml-app. The code is literally completely broken with a `TODO FIXME`. Adding a comment saying that it used to work in 1.18 is not helpful. You need the full 1.18 template for that.
