### ISSUE TITLE
navigator regression: allocate parties in script, no users available for login

### ISSUE THREAD

**Issue by adriaanm-da** [digital-asset/daml#12867]
As diagnosed by @cocreature:

1. You allocate parties via a Daml script on startup (or something else)
2. You do not specify parties in your daml.yaml

Before #12187, you got the list of parties on the login screen, now it shows you nothing and you have to figure out why as a user.

**Comment by stefanobaghino-da** [comment]
> 3. Always display both users as well as any parties that do not have a user that has them as a primary party (that’s to avoid duplicates which get very confusing). We probably should show on the login screen which are users and which are parties.
>
> [...]
>
> I’m somewhat leaning towards 3 as the dwim solution but no strong feelings.

It sounds like a pretty clean approach.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
