### ISSUE TITLE
Document syntax highlighting for DAML on Github

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#129]
Magic is to create a file `.gitattributes` with:

```
*.daml linguist-language=Haskell
```

E.g. https://github.com/DACH-NY/daml/blob/master/.gitattributes

Should be documented somewhere. No idea where

**Comment by hurryabit** [comment]
@cocreature @garyverhaegen-da What do you think about putting this `.gitattributes` file into the skeleton and/or create-daml-app? I don't see us getting proper syntax highlighting support on GitHub anytime soo.

**Comment by garyverhaegen-da** [comment]
@hurryabit Added `.gitattributes` as of #7388.
