### ISSUE TITLE
Support "go to definition" on types

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1292]
In the line `let x : Iou = Iou with ..`, "Go to definition" works on the type constructor, but not on the type.

**Comment by shayne-fletcher** [comment]
This is well known and a consequence of the limits of the techniques we currently employ. There are plans to do better but it requires a whole new approach

**Comment by cocreature** [comment]
This has been implemented since.

**Comment by shayne-fletcher** [comment]
Since... `hie` export files entered the picture?

**Comment by cocreature** [comment]
No this has nothing to do with `.hie` files. I implemented it in https://github.com/digital-asset/daml/commit/5a951120b6cb137965b859ad2284de39f9e1107e last week.

**Comment by neil-da** [comment]
`.hie` gave us cross-package goto definition. The stuff on types was just a few missing cases.

**Comment by shayne-fletcher** [comment]
Ah ok, I see it. Great work - I was wrong in believing this technique want possible here. Outstanding.
