### ISSUE TITLE
create-daml-app should use user management

### ISSUE THREAD

**Issue by adriaanm-da** [digital-asset/daml#12945]
Concretely, we should get rid of the Parties stanza in the create-daml-app daml.yaml template, so that navigator defaults to user management.

**Comment by cocreature** [comment]
we already use user management in create-daml-app, you can just drop the parties from daml.yaml without any other changes.

**Comment by adriaanm-da** [comment]
Right, that's that this ticket is for: we still need to drop the `parties` part.

**Comment by adriaanm-da** [comment]
By the way, there's a few more templates that specify parties explicitly.

- docs/source/daml/patterns/daml.yaml.template
- templates/copy-trigger/daml.yaml.template
- templates/create-daml-app/daml.yaml.template
- templates/empty-skeleton/daml.yaml.template

For now, I'll just update the create-daml-app template.

**Comment by cocreature** [comment]
fixed
