### ISSUE TITLE
Flaky master: //ledger/api-server-damlonx/reference:semantic-test

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1294]
This test [failed with a timeout](https://dev.azure.com/digitalasset/daml/_build/results?buildId=6227) on [this commit](https://github.com/digital-asset/daml/commit/9684e1325e1ad10164a59b138da7f143a492ce0c) on master.

```
//ledger/api-server-damlonx/reference:semantic-test                     TIMEOUT in 61.1s
```

**Comment by SamirTalwar** [comment]
I'm guessing this has since been fixed?

**Comment by garyverhaegen-da** [comment]
Probably. I don't recall seeing it in a while. 🤞
