### ISSUE TITLE
Sandbox help UX is very confusing

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12985]
`daml sandbox --help` shows the help of the sandbox wrapper
`daml sandbox -- -- --help` shows the help of the underlying Canton runner.

That is super confusing and unintuitive. We should do better.

**Comment by cocreature** [comment]
seems sensible yeah

**Comment by sofiafaro-da** [comment]
Should `-c` supplant the default configuration, or be supplied in addition to it? And/or should the default configuration be "disable-able" by a separate flag.

**Comment by cocreature** [comment]
> Should `-c` supplant the default configuration, or be supplied in addition to it? And/or should the default configuration be "disable-able" by a separate flag.

supplied in addition to, that’s what happens atm. We’re not trying to expose generic Canton, just a Catnon sandbox for which the default config is fine.
