### ISSUE TITLE
Template is visible other than Participants and Observers

### ISSUE THREAD

**Issue by sanjeevkkn** [digital-asset/daml#1298]
when I try access first template data from the second template by Participant of both template it leads to visibility of data to all the Participants Of Second template
![Screen Shot 2019-05-22 at 12 42 17 PM](https://user-images.githubusercontent.com/44251557/58154486-59300e80-7c8f-11e9-8217-bd7a0c5ea7be.png)
![Screen Shot 2019-05-22 at 12 43 13 PM](https://user-images.githubusercontent.com/44251557/58154520-6d740b80-7c8f-11e9-806e-57c6245cbff5.png)

**Comment by bame-da** [comment]
On a DAML ledger, any party that sees an "action" (ie a create or exercise) given all the information they need to validate that action. That way they can verify the ledger integrity.

Signatories, observers and controllers of a contract all need to see the exercise of a consuming choice as they need to know that the contract has been archived. As per the above, that means the `observers` of your `Bol` template they get to see the entire sub-transaction, including  the `fetch trandeId`. I assume `Carrier`, and `ImpBank` learn about your `TradeAgreement` by virtue of being observers (or controllers) on `Bol`.

The same isn't true for `nonconsuming` choices. If you don't want the `observers` to see the main part of your choice, but still want to archive the contract, you can construct this yourself as follows:
```
controller exporter can
  RequestBol : BolId
    with
      tradeId : TradeAgreementId
    do
      archive self
      rec <- fetch tradeId
      ...
```

**Comment by sanjeevkkn** [comment]
Then How can I Update Bol template in the Same choice

**Comment by bame-da** [comment]
I missed your second question, sorry. 

Templates can be used multiple times. Contract instances based on templates can not be used again once they are archived.

Closing this issue for now as it's rather stale. Feel free to re-open if you still think there is a bug. If you need clarification, use the public Slack or StackOverflow, please.
