### ISSUE TITLE
Improve damlc warnings on the command line

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#13]
@raphael-speyer-da requests:

2. Allow suppress warnings on command line. When you just care about errors, having to visually scan through a bunch of warnings on the terminal to find them is slow and finicky.

- command line can show warnings regardless of whether there are any errors.

- when warnings are emitted, also emit their unique id so that users know how to -Werror or suppress them

**Comment by cocreature** [comment]
This is good enough for now™.
