### ISSUE TITLE
Flaky master: //daml-assistant/integration-tests:integration-tests

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1304]
[This build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=6332&view=logs) of [this completely unrelated commit](https://github.com/digital-asset/daml/commit/c762d491ea9e2e87b8e048ef6f1f155e990ea0ad) failed on master, apparently after 5 attempts.

@moritzkiefer-da @associahedron could you please take a look?

**Comment by cocreature** [comment]
No idea why `damlc test` would timeout. My guess is that the scenario service (which is a separate process) might fail to startup. I’ll see if I can maybe add some more debugging output to ease debugging if this happens again.

**Comment by associahedron** [comment]
Agree that this is coming from `damlc test` for quickstart-java on Windows.

**Comment by SamirTalwar-DA** [comment]
Is this still valid?

**Comment by cocreature** [comment]
They are still flaky. I don’t know why though. (yet another example demonstrating that marking things as flaky just leads to people ignoring the issues).

**Comment by hurryabit** [comment]
@robin-da Is that one still an issue after your changes to the assistant integration tests?

**Comment by garyverhaegen-da** [comment]
It's a lot rarer now.
