### ISSUE TITLE
trigger-service log level

### ISSUE THREAD

**Issue by shiranA90** [digital-asset/daml#13042]
I’m using trigger-service-1.18.0.jar and can see logs in DEBUG level.
for example this secion in the code ( from trigger/Runner.scala file):

`freeTriggerSubmits(clientTime, v = updateWithNewState) .leftMap( _.expect( "TriggerRule new state", { case DamlTuple2(SUnit, newState) => logger.debug(s"New state: $newState") newState }, ).orConverterException )`

prints in DEBUG mode the content of the contract.
How can that be avoided?
How can I control the logging level of the service?

**Comment by realvictorprm** [comment]
Hi @shiranA90, sadly I don't have a solution at hand yet except that I'm aware of this issue now, I think this should be tackled soon and that I will talk with my colleagues about it.

**Comment by stefanobaghino-da** [comment]
@shiranA90 How are you running the trigger service?

**Comment by shiranA90** [comment]
`exec java -jar /trigger-service.jar \
  --address=ADDRESS \
  --http-port=HTTP_PORT \
  --ledger-host=LEDGER_HOST \
  --ledger-port=LEDGER_PORT
`

**Comment by stefanobaghino-da** [comment]
> `java -jar /trigger-service.jar --address=ADDRESS --http-port=HTTP_PORT --ledger-host=LEDGER_HOST --ledger-port=LEDGER_PORT `

Thanks for letting us know. This should not happen, we'll look into why the expected configuration is not picked up as expected. In the meantime, you can provide your own logging configuration file by providing the path to a custom `logback.xml` file that behaves properly ([see the Logback docs](https://logback.qos.ch/manual/configuration.html#configFileProperty)). A file like [this](https://github.com/digital-asset/daml/blob/6bb74786b9715dc7f0fe278bba18f2e7e529e0ae/triggers/service/release/trigger-service-logback.xml) should get the job done (that is the file that _should_ be in the `trigger-service.jar` file.

Did you download the JAR file from [the release page for version 1.18.0](https://github.com/digital-asset/daml/releases/tag/v1.18.0)?

**Comment by stefanobaghino-da** [comment]
Thanks for confirming. For some reason, the `logback.xml` file is not bundled together with the JAR that we distribute. @moritzkiefer-da are you aware of whether this is done on purpose to avoid issues with the SDK assistant?

**Comment by cocreature** [comment]
that’s right, we set it explicitly in the sdk config so it doesn’t matter what is in the JAR https://github.com/digital-asset/daml/blob/b2d6f8014c12848cc8f9f3537c5de4bc1732b504/release/sdk-config.yaml.tmpl#L85
