### ISSUE TITLE
Include interfaces and interface choices in `daml test` coverage report

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#13044]
Was "Preserve inherited choice info in `daml test` coverage report"

~~Preserving the information of which interface the choice was inherited from to provide more useful output on which choices you missed, e.g., something along the lines `choice C (inherited from interface I)`.~~

For now, let's take the simple approach of counting, for each interface, the distinct interface choices that have been exercised, regardless of the underlying template. Later we can refine this to count distinct interface choices per (interface, template) pair.

relates to https://github.com/digital-asset/daml/issues/12807 and https://github.com/digital-asset/daml/pull/13012

**Comment by dylant-da** [comment]
> For now, let's take the simple approach of counting, for each interface, the distinct interface choices that have been exercised
Turns out it's easy^Kier to count distinct interface choices for each implementation block anyways.

**Comment by dylant-da** [comment]
I think we can close this as done for now
