### ISSUE TITLE
Meta: DamlOnX Ledger API server future work

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#131]
The following issues need to be followed up on:

**Inefficient use of getPackage:**
 The getPackage endpoint returns the DAML-LF archive, leaving
the consumer to decode the archive into a package. This works fine for DAML Engine which holds its own cache of compiled packages. The endpoint is also used by IdentifierResolver, which does not cache packages.

**Naive reference index service:**
The implementation of the reference index service takes some shortcuts and is not currently an ideal example to copy from. For example it uses unbounded queues to forward events to consumers and does not apply backpressure.  See FIXMEs in code.

**Comment by stefanobaghino-da** [comment]
@dajmaki Is this issue still relevant?
