### ISSUE TITLE
VS code highlighting not identifying comments in nested context 

### ISSUE THREAD

**Issue by akalburgi** [digital-asset/daml#1310]
Thanks @meet-da for the report
![image](https://user-images.githubusercontent.com/42743833/58174048-f462bd00-7c6a-11e9-8eb3-78a2c9e09a69.png)

**Comment by associahedron** [comment]
I believe the issue is that the syntax highlighting should be detecting that `-- with this` is a comment, but it's not.

**Comment by akalburgi** [comment]
@associahedron that is correct, bad wording of the issue on my part

**Comment by associahedron** [comment]
Thanks @akalburgi !
