### ISSUE TITLE
Annotate the HTTP JSON API unit tests to generate security evidence

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#13132]
Part of https://github.com/digital-asset/daml/issues/13131

**Comment by realvictorprm** [comment]
Okay, I've gone through the tests, thought about the whole security evidence topic & talked with people and came to the conclusion that for the unit tests there doesn't really seem to be a test so far, that is really relevant for security auditing. However I've identified a potential hole in the simple unit tests which
- I'm not completely sure whether it is possible but in the unit tests we could check for potential SQL injection attacks and reject requests of such kind (not sure however if it is even possible to apply sql injection attacks with our query language. @S11001001 probably can tell more here, my knowledge about the query language is nearly zero currently).

A potentially relevant test could be the one which checks that provided config parameters are read in correctly (where tls configuration details are part of the config).
https://github.com/digital-asset/daml/blob/main/ledger-service/http-json/src/test/scala/com/digitalasset/http/CliSpec.scala#L273-L316

**Comment by S11001001** [comment]
> I'm not completely sure whether it is possible but in the unit tests we could check for potential SQL injection attacks and reject requests of such kind

It isn't interesting to test that the SQL parameter mechanism doesn't permit SQL injection, so anything that uses doobie's SQL interpolation is not worth testing in this way, as it constructively prevents it. Sort of like testing that every list has zero or more elements.

The only area where this would be worthwhile is to check whether you can create a well-typed

```scala
jp: Queries.JsonPath
// such that
val pred: Cord = ('$' -: pathSteps(jp)) ++ "?(@ != null)"
sql"""select *
      from $contractTableName
      where json_exists($contractColumnName,
                        ${oracleShortPathEscape(pred)})
```

evaluates SQL that was included in `jp`. (Relevant functions defined in `OracleQueries`.)
