### ISSUE TITLE
Evaluate breaking Navigator away from the `digital-asset/daml` repository

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#13177]
Navigator is a full stack application built on top of the Ledger API that has both Scala and TypeScript code. The TypeScript part in particular suffers from a build which suffers from a build definition that makes it hard to iterate quickly using standard tooling in the React.js ecosystem.

It could be interesting to consider it to be moved in a separate repository, as its main interface with the rest of the repository (the Ledger API) is well defined.

A few challenges need to be addressed:
1. how to build Scala and TypeScript in the same repo using tooling native to the ecosystem
2. using libraries from the main repository that are versioned alongside the SDK
3. assembling Navigator with the rest of the SDK for releases
4. versioning separately from the SDK and possibly have an SDK version support matrix

**Comment by garyverhaegen-da** [comment]
There doesn't seem to be any appetite for repo structure changes these days. @ray-roestenburg-da please reopen if I'm wrong.
