### ISSUE TITLE
we should not leak sensitive information through error messages

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#132]
right now transaction authorization is performed after execution has finished, which causes problems regarding error messages. this occurred to me while implementing contract keys in the sandbox. specifically, contract keys lookups are authorized after execution has finished.

however, you can just look up and then assert that the key exists, and then that the key does not exist. now, even if you are _not_ authorized to perform the lookups, you're going to get an assertion failure out, and right now, you'll even know which one of the two assertion fails. this will essentially allow you to know which keys exist on the whole participant node you're running on.

i'm sure this can generalize to other leaks, @meiersi-da had some ideas about fetches too, but i'm not sure it actually is a problem with fetches.

there are two solutions:

1. interleave authorization with execution;
2. do not offer any insight on why the command submission failed.

@meiersi-da thinks that 1 is not so hard, and i tend to agree. however as a short term solution 2 is much safer, i think.

cc @meiersi-da @stephencompall-DA @remyhaemmerle-da

**Comment by sofiafaro-da** [comment]
Closing since the interleaving of execution and authorization was implemented by @nickchapman-da. There's still an issue with fetches and errors leaking information, but this will be a separate issue.
