### ISSUE TITLE
C# codegen support

### ISSUE THREAD

**Issue by filmackay** [digital-asset/daml#1332]
Suggestion that we add C# support to codegen. Fork Java, and go from there.

Presumably we'd need to resolve #95 at the same time.

**Comment by neil-da** [comment]
If this something that is nice to have, or has an actual feature request from a user? How important is it?

**Comment by cocreature** [comment]
Just a data point: We just had a user in the public slack requesting C# bindings.

**Comment by filmackay** [comment]
> If this something that is nice to have, or has an actual feature request from a user? How important is it?
Actual feature request from a user - alternative is rolling manually of course.

**Comment by AndrewDCDrummond** [comment]
"Actual feature request from a user - alternative is rolling manually of course."

rolling manually is going to need a hack around issue #95 because of None name conflict.

**Comment by filmackay** [comment]
Please see the community project .NET DAML bindings: https://github.com/digital-asset/daml-net
