### ISSUE TITLE
Test cross-module interfaces & implementations

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#13332]

**Comment by akrmn** [comment]
[This test](https://github.com/digital-asset/daml/blob/dep-graph-test/compiler/damlc/tests/src/DA/Test/DataDependencies.hs#L1587) has a template which implements an interface from a data-dependency, so cross-package in addition to cross-module. Is that enough or can you think of something else to test here? @sofiafaro-da @remyhaemmerle-da

**Comment by sofiafaro-da** [comment]
Some tests that also use "required interfaces" across data-dependencies would be good. Thanks for checking!
