### ISSUE TITLE
Decouple blinding and authorization

### ISSUE THREAD

**Issue by dajmaki** [digital-asset/daml#1336]
Decouple the blinding from the transaction authorization and the scenario ledger.

Blinding is used in situations where transaction has already been authorized. Additionally we will need to be able to compute blinding at the participant (for its hosted parties) based on the committed transaction which has absolute node and contract identifiers. Currently blinding (layered on top of enrichTransaction) only works with integer node ids (Value.NodeId).

**Comment by stefanobaghino-da** [comment]
Fixed by #7262
