### ISSUE TITLE
Make LF archive `protobuf` decoding stack-safe

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#13418]
Ideally we want the decoding phase to be stack safe.
(As we have done for the various phases in the speedy compilation pipeline.)

**Comment by sofiafaro-da** [comment]
LF archive protobuf encoding would be nice too, but it's less important for the engine.

May want to look into expression interning as a general solution. Temporarily we could just try to reduce stack consumption.

**Comment by nickchapman-da** [comment]
This issue is a duplicate of https://github.com/digital-asset/daml/issues/13410
