### ISSUE TITLE
derive Functor, Semigroup etc instances for Generic representations

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#1344]
The instance derivations for Functor, Semigroup, Applicative, Monad have been disabled for the generic representation in daml-prim-src/GHC/Generic.hs because some cause problems to the translation to daml-lf. We want to reenable the deriving of these instances for as many as possible.

**Comment by cocreature** [comment]
Given that generics are somewhat of a mess and cause problems with upgrading, I’m closing this.
