### ISSUE TITLE
Daml Script should rely on application id defaulting

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#13474]
If users do not set the application id explicitly, we should rely on application id defaulting instead of setting it explicitly to `daml-script`.

This might need some thinking on how to handle daml script running against 1.x ledgers if we want to support that. One option could be to only do this for user access tokens but not everything.

**Comment by sofiafaro-da** [comment]
More information on application id defaulting:
- Issue: https://github.com/digital-asset/daml/issues/12083
- Pull request: https://github.com/digital-asset/daml/pull/12100

Clarification on what the script runner should do:

> sofia:
> Thanks! Just to clarify, the script runner should leave the application id blank when it isn't passed explicitly? Or it should try to determine what the default application id should be, based on tokens? (edited) 

> moritz:
> I think at least in the case where the user has specified a user token and not specified --application-id it should be left blank. Maybe also in the case where it specifies a custom claims token with an app id.
> For unauthorized usage I think you do still need it.

**Comment by akrmn** [comment]
@cocreature 

> moritz: [...] `--application-id` should be left blank

Do you mean blank as in the empty string, or should the type of [LedgerClientConfiguration.applicationId](https://github.com/digital-asset/daml/blob/main/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/configuration/LedgerClientConfiguration.scala#L12) change to `Option[String]`?

**Comment by cocreature** [comment]
> Do you mean blank as in the empty string, or should the type of [LedgerClientConfiguration.applicationId](https://github.com/digital-asset/daml/blob/main/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/configuration/LedgerClientConfiguration.scala#L12) change to `Option[String]`?

it’s protobuf so empty string is identical to not setting it. But maybe a good idea to change that API.
