### ISSUE TITLE
Using `key this`, `observer this`, `signatory this`  in template-local let clause causes infinite loop.

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#13470]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

# Affected Daml version

2.0.0

# Bug description

Using the expression `key this` in a template-local `let` clause seems to cause some sort of infinite recursion.

# To reproduce

1. Create a daml project with the below `Main` module. 
2. Open the Script view of the script. 
3. Enjoy the sound of your laptop fans spinning as the scenario service maxes all your CPUs. 
4. Wait patiently for the message `"Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusDeadlineExceeded (StatusDetails {unStatusDetails = \"Deadline Exceeded\"})))"` appears

```
module Main where

import Daml.Script

template T
  with
    p : Party
  where
    signatory p
    key p : Party
    maintainer key

    let k = key this

t = script do
  p <- allocateParty "p"

  submit p do
  createCmd T with p
```

# Expected behavior

The same thing as if the let clause read `let k = p`. Ie the script view appears.

# Additional context

**Comment by alexgraham-da** [comment]
@bame-da FYI I tested creating a contract with this in a 1.18.1 sandbox (running on Hub) and it crashes the ledger with this in the sandbox logs:

```
Exception in thread "ForkJoinPool-4-worker-4" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
        at java.base/java.util.ArrayList.grow(ArrayList.java:237)
        at java.base/java.util.ArrayList.grow(ArrayList.java:244)
        at java.base/java.util.ArrayList.add(ArrayList.java:454)
        at java.base/java.util.ArrayList.add(ArrayList.java:467)
        at com.daml.lf.speedy.Speedy$Machine.pushKont(Speedy.scala:201)
        at com.daml.lf.speedy.Speedy$Machine.executeApplication(Speedy.scala:544)
        at com.daml.lf.speedy.SExpr$SEAppAtomicFun.execute(SExpr.scala:125)
        at com.daml.lf.speedy.Speedy$Machine.loop$1(Speedy.scala:401)
        at com.daml.lf.speedy.Speedy$Machine.run(Speedy.scala:405)
        at com.daml.lf.engine.Engine.$anonfun$interpretLoop$1(Engine.scala:332)
        at com.daml.lf.engine.Engine$$Lambda$2937/0x000000080162c000.apply(Unknown Source)
        at com.daml.lf.speedy.Speedy$Machine.withOnLedger(Speedy.scala:195)
        at com.daml.lf.engine.Engine.interpretLoop(Engine.scala:326)
        at com.daml.lf.engine.Engine.$anonfun$interpretExpression$1(Engine.scala:318)
        at com.daml.lf.engine.Engine$$Lambda$2929/0x0000000801620980.apply(Unknown Source)
        at com.daml.lf.engine.Engine.start$1(Engine.scala:251)
        at com.daml.lf.engine.Engine.runSafely(Engine.scala:265)
        at com.daml.lf.engine.Engine.interpretExpression(Engine.scala:307)
        at com.daml.lf.engine.Engine.interpretCommands(Engine.scala:286)
        at com.daml.lf.engine.Engine.$anonfun$submit$1(Engine.scala:113)
        at com.daml.lf.engine.Engine$$Lambda$2722/0x00000008015af310.apply(Unknown Source)
        at com.daml.lf.engine.Result.flatMap(Result.scala:33)
        at com.daml.lf.engine.Result.flatMap$(Result.scala:32)
        at com.daml.lf.engine.ResultDone.flatMap(Result.scala:61)
        at com.daml.lf.engine.Engine.submit(Engine.scala:105)
        at com.daml.platform.apiserver.execution.StoreBackedCommandExecutor.$anonfun$execute$1(StoreBackedCommandExecutor.scala:67)
        at com.daml.platform.apiserver.execution.StoreBackedCommandExecutor$$Lambda$2713/0x00000008015a3480.apply(Unknown Source)
        at com.daml.metrics.Timed$.trackedValue(Timed.scala:23)
        at com.daml.platform.apiserver.execution.StoreBackedCommandExecutor.execute(StoreBackedCommandExecutor.scala:62)
        at com.daml.platform.apiserver.execution.LedgerTimeAwareCommandExecutor.com$daml$platform$apiserver$execution$LedgerTimeAwareCommandExecutor$$loop(LedgerTimeAwareCommandExecutor.scala:52)
        at com.daml.platform.apiserver.execution.LedgerTimeAwareCommandExecutor.execute(LedgerTimeAwareCommandExecutor.scala:40)
```

**Comment by akrmn** [comment]
To clarify, this happens with any of the following template declarations/functions:
* `key`
* `observer`
* `signatory`
* `ensure`
* `agreement`

There's also a similar problem if `key` is defined in terms of `maintainer`, but that's unlikely, I think

**Comment by bame-da** [comment]
@sofiafaro-da I think it's fine to say that certain template declarations shouldn't be used in the `let` bindings, but crashing with an OOM qualifies as a bug in my book. A graceful error message either at compile or runtime would be a good enough solution.

**Comment by akrmn** [comment]
Hi @bame-da, we've discussed this in the language team and we think the root problem is template-local `let` clauses. They offer no significant benefit over plain top-level bindings and, as you've noticed, they have unclear semantics - even though they give the impression of exactly-once evaluation, they are actually evaluated for every `key`/`observer`/`signatory`/`ensure`/`agreement` clause and for every choice, even if never used. Thus, we propose deprecating and eventually removing the feature of template-local `let` clauses, which, as a side effect, would eliminate this class of unexpected behaviors. 

As an example, the template-local `let` binding in @alexgraham-da's program,

```
template Ledger
  with
    operator : Party
    ledgerId : Text
    ...
  where
    ...
    key (operator, ledgerId) : (Party, LedgerId)
    maintainer key._1

    let getLedgerInfrastructure : Update (ContractId LedgerInfrastructure, LedgerInfrastructure)
        getLedgerInfrastructure = fetchByKey @LedgerInfrastructure (key this)
```

could be converted into the top level function

```
getLedgerInfrastructure : Ledger -> Update (ContractId LedgerInfrastructure, LedgerInfrastructure)
getLedgerInfrastructure this = fetchByKey @LedgerInfrastructure (key this)
```

We will also open a ticket to improve the OOM crash into a proper scenario-service error - after all, any other infinite loop would also crash this way.

**Comment by leonidr-da** [comment]
I think the scope of your warning needs to be broader since
```
template T
  with
    p : Party
  where
    signatory (signatory this)
```
compiles

**Comment by sofiafaro-da** [comment]
We are not adding warnings for everything that could loop infinitely -- this is not possible in theory nor in practice.

I think it's pretty clear that this is an infinite loop:

```
template T
  with ...
  where
    signatory (signatory this)
```

And this is an infinite loop that doesn't look like it:

```
template T
  with ...
  where
    signatory x
    let foo = signatory this
```

Unfortunately adding a warning in the latter case is difficult, even for a basic thing like detecting `key this` and `signatory this`, and is at best an approximation.

I agree with @akrmn (and others in the language team) that the problem here is the template local let syntax, since it creates a false impression of the semantics. I'm in favor of deprecating it and encouraging people to write global functions instead, where the flow of computation is much more explicit.

**Comment by stefanobaghino-da** [comment]
_shakes fist at Gödel_

I had a chat with @sofiafaro-da and went through the thread once again to make sure I had a good grasp of the situation. I think that the overall assessment of the situation by the Language team as summarized by @akrmn above makes a lot of sense.

In general I agree with what has been said so far and I agree with the statement that local `let` bindings "offer no significant benefit over plain top-level bindings". As such, I agree with the idea of deprecating them.

Before we move on, I would like to ask a few questions:
1. @alexgraham-da, @leonidr-da: do you agree with the statement above as well? The only advantage of local `let` bindings is the meaning of `this`, but making it an explicit parameter and making the binding defined at the top level seems a perfectly viable thing to do in a Haskell dialect. As mentioned, the exact semantics are also quite confusing (to be quite honest, I still don't fully understand why those are being evaluated despite going through this thread a couple of times already).
1. @sofiafaro-da: are there benefits about this that you deemed not significant that could still be worth mentioning? Are local `let` bindings actually scoped per template? Can you refer to a local `let` bindings from another template?
1. @sofiafaro-da: are you aware of what is our stance with regards to local `let` bindings? Do we use them extensively in our documentation and/or examples?
1. @sofiafaro-da: if we were to confirm that we want to move on with the deprecation, would it be easy to have a clear deprecation warning and making the fix a clear suggestion by the linter?

**Comment by sofiafaro-da** [comment]
> are there benefits about this that you deemed not significant that could still be worth mentioning? Are local let bindings actually scoped per template? Can you refer to a local let bindings from another template?

They are local bindings, so you can only see them within the template. That said, you can achieve a similar level of visibility by not exporting these helper functions outside of the module that defines the template.

It might help to view the template local `let` bindings:

```
template X with ... where
    let binding1 = bexpr1
    let binding2 = bexpr2
    let binding3 = bexpr3
    ... 
    signatory expr1
    agreement expr2
    ensure expr3
    ... 
```

As syntactic sugar for:

```
template X with ... where
    signatory 
         let binding1 = bexpr1
             binding2 = bexpr2
             binding3 = bexpr3
             ... 
         in expr1
    agreement 
         let binding1 = bexpr1
             binding2 = bexpr2
             binding3 = bexpr3
             ... 
         in expr2
    ensure 
         let binding1 = bexpr1
             binding2 = bexpr2
             binding3 = bexpr3
             ... 
         in expr3
    ... 

```

> are you aware of what is our stance with regards to local let bindings? Do we use them extensively in our documentation and/or examples?

I'm not aware of using them extensively. Our daml introduction doesn't teach this syntax. It is in our language reference docs (as "template-local definitions") and shows up in at least one example that I've seen, but the example can easily be changed to not rely on this template-local definition.

> if we were to confirm that we want to move on with the deprecation, would it be easy to have a clear deprecation warning and making the fix a clear suggestion by the linter?

I think we can add a deprecation warning easily, and include a fix suggestion in the warning.

**Comment by alexgraham-da** [comment]
I have indeed used them in a few of my models (including in a reference app). I agree with @leonidr-da that they do have  value, mostly for convenience and organizational reasons.  In terms of including the payload in the scope I did come up with a workaround for this using the `{..}` syntax and passing `this`, such as in this (useless) example:

```haskell
textNumberTuple : MyTemplate -> (Text, Int)
textNumberTuple MyTemplate{..} = (myText, myNumber)

template MyTemplate
  with
    party : Party
    myText : Text
    myNumber : Int
  where
    signatory party

    nonconsuming choice DoSomething : ()
      controller party
      do
       let tpl = textNumberTuple this
       return ()
```

This works decently and does have the potential benefit of that function being used elsewhere.

Another place I see in my older models that has more value is in setting up more complicated `signatory`/`observer` groups, e.g.:

```haskell
template Order
  with
    exchange : Party
    participant : Party
    pair : AssetPair
    orderType : OrderType
  where
    signatory exchange

    let tokenObservers = case orderType of
          BidOrder  -> pair.baseAsset.signatories
          SellOrder -> pair.quoteAsset.signatories
    observer participant, tokenObservers
```

You could have the `case` statement in the `observer` declaration directly, but that seems bit messier (and you might need to do more than one). It could be a top-level binding, but it would be useless elsewhere and it feels nice from an organizational standpoint to have it exactly where it is used.

So, agreed with @leonidr-da that it wouldn't be earth shattering to lose them, but I'd personally prefer they stay in.

**Comment by sofiafaro-da** [comment]
> Given this, I would like to understand if your statement:
>
> > In general, local let bindings should only depend on the record fields and other local let bindings, not on template functions like key, signatory and observer.
> 
> is something that we can offer as a warning to the user.

Adding such a warning is possible, but nontrivial. We don't have anything like this in damlc at the moment, where we warn against specific usage in specific places. The thing that makes this costly is that it requires digging into (one of) the expression ASTs that we get from GHC in a new way.

Note that there are legitimate uses for `key`, `signatory`, etc inside template local lets, so we'd really like to distinguish between `key this`/`signatory this`/ etc and `key somethingElse`/`signatory somethingElse`/etc. At some point this starts to become a costly solution for a very specific and hopefully rare problem.

The fact that nobody can create a contract that includes one of these infinite loops (the `create` action will never succeed), so this issue never becomes part of the ledger & any amount of testing will discover the issue, makes me think that the best solution is not to do anything at compile-time about these infinite loops for now, and instead just try to improve the "deadline exceeded" error. We can defer adding a compile-time warning until an opportunity presents itself.

**Comment by bame-da** [comment]
@sofiafaro-da one aspect that troubles me with "deadline exceeded" is that it's a pure API error. Both in the script service and on a production ledger, the engine just keeps whirring away.
Being able to configure a maximum runtime for a command interpretation would not only improve this slightly, but add real benefit to production ledgers, which would become resilient against accidental DoS via long-running or infinitely running commands.

**Comment by sofiafaro-da** [comment]
@stefanobaghino-da If we change the semantics of `let` bindings to be lazy (or turn them into functions) we might break some daml models that depend on the eager evaluation of `let` bindings (e.g. to throw an exception if something is wrong). Arguably these daml models should be rewritten to force the evaluation of the `let` binding in the `ensure` clause (or one of the other expressions that get evaluated during a `create`, e.g. `signatory`/`observer`/`agreement`/`key`/`maintainer`), instead of relying on the current eager semantics. Making this semantic change is also not trivial.

@bame-da I discussed with @remyhaemmerle-da and we agree that adding some way to interrupt interpretation in the engine is sensible.

**Comment by leonidr-da** [comment]
I just noticed that the `{..}` desugaring syntax does not work with template let bindings ... That is a good thing!

**Comment by stefanobaghino-da** [comment]
OK, I would not try to fix the semantics. Furthermore, lazy semantics only here seems confusing.

I would say to move on with "better error message at runtime and clear documentation of the semantics" to be acceptance criteria to consider this closed.

**Comment by basvangijzel-DA** [comment]
The local let sounds like a good candidate to get rid of in Daml 3.

**Comment by akrmn** [comment]
now that we have interfaces, there's a new way to trigger this behavior: using interface methods in the local let:

```
data View = View {}

interface Bar where
  viewtype View
  label : Text

template Foo
  with
    p : Party
  where
    signatory p
    let l = label $ toInterface @Bar this
    interface instance Bar for Foo where
      view = View {}
      label = "hello" -- <- `l` is available here so we need to evaluate it, 
                      --    but it depends on `label` so we loop

test : Script ()
test = do
  p <- allocateParty "p"
  submit p do createCmd Foo with p
  pure ()
```

**Comment by matevarga-da** [comment]
^ Could you please review the draft PR above? I think we should add at least a note about this.

**Comment by moisesackerman-da** [comment]
Daml 3.0 completely drops support for template-let syntax (https://github.com/digital-asset/daml/pull/18262), so this is no longer an issue.
