### ISSUE TITLE
[FEATURE REQUEST] Make Java codegen more OO friendly by adding contract methods to empty contract Interface

### ISSUE THREAD

**Issue by TuranDev** [digital-asset/daml#13471]
I confirm that, if this is a feature request that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

### What is the problem you want to solve?

When generating the [Java bindings](https://github.com/digital-asset/daml/blob/7000875e6287da3d221896ba8d16f68f9e83d7da/language-support/java/codegen/src/main/scala/com/digitalasset/daml/lf/codegen/backend/java/inner/ContractClass.scala) all generated Templates seem to contain a static inner Contract class which itself implements an [empty contract interface](https://github.com/digital-asset/daml/blob/d2e2c21684e2d9eade40f74990208125ad4b4ccb/language-support/java/bindings/src/main/java/com/daml/ledger/javaapi/data/Contract.java). These static inner Contract classes are all generated with the methods fromIdAndRecord, fromIdAndRecord (deprecated) and fromCreatedEvent

### What is the solution you would propose?

The addition of the methods fromIdAndRecord, fromIdAndRecord (deprecated) and fromCreatedEvent to the Contract interface would allow for derivative code to leverage generics better using the interface.

### Describe alternatives you've considered

Similar consideration could also be given to the abstract Template class itself by moving the static Identifier variable onto the parent Template class (or exposing a getter for it)

### Additional context

None for now

**Comment by stefanobaghino-da** [comment]
Thanks for opening the ticket @TuranDev. Can you give me a practical example of what you would like to achieve more concretely by having those methods defined as part of the interface? What is the obstacle that would be removed if we "allow for derivative code to leverage generics better using the interface"? I would really appreciate a practical example so that I can understand better. I appreciate your feedback, thank you very much. 🙇🏻‍♂️

**Comment by TuranDev** [comment]
So one example is to leverage your grpc/reactive clients (I don't think it really matters which) in conjunction with the generated types say to expose some utils that reduce the boilerplate required for end users such as say a **fetchContracts** method that takes in a template type and returns an array of results which are the payload's of said contracts .

Right now its somewhat specific so the method would need to be something like:

```
Identifier coinIdentifier = Coin.TEMPLATE_ID;

public List<Coin> fetchCoinContracts(Identifier identifier, Party party) {
   return  ...getActiveContracts(.....).map(event -> Coin.Contract.fromCreatedEvent(event).data)
}

```
For a single type fetch the code would be identical and can be generalised. Due to the lack of methods on the interfaces we can do the below (with some reflection.)

```
public <T extends Template, C extends Contract> List<C> fetchContracts(Class<T> templateClass, Class<C> contractClass, Party party){
    Identifier identifier = templateClass.getIdentifier();
    ....bunch of reflection to get TEMPLATE_ID and fromCreatedEvent method...
    return  ...getActiveContracts(.....).map(event -> (C) reflectedMethod.invoke(null, event).data)
}
```

If the Identifier has a getter and the methods were on the contract interface we would be able to do the above methods implementation without reflecting.

```

public <T extends Template, C extends Contract> List<C> fetchContracts(Class<T> templateClass, Class<C> contractClass, Party party){
    Identifier identifier = templateClass.getIdentifier();
    ....
    return ...getActiveContracts(.....).map(event -> contractClass.fromCreatedEvent(event).data)
}
```

 Hopefully that makes sense

**Comment by stefanobaghino-da** [comment]
I see, thanks for your example. Have you tried using the decoder class? It's designed precisely to decode contracts from created events. You can generate by passing the fully qualified name of the class with `-d` or `--decoderClass` to the codegen ([docs](https://docs.daml.com/tools/codegen.html)).

After a brief look, it appears that that is the only mention of the decoder class in our docs. I'll have a better look and add a ticket to expand the docs to mention it if we really don't have any mention of it in the docs.

**Comment by TuranDev** [comment]
Have taken a look at the decoder class now and unfortunately it doesn't really solve the issue at hand here. It does provide a nice mapping from Identifier to the _fromCreatedEvent_ methods but that then still requires either reflecting or casting to the actual object type. Were it on the interfaces themselves then all this would be done at compile time. Is there a specific reason it's not?

**Comment by S11001001** [comment]
> Were it on the interfaces themselves then all this would be done at compile time. Is there a specific reason it's not?

@TuranDev I don't believe there's a reason. For the record, I'm in favor of our implementing this.

**Comment by S11001001** [comment]
We may wish to add a second interface instead of adding a type parameter to `Contract`, depending on whether there's a compatibility constraint here.

**Comment by S11001001** [comment]
So something more like this would work:

```java
public <T, C extends Contract<?, T>> List<T> fetchContracts(ContractCompanion<C, ?, T> companion){
    Identifier identifier = companion.TEMPLATE_ID;
    ....
    return ...getActiveContracts(.....).map(event -> companion.fromCreatedEvent(event).data)
}

// which could be invoked by
fetchContracts(Coin.COMPANION)
// : List<Coin>
// because Coin.Companion: ContractCompanion<Coin.Contract, Coin.ContractId, Coin>
```
