### ISSUE TITLE
[BUG] - LedgerId not deprecated in CommandSubmissionClient in 2.0.0 

### ISSUE THREAD

**Issue by francescobenintende** [digital-asset/daml#13519]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

# Affected Daml version
2.0.0

# Bug description
[CommandSubmissionClient](https://github.com/digital-asset/daml/blob/main/language-support/java/bindings-rxjava/src/main/java/com/daml/ledger/rxjava/grpc/CommandSubmissionClientImpl.java) has its `ledgerId` as a `@NonNull` argument even though the `ledgerId` is optional from 2.0.0 ([Command submission service docs](https://docs.daml.com/app-dev/grpc/proto-docs.html#commands)).

# To reproduce
1. Instantiate `CommandSubmissionClient` without `ledgerId` in constructor
3. see error

# Expected behavior
CommandSubmissionClient is instantiated.

# Additional context
![image](https://user-images.githubusercontent.com/25821545/161997975-61d34717-3e49-44bf-970f-d57ba49a769c.png)

**Comment by stefanobaghino-da** [comment]
1. Despite the client being publicly visible, the command submission client is not really meant to be used directly, but rather through the `DamlLedgerClient`. Is there a specific reason why you are instantiating the command submission client directly?
2. At this low level, the client relies on Protobuf's behavior by which an empty string is the default empty value. Hence, you can instantiate the client by passing an empty string. If this causes issues, please re-open this ticket adding the information about the failure.
