### ISSUE TITLE
Investigate if JWT is according to spec

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#13583]
Kubernetes-generated JWT contains different fields, which could mean that the JWT is not exactly following the spec. 
It also means that you cannot use K8s itself to generate the tokens. In short:

1. aud should be an array: see https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3
2. scope is not customizable in K8s.

See https://github.com/DACH-NY/daml-cloud/issues/8617 for more details.

Currently, if the scope is not present it’s treated as a custom token rather than a user token.

**Comment by stefanobaghino-da** [comment]
@ray-roestenburg-da Reach out to working group to evaluate current state.

**Comment by ray-roestenburg-da** [comment]
Conclusions were made in https://docs.google.com/document/d/1Og97LckZoDn-Fl5jUylDd2oxs5nPme7oq0ETGeYIPpw/edit#, closing this issue.

**Comment by stefanobaghino-da** [comment]
Is there a relation with https://github.com/digital-asset/daml/issues/14574?
