### ISSUE TITLE
Improve error message for arithmetic overflow in DAML Engine

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#1365]
When you run
```haskell
test = scenario do
  let x = 1000000000000
  assert $ x*x > 0
```
you get the error message
```
Scenario execution failed:
  CRASH: long overflow
```
This error message could be improved by saying that we had an overflow when multiplying two integers. Same for all other arithmetic operations on all numeric types.

**Comment by neil-da** [comment]
Would also be good to say which two integers were being multiplied.
