### ISSUE TITLE
Ledger API Test Tool: survey tests to move into the tool

### ISSUE THREAD

**Issue by gleber-da** [digital-asset/daml#1373]
- [x] DivulgenceIT ~#1792~ #2282
- [x] WitnessesIT ~#2241~ #2486
- [x] ContractKeys #2282 #2491
- [x] CommandServiceIT ~#2241~ #2508
- [x] ActiveContractsServiceIT ~#2241~ #2580
- [ ] CommandTransactionChecksLowLevelIT ~#1792~
- [ ] CommandTransactionChecksHighLevelIT ~#1792~
- [ ] TransactionBackpressureIT ~#1792~
- [ ] TransactionServiceIT ~#1434~
- [x] PartyManagementServiceIT ~#2040~ #2630 
- [ ] CommandSubmissionTtlIT ~#2241~
- [ ] CommandCompletionServiceIT
- [x] PackageManagementServiceIT #2638  

This is the list of most important / highest ROI tests. We still need to add all other *IT tests in `ledger-api-integration-tests` to the test tool.

**Comment by gerolf-da** [comment]
@gleber-da: please provide a description of what is required for this issue.

**Comment by gleber-da** [comment]
The idea is to go over all integration tests and define which of those should be moved into the tool and which are to stay Sandbox-only.

**Comment by gaboraranyossy-da** [comment]
All tests under folder `ledger-api-integration-tests` must be ported. The ones not applicable for all third-party ledgers should be marked as optional.

To have a quick ramp-up with coverage I would start with these tests:

[ ] - CommandTransactionChecksLowLevelIT
[ ] - CommandTransactionChecksHighLevelIT
[ ] - CommandCompletionServiceIT
[ ] - CommandSubmissionTtlIT
[ ] - ActiveContractsServiceIT

**Comment by stefanobaghino-da** [comment]
The missing tests will be split in individual issues and tracked as part of https://github.com/digital-asset/daml/milestone/24
