### ISSUE TITLE
add abstract class parents to generated ordinary records and variants

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13766]
We generate templates with the `Template` parent class; one could be added for generated records and variants as well. At the moment this would only include `toValue` (which is slightly different for each); the record one would become the parent of `Template` (see #13765).

**Comment by stefanobaghino-da** [comment]
Do you expect this to break code if a codegen is re-run across versions purely due to introducing this feature?

**Comment by S11001001** [comment]
> Do you expect this to break code if a codegen is re-run across versions purely due to introducing this feature?

@stefanobaghino-da Yes, if they wildcard-import the package where we add these new parent classes, and they already use a class with the same name, that will be a conflict. It will also break any assumption that the least-upper-bound of two record or variant classes is `Object`.
