### ISSUE TITLE
remove fromIdAndRecord(String, DamlRecord) from codegen output

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13773]
This was deprecated in #1151, that deprecation released in SDK v0.12.18.  Remove it from being generated, _and_ remove the deprecated methods from `ContractCompanion` (#13724).

_Originally posted by @S11001001 in https://github.com/digital-asset/daml/pull/13724#discussion_r862989106_

**Comment by stefanobaghino-da** [comment]
Do you expect this to break code if a codegen is re-run across versions purely due to introducing this feature?

**Comment by S11001001** [comment]
> Do you expect this to break code if a codegen is re-run across versions purely due to introducing this feature?

@stefanobaghino-da Yes. Any code that is still calling this deprecated method will stop working.

**Comment by stefanobaghino-da** [comment]
> > Do you expect this to break code if a codegen is re-run across versions purely due to introducing this feature?
> 
> @stefanobaghino-da Yes. Any code that is still calling this deprecated method will stop working.

Given the long deprecation period, this is more than acceptable, thanks for the feedback.
