### ISSUE TITLE
Expose controllers in Daml

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#13793]
I’d like to have a function of the form
```
controllers : HasExercise t c r => t -> c -> [Party]
```
to get the controllers of a given choice without having to repeat the computation.

I think with interfaces there may be a case where we want an LF primitive for this so there is no option to fake this expression but I haven’t thought this through enough.

low prio imho.

**Comment by akrmn** [comment]
it just means you ___really___ want the new feature 😄
