### ISSUE TITLE
  error type checking <none>:found value cycle

### ISSUE THREAD

**Issue by james-dah** [digital-asset/daml#1379]
Erro goes away when instance is removed, but instance is needed, so that is not a fix.

 da run damlc -- package daml/ForDAMLTeam.daml target/daml/x
da-hs-damlc-app: user error (Creation of DAR file failed:
File:     daml/ForDAMLTeam.daml
Range:    1:0-100001:0
Source:   Ide Error
Severity: DsError
Message:  error type checking <none>:found value cycle:* $c_tolstoy2* $fOneAlien
Code: 
)

[ForDAMLTeam.daml.zip](https://github.com/digital-asset/daml/files/3217007/ForDAMLTeam.daml.zip)

**Comment by hurryabit** [comment]
I have a minimal example exhibiting the same problem:
```haskell
class Id a where
  id : a -> a
  id = \x -> x

instance Id Int where
```
`damlc` does something we call "dictionary sanitization" to account for the fact that GHC's handling of default implementations of type class methods is written under the assumption of lazy semantics. Unfortunately, this sanitization is currently broken for type classes which have exactly one method and this method has a default implementation. I'd say this is a very rare corner case but I'll see if there's a quick fix nevertheless.
