### ISSUE TITLE
Upstream GHC 9 support patches to rules_haskell

### ISSUE THREAD

**Issue by aherrmann-da** [digital-asset/daml#13800]
The [rts-docs and ghc-includes patches](https://github.com/digital-asset/daml/blob/a9ec10a62982d14d0d5a8efe017b8c302c3d4d07/deps.bzl#L45-L48) currently maintained here in the Daml repository should be upstreamed to rules_haskell.

**Comment by cbley-da** [comment]
Done in https://github.com/digital-asset/daml/pull/14045
