### ISSUE TITLE
Improve error message for fields called `this`, `self` or `arg` in templates or template choices

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#13811]
Currently, declaring fields with these names results in poor error messages, for example,

```haskell
template Foo
  with
    p : Party
  where
    signatory p

    choice FooC : ()
      with
        arg : Decimal
      controller p
      do
        return ()
```

fails with

```
  Foo.daml:41:18: error:
  • Conflicting definitions for ‘arg’
  Bound at: Foo.daml:41:18
  <no location info>
  • In a lambda abstraction

  Foo.daml:42:7: error:
  • Conflicting definitions for ‘arg’
  Bound at: Foo.daml:(42,7)-(43,17)
  <no location info>
  • In a lambda abstraction
```

Ideally, this would be caught by the `daml-preprocessor`, giving users an actionable error message.

## Background
This was originally reported as https://github.com/digital-asset/daml/issues/3017, but the idea there was to _allow_ such fields by tweaking the desugaring. That approach introduces a lot of complexity for little gain, so instead we just want to improve the error messages.

**Comment by basvangijzel-DA** [comment]
Might be easier to forbid arg etc as a variable name in this context and propagate this as an error message.

**Comment by samuel-williams-da** [comment]
We'd need to specifically check choice/argument fields, and any body that can take this, self or arg as an argument.
This sounds like it could get messy, I think a daml suggested warning would be better

**Comment by samuel-williams-da** [comment]
Alternatively, we can simply search template/choice arguments to look for these, and not generate the argument label in desugaring if it exists. Maybe alongside a warning for using this name

**Comment by samuel-williams-da** [comment]
or even, rename self, this and arg to be less likely to clash - maybe `_this`, or even some weird symbols
