### ISSUE TITLE
Add or document livelihood/readiness endpoints for the Trigger Service

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#13819]
### What is the problem you want to solve?

I would like to be able to use widely used tools (e.g. Kubernetes) to manage Trigger Service instances so that I can effectively achieve high availability of the service on my deployment.

### What is the solution you would propose?

Add a `/readyz` and `/livez` endpoint like the HTTP JSON API Service.

### Describe alternatives you've considered

Using another endpoint to check for the livelihood of the service, but I'm not sure about which one could be used to this end. If the problem can be solved that way, I'd find it satisfactory to document this.

**Comment by garyverhaegen-da** [comment]
FYI `/livez` is [already documented](https://docs.daml.com/2.1.1/tools/trigger-service/index.html#liveness-check). I see no reference to `/readyz` in either docs or source.

**Comment by stefanobaghino-da** [comment]
IIUC this means the Trigger Service advertises when it's running but not whether it's ready to accept traffic. Or does a positive liveness check "imply" readiness, in the absence of an explicit `/readyz` endpoint?

**Comment by ray-roestenburg-da** [comment]
Liveness and readiness are separate. No liveness restarts the pod, no readiness stops traffic to the pod.

**Comment by stefanobaghino-da** [comment]
> Sorry I just meant the first "half" of the issue described is already solved. I did not mean to imply the second half doesn't need to be solved.

Nothing to be sorry about, I was asking precisely to ensure whether this still needed resolution. Thanks to both you and @ray-roestenburg-da for the information.

**Comment by ray-roestenburg-da** [comment]
I don't know much yet about the trigger service yet, but since it has an endpoint, it could make sence to add a readyz endpoint. Without it it is assumed to always be ready. Is that an issue?

**Comment by garyverhaegen-da** [comment]
> I don't know much yet about the trigger service yet, but since it has an endpoint, it could make sence to add a readyz endpoint. Without it it is assumed to always be ready. Is that an issue?

From a cluster management perspective, "ready" means the cluster can proxy requests to this instance, and "live" means the instance is not crashed. So being live but not ready is a valid state, assuming they've both been coded correctly and that state implies the instance expects to be able to recover.

I can see two issues with not having a `/readyz` endpoint:

1. Should the Trigger Service instance ever get into a broken state, chances are it'll still respond to `/livez`, and in the absence of a `/readyz` it will keep getting requests. This may disrupt service as observed by end users.
2. It just looks bad. As a cluster operator, an application that doesn't have a readiness endpoint looks like it's not been designed to run in a modern cloud environment.

**Comment by ray-roestenburg-da** [comment]
Without a ready endpoint the service is always deemed to be ready.
Both readiness and liveness checks can malfunction over time and provide false negatives / positives for many reasons, which can also result in a less available service.

Some reasons to have a ready endpoint:
- The triggerservice has a known long initialization phase where it cannot handle requests
- The triggerservices needs to get into some state before it can handle requests (maybe depending on some other k8s service)

In general I'm fine with adding a simple `readyz` endpoint. Maybe a good question is, has anyone run into a situation where the omission of the readyz endpoint caused a problem?

**Comment by stefanobaghino-da** [comment]
The main reason to have a `readyz` endpoint is to enable customers using standard container orchestration tooling i.e. Kubernetes. I would recommend to:
* add a `readyz` endpoint
* ensure that the behavior of the `livez` endpoint matches the semantics expected by Kubernetes

Both points are important to enable users to operate a fleet of containers running Daml runtime components.
