### ISSUE TITLE
Better error message on trying to derive custom class

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1381]
When a user tries to `derive` a class that cannot be automatically derived, they get a fairly unhelpful (and arguably misleading) error message. For example, the following code:
```haskell
data SomeData = SomeData with someText : Text deriving (MyClass)
class MyClass a where
  fn : [a] -> Decimal
```
produces the error
> 'MyClass' is not a stock derivable class (Eq, Show, etc.). Try enabling DeriveAnyClass

According to @cocreature,
> DeriveAnyClass is most likely not what you want.

I believe an error message along the following lines would be more helpful:
> Only a small set of built-in classes (Show, Eq, etc.) can be `derive`d automatically. For all other classes, including user-defined classes, you probably want to define the instance explicitly. Here is a starter template:
> ```haskell
> instance MyClass SomeData
>   fn x = ...
> ```
> Also, do not forget to remove `MyClass` from the list of `derive`d classes on line X.

@cocreature mentioned this error message is coming straight from GHC and therefore may not be easy to change. I leave the decision of whether this is worth the effort to people who are better able to evaluate it.

**Comment by cocreature** [comment]
We’re not going to patch GHC for this so closing.
