### ISSUE TITLE
Bad error message when implementing non-interface

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#13823]
I accidentally used an `implements` clause on something that was not an interface and the error looks somewhat confusing:
```
template T
  with
    p : Party
  where
    signatory p
    implements T where
```

```
  Failure to process Daml program, this feature is not currently supported.
  interface type with {abstract:tycon}
  T
```

In that case it was the template itself but I don’t think it matters, implementing `Time` for example produces the same error.

It would be nice to get a slightly more meaningful error, something along the lines of "tried to implement non-interface T"

**Comment by akrmn** [comment]
Fixed by https://github.com/digital-asset/daml/pull/14249
