### ISSUE TITLE
Internal wrapped expression type is returned by the Trigger service in an error message.

### ISSUE THREAD

**Issue by matevarga-da** [digital-asset/daml#13893]
### What is the problem you want to solve?

When the trigger service is requested to run a trigger and the name is of the wrong type, an HTTP 422 (Unprocessable Entity) is returned with a message that refers to the full type of the expression built in the trigger service that will run the trigger. This makes the original type mangled and the possible resolution confusing to understand. When trying to "run" a TriggerA instead of a Trigger, this message was returned:
```
{
"errors": [
"TForall((s,KStar),TApp(TApp(TBuiltin(BTArrow),TBuiltin(BTParty)),TApp(TApp(TTyCon(06430080c9d08699ebbbc1b7a581b6a49241f44cbb0505fcb12144a57ae61c5f:Daml.Trigger.Internal:TriggerA),TVar(s)),TBuiltin(BTUnit)))) is not a valid type for a trigger"
],
"status": 422
}
```

### What is the solution you would propose?

Return the original type the trigger service was asked to run.

**Comment by stefanobaghino-da** [comment]
@sofiafaro-da @remyhaemmerle-da Is this something under your control?
