### ISSUE TITLE
Valdiate key hashes of disclosures.

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#13897]
We need to validate the submitted key hashes in the disclosure metadata.

**Comment by carlpulley-da** [comment]
@cocreature just looking through the Speedy code trying to understand what we can do to resolve this issue.

If we are to perform key hash validation, it currently looks to myself as if we need to know the contract key (e.g. as `GlobalKey` or a `Value` instance) when we construct the disclosure table. Checking that the key hash is correct whilst executing `SBUFetchKey` or `SBULookupKey` looks like it occurs too late to be of any use?

As we have already been supplied with the contract key hash (in order to construct the `DisclosedContract` instance), supplying the full key as part of the disclosures doesn't look unreasonable (as that information must already be to hand).

That said, does this seem a reasonable change here to yourself or am I missing something?

**Comment by cocreature** [comment]
> supplying the full key as part of the disclosures doesn't look unreasonable

Key values can get fairly large, we need to limit the data we ship around to what we actually need. Now we could ship no keys at all and compute them as part of buildDiscTable. But that means we have to compute all keys even for contracts that I never fetch which is also not great.

So instead, the approach we settled on is the following:
1. A ledger API user passes in the contract key hash.
2. buildDiscTable does not validate it, it just builds the table based on the hash.
3. Now if you do key resolution against the disc table in SBUFetchKey, you first resolve against the disc table which gives you a contract. You then compute the actual key based on that contract and checks that it has the same hash. If it doesn't you abort the transaction.

This check is mainly a UX thing. We would fail during validation anyway but the errors are super confusing and it's unclear who you attribute the error to (the submitter might have gotten the disclosed contract from a third party).

I do think this is the flow we want to settle on eventually but if you want a potentially easier first step, we could start by computing all keys at the beginning in buildDiscTable and do this as an optimization later.

**Comment by carlpulley-da** [comment]
@cocreature `SBUKeyBuiltin.execute`:
- uses a Speedy stack key argument to define the key being used by the `SBUFetchKey` or `SBULookupKey` operation
- uses the operation template Id to determine the template being used
- calculates a `GlobalKey` (with a fresh/good hash key calculated) using these two values (i.e. the key `SValue` and the `operation.templateId`).

At this point, we have already calculated the expected key hash using good (i.e. non-disclosed contract) data. 

https://github.com/digital-asset/daml/pull/14563 introduces a template ID check - specifically it validates that the returned contract template ID (sourced from the disclosure table) matches the operation template ID.

As a result, and based on the prior comments, I think https://github.com/digital-asset/daml/pull/14563 may well be providing a fix for this issue? Does that sound reasonable or have I missed something?

N.B. I should point out that if https://github.com/digital-asset/daml/pull/14563 is resolving this issue, then errors manifest not as a key hash being incorrect, but as the contract being incorrectly typed.

**Comment by cocreature** [comment]
@carlpulley-da If I understand you correctly you’re talking about how you calculate the GlobalKey and thereby also the hash that you use to do the lookup. I agree that one is not relying on disclosed data.

But then you do the actual lookup using that key in disclosed contracts. At what point do you validate that the key of the contract returned by that lookup matches the key you used for the lookup?
