### ISSUE TITLE
daml-on-x-example: create repo with example DAML ledger

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#139]
Goal: provide standalone example of a DAML ledger implementation built on top of the integration kit.

- [x] release all artifacts required for example to external Maven URLs as part of the DAML SDK release
- [x] remove TODO and issue link to this issue in DAML Integration Kit docs  
- [x] example is being created here: https://github.com/digital-asset/daml-on-x-example

**Comment by gleber-da** [comment]
I believe point #1 is solved:
https://github.com/digital-asset/daml/blob/master/release/artifacts.yaml#L140
https://bintray.com/digitalassetsdk/DigitalAssetSDK/sdk-components/100.12.10#files/com%2Fdaml%2Fledger%2Fapi-server-damlonx_2.12%2F100.12.10

Marking it as such

**Comment by gleber-da** [comment]
This is done in:
https://github.com/digital-asset/daml-on-x-example

There's a tiny follow to be done: https://github.com/digital-asset/daml/issues/777
