### ISSUE TITLE
parseInt/parseDecimal overflows

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#1390]
When we do:

     parseInt "11111111111111111111"

We get

    CRASH: long overflow

Should we be aiming for None? Or is an error acceptable? My view is that it had better be None, but the only realistic way of getting there is to write a checked Num library, which uses NaN rather than throwing an error if you would overflow, and that's a project in itself.

While we now test that we can parse the maximum precision of `Int`, we have no comparable tests for `Double` - we should.

**Comment by neil-da** [comment]
Alternative approach is just to add a ledger primitive, so we are perfect synchronization CC @hurryabit @bitonic. That's perhaps the only long term way of getting it matching perfectly.

**Comment by bitonic** [comment]
I think the error is what's most in line with fairly inevitable overflow semantics for addition and multiplication. I'd be fine with a `parseIntOptional` in DAML though.

**Comment by garyverhaegen-da** [comment]
Not to derail this too much, but should we consider _not having_ types that can overflow? Contracts seem like a domain model in which one would be willing to revisit the traditional tradeoffs between correctness and speed around fixed-length numeric representations.

If we do support fixed-length arithmetic, my personal preference would be for operations like `parseInt` to fail at compile time when possible (e.g. parsing a literal string, as in this example), for faster feedback. As far as runtime behaviour is concerned, I can see three ways to deal with fixed-length arithmetic, and I think ideally we should offer all three:

- Numeric operations silently wrap, i.e. `MAX_INT + 1 == MIN_INT`.
- All numeric operations return an Optional (or an Either if we want more information) so users can explicitly deal with those issues; this can be a bit cumbersome for users, though.
- Numeric operations throw an error on over- and underflow; this would be something of a balance between the two previous options: not too much overhead in the code, but still reasonable results.

All three options apply just as well to `parseInt` as to `+`.

**Comment by remyhaemmerle-da** [comment]
daml-lf 1.5 implements  `FROM_TEXT_INT64 : Text -> Optional Int64` (See #1407)

**Comment by remyhaemmerle-da** [comment]
DAML-LF `Decimal` operations never underflow, as the result is always rounded (using bancker's rounding)

**Comment by hurryabit** [comment]
This was fixed a while ago.
