### ISSUE TITLE
use Objects.equals instead of Object#equals

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13901]
Generated Java codegen output includes things like

```java
return this.owner.equals(other.owner) && this.myRecord.equals(other.myRecord) && // ...
```

Likewise with `codegen.Contract` and `codegen.ContractWithKey`, which were refactored from this generated output.

Instead this should look like

```java
return Objects.equals(this.owner, other.owner) && Objects.equals(this.myRecord, other.myRecord) && // ...
```

**Comment by stefanobaghino-da** [comment]
Can you clarify the reason why the current generated code is incorrect?

**Comment by S11001001** [comment]
> why the current generated code is incorrect

Similar to `Any#==` in Scala, it handles `null`. Sure, generally, we don't care to account for that, but `equals` methods typically seem to, including other argument tests we currently generate.
