### ISSUE TITLE
JS codegen doesn't generate modules with only empty interfaces

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#13935]
# Affected Daml version

2.3.0-snapshot.20220517.9906.0.de6da710

# Bug description

Interfaces without any choices, in modules without types, don't get codegenerated at all. Therefore, any code that references such interface doesn't compile.

**Comment by S11001001** [comment]
@GeorgSchneider I attempted to reproduce this unsuccessfully in a8426410226a613cca7a3e85e86c448972709b19; the test added there compiles and passes successfully. Could you share any difference between that test and your own test case that might produce the bug?

**Comment by georg-da** [comment]
I can't repro this anymore using the steps I provided. Ok for me to close, it's not an issue anymore in our codebase. Will reopen if I hit it again.

**Comment by S11001001** [comment]
> I can't repro this anymore using the steps I provided.

#13501, #13504, and #13754 were recently fixed in JS codegen related to interfaces; one of those might be familiar.

**Comment by georg-da** [comment]
I've hit this issue again just now. Provided repro steps in the linked issue.

I think the issue occurs if you have a file that _only_ contains an interface without choices, and no other data types or templates.

Such file is then missed entirely from the codegen. Adding some dummy type is sufficient to get things generated correctly.
