### ISSUE TITLE
Monolith Upgrade Demo

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#13967]
Explore how the Daml design style proposed by "Canton Network Upgrades" can be applied even in the case of monolithic Daml applications.

https://github.com/DACH-NY/monolith-upgrade-demo

**Comment by nickchapman-da** [comment]
Synced and Handed over to Motitz.

**Comment by stefanobaghino-da** [comment]
@nickchapman-da or @moritzkiefer-da can either of you summarize your findings with regards to transitioning a monolith application to an upgradable one?

**Comment by cocreature** [comment]
I’ll add a section to https://docs.google.com/document/d/1Oogaz1mZ54Ar5Avfttt1QG6Sh4AZ1nwLcUP_lFYZD48/edit#heading=h.j1o9vy5fqmrz. I’ll try to get to it today.

**Comment by stefanobaghino-da** [comment]
Thanks, I appreciate.
