### ISSUE TITLE
Add parseInt64 and parseDecimal to DAML-LF

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#1398]
Re-implementing both functions in DAML is a recipe for diverging semantics. Thus, we should add two new primitives to DAML-LF:
```
PARSE_INT64 :: Text -> Optional Int64
PARSE_DECIMAL :: Text -> Optional Decimal
```

**Comment by remyhaemmerle-da** [comment]
I propose to follow convention we used for parties , that is use `FROM_TEXT` instead of `PARSE`.

```
FROM_TEXT_INT64 :: Text -> Optional Int64
FROM_TEXT_DECIMAL :: Text -> Optional Decimal 
```

**Comment by hurryabit** [comment]
I would rather rename `FROM_TEXT_PARTY` to `PARSE_PARTY` instead of doubling down on this naming schema.

**Comment by remyhaemmerle-da** [comment]
I would rather rename FROM_TEXT_PARTY to PARSE_PARTY instead of doubling down on this naming schema.

@hurryabit  wrote:

> I would rather rename `FROM_TEXT_PARTY` to `PARSE_PARTY` instead of doubling down on this naming schema.

OK for me.

**Comment by bitonic** [comment]
Those are fine by me. What shall the semantics be regarding

* Overflow?
* Leniency? Only accepting numbers that are identical to what's produced by `TO_TEXT_INT64` has nicer semantics, but would probably be very annoying to the user.

Regarding naming: let's not needlessly rename things. we already have a to of `TO_TEXT_X` functions, let's just stick with that scheme in DAML-LF.

**Comment by remyhaemmerle-da** [comment]
I understand that for overflow we return `None` .

For Leniency I propose to process only the : 
- strings that match  `[+-]?[0-9]+` (for In64)
- strings that match `[+-]?[0-9]+(\.[0-9]+)?` (for decimal)

We return None for any string that do not match the regexp or those that cannot be converted without overflow or lost of precision.

**Comment by remyhaemmerle-da** [comment]
@hurryabit DAML-LF 1.5 or 1.6 ?

**Comment by hurryabit** [comment]
Let's add it to DAML-LF 1.5. I'll expose the two functions in the `daml-stdlib` tomorrow.
