### ISSUE TITLE
Interface View 

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#14112]
- [x] Check that template implements interface
- [x] Check that interface has view method
- [x] Check that view result is serializable (in both compiler & scala side)
- [x] Switch to builtin interfaces views once they have been added to LF

EDIT(@akrmn, 2022-08-17):
- [x] Interface view integration tests

**Comment by remyhaemmerle-da** [comment]
@moisesackerman-da do you consider the integration test is done ?
