### ISSUE TITLE
Drop visibility restrictions for locally created contract keys & disclosed contract keys

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#14199]

**Comment by carlpulley-da** [comment]
From the design documentation for _Command Submission with Disclosed contracts_ we have:

> **Contract Key Visibility**

> The visibility of contract keys during command submission is relaxed to allow fetch/lookup by key for local contracts created in the current transaction even if the readers are not the contract’s stakeholders. This is required to satisfy R4. This does not leak information as the submitter is aware of the create given that it happened in the same transaction.

**Comment by carlpulley-da** [comment]
Outstanding work for this issue is currently captured on PR https://github.com/digital-asset/daml/pull/15131 - this PR has been temporarily parked.
