### ISSUE TITLE
Data-dependencies generate interface types without a constructor

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#14217]
Data-dependencies end up generating an interface payload as something like
```
data CurrentSdk.GHC.Types.DamlInterface => A
```

Consider
```
module Dep where
interface A
```
and then in a package that depends on this via data-dependencies
```
module Main where
import qualified Dep
f : Optional Dep.A -> Dep.A
f x = case x of
  Some x -> x
  None -> error "lol"
```

This fails with
```
  Pattern match has inaccessible right hand side
  In a case alternative: Some x -> ...
```

We should also generate a constructor with `Opaque` like we do outside of data-deps.

**Comment by akrmn** [comment]
aah good catch, we want `Any`, not `Void` :) it's an easy fix though
