### ISSUE TITLE
build-and-lint dependencies

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#14224]
See #13876.

**Comment by stefanobaghino-da** [comment]
The description points at a closed PR. What is this ticket about?

**Comment by garyverhaegen-da** [comment]
> The description points at a closed PR. What is this ticket about?

The PR is a temporary hot fix; this issue is meant to track a more stable, long-term fix.

The proximate issue fixed by the PR was that build-and-lint suddenly broke. The reason it broke is that the dependencies we use for running the test are not pinned, and we therefore use "whatever the internet thinks is the right version right now" for a bunch of our transitive dependencies, which is brittle.

The hotfix pinned one dependency somewhere in the chain to "make things work" at that one point in time. A proper fix would apply a more structured approach to pinning all of the dependencies (I'm not prescriptive here; I guess something along the lines of committing a lockfile could work, or building with Nix, or integrating in Bazel).

Separately, we also have quite a few very old dependencies in there (which is part of why things broke), and it may be a good idea to bump all of that at some point (but that requires a bit of work on our code because as it stands our code is not compatible with modern TypeScript compilers).

Note that all of that is about the code in build-and-lint, i.e. the TypeScript code we use to drive our "integration" test of the TS bindings against a live JSON API. None of this really impacts our packaged tarballs (which do have pinned dependencies AFAIK).

**Comment by S11001001** [comment]
> I guess something along the lines of committing a lockfile could work

There is a lockfile format, `yarn.lock`. I'm not sure why we don't have lockfiles committed for all the various `package.json`s. But I think that would be the best approach, rather than mentioning all transitives explicitly in `package.json`.
