### ISSUE TITLE
Deprecate custom views in Navigator

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#14234]
Custom views were an early attempt at allowing early prototyping. Thanks to the HTTP JSON API Service, the React.js bindings and `create-daml-app`, we already have that area covered and Navigator can start to deprecate the feature.

The first attempt a doing this consisted on a doc-only fix (https://github.com/digital-asset/daml/pull/14177). However, an agreement was reached as part of the PR review (see https://github.com/digital-asset/daml/pull/14177#discussion_r898049233_) to extend the scope of the fix to:
- apply the documentation changes, and additionally
- issue a warning when the feature is used
- remove its usage from `quickstart-java` (including the mention of the feature in its own tutorial document)

**Comment by leonidr-da** [comment]
We do have users who are hacking these things into Navigator. It makes https://github.com/digital-asset/daml/issues/14248 even more pressing.

@LeventeBarczyDA I know that you use this too

**Comment by LeventeBarczyDA** [comment]
There is some impact from this on our existing set of demo libraries. And it's not true that the Navigator is purely a development tool. Even in cases where we have built out a UI, we use the navigator as the "back-end" view, a la the Hub Live contracts view.

**Comment by stefanobaghino-da** [comment]
> There is some impact from this on our existing set of demo libraries.

We understand this, which is why this will be phased out following the normal deprecation cycle.

> And it's not true that the Navigator is purely a development tool. Even in cases where we have built out a UI, we use the navigator as the "back-end" view, a la the Hub Live contracts view.

They may work for small ledgers, but the Navigator is not designed to scale and it won't, since it keeps the whole state of the ledger locally with an assumption of total visibility across parties, which are safe assumptions for development but not for very large ledgers with a secure access. Furthermore, its API is not part of the product and is already subject to breaking changes, so I would discourage building on top of it for products that need a stable API.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
