### ISSUE TITLE
Public methods for creating contract ids

### ISSUE THREAD

**Issue by matthiasS-da** [digital-asset/daml#14257]
The contract id scheme is described here:
https://github.com/digital-asset/daml/blob/main/daml-lf/spec/contract-id.rst

For testing, it would be helpful to have public methods implementing the following functions in the contract id scheme:
- transactionSeed
- rootSeed
- childSeed
- discriminator
- contractId
(Function signature and semantics as described in the rst.)

If they already exist, I would appreciate a pointer.

**Comment by cocreature** [comment]
I think most of those actually exists already:
- [deriveTransactionSeed](https://github.com/digital-asset/daml/blob/d74af21e907289d75d7c34d4d93edecef1a59e0e/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/crypto/Hash.scala#L356)
- [deriveNodeSeed](https://github.com/digital-asset/daml/blob/d74af21e907289d75d7c34d4d93edecef1a59e0e/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/crypto/Hash.scala#L366). This gives you both childSeed & rootSeed
- [deriveContractDiscriminator](https://github.com/digital-asset/daml/blob/d74af21e907289d75d7c34d4d93edecef1a59e0e/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/crypto/Hash.scala#L372)
Anything that is missing for your usecase?

**Comment by matthiasS-da** [comment]
That sounds good.
