### ISSUE TITLE
Introduce a safe way to uninstall an SDK version

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#1427]
Right now, the only way to get rid of an SDK version through the `daml` assistant is by manually deleting it (making sure we're not deleting the currently active one).

Would be nice to have something like

    > daml uninstall 0.12.3

It would be probably desirable to prevent the user from accidentally removing the currently active version.

Still, there may be cases when a convenient short-hand to uninstall-and-switch could be useful. Probably could be nice to have something like the following interaction

    > daml uninstall 0.12.3
    ERROR: unable to forcibly uninstall 0.12.3 because it's the currently active version
    SUGGESTION: in case you want to delete the currently active version, please explicitly state the version you'd like to switch to with the `--switch-to` CLI argument

    > daml uninstall 0.12.3 --switch-to=latest # up-to-date with all the things :)

**Comment by associahedron** [comment]
Sounds good. Instead of providing a "switch to" I think just letting the user know they can't uninstall the active version, and they can resolve this by using `daml install latest --activate`. It's best not to make `uninstall` too complicated, I feel.

**Comment by stefanobaghino-da** [comment]
Cool, I was thinking of this as something like `git checkout -b` in terms of convenience but I see your point.

**Comment by ndmitchell** [comment]
Agreed with keeping it simple. I imagine uninstall will be rare. Let's have it just do one simple thing.
