### ISSUE TITLE
illustrate the phantom/nominal contract ID distinction in Java codegen, maybe work around

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14299]
In Scala codegen, `ContractId[T] = T.ContractId`. However, in Java codegen, `T.ContractId <: ContractId<T>` but not vice versa, which means that `(cidT: ContractId<T>).exerciseX(...)` doesn't work, and `((T.ContractId) cidT)` can fail too.

* [x] add a test illustrating this distinction for Java codegen using `illTyped`, and that a decoded-from-Value `ContractId<T>` may not even be `instanceof T.ContractId`
* [ ] [optional] document it? (We usually don't go into detail on such corner cases)
* [ ] [optional] create a `ContractId<T> => T.ContractId` utility for `ContractCompanion`, with a static forwarder on the codegenned `ContractId` classes

It's also possible that we can get `((T.ContractId) cidT)` to work, but would require a significant redesign of the decoder path. #14313 

Example `fromValue` illustrating the problem:

```java
  public static <a> ParametrizedContractId<a> fromValue(Value value$, Function<Value, a> fromValuea)
      throws IllegalArgumentException {
    Value recordValue$ = value$;
    DamlRecord record$ = recordValue$.asRecord().orElseThrow(() -> new IllegalArgumentException("Contracts must be constructed from Records"));
    List<DamlRecord.Field> fields$ = record$.getFields();
    int numberOfFields = fields$.size();
    if (numberOfFields != 1) {
      throw new IllegalArgumentException("Expected 1 arguments, got " + numberOfFields);
    }
    ContractId<a> parametrizedContractId = new ContractId<a>(fields$.get(0).getValue().asContractId().orElseThrow(() -> new IllegalArgumentException("Expected parametrizedContractId to be of type com.daml.ledger.javaapi.data.ContractId")).getValue());
    return new tests.recordtest.ParametrizedContractId<a>(parametrizedContractId);
  }
```

**Comment by chunlokling-da** [comment]
> static forwarder on the codegenned ContractId classes
I am making ContractId<T> => T.ContractId utility available in ContractCompanion
What does a "static forwarder" mean here? Is there any example "static forwarder" I can follow? Thanks cc @ray-roestenburg-da

**Comment by ray-roestenburg-da** [comment]
A static forwarder in Scala is some generated code (for convenience) that provides Java users access to methods on a Scala object. this makes it possible for Java users to just call `SomeObject.foo` on class `SomeObject` where foo is a static method, instead of going through `SomeObject$.MODULE$.foo` (I think that is what  @S11001001 is referring to, though conceptually).

**Comment by ray-roestenburg-da** [comment]
So in this case the generated `ContractId` class should get a static method that calls the ContractCompanion utility method.

**Comment by chunlokling-da** [comment]
Thanks, based on your information, I believe the "static forward" is referring to [this](https://github.com/digital-asset/daml/blob/9a086ec2254478e175e8eeed5c55181f5e204c11/language-support/java/codegen/src/main/scala/com/digitalasset/daml/lf/codegen/backend/java/inner/ContractClass.scala#L86)

**Comment by S11001001** [comment]
> Thanks, based on your information, I believe the "static forwarder" is referring to [this](https://github.com/digital-asset/daml/blob/9a086ec2254478e175e8eeed5c55181f5e204c11/language-support/java/codegen/src/main/scala/com/digitalasset/daml/lf/codegen/backend/java/inner/ContractClass.scala#L86)

That's right.
