### ISSUE TITLE
Error parsing script JSON input file

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#14438]
# Affected Daml version

2.2.0

# Bug description

I have a script with signature `s : [Int] -> Script ()`.
I have a json file containing `[100000,100]`.

When running 

```
script --ledger-host=localhost --ledger-port=6865 --dar .daml/dist/mydar-0.0.1.dar --script-name Test:s --input-file=inputs.json
```

I get an error

```
Exception in thread "main" com.daml.script.converter.ConverterException: LF conversion failed: spray.json.DeserializationException: Can't read [100000, 100] as TypePrim(PrimTypeInt64,IndexedSeq())
```

# To reproduce

See above

# Expected behavior

Run my script

# Additional context

**Comment by garyverhaegen-da** [comment]
Cannot reproduce.

Here's my test case:

```plain
$ cat input.json
[100000,100]
$ cat daml/Main.daml
module Main where

import Daml.Script

main : [Int] -> Script ()
main ns = do
  debug $ sum ns
$ daml script --ledger-host localhost --ledger-port 6865 --dar .daml/dist/t-0.0.1.dar --script-name Main:main --input-file input.json
[DA.Internal.Prelude:555]: 100100
$
```

Please provide a more complete reproduction.

**Comment by cocreature** [comment]
@bame-da your error message has something that looks like a space in there, your  input file does not. Is there maybe some weird non-breaking space or whatever in there?

**Comment by bame-da** [comment]
It must have been something like that. I had fixed my failing project by switching to a record type instead of [Int] and can no longer reproduce myself. Closing.
