### ISSUE TITLE
Reset service takes ages to complete

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#1443]
When I use a large deadline for a non terminating server-streaming RPC, `TransactionService.GetTransactions`, then a subsequent call to `ResetService.Reset` takes 10 or 15 seconds to complete -- where complete is determined by a successful call to `LedgerIdentityService.GetLedgerIdentity`.

For some context: I am trying to use the reset service when writing tests for the Haskell ledger bindings, so I don't have to spin up a new sandbox ledger (2.5+ seconds) for each separate test.

**Comment by gaboraranyossy-da** [comment]
@francesco-da it seems Haskell folks are still having issues with the ResetService.

**Comment by nickchapman-da** [comment]
I managed to avoid the 10s hang by cancelling the in-flight streaming RPCs before calling ResetService.
https://github.com/digital-asset/daml/pull/1460
