### ISSUE TITLE
replace nullable `ExercisedEvent#getInterfaceId` with an Optional property

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14483]
We generally use `Optional` in the Java event model, e.g. `CreatedEvent#agreementText`. `ExercisedEvent#interfaceId` is an exception. We should give the property type `Optional<Identifier>` instead.

**Comment by cocreature** [comment]
If you remove it before interface GA you can avoid the whole deprecation dance which seems preferable.
