### ISSUE TITLE
DAR Upload in Daml Script Runner breaks Daml Script with multiple participants

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#14562]
https://github.com/digital-asset/daml/commit/1afd0bf479871be9920209d1c0698cea50afc8d7 added a DAR upload to `RunnerMain` which assumes `ledger-host` is defined. That’s not true if you use a participant config.

I think the proper fix here is to drop this DAR upload completely and move it to the integration tests.

This is a regression in 2.3.

Steps to reproduce:
1. `daml new foobar`
2. `cd foobar && daml build`
3. `daml sandbox --dar .daml/dist/foobar-0.0.1.dar`
4. Create `participants.json` with the following content
```
{
    "default_participant": {"host": "localhost", "port": 6865},
    "participants": {},
    "party_participants": {}
}
```
5. ` daml script --dar=.daml/dist/foobar-0.0.1.dar --script-name Main:setup --participant-config participant.json`
6. See the error
7. Fix the error

**Comment by stefanobaghino-da** [comment]
Interesting how "fix the error" is in the steps to reproduce. :trollface:

**Comment by cocreature** [comment]
It's a trap. If you don’t read all the way through and get to 7 you have to fix it.
