### ISSUE TITLE
ledger-api-test tool: better test coverage

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#146]
Todo's for further iterations on testing the conformance of a Ledger API server 

Coverage improvements:
- [ ] port all black box tests from other integration tests into the tool to extend the test coverage
- [ ] ensure semantic tester can check multi-participant workflows (requires to provide it with a topology configuration stating what party is hosted at what Ledger API)
- [ ] elicit error paths (e.g. submitting an ill-typed command)
- [ ] validate that the semantic tester is precise wrt to returned transaction trees (i.e., also checks that not too much data is shown)
- [ ] cover https://github.com/digital-asset/daml/issues/786

Features:
- [x] remove reset requirement using the `<uuid>` prefix for parties choosing a new <uuid> for every test

Quality:
- [ ] test the semantic tester (i.e., ensure it actually does find problems in the implementation)

**Comment by meiersi-da** [comment]
@gleber-da : I've just found this pre-existing ticket for additional tests that we would like to have. Many will probably be covered by the remaining ledger integration tests of the Sandbox code. I've assigned this ticket to you so you can coordinate and update accordingly with the knowledge you gain from the investigation into the remaining ledger integration tests of the Sandbox code.

**Comment by gleber-da** [comment]
@meiersi-da :+1:

**Comment by stefanobaghino-da** [comment]
Replaced by the https://github.com/digital-asset/daml/milestone/24
