### ISSUE TITLE
Extractor fails to work with a large package (buffer size not configurable)

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#1463]
We are developing a large DAML model, and the customer intends to use Extractor.
Since yesterday, builds are failing in a CI step that tests the interaction of sandbox and extractor, with the following error in a log file.  
```
INFO: Received data on closed stream
07:43:50.556 ERROR c.d.e.Main$@[ka.actor.default-dispatcher-10] - FAILURE:
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 52428800: 54226504.
Exiting...
```
This hints at the (hard-coded) 50MB size limit in

https://github.com/digital-asset/daml/blob/9f80f4cb600c3b147d16d5409404ddddb7057e14/extractor/src/main/scala/com/digitalasset/extractor/Extractor.scala#L224-L227

The size should be configurable.

In addition, we would suggest using [withCompression](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withCompression-java.lang.String-) on the package service in

https://github.com/digital-asset/daml/blob/9f80f4cb600c3b147d16d5409404ddddb7057e14/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/LedgerClient.scala#L111

**Comment by S11001001** [comment]
Let's add an extractor command-line option to set the message size, `--ledger-api-message-size-max`, as a _stopgap_.

Afterwards let's try #1496 to make it so no one needs to use that deliberately long-winded option.

/cc @leo-da @bitonic

**Comment by leo-da** [comment]
I don't knog grpc that well, but I thought it is better to make it configurable in the sandbox, both `maxInboundMessageSize` and `maxOutboundMessageSize`. This way we can solve this issue for all possible sandbox clients.

https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withMaxOutboundMessageSize-int-

**Comment by leo-da** [comment]
Reading the doc: https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withMaxOutboundMessageSize-int-

if we remove this `maxOutboundMessageSize` in sandbox, does it mean it will be unlimited?

**Comment by jberthold-da** [comment]
Thanks for preparing the PR, looking good already.
Please note we will need a similar patch to Navigator, see here
https://github.com/digital-asset/daml/blob/master/navigator/backend/src/main/scala/com/digitalasset/navigator/store/platform/PlatformStore.scala#L307
