### ISSUE TITLE
Сircular dependency 

### ISSUE THREAD

**Issue by socproof** [digital-asset/daml#14644]
https://github.com/digital-asset/daml/blob/f529a2a0159e97aa8f74bff7794b07785fdda6c0/ledger-api/grpc-definitions/com/daml/ledger/api/v1/value.proto#L29

Hi!
I am trying to import service with Nodejs (@grpc/proto-loader). But this file contains a circular reference in messages Value,  Variant, List, Map, GenMap
```
 message Value {
  oneof Sum {
  
    Record record = 1;
  
    Variant variant = 2;
  
    string contract_id = 3;
  
    List list = 4;
    // etc...
 }
}
```

```
message Variant {
  Identifier variant_id = 1;

  string constructor = 2;

  Value value = 3;
}
```

```
message List {
  repeated Value elements = 1;
}
```
As you see **Value** refers to **Variant**, but **Variant** refers to **Value** etc.

So I get _Error: no such Type or Enum 'Variant' in Type .Value_ 
I see that all versions of value.proto have the same circular reference. Is this implementation correct?

**Comment by stefanobaghino-da** [comment]
The definition is correct and works using the gRPC codegen. In particular, I was personally able to use this in the past to create the (now discontinued) [Node.js bindings for Daml](https://github.com/digital-asset/daml-js). While those bindings have been discontinued and are no longer supported by Digital Asset, you can probably use them as a basis to better understand how to use Node.js to build an off-ledger service against the Daml ledger.

If you want to keep using @grpc/proto-loader, I don't know the software well enough to guide you with regards to how to use it in particular.
