### ISSUE TITLE
Add or document livelihood/readiness endpoints for the OAuth 2.0 Auth Middleware

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#14649]
### What is the problem you want to solve?

I would like to be able to use widely used tools (e.g. Kubernetes) to manage OAuth 2.0 Auth Middleware instances so that I can effectively achieve high availability of the service on my deployment.

### What is the solution you would propose?

Add a `/readyz` and `/livez` endpoint like the HTTP JSON API Service and the Trigger Service (see https://github.com/digital-asset/daml/issues/13819).

### Describe alternatives you've considered

Using another endpoint to check for the livelihood of the service, but I'm not sure about which one could be used to this end. If the problem can be solved that way, I'd find it satisfactory to document this.

**Comment by hrischuk-da** [comment]
Also, the port that the endpoint is on should be configurable so that I can combine several processes into the same Docker container but still expose each livez endpoint.

**Comment by ray-roestenburg-da** [comment]
@hrischuk-da the auth middleware service port is configurable.
