### ISSUE TITLE
[Intro] Error when running `daml start` in `intro7`

### ISSUE THREAD

**Issue by cgrigis-da** [digital-asset/daml#14654]
# Affected Daml version

SDK versions:
  2.3.2  (project SDK version from daml.yaml)

# Bug description

When running `daml start` in `intro7`, as [instructed by the doc](https://docs.daml.com/daml/intro/9_Dependencies.html#hashes-and-identifiers), the following error is displayed:
```
$ daml start

2022-08-09 09:27:52.13 [INFO]  [build] 
Compiling intro7 to a DAR.

2022-08-09 09:27:52.89 [INFO]  [build] 
Created .daml/dist/intro7-1.0.0.dar
Waiting for canton sandbox to start.
Error: Unknown option --wall-clock-time
Canton v2.3.2
Usage: canton [daemon|run|generate] [options] <args>...
(...)
```

# To reproduce

1. Simply follow the instructions in the doc

# Expected behavior

The Daml sandbox starts.

# Additional context

A workaround is to comment out `--wall-clock-time` in `daml.yaml`.

**Comment by githubarooski** [comment]
FYI this bug impacts all of the intro templates, not just intro7. Do you want a new issue opened?
