### ISSUE TITLE
Log how long every ledger API call takes in the JSON-API

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#14673]
Similar to how DB calls are logged, log the time it takes to call the ledger in a similar format for a first glance when performance issues arise.

**Comment by chunlokling-da** [comment]
The JSON API is already logging time elapsed for all endpoints at TRACE level:
https://github.com/digital-asset/daml/blob/04c37349fc33d3b66ef9528c52a0c66fc246f62f/ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala#L243

Here is a logging example in my local setup with logging level = TRACE
```
15-08-2022 10:18:56.328 [http-json-ledger-api-akka.actor.default-dispatcher-12] TRACE com.daml.http.Endpoints - Processed request after 1006092917ns, context: {instance_uuid: "2bb325e1-9c06-4564-8ebf-08710f4b9cc2", request_id: "8e343856-76d7-4bb0-8147-6b1d3477216f"}
```

@ray-roestenburg-da Can you advise if it is enough for what you were hopping for? May be I can add more info (e.g. API path) to the logging?

**Comment by chunlokling-da** [comment]
There are also many timers defined. I am looking into where are these metric published 🤔

**Comment by ray-roestenburg-da** [comment]
This ticket is to specifically record how long ledger API calls take, not how long the JSON-API takes to process a request.

**Comment by chunlokling-da** [comment]
> Similar to how DB calls are logged, log the time it takes to call the ledger in a similar format 

I have created a draft PR for the change. https://github.com/digital-asset/daml/pull/14711
Can you point me to those DB logs? or some example. I will try to follow it. :+1:

**Comment by ray-roestenburg-da** [comment]
You don't have to follow the same format as the DB logs, but this is an example:
```
Successful Statement Execution:

        SELECT party, last_offset FROM ledger_offset WHERE tpid = ? AND
      party IN (?) 

 arguments = [redacted, redacted]
   elapsed = 1 ms exec + 0 ms processing (1 ms total)
```

**Comment by S11001001** [comment]
> This ticket is to specifically log how long ledger API calls take, not how long the JSON-API takes to process a request. Logging should happen on DEBUG level.

@ray-roestenburg-da I might have missed something here, but why not introduce new metrics for this rather than logging? Typically we "log" timing by metrics. Is this intended for some use case that makes metrics un-useful or otherwise inappropriate?

**Comment by ray-roestenburg-da** [comment]
Customers will often just send us logs initially, so it is convenient to have this information there. It would be good to also add  this as a metric.

**Comment by stefanobaghino-da** [comment]
While this ticket is a useful stop-gap measure, I believe that going deeper with metrics doesn't belong here. Metrics provide aggregations over units of time, not individual cases. I don't think that a service should measure a dependency with metrics. The time it takes for the Ledger API to fulfill a call to be should be measured by the Ledger API. If you are interested in the correlation between individual calls, the right tool to use are distributed traces, which are already supported by the Ledger API. I would recommend giving a look at https://github.com/digital-asset/daml/issues/12798 at your earliest convenience.

**Comment by ray-roestenburg-da** [comment]
I was not proposing to add metrics in this ticket.

**Comment by ray-roestenburg-da** [comment]
A call to a service is not the same metric as a service it's own processing time. From that perspective it makes sense to record a metric on how long a call takes. tracing would then allow you to understand the difference.

**Comment by stefanobaghino-da** [comment]
> I was not proposing to add metrics in this ticket.

That was understood, but thanks for clarifying.

> A call to a service is not the same metric as a service it's own processing time. From that perspective it makes sense to record a metric on how long a call takes. tracing would then allow you to understand the difference.

Metrics aggregate over units of time, tracing allow to drill down on individual cases. You can use them in conjunction only if you're interested in aggregates, not in diagnosing specific calls. By using an individual trace ID you already have the full extent of necessary information without adding metrics. I'm not sure of what additional information you are looking for by adding metrics for an external call once you have distributed tracing in place.
