### ISSUE TITLE
Documentation rendering issues

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#147]
# Headings after code blocks
```rst
.. code-block:

  foo

Some Heading
===========
```
This rst code results in the top-spacing of the heading overlapping into the code block:
![image](https://user-images.githubusercontent.com/29121423/55157242-40f2b600-515c-11e9-9130-132d50c67811.png)

# Links to Anchors show the anchor underneath the search bar
When clicking a link to a heading (e.g. within the same page), the page scrolls to the right location, but the heading is show under the search bar.
![image](https://user-images.githubusercontent.com/29121423/55157406-9202aa00-515c-11e9-91b5-031418976dd4.png)

Scrolling down a bit reveals the heading:
![image](https://user-images.githubusercontent.com/29121423/55157435-a21a8980-515c-11e9-8137-f426882317b3.png)

# Linespacing in code blocks
Generally I would say that the linespacing in code blocks is unusual and more 
![image](https://user-images.githubusercontent.com/29121423/55157599-1c4b0e00-515d-11e9-8a67-703e34fa3d97.png)

Here is the same block with the css attribute `line-height: 100%`:
![image](https://user-images.githubusercontent.com/29121423/55157640-38e74600-515d-11e9-90ad-831cc9c3b5b4.png)

**Comment by georg-da** [comment]
Adding to this issue: when I click on a search result, the search results don't close even if I click outside. The only way to get them to close is to delete the search term. Gets annoying quite quickly.

**Comment by stefanobaghino-da** [comment]
The style has changed multiple times since this ticket was opened. Closing.
