### ISSUE TITLE
Add interface_id in Ledger API Exercise Command

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#14747]
In case of exercise-interface, we abuse the field `templateId` of the Exercise Command to be actually an `interfaceId`. 

We will add a new file `interface_Id` to the exercise command 

```
// Exercise a choice on an existing contract.
message ExerciseCommand {
  // The template or the interface where the choice is defined.
  // One and only one of template_id interface_id is required.
  Identifier template_id = 1;
  Identifier interface_id = 5;

  // The ID of the contract the client wants to exercise upon.
  // Must be a valid LedgerString (as described in ``value.proto``).
  // Required
  string contract_id = 2;

  // The name of the choice the client wants to exercise.
  // Must be a valid NameString (as described in ``value.proto``)
  // Required
  string choice = 3;

  // The argument for this choice.
  // Required
  Value choice_argument = 4;
}
```

**Comment by S11001001** [comment]
Will using `templateId` to specify interface ID still be supported?

**Comment by remyhaemmerle-da** [comment]
> Will using templateId to specify interface ID still be supported?

**Comment by S11001001** [comment]
> it will not be possible to abuse the templateId to specify interface ID.

Then, maybe this should be added to exercise-by-key and create-and-exercise first? At least for those commands, it lets you express something that is impossible, currently. This will just cause regressions in clients like JSON API.

The current behavior doesn't seem like "abuse" at all. It is really just a case of a field that is now misnamed; rename it `contract_type_id` and suddenly it isn't "abuse".

**Comment by remyhaemmerle-da** [comment]
There is two main reasons that have lead to the current decision: 
- using a field name called `template_id` to specify an `interface_id` is very confusion. Renamed the field could have been an option, but @mziolekda and @cocreature demised it as it is breaking (not at binary level, but at the code level). We want to minimize breakage in clients' clients. 
- we want to let us room to smooth improve. Adding the field to `exercise-by-key` and `create-and-exercise` are example of such natural improvements.

For a bit more of background, we cut as much as possible in the set of features for the first iteration of interface, in order to meet the deadline of delivery. We judge with product that supporting interface for `exercise-by-key` and `create-and-exercise` was not essential. If we have time before the cut off for the next SDK  (quite unlikely), we could try to add the field to `create-and-exercise` command.  For  `exercise-by-key` we should add it first to the surface language, this will definitively not happen before the next deadline.

**Comment by S11001001** [comment]
> using a field name called template_id to specify an interface_id is very confusion.

There's a smaller change to deal with the naming problem without breaking how commands are built in current codegen and JSON API.

1. add a `contract_type_id` to `ExerciseCommand`, or whatever you care to call the union of template IDs and interface IDs (I have generally called it "contract type ID" but have not seen any other opinions on this)
2. give it exactly the same semantics as `template_id` does now; command resolves to `contract_type_id` _or_ `template_id`, preferring the former
3. deprecate `template_id`

**Comment by cocreature** [comment]
What’s the issue in codegens & the JSON API? Both of them are very much type aware so why can they not set the right field?

**Comment by S11001001** [comment]
> What’s the issue in codegens & the JSON API? Both of them are very much type aware so why can they not set the right field?

JSON API is _only now_ developing this type-awareness. Even with resolution fixed to provide this information, I still think there are cases where we trust input IDs as template IDs; the checks to prevent this aren't ready yet.

The codegens generally throw it away pretty early, because it was only useful in the by-key and create-and cases, where we can discriminate by the fact that we're carrying a separate definitely-template-ID.

**Comment by remyhaemmerle-da** [comment]
We will keep using `templateId` for both template and interface id.
