### ISSUE TITLE
Resolve node security vulnerabilities for DAML repo

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#1479]
![image](https://user-images.githubusercontent.com/25179017/58713567-d561da80-8390-11e9-9a4d-ec4b1d73a2eb.png)

![image](https://user-images.githubusercontent.com/25179017/58713510-b8c5a280-8390-11e9-9824-51d8b86e0f2a.png)

![image](https://user-images.githubusercontent.com/25179017/58713537-c2e7a100-8390-11e9-97f3-46bdb3bb82fd.png)

**Comment by cocreature** [comment]
should be resolved now
