### ISSUE TITLE
TransactionService.GetTransactions doesn't stay alive

### ISSUE THREAD

**Issue by socproof** [digital-asset/daml#14810]
https://github.com/digital-asset/daml/blob/d8874a3ae2601e3bf38802b0a7a6fcdcb2f160a2/ledger-api/grpc-definitions/com/daml/ledger/api/v1/transaction_service.proto#L29

I have tried using this method both in Go and NodeJS scripts, and nowhere does this method work as a stream. That is, if I subscribe to listen to data, then after receiving all the data, the method immediately shuts down and does not respond to the appearance of new transactions to the Ledger. So I have to call this method again to get a new transaction.
For comparison CommandCompletionService.CompletionStream works as expected, - that is the service listens and returns new events

**Comment by stefanobaghino-da** [comment]
`GetTransactions` returns a stream of responses and you should be able to listen to it. How are you setting up your request? If you provide a specific end offset you will not listen beyond that, you need to leave that field not set in your request using gRPC.

**Comment by socproof** [comment]
Yes, that works. Thank you. I thought this field is mandatory.

**Comment by stefanobaghino-da** [comment]
Thanks. In general, you can rely on the Ledger API reference documentation to identify whether a field is required in a request, as in this example for `GetTransactionRequest`.

https://github.com/digital-asset/daml/blob/31cc435331bd668ab79d53d7d1965a8ecfcdba95/ledger-api/grpc-definitions/com/daml/ledger/api/v1/transaction_service.proto#L98-L101
