### ISSUE TITLE
test that retro implements work like forward implements in JSON API

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14821]

**Comment by chunlokling-da** [comment]
I have manually tested it by running `daml start` on a daml project which contains daml model of retroactive implements.
I examine the state of PackageService with debug log to ensure retroactive-implements is correctly resolved.

**Comment by chunlokling-da** [comment]
I have manually tested it by running daml start on a daml project which contains daml model of retroactive implements.
I examine the state of PackageService with debug log to ensure retroactive-implements is correctly resolved.

The reference to the template in the DefInterface is removed (DefInterface.retroImplements)
A reference to the interface is added to the DefTemplate (DefTemplate.implementedInterfaces)

**Comment by S11001001** [comment]
I would suggest

1. adding a new module in `http-json/src/it/daml` that adds an interface and retroactive implementation to the `CIou` template that is already there,
2. list this module in the `daml_compile` for `CIou` in `BUILD.bazel`, and
3. extend `HttpServiceIntegrationTest` with a test that invokes that choice _by template ID_ and checks the return value as demonstrated in other choices in that file.

**Comment by chunlokling-da** [comment]
PR created https://github.com/digital-asset/daml/pull/14874
