### ISSUE TITLE
Compiler Support for LF 1.15

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#14833]
- [x] Distinguish guarded exercise : https://github.com/digital-asset/daml/pull/14773
- [x] merge

- [x] Re-enable tests disabled in https://github.com/digital-asset/daml/pull/14770 : https://github.com/digital-asset/daml/pull/14836
- [x] Make those tests work & merge

- [x] Delete 1.dev protobuf changes from 1.15 protobuf : https://github.com/digital-asset/daml/pull/14799
- [x] Merge

- [x] Add InterfaceSubscriptionsIT to 1.15 test suite : https://github.com/digital-asset/daml/pull/14836
- [x] Make test work & merge

**Comment by stefanobaghino-da** [comment]
@dylant-da All items seem to be closed here, can this ticket be closed?

**Comment by dylant-da** [comment]
We are doing gardening now to improve error messages and clear out some TODOs but yes, the compiler supports LF 15 - closing now.
