### ISSUE TITLE
Ledger API Identifier improvements

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#1484]
We should either document how to check `com.digitalasset.ledger.api.v1.value.Identifier` equality or just remove the deprecated `name` field from the definition:
```
// Unique identifier of an entity.
message Identifier {

  // The identifier of the DAML package that contains the entity.
  // Required
  string package_id = 1;

  // The identifier of the entity (unique within the package)
  // DEPRECATED: use ``module_name`` and ``entity_name`` instead
  // Optional
  string name = 2 [deprecated=true];

  // The dot-separated module name of the identifier.
  // Required
  string module_name = 3;

  // The dot-separated name of the entity (e.g. record, template, ...) within the module.
  // Required
  string entity_name = 4;
}
```
`value.proto` spec does not say if Ledger API returns `Identifier` with deprecated `name` field set to <module_name>:<entity_name> or just leaves it empty. The problem with the deprecated `name` field is that it affects the automatically generated `equals` and `hashCode` methods. We technically do NOT have a reliable way to checking `Identifier` equality.

**Comment by gerolf-da** [comment]
You shouldn't use the `Identifier` type generated with scalapb for anything other than converting it into a "domain object". Protobuf is a transport protocol, and as such you need to verify that what you received on the wire makes sense for your domain.

**Comment by leo-da** [comment]
@gerolf-da 
but we actually do use `Identifier` and generated classes in the business logic... and our reference apps and examples also do.
We need to document best practices and update all reference apps and examples.

**Comment by gerolf-da** [comment]
The deprecated identifier has been removed by #2211.
