### ISSUE TITLE
rename api-type-signature Maven artifact and remove deprecated symbols

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14859]
Final cleanup after #13669:

* [x] wait for 2.4.0 to branch off
* [x] rename the Maven artifact from daml-lf-interface to daml-lf-api-type-signature
* [x] remove the symbols deprecated in #14856 and the `@deprecatedName`s (api-type-signature is not officially supported, so 1 year period does not apply)

**Comment by chunlokling-da** [comment]
picked it up but 2.4.0  is not yet release so unassign myself
