### ISSUE TITLE
Return both ledger effective time and record time via API

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1494]
We currently only have a field for ledger effective time on transactions, but return record time on it: https://github.com/digital-asset/daml/blob/9f21b6c669c44c859b736fd87832895047e8ca5b/ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/server/services/transaction/TransactionConversion.scala#L52

We should return both and do so correctly.

**Comment by gerolf-da** [comment]
Fixed by #4763.
