### ISSUE TITLE
Enforce that ledger effective time follows causality

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1495]
The interpreter should enforce that I can never have a create of `cid` in `tx` with ledger effective time `t1` and an exercise on `cid` in `tx2` with ledger effective time `t2 < t1`.

Scenario service and Canton already enforce this, but we should make sure it's enforced on all X by checking this in the interpreter. May already be the case, but I couldn't confirm as much.

**Comment by rautenrieth-da** [comment]
This is fixed by the new ledger time model.

The ledger effective time is assigned by the submission service, using an algorithm that guarantees causal monotonicity by construction.
