### ISSUE TITLE
Packageid -> Prefix collision check in java codegen

### ISSUE THREAD

**Issue by chunlokling-da** [digital-asset/daml#14976]
Problem

From #11457 ,

> There is actually also another bug in here: We don’t detect collisions in the DAR prefix in

It is found that there is no check on cases where more than 1 prefix is defined for a package.
When there is more than 1 prefix defined for a package, the behavior now is only one prefix will be used for generating java classes for that package.

Solution:

Instead of implementing a collision check, we have decided to ~generate code with all prefixes configured if more than one is found for a package.~  apply prefix on packages following[ the rule described here](https://github.com/digital-asset/daml/issues/14976#issuecomment-1315810177)

**Comment by chunlokling-da** [comment]
Consider the below reproducer:

```
daml new foobar && cd foobar && daml build
daml new foobar2 && cd foobar2 && daml build
bazel run //language-support/codegen-main -- java ~/foobar/.daml/dist/foobar-0.0.1.dar=aa ~/foobar2/.daml/dist/foobar2-0.0.1.dar=bb --output-directory ~/tmp
```
foobar and foobar2 both have the same daml code. (Template Asset).
We should be able to run code gen to configure the prefix `aa` to `foobar` and prefix `bb` to `foobar2`

However, with the Packageid -> Prefix collision check, we will get this error:
```
Error generating code: Ambiguous prefixes (bb, aa) configured on package id d14e08374fc7197d6a0de468c968ae8ba3aadbf9315476fd39071831f5923662.
```
We have this error because foobar and foobar2 both contain a common package (common dependency) d14e08374fc7197d6a0de468c968ae8ba3aadbf9315476fd39071831f5923662 which is the `daml-stdlib-DA-Internal-Template-d14e08374fc7197d6a0de468c968ae8ba3aadbf9315476fd39071831f5923662`

I am thinking we should not apply prefix to these common dependency and also not to check prefix collision.

**Comment by chunlokling-da** [comment]
After team discussion. We have decided to generate code per configurated package prefix. This collision check will no longer make sense. Going to close this one and create another issue for per configurated package prefix

**Comment by chunlokling-da** [comment]
We have another discussion after @S11001001 has reviewed the PR. We have decided to throw away the per-prefix code generation. Instead, we will have the following rules on dar file prefix for more compatible change:

During  java code generation, for each dar file that is configured with a prefix, the prefix will only apply to the packages in that dar file that satisfy the followings:

1. It is the main package from the dar file
2. The package only appear in this dar file but not in other dar file used for the code generation

Here is an example which @S11001001 suggested in his comment:

Consider 2 dar files A.dar and B.dar,  where B.dar was built from a project that depending on A.dar with "data-dependency"

A.dar contains these packages: A.dalf (main), X.dalf(non unique)
B.dar contains these packages: B.dalf(main), A.dalf(non unique), X.dalf(non unique)

if we configure prefix "pa" to A.dar and "pb" to B.dar

we will get these prefixes applied to packages: 
A.dar : A.dalf (pa)
B.dar : B.dalf(pb)



@S11001001 , @ray-roestenburg-da  please comment if it is what we all expected.

**Comment by S11001001** [comment]
To be clear:

> satisfy **one of** the followings

**Comment by S11001001** [comment]
To demonstrate rule 2 in your example,

> A.dar contains these packages: A.dalf (main), X.dalf(non unique), **Y.dalf(unique)**

>  A.dar : A.dalf (pa), **Y.dalf (pa)**
