### ISSUE TITLE
Faster damlc compilation

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#15]
@raphael-speyer-da 

- faster compilation, with our big project it currently takes over a minute just to compile the daml and the code base will like grow quite a lot over the next year or so

Possible solutions:

* Expose a `-j` flag which is faster, but non-deterministic - which doesn't matter for active dev anyway.
* Use incremental caching with .hi files.
* Profile and optimise the process

**Comment by cocreature** [comment]
We’ve made it a fair bit faster and incremental computation is tracked in a separate issue. Closing this, let’s reopen issues for specific cases that are slower than they should be.
