### ISSUE TITLE
introduce a cache over the SQL ledger

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#1500]
The number of concurrent SQL queries/s are growing with active api connections. To address the problem we need to introduce a cache over ledger records.

**Comment by gaboraranyossy-da** [comment]
@bitonic this will be a problem pretty soon I think.

**Comment by gaboraranyossy-da** [comment]
tagging @gerolf-da too

**Comment by stefanobaghino-da** [comment]
No longer applicable and probably too broad, closing.
