### ISSUE TITLE
Daml start does not work due to invalid or corrupted canton jar

### ISSUE THREAD

**Issue by akapuscinski** [digital-asset/daml#15036]
# Affected Daml version

Tried many versions: 2.3.4, 2.3.2, 1.13.1

# Bug description

I can't run `daml start` due to following issue with canton.jar:

```
Created .daml\dist\nft-0.0.1.dar
Waiting for canton sandbox to start.
Error: Invalid or corrupt jarfile C:\Users\e-ankc\AppData\Roaming\daml\sdk\2.3.2\canton\canton.jar
Port file was not written to 'C:\Users\e-ankc\AppData\Local\Temp\extra-dir-417928992254\sandbox-portfile' before process exit with ExitFailure 1
```

I have tried to download `canton.jar` manually and replaced the one provided with SDK but without luck

# To reproduce

I was following [Introduction do DAML tutorial](https://daml.talentlms.com/dashboard), source code may be found here: <https://github.com/LeventeBarczyDA/private-nft>

java version 11 (also tried with 17 and 8)
```
openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)
```
daml sdk version 2.3.2

1. Clone git repository
2. cd to nft dir
3. run `daml start`

# Expected behavior

daml UI starts and may be accessed by a web browser

# Additional context

OS: Windows 10

I believe this bug is specific to my OS/machine however I'm stuck and don't know what to check next

Results of running `version` and `sandbox` commands:

```
daml version
SDK versions:
  1.13.1
  2.3.2
  2.3.4   (default SDK version for new projects)

daml sandbox
Starting Canton sandbox.
Error: Invalid or corrupt jarfile C:\Users\e-ankc\AppData\Roaming\daml\sdk\2.3.4\canton\canton.jar
Port file was not written to 'C:\Users\e-ankc\AppData\Local\Temp\extra-dir-121593244675\canton-portfile.json' before process exit with ExitFailure 1
```

**Comment by garyverhaegen-da** [comment]
Thanks; in the future, please add new information in new messages, rather than editing existing ones. It makes following what's going on a lot easier.

Could you now try
```
certutil -hashfile C:\Users\e-ankc\AppData\Roaming\daml\sdk\2.3.4\canton\canton.jar MD5
```

and report the result?

**Comment by garyverhaegen-da** [comment]
For reference, here's the result on my test machine:

```
C:\Users\u>certutil -hashfile C:\Users\u\AppData\Roaming\daml\sdk\2.3.4\canton\canton.jar MD5
MD5 hash of file C:\Users\u\AppData\Roaming\daml\sdk\2.3.4\canton\canton.jar:
478e2db553118e8656dc1e182dcb0f66
CertUtil: -hashfile command completed successfully.

C:\Users\u>
```

**Comment by akapuscinski** [comment]
It looks like the hashes are the same:
```
MD5 hash of C:\Users\e-ankc\AppData\Roaming\daml\sdk\2.3.4\canton\canton.jar:
478e2db553118e8656dc1e182dcb0f66
CertUtil: -hashfile command completed successfully.
```

**Comment by garyverhaegen-da** [comment]
This is weird.

If the file itself is not corrupt, then I can only think of two possibilities:

1. Your JVM installation is corrupt, which seems unlikely given that you tried multiple ones. (Note: we only test against 11, so the other ones _may_ not work. I'd expect that to be with some other Java exception though, not a "corrupt jar" message.)
2. The JVM somehow doesn't get proper read access to the jar file.

Is there anything specific to your setup that you could think of? I.e. any kind of security restriction, antivirus, corporate firewall, etc.?

**Comment by garyverhaegen-da** [comment]
Perhaps, to eliminate a possible issue with the `daml` command itself, you could try

```
java -jar C:\Users\u\AppData\Roaming\daml\sdk\2.3.4\canton\canton.jar -h
```

**Comment by garyverhaegen-da** [comment]
Hi @akapuscinski,

Did you manage to find the issue? If not, do you have any additional information you could share?

**Comment by garyverhaegen-da** [comment]
Closing for lack of response. Please reach out on [the forum](https://discuss.daml.com) if it happens again.
