### ISSUE TITLE
deprecate and remove fetchcontracts.domain.TemplateId

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#15040]
As noted here, this `TemplateId` is just an alias for `ContractTypeId`. Replace all usages with either `ContractTypeId` or `ContractTypeId.Template`, depending on what is meant, and delete the alias.

`TemplateId` is pervasive, so it is better to have a timeboxed PR that removes only some of the usages (keeping the aliases below) and can be merged quickly than to have a PR sit around for a week and almost certainly conflict.

https://github.com/digital-asset/daml/blob/32583edb7d3c69da77605730db83f034658b6338/ledger-service/fetch-contracts/src/main/scala/fetchcontracts/domain.scala#L33-L37

**Comment by chunlokling-da** [comment]
This issue depends on https://github.com/digital-asset/daml/issues/15098

**Comment by S11001001** [comment]
> This issue depends on #15098

@chunlokling-da #15098 is only about the "non-trivial" cases. For this issue, the idea is to

1. change each occurrence to `ContractTypeId`, `ContractTypeId.Template`, or `ContractTypeId.Interface`, depending on what the ID is supposed to represent
2. the cases that _should_ be changed to `ContractTypeId.Template` but it does not seem to be trivial to make this change, leave a `TODO #15098`
3. however, some cases _are_ trivial; they should just be changed for this issue when it is just as easy as leaving a TODO
4. then this one can be closed and the work in #15098 remains to clean up those TODOs

cc @ray-roestenburg-da

**Comment by chunlokling-da** [comment]
> change each occurrence to ContractTypeId, ContractTypeId.Template, or ContractTypeId.Interface, depending on what the ID is supposed to represent

when we say "ContractTypeId" which is a case can be either template or interface. We should better use `ContractTypeId.Resolved` if we are sure it is resolved at the point right?

**Comment by S11001001** [comment]
> We should better use `ContractTypeId.Resolved` if we are sure it is resolved at the point right?

Yes, and moreover, there is also `ContractTypeId.Template.Resolved`, which is where you are sure it is template _and_ it is resolved, and likewise for `Interface`.
