### ISSUE TITLE
in WS query stream, template IDs are not translated to interface IDs for archive events

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#15055]
Example block from the stream, for which `templateId` is the implementing template even though this is an interface query:

```js
[
        {
            "archived": {
                "contractId": "00bf7f99faacb2c8d609b7cc02189555325f9878fbcadc28ac19dfd04fd2fba2f4ca00122093fdada3b2c8e1c3c9135c20414fe31a9d270e66cbc83a426906399c33cb8e82",
                "templateId": "8e0e4f359d0f65be65883ff8bd047511f33b97b0ead9d6b47e10a681879e95f7:Daml.Finance.Holding.Fungible:Fungible"
            }
        },
        {
            "created": {
// snip
```

Just as we swap template IDs for interface IDs in `created` events, so must we do so for `archived` events.

* [x] rewrite "interface sub query endpoint" test to use the `Consume` language, so it can test archive events
* [x] add an exercise to the test
* [x] test that the archive events have the interface ID
* [x] add the template-ID-to-interface-ID mapping to archive events in websocket result stream

_Originally posted by @GeorgSchneider in https://github.com/digital-asset/daml/issues/15042#issuecomment-1251176163_

**Comment by chunlokling-da** [comment]
it is the "interface sub query endpoint": 
https://github.com/digital-asset/daml/blob/41dc32a016415a24f648a0d99bba2470055b4ec8/ledger-service/http-json/src/itlib/scala/http/AbstractWebsocketServiceIntegrationTest.scala#L262
