### ISSUE TITLE
Handling of FilePaths and URIs in damlc

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#1507]
We have had quite a few issues caused by various filepath handling issues so it is time to rethink how we handle things and try to come up with an approach that hopefully stops these issues from reappearing. (Note: Obviously tests help with that as well, I’ll try to get a working version of LSP-based tests running on all platforms on CI soon).

There are a few issues that we have encountered:

1. We must not leak absolute filepaths into DAML-LF.
2. On Windows, file paths are not normalized and we often end up with a mix of forward and backward slashes. Given that we use file paths as keys in various places it is crucial that we are consistent here.
3. Even if we ignore mixing up forward and backward slashes, a URI->FilePath->URI is inherently a lossy conversion as we lose the information on which characters have been percent-encoded.

1 already seems to be covered sufficiently well by our current approach of making paths relative to the project root outside of the IDE so I’m not too worried about that.

That leaves us with 2 and 3. I see two options for solving this:

1. Stick with file paths, normalize slashes and ensure that whenever we look at URIs we treat escaped and unescaped characters identical. This would also require patching haskell-lsp which currently uses the URIs that it gets in messages without any changes, e.g., as keys in the VFS.
2. Use URIs internally and avoid the roundtrip completely. This would allow us to work with the URIs we get in LSP messages directly. We also don’t have to worry about forward vs backward slashes here since file URIs always use forward slashes. However, we could still end up with some inconsistencies if we have to produce our own file paths, e.g., during module chasing. If we go for this approach I would suggest to not use the full URI but only use the URI path so we can avoid having to check everywhere if we are actually working with `file:` URIs.

I am slightly leaning towards 2 since a) it does not require patching haskell-lsp (if we can get it upstream that’s fine but I’d very much like to not having to maintain patches for that) and b) I am slightly worried that finding all spots can be quite difficult. On the other hands the potential inconsistencies here also worry me.

Thoughts @neil-da, @associahedron, @majcherm-da?

**Comment by associahedron** [comment]
I like option 2 because filepaths are much more platform-dependent and it doesn't make much sense to be converting back and forth between filepaths and URIs all the time.

Does this mean we'll work with URI paths relative to the project root in the compiler?

**Comment by cocreature** [comment]
I wouldn’t change relative vs absolute file paths here. So for things like `damlc build` we will be working with relative paths while for `damlc ide` we will be working with whatever we get from the LSP server which is absolute. While URIs can’t contain relative paths (see https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files), I would use the URI path internally so all that would mean is that we have to use forward slashes in `damlc build` for relative paths. Also, we already do use relative paths in URI (despite that being wrong :slightly_smiling_face:) for things like the `DiagnosticsStore` which is coming from `haskell-lsp` and is indexed by URIs. While not being valid URIs haskell-lsp just treats them as opaque text so that is not an issue.

We could consider switching back to absolute paths everywhere and try to relativize in the conversion to DAML-LF but even if we decide to do that, it would mostly be an orthogonal change that we can tackle separately (and I’m not sure it is something worth doing).

**Comment by associahedron** [comment]
Well ... relative paths (of URIs) are _a thing_ in HTML land (e.g. `<a href="index.html">`, so I can't see them being really wrong.

**Comment by cocreature** [comment]
Right but `file:`-URIs cannot be relative. They always start with a `/`.

**Comment by associahedron** [comment]
This was a miscommunication -- I never meant "URIs" of the form `file:relativePath`, only relative paths of URIs, e.g. 'daml/Main.daml' as a "URI-relative" path, relative to a project root URI e.g. 'file:/path/to/my/project`. It sounds like we agree on this point. (The `DiagnosticsStore` thing is weird and wrong though, but probably not worth "fixing" unless it causes problems.)

**Comment by associahedron** [comment]
(Or to put it in Haskell documentation terms ... absolute URIs like `file://` are a left module of the URI-relative path monoid, which is what we should use in code like `damlc build` to prevent contamination of absolute paths in DAML-LF.)

**Comment by majcherm-da** [comment]
We could also consider a more strict type for file paths than `FilePath` String synonim, maybe just a wrapper for it, which could ensure paths are normalised on pack/unpack and not use `FilePath`/`String` anymore.

**Comment by cocreature** [comment]
Yeah I definitely want to have a newtype for this but we need to decide on what we put in the newtype :slightly_smiling_face:

**Comment by neil-da** [comment]
I'm inclined to say use URI everywhere, in both build and ide. Then, when translating to GHC parser (which is where we have to be relative), we relitavise the paths explicitly and in a very specific place. I'm not keen on having build and ide diverge too far, since that consistency has been helpful.

**Comment by neil-da** [comment]
And make all those URI's fully absolute everywhere.

**Comment by cocreature** [comment]
I think I agree about going with 2 (although I would go with the URI path instead of the full URI, otherwise you end up with partial conversions that check whether it’s a `file:` URI everywhere) but I am still a bit worried about the issue mentioned before, let me give a concrete example:

1. The IDE asks us to open `A.daml` using some URI, `A.daml` imports some other file `Foobar.daml`.
2. This requires us to create a URI for `Foobar.daml` and send it to the client.
3. Now the user opens `Foobar.daml` in the IDE. This means we will get a URI for `Foobar.daml` from the IDE. If that URI does not match what we have produced ourselves before, we now have two different URIs for the same file which is guaranteed to result in problems.

Now if we are careful to construct the URI for `Foobar.daml` based on the URI of `A.daml` rather than creating it by some `filePathToUri` function that takes the absolute path of `Foobar.daml`, this is probably reasonably safe but at least technically even for a file path as simple as `Foobar.daml`, the client would be free to percent-encode the characters and there is no chance for us to guess in advance what it will do here. If you have a file path with some special characters that gets more likely.

Going with 2 still seems like the better option and I would expect that this issue is probably not particularly common but it definitely makes me feel a bit uncomfortable.

As for absolute paths, I think enforcing absolute paths everywhere is probably a good idea but I would do it as a second step.

**Comment by neil-da** [comment]
Would absolute paths plus a canonical encoding (e.g. no percent escaping) not solve the problem pretty robustly? You still have symlinks, but to my mind those are different files, so as long as you don't chase through them, we should be fine.

**Comment by cocreature** [comment]
Applying a canonical encoding has pretty much the same issues as roundtripping via filepaths (once you have a canonical encoding, you can roundtrip from canonical URI -> FilePath -> canonical URI): It breaks as soon as anything relies on the original URI. 

Currently, this is definitely the case for `haskell-lsp`: The VFS uses the URI send by the client without any normalization. This recently broke Windows because VSCode percent-encodes colons while we didn’t. So if we want to go this route, we have to patch `haskell-lsp`. I expect that we should be able to upstream those changes so the maintenance costs are not too high but I am somewhat worried that finding all the places that need to be modified could turn out to be rather tricky.

And even if we make sure that all of our code including dependencies like `haskell-lsp` always uses the normalized URIs, we still have the issue that LSP clients might not handle it well, if e.g. the diagnostics are sent for a URI with a different encoding than the client send when they opened the file. This is arguably a bug in the client but given that those are outside of our control (and we need to support more than VSCode when working as a Haskell IDE), this might not be an easy fix.

**Comment by cocreature** [comment]
We decided on the following plan which I am going to implement it:

1. Patch haskell-lsp (and try to upstream the patches) to use normalized URIs as keys. This fixes the issues due to different percent encodings.
2. Introduce a newtype in our codebase that represents normalised filepaths. This avoids issues due to different uses of `/` `\`.
