### ISSUE TITLE
Remove deprecated fromValue methods

### ISSUE THREAD

**Issue by chunlokling-da** [digital-asset/daml#15120]
Since Daml 2.5.0 #14313, the `fromValue` methods in Java codegen output are deprecated, with Javadoc explaining to use valueDecoder method instead. After the deprecation cycle is complete, delete the code that generates those methods in  `EnumClass.scala`, `FromValueGenerator.scala`, `VariantCases`, `VariantConstructorCases` and `VariantRecordMethods`  (just search for `Deprecated` or this issue #).

Also delete in static method `fromFunction` in interface ValueDecoder 

* [ ] 1st Nov 2023 ? (1 year after 2.5.0)
* [ ] >=Daml 3.0.0

**Comment by stefanobaghino-da** [comment]
Are the deprecated methods already marked as such in the generated code?

**Comment by chunlokling-da** [comment]
Yes the [PR](https://github.com/digital-asset/daml/pull/15017) is merged so they are marked deprecated in `main` branch. ie, if we now run the codegen with the build from `main` branch, the fromValue methods in the generated java code are marked deprecated.

**Comment by stefanobaghino-da** [comment]
OK, thanks!
