### ISSUE TITLE
Accessor field disambiguation

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/daml#15141]
Possibly related to #8918?

In the simple example here:

https://github.com/lucianojoublanc-da/fieldbug/blob/4d2bb85db1d3ab183a504d7c419ca87433291364/daml/Main.daml#L25

We get a disambiguation error. 

<pre>Compiling fieldbug to a DAR.
File:     daml/Main.daml
Hidden:   no
Range:    25:20-25:25
Source:   typecheck
Severity: DsError
Message: 
  <font color="#CB4B16">daml/Main.daml:25:20: error:</font>
<font color="#CB4B16">  Ambiguous occurrence ‘party’</font>
<font color="#CB4B16">  It could refer to</font>
<font color="#CB4B16">  either the field ‘party’, defined at daml/Main.daml:9:21</font>
<font color="#CB4B16">  or the field ‘party’, defined at daml/Main.daml:7:21</font>
ERROR: Creation of DAR file failed.
</pre>

Adding the function signature like so:

https://github.com/lucianojoublanc-da/fieldbug/blob/b44e25170d80ff19d82431ddca1e73db177a4fba/daml/Main.daml#L25

Fixes the problem.

Is this expected? Shouldn't the compile be able to determine which function we are referring to based on it's arguments?

# Affected Daml version

2.4.0-snapshot.20220905.10544.0.a2ea3ce6

# Bug description

Disambiguation errors where the compiler should be able to determine which field accessor we are referring to based on the argument.

# To reproduce

Se linked example repo above

**Comment by cocreature** [comment]
That’s expected. You get nice overloading if you use (Foo newOwner).party but the non-dot based accessor do the weird Haskell field name overloading which is not type class based and needs a lot more type annotations.

**Comment by lucianojoublanc-da** [comment]
Yeah what I really wanted to do here is have a list of `Foo`s and be able to do `fieldName <$> foos` to project a list of fields. I have to write `(\x -> x.fieldName) <$> foo` instead.
