### ISSUE TITLE
Navigator marks contract as archived when the contract is actually active

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#1519]
A user reported an issue in the public slack channel:
> Possible bug in Navigator? In some cases I can see that the Navigator marks contracts as archived when the contract is actually active, is shown active by the scenario test, and I can actually exercise choice on  it. Has anybody else seen this?

~https://damldriven.slack.com/archives/C94RD7677/p1559670572017100~

**Comment by leo-da** [comment]
cc @rautenrieth-da

**Comment by stefanobaghino-da** [comment]
Broken link and not enough information to reproduce, closing.
