### ISSUE TITLE
Group security evidence by components

### ISSUE THREAD

**Issue by cbley-da** [digital-asset/daml#15222]
Grouping the components for which the evidence of testing is presented (i.e. it should be clear whether the test is about the Daml Engine, or the HTTP JSON API Service, or whatever else).

## Relevant components

1. HTTP JSON API service
2. trigger service
3. OAuth2.0 auth middleware

Part of https://github.com/digital-asset/daml/issues/14254

**Comment by stefanobaghino-da** [comment]
So, the problem we had before was that the old file used by the language team was grouping the results by category in a hierarchical fashion.

If you migrated to the Scala annotations instead and you produce a single CSV file as part of every release (which is something that should already be part -- see `test-evidence-2.4.2.zip` [here](https://github.com/digital-asset/daml/releases/tag/v2.4.2) for an example) and each test evidence item contains the category and the component, that would satisfy the requirement without any additional generated file.

**Comment by cbley-da** [comment]
OK, is it sufficient if the information is part of an existing field / column or should it be in its own?
