### ISSUE TITLE
Provide a CSV file for the security evidence of runtime components

### ISSUE THREAD

**Issue by cbley-da** [digital-asset/daml#15223]
Make the information available together with the one provided by the Canton and Ledgers team as a CSV file bundled with every release, to which the documentation points

Currently, the `TEST_EVIDENCE` annotations are processed to generate the `security-evidence.md` file.

Either adapt the generator to (additionally) output a CSV file or move to scalatest style annotations (lib-scala/test-evidence).

Part of #14254

**Comment by cbley-da** [comment]
While converting `TEST_EVIDENCE` annotations, I discovered that sometimes (e.g. in `daml-lf/engine/src/test/scala/com/digitalasset/daml/lf/engine/ApiCommandPreprocessorSpec.scala`) these annotations are simply attached to an arbitrary statement (like ` val validExeInterface = ApiCommand.Exercise(...)`).

This makes test-evidence SecurityTest entries not directly suitable since these are based on tagging scalatest tests. I need to have a deeper look to figure out how to move forward.

**Comment by stefanobaghino-da** [comment]
Cases like those use table-driven property checks. I would check with @mziolekda and his team if they support it in some way. If they don't, you might want to inquire as whether table-driven property checks can be used for evidencing security testing at all: apart from creating the test data, you also need to verify that it's used as part of your tests. Ultimately, it might be simpler (although admittedly more verbose) to re-frame those table-driven property checks as normal tests (but @remyhaemmerle-da please do let me know if you have substantial reasons to press against this approach).

Are you doing the thread modeling already? That document could end up making you realize that certain annotations could simply be dropped (or need to be replaced by others).

**Comment by stefanobaghino-da** [comment]
(and thanks for flagging this, very wise to inquire as to how to move forward) 🙇🏻‍♂️

**Comment by remyhaemmerle-da** [comment]
>  annotations are simply attached to an arbitrary statement (like val validExeInterface = ApiCommand.Exercise(...)).

In fat they are attached to several statements, 
For instance the following annotation is attache to the following 4 statements.
```
    // TEST_EVIDENCE: Integrity: ill-formed exercise-by-key API command is rejected
        validExeByKey.copy(templateId = "Mod:Undefined") ->
          a[Error.Preprocessing.Lookup],
        validExeByKey.copy(contractKey = ValueList(FrontStack(ValueInt64(42)))) ->
          a[Error.Preprocessing.TypeMismatch],
        validExeByKey.copy(choiceId = "Undefined") ->
          a[Error.Preprocessing.Lookup],
        validExeByKey.copy(argument = ValueRecord("", ImmArray("content" -> ValueInt64(42)))) ->
          a[Error.Preprocessing.TypeMismatch],
```

**Comment by remyhaemmerle-da** [comment]
@stefanobaghino-da I am not very queen on defactorizing, my test in order to improve generation of test evidence documentation. 
Repetition make easy introduction of bugs when we need to change something and make review a very tiring task. 

In this case, we can simply factorize all the test evidence in a single one, with something like : 
 ```
    // TEST_EVIDENCE: Integrity: ill-formed API command is rejected
```

**Comment by stefanobaghino-da** [comment]
The idea is that of moving away from the framework built around the `TEST_EVIDENCE` tag to make it easier to integrate the security evidence artifacts with the ones provided as CSV by other teams. As such, the tag cannot be put freely in the source code but needs to annotate a specific ScalaTest test case, which is what creates the problem. As such, I would recommend to do one of the following:

1. if sensible within the framework of the threat modeling (which provides the framework within which a test should be annotated or not, and how -- and should hence be done before any other work), slim down the annotations into one that covers them all and can go on the test case itself
1. alternatively, if feasible and not exceedingly complex and time-consuming, extend the security evidencing annotations to make sure it can be used to validate that a specific test has been run with a specific row of table-drive property based checks
1. if necessary and within the boundaries of the threat modeling, break up tests where needed and annotate them individually while balancing this act without introducing unnecessary repetition

As mentioned, any action should more or less derive from the threat modeling document for the component under test. Please note that components like the Daml engine and interpreter are under the responsibility of the Daml-LF team and @remyhaemmerle-da will work together with @soren-da to move forward with those.

@cbley-da As part of the scope that we aim to address before the end of the year are only the Ledger Clients components, which means the OAuth 2.0 Auth Middleware, the Java bindings, the HTTP JSON API service, the TypeScript bindings, the React.js bindings, and the Trigger Service (but not the Trigger Runner).
