### ISSUE TITLE
Document threat model for each runtime component

### ISSUE THREAD

**Issue by cbley-da** [digital-asset/daml#15224]
Provide a document for each component that establishes the threat model under which the security evidencing is conducted

* HTTP JSON API Service
* Trigger Service
* OAuth 2.0 Auth Middleware

Part of #14254

**Comment by cbley-da** [comment]
@stefanobaghino-da just to clarify, is the expected output a readable document that should be generated from the CSV / JSON file here, or is the CSV / JSON sufficient on its own? Asking since the examples provided were spreadsheet like documents - but CSV is probably enough to be spreadsheet-like?!

**Comment by cbley-da** [comment]
After a quick review by @nycnewman, the format is fine as is.

**Comment by stefanobaghino-da** [comment]
Thanks for reaching out to @nycnewman directly, he's definitely the SME and main stakeholder here. 🙇🏻
