### ISSUE TITLE
Custom Views alpha release

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#15236]
Prepare Custom Views for the first release (in Early Access, specifically in Alpha):
- [x] #15463
- [x] #15464
- [x] #15465
- [x] #15468
- [x] https://github.com/DACH-NY/projection/issues/7

**Comment by stefanobaghino-da** [comment]
@ray-roestenburg-da Feel free to break it up in multiple tickets, I made the points self-contained so breaking it apart should be one click away.

**Comment by ray-roestenburg-da** [comment]
@stefanobaghino-da thanks

**Comment by ray-roestenburg-da** [comment]
Moved out  #15466 and #15467 from the alpha release.

**Comment by ray-roestenburg-da** [comment]
Published to [maven central](https://repo1.maven.org/maven2/com/daml/custom-views_2.13/2.5.0-snapshot-20221130-4-sa821299a/)
