### ISSUE TITLE
Document the limitations of the JSON API

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15253]
The JSON API is a very useful component to get started quickly. It simplifies common usage patterns. From the JSON API README: 

> The JSON API is here to get basic ACS-using applications off the ground quickly, with a shallow development learning curve. It is not meant to support every ledger use case or every size of application. Always keep in mind that JSON API is an ordinary ledger client; there is nothing that it can do that any application written against the gRPC API could not do, and in a way that is more optimized for whatever advanced application someone might have in mind.

It is important for users to know before they start using the JSON API, what the exact limitations are, especially regarding the size of the application, and the ledger use cases it can support. As an example, the database cache is internal, not optimizable by end users, and is pre-optimized for the JSON API's expected usage. It is likely unclear from the documentation right now which endpoints and usage of those will benefit from that optimization, and which usages cannot and will degrade performance at larger application sizes.

We should be clear about these limitations from the start in the documentation.
The documentation should describe the specific use case that the JSON API is good for, and which size of application it can support, as well as the kind of performance users can expect.

**Comment by stefanobaghino-da** [comment]
Suggestion: use this information to expand the "Production usage" section. Probably, it's worth adding a note at the top emphasizing the role of the HTTP JSON API service as a great tool to minimize time-to-market and/or produce prototypes quickly but requires attention if the ultimate solution has specific scaling aspects to address and/or performance targets to hit. I would recommend de-emphasizing the term "cache" and use "query store" more consistently, document how the HTTP JSON API service reads from and writes to it, how it affects latency and throughput and suggest possible scaling options and alternatives if the load exceeds the capacity of even the best designed and executed deployment.
