### ISSUE TITLE
Wrong type suggestion for Intro8 template in Daml Studio

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#15256]
# Affected Daml versions

Basically all of them; I have tested `1.16.0`, `1.17.1`, `1.18.3`, `2.0.1`, `2.1.1`, `2.2.1`, `2.3.6`, `2.4.0`, and current head (4f08bedc172e89f3d04664507dbcac02aed8e5db).

Note: the template was introduced in `1.14.0`, but does not compile until `1.16.0`.

# Bug description

The IDE suggests a type annotation at the top of the file, which does not correspond to any declaration in the code.

This is the same UX as for a function with no type annotation, where the IDE would suggest the inferred type.

Clicking on the suggestion adds the type annotation, which makes compilation fail.

# To reproduce

```bash
cd $(mktemp -d); DAML_SDK_VERSION=2.4.0 daml new t --template=daml-intro-8; cd t; daml studio --replace=always
```

Open the `daml/Intro/Exception.daml` and wait a few seconds. The type annotation suggestion `_templateLet_Shop : Shop -> Decimal` will appear at the top of the file. (Before the copyright comment, and more importantly before the `module` line.)

# Expected behavior

No type annotation suggestion at the top of the file. Moreover, I expect that whenever the IDE suggests a type annotation, clicking the suggestion to add it to the file leaves the semantics of the code unchanged, and specifically does not break compilation.

# Additional context

This was tested on macOS 12.6 running on a M1 processor. Given the nature of the issue, it seems unlikely to matter, though.

Though the issue appears with the `daml-intro-8` template, the following, pared-down Daml file seems to be enough to reproduce the issue:

```haskell
module Intro.Exceptions where

template Shop
  with
    owner : Party
  where
    signatory owner
    let price: Decimal = 100.0
```

which, along with the `Let_` part of the suggested type annotation, seems to indicate some weird/unexpected interaction between desugaring and whatever the type annotation suggestion engine is in the IDE.

**Comment by akrmn** [comment]
Thanks for raising this. 

For context, the variables `_templateLet_<Template name>` do exist internally for templates with local `let` bindings. I think it's relatively simple to filter out any type signature suggestions for variables whose name starts with `_templateLet_`, though I'm not sure what's the simplest way to test that in our current suite.

We might alternatively get away with generating wildcard type signatures like `_templateLet<Template name> : _` while adding `{-# LANGUAGE PartialTypeSignatures #-}` and `{-# OPTIONS_GHC -Wno-partial-type-signatures #-}` to every module

However, considering https://github.com/digital-asset/daml/issues/13470 brought us really close to dropping this language feature before falling dormant, perhaps a reassessment of that would lead us to dropping it, leaving this moot.

**Comment by garyverhaegen-da** [comment]
If fixing the underlying bug in the compiler is not a priority, and dropping `let` bindings at the template level is on the table (I imagine that's what you meant by "the language feature"?), a simpler way to address this issue would be to rewrite the sample code to not use a template-scoped `let`.

If that sounds like a viable option, I'd be happy to do that myself.

**Comment by akrmn** [comment]
> I imagine that's what you meant by "the language feature"?

Yes, exactly

> a simpler way to address this issue would be to rewrite the sample code to not use a template-scoped `let`

That's a good point. Also, looking at the code, it's a bit weird that `price` is just a local constant that can't be set by the `Shop` owner, another argument for defining it differently. Making it a template parameter would make more sense.

> If that sounds like a viable option, I'd be happy to do that myself.

Thanks, appreciated. Please tag @digital-asset/daml-language and @digital-asset/compiler on the PR.
