### ISSUE TITLE
Current module name collision detection in codegen may not be necessary for some modules in codegen

### ISSUE THREAD

**Issue by chunlokling-da** [digital-asset/daml#15340]
Originated from https://github.com/digital-asset/daml/issues/15341

Assuming prefixes are not configured at Dar file level nor at daml.yaml. Here is a brief description of the flow of how code-gen currently does the module collision detection on dar files:

1. Load 1 or more dar files specified in the command line arguments.
2. For each dar file, decode it into 1 or more `typesig.PackageSignature`s. Each of these has a package id
3. Collect all of these `typesig.PackageSignature`s and deduplicated packages by package id to produce a list of `typesig.PackageSignature`s
4. For each module name found in these `typesig.PackageSignature`s, Produce a list of (module name, Package Id)
5. Group the list of pairs by module name, if there exists a module name that is associated with more than 1 package id, a collision is detected and an error occurs for the code generation.

Questions / Discussions:

1. What is the purpose of this collision detection introduced in the first place? Is it mainly to avoid name clash of generated code?
2. If it is to avoid name clash of generated code, the current collision check is done on all module names including those which are not to be generated. (e.g. GHC.Stack.Types). It seems to be sensible that we should only check for collision on modules which is going to be generated. 
3. How do we determine whether the module needs to be generated? From the current behavior, it seems that only those included in`Scope.serializableTypes` will be generated. What does serializableTypes actually mean?
4. From https://github.com/digital-asset/daml/issues/15341, it appears that the collision is detected on the 2 packages seem to be the same package but with different package id. Is it a valid cases? Could it be a case of 2 different versions of the same packages `daml-prim`?

The problem:

Current module name collision detection in code gen is done on all types found from the dar files. We should only do the collision check on the types which are used for code generation. In the issue of  https://github.com/digital-asset/daml/issues/15341 , `GHC.Stack.Types` module is definitely not one of these types being used.

**Comment by cocreature** [comment]
There are two checks we need:

1. Each generated module should only be associated with one package prefix. If there are multiple, we should produce an error and not chose randomly.
2. After adding the prefixes there should be no module name collisions for the generated modules.


We definitely don’t want a collision check for any two modules in different packages.

**Comment by ray-roestenburg-da** [comment]
3. as far as I know, and this is a loose definition, serializable types are records, and all types that are referenced in records, all the way down to the 'primitives'. We generate the types that users can use to interact with the gRPC services, so I imagine these as arguments to the gRPC service calls, which need to be serializable (obviously), other types the users do not need since they would not be able to do anything meaningful with them. I think we concluded from offline discussions that we could use the code that is in place to find all types in dependencies (DependencyGraph.transitiveClosure which we should rename)

**Comment by ray-roestenburg-da** [comment]
4. This question has been answered in https://github.com/digital-asset/daml/issues/15341 

> @garyverhaegen-da has found that daml-finance is compiled with --target=1.15 but daml-ctl isn't, so it ends up using the default 1.14. Therefore we have 2 different packages for daml-prim. However, module name collision should never check on type such as GHC.Stack.Types which is not going to be generated in the code-gen output.

Are there any outstanding questions here that need to be answered @chunlokling-da ? otherwise please remove discussion label.

**Comment by chunlokling-da** [comment]
@ray-roestenburg-da All my questions are well answered. Thanks. I have removed the discussion label
