### ISSUE TITLE
Expose template id from com.daml.ledger.javaapi.data.Template

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#15350]
For the Scala codegen, I can easily get access to the template id when working generically with templates. For the Java codegen I cannot. Each template has it but it’s not part of the Template class they inherit from.

**Comment by cocreature** [comment]
As far as I can tell, I also cannot hack my way around that by calling `toValue` because the generated value does not have the record id set.

**Comment by S11001001** [comment]
Probable implementation of this would be to add

```java
  /** @hidden */
  protected abstract ContractCompanion<
      ? extends Contract<? extends ContractId<? extends Template>, ? extends Template>,
      ? extends ContractId<? extends Template>,
      ? extends Template> getCompanion();
```

To which the static `COMPANION` already conforms, simplifying the implementation of `getCompanion` in codegen. Then we can define `getTemplateId()` in `Template` similar to how `templateId` is defined for Scala `Template`.

**Comment by cocreature** [comment]
While we're at it, please also expose it from `Contract`.
