### ISSUE TITLE
Wrong type suggestion in Daml Studio when using template-scoped let

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#15359]
# Affected Daml versions

Basically all of them; @garyverhaegen-da tested `1.16.0`, `1.17.1`, `1.18.3`, `2.0.1`, `2.1.1`, `2.2.1`, `2.3.6`, `2.4.0`, and current head (4f08bedc172e89f3d04664507dbcac02aed8e5db).

# Bug description

The IDE suggests a type annotation at the top of the file, which does not correspond to any declaration in the code.

This is the same UX as for a function with no type annotation, where the IDE would suggest the inferred type.

Clicking on the suggestion adds the type annotation, which makes compilation fail, because type annotations are not allowed before the `module` declaration.

# To reproduce

```yaml
# daml.yaml
sdk-version: 2.4.0
name: tlet
source: Main.daml
version: 0.0.1
dependencies:
  - daml-prim
  - daml-stdlib
```

```haskell
-- Main.daml
module Main where

template T with
    owner  : Party
  where
    signatory owner
    let x : () = ()
```

Save `daml.yaml` and `Main.daml` to a new empty directory, then open the directory in Daml Studio and wait a few seconds. The type annotation suggestion `_templateLet_T : T -> ()` will appear at the top of the file. (Importantly, before the `module` line.)

# Expected behavior

No type annotation suggestion at the top of the file. Moreover, I expect that whenever the IDE suggests a type annotation, clicking the suggestion to add it to the file leaves the semantics of the code unchanged, and specifically does not break compilation.

# Additional context

This was tested on macOS 12.6 running on a M1 processor. Given the nature of the issue, it seems unlikely to matter, though.

This was originally raised as #15256, which dealt specifically with the occurrence of this issue in the `daml-intro-8` template. Since #15358 closes that issue, this ensures we keep track of the general case.

**Comment by basvangijzel-DA** [comment]
@dylant-da I think this is now fixed with https://github.com/digital-asset/daml-ghcide/pull/23?
