### ISSUE TITLE
Confusing error message when using `..` on a non-existing record

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#15389]
### What is the problem you want to solve?

This code:

```haskell
module Main where

import Daml.Script

data D = D with f1 : Int, f2 : Int

setup : Script ()
setup = script do
  let d1 = D 1 2
  debug(d2 with ..)
  return ()
```

produces the confusing error:

```plain
Message:  daml/Main.daml:10:17: error: You cannot use `..' in a record update
```

which is technically correct, but I think something along the lines of:

```plain
Message:  daml/Main.daml:10:9: error:• Variable not in scope: d2
```

would be better.

### What is the solution you would propose?

Detect unbound variables before record update syntax.

### Describe alternatives you've considered

If at that point we can't yet know which variables are in scope, perhaps a more explicit "you need a type name here instead of a variable name" type of error message could work too.

Alternatively, we could just support `var with ..` syntax. It's not needed and arguably a bit wasteful, but I can't see it doing any harm either.

### Additional context

Note that

```haskell
module Main where

import Daml.Script

data D = D with f1 : Int, f2 : Int

setup : Script ()
setup = script do
  let d1 = D 1 2
  debug(d1 with ..)
  return ()
```

produces the same error message, suggesting the invalid syntax gets caught "before" the unbound variable. Even in this case, I think pointing out you need a type (or supporting that syntax, and failing here because neither `f1` nor `f2` is in scope) would be better.

This was inspired by a [forum discussion](https://discuss.daml.com/t/scrip-result-does-not-appear/5544).

**Comment by S11001001** [comment]
I'm not a big fan of the suggested error message.

> Variable not in scope: d2

implies that if you bring `d2` with a suitable type into scope, this will work. But it won't. It won't work if you fix the "typo" by changing it to `d1` either, which is the other usual implied fix of unbound variable errors.

If we're to improve the error message, I think a restatement of the current one would be better. Such as stating that only a data constructor (the relevant `D` here is the data constructor, not the type; compare to variant data constructors) can be used with `..`, which is technically just another way to word the current message.

**Comment by garyverhaegen-da** [comment]
That makes sense, yes. Something like:

```
error: .. is only supported with a data constructor
```
at least points to a solution.
