### ISSUE TITLE
Investigate dev-env log ordering

### ISSUE THREAD

**Issue by jonas-chevalier-da** [digital-asset/daml#154]
For some reason the "build dev-env" logs are not ordered properly.

These logs should be before:
```
$ nix-build --no-out-link ./nix -A tools -A cached
outputs:
```

these logs:
```
[n| 200 | 	 19.936961ms | localhost:3000 | GET /wz21gkn36xj3m8z1w5knnvzpg4s6nhzn.narinfo
[n| 200 | 	 21.424099ms | localhost:3000 | GET /wzb2mb1zkrgdhm39vsm1dgf5ci4jd1xs.narinfo
[n| 200 | 	 25.395908ms | localhost:3000 | GET /x04vc2k1dji1hyfizyz9mvq04gqjyqhy.narinfo
[n| 200 | 	 13.373926ms | localhost:3000 | GET /zzk5hw8fx9sx14rlf7wxwrh2by8h1qi7.narinfo
```

I have tried many approaches to fix this issue. For example sending all the logs to stderr to make sure they are linearized.

I think the issue is that stdout and stderr are not line-buffered on Azure.

**Comment by cocreature** [comment]
Hasn’t come up within the last year so closing.
