### ISSUE TITLE
remove overloads in `CommandClient`

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#15424]
...using an auxiliary builder or other type, similar to how `ContractUtil` overloads the companions for `TransactionClient` and `ActiveContractClient`.

* [ ] introduce new functions
* [ ] deprecate old functions

**Comment by S11001001** [comment]
There are a few broad strategies that are generally worth comparing.

## factoring overloads as an auxiliary type

This is how `ContractUtil`, which essentially abstracts over the usage of `ContractCompanion` or `InterfaceCompanion` for ACS/transaction streams.

We have 4 functions that take a `ContractUtil`, and two overloads that produce instances, one for each possibility. 6 functions. If, instead, we embedded directly two functions, one for each companion, then we would have 8 functions.

So, anywhere we have common sets of options to different functions, that multiply their overloads in a common way, we can refactor those option sets to a separate type, provide syntax for producing values of that type, and accept those values as arguments to the client API instead.

This can be combined with any of the other strategies: you could produce the auxiliary type's values with builders, or have factory methods that take optionals, &c, &c.

## builder

This is only suitable for option sets that are all truly optional, i.e. every possible arrangement of option settings is possible. So, for example, it won't work if you must specify _either_ x and y _or_ a and b and c. We could define an auxiliary sum type in that case instead.

I know @fayi-da isn't a fan of builders, I'd guess due to its verbosity and mutate-y awkwardness, but the pattern does have some advantages worth considering:

1. it also fixes the problem where we don't have keyword arguments in Java
2. it doesn't require further explanation to use it
3. it lets us add and deprecate individual arguments without breaking compatibility significantly

## sum types

Only really useful in more complex cases where builders would allow you to create invalid option sets, like the example mentioned above. Also probably verbose enough that it's only really beneficial if you can use the resulting auxiliary type for multiple API functions.

`ContractUtil` is effectively an example of this, even though the implementation doesn't look like it.

## optional and empty map/list

This is a straightforward translation of the current API. I won't dig into its advantages, as @fayi-da is aware of them. But I do want to point out the semantic weakness: it is by no means obvious that an empty list or map passed as an argument is "just the default", rather than a semantically meaningful empty list or map. We cannot regain the advantage from Scala where the default argument is explicitly specified _as_ a default with this approach.

It is less obvious, but this problem also applies to optional. It is more common to use `None` to mean default, but that doesn't mean every `None` you encounter is a default rather than a semantically meaningful argument.

**Comment by ray-roestenburg-da** [comment]
I would prefer a combination of auxiliary type and if needed a builder on that auxiliary type, only for optionals, as @S11001001 points out.
