### ISSUE TITLE
Daml Studio reports problem "HLint 2.3 and beyond cannot use Haskell configuration files"

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#15443]
Opening Daml Studio on any project using Daml SDK version `2.5.0-snapshot.20221028.10865.0.1b726fe8` reports this error message as a project "Problem":

```
[{
	"resource": "/",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "HLint 2.3 and beyond cannot use Haskell configuration files.\nTried to use: [(\"/home/moritz/.daml/sdk/2.5.0-snapshot.20221028.10865.0.1b726fe8/damlc/lib/resources\",Nothing)]\nConvert it to .yaml file format, following the example at\n  <https://github.com/ndmitchell/hlint/blob/master/data/hlint.yaml>\nCallStack (from HasCallStack):\n  errorIO, called at src/Config/Read.hs:16:9 in hlint-2.2.11:Config.Read",
	"source": "compiler",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}]
```

Originally reported by @cocreature on slack

**Comment by cocreature** [comment]
Do you know how this got through our manual release tests? I would have expected that we catch this in the Daml Studio tests.

**Comment by akrmn** [comment]
> Do you know how this got through our manual release tests? I would have expected that we catch this in the Daml Studio tests.

I'd say it's very easy to miss since the bug only results in one "Problem" being reported in the lower left corner, only visible as "❌ 1 ⚠️ 0" instead of the usual "❌ 0 ⚠️ 0". The only way to actually see the error is to open the Problems tab, which isn't part of the tests, and the rest of the tested components work as usual (for instance, the "Script results" code lens works fine)
