### ISSUE TITLE
Integrate Custom Views in the SDK releases

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15468]

**Comment by ray-roestenburg-da** [comment]
@garyverhaegen-da made a point in a recent meeting that integrating the projection library into the SDK is not strictly necessary. @stefanobaghino-da I would like to consider this option, since we can simply provide a maven published artifact to developers. The projection library does not have to follow the SDK version scheme either.

**Comment by stefanobaghino-da** [comment]
@bame-da? To the best of my understanding you want everything versioned in lockstep and the documentation in a single place.

@ray-roestenburg-da Waiting for Bernhard's ack, feel free to take whatever approach you deem most effective to fulfill the constraint above.

**Comment by ray-roestenburg-da** [comment]
After some discussions, integration is done by publishing versions on main commits to maven and then assigning a specific version deployment when a final version is released. cc @garyverhaegen-da  let me know if I missed anything.
