### ISSUE TITLE
Use Blocking dispatcher for blocking IO operations

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15486]
JDBC and Doobie both use blocking IO. Actions should be executing on a dedicated fixed size threadpool, see [handling blocking operations in akka http routes](https://doc.akka.io/docs/akka-http/current/handling-blocking-operations-in-akka-http-routes.html) and [blocking needs careful management](https://doc.akka.io/docs/akka/2.7/typed/dispatchers.html#blocking-needs-careful-management). 

Solution: configure a `blocking-dispatcher` in `reference.conf` in the projection lib, lookup the dispatcher via `context.system.dispatchers.lookup`, use this execution context for blocking calls. Users can override settings for this blocking-dispatcher through the `application.conf`.

origin: https://github.com/DACH-NY/projection/issues/49
overview: https://github.com/digital-asset/daml/issues/15463

**Comment by chunlokling-da** [comment]
Also useful doc: https://doc.akka.io/docs/akka/2.5.32/stream/stream-integrations.html#integrating-with-external-services
