### ISSUE TITLE
Ensure automated test to make sure templates produced by da new can be consumed by navigator and sandbox

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#155]
brian   [2 minutes ago]
@ivy.peng just discovered that `da new` did not work correctly with SDK 0.11.24 (invalid character at VOID# when starting sandbox).  resolved by upgrading to 0.11.25 : do we have any tests around verifying the da new command and making sure the DAML produced plays happily with everything? (edited)

neil   [1 minute ago]
If we didn’t catch it, then clearly not. Can you open a ticket for it? Seems an obvious thing to check.

neil   [< 1 minute ago]
However, I think our manual tests would have caught that, so we wouldn’t have ever made 0.11.24 public

not-fran   [< 1 minute ago]
There's a manual test involved before releasing an SDK publicly that includes running `da new`.

brian   [< 1 minute ago]
okay i'll create a ticket

**Comment by akalburgi** [comment]
The new `daml assistant` has integration tests
