### ISSUE TITLE
Unexpected and flaky "No scenario root for file" in IDE

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#15523]
# Affected Daml version

2.4.0 with Daml-LF 1.15

# Bug description

I have the IDE open in `/Users/bame/repo/upgrading-daml-training`.

In one file I get the error

```
user error (No scenario root for file "/Users/bame/repo/upgrading-daml-training/daml/Exercise3/Solutions/Currency/Bonus/Scripts.daml".)
```

# To reproduce

1. Check out https://github.com/DACH-NY/upgrading-daml-training
2. Hope

I can't reliably reproduce this. Reloading the window fixes it.

# Expected behavior

No error.

# Additional context

**Comment by akrmn** [comment]
hi @bame-da, I'm trying to reproduce this on my machine but I don't have access to the repo you mention (neither on this account nor on @moisesackerman-da). Could you please give me access to it?

**Comment by akrmn** [comment]
I do have access now (thanks @garyverhaegen-da!) but I haven't been able to reproduce the issue
