### ISSUE TITLE
Support Pruned Ledgers in Navigator

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#15520]
### What is the problem you want to solve?

I would like to be able to use the Navigator in Test/Dev environments which were pruned.

### What is the solution you would propose?

Bootstrap the Navigator like we recommend bootstrapping other client applications: from an ACS snapshot.

### Describe alternatives you've considered

We could make bootstrapping from ACS optional if we wanted full backwards compatibility of showing all archived contracts.

**Comment by bame-da** [comment]
At a minimum, we should document this limitation for the time being.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
