### ISSUE TITLE
Sandbox fails divulgence semantic test

### ISSUE THREAD

**Issue by timw-da** [digital-asset/daml#157]
The following PR aims to extend our sandbox semantics tests, however one of the tests "test_divulgence_of_token" had to be disabled as the semantics from the sandbox are not as expected. The test is now in master and can be enabled by removing the blacklist here: https://github.com/DACH-NY/daml/blob/f4cc62cf3b063c3679ce65512a00676b03ba51f6/ledger/ledger-api-integration-tests/src/test/semanticsuite/scala/com/digitalasset/platform/semantictest/SandboxSemanticTestsLfRunner.scala#L31

**Comment by dajmaki** [comment]
I don't think #10 is related to this.
