### ISSUE TITLE
Trigger messages need priority processing

### ISSUE THREAD

**Issue by carlpulley-da** [digital-asset/daml#15707]
Currently, whenever the trigger service is overloaded with command submissions, then messages from the transaction and completion sources may be arbitrarily delayed. This can lead to the trigger service internal buffers overflowing (particularly if there are too many command submission failures) and the trigger service failing.

One concrete example of this behaviour was evident when we introduced rate-limiting for in-flight command submissions. When a large number of created contracts needed to be processed at trigger start up, this eventually led to lots of command submission failures (since only 50 submissions could be processed at a time) and eventually to the submission queue overflowing. Logging indicated that 98-99% of the time was being spent initialising the trigger rules with only 1% (at best) of the transaction and completion message being processed, and so the trigger rule Daml ACS and in-flight data structures were never updated in a timely manner.

in these loading scenarios, we should investigate if the use of priority message processing might help out.

Ref: https://github.com/digital-asset/daml/pull/15697

**Comment by stefanobaghino-da** [comment]
Would it be possible to gracefully propagate back-pressure to the original caller?

**Comment by carlpulley-da** [comment]
Closing this ticket as this work as triggers are now deprecated
