### ISSUE TITLE
Make explicit eventId to offset relationship in proto specs.

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#15750]
### What is the problem you want to solve?
The format of event_id has an implicit guarantee that it is `offset:number` 

### What is the solution you would propose?

Make that explicit.

### Describe alternatives you've considered
We could ignore it but then we do have to store the offset separately in off ledger components.

**Comment by stefanobaghino-da** [comment]
There's no such guarantee at the API level of any such formatting. If you're interested in the ordering of events by their ID as part of a transaction, it's already documented (see `child_event_ids` [here](https://docs.daml.com/app-dev/grpc/proto-docs.html#exercisedevent)).
