### ISSUE TITLE
Allow to run tests manually in the IDE

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#15780]
### What is the problem you want to solve?

Long running tests can become difficult to handle for the IDE. Since minor code edits can trigger them, they can become unwieldy and lead to a sub-optimal developer experience.

### What is the solution you would propose?

Allow to disable tests from running automatically in the IDE and add the possibility of running them individually from the IDE through manual interaction (as it is common to do in mainstream languages using widespread IDEs).

### Describe alternatives you've considered

Wrapping tests in functions and manually write in the tests that I want to be run at a specific time. Gets the job done but not ideal in terms of developer experience.

**Comment by dylant-da** [comment]
https://github.com/digital-asset/daml/pull/16211
