### ISSUE TITLE
Old style `maintainer` expressions lead to ambiguous occurrence errors

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1578]
Before, this would work:

```
template T
  with
    p : Party
  where
    signatory p

template K
  with
    p : Party
  where
    signatory p

    key this : K
    maintainer p
```

In the newest SDK, it needs to be `maintainer key.p`, not `maintainer p`. The error, is very unhelpful as it just reads "Ambiguous occurrence ‘p’". Changing to the intuitive `this.p` gives "Variable not in scope: this". Neither will help users figure out what to do.

**Comment by bame-da** [comment]
Oh and without the template `T`, the error is 
```
No instance for (IsParties (K -> Party))
        arising from a use of ‘toParties’
```
That's no better, either.

**Comment by bame-da** [comment]
In addition to a better error messages, would it be possible to prepend `let K {..} = key in` to the `maintainer` expression in those cases where `K` is a record?

**Comment by neil-da** [comment]
The real solution to this is to disable top level record selectors, which helps a bit. I'm not overly keen on having a special "if this type is a record" rule... I am expecting most keys to be tuples, but not sure if that's the case in reality.

**Comment by bame-da** [comment]
>  I am expecting most keys to be tuples
I'm expecting most keys to be records. I don't like defining the same data twice so I tend to construct things like this:

```
data K = K
  with
    p : Party
    i : Int
    t : Text
      deriving (Eq, Show)

template MyTemplate
  with
    k : K
    a : Party
    b : Party
  where
    signatory a, b, k.p

    key k : K
    maintainer key.p
```

**Comment by hurryabit** [comment]
Given that we don't teach people about the old syntax anymore, I consider this irrelevant.
