### ISSUE TITLE
Filter by contract payload in Navigator

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#15788]
### What is the problem you want to solve?

Sifting through a large number of contracts in Navigator can be unwieldy without supporting for predicates based on contract payload.

### What is the solution you would propose?

Add the possibility of filtering contracts based on specific properties in their payload.

### Describe alternatives you've considered

Sorting and looking for something manually.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
