### ISSUE TITLE
Document `daml test` subcommand

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#15781]

**Comment by basvangijzel-DA** [comment]
Dylan/Moisés also found an issue on daml test reporting.

**Comment by stefanobaghino-da** [comment]
> Dylan/Moisés also found an issue on daml test reporting.

What's the issue?

**Comment by dylant-da** [comment]
This is for the changes that are coming down to 2.5.0 - we count the number of local interface implementations correctly, but the breakdown into local/external interfaces is incorrect.

**Comment by basvangijzel-DA** [comment]
@dylant-da How quick a fix would this be? They're considering an RC2 for 2.5.0, so would this be a doable fix for that?

**Comment by dylant-da** [comment]
yes, I have a PR going here https://github.com/digital-asset/daml/pull/15806

**Comment by dylant-da** [comment]
Documentation: https://github.com/digital-asset/daml/pull/16024
