### ISSUE TITLE
Items being cut off by Navigator

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#15787]
### What is the problem you want to solve?

Items like choices in a template or interface or fields like observers disappearing from the view when there are too many of them.

### What is the solution you would propose?

Ensure that a reasonably large number (~tens) of items like choices in template or interfaces or fields like observers always appear on the Navigator UI.

### Describe alternatives you've considered

Fixing the CSS during the active browser session, which is definitely not something developers should do to work around this.

**Comment by stefanobaghino-da** [comment]
Example of items (specifically choices) being cut off.

![cut](https://user-images.githubusercontent.com/43749967/205661646-54062010-34f4-4330-8c09-0f0ceeacc53c.png)

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
