### ISSUE TITLE
Allow to collapse and expand record payload visualization in Navigator

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#15790]
### What is the problem you want to solve?

Visualizing a contract's payload in Navigator can become difficult with a quite complex and nested record structure.

### What is the solution you would propose?

Allow to dynamically collapse and expand a contract's payload as necessary. Anything beyond the first level of nesting is probably better to be kept collapsed to make the visualization cleaner by default.

### Additional context

Related to #15785

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
