### ISSUE TITLE
Error message for choices being called on wrong templates triggers incorrectly

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#15813]
Take this example
```
module Main where

import Daml.Script
import DA.Assert

template T
  with
    p : Party
  where
    signatory p

    choice C : ()
      controller p
      do pure ()

exerciseE : Choice t c (Either Text r) => ContractId t -> c -> Update r
exerciseE cid c = do
  r <- exercise cid c
  case r of
    Left err -> abort err
    Right r -> pure r

test : ContractId T -> Update ()
test cid = exerciseE cid C
```

This fails with
```
  daml/Main.daml:24:12: error:
  • Tried to exercise a choice ‘C’ on template ‘T’ but no choice of that name exists on template ‘T’
  Choice ‘C’ belongs only to the following types: template ‘T’
  • In the expression: exerciseE cid C
  In an equation for ‘test’: test cid = exerciseE cid 
```

That is just wrong, the choice with that name does exist. It just has a different type. More confusingly, the actual type error is hidden.

**Comment by dylant-da** [comment]
The second line in the error, `Choice ‘C’ belongs only to the following types: template ‘T’`, shows that the checker knows about the relationship between C and T - the TcDaml checker didn't have a case for this possibility (return type mismatch), so it fell through to the default case, which complains about nonexistence

**Comment by dylant-da** [comment]
https://github.com/digital-asset/daml/issues/15890
