### ISSUE TITLE
Update custom-view example

### ISSUE THREAD

**Issue by fayi-da** [digital-asset/daml#15823]
In #15808 , the `ConnectionSupplier` was removed in favour of a `DataSource`. The [custom-views example](https://github.com/digital-asset/ex-custom-views-spring-boot) should be updated to reflect this

**Comment by fayi-da** [comment]
Depends on https://github.com/digital-asset/custom-views/pull/15

**Comment by ray-roestenburg-da** [comment]
Fixed by https://github.com/digital-asset/ex-custom-views-spring-boot/pull/3
