### ISSUE TITLE
Daml engine propagates the agreementText as part of the usedDisclosedContracts interpretation result

### ISSUE THREAD

**Issue by tudor-da** [digital-asset/daml#15846]
Canton needs the `agreementText` for converting a disclosed contract into an input contract, for backwards compatibility reasons.

**Acceptance criteria**
`Engine.submit` enriches `com.daml.lf.transaction.Transaction.Metadata.disclosures` with an additional field for `ProcessedDisclosedContract`, `agreementText` - extracted during interpretation.

**Comment by daravep** [comment]
But how will we then instruct the autonomous enforcement devices? Joke aside, yes, I think it makes sense to deprecate this field and simply not support out of band disclosure of contracts with agreements.

**Comment by remyhaemmerle-da** [comment]
fixes by #15901
