### ISSUE TITLE
Conversion from javaapi.data.Value to lf.value.Value

### ISSUE THREAD

**Issue by chunlokling-da** [digital-asset/daml#15865]
From https://github.com/digital-asset/daml/issues/13558

Create a new library under language support to implement the conversion between `javaapi.data.Value` and `lf.value.Value` in both directions

**Comment by chunlokling-da** [comment]
@S11001001 

I have found this util `ApiValueToLfValueConverter` in json api which can be used to convert `javaapi.data.Value` to `lf.value.Value`

https://github.com/digital-asset/daml/blob/d2e2c21684e2d9eade40f74990208125ad4b4ccb/ledger-service/http-json/src/main/scala/com/digitalasset/http/util/ApiValueToLfValueConverter.scala#L26

My plan is `javaapi.data.Value` -> ledger.api.v1 proto (using ApiValueToLfValueConverter ) -> `javaapi.data.Value`
Do you think it is reasonable?

**Comment by chunlokling-da** [comment]
> My plan is javaapi.data.Value -> ledger.api.v1 proto -> (using ApiValueToLfValueConverter ) -> lf.value.Value
Do you think it is reasonable?

Just had a quick chat with @S11001001, it is not a good idea to convert the `javaapi.data.Value` to large type `ledger.api.v1 proto`  and then convert it back to the small type `lf.value.Value`. Plus the proto types are not the same (java one vs scala one)

As discussed, I will create a new library to implement the conversion between  javaapi.data.Value and lf.value.Value in both direction

**Comment by S11001001** [comment]
> javaapi.data.Value and lf.value.Value in both direction

To facilitate the first, you might define a `fold` using methods similar to what we have for `Update` or [this one](https://github.com/digital-asset/daml/blob/5ab3fd7cbefce0100613eacc2112e0935cb221df/daml-lf/api-type-signature/src/main/scala/lf/typesig/Type.scala#L178-L191) on `javaapi.data.Value`, as you won't have any kind of exhaustiveness checking otherwise.
