### ISSUE TITLE
Bug: the update parameter to submitAndWaitForResult is not used as the command to submit, unless it is passed in the CommandSubmission.

### ISSUE THREAD

**Issue by fayi-da** [digital-asset/daml#15905]
In #15519 , we deprecated overloaded methods for command client which mean't to use the command client, you write something like:

```scala
val commandsSubmission =
  CommandsSubmission.create(appId, commandId, update.commands()).withActAs(actAs).withReadAs(readAs)

client.getCommandClient.submitAndWaitForResult(
  commandsSubmission,
  update
)
```

However, from the above, you have to provide the update twice and it is possible to provide the wrong arguments to `CommandsSubmission.create(...)` as it is unclear what commands are expected. A potential solution will be to have something like:

```scala
val commandsSubmission =
  CommandsSubmission.create(appId, commandId, update).withActAs(actAs).withReadAs(readAs)

client.getCommandClient.submitAndWaitForResult(
  commandsSubmission
)
```

Here, the update is provided just once on creation and can be used to augment `commandsSubmission` within the implementation of `submitAndWaitForResult()`

- [ ] Add Update as a member of CommandsSubmission
- [ ] Update submitAndWaitForResult to `submitAndWaitForResult(final CommandsSubmission submission)`
- [ ] Update implementation of `submitAndWaitForResult()` to get update and commands from the passed in 'CommandsSubmission`

**Comment by ray-roestenburg-da** [comment]
The potential solution described is problematic for the methods that use `CommandSubmission` without an `Update`. Another possibility is to change the `submitAndWait...` methods to take a ``CommandSubmission` and a `List<Command>`, remove the `List<Command>` from CommandSubmission, so that it becomes:

```
val commandsSubmission =
  CommandsSubmission.create(appId, commandId).withActAs(actAs).withReadAs(readAs)

client.getCommandClient.submitAndWaitForResult(
  commandsSubmission, 
  update
)
```

**Comment by ray-roestenburg-da** [comment]
It seems to make more sense to create a specific `CommandsSubmission` like type for `Update`.
