### ISSUE TITLE
Release damlc windows jar (damlc-xxx-windows.jar)

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#1591]
We currently do not publish damlc windows jar as part of the release, only osx and linux jars are available:
https://digitalassetsdk.bintray.com/DigitalAssetSDK/com/digitalasset/damlc/100.12.24/
```
damlc-100.12.24-linux.jar
damlc-100.12.24-linux.tar.gz
damlc-100.12.24-osx.jar
damlc-100.12.24-osx.tar.gz
damlc-100.12.24.pom
```
If we are planning to fully support Windows as a dev platform, we need `damlc-xxx.windows.jar` released along with linux and osx jars. We have a few SBT examples that work only on Windows and  OSX just because of this limitation. Here is one of them:

https://github.com/digital-asset/daml/blob/cc21c78be221748b400b6ac928c9cc3d0d5b082e/language-support/scala/examples/codegen-sbt-example/project/daml.sbt#L7

Spider uses the same approach. They build their DAR from the SBT build. Integration testing also requires the ability to compile DARs from SBT or Maven.

**Comment by leo-da** [comment]
CC: @cocreature @neil-da @associahedron

**Comment by cocreature** [comment]
I very much would like to avoid extending support for the damlc jar. Given that the only user of it is considering to move away from it, I don’t think we should spend effort on supporting this on Windows.

**Comment by neil-da** [comment]
We're not going to do this, as there is no demand for it from actual users. We are intending to kill the damlc jar soon - apparently Docker is a preferred alternative.
