### ISSUE TITLE
Navigator cannot be used to demo Canton examples

### ISSUE THREAD

**Issue by wallacekelly-da** [digital-asset/daml#15918]
# Affected Daml version

2.4.2

# Bug description

When trying to use Navigator to test or demonstrate the creation of a contract in a Canton network, Navigator only ever displays the _local_ Parties of a Participant node. Consequently, Navigator cannot be used to test or demonstrate Canton examples. 

# To reproduce

Setup a project with this topology.

![image](https://user-images.githubusercontent.com/116685059/208128128-8066e915-6f4b-4bee-855b-db3d4432dc7c.png)

1. Either:
    * Clone [this branch](https://github.com/wallacekelly-da/daml-public-demos/tree/navigator-non-local-parties/navigator-non-public-parties) or
    * Follow the instructions in the [README](https://github.com/wallacekelly-da/daml-public-demos/blob/navigator-non-local-parties/navigator-non-public-parties/README.md) to setup the project from scratch.
3. Run `daml build`.
4. Run `canton-open-source-2.4.2/bin/canton --config canton.conf --bootstrap bootstrap.canton`
5. Run `daml navigator server -c ui-backend-participant1.conf --feature-user-management false localhost 5011`
6. Browse to `http://localhost:4000`
7. Login as a Bank.
8. Try to create a Main:Asset contract, with a Bank issuing an asset to an Alice.

# Expected behavior

When selecting the _owner_ field, the dropdown box includes all parties in the domain, including Alice.

# Actual behavior

When selecting the _owner_ field, the dropdown box _does not include_ Alice.

![image](https://user-images.githubusercontent.com/116685059/208128189-1d4a8a81-1eea-428e-87a7-e33ccb4983b7.png)

# Workaround

1. Within the Canton Console, run `mydomain.parties.list("Alice").head.party.toProtoPrimitive`.
2. Copy the resulting string (e.g., `Alice::122018b58d58548da032498e024c6a056fe352bff317d33cf31c55749e359fcbcaf1`) and paste it into Navigator's _owner_ field.
3. Fill in the other contract fields, press Submit, and create the contract successfully.

# Additional context

See [this forum discussion](https://discuss.daml.com/t/navigator-drop-downs-only-include-local-parties/5829?u=wallacekelly).

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
