### ISSUE TITLE
THREADPOOL_OVERLOADED when loading large number of packages

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#15922]
Spin-off of #15551, as reported by @GeorgSchneider . When loading a large number of packages (66 is good enough), and perhaps also starting many active websocket streams (which may trigger a race that multiplies said loading), we see sometimes

```
11-11-2022 14:58:35.623 [http-json-ledger-api-akka.actor.default-dispatcher-13] ERROR akka.actor.ActorSystemImpl - Websocket handler failed with ABORTED: THREADPOOL_OVERLOADED(2,0): The Index Database Connection Threadpool queue size (1005) has exceeded the maximum (1000). Api services metrics are available at daml.index.db.threadpool.connection.api-server. 
io.grpc.StatusRuntimeException: ABORTED: THREADPOOL_OVERLOADED(2,0): The Index Database Connection Threadpool queue size (1005) has exceeded the maximum (1000). Api services metrics are available at daml.index.db.threadpool.connection.api-server.
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Unlike with #15551, json-api manages to recover from this problem. See that issue for reproduction.

**Comment by S11001001** [comment]
One possible cause: a regression following #10602. Since #10192 is an important feature, we really can’t go back on that.

I suspect this because in the only situation where I’ve observed this, it happens in concurrence with the first websocket requests in reproducing #15551 (which is otherwise unrelated to this issue), which coincide with many log messages with repeated package IDs produced by this line

https://github.com/digital-asset/daml/blob/2dd939ced365426a2fcdb6f22375124e1944519e/ledger-service/http-json/src/main/scala/com/digitalasset/http/PackageService.scala#L124

And moreover, when I replace `traverse` with [`traverseFM`](https://github.com/digital-asset/daml/blob/311f419842845f7135f6b538446fd390a6ee6d2e/ledger/participant-integration-api/src/test/lib/scala/platform/store/dao/JdbcLedgerDaoSuite.scala#L909-L919) in the following line, the `THREADPOOL_OVERLOADED` errors go away:

https://github.com/digital-asset/daml/blob/2dd939ced365426a2fcdb6f22375124e1944519e/ledger-service/utils/src/main/scala/com/digitalasset/ledger/service/LedgerReader.scala#L65

However, **this does not make `traverseFM` a good solution in this case, just a confirmation of a source of the problem**.

1. _Why does this make me suspect #10602?_ Because if concurrent requests need to update the package store, they will each try to perform the update. The bigger the update, the longer this takes, and the more likely it is to happen concurrently with other requests. Now, this never leads to bad data, because each is just doing the same work, and the last one “wins” but that is essentially irrelevant. However, it means that you’re multiplying a potentially large number of concurrent package service requests by a large number of websockets you’re trying to start up, and retrying if they fail which starts the process over…
2. Why is `traverseFM` good evidence? Because, as described in its javadoc, it essentially makes each request make at most one package service request at a time. If that fixes the problem in all reproduction scenarios, then large numbers of concurrent package service requests are the proximate cause.

### `traverseFM` is a bad solution

One at a time per json-api request is too few. You can do grouped requests, combining `traverseFM` and `traverse` (because `Traversable` functors compose), but this is a hackish approach, and risks still multiplying into overload.  We would really prefer a server-wide limit.

### bespoke shared state is also a bad solution

We do our best to limit the possibility of problematic concurrent update. In a sense, the #10602 strategy of the single-assignable-variable cache and making double-evaluation mostly harmless avoids a very large class of potential concurrent update bugs.

One could imagine a hand-written service that globally enqueues package service requests and caches the responses, so double-evaluation would still happen for package parsing and the rest of the cache update, but would be suppressed for the requests to the package service. However, I have a much better idea for effectively achieving a global limit on package service requests that doesn’t entail bug-prone bespoke concurrent shared state, explained below.

### partial loading or “one package at a time” will not work

You could imagine loading a package, updating the shared state, &c, so that fewer package requests are duplicated. However, this will only work in toy examples that you might build in integration testing, but fall apart in actual production scenarios.

This is because a core assumption of package loading is that _the complete transitive closure of inter-package references is well-defined_. So packages abcd and efgh can be added to the participant, abcd depending on efgh, and you have no way to guarantee that you’re loading efgh first, so the load of abcd by itself will put the cache in an invalid state. That’s why whole multi-package deltas are fetched before trying to compute the cache structures.

### Suggested Fix

The first thing I would try is to [address this FIXME](https://github.com/digital-asset/daml/blob/2dd939ced365426a2fcdb6f22375124e1944519e/ledger-service/utils/src/main/scala/com/digitalasset/ledger/service/LedgerReader.scala#L31-L32). If that fixes it all by itself, great! If it doesn’t, that’s OK, it’s a prerequisite for the remainder.

[`global`](https://www.scala-lang.org/api/2.13.8/scala/concurrent/ExecutionContext$.html#global:scala.concurrent.ExecutionContextExecutor) probably feeds 256 extra threads for package service requests to all json-api requests. If we give _that_ traversal an `ExecutionContext` that won’t do that, we can globally limit the number of concurrent package service requests without implementing shared-state ourselves.

The problem is that `ExecutionContext` as a nullary typeclass is only suitable for one instance per program. By using [typed `ExecutionContext`s](https://github.com/digital-asset/daml/blob/2dd939ced365426a2fcdb6f22375124e1944519e/libs-scala/concurrent/src/main/scala/concurrent/package.scala#L11-L63), which already exist, we can define where we need this special `ExecutionContext`, and distinguish it from the _other_ `ExecutionContext` (the one that didn’t work by itself according to the above trial) by giving _that_ one a type argument as well.

Defining an `implicit ExecutionContext[LedgerReader]` alongside plain `ExecutionContext` will compile, _but will give you bad results, since the former will always win_. Instead, wherever there are two `ExecutionContext` in scope, _both_ must have a type argument, so neither wins, and the compiler makes you pick one where it’s ambiguous. You can either propagate the more specific constraint into one layer of function call at a time until everything compiles, or go all the way through the json-api codebase; I think only the former is called for.

I suggest starting with only `LedgerReader.loadPackageStoreUpdates` taking this new `ExecutionContext`. Later on you can expand to the primitive `LedgerClientJwt` helpers if it seems wise to have broader coverage of ledger API call throttling.

**Comment by dasormeter** [comment]
@stephencompall-DA We are seeing this package pounding affecting Hub production ledgers, with the addition that we have turned off canton participant rate limiting, and this pounding on http-json-api startup causes the  canton participant to run out of memory

Is anyone actively working on a resolution to this issue?

**Comment by S11001001** [comment]
@danielporterda @dasormeter Do you have any reproduction scenarios that _do not_ fit the pattern mentioned in the description in this ticket, i.e.

1. errors accompanied by (hopefully eventually) `INFO  com.daml.http.PackageService - new package IDs loaded` spam,
2. chiefly around json-api start time, _or_ after having uploaded DARs
3. and started a client that uses a whole bunch of requests right away like finance-app?

I have been focusing on this particular case, so please let me know if you have something that doesn't fit this pattern.

**Comment by danielporterda** [comment]
No. We believe Georg's issue encapsulates our failure mode completely.

**Comment by S11001001** [comment]
#16170 is a backport to 2.5.x.
