### ISSUE TITLE
Pretty-printing types in daml error messages

### ISSUE THREAD

**Issue by dylant-da** [digital-asset/daml#16011]
Comment: https://github.com/digital-asset/daml/pull/15999#discussion_r1063262169

**Comment by basvangijzel-DA** [comment]
Nice to have, can possibly be done in a day or two.

**Comment by dylant-da** [comment]
@samuel-williams-da `TcDaml.hs` should be the only file, to understand how it links into the rest of the compiler look at `TcErrors.hs` and `RdrHsSyn.hs`
