### ISSUE TITLE
createAndExercise fails

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#16023]
2.5.0

# Bug description

```
template T
  with
    p : Party
  where
    signatory p

    key p : Party
    maintainer key

    choice Cycle : ContractId T
      with 
        n : Int
      controller p
      do 
        let
          n1 = n / 2
          n2 = n - n1
        when (n1 > 0) do
          cid <- create this
          exercise cid Cycle n1
        when (n2 > 0) (createAndExercise this (Cycle n2))
```

generates error

```
  • Tried to exercise a choice ‘Cycle’ on template ‘T’ but no choice of that name exists on template
  ‘T’
  Choice ‘Cycle’ belongs only to the following types: template ‘T’
```

That is obviously contradictory.

# To reproduce

See code above.

# Expected behavior

Should work.

# Additional context

**Comment by bame-da** [comment]
It's actually just a bad error message. The problem is that I was missing a `void` to remove the return type inside the `when`.

**Comment by stefanobaghino-da** [comment]
@dylant-da Is this somehow good input for you?

**Comment by cocreature** [comment]
This looks like the issue Dylan already fixed in https://github.com/digital-asset/daml/pull/15999

**Comment by stefanobaghino-da** [comment]
If that's the case feel free to close this, @dylant-da. 🙇🏻‍♂️

**Comment by dylant-da** [comment]
Sorry I didn't notice that I hadn't closed this, closing now
