### ISSUE TITLE
Investigate space leak in test

### ISSUE THREAD

**Issue by dylant-da** [digital-asset/daml#16030]

**Comment by basvangijzel-DA** [comment]
@stefanobaghino-da  will try to provide more information from the customer that encountered this issue.

**Comment by dylant-da** [comment]
I came back to this again, still no obvious places for a space leak have shown up yet

**Comment by stefanobaghino-da** [comment]
@dylant-da The issue is unrelated to coverage, unlike initially mentioned (hence the change in title). The customer is experiencing growing memory pressure up to the point of receiving an OOM by adding tests while running the same version, which seems to indicate that each tests leaks some memory (as I would assume that after a test has run, any memory used by it can be reclaimed). Do you have a way of investigating whether that's the case by profiling the memory usage?

**Comment by stefanobaghino-da** [comment]
@dylant-da Is there any update on this?

**Comment by stefanobaghino-da** [comment]
The tests are being run using `daml test`.

**Comment by stefanobaghino-da** [comment]
Memory consumption seems to be correlated with the number of test cases, which seem to point at a memory leak with memory that goes unreleased in-between test cases being run.

**Comment by stefanobaghino-da** [comment]
Ideally we should profile the test runner to validate this hypothesis.

**Comment by stefanobaghino-da** [comment]
From @basvangijzel-DA in a separate conversation:

> The origin is a GHC error, see here:
> 
> https://github.com/digital-asset/ghc/blob/323dc6fcb127f77c08423873efc0a088c071440a/rts/win32/OSMem.c#L491
>
> The particular error within is a Windows OS paging error, and might not actually be caused by the system not having enough memory. If they for example are using a fixed page file size, you will very likely run into this problem. They should really try (to increase the page size to 1.5x RAM size)[https://learn.microsoft.com/en-AU/troubleshoot/windows-client/performance/slow-page-file-growth-memory-allocation-errors], or even better, let the OS manage the page file based on system needs.
>
> See for example the first answer here:
>
> https://answers.microsoft.com/en-us/windows/forum/all/the-paging-file-is-too-small-for-this-operation-to/e62356fd-5bae-4fdf-ad1c-0b2824ba8aa7

@basvangijzel-DA Both solutions (increasing the page file size to more than 1.5x the available memory and leaving it to the operating system) have been tried but neither worked.

**Comment by stefanobaghino-da** [comment]
@bame-da did some testing on his own and the script runner _seems_ to not have a problem reclaiming unused memory. The only thing I can think of is the compiler consuming memory linear to the number of tests. Not sure whether that makes sense or not, you definitely have a better understanding of the architecture.

**Comment by dylant-da** [comment]
The compiler and the runtime both appears to consume more memory when we generate more tests in source, but the growth in memory usage is negligible - in a file with 10000 tests, memory usage doesn't exceed 5MB when exercising one test, so other tests don't seem to cause as much issue.

I'll continue to test tomorrow

**Comment by dylant-da** [comment]
By building a series of large long-running tests, I've been able to find that they definitely accumulate memory in the JVM - now that we've found there is a leak, I'm working on finding the source and fixing it

**Comment by dylant-da** [comment]
Blocked until we get more info on whether our mitigations work

**Comment by dylant-da** [comment]
Closing as stale - if these sorts of issues come up again, we can recommend saving intermediate results via https://github.com/digital-asset/daml/pull/16928
