### ISSUE TITLE
damlc docs parse error for standard project

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#16046]
```
$ daml new --template=create-daml-app new-app
$ cd new-app
$ daml build

2023-01-12 12:15:59.09 [INFO]  [build] 
Compiling new-app to a DAR.

2023-01-12 12:15:59.87 [INFO]  [build] 
Created .daml/dist/new-app-0.1.0.dar

$ daml damlc docs .daml/dist/new-app-0.1.0.dar -o readme
File:     .daml/dist/new-app-0.1.0.dar
Hidden:   no
Range:    1:3-1:3
Source:   parser
Severity: DsError
Message:  .daml/dist/new-app-0.1.0.dar:1:3: error:lexical error at character '\ETX'
Error processing input from .daml/dist/new-app-0.1.0.dar
```

As reported by Julius William, docs crashes with a lexical error, even when using a fresh project, using the template create-daml-app. 

We should have a look at fixing this, and furthermore adding this as an automated test.

**Comment by akrmn** [comment]
`daml damlc docs` doesn't support `.dar` files as input, rather, it expects the project's `.daml` files (or, with the option `--input-format=json`, `.json` files obtained from previously calling `daml damlc docs --format=json` on `.daml` files). Sadly we don't have any documentation to point users to, so for now I've opened https://github.com/digital-asset/daml/issues/16047.
