### ISSUE TITLE
make sure to reject null transactions in PostgresLedgerDao

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#161]
see https://github.com/DACH-NY/daml/blob/9865bbebc2364d35dbf0e8927be4f8a366ef03b1/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala#L174

**Comment by stefanobaghino-da** [comment]
This issue refers to code that is no longer on the codebase. I double checked against the current code and this piece in particular does not appear in the files that took `PostgresLedgerDao`'s place. @gerolf-da feel free to triple check and re-open if you think there's an issue I missed.
