### ISSUE TITLE
Read DAR manifest as per the Manifest Specification

### ISSUE THREAD

**Issue by akalburgi** [digital-asset/daml#1617]
In visualization code reading a manifest file can result in a failure as multiline DALFs line is not taken into account. 
Specification at https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Name-Value_pairs_and_Sections

**Comment by neil-da** [comment]
Ideally I want the module in the DAML LF package that reads/writes a DAR, and use that everywhere.

**Comment by leo-da** [comment]
there is one called: DarReader :)
and also DarManifestReader. not sure what writer supposed to do.

**Comment by akalburgi** [comment]
fixed by https://github.com/digital-asset/daml/pull/2207
