### ISSUE TITLE
Issue setting up dev environment on RHEL7

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#162]
I ran into numerous issues with nix trying to set up the dev environment on a new RHEL7 system while testing a tool. According to @jonas-chevalier-da RHEL7 disables user namespaces, which Nix depends on for sandboxing.

In order to fix this issue I first had to add `sandbox = false` into `/etc/nix/nix.conf` to install nix, then added the same line into `~/.config/nix/nix.conf` for it to run in the dev environment.

There were further errors still when I first tried to build due to Haskell not being installed, which caused something to invoke git with a flag it didn't recognize. Unfortunately I ran out of time to look further.

Some error output below below:

```
installing 'nix-2.2.1'
error: cloning builder process: Invalid argument
error: unable to start build process
install: unable to install Nix into your default profile
```

**Comment by cocreature** [comment]
Nobody uses rhel internally and nobody externally has complained about this so closing.
