### ISSUE TITLE
Contract keys are broken in Scenarios

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1623]
I'm working on a DAML model for group chats:
https://gist.github.com/bame-da/7eb238eb87d8e20d6362948c22a50bed

The `MessageIndex` contract has a key, which goes wrong in two ways:

1. At the end of the `second_post` scenario, I have two active `MessageIndex` contracts with the same key
2. The reason we even *try* to create the second index is that the `lookupByKey` in `GetOrCreateIndex` doesn't work.

**Comment by bame-da** [comment]
Not surprisingly, this is reproducible in Sandbox following exactly the steps from the scenario.

**Comment by gerolf-da** [comment]
I'm fairly confident that I found the cause of this bug: `hashCode` and `equals` in `ImmArray` violate the contract that the hash codes of 2 objects need to be the same, if `o1.equals(o2) == true`.

**Comment by gerolf-da** [comment]
In addition to that, `FrontStack` also didn't override and implement `hashCode`.

**Comment by bame-da** [comment]
The latter is the more likely culprit, I think. That would explain why I only ran into this when using a list inside my keys.

**Comment by gerolf-da** [comment]
Yes, the issue regarding the contract keys is probably rooted in FrontStack, because we are not slicing the record fields `ImmArray`.
