### ISSUE TITLE
npm install on create-daml-app fails with npm=9.3.1, nodejs=18.14.0

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#16258]
Running npm install on create-daml-app (after generating the files is) fails because it cannot find a file:

```
[nix-shell:~/create-daml-app/ui]$ npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/moritz/create-daml-app/ui/node_modules/@daml.js/40f452260bef3f29dede136108fc08a88d5a5250310281067087da6f0baddff7/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/moritz/create-daml-app/ui/node_modules/@daml.js/40f452260bef3f29dede136108fc08a88d5a5250310281067087da6f0baddff7/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moritz/.npm/_logs/2023-02-07T14_53_57_699Z-debug-0.log
```

I think it may be an NPM 8 vs NPM 9 issue.

You can repro with 
```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/e75e7234275c413d038341764a3426245e0fb174.zip nix-shell -p nodejs-18.x
```

**Comment by basvangijzel-DA** [comment]
This is also a problem on Windows (and our Windows ad-hoc machines).

NPM version: 9.3.1
Node version: 10.4.0

**Comment by basvangijzel-DA** [comment]
It is indeed likely npm 9 that is at fault. When downgrading to the things that come with the 10.3.0 release:

NPM version: 8.19.3
Node version 10.3.0

**Comment by garyverhaegen-da** [comment]
This seems relevant: https://github.com/nodejs/node/issues/46542.

Running
```
npm install --install-links false
```
works for me on both macOS and Windows. From what I can gather this used to be the default but they changed it in (Node) 18.14; there seems to be a chance they'll reverse that, so I'm not sure what the appropriate action is on our side.

Updating the instructions seems like a good approach as it should be harmless either way (i.e. whichever default they end up sticking with, explicitly setting the value should work).

**Comment by pragmaxim** [comment]
`npm install --install-links false` actually works on Linux too with : 
```
  npm: '9.4.0',
  node: '19.6.1',
```
There is a lot of great daml examples out there but they are hard to run due to nodejs version issues.

**Comment by pragmaxim** [comment]
well, `npm start` then fails as `node_modules/@daml.js/` is empty :-/

**Comment by garyverhaegen-da** [comment]
> well, `npm start` then fails as `node_modules/@daml.js/` is empty :-/

I don't have a Linux environment handy right now, but that shouldn't be the case. Can you double-check you have run `daml codegen js` before `npm install`?

**Comment by pragmaxim** [comment]
>I don't have a Linux environment handy right now, but that shouldn't be the case. Can you double-check you have run daml codegen js before npm install?

Yes I did, it ends up with the same error as in https://github.com/digital-asset/daml/issues/16258#issue-1574499086

I've played with a bunch of daml projects and they all worked fine on Node version `16.16.0`. Making them work with `18.14.0+` is beyond my frontend skills.

**Comment by garyverhaegen-da** [comment]
It looks like it got fixed on the node side - at least for me the GSG now works out of the box (i.e. without having to add the `--install-links` flag) for 2.5.5 and 2.6.0 (both unreleased as of yet, but still) on Node 18.14.2 (npm 9.5.0).

**Comment by garyverhaegen-da** [comment]
Closing as this is fixed as far as I can tell. Should anyone encounter this issue again please open a new ticket for it.
