### ISSUE TITLE
Codegen should generate decoder instances of CreateContract input

### ISSUE THREAD

**Issue by bartfaitamas** [digital-asset/daml#163]
The `fromValue(Record args)` method on contract templates is not enough, because it does not checks if the TemplateID matches. There should be a Decoder `decoder(CreatedContract)`, which checks for TEMPLATE_ID. What we had, and caused a hard to catch but is code like this:
```java
Record args = createdContract.getCreateArguments();
if (createdContract.getTemplateId().equals(SettlementInstructionNotification.TEMPLATE_ID)) {
   return SettlementInstruction.fromValue(args);
```
It was hard to catch the SettlementInstuciton vs SettlementInstucitonNotification mismatch.

**Comment by stefanobaghino-da** [comment]
@bartfaitamas @gerolf-da Is this fulfilled at this point?
