### ISSUE TITLE
Daml assistant throwing an error when trying to install the latest SDK

### ISSUE THREAD

**Issue by rexng-da** [digital-asset/daml#16301]
# Affected Daml version

2.5.3

# Bug description

`daml install latest` threw an error:

```
daml: Failed to parse SDK version from https://docs.daml.com/latest
  context: Installing the SDK.
  details: endOfInput
```

# To reproduce

Run `daml install latest` in a terminal

# Expected behavior

The latest Daml SDK should be installed. Or if it is already installed, a no-op message should be returned.

# Additional context

`daml install latest` seems to send a request to https://docs.daml.com/latest, which at the time of writing, returns the latest Daml SDK version (`2.5.3`) successfully.

**Comment by garyverhaegen-da** [comment]
This should be fixed now, sorry about that.

Please close the ticket if you can confirm it works for you now.

**Comment by rexng-da** [comment]
Thanks @garyverhaegen-da. Can confirm it works now.
