### ISSUE TITLE
Table and Transaction views from Daml Studio in Daml Assistant CLI

### ISSUE THREAD

**Issue by drdo** [digital-asset/daml#16310]
### What is the problem you want to solve?
The table and transaction views available for Daml Scripts in Daml Studio are extremely useful but
are currently only available if one uses vscode.

I would like them to be available via Daml Assistant as well.

This would be major setup towards being able to use other editors for Daml productively.
It's already possible to get most of the functionality via the Daml language server.

### What is the solution you would propose?
Provide the same table and transaction view available in Daml Studio "Script results"
via Daml Assistant by running the scripts in the existing mocked ledger implementation.

### Describe alternatives you've considered
I  don't see any convenient alternatives.

Writing a program to launch a Daml sandbox,
run the script and gather all the contracts on the ledger via the Ledger API
for display should be possible.

**Comment by dylant-da** [comment]
Hiya, thanks for the suggestion, we're working on this now

**Comment by dylant-da** [comment]
Hi @drdo , for the time being we've added two flags to `daml test`

```
--table-output <table output dir>
--transactions-output <transactions output dir>
```

`daml test` then places the HTML source for the table and transaction output for each test into `<table output dir>/table-<test-name>.html`, which can then be viewed in browser or postprocessed another way (output onto command line via `cat`, extracted with XML).

**Comment by drdo** [comment]
Hey @dylant-da, this would definitely help!

I'm wondering though if there isn't also some kind of intermediate representation before rendering html that could be easily exported in a format more ergonomic for programmatic consumption (e.g. JSON).

**Comment by dylant-da** [comment]
The test results are encoded in a protobuf, but some postprocessing is necessary to extract all the relevant information, and then a fair bit more to write it out in a "human-readable" format.

Determining and serializing to a JSON schema will take a bit of time - we can create an issue on the backlog to address this, and in the meantime write HTML to give you some reasonable access to the studio results?

**Comment by drdo** [comment]
Sure, thanks.

**Comment by RobinParmentier** [comment]
Hey,
Have these changes been included in release 2.5.5.?
If not, will they be included in future releases?

**Comment by dylant-da** [comment]
It looks like it didn't make the upcoming release, I'm afraid, but it should make it in the next one. For the record, would you also be interested in a serialized format, or do you prefer the HTML output?

**Comment by RobinParmentier** [comment]
Ok, thank you for the info.
For my purposes I would prefer the HTML output, but either one could work.
