### ISSUE TITLE
upgrade tooling

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#1636]
Upgrading
-------------
Upgrading of a DAML system running package1 is done by loading the next version package2 and a generated upgrade package 'update'. The upgrade package contains nonconsuming choices for each contract template type that take as input contract instances of package1, archive them and create a contract instance of package2 of the converted data. For example for the module `Foo` contained both in package1 and package2 we create in the upgrade package:

```haskell
daml 1.2
module Foo where
import "package1" Foo qualified as A
import "package2" Foo qualified as B
import DA.Upgrade


template FooUpgrade
    with
        op : Party
    where
        signatory op
        nonconsuming choice Upgrade: ContractId B.Foo
            with
                inC : ContractId A.Foo
                sigs : [Party]
            controller sigs
                do
                    d <- fetch inC
                    assert $ toSet sigs == toSet d.signatory
                    create $ conv d
```

These upgade modules are generated from code in package1 and package2. We try to generate upgrade choices for all data template data types that are present and named the same in package1 and package2. The `conv` function is defined in DA.Upgrade and uses DA.Generics to derive conversion functions between isomorphic data types. Conversions that can not be generated automatically lead to a type-check error and the user needs to implement them and add them manually.

Implementation plan:
----------------------------

- [x] Add Generics implementation to DAML compiler
- [x] Add DA.Upgrade module to daml-stdlib
- [x] Generate Generic instances for all data types contained in a DAML module? Answer: no, we get 10% percent longer compile times in single module projects.
- [ ] Implement 'migrate' command for daml assistant that generates upgrade modules, where both packages are loaded from source.
- [ ] Improve 'migrate' command for daml assistant such that it can read package1 and generate generic instances just from the contained .dalf files (because it might have been compiled with a different compiler)

**Comment by cocreature** [comment]
This has morphed into various other issues so I’m closing this.
