### ISSUE TITLE
Extend daml with scaffolding actions

### ISSUE THREAD

**Issue by carlpulley-da** [digital-asset/daml#16362]
Whilst working on the Rosta-app, I noticed that it was more painful than necessary to add react code to an ow pure Daml project.

`daml create create-damp-app` allows users to quickly generate a template project and then play/interact with it.

What might be helpful for end users is if we had something like a `daml scaffold add-react` extension to the daml CLI? I'd expect such a CLI action to:
- add relevant folders to a project for supporting a react UI (e.g. `ui/src/components`, `ui/public`)
- add `daml.svg`, `favicon.png`, `index.html`, `manifest.json` to `ui/public`
- add `App.tsx`, `App.test.tsx`, `LoginScreen.tsx` and `MainScreen.tsx` to `ui/src/components`
- add `config.ts`, `Credentials.ts`, `index.css`, `index.tsx`, `react-app-env.d.ts` and `setUp.js` to `ui/src`
- add `package.json` and `tsconfig.json` to `ui`
- run codegen for the current Daml project
- update `daml.yaml` with `codegen` and `init-script` entries

Doing this would allow a user to very seamlessly move from a Daml only project to a Daml with react UI project (with the ability to also deploy to Daml-Hub).

Currently, users have to checkout an existing template project and then copy and paste folders/files across (with some hacking).

**Comment by basvangijzel-DA** [comment]
Let's see what happens with the ref app project, if this is still needed.

**Comment by carlpulley-da** [comment]
Closing this ticket as roster-app is now deprecated
