### ISSUE TITLE
upgrade tooling - plan 2

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#1637]
Upgrading - Plan 2
-------------------------
This is related to #1636 . Here the plan is to implement a daml assistant command that takes as input package1 and package2 and creates package3 that is essentially the package1 plus the difference of package2 and package1 plus upgrade templates:

```
pkg3 = pkg1 + (pkg2 - pkg1) + upgradeTemplates
```

Here, pkg2 can only contain data defintions from pkg1 that are extended such that the old data definitions can be embedded.

**Comment by neil-da** [comment]
Idea would be that this fails if you have any templates which have the same name but aren't extended only by adding optional fields.

**Comment by cocreature** [comment]
This has morphed into various other issues so I’m closing this
