### ISSUE TITLE
Review ledger API server gRPC status codes and input validation

### ISSUE THREAD

**Issue by dajmaki** [digital-asset/daml#1638]
As part of PR #1613 we needed to change some gRPC status codes from INVALID_ARGUMENT to NOT_FOUND and to relax validation of some input fields.

We need to follow up with reviewing what gRPC status codes should be returned where and to make sure they're tested and they make sense (e.g. the eventId validation should return INVALID_ARGUMENT instead of NOT_FOUND, but this was difficult to make work with the daml-on-x implementation).

Additionally we should make sure that the inputs are properly validated in the backends (e.g. the SandboxIndexAndWrite service should further validate transaction_id and event_id fields).

**Comment by gerolf-da** [comment]
[`TransactionServiceRequestValidator`](https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-common/src/main/scala/com/digitalasset/ledger/api/validation/TransactionServiceRequestValidator.scala#L74) should return `OUT_OF_RANGE` instead of `INVALID_ARGUMENT`.

**Comment by gerolf-da** [comment]
For reference: [gRPC Status Codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)

**Comment by stefanobaghino-da** [comment]
> [`TransactionServiceRequestValidator#offsetIsBeforeEndIfAbsolute`](https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-common/src/main/scala/com/digitalasset/ledger/api/validation/TransactionServiceRequestValidator.scala#L74) should return `OUT_OF_RANGE` instead of `INVALID_ARGUMENT`.

Is this the only relevant change to apply?

**Comment by gerolf-da** [comment]
No, that's specifically one that @meiersi-da stumbled upon, but then decided to take care of separately in #6842.
