### ISSUE TITLE
[00004377] Referencing a template-level bind to 'signatory this' in a choice body, makes the Scenario service fail in Daml Studio

### ISSUE THREAD

**Issue by matevarga-da** [digital-asset/daml#16509]
# Affected Daml version

2.5.5

# Bug description

Referencing a template-level bind to 'signatory this' in a choice body, makes the scenario service to consume a lot of resources, then crash eventually. Running the same script with the script runner does not produce any issues.

# To reproduce

Create a daml project that contains a template like this:

```
module TestThis where

import Daml.Script

template TestThis with
   sig: Party
  where
    signatory sig
    let sign = signatory this
    nonconsuming choice Something : ()
      controller sig  
      do
        debug $ sign
        pure ()

testthis : Script ()
testthis = do
  alice <- allocateParty "alice"
  t1 <- submit alice do 
    createCmd 
      TestThis with 
        sig=alice
  pure()

```
# Expected behavior

Run the script successfully.

# Additional context

More details on the original support case raised: [00004377](https://digitalasset1.lightning.force.com/lightning/r/Case/5004x00000U5mkBAAR/view)

**Comment by cocreature** [comment]
this is a dup of https://github.com/digital-asset/daml/issues/13470 I believe.
