### ISSUE TITLE
Manage and track Trigger Ledger command submissions

### ISSUE THREAD

**Issue by carlpulley-da** [digital-asset/daml#16537]
Currently, when trigger code performs a command submission, we rely on the Daml user code to track, manage and retry command failures. Unfortunately the Daml code has no visibility of the underlying Ledger submission fields:
- application ID - this might be used to identify a particular trigger instance that submitted the command?
- submission ID - this might be used to manage/track submission retries at some future point in time?

and so the user code has a high implementation burden should it try to do any of this.

Reference: 
- https://docs.daml.com/app-dev/command-deduplication.html

**Comment by basvangijzel-DA** [comment]
We don't want to do automatic retries (per discussion)

**Comment by carlpulley-da** [comment]
Closing this ticket as triggers are now deprecated
