### ISSUE TITLE
-package ghc missing on da-ghci //compiler/haskell-ide-core:haskell-ide-core-demo

### ISSUE THREAD

**Issue by aherrmann-da** [digital-asset/daml#1656]
```
da-ghci //compiler/haskell-ide-core:haskell-ide-core-demo
```
fails with 
```
    Could not load module ‘Platform’
    It is a member of the hidden package ‘ghc-8.6.5’.
    You can run ‘:set -package ghc’ to expose it.
 ```
`-package ghc` (or equivalent) is missing from the generated ghci wrapper. Presumably, because `ghc` is a core-package and is treated specially by Hazel.

**Comment by neil-da** [comment]
Would also be great if `da-ghcid` could pass GHC flags on to `da-ghci`, just like `da-ghci` already can.
