### ISSUE TITLE
Document usage of trigger simulation code

### ISSUE THREAD

**Issue by carlpulley-da** [digital-asset/daml#16681]
With the merging of https://github.com/digital-asset/daml/pull/16551, we will need to document how this code can be used to identify performance issues in Daml trigger code.

**Comment by basvangijzel-DA** [comment]
@samuel-williams-da would be happy to try triggers out + docs and see where the gaps are.

**Comment by carlpulley-da** [comment]
Closing this ticket as triggers are now deprecated
