### ISSUE TITLE
Fix bazel warnings

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#167]
DEBUG: /home/leos/.cache/bazel/_bazel_leos/93a0419858f716ca84fdda0fa1969d7d/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
DEBUG: /home/leos/.cache/bazel/_bazel_leos/93a0419858f716ca84fdda0fa1969d7d/external/io_bazel_rules_scala/scala/private/common.bzl:64:13: ignored dependency, has no JavaInfo: <merged target //daml-foundations/daml-tools/da-hs-damlc-app:da-hs-damlc-app>

**Comment by cocreature** [comment]
Hasn’t come up within the last year so closing.
