### ISSUE TITLE
Feature request / DAML Studio: Don't revert back to table view on changes

### ISSUE THREAD

**Issue by sofusmortensen** [digital-asset/daml#1675]
If you have chosen the "transaction view" for showing the result of your scenario, and you make a change that automatically reruns the scenario, the view is reverted back to "table view". 
I don't think the user would expect that. I find it more convenient to stick to the chosen view.

**Comment by cocreature** [comment]
Thanks for the bug report! I fully agree that the current behavior is undesirable. I’ll look into a fix.
