### ISSUE TITLE
Add `key` to all events

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#1680]
The contract key has been added to `CreatedEvent`s on the Ledger API ([here](https://github.com/digital-asset/daml/pull/1586)). It could be worth it to have them on `ArchivedEvent`s and `ExercisedEvent`s as well.

/cc @bame-da @francesco-da for your thoughts

**Comment by bame-da** [comment]
I think so, at least on `ArchivedEvents`. Otherwise I still have to index my contract store with CIDs to be able to process `ArchiveEvents`.

**Comment by bitonic** [comment]
@stefanobaghino-da sounds very sensible, feel free to go ahead with this.

**Comment by stefanobaghino-da** [comment]
@dajmaki You're probably interested in this.

**Comment by dajmaki** [comment]
Thanks. I'm working on adding contract key to the exercise node (NodeExercises, and in transaction.proto). I need this for #1456. Once this lands (hopefully tomorrow), it should be fairly straightforward to add it to ledger API. Note this is just the key without the maintainers (which would change the interpreter, doable but much more work).

**Comment by stefanobaghino-da** [comment]
@dajmaki Have you been able to make progress?

**Comment by gerolf-da** [comment]
Closing this as it hasn't been actively requested and seems to be more of a convenient feature.
