### ISSUE TITLE
establish the relationship between flexible controllers and observers, and add tests

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#171]
with the introduction of flexible controllers the controllers of a given contract cannot be determined statically, since they might depend on the choice arguments.

formally we define the contract stakeholders as `signatories \cup observers`. moreover, the observers of a template are defined directly in the DAML-LF template definition. obviously the observers are parametrized over the template argument.

however:

1. it's not very clear how the observers are currently computed, given that the controllers are not computable from the template argument alone
2. if flexible controllers are _not_ observers, this means that they are not stakeholders...
3. ...which means that they should not see contract which they are able to exercise on the ledger api, which definitely feel fishy. so maybe we actually have (or should have) a guarantee that all possible flexible controllers are part of the observer set
4. whatever the outcome of the 3 points above is, we should test everything in the ledger API integration tests.

cc @oggy- @meiersi-da @martin-drhu-da

**Comment by bame-da** [comment]
Note that my suggestion was to call the union of signatories and controllers "authorizer" and indeed there is a matching definition of "authorizing party" in the docs. To keep things simple, we ultimately agreed to change terminology, though

**Comment by bitonic** [comment]
I've now added tests for this, see https://github.com/digital-asset/daml/blob/e36e1074e090a1b7ac5cee9c4379a1025cf0fafc/ledger/ledger-api-integration-tests/src/test/itsuite/scala/com/digitalasset/platform/tests/integration/ledger/api/WitnessesIT.scala . These test validate the expected semantics described here.
