### ISSUE TITLE
Non-consuming choices and observers: verify that sandbox respects the ledger privacy model

### ISSUE THREAD

**Issue by oggy-** [digital-asset/daml#172]
The ledger privacy model is defined through projections:
https://docs.daml.com/concepts/ledger-model/ledger-privacy.html#da-model-projections
notably, the notion of an "informee". The model says that observers of a contract are not informees on non-consuming exercise actions on that contract, unless they are actors. @robin-da also had an internal blog post on this.

The Sandbox should respect the ledger model in this regard.

**Comment by stefanobaghino-da** [comment]
@oggy- is there a specific issue about this that it's not covered by our tests?

**Comment by oggy-** [comment]
@stefanobaghino-da I suspect that it didn't used to be covered (and was possibly buggy?). IIRC I created the question after a discussion with Francesco back then, where we decided we needed to test it. 

I'm not sure where tests like this currently live. Do you have any specific suspects that think already cover this?

**Comment by stefanobaghino-da** [comment]
After a cursory look I believe this may be covered by [this conformance test](https://github.com/digital-asset/daml/blob/27dcb1f2921890f3f500115aa9e9cf2b5960ce0f/ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/tests/Witnesses.scala) (which is backed by [this DAML model](https://github.com/digital-asset/daml/blob/27dcb1f2921890f3f500115aa9e9cf2b5960ce0f/ledger/test-common/src/main/daml/Test.daml#L516-L542)), in particular the parts inspecting the `nonConsumingTree`.

**Comment by oggy-** [comment]
Thanks for finding these. Yep this issue looks covered, will close now.

**Comment by stefanobaghino-da** [comment]
Thanks for double checking!
