### ISSUE TITLE
Cleaning up license files in JARs

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#17285]
Assigning to @basvangijzel-DA for prioritization.

The SDK tarballs include the expected LICENSE.txt file at their root, which is great. The situation is less great for the JAR files produced by this repo, however:
- `daml-sdk.jar` contains the expected license file at `/LICENSE.txt`, but also a bunch of other license files, presumably from dependencies, both at the root and under `META-INF/`.
- Same applies to `http-json-ee.jar`, `trigger-service-ee.jar`, `trigger-runner.jar`, and `daml-script.jar`.
- The `oauth2-middleware.jar` file has the expected Apache 2 license at `/LICENSE.txt`, but also another copy at `/LICENSE`, another one at `META-INF/LICENSE`, and the MIT license at `META-INF/LICENSE.txt`.

We should strive to have only one LICENSE file in each JAR, and ideally the correct one.

**Comment by samuel-williams-da** [comment]
All licenses of dependents should be included in a NOTICES file, which is also missing

**Comment by garyverhaegen-da** [comment]
> All licenses of dependents should be included in a NOTICES file, which is also missing

Good catch. Note that we are _generating_ said [NOTICES](https://github.com/digital-asset/daml/blob/main/NOTICES) file, at least, so hopefully adding it shouldn't be too difficult.

**Comment by samuel-williams-da** [comment]
I should also note that I am reproducing this by building the fat jars - so `bazel build ?_deploy.jar`. I'm unfamiliar if the release process makes further changes to these artefacts.

**Comment by garyverhaegen-da** [comment]
As far as I'm aware there is no change to the JAR files in the rest of the pipeline.

**Comment by garyverhaegen-da** [comment]
There are still a few extra LICENSE files in the 2.7.1 artifacts. (At least as of `2.7.1-rc2`, but there won't be time to make any further changes on 2.7.1.)

**Comment by garyverhaegen-da** [comment]
2.8.1 artifacts look good to me license-wise.
