### ISSUE TITLE
Countdown ranges don't work as expected

### ISSUE THREAD

**Issue by mjhopkins-da** [digital-asset/daml#1730]
```haskell
testRanges : Scenario ()
testRanges = do
  [1 .. 20]   === [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
  [0,4 .. 20] === [0,4,8,12,16,20]
  [20,19..0]  === [20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0] -- Failure, expected [19,18] === [20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0]
  [20,18..0]  === [20,18,16,14,12,10,8,6,4,2,0] -- Failure, expected [18,16] === [20,18,16,14,12,10,8,6,4,2,0]
```

This also fails:

```
--   [0.0,0.25 .. 1.0] === [0.0,0.25,0.5,0.75,1.0] --  No instance for (Enum Decimal)
```

but I imagine this might have been a conscious choice - is that right? An `Enum` instance could be handy but rounding issues can be tricky.

**Comment by hurryabit** [comment]
I will look into the count down ranges when I'm back in the office later this week.

Rounding should not be an issue for the `Enum Decimal` instance. If @neil-da doesn't object I'll add it.

**Comment by ndmitchell** [comment]
I wrote this code so was planning to take a look tomorrow, if you don't beat me to it. No problem with Enum Decimal - I welcome it.

**Comment by mjhopkins-da** [comment]
Awesome - thanks!

**Comment by hurryabit** [comment]
I'm not convinced we should have `instance Enum Decimal` anymore. What would, say, `succ 1.5` be?

**Comment by neil-da** [comment]
Agreed, `Enum Decimal` is a bad idea - hadn't thought of that
