### ISSUE TITLE
Failure to use arbitrary_canton_sha with patched canton jars

### ISSUE THREAD

**Issue by carlpulley-da** [digital-asset/daml#17339]
When `CantonFixture` based tests use the patched Canton jar files (e.g. by setting `devMode` to be true) and a Canton commit hash is specified in `arbitrary_canton_sha`, then Canton is not rebuilt. This results in the wrong Canton jar file being patched.

This issue impacts cross cutting changes between Daml and Canton (particularly those that do not impact engine and archive submodules).

The current work around to this issue is to use the Canton CircleCI job to manually publish a snapshot version of Canton. This published snapshot can then be used in the file `canton_dep.bzl`.

**Comment by basvangijzel-DA** [comment]
Not needed if you publish your own Canton snapshot.
