### ISSUE TITLE
Remove Daml Repl

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#17373]
Proposer: Canton Ledgers Team
PM Approver: Bernhard Elsner
Engineering Approver: Ratko 

Summary
Console that allows you to interact with a Daml ledger using Daml expressions. Removing it simplifies our build a lot as it breaks the cyclic dependency between compiler and Canton. The Repl has not really found users that use it and has never made it beyond experimental. The REPL is based on the Haskell bindings which are broken and would need additional investment.

Specific Changes
rm -rf repl

Impact and Migration
Few users
Interactive CLI for ledger will be Daml Shell

**Comment by akrmn** [comment]
Must happen after #17374

**Comment by moisesackerman-da** [comment]
Done in https://github.com/digital-asset/daml/pull/18648
