### ISSUE TITLE
Navigator Party dropdown list missing inside a Map

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#17391]
While Daml Navigator nicely shows a dropdown list for an input for Party IDs, one has to manually copy+paste the Party ID in a Map structure, because the dropdown list is missing.
Reproduce with:

```
template T with
    p: Party      -- Navigator nicely shows a dropdown
    m: Map Party Int  -- dropdown list is missing
  where
    signatory p
```

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
