### ISSUE TITLE
Sandbox ports are inconsistent

### ISSUE THREAD

**Issue by gleber-da** [digital-asset/daml#174]
It looks like ports used by Sandbox are inconsistent.

If you run

    bazel run //ledger/sandbox:sandbox-binary -- $PWD/bazel-bin/ledger/sandbox/Test/com/digitalasset/Test/0.1/Test-0.1.dar

it starts at port 6865

If you run

    bazel run //ledger/sandbox:sandbox-binary -- --help

it tells that the default port is 8080

If you create `da new quickstart`, cd into it and next do

    da sandbox

it starts on port 7600.

Documentation at https://docs.daml.com/tools/sandbox.html suggests that it will use port 8080. In other places in the documentation I see both 7600 and 6865 mentioned.

**Comment by stefanobaghino-da** [comment]
This ticket is no longer valid, closing.
