### ISSUE TITLE
Unify test utilities used by the API integration tests

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#1746]
All tests rely on Test.dar having simple templates, so we can create nice limited API to generate test data. They could be published via the `LedgerContext` in cohesion with the fixtures. 

common tasks which would worth standardising:

- generating commands
    - random command ids (application ids), latter should be the same for the test suite
    - log them so we can trace them
    - expose simple factories for all the parameters of a create and exercise

- submitting commands 
    - via both low and high level services 
    - they should be just functions returning a Future with the transactionId (in case of high level)
- have a factory for filters
- Reading transactions
- Reading completions

**Comment by stefanobaghino-da** [comment]
Superseded by #2282. Probably worth having a second look at infrastructure needed by the integration tests after all tests relevant to the Ledger API have been ported over to the new tool.
