### ISSUE TITLE
Add MAP_FROM_LIST to DAML-LF

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#1753]
We expose a function
```haskell
TextMap.fromList :: [(Text, a)] -> TextMap a
```
in DAML and use it many other functions, like `TextMap.map`, as well. Currently, it is implemented as a fold over the list calling `TextMap.insert` for each element. This is not particularly efficient. Given how important this function is, we should provide a primitive for it in DAML-LF.

**Comment by bitonic** [comment]
Probably sensible, but not very urgent -- it's inefficient just because it's not a primitive, but the complexity would be the same.

**Comment by neil-da** [comment]
I'm inclined to wait until we have profiling showing its a bottleneck. Every additional primitive is going to have a much higher cost if we ever have two runtimes.

**Comment by remyhaemmerle-da** [comment]
We will not extend TextMap until further notice.
