### ISSUE TITLE
Multi-ide support for package-less modules

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#17575]
With the new multi-ide support, creating new modules (before saving them) will not have a package assigned, and as such, will not receive intelligence in the IDE.
The ideal solution to this is to create a "generic" subIDE, running without any real modules or package name, which handles the requests for files like this. This ensures that you aren't able to import modules that aren't generic until you have this file in a package which includes packages via the daml.yaml, but still gives you some amount of support.

**Comment by basvangijzel-DA** [comment]
@samuel-williams-da 
I think this one is done?

**Comment by samuel-williams-da** [comment]
Done but not merged :)
