### ISSUE TITLE
Update multi-package.yaml discovery in multi-ide

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#17578]
Pending review from Curtis, update the multi-package.yaml discovery logic for the IDE to match as describes [here](https://docs.google.com/document/d/1WtKAzfRVJGB1rkbgs3tWcPKvHPnFPJTGdW-TwQdvPng/edit?usp=sharing)
We will formalise the requirements directly in the ticket once we get the go-ahead for this behaviour.

**Comment by basvangijzel-DA** [comment]
Has this been done, and if not, 2.10 I assume?

**Comment by samuel-williams-da** [comment]
Superseded by #19079
