### ISSUE TITLE
daml.yaml sdk version broken for snapshots

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#17670]
Currently, using the `sdk` field in the daml.yaml to install a 2.8 snapshot is broken.
This is a result of the release/sdk version split.
In order to install an sdk, we need the release version. The get-daml script and `daml install` have both been updated to achieve this behaviour.
Sadly however, the daml.yaml sdk-version has not.

This ticket is to update that field to use the same release resolution logic implemented in `daml install`.
Following this, you'll also need to update:
- daml.yaml generation, as part of `daml new`, `daml create-daml-app` and `daml init`, should generate a daml.yaml with the release version, not the sdk version, which can be derived from the sdk install path.
- `daml version` should list release versions, not sdk versions.

This needs fixing ASAP

**Comment by dylant-da** [comment]
Progress here: https://github.com/digital-asset/daml/pull/17682

**Comment by dylant-da** [comment]
First successful build working :tada:
