### ISSUE TITLE
Transaction service streaming from Ledger_Begin gets slower over time

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1774]
The cost of streaming transactions from Ledger_Begin should be linear in the number and size of the transactions streamed. In actual fact it appears to get slower over time due to heartbeat events that get read from the DB and filtered as part of stream processing.

We should be a bit more clever about this and e.g. filter out the Heartbeat events at DB level.

FYI @gerolf-da @da-tanabe

**Comment by gerolf-da** [comment]
I started working on it in branch [1774-efficient-transaction-streaming](https://github.com/digital-asset/daml/tree/1774-efficient-transaction-streaming).

**Comment by stefanobaghino-da** [comment]
After the participant index schema redesign and the recent contributions by @leo-da and @gerolf-da this ticket has probably been addressed (as per its original description). I'm moving this to the scalability milestone.

I would suggest either closing this and open more fine grained tickets based on recent findings or use this ticket as a better refined item to track progress in this regard. @gerolf-da can you take a couple of minutes for this, please?

**Comment by gerolf-da** [comment]
Agreed, @stefanobaghino-da. Closing this, as the heartbeat problem has been solved by removing heartbeats altogether.
