### ISSUE TITLE
Sandbox performance regression in versions 100.11.X

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#178]
While upgrading a large application from sandbox 6.0.0 to a newer version (current target: 100.11.29) we observed that integration tests (involving sandbox, an application, and a special test driver) need much longer to run than before.

I will try to find out precisely which version introduced the regression, and whether it is really caused by sandbox performance (it may also be caused by other components, the upgrade I have tried is global) but reporting it now.

**Comment by jberthold-da** [comment]
Unfortunately not at the previous speed with the proposed change, and I am seeing many exceptions `RejectedExecutionException: event executor terminated`

**Comment by francesco-da** [comment]
this seems to still be an issue, reopening.

**Comment by francesco-da** [comment]
the core issue here is that tearing down the netty server takes a while -- between 1 and 2 seconds. i thought that me and @gaboraranyossy-da had fixed it by specifying different parameters to `shutdownGracefully` here: https://github.com/digital-asset/daml/blob/dc273159eb37047baea519134ad860a59d04af96/ledger/sandbox/src/main/scala/com/digitalasset/ledger/server/LedgerApiServer/LedgerApiServer.scala#L273 .

but apparently we have not -- in the tests privately provided to me by @jberthold-da it still often takes up to 2 seconds.

i suspect this is going to be tough to fix without delving into netty internals more that we have done already. an alternative solution would be to reset _without_ restarting the server, but then the semantics for that would be even trickier.

note that before the reset service was faster but racier -- it'd often hang up in our tests.

**Comment by francesco-da** [comment]
@jberthold-da btw, it is likely that these delays are because there are dangling connections to the server. you should make sure that there are _not_ while calling the reset service.

in the meantime, i'll make the timeouts shorter, which will forcefully terminate the server even if there are still dangling connections, which should ameliorate the immediate performance issues.

**Comment by francesco-da** [comment]
i also noticed something else in the tests provided by @jberthold-da : even if we do force shutdown earlier, the server still takes a couple of seconds to start up. so i fear that by forcing an early shutdown in netty, we're just delaying the problem.

**Comment by jberthold-da** [comment]
> an alternative solution would be to reset without restarting the server

This appears as the actual functionality we need. The server should not be restarted, but the ledger should be cleared.

**Comment by gaboraranyossy-da** [comment]
I think this is be possible, but would require some work. Ideally we would bring down at least the services for the time the reset is happening and rebind them when they are ready.  I'd really like to avoid having mutable state within the service implementations. A service should be bound only when it's ready to accept requests. 

Note that the grpc streams would still need to be explicitly closed from server side and I'd still generate a new `ledger_id` to avoid confusion.

**Comment by jberthold-da** [comment]
Yes, the `ledger_id` should be fresh (that's how one can tell whether the reset has happened).
It is cautious to try to avoid a race between resets and other requests but maybe that's not crucial: we are discussing a _test_ service so it is the caller's responsibility to consider the reset happening.

**Comment by jberthold-da** [comment]
I just read through the [DAML docs about ledger reset](https://docs.daml.com/app-dev/ledger-api-introduction/proto-docs.html#resetrequest), which state that requests will not be accepted, but also says that a retry loop should be used to notice when the new ledger is up (and that it will only reset the ledger, not reboot the server).
