### ISSUE TITLE
Flag to specify release version while installing an SDK tarball

### ISSUE THREAD

**Issue by dylant-da** [digital-asset/daml#17851]
When `daml install <sdk tarball>`, by default the install command picks up the daml version for the sdk tarball's internal version using GitHub's version.

This is problematic during the release process - in this case we know the projected release version for the tarball we've built and the artifacts we're building with it, but no release exists on GitHub yet.

This is also a problem for CI when we want to run many installs without running against the GitHub API limit.

I suggest extending the `--allow-install-non-release` flag to take a version, i.e. `--install-with-release-version <version>`.

**Comment by garyverhaegen-da** [comment]
@dylant-da I believe this is done per https://github.com/digital-asset/daml/pull/18097.
