### ISSUE TITLE
daml-assistant: extension unavailable when using portable installation of Visual Studio Code

### ISSUE THREAD

**Issue by bascott** [digital-asset/daml#1789]
Workarounds involve symlinking standard system install extensions directory to the portable extensions directory, or forcing VSCode to use standard diretory via `--extensions-dir` option.

**Comment by cocreature** [comment]
Hi @bascott, thanks for the report. We are working towards publishing the extension in the VSCode marketplace which should avoid that issue.

**Comment by cocreature** [comment]
The extension is now part of the VSCode marketplace and we install it via `code --install-extension` instead of assuming a specific extension directory so this should be fixed now.
