### ISSUE TITLE
change from separate DAML-LF dev major version to dev minor version 

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#179]
in this past 2 months the DAML-LF dev major version hasn't worked very well, and in practice we've used the latest DAML-LF minor version (e.g. 1.3) as a "staging" area for new features.

this is not great though, since in practice we're making the latest DAML-LF version a moving target.

i talked to @remyhaemmerle-da and @S11001001 and with stephen we came up with the following plan:

1. we remove the DAML-LF dev major version
2. instead, we have a `dev` _minor_ version that we use at all times as a staging area
3. all tools should be able to write / read the dev version (e.g. `--target 1.dev`). however the dev minor version should _never_ be the default output of the compiler.
4. all new features are put in the minor dev version. the spec also has a "dev" section where new features are batched
5. when a new batch of features is ready, we call the current dev version a new minor version (e.g. DAML-LF 1.4), and update references in the spec and code. this way as soon as we come up with a new DAML-LF version it is "done".

@remyhaemmerle-da @martin-drhu-da what do you think?

**Comment by S11001001** [comment]
Semantics question: is it possible for previous major versions to have a dev minor version?

**Comment by bitonic** [comment]
@S11001001 yes, I think we should allow this, to allow multiple major release lines to progress.
