### ISSUE TITLE
Add flexible controllers and disjunction choices

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#18]
There are lots of docs on syntax etc everywhere, so someone needs to trawl and put together a complete proposal.

**Comment by martin-drhu-da** [comment]
@akalburgi Please have a look above for a description of how we want the syntax highlighting for flexible controllers to look like.

**Comment by akalburgi** [comment]
@martin-drhu-da , @shayne-fletcher-da  I have added the syntax highlighter to the new keywork choice. While updating this new keyword I came across some inconsistencies in color highlighters  (esp functions) I am going to look deeper into this and see how this is handled in haskell extension.

**Comment by martin-drhu-da** [comment]
All pieces are implemented. The documentation is still missing but has its own ticket https://github.com/digital-asset/daml/issues/168
