### ISSUE TITLE
Header inclusion paths are absolute in network build on Windows

### ISSUE THREAD

**Issue by nmattia-da** [digital-asset/daml#180]
In spit of having the two gcc flags `-no-canonical-prefixes` and `-fno-canonical-system-headers` (see the [crosstool](https://github.com/tweag/rules_haskell/blob/7a306841b0fcca41c9fd62b3f7033fbd67d50e22/haskell/CROSSTOOL.windows#L39-L41)) the Windows build of the `network` package fails with the following error:

```
ERROR: ... this rule is missing dependency declarations for the following files included by bazel cache:
(list of absolute paths of the headers bundled with GHC)
```

It is unclear why the `unfiltered_cxx_flags` from the crosstool are not passed to the network build. Note that it does work for e.g. the `text` package, which may be just pure luck as gcc has strange heuristics for deciding whether to use absolute or relative paths when generating the `.d` list of inclusions (unless specified with `-no-canonical-prefixes` and `-fno-canonical-system-headers`.

While trying to figure out why the C flags are not passed to the native `cc_library` I could clarify [the semantics of the `cxx_builtin_include_directory`](https://github.com/bazelbuild/bazel/blob/357cb1e8f6b2ef90c4840a88e5b564d2f6fdaa71/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java#L466), which actually tried to match by prefix only. In https://github.com/DACH-NY/daml/pull/1355 I work around the issue by specifying `C:/` as a built-in include directory which fixes the issues with caching. This however should be treated as a temporary workaround, at best.

**Comment by cocreature** [comment]
Hasn’t come up in a year so closing
