### ISSUE TITLE
Update flags + docs for daml install

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#18080]
We are now recommending to clients to use `daml install` on tarballs directly, for those installing without internet.
As such, the TARGET option help should mention that this can be a path.
Similarly, the `--install-with-custom-version` flag is missing a help string.
Likely both of these are missing from docs.daml.com as well (not verified)

**Comment by dylant-da** [comment]
There is documentation in docs.daml.com https://github.com/digital-asset/docs.daml.com/pull/593, agree that there should be help text for the install-with-custom-version flag, PR here https://github.com/digital-asset/daml/pull/18097
