### ISSUE TITLE
Incorrect instructions for API Intro Example

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#182]
@gleber-da Submitted this one via the support widget from https://docs.daml.com/app-dev/ledger-api-introduction/index.html#example-project-ping-pong:

```
As per recommendation in the screenshot, I did the following:

~/tmp ❯❯❯ ls
~/tmp ❯❯❯ da new example-ping-pong-grpc-java ping-pong-java
quickstart-java  Built-in template for version: 100.11.23
~/tmp ❯❯❯ ls
~/tmp ❯❯❯

The promised directory is nowhere to be found and the command output is not explaining what has happened.
```

I can confirm the above behaviour. The command `da new example-ping-pong-grpc-java ping-pong-java` seems to result in the available templates being listed which is rather odd. Not worth fixing in the old assistant anymore, but worth being aware that bad `da new` commands result in no error message.

We should simply change the instructions to get the example form GitHub. I _think_ the API example has been merged with the java examples into https://github.com/digital-asset/ex-java-bindings. @gerolf-da @pajb-da, could you confirm?

**Comment by gerolf-da** [comment]
Fixed by #216. The instructions now point to the [java bindings examples on GitHub](https://github.com/digital-asset/ex-java-bindings). Thanks @bethaitman-da.
