### ISSUE TITLE
Deprecate warning for agreement text in daml 2.x

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#18414]
Agreement text will be gone in Daml 3.0. 
We need to mark it as deprecate in 2.9. I think a simple compiler warning should be enough

**Comment by moisesackerman-da** [comment]
Done as https://github.com/digital-asset/ghc/pull/179, https://github.com/digital-asset/daml/pull/18468, and https://github.com/digital-asset/docs.daml.com/pull/640.
