### ISSUE TITLE
Bug: `AllInDars` is implemented as `AllPackagesKnownToTriggerService`

### ISSUE THREAD

**Issue by carlpulley-da** [digital-asset/daml#18425]
Fixes https://github.com/DACH-NY/canton/issues/16996

Issue:
------

When the same trigger code is compiled to generate 2 versions:
- v1 trigger code/dar
- v2 trigger code/dar

And the trigger Daml code registers to `AllInDar`

And a trigger service is ran with a database

And the v1 trigger dar is uploaded to the trigger service

And the v2 trigger dar is uploaded to the trigger service

Then when the v2 trigger is started on the trigger service, we observe that the trigger attempts to register against both v1 and v2 templates.

This is incorrect, the v2 trigger should **only** be registering against the v2 templates and *not* the v1 templates.

Analysis:
---------

Code analysis shows that we define our actual trigger filters at:
- https://github.com/digital-asset/daml/blob/main-2.x/triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala#L415-L426 causes `AllInDar` to map to the filter `_ => true`
- https://github.com/digital-asset/daml/blob/main-2.x/triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala#L389-L398 then filters through all packages known to the trigger service - i.e. all packages known in its `dalf`  database table

**Comment by carlpulley-da** [comment]
Related to https://github.com/DACH-NY/canton/issues/16996

**Comment by carlpulley-da** [comment]
Related to https://github.com/digital-asset/daml/pull/18426

**Comment by basvangijzel-DA** [comment]
Should modify the documentation to not use AllInDar in production code.
