### ISSUE TITLE
UP-18 Upgrades error piping

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#18616]
Ensure that Dev Upgrade errors make it through canton back to the ledger-api
Pipe lookup errors out of the engine and through canton.
  - Ensure that an invalid variant downgrade gives back a usable error

Ensure that uploadDAR errors (including the type specific error) make it back to the ledger API response. See also #19092.

**Comment by basvangijzel-DA** [comment]
LookupError and DevError

**Comment by basvangijzel-DA** [comment]
Consider combining [17875](https://github.com/digital-asset/daml/issues/17875)

**Comment by carlpulley-da** [comment]
Closing as this has been completed
