### ISSUE TITLE
Make sure that the submitter is in the maintainers for all contract keys operations

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#1866]
The docs for contract keys ( https://docs.daml.com/daml/reference/contract-keys.html ) mentions

> You need authorization from all of the maintainers to run `lookupByKey`, and it can only be submitted by one of the maintainers.

This restriction comes from one of @andreaslochbihler-da or @meiersi-da , but it is currently not implemented! I think we should implement it asap under a new DAML-LF version.

As far as I can see this restriction make sense for two reasons:

* When implementing a DAML ledger in a decentralized fashion, it is extremely advantageous to be able to resolve all the keys locally, rather than having to stop mid-transaction and have to ask maintainers on some other node for the result.

* Without this restriction, when looking up a key, it might be the case that the key exists, but for a contract which is not in the view of the submitter. To keep this consistent with the behavior of fetches for existing contracts that the submitter does not see, we must return `None` -- see #751  for details.

    However this creates the bizarre situation where you might have a `lookupByKey` to return `None` on the submitter node, then for the transaction to get shipped to another node, and return `Some` there.

    This is a novel failure mode for transactions, where a well-intentioned DAML author / DAML application writer can end up with transactions that get bounced after passing the initial validation, and not because of conflicts.

    This was brought to our attention by @bame-da -- see #1852 .

    Making sure that lookups are submitted by one of the maintainers sidesteps this problem, since all maintainers are signatories, and thus must be aware of the contract.

Nota bene: this restriction is quite harsh! It essentially forbids "contract key lookup delegation", and generally hurts transaction compositionality. @hurryabit and @daravep have argued that this goes against the "spirit of DAML", or some similar moral judgement :upside_down_face: . More technically, I _think_ it also will require us to carry around the transaction submitter when validating partial transactions, which AFAIK does not happen currently.

@esaraniecki-da has argued that contract key delegation is needed only in scenarios that do not happen in real life anyhow. The classic example is bank transfers.

Assume that bank transfers requests work using an account id as a key, with the bank as the maintainer, so that key lookups are required to perform it. Now, if bank transfer are implemented with the bank allowing (that is, delegating) the sender to transfer a part of its balance to the receiver, this operation would fail since the sender will _not_ be able to submit a transaction where an account key lookup is performed. @esaraniecki-da argues that this is not what would happen in practice anyway: the sender would instruct the bank to perform the transfer, and the bank would pick up the message and execute. He has some more principled financey arguments to back this opinion up, that I can't accurately convey :).

In any case, I think by far the safest option is to implement this restriction immediately, and possibly relax it in the future, as long as the cost of porting existing applications is relatively low.

cc @meiersi-da @neil-da @da-tanabe @dajmaki

**Comment by hurryabit** [comment]
I would not describe my remark as a moral judgement. ;)
What's actually happening here is that we're basically giving up transactionality whenever we need to use the request contract + nano bot pattern @esaraniecki-da hints at.

**Comment by bitonic** [comment]
@hurryabit what do you mean with "transactionality"?

**Comment by bame-da** [comment]
I think what he means is that `lookupByKey` harms composability. Instead of allowing a bank customer to atomically transfer funds, the customer has to submit a transfer request, and the bank performs the transfer in a second transaction.

**Comment by andreaslochbihler-da** [comment]
@bitonic I think that @hurryabit refers to transactionality that a bank transfer does not get rejected if the account does not exist at the bank; this will be discovered only later when the bank's nanobot picks up the incoming transfer and tries to look up the account by the account id key.

**Comment by andreaslochbihler-da** [comment]
Overall, this is a stop-gap measure until we figure out how to properly do key delegation (and delegation in general, see the discussions around divulgence and disclosure). It hinders compositionality now, but it will be easier to relax this constraint when we have a solution. Therefore, I see this as a restriction in functionality that makes applications portable across different DAML ledgers; similar to the restriction at submission time that the submitter must have seen all input contracts (e.g., via divulgence), which is not checked during validation, either.

Consequently it suffices to implement this check only for the submission. There is no intention to enforce "submitter must be a maintainer" during validation; if we find in the future a way to disclose key information or support interactive submission, then we can lift this restriction without changing the validation parts. In particular, this should not affect whether we have to ship the submitter along with the transaction.

**Comment by bitonic** [comment]
@andreaslochbihler-da thanks a lot for filling in the details.

One more thing: don't we need a similar restriction for creates with contract keys? Or in other words, shouldn't we make sure that creates with a contract key are submitted by one of the maintainers?

**Comment by bame-da** [comment]
I think that would kill contract keys, as having a key on a template would make both creates and consuming choices non-composable.

**Comment by bitonic** [comment]
@bame-da can you elaborate why this restriction on lookups would be acceptable, but not on creates?

**Comment by bame-da** [comment]
I actually don't love it on lookups, either. Having thought about it a few days, I'm coming around to the idea of just bouncing false negative lookups during validation. In other words, we should consider introducing a new failure mode.

**Comment by bitonic** [comment]
@bame-da right, but the first point still stands and it's really the one that motivated this restriction to begin with.

**Comment by bame-da** [comment]
There appear two schools of thought regarding the role of maintainers:

1. Maintainers are the only parties that keep contracts in an index `Key -> ContractId`. Lookups are done by going to the maintainers and asking.
2. Everyone maintains the index `Key -> ContractId` for any contract in their PCS. Maintainers are the validators of lookups (and creates, by virtue of being signatories).

Ratko and @francesco-da (and @andreaslochbihler-da ) seem to have model 1 in mind. I have always had model 2 in mind, which explains why we talked past each other in some discussions.

The Sandbox behaviour is somewhere in between at the moment as #1852 shouldn't happen in either scenario.

Anyway, if we go with model 2., the first point @bitonic raises disappears. Submitters resolve keys locally to their best ability. If they don't know the full truth, we have a new failure mode in that a transaction sent in good faith can bounce for reasons other than collisions.

As I said above, if the alternative is to break composability for templates with keys, I favour this route. I use Contract Keys in almost all my DAML models now. Moving back from that, or not being able to delegate choices anymore, would be very painful.

**Comment by andreaslochbihler-da** [comment]
@bitonic Regarding creates: Even if we had the requirement that the submitter must be a maintainer of the key, we could not prevent that a create transaction fails because of a key conflict. For suppose we have a template with two maintainers, `A` and `B`. `A` and `B` can concurrently try to create a contract instance with the same key. When they submit their transaction, they are not yet aware of the other's transaction, and depending on which is sequenced first, the outcome is different. Whether it makes sense to use a new failure mode for this case or not, is up to you. It is kind of a conflict between transactions.

**Comment by andreaslochbihler-da** [comment]
@bame-da This is an instance of the divulgence/disclosure problem. From a user perspective, I would like to not think about who maintains this index `Key -> ContractId` at all, just like I don't want to think about whether I have seen the contract on which I have been delegated a choice (the `insufficient divulgence` error). So neither option 1 or 2 really fits this model.

We introduced the restriction "submitter must be a maintainer of all lookups" because we did not want to do the same mistake that we had done for divulgence. Non-stakeholders of a contract don't know when they can delete a divulged contract from the PCS because they will not be informed about the archival and a party can try to use them in any future transaction. This is because we are using divulgence (which is actually about validation) to do disclosure (for business workflows). This restriction for keys disallows this abuse of divulgence.

Now, once we have settled on a proper way to do disclosure of contracts, we can hopefully use this to disclose `Key -> ContractId` relationships, too, although I'm not sure that the current proposals work out of the box for keys. Then I'm happy to get rid of the restriction that the submitter must be a maintainer.

**Comment by remyhaemmerle-da** [comment]
Because of a bug in #1937, the feature was not properly released in 1.6

**Comment by meiersi-da** [comment]
@remyhaemmerle-da note that @bame-da just mentioned this issue indirectly in #2311

**Comment by gerolf-da** [comment]
Closing this issue, because 
1) it was never released in a DAML LF version
2) #2311 would loosen the restriction again.
