### ISSUE TITLE
Deprecate Daml repl for Daml 2.9

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#18723]
https://github.com/digital-asset/daml/pull/18648 removed `daml repl` for daml 3.0, now we need to deprecate for daml 2.9 but it's enough to just mention it in the docs

**Comment by moisesackerman-da** [comment]
@basvangijzel-DA for the docs, should we refer users to an alternative? do we just say "this feature will be removed soon"?

**Comment by moisesackerman-da** [comment]
`daml shell` should be the replacement
