### ISSUE TITLE
Intern module names in LF packages

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#1882]
Like #1496, but for module refs, using #1614's implementation. Package refs gave us a 15% savings even with many `self` package refs (which are not optimizable); module refs should net even more.

**Comment by stefanobaghino-da** [comment]
@S11001001 is this is no longer a valid ticket, can you please close this? If it was closed by a specific PR, can you reference it here? Thanks.

**Comment by S11001001** [comment]
Obviated by #3067, #3296.
