### ISSUE TITLE
Initial access documentation for upgrades

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#18994]
Initial access documentation for zero downtime contract upgrades, based on initial topics here: [18993](https://github.com/digital-asset/daml/issues/18993)

**Comment by dylant-da** [comment]
@samuel-williams-da @hrischuk-da I think we can close this?

**Comment by samuel-williams-da** [comment]
I'd say after we merge the changes Curtis intends to make.

**Comment by dylant-da** [comment]
Update from last product grilling session:
Curtis will
- Make inline changes that will need review
- Uncover some gaps that will need additional text to be closed
- Uncover missing topics that will need more additional tet

**Comment by dylant-da** [comment]
I've checked with Curtis, we can close
