### ISSUE TITLE
Additional interface type checking

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#18990]
* No duplicate definitions at participant level (best effort: only check between previous and next)
* warning if an interface definition is in a package with templates. Suggest user to put interface definition in its own package

**Comment by dylant-da** [comment]
Both of these should be handled by https://github.com/digital-asset/daml/pull/19054
- No duplicate definitions from FailsWhenAnInterfaceIsDefinedInAnUpgradingPackageWhenItWasAlreadyInThePriorPackage
- Warning comes from `WShouldDefineIfacesAndTemplatesSeparately` and `WShouldDefineTplInSeparatePackage`
