### ISSUE TITLE
IDE Ledger - basic upgrading support for 2.9

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#18992]
* (No package upload checks)
* Basic support of package names
* Should support runtime downgrades/upgrades

**Comment by moisesackerman-da** [comment]
I assume this is for daml3-script? or do we also want to support upgrades in the old daml-script? @basvangijzel-DA

**Comment by moisesackerman-da** [comment]
Also, do we want to support upgrades/downgrades on LF 1.dev only or do we also want to support them on e.g. LF 1.16/1.15?

**Comment by moisesackerman-da** [comment]
For now I'll assume daml3-script only and LF 1.dev only. According to @remyhaemmerle-da this should also work on LF 1.16 once we have it so I'll leave some TODOs for it.

**Comment by moisesackerman-da** [comment]
As discussed on Slack, this should apply to `daml-script` _and_ `daml3-script`

**Comment by basvangijzel-DA** [comment]
Discussed: only daml3-script and LF 1.16.

**Comment by basvangijzel-DA** [comment]
Discussed with Samuel: flag is currently broken, however since upgrades will be tied to LF 1.16, as will daml  v3 script, we can just remove the flag/boolean and enable upgrade behaviour always (for Daml 3 script and LF 1.16).

**Comment by basvangijzel-DA** [comment]
Interfaces are not yet supported.

**Comment by samuel-williams-da** [comment]
Moving interface support to #19594
