### ISSUE TITLE
Make 2.9 release ready

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#19009]
- [x] Freeze LF version (Rémy)
- [x] Add in the typechecker that version is >= 1.16 as part of upgrades  (Rémy)
- [x] Remove typecheck-upgrades flag (Dylan)
- [x] Transaction version for contract keys (Rémy)

**Comment by dylant-da** [comment]
typecheck-upgrades: false is still available for debugging and as a last resort, but is not given to users and defaults to true

@remyhaemmerle-da says that transaction versioning is done
