### ISSUE TITLE
Support traceid in Daml debug logging

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#19002]
Ensure trace-id based logging with `debug` and `trace` for Daml programs. 

See https://docs.google.com/document/d/1MZXbfYYSq1PseQC-y0M3oYnayqi6lLp_YJYtsLRKHxA/edit#bookmark=id.g54sd7o2m5d5 and https://digitalasset.atlassian.net/jira/polaris/projects/PT/ideas/view/3644121?selectedIssue=PT-174

(planned for patch release)

**Comment by basvangijzel-DA** [comment]
Please also see https://www.google.com/url?q=https://github.com/DACH-NY/canton/pull/13856&sa=D&source=docs&ust=1713524049337209&usg=AOvVaw0ECM92T0vwP6Ex3icH_0zN

**Comment by daravep** [comment]
Done on main, backporting to 2.9 https://github.com/digital-asset/daml/pull/19154

**Comment by daravep** [comment]
Done
