### ISSUE TITLE
Specify the C# namespace in the ledger api proto files so Digital Asset is correctly capitalised

### ISSUE THREAD

**Issue by AndrewDCDrummond** [digital-asset/daml#1901]
Currently the protoc generated C# files for the ledger API generate a namespace that is imported like this : 

`using Com.Digitalasset.Ledger.Api.V1;`

however it would look more desirable like this : 

`using Com.DigitalAsset.Ledger.Api.V1;`

to accomplish this aesthetic improvement add the following : 

`option csharp_namespace = "Com.DigitalAsset.Ledger.Api.V1.Admin";`

to all proto file sin the api\v1\admin folder,

`option csharp_namespace = "Com.DigitalAsset.Ledger.Api.V1.Testing";`

to all files in the api\v1\testing folder, and 

`option csharp_namespace = "Com.DigitalAsset.Ledger.Api.V1";`

to all files in the api/v1 folder.

And propagate the same ot any later versions of the API that will be forthcoming.

Or reject the issue as it is a 'nicety' :-)

**Comment by AndrewDCDrummond** [comment]
looks like this is closed by #1911 :-)

**Comment by remyhaemmerle-da** [comment]
@AndrewDCDrummond 
> looks like this is closed by #1911 :-)

It will be closed once #1911 is merged :-)

**Comment by remyhaemmerle-da** [comment]
Closed by #1911. 
Thanks to @AndrewDCDrummond for reporting the issue and describing the way to fix it.
