### ISSUE TITLE
Check the LF version is increasing 

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#19041]
Given two packages in upgrade relation. 
The LF version of the upgrade package should be equal to/newer than the LF version of the upgraded package

- [x] add check in the compiler
- [x] add a static check during upgrade validation https://github.com/digital-asset/daml/pull/19168
- [x] ~add a check at runtime when (up/down)grading contract~ (we rely on the static check)
- [x] backport to main-2.x https://github.com/digital-asset/daml/pull/19070

**Comment by dylant-da** [comment]
This is checked on the compiler side

**Comment by dylant-da** [comment]
Just adding the PRs that check this here:
2.x: https://github.com/digital-asset/daml/pull/19978
3.x: https://github.com/digital-asset/daml/pull/20012
