### ISSUE TITLE
GRPC's 'Timer list shutdown' error on Windows

### ISSUE THREAD

**Issue by majcherm-da** [digital-asset/daml#1907]
From time to time the below error is thrown by GRPC:
`
E0626 14:58:23.526000000   720 external/com_github_grpc_grpc/src/core/ext/filters/client_channel/backup_poller.cc:110] run_poller: {"created":"@1561561103.526000000","description":"Timer list shutdown","file":"external/com_github_grpc_grpc/src/core/lib/iomgr/timer_generic.cc","file_line":295}
`

causing issues with scenario-service communication **on Windows**:
- `da-hs-damlc-app.exe: user error (Scenario service exited unexpectedly)`
- `Exception: user error (Scenario service exited unexpectedly)`

This happened in such targets like:
`//daml-foundations/daml-tools/da-hs-daml-cli:damlc-test-tests`
`//docs:patterns-daml-test`
`//docs:ledger-model-daml-test`

**Comment by cocreature** [comment]
Closing in favor of #2520
