### ISSUE TITLE
completionStream rpc rejects requests without an offset

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#1913]
When no `offset` is provided in a `CompletionStreamRequest`, the comments states:
```
  // This field indicates the minimum offset for completions. This can be used to resume an earlier completion stream.
  // Optional, if not set the ledger uses the current ledger end offset instead.
  LedgerOffset offset = 4;
```

I would have expected to get stream which tails future completions, but instead observe a stream which is immediately closed.

**Comment by stefanobaghino-da** [comment]
After investigation, the actual issue is that the stream closes immediately **with an error** because the offset parameter is actually required by the sandbox.
