### ISSUE TITLE
Quantified type variables clash if they appear more than once in a signature

### ISSUE THREAD

**Issue by mjhopkins-da** [digital-asset/daml#1915]
This code
```haskell
type A = forall f. Functor f => f Int

aIdentity : A -> A 
aIdentity = identity
```

fails to compile with 

```
 error type checking value dIdentity:shadowing type variable: f
```

This came up because I'm attempting to write a lens library for DAML.

If I inline one definition of `A`, swapping `f` for another variable, then it works
i.e.

```haskell
forall f. Functor f => f Int

aIdentity : A -> forall g. Functor g => g Int 
aIdentity = identity
```

It also works if I remove the functor constraint from the definition of `A`.

**Comment by cocreature** [comment]
Probably one for @hurryabit

**Comment by garyverhaegen-da** [comment]
Interestingly, inlining both also seems to work:
```
aIdentity : (forall f. Functor f => f Int) -> (forall f. Functor f => f Int)
aIdentity = identity
```

**Comment by garyverhaegen-da** [comment]
While this:
```
aIdentity : forall f. Functor f => (f Int -> (forall f. Functor f => f Int))
```
(which I think is the natural parse for the priority of these operators? I hate priorities) fails to unify the two `f`s:
```
  daml/Main.daml:12:13: error:
  • Couldn't match type ‘f1’ with ‘f’
  ‘f1’ is a rigid type variable bound by
  the type signature for:
  aIdentity : f Int -> forall (f1 : * -> *). Functor f1 => f1 Int
  at daml/Main.daml:12:1-20
  ‘f’ is a rigid type variable bound by
  the type signature for:
  aIdentity : forall (f : * -> *).
  Functor f =>
  f Int -> forall (f1 : * -> *). Functor f1 => f1 Int
  at daml/Main.daml:11:1-72
  Expected type: f Int -> f1 Int
  Actual type: f1 Int -> f1 Int
  • In the expression: identity
  In an equation for ‘aIdentity’: aIdentity = identity
  • Relevant bindings include
  aIdentity : f Int -> forall (f1 : * -> *). Functor f1 => f1 Int
  (bound at daml/Main.daml:12:1)
```

**Comment by garyverhaegen-da** [comment]
Actually, is that a type signature that should compile? There is nothing to enforce that A on each side is the same, yet the notation `A -> A`, for a human, seems to imply so.

**Comment by mjhopkins-da** [comment]
> Interestingly, inlining both also seems to work:
> 
> ```
> aIdentity : (forall f. Functor f => f Int) -> (forall f. Functor f => f Int)
> aIdentity = identity
> ```

I think this shows the crux of the issue: the `f` is quantified, and scoped to `A`, so the above is the correct inlining of the type synonym.

**Comment by hurryabit** [comment]
Just relaxing the DAML-LF type checker doesn't do the job. The following code causes a type error:
```haskell
type F f = forall a. f a

shadow : forall a. F (Either a)
shadow = error "shadow"
```
The problem is that the translation from GHC Core to DAML-LF does not do capture avoiding substitution when inlining type synonyms. I'll look into this next week.
