### ISSUE TITLE
[upgrades] crash when two commands target different packages for the same contract inside the same request

### ISSUE THREAD

**Issue by paulbrauner-da** [digital-asset/daml#19161]
# Bug description

The crash happens for the following scenario, assuming two packages `0` and `1`, where `1` upgrades `0`:

```
Scenario
  Topology
    Participant 0 parties={1}
  Ledger
    Commands participant=0 actAs={1} disclosures={}
      Create 0 pkg=0 sigs={1} obs={}
    Commands participant=0 actAs={1} disclosures={}
      Exercise NonConsuming 0 pkg=0 ctl={1} cobs={}
      Exercise NonConsuming 0 pkg=1 ctl={1} cobs={}
```

That is:
  - We send a first request to the ledger API, creating a contract for package ID `0`
  - We then send a request made of two commands:
      - One non-consuming exercise on the previously created contract with explicit package ID `0`
      - One non-consuming exercise on the same contract with explicit package ID `1`
      
Any permutation of `0`s and `1`s will trigger the error, as long as the two commands in the second request use different package IDs. This also works if the package ID is not explicitly specified in one of the commands, as long as the other command uses a different package ID than the default one picked by canton.

# Reproduction

The branch [pb/repro-for-remy](https://github.com/digital-asset/daml/tree/pb/repro-for-remy/) has a reproduction. In one terminal, from the `sdk` folder, run canton using:
```
./daml-lf/model-test-lib/run_canton.sh
```
Then in another terminal, launch the program that reproduces the error:
```
bazel run daml-lf/model-test-lib:demo
```
The entrypoint is [Demo.scala](https://github.com/digital-asset/daml/blob/pb/repro-for-remy/sdk/daml-lf/model-test-lib/src/main/scala/com/digitalasset/daml/lf/model/test/Demo.scala).

# Root cause

@remyhaemmerle-da and @moisesackerman-da have narrowed down the problem to a cache issue: after the first exercise, information about the contract is stored in a cache whose keys don't include the template ID. The cached data is fetched [in `fetchAny`](https://github.com/digital-asset/daml/blob/75ff49bbeccce741124830ff04f5b61ac72378ab/sdk/daml-lf/interpreter/src/main/scala/com/daml/lf/speedy/SBuiltinFun.scala#L2214) which leads to [a clash](https://github.com/digital-asset/daml/blob/283e801c8f3eed0512b7f780965e4fe5d9045c2b/sdk/daml-lf/interpreter/src/main/scala/com/daml/lf/speedy/SBuiltinFun.scala#L1107) between expected and actual template IDs down the road.

# Possible fix

The branch [pb/demo-fix-for-upgrade](https://github.com/digital-asset/daml/tree/pb/demo-fix-for-upgrade) has a [one-line fix](https://github.com/digital-asset/daml/commit/7a117ebbe5f5ee74d16838d3146af0d784e04c16#diff-13352353b9fde9b28d8cdc1e0032aac09a57cb3f27c1cf1d92a3e67d442f355eR2214) demonstrating that the root cause has been correctly identified, but it then break other tests. These tests are potentially wrong but either way it is not clear than this is the best way to solve the problem. @remyhaemmerle-da suggested that `fetchAny` does too many things: it should only concern itself with fetching `Any` contracts, for which we never have a target template IDs, and "casting" a contract should be performed by another construct.

**Comment by remyhaemmerle-da** [comment]
fixed by #19200
