### ISSUE TITLE
Derived Eq and Show instances for variants don't work as expected

### ISSUE THREAD

**Issue by mjhopkins-da** [digital-asset/daml#1926]
My expectation is that the code sample below ought to compile

```haskell
testOptionalEq = None == None
testEitherEq   = Left 1 == Left 1

testOptionalShow = show None
testEitherShow   = show (Left 1)
```
and yet each line results in a compilation error, either 

```
Ambiguous type variable `a1' arising from a use of `=='
  prevents the constraint `(Eq a1)' from being solved.
  Probable fix: use a type annotation to specify what `a1' should be.
```

or

``` 
Ambiguous type variable `a0' arising from a use of `show'
  prevents the constraint `(Show a0)' from being solved.
  Probable fix: use a type annotation to specify what `a0' should be.
```

The corresponding Haskell works fine.

Of course, there is the obvious workaround: pin down the unspecified type variable in each case.
But it would be great to see this fixed.

**Comment by neil-da** [comment]
I get the exact same issue in Haskell. If you tried this in `ghci` you might be using the automatically turned on (only in `ghci`) [`ExtendedDefaultRules`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#extension-ExtendedDefaultRules). If in DAML you turn on `{-# LANGUAGE ExtendedDefaultRules #-}` at the top of the file this code then works. However, like Haskell, there a good reasons for not having this feature on as standard (it's somewhat hacky), so use if you want, but I'd recommend more type signatures.

**Comment by ndmitchell** [comment]
It's a great question, so I reasked/answered on StackOverflow: https://stackoverflow.com/questions/56803020/ambiguous-type-variables-from/56803021

**Comment by mjhopkins-da** [comment]
Ah, of course :man_facepalming:
