### ISSUE TITLE
Non Linearity of upgradability of the standard libraries

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#19338]
The issue relies on:

### 1. an SDK contains several version of the standard library 
In a SDK there is a version of the standard library for each LF versions the compiler produces.

Let's take for example 2 fictitious SDKs with two fictitious LF Versions as example
- SDK 2.10.0 defines two stdlibs: 
    -  `stdlib_2.10.0_LF_1.16`
    -  `stdlib_2.10.0_LF_1.17` 
- SDK 2.11.0 defined two stdlibs:  
    -  `stdlib_2.11.0_LF_1.16`
    -  `stdlib_2.11.0_LF_1.17`

In practice: 
-  `stdlib_XXX_LF_1.17` will almost always contains more types that `stdlib_XXX_LF_1.16` (for the new features introduced by LF 1.17, think of new builtin types or new type classes) 
- `stdlib_2.10.0_LF_XXX` will often contains more types that `stdlib_2.11.0_LF_XX` (for a new features independent of the LF Version, think for instance to a new data type defined in pure Daml, like Queue) 

### 2. the upgrade type checking is modular.  
  During comparison of two packages `pkgA` and `pkgB`, the comparison of two types externally defined , 
```
     pkg1:Mod1:Type1 <= pkg2:Mod2:Type2         (pkg2:Mod2:Type2 upgrades pkg1:Mod1:Type1)
```
succeeds if: 
     - `Mod1:Type1` = `Mod2:Type2`  (module and entity names are syntactically equal) 
     - `pkg1` <= `pkg2` (`pkg2` is a valid upgrade of `pgk1`)
     - (more constraints not relevant here)

**Importantly** that means that : all types defined in `pkg1` must be defined in `pkg2`  

### The Problem, non linear relationship of stdlib upgradability.  

We want to upgrade a package from one LF version to the other one in the same SDK, so we need
- `stdlib_2.10.0_LF_1.16` <=  `stdlib_2.10.0_LF_1.17`
- `stdlib_2.11.0_LF_1.16` <=  `stdlib_2.11.0_LF_1.17` 

and we want to upgrade from one SDK to the other, so we need
- `stdlib_2.10.0_LF_1.16` <=  `stdlib_2.11.0_LF_1.16`
- `stdlib_2.10.0_LF_1.17` <=  `stdlib_2.11.0_LF_1.17`

by transitivity we also get `stdlib_2.10.0_LF_1.16` <= ` stdlib_2.11.0_LF_1.17`

but in general `stdlib_2.10.0_LF_1.17` is not comparable to `stdlib_2.11.0_LF_1.16` (both contains types than  the other does not contains). 

This mean we cannot, in general, linearize the upgrade relation of stdlib. However is it currently a very important restriction we have in place, all packages with the same name should be comparable.

**Comment by remyhaemmerle-da** [comment]
We can indeed distinguish packages that defines templates **and** serializable types, from packages that define only function and unserializable type. 
@moritzkiefer-da brautgh to my attention that the stdlib defined almost no serializable types (all the Daml standard types are defined in stable package that conveniently never change. 

So the plan is as follow, 
- we will modified the stdlib so it does not define serializable types

**Comment by paulbrauner-da** [comment]
After a call with @remyhaemmerle-da, summarizing my understanding of how and why the upgrade check will work.

- First we assume that the standard library only contains types that are either in stable packages or are not serializable.
- The we restrict the upgrade check between two packages to serializable types.

Now we amend the upgrade check between two types at upload time like this:
  - When comparing two types pkg1:A and pkg2:A, we look up the versions of pkg1 and pkg2
  - if pkg1 and pkg2 are stable packages then pkg1 == pkg2 and thus we have trivially pkg1 <= pkg2 for the upgrade relationship
  - if pkg1 and pkg2 are not stable, then pkg1:A and pkg2:A must be serializable because the packages we are comparing for upgrade validation already went through "normal" validation, which checks that serializable types are made of serializable components. Thus they can't be part of the standard library and we simply check that pkg1 <= pkg2, which is well defined for packages outside of the standard library.

**Comment by meiersi-da** [comment]
@remyhaemmerle-da @paulbrauner-da : I sadly don't understand all the details in your write-up. Two validation questions come to mind:
1. Can a third-party define a utility library that is free of the versioning constraints like the `stdlib`? We do that for example here in CN: https://github.com/DACH-NY/canton-network-node/blob/main/daml/splice-util/daml/Splice/Util.daml
2. From my experience in Daml studio, it seems that all types with an `(Eq, Show)` instance are considered `Serializable`. How can a utility library avoid being subjected to the strong version compatibility check when using types that implement these type-classes for coding purposes?

**Comment by meiersi-da** [comment]
>  We'll probably want to make that cleaner by allowing one to mark a datatype as non-serializable (by making it an instance of a typeclass for instance)

Why not make this opt-in instead of opt-out: declare serializable types using a `(Serializable)` constraint on the datatype declaration.

**Comment by remyhaemmerle-da** [comment]
> Why not make this opt-in instead of opt-out: declare serializable types using a (Serializable) constraint on the datatype declaration.

I am more and more convince it is the way to go, as: 
- It make the upgradability easier (the comparision will ignore unserializable type)

**Comment by remyhaemmerle-da** [comment]
> Why not make this opt-in instead of opt-out: declare serializable types using a (Serializable) constraint on the datatype declaration.

this actually sounds reasonable. Will will investigate, but probably only for daml 3.x

**Comment by remyhaemmerle-da** [comment]
Just for reference, it is possible to defined a unserializable type that extends `Eq` and `Show`.

See the type slightly combursome type `B` in:  
```
data Void
data A phantom = A {} deriving (Eq, Show)
data B = B { a: A Void } deriving (Eq, Show)
```
