### ISSUE TITLE
Fix data flavour change error on upload checks

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#19483]
The error for when a data type changes "variety" or "flavour" (i.e. from record to variant) is currently `EUpgradeMismatchDataConsVariety $dataConName` on the upload checks. This should be updated to something readable.

**Comment by dylant-da** [comment]
Done!
https://github.com/digital-asset/daml/pull/19658
https://github.com/digital-asset/daml/pull/19659
https://github.com/digital-asset/daml/pull/19670
