### ISSUE TITLE
Add warning for type checking upgrades at compile time for bad metadata

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#19492]
Given that we are using the upgrades field in the daml.yaml. 
Consider giving a warning, that can be disabled for the following cases:

- [ ] package name is different from the package in the upgrades field
- [ ] warning if the version number is the same or older (possibly consider generalising the upgrades field to upgrades and downgrades before implementing this).

**Comment by daravep** [comment]
@dylant-da Why wouldn't we display this as an error? If I define an upgrade dependency, shouldn't the compiler insist that the package names are consistent? If they are not consistent, the upgrade dependency wouldn't have any effect, so shouldn't be defined at all. No?

**Comment by dylant-da** [comment]
The current behaviour is a leftover from the prior approach when we didn't check dependencies and so package names ultimately didn't matter until upload. I agree that it should be turned into an error.

**Comment by dylant-da** [comment]
@samuel-williams-da implemented this https://github.com/digital-asset/daml/pull/19978

**Comment by samuel-williams-da** [comment]
Now also merged for 3x, closing
