### ISSUE TITLE
Compiler upgrade checks don't allow alpha equivalence between datatypes

### ISSUE THREAD

**Issue by dylant-da** [digital-asset/daml#19590]

**Comment by daravep** [comment]
Likely revealing my ignorance, but what do you mean here? Our assumption in upgrading is that data types can't be renamed. So do you want to support renaming?

**Comment by dylant-da** [comment]
Fixed by https://github.com/digital-asset/daml/pull/20016 and https://github.com/digital-asset/daml/pull/20024 on 2.x, https://github.com/digital-asset/daml/pull/20025 on 3.x
