### ISSUE TITLE
queryInterfaceContractId doesn't' run upgrades

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#19607]
Running `queryInterfaceContractId` on a daml contract does not perform upgrades on the contract before computing it's view.
i.e. a participant with V1 and V2 package, V1 contract instance of interface
Calling `queryInterfaceContractId` on that contract gives the V1 instance view, rather than V2, despite package preference.

**Comment by samuel-williams-da** [comment]
Daml script queries the ACS for interface views, and gives this back.
The ledger-api currently uses the interface view definition from the contract version it was created with, whereas we might expect it to choose an instance according to package resolution - to discuss with Tudor.
Consider alternative of computing the view at creation time, and now allowing to change with upgrades - similarly to signatories, such that re-computation would ensure it doesn't change.

**Comment by samuel-williams-da** [comment]
Leaning towards package map

**Comment by samuel-williams-da** [comment]
This will mean that querying will need a way to override the package map, as command submission does.

**Comment by samuel-williams-da** [comment]
Fixed in 2x by @paulbrauner-da by preventing view changes

**Comment by tudor-da** [comment]
For reference, he fix PR in 2.x: https://github.com/digital-asset/daml/pull/19857
