### ISSUE TITLE
Templates and interfaces warning should only report once per module

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#19609]
Currently, if there are multiple templates or multiple interfaces in the same module alongside the other, you get multiple warnings/errors for that file with the exact same message.

**Comment by dylant-da** [comment]
Solved by
https://github.com/digital-asset/daml/pull/19893
https://github.com/digital-asset/daml/pull/19908

**Comment by dylant-da** [comment]
Forward port to 3.x complete https://github.com/digital-asset/daml/pull/19979
