### ISSUE TITLE
Upload validation cannot compare local packages

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#19742]
Uploading a DAR with both V1 and V2 of a package doesn't compare the two for upgrade checking, as the upgrade checker is only able to lookup packages already uploaded previously.

We are also missing a test for this.

Also consider this for compile time checks

**Comment by remyhaemmerle-da** [comment]
https://github.com/remyhaemmerle-da/upgrade-key/tree/bug1 show the issue
One can load the dar template-3.0.0.dar while the package template-3.0.0 and template-2.0.0 are incompatible

**Comment by samuel-williams-da** [comment]
Done for 2.9 + 2.x, blocked for 3.x as rest of the checks haven't been fully ported yet.

**Comment by dylant-da** [comment]
Now that I've forwardported the 2.x changes I think we can do this one as well, assigning @samuel-williams-da
