### ISSUE TITLE
Sandbox 100.13.10 reloads the package when invoking the`Reset` service

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#1979]
**Steps to reproduce**
1. Set up a system monitor to watch CPU and RAM
2. start sandbox (`java -jar sandbox-100.13.10.jar --port 8080 my.dar`) with a dar containing a large package dalf (ours is 78MB).
3. Observe that sandbox loads the dar, visible in a CPU spike and large RAM footprint (from 0.13.10 sandbox seems to eagerly load packages, which is a good idea :+1: . Intended? )
4. reset sandbox using `grpcurl`, like this:
```
 grpcurl -d "$(grpcurl -plaintext localhost:8080 com.digitalasset.ledger.api.v1.LedgerIdentityService/GetLedgerIdentity)" -plaintext localhost:8080 com.digitalasset.ledger.api.v1.testing.ResetService/Reset
```
5. Observe that sandbox again produces a CPU spike, and RAM allocation might increase again)

**What's your preferred solution?**
Sandbox should not "reboot" but simply use a new ledger, and should be ready to use within milliseconds after a reset. This used to be the case.

The reset service is essential for proper feature and integration testing. Changing sandbox behaviour may cause performance issues (it did in the past). It would be a good idea to monitor its performance.

**About your system**
 - OS: Linux
 - SDK version 0.13.10

**Comment by rautenrieth-da** [comment]
This code changed when the package management API was implemented. Packages are reloaded from file and added to the ledger on each restart: https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/SandboxServer.scala#L168.

We could factor out the loading from file, and keep a snapshot of the package store initialized from CLI arguments, reusing it after each reset. Note however that package uploads are conceptually ledger events much like the exercising of a choice, so we will have to do _some_ work after each reset. This will be especially noticeable when using the Postgres backend, where packages are now persisted in the database (as of 100.13.11).

**Comment by gerolf-da** [comment]
@rautenrieth-da: good point. I think factoring out the loading of the dar file into `InMemoryPackageStore` outside the initialization is a good start. Let's measure how much that improves the situation.

**Comment by jberthold-da** [comment]
Interesting - I did not notice the package mgmt. API before.
Resetting packages to an initial state probably makes sense, but keeping all uploaded packages in the store (as if they had been provided on startup) might be even better - the one thing that does not work is a complete reboot (which it does right now, again).
Keep in mind that ledger reset is a test tool anyway. 
I assume nobody would want it active in a production deployment. It may be a good idea to only enable it with a special test mode flag on startup. Then it is fair game to keep packages in the store IMHO.
