### ISSUE TITLE
Local contracts are not upgraded

### ISSUE THREAD

**Issue by samuel-williams-da** [digital-asset/daml#19905]
Local contracts (those contract created withing a transactions) are not upgraded when fetch/exercise with a different version. 
Those failed with WronglyTypeContract Error.

the test    "signatories in local contract"  in this [branch](https://github.com/digital-asset/daml/commit/e40c054e14db2e2f90308b320bf8882862a6545e#diff-34600e2c69caed67564e51b6fd6866305026540da6af73d1fc9c10b7960e2430R566) show the issue. 

The missing upgrade is located in [FetchTemplate SBuiltinFun](https://github.com/digital-asset/daml/blob/c3de7c0c50043edac8d2f3463538f4df494905a9/sdk/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltinFun.scala#L2130).

**Comment by dylant-da** [comment]
Delaying until Remy gets back, unless upgrade squad says elsewise
