### ISSUE TITLE
Stop flickering of codelenses

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#1993]
At the moment, you get a lot of flickering of codelenses for scenarios while editing a file. This is because we do not output any codelenses when we fail to compile a file, so you go from compiling file with codelenses to file with parse error without codelenses back to compiling file with codelenses during editing.

This is particularly annoying since the codelenses shift the code around vertically in VSCode.

The following seems like a better solution here:
1. Cache codelenses so that we can return the previous codelenses if we cannot compile the file.
2. Add a note in the IDE if there is an open scenario view for a scenario that does no longer exist (i.e., we are able to compile the file but the scenario no longer is part of the file). We should have that either way since that is already an issue at the moment.
3. Add a note in the IDE if there is an open scenario view for a scenario in a file that does no longer compile. We should have that either way since that is already an issue at the moment.

**Comment by hurryabit** [comment]
Parts 2 and 3 sound like the right thing to do. I have some doubts about 1. Suppose we have a file full of placeholders like
```haskell
test1 = scenario do pure ()

test2 = scenario do pure ()
```
If we now start actually implementing `test1`, the code lens for `test2` will move into the body of `test1` until we reach a state that compiles again. With `do` notation this might take a while. It would be great if there was an easy way to detect when the uses enters or deletes a new line. Do we know if there's such a way?

**Comment by cocreature** [comment]
That’s a fair point. I would argue that having the codelenses be at incorrect positions is still better than not having them but I expect that overtime we will want to have more and more things that depend on cached information so we need to be able to map positions in a cached document to positions in the currnent document. The position mapping should be quite easy to implement but for the actual caching of requests we should come up with something that is more general than codelenses.

**Comment by cocreature** [comment]
All three points have been addressed now, thanks @majcherm-da for taking care of 2 and 3!
