### ISSUE TITLE
test java codegen with strange type / module names using daml-lf directly

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#2]
there are various edge cases in the java codegen that we cannot test easily or at all using a `.daml` file. for example i do not believe we can currently generate type names with dollars in them from `.daml`.

before it was very hard to write DAML-LF directly, but it's actually much easier now thanks to @remyhaemmerle-da 's parser. see https://github.com/DACH-NY/daml/blob/2766d13da75fcf7b1e08f00fbc02d6891aa53645/daml-foundations/daml-lf/interface/src/test/scala/com/digitalasset/daml/lf/iface/TypeSpec.scala#L75 for an example test where i use the type parser. 

problematic tests we should make sure to test:

- [ ] strange names (dollars, keywords, etc)
- [x] prefix clashes, e.g. `Foo:Bar` and `Foo.Bar:Baz` -- this is now forbidden as per DAML-LF collision restriction, see  https://github.com/DACH-NY/daml/blob/c876df419ddcfb13b4cc445e9f014c8ac6f6642a/daml-lf/spec/daml-lf-1.rst#id31 . specifically, the type `Foo:Bar` would conflict with module `Foo.Bar`
- [x] `Foo:Bar` resulting in class `Foo` in the default namespace, rendering it effectively unusable (cannot be used in another Java file). -- not applicable anymore because now we create a package per module, rather than a class per module.

and anything else @stefanobaghino-da , @gerolf-da , or @mariop-da can think of.

**Comment by gerolf-da** [comment]
We don't intend on writing DAML-LF directly for java codegen tests.
