### ISSUE TITLE
Provide participant id as a command line argument

### ISSUE THREAD

**Issue by mziolekda** [digital-asset/daml#2025]
Currently the participant id is hardcoded. This is sufficient for in-memory ledgers implemented in a single node, but not good enough for a distributed ledger with multiple participants.

Implement passing of participant id as a command line argument. This needs to happen in all ledger api server implementations as well as in the indexer.

**Comment by SamirTalwar-DA** [comment]
This is now implemented for Sandbox and the KVUtils single-node runner. Is there anything else that needs to be done in this repository?

**Comment by SamirTalwar-DA** [comment]
Asked around; sounds like we're not sure. Closing this, but feel free to re-open it and add more details if there's something to be done.
