### ISSUE TITLE
Use participant's id to determine if a party is local

### ISSUE THREAD

**Issue by mziolekda** [digital-asset/daml#2026]
At present, the postgres indexer marks all the parties as local to the participant. This is not correct for a distributed ledger, where the read service will supply information about parties located at all the participant nodes connected to the ledger.

Inspect participant ids arriving in updates from the read service and mark parties as local when the participant id matches with the participant id configured in a command-line argument.

**Comment by oliverse-da** [comment]
Going through old issues: Is this issue resolved @stefanobaghino-da and @mziolekda ? Looking at `JdbcIndexer`, specifically the last line in this code snippet:

```
  private def handleStateUpdate(offset: Offset, update: Update): Future[Unit] = {
[..]
    val result = update match {
      case PartyAddedToParticipant(
          party,
          displayName,
          hostingParticipantId,
          recordTime,
          submissionId) =>
        ledgerDao
          .storePartyEntry(
            offset,
            PartyLedgerEntry.AllocationAccepted(
              submissionId,
              hostingParticipantId,
              recordTime.toInstant,
              domain
                .PartyDetails(party, Some(displayName), this.participantId == hostingParticipantId))
```
