### ISSUE TITLE
damldocs: Separate daml-prim and daml-stdlib in official docs (or combine them better).

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#2060]
As part of #2013, daml-prim and daml-stdlib are now processed separately when building the standard library docs, because they need to be compiled separately, otherwise they fail at the typechecking stage. The RST and Hoogle docs are combined by concatenation (using the `--prefix` flag), but this causes problems with the `-- | MOVE Prelude` directives in daml-prim, resulting in two separate `Prelude` modules in the docs, which leads to Sphinx error. (Cross-package `MOVE` is pretty problematic in general!)

The issue is temporarily solved by removing the `-- | MOVE Prelude` directives in `daml-prim` and adding a comment to the effect that "This module is included in Prelude". But I think in general it would make sense to be explicit about what is in `daml-prim` and what is in `daml-stdlib`, exposing them as separate packages in the docs, giving them separate doc pages / sites, since users can already include them separately in their daml projects. That way, it's fine if they both have "Prelude" modules (even if they really don't).

**Comment by cocreature** [comment]
I am slightly worried that this might end up confusing users more than it helps. DAML packages are something that users have very little interaction with atm and even if they do, the distinction between `daml-prim` and `daml-stdlib` is not clear at all. Maybe we should just reexport the relevant (from a user’s perspective) parts of `daml-prim` in `daml-stdlib` and only show docs for that? That seems somewhat similar to how GHC handles this with `ghc-prim` and `base`.

**Comment by associahedron** [comment]
That sounds reasonable to me, although a bit beyond the current ability of damldocs AFAICT. 🙃

Perhaps there is also a better way to combine daml-prim and daml-stdlib docs and I just need to investigate more.

**Comment by associahedron** [comment]
I'm now combining daml-prim and daml-stdlib through the intermediate json representation, instead of concatenating hoogle / rst docs. There is a bug here -- modules with the same name are not combined properly -- so I raised that as a separate ticket #2073. Once that's solved, I can put all the `-- | MOVE Prelude` back in place.
