### ISSUE TITLE
daml-assistant: Kill/terminate signals leave behind child processes

### ISSUE THREAD

**Issue by gaborh-da** [digital-asset/daml#2062]
**Is your feature request related to a problem? Tell us about it.**
We needed to start up Sandbox via `daml assistant` from Java using ProcessBuilder/Process. Finally, we had to shut it down with `process.destroy()` that sends a kill signal. It left two child processes behind.

This behaviour is manually reproducible from a terminal.

**Steps to reproduce**
1. Start a `daml sandbox`
2. Observe the processes started (three processes)
3. Kill the parent: the other two remains there

```
>>> daml sandbox

>>> ps xao pid,ppid,command | grep "daml/sdk"
22895  5216 /home/gabre/.daml/sdk/0.13.10/daml/lib/ld-linux-x86-64.so.2 --library-path /home/gabre/.daml/sdk/0.13.10/daml/lib /home/gabre/.daml/sdk/0.13.10/daml/lib/daml sandbox
22908 22895 /home/gabre/.daml/sdk/0.13.10/daml-helper/lib/ld-linux-x86-64.so.2 --library-path /home/gabre/.daml/sdk/0.13.10/daml-helper/lib /home/gabre/.daml/sdk/0.13.10/daml-helper/lib/daml-helper run-jar sandbox/sandbox.jar
22918 22908 java -jar /home/gabre/.daml/sdk/0.13.10/sandbox/sandbox.jar

>>> kill -9 22895 # kill signal, term signal's result is the same

>>> ps xao pid,ppid,command | grep "daml/sdk"
22908  4117 /home/gabre/.daml/sdk/0.13.10/daml-helper/lib/ld-linux-x86-64.so.2 --library-path /home/gabre/.daml/sdk/0.13.10/daml-helper/lib /home/gabre/.daml/sdk/0.13.10/daml-helper/lib/daml-helper run-jar sandbox/sandbox.jar
22918 22908 java -jar /home/gabre/.daml/sdk/0.13.10/sandbox/sandbox.jar
```

**What's your preferred solution?**
Expected behaviour is that all the three processes exit.

**Screenshots**
N/A

**About your system**
 - OS: Ubuntu Linux
 - SDK version 0.13.10

**Additional context**
N/A

**Comment by cocreature** [comment]
Fixed in https://github.com/digital-asset/daml/pull/2069
