### ISSUE TITLE
Recover from failures in PostgresIndexer

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#2065]
- PostgresIndexer should restart the stream of state updates from the read service if an error occurs in the stream.
- Clarify and document how database write failures should be handled.
  - Connection dropped -> we can recover
  - SQL Errors -> we cannot recover 💥
- Deal with errors during the initialization phase on startup

TODO: Investigate more possible failure scenarios.

**Comment by rautenrieth-da** [comment]
Implementation plan:
- Wrap `PostgresIndexer` in a new class called `RecoveringPostgresIndexer`
- `RecoveringPostgresIndexer` holds a mutable handle to an actual `PostgresIndexer`
- `RecoveringPostgresIndexer` listens to all errors from the actual `PostgresIndexer` (i.e., upon initialization and through the `onError` handle). When encountering a `SQLRecoverableException` or `SQLTransientException` (or any other exception that looks recoverable by restarting the indexer), it will kill the actual `PostgresIndexer` and restart it
