### ISSUE TITLE
Missing `signatories` on event from `ActiveContractsService`

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#2070]
I'm seeing the events returned from the `GetActiveContracts` stream as having no `signatories`, whereas the *same* event from `GetTransactions` does have the single expected signature

```
    expected: CreatedEvent {eid = EventId {unEventId = "#0:0"}, cid = ContractId {unContractId = "#0:0"}, tid = TemplateId (Identifier {pid = PackageId {unPackageId = "d624f0b838173a2e1bf3f29fa0e49c6da33f7be7882dace554a53eb640684237"}, mod = ModuleName {unModuleName = "Iou"}, ent = EntityName {unEntityName = "Iou"}}), createArgs = Record {rid = Just (Identifier {pid = PackageId {unPackageId = "d624f0b838173a2e1bf3f29fa0e49c6da33f7be7882dace554a53eb640684237"}, mod = ModuleName {unModuleName = "Iou"}, ent = EntityName {unEntityName = "Iou"}}), fields = [RecordField {label = "issuer", fieldValue = VParty Alice},RecordField {label = "owner", fieldValue = VParty Alice},RecordField {label = "currency", fieldValue = VString "A-coin"},RecordField {label = "amount", fieldValue = VDecimal "100.0"},RecordField {label = "observers", fieldValue = VList []}]}, witness = [Alice], key = Nothing, signatories = [Alice], observers = []}
     but got: CreatedEvent {eid = EventId {unEventId = "#0:0"}, cid = ContractId {unContractId = "#0:0"}, tid = TemplateId (Identifier {pid = PackageId {unPackageId = "d624f0b838173a2e1bf3f29fa0e49c6da33f7be7882dace554a53eb640684237"}, mod = ModuleName {unModuleName = "Iou"}, ent = EntityName {unEntityName = "Iou"}}), createArgs = Record {rid = Just (Identifier {pid = PackageId {unPackageId = "d624f0b838173a2e1bf3f29fa0e49c6da33f7be7882dace554a53eb640684237"}, mod = ModuleName {unModuleName = "Iou"}, ent = EntityName {unEntityName = "Iou"}}), fields = [RecordField {label = "issuer", fieldValue = VParty Alice},RecordField {label = "owner", fieldValue = VParty Alice},RecordField {label = "currency", fieldValue = VString "A-coin"},RecordField {label = "amount", fieldValue = VDecimal "100.0"},RecordField {label = "observers", fieldValue = VList []}]}, witness = [Alice], key = Nothing, signatories = [], observers = []}
```

**Is your feature request related to a problem? Tell us about it.**
It's really helpful when we understand _why_ you're making a feature request - for example, because it solves a problem you're having. Include a description of the problem here --- eg "I'm always frustrated when [...]"

**Steps to reproduce**
Steps to reproduce the problem:
2. Attempt to '...'
3. See error message '...'

**What's your preferred solution?**
Tell us what you'd want or expect to happen.

**Screenshots**
If they're relevant, add screenshots to help show us the problem.

**About your system**
 - OS: (are you on Windows, OSX, Linux? Which version?)
 - SDK version (e.g. 0.12.18)

**Additional context**
Is there anything else you can think of that might help us enhance or fix this issue?

**Comment by stefanobaghino-da** [comment]
After a brief investigation, [the active contract service has simply no notion of signatories and observers](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ActiveContracts.scala#L193-L200). These are dropped along the way [at this time](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ActiveContracts.scala#L103-L121).

It's worth noting that [the SQL schema for contracts currently has no reference to signatories and observers](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/resources/db/migration/V1__Init.sql#L65-L97) and [the contract blob does not appear to have them either](https://github.com/digital-asset/daml/blob/master/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/value/Value.scala#L253), so the situation probably deserves more attention as **this leaves me with doubts regarding the fact that a persistent PSQL-backed ledger in the reference implementation could ever serve signatories and observers** (if that's the case, tests also failed spectacularly letting this go through).

For reference, [this is the PR that added signatories and observers](https://github.com/digital-asset/daml/pull/1814). More details coming as soon as I can move on with this.

**Comment by gerolf-da** [comment]
The signatories and observers are derived from the data in `NodeCreate`. You can extend `ActiveContract` with `signatories` and `observers` fields, and wherever an `ActiveContract` object is created, you probably have the original `NodeCreate` value available.
