### ISSUE TITLE
Differentiate between disclosed and divulged contracts in DAML Studio

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#2111]
It would be useful to be able to differentiate between disclosed and divulged contracts in the IDE. Disclosure mostly happens willingly, whereas divulgence is often a side-effect that's not obvious to the user. Being able to identify divulged contracts visually will help developers to better understand the (privacy) consequences of their code.

Suggested solution in the transaction view:
Instead of `known to (since)` have `disclosed to (since)` and `divulged to (since)`.

Suggested solution in the table view:
Mark the `X` that signals visibility for a party in a different color if the contract is divulged instead of disclosed.

**Comment by cocreature** [comment]
Fixed, thanks @hurryabit!

**Comment by hurryabit** [comment]
It's only fixed for the table view but not for the tree view. Thus, I'd like to keep the ticket open.
