### ISSUE TITLE
Evaluate usefulness of eager package loading in the StandaloneIndexServer

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#2129]
The `StandaloneIndexServer` is [currently loading the packages eagerly at startup](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/index/StandaloneIndexServer.scala#L138-L139). This may be a legacy of past needs, theoretically now tailing the `ReadService` should be enough and working toward this end without having to explicitly (and eagerly) load the packages.

**Comment by gerolf-da** [comment]
This stems from a time where packages weren't written to the database yet.
Next steps:

On normal package upload:
- WriteService -> Ledger -> ReadService -> Postgres -> Index -> Preload/compile package into DAML-LF engine -> Return response to client

On startup:
- Preload the engine with all packages already stored in the Postgres index database
- Use the PackageManagementService to upload the packages provided on the command line. This means the package will end up being loaded into the DAML-LF engine as per the normal package upload above.

**Comment by stefanobaghino-da** [comment]
I'm not sure this is relevant anymore. Closing unless needed.
