### ISSUE TITLE
Publish daml_kvutils_java_proto source to bintray

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#2134]
**Is your feature request related to a problem? Tell us about it.**

**Steps to reproduce**
Steps to reproduce the problem:
1. Go to latest published participant-state-kvutils-proto-java in bintray.  The binaries and pom file are published by not the gen'd java source
e.g. https://digitalassetsdk.bintray.com/DigitalAssetSDK/com/daml/ledger/participant-state-kvutils-java-proto/100.13.8/

**What's your preferred solution?**
https://digitalassetsdk.bintray.com/DigitalAssetSDK/com/daml/ledger/participant-state-kvutils-java-proto/100.13.12/participant-state-kvutils-java-proto-sources-<sdk_version>.jar should be published to bintray as part of each SDK release

**Screenshots**
![image](https://user-images.githubusercontent.com/25179017/61151009-d23f2b80-a4b2-11e9-8b54-3a38094df9cb.png)

**About your system**
 - OS: (are you on Windows, OSX, Linux? Which version?)
 - SDK version : All including most recent 100.13.12

**Additional context**
daml_kvutils_java_proto generation defined in this BUILD.bazel file
https://github.com/digital-asset/daml/blob/dd77ea99e1396aaa8382faf48dc6bc5abdfc52fa/ledger/participant-state/kvutils/BUILD.bazel#L74-L77

**Comment by cocreature** [comment]
Is this still an issue @dasormeter?

**Comment by dasormeter** [comment]
Closing as there is no usage of bintray any longer
