### ISSUE TITLE
Generated code for kvutils java proto are not in classpath for intellij, preventing resolution and drillthrough of resultant classes from within IDE

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#2135]
**Steps to reproduce**
Steps to reproduce the problem:
1. Import DAML project into IntelliJ using "Import Bazel Project"
2. Once all is imported and Bazel project is healthy, load a class that uses the gen'd Java classes from kvutils java proto such as `KeyValueSubmission.scala`
3. When loading in IntelliJ the relevant gen'd classes cannot be resolved by IntelliJ
**What's your preferred solution?**
Imported classes resolved and clickable in IntelliJ - no errors shown visually

**Screenshots**
![image](https://user-images.githubusercontent.com/25179017/61151675-7b3a5600-a4b4-11e9-8416-3bdf3b99f814.png)

**About your system**
 - OS: OSX Mojave
 - SDK version: 0.13.12

**Additional context**
Consider whether following bazel process similar to scenario-service protos improves the situation
https://github.com/digital-asset/daml/blob/dcd20ace8a5ed7abb8081ba34879345ddf801bc0/compiler/scenario-service/protos/BUILD.bazel#L7-L46

daml_kvutils_java_proto generation defined in this BUILD.bazel file
https://github.com/digital-asset/daml/blob/dd77ea99e1396aaa8382faf48dc6bc5abdfc52fa/ledger/participant-state/kvutils/BUILD.bazel#L74-L77

**Comment by dasormeter** [comment]
related to #2134

**Comment by cocreature** [comment]
Is this still an issue @dasormeter?

**Comment by dasormeter** [comment]
no @cocreature I think we can close
