### ISSUE TITLE
Haskell executables should wait for child processes to exit

### ISSUE THREAD

**Issue by gaborh-da** [digital-asset/daml#2142]
`damlc`, `daml-helper` and the `daml` assistant all try to terminate child processes if they are terminated themselves by sending them a signal. However, they do not wait for the child processes to exit which is rather confusing.

It would be better if we used a variant of `withCreateProcess` that waits for the child processes to exit.

cc @associahedron

**Comment by associahedron** [comment]
We do use `withCreateProcess`. It does wait for sandbox to end, unless the parent process is killed, in which case the child processes are also killed (by `withCreateProcess`).

What is the issue you are experiencing, when using `daml sandbox`?

**Comment by cocreature** [comment]
The issue is exactly in `withCreateProcess`: When the parent process is killed we kill the children but we do not wait for them to terminate.

**Comment by associahedron** [comment]
> It would be better if we used a variant of withCreateProcess that waits for the child processes to exit.

Oh, I totally misread that sentence!
