### ISSUE TITLE
Compiler generates daml-lf 1.5 with type variables shadowed.

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#2148]
DAML-LF version 1.5 (or previous) did not accept type variables shadowing. 

In order to fix #1915, while minimizing future maintenance cost, we decided to relaxed globally this restriction in the engine type checker. 

To be sure, the standard users will not face any problem when loading with a old SDK,  daml-lf produced with the latest SDK version, we assumed the compiler will not  produce daml-lf 1.5 with type variables shadowed. 

It appears however that the current version of the compiler produces DAML-LF 1.5 with  type variables shadowed when compiling the daml standard library, hence breaking backward compatibility.

**Comment by hurryabit** [comment]
This is fixed by #2161, which drops support for DAML-LF 1.5 from `damlc`.
