### ISSUE TITLE
Add scenario function to read CSV files

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#2173]
We want a function `readCSV : Serializable a => Text -> Scenario [a]`.

Depending on how much of the conversion from `Text` to the `a` we do in DAML-LF, this might either be trivial or a require a serious amount of work.

**Comment by cocreature** [comment]
I don’t want to spend any effort on scenarios anymore and DAML script already has an `input-file` feature. That requires JSON instead of a CSV but I think converting CSV to JSON outside of DAML is simpler than parsing CSV in DAML so closing this.
