### ISSUE TITLE
Make template let desugaring only do things once

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#2175]
Using:
```haskell
template Person
  with
    person : Party
    name   : Text
  where
    let foo : Int -> Int
        foo _ = "test"
    signatory person
    controller person can
      Sleep : () do return ()
      nonconsuming Nap : Int with i : Int  do return $ foo i
```
I get much the same error (varying slightly with the context) repeating 5 times. That's because we desugar let bindings by duplication. We shouldn't do that!

It also causes issues if we don't have errors, e.g. DEL-6456 means we can't have unused binding warnings turned on.

**Comment by cocreature** [comment]
We have to do this 5 times. There is no place where we could store the result after computing it once. E.g., let’s say we compute it during `create`, we cannot store it anywhere so we get it in the choice body without adding an extra field to the template. This requires a change in DAML-LF and I don’t believe this is worth it so closing for now.

**Comment by nickchapman-da** [comment]
This issue is fixed
