### ISSUE TITLE
Allow choice argument to shadow template argument

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#2186]
```haskell
daml 1.2
module FieldNameClashTemplate where

template Clash with 
    p : Party
    clash : Text
  where
    signatory p

    controller p can
      DoStuff : Int
        with clash : Int
        do pure clash
```
fails to compile with
```
    * Conflicting definitions for `clash'
      Bound at: /home/martin/Github/demo/quickstart/daml/Main.daml:52:12-21
                /home/martin/Github/demo/quickstart/daml/Main.daml:52:12-21
    * In an equation for `choice'
```
This this caused by the fact that we desugar the choice body as
```haskell
actionClashDoStuff self Clash{..} DoStuff{..} = ...
```
If we desugared it as
```haskell
actionClashDoStuff self Clash{..} = \DoStuff{..} -> ...
```
the problem should go away.

**Comment by samuel-williams-da** [comment]
Desugared `actionClashDoStuff self Clash{..} = \DoStuff{..} -> ...` syntax leads to a `Collapse lambdas` lint recommendation, which obviously cannot stay - need to consider if theres a way around it - say some hack like `actionClashDoStuff self Clash{..} = identity $ \DoStuff{..} -> ...`, or if we disable the linter suggestion altogether (or per file)
