### ISSUE TITLE
Allow for rollback of sub-transactions within DAML workflow

### ISSUE THREAD

**Issue by andrae-da** [digital-asset/daml#22]
A cursory review of the business requirements for production DAML projects suggests that >90% of any given workflow is specifying exceptional workflows to handle business constraint violations.

At the present point in time, DAML only permits a single response to a business constraint violation: `abort` the current transaction in its entirety. Unfortunately, this leaves the system in an invalid state, as the business requirement is for the workflow to transition to an error handling/recovery state, and this would require updating the ledger—something that is currently impossible once an `abort` has been triggered.

What is needed is the ability to 'catch' the abort at a sub-transaction level, and then proceed with an alternative ledger-update. It is anticipated that this would end up looking something along the lines of `MonadError`.

Worth noting that:
- This is not an asynchronous exception capability, specifically:
- Failures of `fetchBy`, `fetch`, key-uniqueness violations, exercises on inactive cids are all contention failures only detectable at post-sequence validation, _not_ business constraint violations, so do not interact with this feature
- `ensuring` violations and `assert`/`abort` violations _do_ represent business constraint violations, and so _should_ interact with this feature
- This would entail requiring `assert`/`abort` to take any instance of `Show` as an argument.
- `Update a`, would now become a right-biased `Update e a`
- If the exception remains uncaught at the outer transaction, then the behaviour remains identical to the current behaviour, except for an implicit call to `show e` go obtain a string

Note: Our experience to date suggests that any non-trivial, real-world, multi-party workflow requires this functionality.

**Comment by filmackay** [comment]
> @andrae-da can you help me understand the desired semantics from your perspective. In the `Complete` choice, assume the withdrawal succeeds, but the deposit throws. Is it desired that the withdrawal still goes through?

The way it is written, the deposit throws it is handled and not re-thrown, so therefore the withdrawl stands. Semantics are similar to a TSQL?

> Furthermore, I see one immediate question from a platform implementation perspective. Let's remove the keys and the two `lookupByKey` actions from `Complete` in your example and pass `fromCid` and `toCid` as template arguments. Assume that the withdrawal throws. However, for it to throw, the `fromCid` contract must be active. How do we get all validators to check the activeness? One option is to replace the withdrawal `Exercise` action by a `Fetch`.

Does't `Exercise` implicitly check for activeness? If an exercise/fetch fails this would create an abort, which is non-catchable. Party of the second category of failures that would be unchanged from the current model.

> Generally, I agree with @meiersi-da , this will need some careful thought, and I'd like us to have an update to the LF spec and the ledger model if necessary before this enters production. Also, when coming up with the right solution and the right semantics, it'd be helpful to have a small catalogue of relevant business examples with their requirements (not necessarily code) specified, where you expect this feature to help, such that we can validate the solution.

We have a lot of these - we try to catch everything that fail deterministically, and leave races/contention to abort and retry. But we are a bit trapped with things like arithmetic unless we built a special safe library.

For Spider, anything that "fails" (other than a race/contention issue) needs to "succeed" in that we create a contract evidencing a error back on the ledger.

**Comment by oggy-** [comment]
> Does't Exercise implicitly check for activeness? If an exercise/fetch fails this would create an abort, which is non-catchable. Party of the second category of failures that would be unchanged from the current model.

Right, I didn't express myself clearly enough. What I meant is: if we record an `Exercise` in the transaction, this would consume the contract. But since the exercise didn't actually succeed, I assume that the desired semantics would be not to consume the contract.

> We have a lot of these - we try to catch everything that fail deterministically, and leave races/contention to abort and retry. But we are a bit trapped with things like arithmetic unless we built a special safe library.

I trust that you do. But for us who are not so deeply caught in the web, it's helpful to have another 2-3 characteristic examples that are currently painful such that we can evaluate the proposed solutions against them.

> For Spider, anything that "fails" (other than a race/contention issue) needs to "succeed" in that we create a contract evidencing a error back on the ledger.

So for example, if a trade comes in for a party whose master service agreement has been revoked, is this a race condition, or something that should be evidenced?

**Comment by francesco-da** [comment]
hi all, thanks for the discussion. i think by now it's reasonably clear what this proposal is about -- introducing "delimited rollbacks" to the update monad. it also seems clear that this would have an impact on the transaction structure, since we'd need to record what happened in failed branches.

in other words, this is not a small feature and probably has far-reaching consequences that we need time to examine. moreover, as @andrae-da says, we have other changes in the pipeline that we are in the process of including.

so, we're going to put this proposal in the backlog for now and come back to it after a few other things have settled in a month or two.

**Comment by andrae-da** [comment]
> @andrae-da can you help me understand the desired semantics from your perspective. In the `Complete` choice, assume the withdrawal succeeds, but the deposit throws. Is it desired that the withdrawal still goes through?
> 

As @filmackay commented, the error is caught and handled, so yes it should definitely succeed. Of course this is provided the `SuspendDeposit` choice in the `Deposit` rollback-handler does not itself fail, but that can't happen in the example as written.

> Furthermore, I see one immediate question from a platform implementation perspective. Let's remove the keys and the two `lookupByKey` actions from `Complete` in your example and pass `fromCid` and `toCid` as template arguments. Assume that the withdrawal throws. However, for it to throw, the `fromCid` contract must be active. How do we get all validators to check the activeness? One option is to replace the withdrawal `Exercise` action by a `Fetch`.

As `Withdrawal` can have its own fetches and exercises that must themselves be validated, I don't believe this is an option. My suggestion was that we should introduce an attribute to `Exercise` nodes to mark them as "Succeeded" or "Failed". Then validators do not need to change anything, only the code that maintains the ledger state needs to track whether or not there is a "Failed" node within its path to the root.

> Generally, I agree with @meiersi-da , this will need some careful thought, and I'd like us to have an update to the LF spec and the ledger model if necessary before this enters production. Also, when coming up with the right solution and the right semantics, it'd be helpful to have a small catalogue of relevant business examples with their requirements (not necessarily code) specified, where you expect this feature to help, such that we can validate the solution.

I'm not sure why we would need to change the ledger model to support this? There is still just a transaction tree, that gets sequenced, and can produce a series of ledger updates. The LF-spec will probably need to change slightly to accommodate this though.

Regarding examples, Spider currently supports 21 distinct ingress messages, each of which can initiate an average of 3-4 workflows, all of which require this functionality.

**Comment by oggy-** [comment]
My current thoughts:

1. this is definitely not just an LF change, it requires a change to the ledger model, and thus all ledger implementations. However I think it's relatively minor and nothing unexpected, you pretty much hinted at it above: every DAML action comes in a "roll-forward" (i.e., the current) and "roll-back" variant, and all of its subactions must be of the same variant as the action itself. Authorization and visibility rules of the roll-back variants are the same as for the roll-forward variant. Consistency rules are different though; rolled-back consuming `Exercises` are actually non-consuming, and rolled-back `Creates` are no-ops, except if they are on keyed contracts, in which case they turn into `NoSuchKey`.

2. I think we actually have a design choice: we can either make the DAML contract model "rollback-closed" (how's that for an impenetrable name?), or we can leave it to the developer.

    a) rollback-closed: whenever a roll-forward action variant is in the model, then so is its roll-back variant. This is the option you assumed. This has privacy implications and makes us non-backwards compatible in that sense, i.e., it changes the semantics of existing contracts. E.g., if we have an innocuous `DvD` contract with a choice such as:

    ```
    choice Perform: ...
        with
         sellerIouCid: ContractId Iou
         buyerIouCid: ContractId Iou
         actor: Party
        do
          assert $ actor == seller || actor == buyer
          sellerIou <- fetch sellerIouCid
          buyerIou <- fetch buyerIouCid
          ...
    ```
    which would allow both the seller and the buyer to probe every Iou of the other party they know for activeness. Similar (though probably more contrived) examples can be made for `Creates` with keys

    b) we make roll-back optional, and let the DAML author indicate which actions may be rolled back. In particular, I think only exercises and keyed contract creations are relevant. The downside of this is that it's a bit less compositional. So if a popular library defines a choice without a roll-back option, you can build anything on top that can be rolled back. We might be more lenient and allow a roll-backable exercise to do all the roll-backable updates first, and then the non-roll-backable exercises later by typing the Update's `bind` appropriately, but I don't know if this is feasible. The other option is to have a `only roll-forward` annotation instead of `may roll-back`, but that would again make us backwards incompatible.

3. I'd vote a strong no for making the exceptions from failed fetches/exercises catchable. Luring people into thinking that there's no contention is one problem, but there's also another one, which is that this would require an equivalent of a `NoSuchContract` action in the ledger model. This would create the same problems as `NoSuchKey` for Canton (the scope of the `NoSuchContract` statement is unclear, is it per participant, per domain, etc). Catching failed creates is probably OK, though (as long as they don't create keys).

**Comment by andrae-da** [comment]
Regarding:

1. Agreed completely.
2. Rollback-open prevents one of the primary motivations behind exceptions — the ability to compose workflows into atomic workflows, by requiring workflow authors to explicitly authorise composition. Fortunately, the privacy example you provide requires fetch authorisation on the probed contract, and if we have that, we can already probe by composing `exercise cid Perform` before `fetch flagCid`, and submitting it immediately after `exercise flagCid Archive`, and observing which fetch failed (we'll call this the timing-example). If we don't have fetch auth, then both the exception-example and the timing-example fail with an authorization failure, not a double-spend failure.
3. A reminder that this proposal is for catching language/interpreter exceptions, not ledger-model constraint violations. So contract-key violations, double-spend, fetch failures, etc are out-of-scope for this proposal. So I agree wholeheartedly with a strong no for making exceptions from failed fetches/exercises catchable, as these are ledger-model constraint violations.

**Comment by cocreature** [comment]
this is covered as part of exceptions in daml-lf 1.14
