### ISSUE TITLE
typeclass names in daml stdlib doc not generated correctly

### ISSUE THREAD

**Issue by lJoublanc** [digital-asset/daml#2221]
On the live website https://docs.daml.com/daml/reference/base.html, as at 18/07/2019, some of the doc for the typeclasses doesn't appear to be generated correctly. e.g. the second class has a heading

`class (`Action <class-da-internal-prelude-action-24943_>`_ m) => CanAbort m where`

That looks like a problem with the code generation.

**Comment by hurryabit** [comment]
@associahedron That looks like one for you.

**Comment by associahedron** [comment]
Hi @lJoublanc, thank you for the bug report!

This issue has already been fixed in #2202 and should be in the next release of the docs.
