### ISSUE TITLE
CI instability due to external servers failing

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#2231]
Over the past few days I have been investigating options to reduce the number of flaky failures on CI due to external servers not responding. I have not found any option I am happy with, so I thought I'd summarize my findings here and invite more input.

The options I have considered can be reduced to variations on two main ideas:
1. Copy all external artifacts to a known location we control (which would be a GCS bucket), or
2. Install a transparent web proxy for our build nodes.

# GCS bucket

This idea is very simple: we'd create a new GCS bucket, similar to the ones we have for the nix and Bazel caches (though probably without the expiration policy), and manually copy our dependencies there. We could use a content-based naming scheme, i.e. artifacts would be located under `/<hash>/name.ext`, making it easy to periodically check for corruption.

This has the following advantages:
- GCS has been very reliable for us so far, and we already have a completely blocking dependency on it anyway, so this does not introduce a new moving piece that can fail to our build process.
- There is no ongoing maintenance cost as Google handles all the servers magically behind the scenes and we can just pretend it's a big shared hard drive.
- It does not require any special access rules beyond what we already have, so that bucket could, just like the caches, be open to the world in read-only mode.
- The caching is completely explicit: looking at the URLs in the repo, it would be evident that packages are fetched from our own cache.

And the following disadvantages:
- It requires replacing all URLs in our build definitions by URLs we create. This is going to be very tedious and a lot of initial effort, plus some ongoing effort every time we change or add a dependency.
- Upgrades become harder because in addition to having to copy the new artifact to the GCS bucket, it may also not be obvious where to look for the next version.
- It's easy to slip: we could still add external URLs easily, and thus reintroduce flakiness.
- It cannot cover URLs that are not explicitly defined in our repo (e.g. I believe npm dependencies).

# Transparent proxy

The other main option would be to set up a new server within our network, running a transparent caching proxy server (e.g. [squid](http://www.squid-cache.org)), and rely on the `http_proxy` and `https_proxy` environment variables (and their uppercase equivalents).

We'd need to define a sensible caching policy. It is not obvious to me what is the best approach here: too little caching and we do not solve anything; too much caching and we may not detect when external links are dead (or now return a different result), making a failure of this cache potentially very costly. There is probably a sweet spot around twice the length of the outages we want to be isolated from, so something like:
- Once the cache gets a result, it considers it fresh for a day (i.e. does not even look at the original server for a day)
- For two days after that (hours 25 to 72 after receiving the response), upon request the cache tries to contact the original server to refresh its own copy, but if the server does not send a successful response, the cache keeps serving its own local copy.

This has the following advantages:
- Caching is implicit, meaning there is no need to change any URL in our existing dependency definitions.
- Caching will work for any tool we use that supports `http_proxy`, so it could cover external dependencies that are not explicit URLs in our files (e.g. npm ones).
- This may make builds slightly faster as the cache would be co-located with the CI nodes.

And the following disadvantages:
- The macOS nodes are not colocated with the other ones, so they would still have to go through a potentially flaky, slow network connection.
- The macOS nodes being external mean this proxy server needs to be accessible from the internet, which introduces _a lot_ of complexity around correctly securing it; HTTP proxy software is _not_ designed for this.
- Not including the macOS nodes in the proxying would solve the security issues, but would not unblock any build when there is a systemic failure on an external system, so the benefit would be very minimal.
- This may still not cover all of our external dependencies, as we would be relying on software honouring the `http_proxy` env var (and all our tooling to correctly propagate that env var to subprocesses).

From a security perspective, the node hosting the cache server would need to be regularly patched and ideally regularly destroyed and recreated. To a large extent this negates the whole point of having the cache in the first place. Similarly, running multiple nodes in parallel to avoid downtimes during cache server upgrades will dilute the effectiveness of the cache.

# Do nothing

The obvious alternative is to do nothing about it and just keep suffering through the outages. Given the time I've already spent on this, the frequency of outages and all the other sources of flakiness we have, this is my preferred option at this point.

**Comment by cocreature** [comment]
Thanks for the detailed writeup! While it makes me somewhat sad to say this, I agree that not doing anything seems like the most sensible option at the moment.

**Comment by flokli** [comment]
External dependencies fetched via nix shouldn't be too flaky, as those are already persisted in the GCS bucket.

As far as bazel goes, https://docs.google.com/document/d/1aagKnM8kRmMvLqSXasShsI-NYOBZYtgNrbYWLPwBoBg/edit and https://github.com/bazelbuild/bazel/issues/6359 might help too.

**Comment by garyverhaegen-da** [comment]
We've done various small fixes over time, and there days CI fails a lot more because of our own flaky tests than any external source. I don't think we need to address this anymore.
