### ISSUE TITLE
setTime RPC in ledger API has wrong behaviour

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#2245]
The `setTime` RPC  from the ledger API `TimeService` implemented by the sandbox doesn't match the spec in: `time_service.proto`. In particular:
```
  // MUST precisely match the current time as it's known to the ledger server.
  // On mismatch, an ``INVALID_PARAMETER`` gRPC error will be returned.
  google.protobuf.Timestamp current_time = 2;
```
I am seeing the following: If an incorrect `current_time` is passed, the ledger is not updated with the `new_time`, but no gRPC error is returned.

**Comment by gerolf-da** [comment]
I cannot reproduce the behavior. If I change the time with navigator, I can see the error message:
```
Failed to set time for request [SetTimeRequest(sandbox-e8ce7604-c98a-4a9b-a813-f16eea162d59,Some(Timestamp(86400,0)),Some(Timestamp(0,0))), INVALID_ARGUMENT: new_time [1970-01-01T00:00:00Z] is before current_time [1970-01-02T00:00:00Z]. Setting time backwards is not allowed.]: {}
```

**Comment by stefanobaghino-da** [comment]
@nickchapman-da can you follow up on @gerolf-da's question?

**Comment by stefanobaghino-da** [comment]
No feedback, closing.
