### ISSUE TITLE
ListKnownPackages errors if called before GetLedgerIdentity

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#2260]
If `ListKnownPackages` from `package_management_service.proto` is called before `GetLedgerIdentity` has ever been called, then the GRPC call errors with a timeout.

Putting in a dummy call to `GetLedgerIdentity` fixes the problem, and the results are returned as expected.

**Comment by gerolf-da** [comment]
Does that happen for both the postgres and the in-memory sandbox?

**Comment by nickchapman-da** [comment]
I've only been using the in-memory sandbox.

**Comment by gerolf-da** [comment]
@nickchapman-da: Can you reproduce this issue with the following steps?
1) Start sandbox with or without a dar file loaded
2) run the command: 
```
grpcurl -plaintext localhost:6865 com.digitalasset.ledger.api.v1.admin.PackageManagementService/ListKnownPackages
```

According to your description, this should result in an error, but in both cases (with and without dar) I get a proper response.

**Comment by nickchapman-da** [comment]
I dont have grpcurl. How can install this on Linux?

**Comment by nickchapman-da** [comment]
You can reproduce the issue from Haskell by uncommenting here:
https://github.com/digital-asset/daml/blob/master/language-support/hs/bindings/test/DA/Ledger/Tests.hs#L356

**Comment by nickchapman-da** [comment]
Is it possible that the ListKnownPackages only fails if it is called before the sandbox has properly initialised itself? But GetLedgerIdentity does wait until things are ready.

This might explain why your test does not reveal an issue: because you startup the sandbox and run the grpcurl by hand at the command line, and you leave a long enough pause between the calls.

Please note: the above is all just random speculation :)

**Comment by cocreature** [comment]
@nickchapman-da `grpcurl` is part of our dev-env.

**Comment by nickchapman-da** [comment]
thank you Moritz!

**Comment by nickchapman-da** [comment]
Works as expected I guess
```
$ grpcurl -plaintext localhost:6865 com.digitalasset.ledger.api.v1.admin.PackageManagementService/ListKnownPackages
{
  
}
```

**Comment by gerolf-da** [comment]
I just ran the tests myself, and the "timeout" is detected veeeeery quickly (< 1s). Presumably the timeout should be 30 seconds from here?
https://github.com/digital-asset/daml/blob/16259ab00f0f62afba057d59b829ef21c5c96134/language-support/hs/bindings/test/DA/Ledger/Tests.hs#L556

**Comment by gerolf-da** [comment]
Adding `threadDelay 10000` instead of `_ <- getLedgerIdentity` makes the test succeed. Could you check that the provided timeout is actually respected? The sandbox loads dars on startup, so maybe that's why it takes longer to process the request? In any case, the 30 second timeout doesn't seem to be used.

**Comment by nickchapman-da** [comment]
I don't think the 30s timeout is related the issue.
I think the problem might be that the ListKnownPackagses call is made following a sandbox reset.
And the client side logic which detects when the sandbox is available again is not working.
I'll investigate some more...

**Comment by nickchapman-da** [comment]
Ok. so the problem is in the retry handling in the haskell ledger bindings. It is broken for some ledger services.  I have the fix for the current example. But I am going to restructure the code to be a bit more DRY, so it can't be forgotten in new ledger-services.
