### ISSUE TITLE
daml-docs should display anchor links next to definitions

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#2283]
Every definition by daml-docs is reachable via an anchor link. However, when you are browsing the docs it is not obvious how you get the anchor link for the definition you are currently looking at short of opening the inspector in your browser.

There are a few ways we could go about this:

1. Turn the name of the definition into a link to itself.
2. Display the link on hover, next to the definition (e.g., with a `#` as the text).
3. Display the link unconditionally but all the way on the right to not get in the way.

I think we did 2. at some point, 3. is what Hackage does but it is very easy to miss the link ime.
Doing 2. unconditionally is a bit too noisy ime. 1. is what the rust docs do and seems like the best solution to me.

**Comment by cocreature** [comment]
1. seems to run into the usual issue of RST not supporting nested markup.

**Comment by associahedron** [comment]
1 can be still be done by creating the link instead of bolding the text, where possible.

**Comment by associahedron** [comment]
Still open for Markdown/HTML rendering.
