### ISSUE TITLE
Add Numeric type to LF

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#2289]
DAML-LF `Decimal` types have fixed precision (i.e. 38) and fixed scale (i.e. 10).

We will substitute the original `Decimal` types by a new `Numeric` types with fixed precision (still 38) but parametrizable scale (between 0 and 37). Note the max scale is 37 (and not 38) because we want 1 to be representable at any valid scale. 

Here is a plan:

+ We create a new DAML-LF (let's name it 1.x)
  
  - We add the kind `nat`, so kinds are of the form:
    
    ```
    k  := * | nat | k -> k
    ```
  
  - We create a family of types of kind `nat`, denoted by integer. 
  
  - We replace the `Decimal` type by the higher-order type `Numeric`:
   
    ```
    Numeric : nat -> * 
    ``` 
    
    We will call the parameter (of kind `nat`), the scale.
    
    for any scale `n`, `(Numeric n)` is serializable but `Numeric` is not.
  
  - We replace `Decimal`  literal by `Numeric` literals. Numeric literals are encoded by strings that match `[-+]?\d+.\d*` and where the number of decimal digits specified the scale. For instance:
    ```
    0. : Numeric 0
    1.0 : Numeric 1 
    3.1415926535897932384626433832795028841 : Numeric 37
    ```
  
  - Decimal builtins are modified as follows:
    
    ```
    ADD_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Numeric s
    SUB_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Numeric s
    MUL_NUMERIC: ∀(s1 s2 s:nat). Numeric s1 → Numeric s2 → Numeric s
    DIV_NUMERIC: ∀(s1 s2 s:nat). Numeric s1 → Numeric s2 → Numeric s
    ROUND_NUMERIC: ∀(s:nat). Int64 → Numeric s → Numeric s
    INT64_TO_NUMERIC: ∀(s:nat). Numeric s → Int64
    EQUAL_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Bool
    LEQ_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Bool
    GEQ_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Bool
    LESS_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Bool
    GREATER_NUMERIC: ∀(s:nat). Numeric s → Numeric s → Bool
    FROM_TEXT_NUMERIC:  ∀(s:nat). Text → Numeric s
    TO_TEXT_NUMERIC: ∀(s:nat). Numeric s → Text 
    ```
  
  - We provide also a set of new builtins. The following is a not definitive  proposal.
    
    ```
    CAST_NUMERIC: ∀(s1:nat, s2:nat). Numeric s1 → Numeric s2
    SHIFT_NUMERIC: ∀(s1:nat, s2:nat). Numeric s1 → Numeric s2
    ```
    
    `CAST_NUMERIC` converts a Numeric from one scale to another while keeping the value the same.
    If the value does not fit (number is too large, or loss of precision would occur), it raises an error.

    `SHIFT_NUMERIC` converts a Numeric from one scale to another by shifting the decimal place. Thus it will multiply or divide the value by some power of 10. This will never fail.

+ archive backward compatibility:

   - We create a new `NUMERIC` version for all proto `DECIMAL` messages 

  - Builtin type  `TDecimal` becomes an alias for `TNumeric 10`

  - `Decimal` builtin function are converted automatically to their `Numeric` counterpart applied to the type `10`
         
+ For the Values (we create a new version of the value):  

  - Decimal values are replaced by Numeric values. Type of such value should 
    always come with scale.

  - For (un)serialization:  
    - if LF version < 1.x, we serialize `Numeric` as `Decimal` was done, that 
      we drop trailing zeros.
    - if LF version >= `1.x`, we serialize with trailing zeros to indicate the 
      scale, that is the number of decimal digits indicate the scale. 
      
+ For the ledger API: 

  - For `Numeric` input, we accept any string which matches `[+-]?\d+(\.\d+)?`
    as long the corresponding bigDecimal have precision <= 38 and  a positive 
    scale 38. Scale will be verified during value type checking (append during 
    compilation to Speedy)
    
  - As `Numeric` output, we produce strings that match `[+-]?\d+(\.\d+)?`, 
    where the number of decimal digits indicate the scale.       
           
fixes #1706
fixes #1729

**Comment by associahedron** [comment]
Looks awesome. Some notes from me.

> We will substitute the original Decimal types by a new Numeric types with fixed scale (still 38) but parametrizable scale (between 0 and 38).

I think you mean "new Numeric types with fixed *precision* (still 38)" here.

>   * We replace Decimal  literal by Numeric literal with type `∀(s:nat). Numeric s`.

This is a bit confusing to me. My understanding is that a literal will have the type `Numeric s` for fresh `s`. Perhaps it would be nice to give an example.

>   * We provide also the new builtin:
>     ```
>     CAST_NUMERIC: ∀(s1:nat, s2:nat). Numeric s1 → Numeric s2
>     ```
>     the builtin fails in case of overflow or lost of precision.

This means there will be no way to convert between different scales without loss of precision. It would probably be useful to have a `SHIFT_NUMERIC: ∀(s1:nat, s2:nat). Numeric s1 → Numeric s2` that limits itself to shifting the decimal place, leaving the digits as is, without the possibility of overflow or underflow.

**Comment by remyhaemmerle-da** [comment]
> I think you mean "new Numeric types with fixed _precision_ (still 38)" here.

Indeed. It is fixed. 

> > * We replace Decimal  literal by Numeric literal with type `∀(s:nat). Numeric s`.
> 
> This is a bit confusing to me. My understanding is that a literal will have the type `Numeric s` for fresh `s`. Perhaps it would be nice to give an example.

I am not sure I understand. 
The idea is that numeric literals need to be parametrized with there scale. For instance if you want the the numeric Zero with scale 10, you should use the expression `(0.0 @10)` (where @ is the type application within expression).

This is usefull if you want to write generic DAML-LF funcions, like for instance.
```
val incr: ∀(s:nat) -> Numeric s -> Numeric s = 
  Λ (s : nat).  λ (x: Numeric s) . ADD_NUMERIC @s (1.0 @s) x
```
   

> > * We provide also the new builtin:
> >   ```
> >   CAST_NUMERIC: ∀(s1:nat, s2:nat). Numeric s1 → Numeric s2
> >   ```
> >   
> >   
> >   the builtin fails in case of overflow or loss of precision.
> 
> This means there will be no way to convert between different scales without loss of precision. It would probably be useful to have a `SHIFT_NUMERIC: ∀(s1:nat, s2:nat). Numeric s1 → Numeric s2` that limits itself to shifting the decimal place, leaving the digits as is, without the possibility of overflow or underflow.

I am still not sure I understand. 
-  ``CAST_NUMERIC`` will ensure there is no loss of precision. 
- If you want ti convert with  loss of precision, first you round, then you cast.

**Comment by remyhaemmerle-da** [comment]
I change my mind with Numeric literal. Numeric literal have now a fixed scale. 
To implement a `incr` function parametrize by a `scale`, you could write: 
```
val incr: ∀(s:nat) -> Numeric s -> Numeric s = 
  Λ (s : nat).  λ (x: Numeric s) . ADD_NUMERIC @s (CAST_NUMERIC @0 @s 1) x 
```

**Comment by associahedron** [comment]
I mean that if `CAST_NUMERIC` keeps the *values* the same, there will be no way to multiply a number by 10^9, for example, and adjust the scale at the same time. The best you can do is either:

* multiplying, and then casting to the new scale
* casting to the new scale, and then multiplying
* truncating, then casting to the new scale, and then multiplying

The first option risks overflow when multiplying.

The second option risks underflow when casting (i.e. the operation will fail).

The third results in less precision -- you lose 9 digits of precision for no reason.

That's why I think it would be good to have a `SHIFT_DECIMAL` that changes the scale while multiplying by a power of 10. In other words, it shifts the decimal point. (The "mantissa" stays the same.) For example `SHIFT_DECIMAL @0 @3 1.` computes to `0.001`.

Since all Numerics have the same precision, there's no reason changing the scale in this way should result in loss of precision.

> I changed my mind with Numeric literal. Numeric literal have now a fixed scale.

That seems better.

**Comment by associahedron** [comment]
(You can implement the successful cases of `CAST_DECIMAL` using `SHIFT_DECIMAL`, but not the other way around. I think it's better to have both.)

**Comment by remyhaemmerle-da** [comment]
@associahedron Good point. I add it.

**Comment by hurryabit** [comment]
We should consider adding a function to round and cast at the same time, say
```
ROUND_AND_CAST_NUMERIC: forall s1 s2. Numeric s1 -> Numeric s2
```
We can't implement this using `ROUND_NUMERIC` and `CAST_NUMERIC` since there's no way to lower a type level number to a value level number.

**Comment by remyhaemmerle-da** [comment]
Let's start the development without any builtin. We should specify and implement those before closing the issue.

**Comment by remyhaemmerle-da** [comment]
What do you thing to directly to generalize multiplication and division like that ? 

```
MUL_NUMERIC: ∀(s1, s2, s:nat). Numeric s1 → Numeric s2 → Numeric s
DIV_NUMERIC: ∀(s1, s2, s:nat). Numeric s1 → Numeric s2 → Numeric s
```

**Comment by hurryabit** [comment]
> What do you thing about directly generalizing multiplication and division as follows ?
> 
> ```
> MUL_NUMERIC: ∀(s1, s2, s:nat). Numeric s1 → Numeric s2 → Numeric s
> DIV_NUMERIC: ∀(s1, s2, s:nat). Numeric s1 → Numeric s2 → Numeric s
> ```

I think we should not mix things up. If this turns out to be valuable in the future, let's do it then in a separate primitive.

**Comment by associahedron** [comment]
> What do you thing about directly generalizing multiplication and division as follows ?
> 
> ```
> MUL_NUMERIC: ∀(s1, s2, s:nat). Numeric s1 → Numeric s2 → Numeric s
> DIV_NUMERIC: ∀(s1, s2, s:nat). Numeric s1 → Numeric s2 → Numeric s
> ```

In principle there's nothing wrong with having the multiple scale multiplication and division at the LF level. `DIV_NUMERIC` would make it easy to implement a polymorphic `fromRational` (necessary to convert polymorphic numeric literals in DAML to numeric expressions in DAML-LF)

In the stdlib though we only expose a single scale multiplication (because of typeclasses). We could expose a special numeric multiplication with the multiple scales in `DA.Math`, but unless there's demand for it, we probably shouldn't.

**Comment by associahedron** [comment]
Update of `DA.Math` functions for `Numeric` is delayed until #1066 or until someone (e.g. @bame-da) makes the implementation polymorphic in scale.
