### ISSUE TITLE
Allow the sandbox to support multiple independent ledgers

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#2301]
Suggestion for the sandbox :

Allow the sandbox to support multiple independent ledgers.

This might be implemented as a `NewLedgerService` supporting a `NewLedger` RPC. When this RPC is called, a port would be dynamically allocated by the sandbox and returned as the response to the `NewLedger` request. The sandbox would then service this new port as an independent ledger. You might also want a `StopLedger` request as well.

This would be great for testing. Nicer than using the `ResetService`.

**Comment by stefanobaghino-da** [comment]
I wholeheartedly discourage using the `ResetService`.

Where possible (issuing commands and reading transactions) for testing we recommend isolating your tests by allocating parties for each test and sticking to those in the test body, which also allows you to run all tests in parallel (something you cannot do using the `ResetService`). If you're using implicit party allocation, this simply means using names that are unique to each test case.

This leave out tests that need to perform admin tasks that alter the global state of the ledger (e.g. configuration changes), which can be run sequentially at the end of the run.

This is the approach taken by the Ledger API test tool.

So-called _virtual ledgers_ are not in the roadmap.
