### ISSUE TITLE
Allocate parties in daml deploy.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#2312]
Allocate parties (with the party management service) as part of `daml deploy`. This should probably be configurable in daml.yaml, under some `deploy` header. Unclear what should be done on subsequent deploys, though -- should parties be searched for instead of allocated again? 

cc @nickchapman-da

**Comment by associahedron** [comment]
> soren  35 minutes ago
> A useful feature would also be to control which parties are allocated, as in Canton we can have multiple participant nodes each hosting a subset of parties

**Comment by cocreature** [comment]
I believe we have fixed this? Feel free to reopen if I missed something.
