### ISSUE TITLE
Race condition in java bindings (probably)

### ISSUE THREAD

**Issue by ghomanyi** [digital-asset/daml#2356]
I am working on a java application which contains several bots wired by the `Bot.wire` mechanism. The observed behavior:
* During initial market setup one bot creates a contract. 
* The created contract (`ExecutionAgreementInvitation`) triggers another bot, which exercises a consuming choice on it (Pending set maintained)
* The command is successful, however next time the bot function is triggered, the LedgerView of that bot still contains the very same contractId.
* Therefore the bot attempts to exercise again
* The second exercise fails with `INVALID_ARGUMENT: Command interpretation error in LF-DAMLe: dependency error: couldn't find contract AbsoluteContractId(#48:1). Details: N/A.`
* Next time the same contracId is still present on the LedgerView, so the app starts to loop while sandbox keeps reporting the dependency error.

This doesn't happen always, sometimes the setup is successful. Especially if the number of bots in the application is low, the success rate is much higher than the case with lots of bots.

When I set the SDK to an old version (0.12.15) to test the issue: all the attempts were successful (20 in a row). So seems that this behavior was introduced in the recent releases.

So far I saw this happening on a single template (`ExecutionAgreementInvitation`) but the actual contractId may vary (#48:1, #49:1, #50:1) depending on which instance of the bot meets the issue.

I have a branch prepared to reproduce the issue, I can share the details if needed.

**Comment by stefanobaghino-da** [comment]
This is very sneaky, apparently it was already there in earlier releases but the rate at which it fails seems to be way higher in recent ones. Still investigating.

**Comment by stefanobaghino-da** [comment]
0.12.21 seems to be the version starting from which the flakiness starts. Still unable to pin down a specific change that could have triggered this.

**Comment by stefanobaghino-da** [comment]
Numerous runs seem to point at https://github.com/digital-asset/daml/pull/1362 as the possible cause of the issue. Running the tests against sandbox at revision https://github.com/digital-asset/daml/commit/ff088efd94cffc523e56219bf7978251b0c617c5 using SDK 0.12.20 dependencies (0.12.21 work only with DAML 1.5, whose support lands later on between 0.12.20 and 0.12.21) causes around 1 in every 4 or 5 tests to end up in the infinite loop described. Quite hard to tell what could have caused this issue at the moment, thought.

**Comment by stefanobaghino-da** [comment]
So it looks like it's a sandbox issue from my experimentation, rather then a bindings one.

**Comment by tamaskalcza-da** [comment]
Hi @gerolf-da @stefanobaghino-da, do you have an update on this?

**Comment by stefanobaghino-da** [comment]
We haven't been able to look into this so far. Just out of curiosity, is the problem still there with the latest version of the SDK?
