### ISSUE TITLE
HTTP JSON API JWT Authentication

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#2360]
JWT Authentication and Authorization will be implemented on the Ledger side.
HTTP JSON API would not do any JWT validation by default. However we provide a functionality to override the default pass-through logic. Anyone customizing HTTP JSON API can pass `validateJwt` argument to `com.digitalasset.http.HttpService#start`:
https://github.com/digital-asset/daml/blob/689d4d876ca168e0d680a9e24a3d23e53a22c6b4/ledger-service/http-json/src/main/scala/com/digitalasset/http/HttpService.scala#L44-L49

JWT pass-through is blocked by: #2523
also depends on: #2540

**Comment by S11001001** [comment]
ledger-service/http-json does not have to _verify_ the JWT token; it only needs to read the data to find the party and ledgerId. It should pass the token through so signature verification can be done upstream.

This only applies if the payload is always unencrypted. If we have production scenarios where the payload _is_ encrypted, then we'll have to support verification.

From discussion with @gerolf-da

**Comment by gerolf-da** [comment]
It is also possible/allowed to [replicate claims as header parameters](https://tools.ietf.org/html/rfc7519#section-5.3) in case decryption is not possible at some points in the pipeline (as would be the case of the ledger services). In our case, we would require that the token issuer puts ledgerId, applicationId, and party unencrypted into the header as well. The actual capability-claims (like admin or read-only, ...) could still remain in the encrypted body without affecting the functionality of the high level API.

**Comment by leo-da** [comment]
@S11001001 you cannot decode a token without verification... actually decoding is verification. Right now it is with a secret, but eventually will be with a public key fetched via JWKS API: https://auth0.com/docs/jwks

**Comment by leo-da** [comment]
@S11001001 @gerolf-da yep, we can do this... so I can base64 decode the token, take the party and ledger id from there and pass them to the created API commands/requests. However the current ledger api implementation does not support passing JWT. So, I'd say let keep the verification for now and we can easily remove it once the ledger api supports JWT verification.

**Comment by leo-da** [comment]
@gerolf-da JWT header and payload are unecnrypted, they are just base64 encoded. However JWT has a signature that is supposed to guarantee that the header and payload has not been changed.

**Comment by darkedges** [comment]
> ledger-service/http-json does not have to _verify_ the JWT token; 

IMHO this is a very bad approach, the JWT token should be verified at each boundary to ensure it is valid. If you leave it to the very end of the process, you may have performed unnecessary processing.

Also any thoughts on how this will be eventually done? Are you expecting to use JWKS hosted somewhere? Or some other mechanism?

**Comment by darkedges** [comment]
>  We can declare that we only support unencrypted tokens.

Why limit what can be done from the beginning? There are a number of established java libraries available that provide the functionality you are after, for example https://connect2id.com/products/nimbus-jose-jwt

If you want you could specify that those details are stored in the JWT header, which will not be encrypted, but you still need to do the verify to ensure it has not been tampered with.

**Comment by gerolf-da** [comment]
@darkedges: great questions, thank you. Let me put some more color to these statements:

Regarding *not verifying* the token in this layer: How we currently envision the Ledger API Authentication story to pan out is the following:

- The operator of a ledger needs to integrate the ledger into some identity management system.
- The Ledger API Server will provide a hook for the ledger operator to implement token validation. It is up to the ledger operator to do this as they see fit.
- The High Level API (i.e. HTTP JSON API) currently simply operates just like any other ledger application and can be run by any user. Therefore it cannot do the actual validation (it doesn't know the secret or the keys), but can only pass on the received token to the Ledger API Server, which will then do the validation.

On the topic of requiring *unencrypted tokens*, this is mostly a "restriction" for convenience in the experimental stage of the High Level API. We are aware that it is practice to put some claims into the unencrypted header.

This is mostly just a preview of what is to come in the next couple of weeks, as we spec out the Ledger API authentication story for the whole stack.

**Comment by darkedges** [comment]
@gerolf-da there are ways and means of knowing where the JWKS is located, for example during the onboarding process the JWSK uri can be registered, and therefore the JSON API could resolve via a caching mechanism those details. Yes it requires a central registry / directory, but that is already alluded to in the documentation updates.

For example you can use the kid in the header to find the public key via the JWKS cache.

Anyway will await the updates.

**Comment by leo-da** [comment]
@gerolf-da, @darkedges we actually have the logic that validates the JWT using auth0 java library. However we don't advertise it in the docs.

I think we should close this ticket, it implements exactly what we originally discussed, JWT pass-through logic. If we want to document and provide reference implementations for RSA and HMAC token validation, this has to be done as a separate feature request.

**Comment by leo-da** [comment]
See #2658
