### ISSUE TITLE
HTTP JSON API: Support both wall-clock-time and static-time modes

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#2362]
We currently support sandbox `--wall-clock-time` mode only.
You can connect to a sandbox running in `--static-time` mode, but you have to set `meta.ledgerEffectiveTime` value explicitly in the submitted command, see:
https://github.com/digital-asset/daml/blob/b940951a76d81d0604874c67339407a6a183539d/ledger-service/http-json/src/main/scala/com/digitalasset/http/domain.scala#L164-L168

**Comment by leo-da** [comment]
cc @tweber-da

**Comment by S11001001** [comment]
from @tweber-da: Currently the ledgerEffectiveTime must be in epoch millis which is a bit tedious to set in general

**Comment by leo-da** [comment]
we would not support this. Any questions, talk to @bame-da
