### ISSUE TITLE
sandbox can't be initialized with a scenario that uses a submitMustFail

### ISSUE THREAD

**Issue by shaul-da** [digital-asset/daml#2388]
For quick demonstrations and iterating between Navigator and IDE it's helpful if I could simply initialize Navigator from any scenario, including one that has a `submitMustFail` in it (in which case this would simply be ignored).

Low priority, not sure if this is a good `good-first-issue` or not

**Comment by stefanobaghino-da** [comment]
Fixed by https://github.com/digital-asset/daml/pull/4036
