### ISSUE TITLE
Enable or remove Navigator license checking

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#239]
Navigator includes [code](https://github.com/digital-asset/daml/tree/master/navigator/docs) to check library licenses and generate a license listing in RST format. This is currently not used anywhere.

Either run the license check as part of the CI (e.g., port it to `bazel test`), or remove the code and rely on other services (such as BlackDuck).

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
