### ISSUE TITLE
`//language-support/scala/codegen-sample-app:medium_tests` timed out

### ISSUE THREAD

**Issue by lshlyapnikov** [digital-asset/daml#240]
cloned the repository and built everything first time, following instructions from: https://github.com/digital-asset/daml/blob/master/README.md

`bazel build //...` -- all good.

However `bazel test //language-support/scala/...` failed:
```
...
//language-support/scala/codegen-sample-app:ScalaCodeGenIT               PASSED in 14.7s
//language-support/scala/codegen-sample-app:tests                        PASSED in 12.5s
//language-support/scala/codegen-sample-app:medium_tests                TIMEOUT in 300.1s
  /home/lshlyapnikov/.cache/bazel/_bazel_lshlyapnikov/93421a3de0d4136018d3a996a13bee95/execroot/com_github_digital_asset_daml/bazel-out/k8-fastbuild/testlogs/language-support/scala/codegen-sample-app/medium_tests/test.log

Executed 3 out of 30 tests: 29 tests pass and 1 fails locally.
INFO: Build completed, 1 test FAILED, 31 total actions
```
from the test.log:
```
00:39:03,078 |-ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [encoder] of type [net.logstash.logback.encoder.LogstashEncoder] java.
lang.ClassNotFoundException: net.logstash.logback.encoder.LogstashEncoder
        at java.lang.ClassNotFoundException: net.logstash.logback.encoder.LogstashEncoder
        at      at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by lshlyapnikov** [comment]
[/home/lshlyapnikov/.cache/bazel/_bazel_lshlyapnikov/93421a3de0d4136018d3a996a13bee95/execroot/com_github_digital_asset_daml/bazel-out/k8-fastbuild/testlogs/language-support/scala/codegen-sample-app/medium_tests/test.log](https://github.com/digital-asset/daml/files/3045951/test.log)

**Comment by lshlyapnikov** [comment]
cc @stephencompall-DA, @leo-da

**Comment by lshlyapnikov** [comment]
```
medium_tests = [
  'src/test/scala/com/digitalasset/codegen/SlickIntegrationPostgreSqlSpec.scala',
  'src/test/scala/com/digitalasset/codegen/problems/PostgreSqlKnownProblemSpec.scala',
]
```

**Comment by leo-da** [comment]
We are going to drop the support for `scala/codegen-sql-support` module.
We will delete the `scala/codegen-sql-support` with all corresponding unit and integration tests. Tagging the repository before the delete. Proposed tag name: `scala-sql-codegen-before-deletion`.
CC @francesco-da

**Comment by leo-da** [comment]
Tagged master that includes `language-support/scala/codegen-sql-support`:
https://github.com/digital-asset/daml/releases/tag/scala-sql-codegen-before-deletion
