### ISSUE TITLE
Address node vulnerabilities reported by github for daml repo

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#2457]
![image](https://user-images.githubusercontent.com/25179017/62706201-0c6df100-b9bd-11e9-88fe-73675f9d5592.png)

![image](https://user-images.githubusercontent.com/25179017/62706214-155ec280-b9bd-11e9-80ab-2ff82ca42912.png)

![image](https://user-images.githubusercontent.com/25179017/62706241-20195780-b9bd-11e9-8c87-355998448387.png)

![image](https://user-images.githubusercontent.com/25179017/62706296-36271800-b9bd-11e9-9102-989874ff0516.png)

![image](https://user-images.githubusercontent.com/25179017/62706316-3fb08000-b9bd-11e9-8f45-ecfa5e7a208f.png)

![image](https://user-images.githubusercontent.com/25179017/62706331-4808bb00-b9bd-11e9-8b53-0aed6585e799.png)

![image](https://user-images.githubusercontent.com/25179017/62706347-5060f600-b9bd-11e9-8e39-bcca931e01c4.png)

![image](https://user-images.githubusercontent.com/25179017/62706359-59ea5e00-b9bd-11e9-9d6c-dfd70be8623b.png)

![image](https://user-images.githubusercontent.com/25179017/62706370-62429900-b9bd-11e9-9c5f-a47be2339e3f.png)

![image](https://user-images.githubusercontent.com/25179017/62706390-6a9ad400-b9bd-11e9-93aa-1856b2e89e19.png)

**Comment by cocreature** [comment]
These have been addressed
