### ISSUE TITLE
Mysterious crash on contract creation

### ISSUE THREAD

**Issue by NathanMatthewsDA** [digital-asset/daml#2484]
Error can be replicated by cloning:

https://github.com/NathanMatthewsDA/Poker

And running the Navigator/Bootstrap scenario in the IDE.

Error is:

Scenario execution failed on commit at Navigator:156:5:
  Aborted:  foldl1: empty input

Last source location: DA.Optional:24:29

Ledger time: 1970-01-01T00:00:00Z

**Comment by cocreature** [comment]
I did some printf debugging on Friday, the exact line that causes the error is the create at https://github.com/NathanMatthewsDA/Poker/blob/33d8d3ce239748395d9b2a2c621ce79bdaf2fa79/daml/Round.daml#L87. Printing the record passed to the create before works just fine so it looks like either a runtime error or the create is being miscompiled somehow.

**Comment by hurryabit** [comment]
It's the `maxOn` function used in the computation of the signatories of `Round` that causes the trouble:
https://github.com/NathanMatthewsDA/Poker/blob/33d8d3ce239748395d9b2a2c621ce79bdaf2fa79/daml/Utils.daml#L18

**Comment by hurryabit** [comment]
We'll have a look into printing more informative stack traces when the interpreter crashes.
