### ISSUE TITLE
improve DAML `*.dar` package dependency handling

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/daml#2510]
Dependency handling in DAML projects is currently very opaque.

Documentation
============
  - would be good to have a general explanation of dependency handling. i.e. currently it's manual; there is no automatic artifact fetching. Is there a plan to create an artifact repository (like maven-central for java)?
  - what is the syntax in daml.yaml (relative path? include `*.dar` suffix? include version number?)
  - and where to put the *.dar file (in a `lib/` subdir? in root dir?)

Error Messages
=============
 @robin-da @moritzkiefer-da explained that `dar` files are currently not compatible across DAML versions. Example error:
```
Compiling example to a DAR.
File:     daml/Main.daml
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message: 
  error type checking data type Main.AssetInstance:
  unknown data type:
  33eff689d79d36ff70855fea91cbacdf41e75d61d28b67809fcf9f6845b942d7:DA.Internal.Template:PreConsuming
Code: 
ERROR: Creation of DAR file failed.
```
The version the `dar` was built against can be checked by looking in the `META-INF` file inside the `*.dar` archive, against the version number in `daml.yaml`. Make the errors easier to understand.

   I also suggested to append the language version to package names, like in scala - it's rudimentary but serves to check versions are compatible. e.g. `cdm-daml-2.0.128_0.13.15.dar` instead of just `cdm-daml-2.0.128.dar`.

**Comment by cocreature** [comment]
Thanks for the issue, this definitely needs fixing!

**Comment by robin-da** [comment]
documentation for package imports has been added to the sdk.

**Comment by robin-da** [comment]
work on nicer error message is in progress.
