### ISSUE TITLE
Sandbox 0.13.19 Reset Service is substantially slower than before / GRPC channel closed on reset

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#2549]
In SDK version 0.13.19, the sandbox ledger reset is much slower than it was before.

As a result, our test harness times out waiting on the reset, and complains about a GRPC channel being closed server-side. It would be good to investigate whether the channel can stay open across resets.

This may have been caused by the reordering of `close` calls in #2471 (that is the only indication of change in the changelog).

**Comment by stefanobaghino-da** [comment]
I've just run stress tests on the ResetService and it's speed actually increased between 0.13.18 and 0.13.19. Can you better qualify your claim?

**Comment by stefanobaghino-da** [comment]
The ResetService is not the culprit. As pointed out later in the ticket, running tests against several revisions points at the fact that the reordering of the `close` call in #2471 is the culprit. There is no relationship between the two.

**Comment by stefanobaghino-da** [comment]
Indeed, there is a relationship between the two. Sorry for not acknowledging this before. Unfortunately I have not been able to come up with a good repro for our tests so far. I'll make sure that this is tested before committing a simple revert.
