### ISSUE TITLE
Remove DAML-on-X stack in favor of default Ledger API server

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#2557]
This is a meta-issue to track the removal of the DAML-on-X stack in favor of the default Ledger API server.

Work items
- [x] move DAML on Sawtooth to Ledger API server (@mziolekda )
- [x] move DAML on VMware to Ledger API server (@mziolekda )
- [x] move DAML on Corda to Ledger API server (@simonmaxen-da )
- [x] move DAML on Fabric to Ledger API server (@dasormeter )
- [x] move Canton to Ledger API server (@oliverse-da )
- [x] move [`digital-asset/daml-on-x-example`](https://github.com/digital-asset/daml-on-x-example) to Ledger API server (@dasormeter )
- [x] update Ledger API integration kit docs ( @dasormeter  ) and update release notes with deprecation
- [x] remove DAML on X stack (@dajmaki ) and update release notes with removal

FYI: @gerolf-da

**Comment by meiersi-da** [comment]
@dajmaki @mziolekda @vivd-da @sormeter @oliverse-da @gerolf-da -- please quickly double-check for completeness and executability; and use this issue to track the discussion.

**Comment by meiersi-da** [comment]
@dasormeter @oliverse-da -- Canton and Fabric were the last two remaining. AFAIK, they have been completed a long time ago. Closing assuming you'll tell me if I'm wrong :)

**Comment by oliverse-da** [comment]
👍
