### ISSUE TITLE
fix WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#26]
On da run sandbox I get some text saying:

WARNING: An illegal reflective access operation has occurred

At this point I freaked out, and, assuming the computer was illegally accessing reflective services, smashed all the mirrors in my house. This message should not be something users see.

The fix for this is in the protobuf lib and will be released in version v3.7.0. There are only RCs for it when I am writing this. It's gonna take some time until this change makes it up the protobuf -> grpc-protobuf -> grpc-java -> .. dependency chain.

**Comment by Northshoot** [comment]
Good morning,

Somehow it got back! Fresh installation and same error for 

```
╰☕ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
``` 

as for
```
╰☕ java --version
java 12.0.1 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

And the error is

```
╭─  ~/wo…ce/pr…ts/daml/demo/quickstart                                                                     2316  100% 
╰☕ da run sandbox -- --scenario Main:setup target/daml/*
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/hai/.da/packages/sandbox/100.12.3/sandbox-100.12.3.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
DAML LF Engine supports LF versions: 0, 1.0, 1.1, 1.2, 1.3; Transaction versions: 1, 2, 3, 4, 5; Value versions: 1, 2, 3, 4
Starting plainText server
listening on localhost:6865
```

If there is a specific java requirement, would be great if installer checks them and ask to update or at least informs about potential problems. Running into warnings in the first few minutes is a strage experience.

**Comment by natalie-da** [comment]
Hi @Northshoot . Thanks for raising. It seems like we're currently supporting Java 8 only. We are working on improving this though. Meanwhile, I've asked my team to update documentation to reflect that. Apologies for convenience this may have caused!
