### ISSUE TITLE
Simple daml scenarios fail to compile with --ghc-option -W --ghc-option -Werror

### ISSUE THREAD

**Issue by andrewking-da** [digital-asset/daml#2611]
The following scenario when compiled with `daml damlc -- compile --ghc-option -W --ghc-option -Werror Test.daml` fails to compile with errors like `<no location info>: error: Defined but not used: ‘this’`
```Haskell
daml 1.2

module Bug where

template Test
  with
    operator: Party
  where
    signatory operator

myTest : Scenario ()
myTest = do
    operator <- getParty "operator"
    submit operator $ create Test with operator
    pure ()
```

**Comment by hurryabit** [comment]
@rohanjr That looks like one for you.

**Comment by hurryabit** [comment]
This should be fixed by now.
