### ISSUE TITLE
Support for Logging in DAML

### ISSUE THREAD

**Issue by ashfaq-shaik** [digital-asset/daml#2654]
Is there any support for Logging in DAML. Its quite hard figuring out an issue when code in DAML breaks.

Pardon my ignorance, if this already exists, could you point me to some documentation on how to get logging working.

In languages like solidity, I can emit and log event and its stored in the blocks log.

**Comment by cocreature** [comment]
There are a few functions that allow you to print something for debugging namely `traceRaw`, `trace`, `traceId` and `debug`, see https://docs.daml.com/daml/reference/base.html#function-da-internal-prelude-traceraw-59593. However, at the moment you can only see the output in scenarios. There is an open issue for also making this output available in the sandbox https://github.com/digital-asset/daml/issues/28

**Comment by ashfaq-shaik** [comment]
Thank you

**Comment by gerolf-da** [comment]
This is now fixed (pending an SDK release). DAML `trace` messages are logged at `DEBUG` level. See #28 and #3983.

**Comment by cocreature** [comment]
thank you @gerolf-da!
