### ISSUE TITLE
docs generation generates duplicate references for `default` methods of type classes

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#2659]
If type classes have a `default` method implementation, the doc generation generates a duplicate function reference. Here's the failing example: 

```
class Convertible a b where
  convert : a -> b
  default convert : (Generic a repA, Generic b repB, GenConvertible repA repB) => a -> b
  convert = to . cv . from
```

**Comment by associahedron** [comment]
Yep, that's a bug. A workaround for now is to `-- | HIDE` the default implementation.
