### ISSUE TITLE
--package-name changes package hash

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#266]
### Observed behavior
The `--package-name` parameter influences the package hash.

### Expected behavior
The `--package-name` has not influence on the package hash.

### Steps to reproduce
A minimal daml model to reproduce the behavior is:

```haskell
daml 1.2
module Bug where

data Beetle = Beetle ()
```
```
da run damlc -- compile Bug.daml --package-name Foo -o Foo.dalf
da run damlc -- compile Bug.daml --package-name Bar -o Bar.dalf
```
The attached [package-hash.zip](https://github.com/digital-asset/daml/files/3049118/package-hash.zip) contains the daml, dalfs, and proto-decoded dalfs.
The diff between the proto-decoded dalfs yields:
```
93860c93860
<           name: "$$con2tag_IS6OjtaJasZEhAnQ63mtm2"
---
>           name: "$$con2tag_5pPfDBlEvz6AIF3O5Ut5ze"
93955c93955
<           name: "$$con2tag_2hRjBLiwHr2JgSMKQdc6CW"
---
>           name: "$$con2tag_3NJKK7CQ6OdCGhpEf8108X"
96737c96737
< hash: "e54d052cb718337f9fbaaf5e2d304a7c22a7b341f79a3c0bc59dbdbd865dd640"
---
> hash: "0ac71ece8cfd94666adc1b07fe010e240a9573a7947b899f4d465f452179f888"
```

**Comment by robin-da** [comment]
We investigated this and we don't see a reason to change this, the package name is just considered a part of the package. The exact reason for the hash to be dependent on the package name is as follows:

Every algebraic data structure that derives a `Ord` instance gets a `con2tag` function by ghc. For example 

```
data Beetle a b = Beetle a | Bug b deriving (Eq, Ord)
```

leads to 

```
 def $con2tag_19KrMaXUkmb6L669pU1Ai0 : forall a b. Bug:Beetle a b -> Int64 =
    /\a b.
      \(ds : Bug:Beetle a b).
        case ds of
          Bug:Beetle.Beetle ds1 -> 0
          Bug:Beetle.Bug ds1 -> 1
```

in the dalf and the package name influences the id of the `con2tag_<id>` name.

**Comment by gerolf-da** [comment]
The point that confuses me is that the notion of "package name" does not exist in daml-lf. An entity is uniquely identified by package id (aka package hash), module name, entity name. I don't see a reason why the package name, presumably used by GHC to disambiguate entities from different packages, should leak into the produced daml lf code, especially considering that this particular case of the `con2tag` function seems to be more accidental than on purpose.

**Comment by martin-drhu-da** [comment]
@gerolf-da Is it just confusing or do you want it to be fixed?

**Comment by gerolf-da** [comment]
@martin-drhu-da: I think it's both confusing, unexpected, and from a DAML LF standpoint it doesn't make sense.

**Comment by francesco-da** [comment]
I think the name should be in the DAML-LF package itself in a more "official" manner, so that if a sysadmin is dealing with understanding where a .dalf comes from, he can at least get a hint.

**Comment by martin-drhu-da** [comment]
Shall we just change the `Package` message type to
```
message Package {
  repeated Module modules = 1;
  string name = 2;
}
```
This would only be very minor work on the compiler side.

**Comment by francesco-da** [comment]
@martin-drhu-da yea, i think something like that would be ideal.

**Comment by martin-drhu-da** [comment]
@robin-da Can you please take care of adding the `name` field to `Package` as part of the packaging work. Please only write it for DAML-LF >= 1.3.

**Comment by gerolf-da** [comment]
But I could still have 2 DARs deployed in the same ledger with different hashes but the same package name, no?

**Comment by robin-da** [comment]
@gerolf-da I think the idea would be to make it very explicit that the package hash depends on the package name.

**Comment by gerolf-da** [comment]
@robin-da: I understand that. But I still don't understand what the purpose of the package name itself is. Should this serve as description meta data?

**Comment by cocreature** [comment]
I don’t really see a reasonable way to fix this and I would actually like to go the other way and include the name in DAML-LF (see #4412) so I’m closing this.
