### ISSUE TITLE
consider moving gcp_cdn_bucket to the Terraform Module Registry

### ISSUE THREAD

**Issue by flokli** [digital-asset/daml#2665]
The terraform module `gcp_cdn_bucket` is generally useful, as it allows to setup a GCS bucket, load balancer and a CDN config in a generic fashion.

In DAML, it's used for the nix and bazel cache, and I use it some other projects as well.

While using it, I discovered some bugs, and filed #1716 and #2460 which fixed some issues.

I currently refer to it in the following (slightly clumsy) way:

```tf
module "bazel_cache" {
  source = "git::https://github.com/digital-asset/daml.git//infra/modules/gcp_cdn_bucket?ref=…"

  … module parameters …
}
```

Because it's generally useful, what about publishing it in the Terraform Module Registry under a `daml` handle, with a separate repository?

This would allow more people to discover, improve and use it.

cc @garyverhaegen-da @cocreature

**Comment by cocreature** [comment]
Could you expand a bit more on what the benefits are of publishing it to the registry? Is it just about being able to replace the git URI with something like `daml/gpc_cdn_bucket`?

In principle this sounds reasonable to me but I’ll leave the decision to @garyverhaegen-da since I don’t know enough about terraform.

**Comment by flokli** [comment]
Yes, that's mostly it :-)

It's a pretty self-contained terraform module.

IMHO, it would just make sense to have it hosted somewhere separate.

Issues and PRs regarding it won't clutter the daml tracker, and having it on the Terraform Registry would increase visibility and reusability too - it shouldn't hurt to see more people using and improving it ;-)

**Comment by cocreature** [comment]
We don’t have the resources for that atm so closing.
