### ISSUE TITLE
Allow setting additional damlc options in daml.yaml

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#2676]
Currently, if you want to pass additional options to damlc (the most common usecase for that is probably `--ghc-option` you have to pass them manually when invoking `daml build`, `daml test` and set them in the VSCode options for `daml studio`. Keeping all of that in sync is a bit annoying. It would be nice if we had a `damlc-options` field in `daml.yaml` and all `damlc` commands (or at least `build`, `test` and `ide` initially) will pick them up automatically.

@jberthold-da would probably be quite happy about that :slightly_smiling_face: 

I’m not quite sure which options we should allow setting there. Initially, I would probably limit it to `--ghc-option` but require that users write something like `--ghc-option -W` in their `daml.yaml` rather than implicitly prepending `--ghc-option` to everything to be able to extend it to other options later on.

**Comment by garyverhaegen-da** [comment]
@cocreature I believe this is covered by #2772. Are we missing anything to close this?

**Comment by cocreature** [comment]
Yes this can be closed, thanks a lot for implementing it!
