### ISSUE TITLE
Strip Haskell binaries

### ISSUE THREAD

**Issue by moritzkiefer-da** [digital-asset/daml#27]
We should strip the Haskell binaries that we produce in Bazel. Ideally we would fix this by getting `rules_haskell` to respect Bazel’s [`--strip` flag](https://docs.bazel.build/versions/master/user-manual.html#flag--strip).

**Comment by cocreature** [comment]
Binary size doesn’t seem to be a problem for now and if it becomes one `split-sections` is probably a more useful thing to look into so closing.
