### ISSUE TITLE
ghc-lib update procedure

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#2702]
Some progress has been made recently on the ghc-lib side to automate its release process; while that is overall a Good Thing™, it does have the unfortunate side-effect that [the current instructions for upgrading ghc-lib in this repo](https://github.com/digital-asset/daml/blob/bf5995f529016701557abbb71d8591497a3bcfd0/ghc-lib/working-on-ghc-lib.md#how-to-deploy-ghc-lib) are now in need of an almost complete rewrite.

It's not quite clear to me whether the best approach at this point is to document the process as it stands, or to first automate away the last remaining steps and then document that. From what I understand the steps that still need automating start when the next version of ghc-lib has been pushed to Bintray already and consist roughly of:
1. Updating a bunch of files in this repo with the new version number and corresponding SHA1 (`util.bzl`, `BUILD.ghc-lib-parser`, `WORKSPACE`),
2. Testing that the resulting build passes all tests.

This could be done with a script in this repo that takes a version as argument and makes the necessary updates. If that script existed, then the release process on the ghc-lib side could, after having uploaded the tarballs to Bintray, clone the DAML repo, run this script (passing in the version number it just created), and use the GitHub API to create a corresponding PR, thereby running all tests against this new version.

The main tricky bit I can think of is to find a way to make sure this script is tested by `build.sh` so if we refactor our Bazel files we don't have to wait for the next attempt to upgrade ghc-lib to discover it broke.

**Comment by cocreature** [comment]
This has been addressed now. Thanks @garyverhaegen-da!
