### ISSUE TITLE
Add health checks and health reporting to participant processes

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#2733]
The Ledger API Server and Indexer processes should report their health status.

1. Specify which health checks are needed.
2. Specify the means to report the status.

All components should support two types of checks: readiness and liveness in order to be compatible with the most prevalent container orchestrations. These two are natively supported by kubernetes while docker swarm only supports the latter type in the form of a generic HEALTHCHECK.

- Readiness probe: used by container orchestration to wait until the app is fully started before it allows the service to send traffic to the new copy
- Liveness probe: used by container orchestration to detect that the app is no longer serving requests and restarts the offending pod

The format of these probes can be determined by the implementers. It could be either a [HTTP](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) endpoint or [gRPC](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/). Both can be easily picked up by the person implementing the orchestration.

The semantics of the checks should be meaningful in the context of the specific application.

- Readiness of ledger api server should indicate a point in time at which clients can be serviced in a meaningful manner i.e. all modules are initialized, database connections have been established, TLS certificates have been picked up and validated, ledger id and configuration have been retrieved and processed, connection with the ledger from the write service has been established
- Readiness of the indexer should be signaled, when database connections have been established, databases have been created, schemas have been updated, TLS certificates have been picked up and validated, connection with the ledger from the read service has been established
- Liveness of the ledger api server should depend on the availability of the index database, availability of the ledger connection in the write service (new interface for connection status will be necessary) and liveness of the threads
- Liveness of the indexer should depend on the availability of the index database, availability of the ledger connection in the read service (new interface for connection status will be necessary) and liveness of the threads

**Comment by meiersi-da** [comment]
FYI: @gerolf-da handed over to @mziolekda

**Comment by SamirTalwar** [comment]
[Kubernetes' documentation on liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) is very useful reading.

**Comment by SamirTalwar** [comment]
I don't think it'd be a good idea to make liveness depend on any external service; liveness is much more about detecting when a service has locked up in some fashion (deadlock, etc). If you make Service A's liveness depend on Service B, then if Service B will go down, Service A will be taken down too. This can lead to cascading shutdowns that take much longer to recover from than if you'd just waited until Service B was back up.

I think it's more apt to use readiness in this case; Service A is not _ready_ until Service B is ready and available. This ensures that Service A is taken out of the load balancer and doesn't receive requests it can't handle, but as soon as Service B is online, it'll come back, without an expensive restart.

**Comment by SamirTalwar** [comment]
It looks like the [gRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) is highly appropriate for readiness checks. We can mandate the use of [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) to test this. This approach has been blessed on the Kubernetes blog: [Health checking gRPC servers on Kubernetes](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/).

**Comment by SamirTalwar** [comment]
Still need to create a GRPC server for health checks on the `StandaloneIndexer`, so this is not done yet.

**Comment by gerolf-da** [comment]
The indexer is now covered by health checks.
