### ISSUE TITLE
VSCode extension uses deprecated / removed feature

### ISSUE THREAD

**Issue by bartfaitamas** [digital-asset/daml#275]
Trying to look at `Scenario results` in VSCode, I get the following error:

>  command 'vscode.previewHtml' not found

and the scenario output is not showed.

VSCode details

```
Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-16-generic
```

I'm using Ubuntu Bionic, installed and regularly update VSCode from the official repository: `http://packages.microsoft.com/repos/vscode stable main`

**Comment by bartfaitamas** [comment]
see here: https://github.com/Microsoft/vscode/issues/62630

**Comment by ndmitchell** [comment]
Which version of DAML are you using? I believe this is fixed in the latest one.

**Comment by bartfaitamas** [comment]
I'm working on porting the project to DAML 1.2, but how is daml version affects VSCode extensions?
This is an older project using older SDK by default, but tried with the latest version as well:

```
% cat ../da.yaml                                                                                                                                                                                                                           
project:
#  sdk-version: '0.11.14'
  sdk-version: '0.12.1'
```

VSCode extension info with the latest SDK:

```
Name: DAML Studio
Id: digital asset.da-vscode-daml-extension
Description: DAML editing and analysis tools
Version: 1.0.0-dirty
Publisher: Digital Asset
```
But that's the same for both versions

**Comment by bartfaitamas** [comment]
Link to the daml extension in VSCode directory was pointing to an older version:

```
$ ls -la ~/.vscode/extensions/
da-vscode-daml-extension -> ~/.da/packages/daml-extension/100.11.14
``` 

Running `da setup` fixed the link, and everything's fine with the latest VSCode.
