### ISSUE TITLE
Add examples to StdLib docs and test them

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#276]
Each Standard Library function should have a compact, but meaningful example demonstrating its use.

**Comment by neil-da** [comment]
If we're adding examples, they should also serve as tests, just like the Extra library, e.g. https://hackage.haskell.org/package/extra-1.6.14/docs/Data-List-Extra.html

**Comment by bethaitman-da** [comment]
I think this would make the stdlib docs hugely more usable. How much effort is it to do this?

**Comment by neil-da** [comment]
@bethaitman-da to do it in the abstract? Maybe 1 engineer day. To test it as well takes a fair bit longer. Doing it without testing is probably a recipe for disaster.

**Comment by bethaitman-da** [comment]
Agreed - there's zero point adding examples if they're not tested.

**Comment by cocreature** [comment]
We do have examples in the stdlib and they are tested automatically.
