### ISSUE TITLE
json-api: comparison query

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#2780]
Building on #2778 .

Match LF values on comparison operators for number, text, date, and time values. Instead of a value, a key can be an object with one or more operators: `{ <op>: value }` where `<op>` can be:

* `"%lt"` for less than
* `"%gt"` for greater than
* `"%lte"` for less than or equal to
* `"%gte"` for greater than or equal to

These operators cannot occur in objects interpreted in a record context, nor may other keys than these four operators occur where they are legal, so there is no ambiguity with #2778 .

Example:  `{ "person.dob": { "%lt": "2000-01-01", "%gte": "1980-01-01" } }`

* Match: `{ person: { dob: "1986-06-21" } }`
* No match: `{ person: { dob: "1976-06-21" } }`
* No match: `{ person: { dob: "2006-06-21" } }`

**Comment by ashfaq-shaik** [comment]
In which version will this feature be available?

**Comment by stefanobaghino-da** [comment]
> In which version will this feature be available?

It's been merged to master yesterday and will be available starting from the next release, 0.13.35.
