### ISSUE TITLE
HTTP JSON API should answer OPTIONS prerequests

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#2782]
Apparently most browsers send OPTIONS preflight request before they send a header containing the 'Authorization' header for JWT. However the HTTP-JSON API doesn't answer those. Here's a request from my browser:

```OPTIONS /contracts/search HTTP/1.1
Host: 127.0.0.1:7575
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization
Referer: http://localhost:3000/
Origin: http://localhost:3000
```
This breaks web-frontends trying to fetch data from the service. Here's a discussion on the issue: https://stackoverflow.com/questions/44245588/how-to-send-authorization-header-with-axios

**Comment by leo-da** [comment]
An example OPTIONS request:
```
OPTIONS /contracts/search HTTP/1.1
Host: 127.0.0.1:7575
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization
Referer: http://localhost:3000/
Origin: http://localhost:3000
```

**Comment by leo-da** [comment]
adding OPTIONS support is not a problem. However OPTIONS pre-request is used as part of the CORS mechanism (Cross-Origin resource Sharing), which we don't want to support. @robin-da set up a reverse proxy, this solved the original issue. Closing this, unless there are other reasons to support OPTIONS method.

**Comment by cocreature** [comment]
Why do you not want to support CORS? Having the JSON API server run on a different host than the server serving your frontend seems quite common and often you don’t have enough control over the frontend server to add a reverse proxy, e.g., if you support CORS I can host a frontend on github pages which is really convenient.

**Comment by hurryabit** [comment]
Why do we not want to support CORS? Basically everybody writing a DAML-based app using the JSON API will have this problem. Having to setup a reverse proxy doesn't exactly lower the barrier to entry.
cc @gerolf-da

**Comment by leo-da** [comment]
@cocreature @hurryabit we have considered adding CORS support. @da-tanabe had a slack conversation with @bame-da and we agreed that the risks and complexity added by CORS support are not worth the effort. There are tons of web dev options to get around the problem without the reverse proxy. @da-tanabe provided the corresponding links, which we can add to an FAQ at some point.

The simplest solution would be to support dev only `--static-resource-directory`.

Again, we are open for discussion.

**Comment by leo-da** [comment]
## Links
- https://create-react-app.dev/docs/proxying-api-requests-in-development
- https://medium.com/better-programming/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d
- https://webpack.js.org/configuration/dev-server/#devserverproxy

**Comment by leo-da** [comment]
@hurryabit now you can start JSON API daemon with `--static-content "directory=/home/leos/tmp/html,prefix=static` this will serve static content from `/home/leos/tmp/html` directory and map it into `/static/*`

Is this sufficient or do you really need CORS support?

**Comment by leo-da** [comment]
`--static-content` is NOT recommended for PROD deployments.

**Comment by hurryabit** [comment]
@leo-da Serving static content during development is enough. I think we don't wont to get into the business of building a webserver. Thank you very much for taking care of this.
