### ISSUE TITLE
VS code plugin: color of squiggly lines?

### ISSUE THREAD

**Issue by edsko** [digital-asset/daml#2834]
I'm not entirely sure if the VS code plugin is responsible here, but the color of the squiggly lines doesn't seem to respect configuration settings. If I set

```
    "workbench.colorCustomizations": {
        "editorWarning.foreground": "#ffff00",        
        "editorWarning.border": "#ffffff"        
    },
```

in my configuration file, they still appear in the old color. (The above would be very ugly, I was merely trying to change it at all :).

**Comment by cocreature** [comment]
Are you sure you are getting warnings instead of errors? Errors have a separate configuration setting `editorError.foreground`. I don’t think we do anything special with regards to colors. We just send the diagnostics to VSCode and it does all the rendering.

**Comment by edsko** [comment]
Yeah, unused definitions.

**Comment by edsko** [comment]
Hmm, letme check if there's a `-Werror` somewhere.

**Comment by edsko** [comment]
Ah, yes. My mistake. Sorry! :)

**Comment by cocreature** [comment]
No worries, glad you got it figured out!
