### ISSUE TITLE
navigator: templates of additional packages are not shown.

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#2868]
When deploying an additional package to the sandbox, it's templates are not shown in the Templates view, while they are seen with the `templates` command of the navigator console.

**Comment by rautenrieth-da** [comment]
I assume by "deploying an additional package to the sandbox" you mean uploading a package through the package management service of the ledger API?

**Comment by robin-da** [comment]
@rautenrieth-da yes, exactly.

**Comment by dasormeter** [comment]
@rautenrieth-da @gerolf-da are there plans to support dynamic package loading from navigator?  i also just encountered this as i had started navigator before i uploaded packages and did not see the corresponding templates for them

**Comment by rautenrieth-da** [comment]
@dasormeter https://github.com/digital-asset/daml/issues/4592

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
