### ISSUE TITLE
Investigate possibilities for performance improvements in SQL backend

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#2888]
Below is an overview of database interactions when storing a transaction in Sandbox and JdbcIndexer.

## Task 1
Eliminate all wasteful interactions that are not strictly necessary:
* double contract look-ups for exercise nodes
* we validate each transaction node on its own, resulting in multiple contract-lookups in case a contract is fetched multiple times within a transaction.

## Task 2
Check if more targeted queries can reduce the number of roundtrips we do to the database. For example, instead of loading the entire contract (witnesses, divulgences, keys, ...) we specifically only load the LET of the transaction that created the contract here: 
https://github.com/digital-asset/daml/blob/194af9bcf83b0cd5900fa87c7e939c615d080f76/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ActiveLedgerStateManager.scala#L103-L110

### Aliases
*contract-lookup* = 
* 4 queries (contract, witnesses, divulgences, keyMaintainers)

*contract-insert* =
*    3 batch-inserts (contract data, witnesses, divulgences)
*    2 optional contract-key (maintainers + data) inserts

### Committing a Transaction
For each transaction that needs to be persisted, we currently execute:
* 1 insert for the transaction itself
* 1 batch-insert for disclosures of all events in the transaction
* 1 batch-insert for divulgences

Per transaction node actions:
* Fetch: 1 contract-lookup
* Create: 1 contract-insert
* Exercise: 2 contract-lookups (yes, wasteful) + 1 optional contract update (set archived offset for consuming choices) + 1 optional contract key delete

**Comment by rautenrieth-da** [comment]
Changes after #2998:

## Aliases
~*contract-lookup*~ (removed)

contract-let-lookup =
* 1 query (contract metadata)

## Committing a Transaction

Per transaction node actions:

Fetch: 1 contract-let-lookup (**3 queries less than before**)
Create: 1 contract-insert
Exercise: 1 contract-let-lookup + 1 optional contract update (set archived offset for consuming choices) + 1 optional contract key delete (**7 queries less than before**)

Note also that *contract-let-lookup* does not deserialize the contract arguments (unlike *contract-lookup*), so we also save some CPU time.
