### ISSUE TITLE
Remove redundant HsPar's in template desugaring

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#2897]
If one were to enable the DLint rule for redundant brackets (and redundant `$`, move `$`), then template desugaring would trigger those hints. This needs fixing. As its not critical this is low priority but should get done... @hurryabit suggests its a Friday afternoon "background" job sort of thing for when a break is needed from more intense work.

**Comment by cocreature** [comment]
Doesn’t seem useful to fix.
