### ISSUE TITLE
Sign binaries

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#29]
For general security reasons it would be nice to sign all binaries we produce for a release, including the installer. No need to do it immediately, but in the medium term.

CC @shaul-da

**Comment by neil-da** [comment]
Turns out to be quite important for the installer itself, or we get Windows defender being upset.

**Comment by cocreature** [comment]
Our Windows installer is now signed. If we decide to sign other things (signing Maven artifacts is already tracked as part of the work towards publishing to Maven central), let’s open separate issues for that.
