### ISSUE TITLE
http-json process does not reflect changes in ledger state/templates.

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/daml#2906]
The HTTP-JSON api v0.13.23, when started, behaves as if caches the current list of templates on the ledger. This means that, if any templates on the ledger are updated/removed/added, this will not be visible through the HTTP-JSON process, unless it restarted.

This is a problem for production/long-running ledgers where this endpoint can not/ should not be restarted.

This is a feature request to ensure that the http-json endpoint is always 'in-sync' with the underlying ledger.

**Comment by leo-da** [comment]
The HTTP JSON API loads all available Template ID mappings on start-up.
