### ISSUE TITLE
da run damlc --test --junit returns exit code 0 even for failing tests

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#291]
`da run damlc -- test --junit ...` returns an exit code of 0 even if some tests failed

**Comment by jberthold-da** [comment]
Just tested this, it does not appear specific to `--junit <filename>`.

**Comment by drewharding-da** [comment]
This issues is blocking our SDK upgrade, so definitely would like to see it fixed.

**Comment by moritzkiefer-da** [comment]
Sorry, I didn’t realize this was a blocker for you. I’ll try to fix it today.

**Comment by drewharding-da** [comment]
Not surprising - I only just found out myself :-)
