### ISSUE TITLE
Please provide sample response for contracts/search in http-json

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#2926]
The sample response for POST/GET http://localhost:7575/contracts/search is missing in the documentation: https://github.com/digital-asset/daml/tree/master/ledger-service/http-json

**Comment by leo-da** [comment]
`/contracts/search` is documented:
https://github.com/digital-asset/daml/blob/603e0a169f27b93c66c0ab5145bc544c6e06a206/ledger-service/http-json/README.md#L71-L75

**Comment by leo-da** [comment]
@lima-da or did you mean `/contracts/lookup`?

**Comment by lima-da** [comment]
@leo-da hmm, I assume the doc only includes POST request body. but not response.

**Comment by leo-da** [comment]
@lima-da @da-tanabe you guys probably not going to like the output :)
Chatted with @lima-da we can display a flattened collection of `ActiveContract`s without the wrappers, offset and etc.
