### ISSUE TITLE
Log unexpected errors in the scenario runner

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#2928]
I experienced a couple of un-reproducible strange crashes in the scenario runner in the IDE yesterday and noticed they are not in the telemetry log. Would be nice if they were so we can use the logs to improve the stability of the scenario runner.

**Comment by hurryabit** [comment]
Scenarios are about to be deprecated.

@cocreature Do you know if we have similar issues with DAML Script?

**Comment by cocreature** [comment]
I think most of those errors come from how scenario contexts are managed so they might still exist but given that it hasn’t come up in a year and nobody looks at telemetry errors actively any way I’m not all that worried about this.
