### ISSUE TITLE
Duplicate module name when importing transitive dependencies

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#2929]
When I `daml build` the project in [auth.zip](https://github.com/digital-asset/daml/files/3620038/auth.zip) I get:

```
File:     Library.daml
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message: 
  Data.NameMap.fromList: duplicate name ModuleName {unModuleName = ["Fact","Claim"]}
  CallStack (from HasCallStack):
  error, called at libs-haskell/da-hs-base/src/Data/NameMap.hs:190:13 in
  libs-haskellZSda-hs-baseZSda-hs-base:Data.NameMap
```

`Fact.Claim` is a dependency of `Rule.Application`, and it is also imported explicitly in `Library.daml`. I'd expect the compiler to recognise that these are the same module. Note that in the IDE everything works fine, it's just `daml build` that complains.

**Comment by cocreature** [comment]
The issue appears to be that we end up with `./Fact/Claim.hs` and `Fact/Claim.hs` which we treat as distinct files. Not quite sure where the culprit is.
