### ISSUE TITLE
allow to submit DAML-LF values as JSON on the ledger API

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#296]
the protobuf interface is a real pain from JS and generally without a codegen. it'd be nicer to just use an idiomatic, type-less JSON representation that you can submit as an alternative to the protobuf one.

the problem is what to output in events. it should probably be a switch when submitting subscribing.

**Comment by martin-drhu-da** [comment]
fyi @neil-da

**Comment by stefanobaghino-da** [comment]
I believe that at this point it's safe to say the idea behind this ticket is covered by the HTTP/JSON API. I'd suggest to close this. @gerolf-da?

**Comment by gerolf-da** [comment]
Yes, thank you.
