### ISSUE TITLE
DARs produced with SDK 0.13.22 or later are missing some .daml files

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#2960]
Tried `daml build`ing these examples after upgrading them to SDK 0.13.25 and observed that they produce dars missing all .daml files except for the entrypoint DAML listed in `daml.yaml`'s `source` attribute:
* https://github.com/digital-asset/ex-models/tree/master/crowd-funding
* https://github.com/digital-asset/ex-models/tree/master/chess

The behavior seems to have changed in 0.13.22, as reverting back to SDK 0.13.21 produces a dar with all .daml files as expected.

**Comment by cocreature** [comment]
This was caused by https://github.com/digital-asset/daml/pull/2687. If you specify the directory in `source`, it works properly so that’s at least a workaround (and you might want to migrate to that anyway) but if you specify a single file, things fall apart.
