### ISSUE TITLE
Migration Code build fails when upgrading DAR from 0.13.24 to 0.13.25

### ISSUE THREAD

**Issue by meet-da** [digital-asset/daml#2971]
Steps to reproduce -
1) Create a new project by running `daml new V1` and set its sdk version in `daml.yaml` to 0.13.24
2) Create a new project by running `daml new V2` and set its sdk version in `daml.yaml` to 0.13.25
3) Modify `template Asset` in V2/Main.daml to add a field `assetId: Text`; modify scenario accordingly
4) Run `daml build` on V1
5) Run `daml build` on V2
6) Navigate to V2 and run the `daml migrate` command -
```
daml migrate ~/Desktop/Projects/MigrationCode ../V1/.daml/dist/V1-0.0.1.dar .daml/dist/V2-0.0.1.dar
```
7) Navigate to the generated migration code folder and modify the auto-generated `Main.daml` to the following - 
```
daml 1.2
module Main where
import MainA qualified as A
import MainB qualified as B
import MainAInstances()
import MainBInstances()
import DA.Upgrade
template instance AssetUpgrade = Upgrade A.Asset B.Asset
template instance AssetRollback = Rollback A.Asset B.Asset
instance Convertible A.Asset B.Asset where
  convert d = B.Asset with issuer = d.issuer;
                            owner = d.owner;
                            name = d.name; 
                            assetId = "DEFAULT_VALUE"
instance Convertible B.Asset A.Asset where
  convert d = A.Asset with issuer = d.issuer; 
                            owner = d.owner; 
                            name = d.name
```
8) Run `./build.sh` -
```
meetanshruwadhwa2uhtd5:MigrationCode2 meetanshruwadhwa$ ./build.sh
Compiling MigrationCode2 to a DAR.
File:     
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message: 
  <command line>: cannot satisfy V1-0.0.1:
  V1-0.0.1 is unusable due to missing dependencies:
  daml-stdlib-0.13.24
  (use -v for more information)
ERROR: Creation of DAR file failed.
```
FYI @bame-da

**Comment by cocreature** [comment]
I’m a bit confused here. My understanding was that we added the version to `daml-stdlib` to fix cross-SDK upgrades but looking at the code, I can’t see anything that even tries to attempt to handle this.

**Comment by hurryabit** [comment]
@meet-da How urgent is it to fix that? @robin-da, who's the expert in this part of the code base, is currently on vacation. Can it wait until he's back mid next week or should we to investigate before this?

**Comment by cocreature** [comment]
I think this can wait until next week but we should also make sure that there is not only a single person that is able to fix bugs in the migration code. Given our team structure @nickchapman-da is probably well-suited for familiarizing himself with the code.

**Comment by robin-da** [comment]
working on this now.

**Comment by cocreature** [comment]
@robin-da Can we close this now?

**Comment by robin-da** [comment]
@yes, this works now.
