### ISSUE TITLE
Give better error messages on malformed contract key (maintainer) expressions

### ISSUE THREAD

**Issue by martin-drhu-da** [digital-asset/daml#299]
When we use an expression too complex for a contract key, we get a dump of the expression and a hint that it's unsupported. When we refer to a template argument that is not part of the contract key, we basically get an error message that `this` is not part of the contract key. Both error messages should be heavily improved.

**Comment by bitonic** [comment]
@hurryabit can we close this now that #298 has been merged?

**Comment by hurryabit** [comment]
@bitonic #298 does not affect the error messages. They are still horrible.

**Comment by bitonic** [comment]
@hurryabit OK. moving this to maintenance -- I think we can expose CKs in the SDK before we fix this.

**Comment by hurryabit** [comment]
#1527 made this problem go away.
