### ISSUE TITLE
Ledger api server logging: Differentiate whether contract does not exist or is archived in logging warning

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#2992]
It would be great if the following warning would indicate that the contract is inactive rather than unknown. Report so at warning level, as this is normal (racy) behavior.
It's more problematic if a contract id is used for a completely unknown contract, i.e., not even in the PCS

```
17:11:30.203 [index-akka.actor.default-dispatcher-10] WARN  c.d.c.l.a.s.p.s.s.ApiSubmissionService:AdminWorkflowTest/participant/participant2 - Submission of command 37e06a81-9c24-470c-a38e-558d6f07a872 has failed.
com.digitalasset.platform.server.api.ApiException: INVALID_ARGUMENT: Command interpretation error in LF-DAMLe: dependency error: couldn't find contract AbsoluteContractId(424e2f9b4d1c86572e3ff0dec971ce4b734430f17e7f2d0070fbe9c1bf2f0a4c:e0945569592b869f717e540da4a51b971f7466919fbbc5a47f91620c410cb689). Details: N/A.
```

**Comment by stefanobaghino-da** [comment]
If I'm not mistaken this would require the interpreter itself being aware of the distinction. Does it make sense? Is this something we want? /cc @gerolf-da
