### ISSUE TITLE
create targets to produce a zip / jar file for each .proto set we want to release

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#30]
right now we do not have bazel targets producing packages with the .proto files that we want to distribute. these are, at least:

- [ ] daml-lf value
- [ ] daml-lf transaction
- [ ] daml-lf archive
- [ ] ledger api

note that the `proto_library` rule produces a binary file with the descriptor set for the .protos, but without the protos themselves.

**Comment by cocreature** [comment]
We release all protos in a zip on github releases.
