### ISSUE TITLE
JSON API Documentation

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#3004]
The JSON API is currently not documented on docs.daml.com. There is a link to the [README](https://github.com/digital-asset/daml/blob/master/ledger-service/http-json/README.md) on github deep inside the DAML Assistant part of the docs, but:

* It's not consistent with the other docs.
* Its not a stable link to the documentation as of a specific SDK release.

To give users and indication, we want to provide a very minimal and basic guide on how to use the JSON API.
The documentation should cover the following topics:

1) How to get started with using the API
2) Description of the endpoints (request/response messages) ideally with short examples
2.1) `/command/create`
2.2) `/command/exercise`
2.3) `/contracts/search` (for basic searches by template ID)
3) Description of the JSON  encoding of LF values

Points 1) and 2) are basically already covered by porting the [README](https://github.com/digital-asset/daml/blob/master/ledger-service/http-json/README.md) from Markdown to ReStructuredText.

Point 2) is covered by porting the [DAML-LF JSON Encoding](https://github.com/digital-asset/daml/blob/master/ledger-service/lf-value-json/specification.rst) spec from Markdown to ReStructuredText.

The documentation should be put into the [experimental section](https://docs.daml.com/experimental/warning.html) of the DAML docs with a disclaimer that:

1. The JSON API is actively being worked on, and that the messages and encoding are subject to change
1. We welcome feedback to smooth out any rough edges.

Going forward, changes to the API or the encoding will be documented alongside the PR that makes the change, along side an entry in `unreleased.rst` with the following format:
```
- [JSON API - Experimental] Some change that occured
```

**Comment by gerolf-da** [comment]
Thanks for the quick turnaround, @S11001001 👏

**Comment by lucianojoublanc-da** [comment]
I can see the documentation has been removed from the README, but there is (as of this morning 26/09/2019) no new content in the experimental section of the official docs or anywhere that I can see. 

Is something needed to be done to rebuild/deploy the new docs perhaps? Looks like we currently have no doc available anywhere apart from git history.

**Comment by gerolf-da** [comment]
The docs will be available at docs.daml.com as of the next release. In the meantime, you can find everything here: https://github.com/digital-asset/daml/pull/3012/files
Sorry for the inconvenience.
