### ISSUE TITLE
Improve the log output of Navigator

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#3018]
The log output could be improved. It is difficult to get verbose logging info when debugging Navigator.

## More log output

Add more log output that is disabled by default:
1. command submissions (without contract arguments, but what templates are used, so we don’t log sensitive data)
1. command results.

## Logback config

Don't package the `logback-config.xml` in the JAR file, but extract it next to the JAR file in `~/.daml/sdk/x.y.z/navigator` for easier overrides. The `json-api` component uses this approach.

## Override log verbosity from command line arguments

Add a `--verbose` CLI flag. The flag could set an environment variable that is then used in the logback config:
```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
      <encoder>
        <pattern>%highlight([%level] %logger{10}: %msg) %n</pattern>
      </encoder>
      <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
          <level>${NAVIGATOR_STDOUT_LOG_LEVEL:-WARN}</level>
      </filter>
    </appender>
```

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
