### ISSUE TITLE
Validate auth claims in TimeService

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#3030]
This is an admin-only service.

**Comment by stefanobaghino-da** [comment]
On second thought, this being a test service it would probably be best left unauthenticated. Forcing this to be an admin-only endpoint can turn out to be an obstacle to start playing around with authenticated environments in a dev setup. Thoughts?

**Comment by rautenrieth-da** [comment]
I would keep it the same as ResetService - both are not available in production.
My initial thought was also to have them both as admin services.

What exactly would be make using the TimeService more difficult that the LedgerIdentityService? Do you think that there will be dev setups where you do not have admin claims?

**Comment by stefanobaghino-da** [comment]
I guess it's fine to keep them authenticated then.
