### ISSUE TITLE
Proposal: Add TemplateTypeRep to DAML and DAML-LF

### ISSUE THREAD

**Issue by aherrmann-da** [digital-asset/daml#3072]
This proposes adding a new type `TemplateTypeRep` to DAML and DAML-LF. This is motivated by DAML triggers, which receive `Created` and `Archived` updates of `AnyTemplate` (and `AnyContractId`) and where it is useful to have `TemplateTypeRep` to be able to compare template types, use template types as keys in mappings, and for heterogenous containers of templates. 

# Changes to DAML

- Add a new type `TemplateTypeRep` which uniquely identifies a template type.
- Add the following primitives
  - `templateTypeRep : Template t => TemplateTypeRep`
  - `typeRepEq : TemplateTypeRep -> TemplateTypeRep -> Bool`
    Provided to implement `Eq TemplateTypeRep`.
  - `typeRepToText : TemplateTypeRep -> Text`
    Provided so that `TemplateTypeRep` can be used associated with a map key.

# Changes to DAML-LF

- Add a new builtin type `TemplateTypeRep` corresponding to `TemplateTypeRep` in DAML.
- Add a family of `templateTypeRep tyCon` builtins of type `TemplateTypeRep` parameterized by a `TypeConName`.
  The typechecker checks that the type parameter is a template type.
  This builtin returns the `TemplateTypeRep` corresponding to the given template type.
  This will not be part of `BuiltinFunction`, but a separate AST node, since `BuiltinFunction` is an `Enum`.
- Add a builtin `typeRepEq` of type `TemplateTypeRep -> TemplateTypeRep -> Bool`.
  This builtin returns `True` if the given `TemplateTypeRep` are equal and `False` otherwise.
- Add a builtin `typeRepToText` of type `TemplateTypeRep -> Text`.
  This builtin returns a unique textual representation of the given `TemplateTypeRep`.

# Implementation Plan

As this is part of DAML triggers, I propose that the language team (primarily myself) take over the implementation work.

**Comment by aherrmann-da** [comment]
Pinging @cocreature for a first round of discussion.

**Comment by hurryabit** [comment]
@remyhaemmerle-da needs to be involved in this too.

**Comment by cocreature** [comment]
`typeRepToText` isn’t crucial for now probably. We can prototype with a ĺookup list and change it to a proper map once we add that.

**Comment by remyhaemmerle-da** [comment]
As a general rule, we should try to limit the number of features added to LF. 
Do not forget once a feature is added, it has to be supported **forever**  without exception: we cannot drop support for an old version of LF, on the contrary of the compiler. Having to much concept in the language will also complexity optimization we will have to provide in a no so long future (eg. ASX).

Note also, it is currently plan to allow only serializable type as key for map. As the complexity to add serializable type in the runtime I do not think we should make this new type (nor AnyTemplate) serializable.

I propose to add only a builtin expression `tyCon @Mod:T` of type Text that produces for any type Constructor a unique textual representation.

**Comment by cocreature** [comment]
For now that would be sufficient but it’s really hard to extend and modify this later if we end up finding more usecases for this, e.g., something like Haskell’s `cast : a -> TypeRep -> Maybe b` is a reasonable operation to have that we could add later to this representation. There is no way to implement that if `TypeRep` is just a `Text` and doesn’t store the type. I also don’t think it leads to a nice API especially if we later want to end up extending this to allow arbitrary monomorphic types. Of course, you can argue that this does not matter for DAML-LF and the save APIs should be built on top of it in DAML (which we will certainly do here) but given the effort you are putting into making maps save at a DAML-LF level that seems somewhat inconsistent.

I completely agree that we should be cautious about adding new features to DAML-LF but I’m worried that your proposal will lead to exactly the situation that we want to avoid, namely, a primitive that is now useless and you have to keep maintaining. Planning for forward compatibility and extensions is crucial to avoid adding primitives that will become useless at some point but you have to keep maintaining.

**Comment by remyhaemmerle-da** [comment]
There are an important difference between Map and your new `TypeRep`.

1 - The former is serializable while the latter is not. In particular you have no way to hide LF MAP from the user since it can access it thought layer of DAML while you can do it for TypeRep.

2- Map is fundamentally more complex that your new TypeRep. There is performance and determinism issues that are difficult to deal with at the DAML-LF (otherwise we would probably continue using DAML implementation). Taking into account this complexity it is reasonable to be more thorough.

**Comment by cocreature** [comment]
My point wasn’t about whether we should add a new Map type to DAML-LF or not but about the fact that you are putting in a lot of effort to make a safe DAML-LF API for equality as opposed to having an API that crashes in some cases and make it safe in DAML. That feels somewhat similar to not having a new type for `TypeRep` but of course your proposal won’t actually crash so I don’t want to derail the discussion further by this.

My point about forwards compatiblity and extensibility still stands however. Also `TypeRep` will have to be serializable.

**Comment by gerolf-da** [comment]
Adding a new serializable type to DAML-LF is very costly. It affects DAML-LF Values, bindings, applications (extractor, navigator, json api, ...). Unless absolutely strictly necessarily for a crucial feature, adding a serializable type is not the right approach.

**Comment by cocreature** [comment]
We don’t need serializability because we actually want to serialize this but to be able to use this as map keys. If making types serializable is expensive, I wonder if using serializability as the restriction for map keys is a good idea is a discussion for another issue.

As for this one, I’m still not convinced that not having a newtype is a good idea. We could avoid the serializability requirement if we provide conversions from and to text while still having a separate, unserializable `TypeRep` type.

**Comment by cocreature** [comment]
After some discussions, we’ve decided to go with @remyhaemmerle-da’s proposal for now and keep it in `1.dev` for a bit to see if we actually find a need to change it.

**Comment by cocreature** [comment]
This has been implemented.
