### ISSUE TITLE
have DarReader to support .dars without MANIFEST with latest format

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#308]
@leo-da , i've realized that we have unwillingly broken backwards compat with older `.dar`s. we should restore this. if we do not find the `MANIFEST` file with the fileds we expect, we should just get all `.dalf`s as we did before, and:

1. if it's only one `.dalf`, then that's the main one
2. if it's two `.dalf`s, where one of them has `-prim` in the name, the one without `-prim` is the main dalf.
3. parse error in all other cases

**Comment by francesco-da** [comment]
@martin-drhu-da let's hold off a visible release until we fix this, please

**Comment by neil-da** [comment]
Anything that blocks a release from being made should be tagged `broken`.
