### ISSUE TITLE
IDE: `Data.NameMap.fromList.: duplicate name` compilation error

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/daml#3099]
We are seeing a compilation error message
```
Data.NameMap.fromList.: duplicate name ModuleName ....
```
And more specifically:
* Only occurs in the IDE (daml build is fine)
* Only in windows (ubuntu and macos DA laptops seem fine)
* It's confirmed on SDK versions 0.13.27, 0.13.24

Steps to reproduce:
```sh
git clone https://github.com/digital-asset/derivhack2019
cd derivhack2019/examples/hellocdm
git checkout v0.0.1 # currently also reproducible on HEAD
daml studio
```
Opening the `Main.daml` file should trigger this error.

@cocreature we expect participants of a Barclay's hosted event to run into this, so if this can be given high priority it would be really helpful. Event is on the 16th but they already have access to the above material - that's how we initially found out about it (two people reported it already).

**Comment by tweber-da** [comment]
Not a real fix, but if I re-export `Org.Isda.Cdm.MetaFields` in `Org.Isda.Cdm.Classes` and remove the module import of `Org.Isda.Cdm.MetaFields` in `Main.daml`, then the error disappears.
