### ISSUE TITLE
tidy up filesystem structure of the repo

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#31]
a draft of how to organize the components:

* [x] `release` -- what is now `daml-foundations/ci`
* [x] `daml-lf/` https://github.com/DACH-NY/daml/pull/454
    - `spec`
    - `archive`
    - `interpreter`
    - `data`
    - `transaction`
    - `lfpackage`
    - `repl`
    - `testing-tools`
* [x] `ledger-api/`
    - proto files
    - basic tests
* [ ] `haskell-ide-core/`
    - "will be its own component until we spin it out" -- @neil-da 
* [ ] `compiler/`
    - compiler
    - scenario interpreter
    - vs code extension?
* [x] `ledger/`
    - common libraries
    - sandbox
    - semantic tests
* [x] `language-support/`
    - `java/`
        + bindings
        + codegen
    - `js/`
        + bindings
        + ts codegen
    - `scala/`
        + bindings
        + codegen
* [x] `da-assistant/` (old)
* [x] `daml-assistant/` (new)
* [x] `navigator/` -- #783
* [x] `extractor/` -- #688
* [ ] `installers/`
* [x] `docs/`
    - all the sdk docs
* [x] `bazel_tools/`
    - utility functions, etc. the 
* [x] `dev-env`
    - as per https://github.com/DACH-NY/daml/issues/304#issue-414010639 , at least for now
* [x] `README.md`
* [x] `CONTRIBUTING.md`
* [x] `BAZEL*.md`
* [x] `LICENSE`, once we open source

moreover,

* [x] all sbt files are removed
* [x] all `BUCK` files are removed
* [ ] everything that does not fit in the above directories is removed
* [x] ledger-bindings removed, see #123

**Comment by associahedron** [comment]
I added a `/templates` directory for `daml new` templates. 

Should we close this ticket or update it?

**Comment by neil-da** [comment]
Closing it - let's track individual changes we still see desirable in separate tickets.
