### ISSUE TITLE
Problem with dot-notation for field access in SDK 0.12.1

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#310]
The following code produces an error whose location spans the entire file (0-10000).
```
daml 1.2
module FieldBug where
data AType = Con1 with field: Text
            | Con2 with field: Text

fieldBug : AType -> Text
fieldBug f = f.field -- error [1]
-- fieldBug f = field f -- works

{-
[1] 
error type checking value FieldBug.fieldBug:
  expected record type:
  * found: 
      TypeConApp {tcaTypeCon = Qualified {qualPackage = PRSelf, qualModule = Tagged ["FieldBug"], qualObject = Tagged ["AType"]}, tcaArgs = []}
-}
```
The code is accepted when the field accessor `field` is used instead of the dot notation `.field`.
SDK 0.12.31 works fine with this code.

**Comment by neil-da** [comment]
@jberthold-da which version is broken?

@martin-drhu-da could this have been your changes?

**Comment by martin-drhu-da** [comment]
This might be related. I'll look into it this afternoon.
