### ISSUE TITLE
Documentation of using navigator outside the SDK is outdated

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#3100]
The documentation of [Using Navigator outside the SDK](https://docs.daml.com/tools/navigator/index.html#using-navigator-outside-the-sdk) is outdated as of release `0.13.27`.
It still points to the `da` command and uses `da path` which doesn't exist anymore for the `daml` command.

**Comment by stefanobaghino-da** [comment]
Dropping in favor of #3237, which is a duplicate of this one (I already opened #6773 to close it, which is why I'm closing this one).
