### ISSUE TITLE
Add documentation on daml damlc inspect-dar to docs.daml.com

### ISSUE THREAD

**Issue by meet-da** [digital-asset/daml#3105]
Would be great to add information on usage of this command to https://docs.daml.com/concepts/identity-and-package-management.html or https://docs.daml.com/migrate/index.html, along with a description of our recommended approach on how this should be used as the source of truth on package identifiers that are then shared off-band with ledger api clients.

**Comment by meet-da** [comment]
FYI @bame-da @robin-da @moritzkiefer-da

**Comment by cocreature** [comment]
https://docs.daml.com/daml/reference/packages.html#inspecting-dars
