### ISSUE TITLE
Enforce that module names match file names

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#3106]
Currently, we do not enforce that module names match file names, e.g., you can have a module in place `A/B.daml` with the module name `A.C`. However, this causes all kinds of issues, e.g., imports will not be resolved properly so I believe it would be less confusing if we start to enforce this. Somewhat by accident we already do require this for everything but the last component or the imports from `A/B.daml` will not be resolved properly.

We should first warn about this and then break it in future releases.

**Comment by bame-da** [comment]
Since our quickstart didn't follow the rules in the docs, users likely have projects with poorly named modules. Therefore, let's only emit a warning for now:

```
Warning: Module names should always match file names, as per [documentation|https://docs.daml.com/daml/reference/file-structure.html]. This rule will be enforced in a future SDK version. Please change the filename to MODULE_NAME.daml in preparation.
```
Suggesting to change file name over module name, as that won't break any dependencies.
Then in Step2:
```
Error: Module names must match file names, as per [documentation|https://docs.daml.com/daml/reference/file-structure.html]. Please change the filename to MODULE_NAME.daml.
```
