### ISSUE TITLE
ledger-api: support per-party package uploads

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#311]
DAML's authorization rules allow in principle any party to upload new contract templates. All parties are always guaranteed that unknown contract templates are only referred to from contracts that they are an observer on, but never from contracts on which they are a signatory.

In practice though, allowing arbitrary code deployments requires for most ledger implementations that solid resource control for DAML engine execution is in place.

This ticket serves as a meta-ticket for designing and implementing per-party package uploads.

FYI: @neil-da @francesco-da @cbaatz-da

**Comment by gerolf-da** [comment]
Closing this ticket as it is tracked on the roadmap under DAML-52.
