### ISSUE TITLE
http-json needs API versioning support for future/backwards compatibility

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#3145]
When client is relying on certain version of API, and some “major” changes are introduced to the payload/error-handling, we need some versioning mechanism(uri/header) to prevent client failure

**Comment by leo-da** [comment]
@lima-da HTTP JSON API is still considered experimental. We do not yet want to commit to freezing the API. I would recommend DAML do it on its side for now. Once HTTP JSON API is stabilized we will get back to this issue.

CC @bame-da

**Comment by leo-da** [comment]
@hurryabit I assume we don't want to use semantic versioning in the JSON API URL? Don't need really need the patch version.

What is it going to be `<major>.<minor>` or just `<major>`?

- `/v1/create`, `/v1/search`....
or
- `/v1.0/create`, `/v1.0/search`.

**Comment by hurryabit** [comment]
@leo-da I'm fine with having just a major version.
