### ISSUE TITLE
`damlc docs` produces wrong choice documentation when an export list is used

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#3146]
(bug introduced by #2477 )
When a DAML module uses an export list, choices won't be documented correctly.
For the example module below, the choice `DoAThing` is documented as `**Choice External:DoAThing**` without argument fields (`(no fields)`), and the doc. comment disappears.

(Command 
`daml damlc docs ./Testing.daml -f markdown -o testing.rst  --include-modules Testing  --combine`)

If the export list is commented out, everything works as expected (the choice has its argument and the doc. comment is the description).

```haskell
daml 1.2 module Testing
  ( Exported(..), Something(..)) -- comment this out and it works
--  ( Exported(..), Something(..), DoAThing(..)) -- use this line and it works, too
  where

-- This was actually imported from another module in the real code
data Something = Something with contents: Text
   deriving (Eq, Show)

template Exported
  with somebody: Party
  where
    signatory somebody

    controller somebody can
      nonconsuming DoAThing: ()
        -- ^ This choice will come out as "external" in the documentation. This comment will vanish.
        with stuff: Something
        do pure ()
```

**Comment by jberthold-da** [comment]
The cause of this behaviour is that the `typeMap` used for choice documentation is made using `getTypeDocs`, which now filters by export list.

https://github.com/digital-asset/daml/blob/5bcdb3e8a088333f771fc86d0a863efdd99cd03b/compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs#L100

https://github.com/digital-asset/daml/blob/5bcdb3e8a088333f771fc86d0a863efdd99cd03b/compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs#L399

Obviously, users won't write a Choice name, as a data type, into the export list. I suggest to use a complete unfiltered type map for the choice documentation.
Happy to have a look at it some time, but I'm unavailable in the next two weeks.

**Comment by associahedron** [comment]
Thanks for the bug report! I will try to fix it soon.
