### ISSUE TITLE
Add a "copy code" option to (DAML) code sections in the documentation

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#3148]
It would be nice if there was a button to copy code sections out of the documentation into the clipboard. It's quite common these days and makes the UX of trying our code examples a bit bettter.

Bonus: add an option to "Open in Web IDE" for runnable DAML programs :)

**Comment by hurryabit** [comment]
@nemanja-memarovic-daml That might be something for you. cc @bame-da

**Comment by cocreature** [comment]
We have one now.
