### ISSUE TITLE
Flexible controllers : Error while writing scenarios. Last statement in do should be an expression

### ISSUE THREAD

**Issue by ashfaq-shaik** [digital-asset/daml#3163]
Sample code. https://gist.github.com/hurryabit/f5f9bc3aea9f7c9bbdaa88d3cbd1752e

**Problem:** Trying to retrieve contract id on choice exercise ends up failing
**Steps:**
- Modify line 51 to `resultContractId <- submit eric do`
- This will result in 
```
/home/sdk/workspace/Primer.daml:51:5: error:
    The last statement in a 'do' block must be an expression
      mycontract <- submit
                      eric do exercise suggestion AcceptFeature {sponsor = eric}compiler
```

**Comment by cocreature** [comment]
This is expected behavior. I’ve answered a similar question on stackoverflow recently, see if that helps: https://stackoverflow.com/questions/58252709/scenario-execution-fails

**Comment by ashfaq-shaik** [comment]
That helps thanks.
