### ISSUE TITLE
bazel/intellij sources of third parties dependencies

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#319]
The sources of the third party dependencies are not loaded by intellij.

**Comment by nicholassmith-da** [comment]
Known issue https://github.com/bazelbuild/intellij/issues/225
Summary: Try enabling  'Settings > Other Settings > Bazel Settings > Use a local jar cache'
(Seems to work)

**Comment by stefanobaghino-da** [comment]
The suggestion seems to work. @remyhaemmerle-da feel free to close the ticket if that's the case. :slightly_smiling_face:

**Comment by stefanobaghino-da** [comment]
Better late than never. 😂
