### ISSUE TITLE
Archive choice does not work over JSON API

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#3219]
I have a very simple DAML model:
```
module User where

template User with
    party: Party
  where
    signatory party

  choice Delete: ()
    controller party
    do
      pure ()
```

When I try to archive an instance of user via the JSON API by sending the payload
```
{
  templateId: { moduleName: 'User', entityName: 'User' },
  contractId: '#1632:2',
  choice: 'Archive',
  argument: {}
}
```
to the `command/exercise` endpoint, I get the following error:
```
{
  "errors": Array [
    "JsonError: Type Identifier(01b628a7ed48a676938444223da83a995913e10fe52e77631e5d785aa5930ad2,User:Archive) not found",
  ],
  "status": 400,
}
```
Exercising the `Delete` choice, however, works just fine and archive the contract.

My suspicion is that some part of the JSON API assumes that the `Archive` data type passed into the `Archive` choice is defined in the same module as the template, in this case `User`. This assumption would not be valid since the `Archive` data type is defined in `daml-stdlib`.

**Comment by leo-da** [comment]
It is trying to find a record definition for the `Archive` choice arguments. Argument record defined in the same module... but I guess we don't handle `Archive` properly.

**Comment by cocreature** [comment]
Note that on an LF level, the assumption that the choice argument type belongs to the same module and package as the template is just wrong in general not just for `Archive`. It happens to be the case, that right now `Archive` is the only case where `damlc` generates code that violates your assumption but I don’t recommend to fix this by special casing `Archive`. This is just asking to break again in the future.

**Comment by leo-da** [comment]
In this case what is the rule to lookup choice record identifier? Multiple templates from multiple packages might have choices with the same name, right? We need a unique way of identifying them?

**Comment by cocreature** [comment]
You first have to infer the template id (which you already do if it’s not specified). Based on that you should be able to figure out the template definition in the package and then you can look at the type of the choice. I guess in Scala, this probably means looking at https://github.com/digital-asset/daml/blob/36719717fa22706bd9c2fc2da8c81db1602c4a01/daml-lf/language/src/main/scala/com/digitalasset/daml/lf/language/Ast.scala#L562

**Comment by leo-da** [comment]
Here is the ADT from the interface reader.
DefTemplate` does not have a reference to choice record identifier.
https://github.com/digital-asset/daml/blob/06a4d5602583d903f4657ec4b4ff88eec2e02324/daml-lf/interface/src/main/scala/com/digitalasset/daml/lf/iface/DefDataType.scala#L169

**Comment by cocreature** [comment]
https://github.com/digital-asset/daml/blob/06a4d5602583d903f4657ec4b4ff88eec2e02324/daml-lf/interface/src/main/scala/com/digitalasset/daml/lf/iface/DefDataType.scala#L196
appears to have the type you are looking for. Note that on the LF level we also don’t require the choice argument to have a record type.

**Comment by leo-da** [comment]
yes, thanks, the identifier is in there.
```
Archive -> TemplateChoice(TypeCon(TypeConName(Identifier(2f42229dbdd037891ae4540614d950ac978a06e57665e18c5db82b6f74be1875,DA.Internal.Template:Archive)),ImmArray.ImmArraySeq()),true,TypePrim(PrimTypeUnit,ImmArray.ImmArraySeq()))),None)),
Iou:Iou_Transfer -> Normal(DefDataType(ImmArray.ImmArraySeq(),Record(ImmArray.ImmArraySeq((newOwner,TypePrim(PrimTypeParty,ImmArray.ImmArraySeq())))))), Iou:Iou_Merge -> Normal(DefDataType(ImmArray.ImmArraySeq(),Record(ImmArray.ImmArraySeq((otherCid,TypePrim(PrimTypeContractId,ImmArray.ImmArraySeq(TypeCon(TypeConName(Identifier(295527aa365d36ea87e4e3213c8f4ff9ee6ea216de208a8dd02e947fdecce2a7,Iou:Iou)),ImmArray.ImmArraySeq())))))))),
```

**Comment by leo-da** [comment]
> Note that on the LF level we also don’t require the choice argument to have a record type.
What type is that if not record? List?
