### ISSUE TITLE
Unable to launch DAML studio

### ISSUE THREAD

**Issue by IronFisher** [digital-asset/daml#3238]
I have gone through all the installation requirements for DAML including installing Visual Studio which runs successfully on my Mac as well as the latest Java SDK. I went through the quickstart and DAML successfully works on my system using the IOU on http://localhost:4000. I updated %PATH correctly and have gone through the instructions twice to make sure I'm not missing anything.

Here is what I launch: 
```
MacBook-Pro-2:quickstart aron.elston$ daml studio
/bin/sh: code: command not found

Failed to install DAML Studio extension from marketplace.
Installing bundled DAML Studio extension instead.
/bin/sh: code: command not found

Failed to install DAML Studio extension from SDK bundle.
Please open an issue on GitHub with the above message.
https://github.com/digital-asset/daml/issues/new?template=bug_report.md
/bin/sh: code: command not found

Failed to launch DAML studio. Make sure Visual Studio Code is installed.
See https://code.visualstudio.com/Download for installation instructions.

MacBook-Pro-2:quickstart aron.elston$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/aron.elston/.daml/bin
MacBook-Pro-2:quickstart aron.elston$ pwd
/Users/aron.elston/.daml/bin/quickstart
MacBook-Pro-2:quickstart aron.elston$ 
```

**Comment by cocreature** [comment]
Hi @IronFisher, we’ve had a similar question on Stackoverflow recently. Hopefully that should help with your issue as well, see https://stackoverflow.com/questions/58474794/unable-to-launch-daml-studio. If it doesn’t, let us know.

**Comment by cocreature** [comment]
Closing since @IronFisher accepted the answer to their stackoverflow question so I believe the problem has been solved. If you are still having issues let us know and we’ll try to help.
