### ISSUE TITLE
ContractId of non-disclosed contract leaked

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3246]
I've got a contract where I accidentally forgot to set `observer users`.

```
template AppSemaphore
  with
    operator : Party
    users : [Party]
  where
    signatory operator

    key operator : Party
    maintainer key
```

A contract instance exists with cid `#51:2` on my ledger.
Now when a user does a `fetchByKey @AppSemaphore operator`, the error I get is

```
Command interpretation error in LF-DAMLe: dependency error: couldn't find contract AbsoluteContractId(#51:2). Details: N/A.
```

This seems like a leak as the user shouldn't be able to ascertain whether any such contract exists.

**Comment by gerolf-da** [comment]
I'm afraid I don't understand the problem. The error message doesn't give away whether the contract exists or not, does it? What is being leaked here?

**Comment by bame-da** [comment]
I think it does. The error message says
> couldn't find contract AbsoluteContractId(#51:2)
That suggests that the ledger did a key lookup, found `#51:2`, but then decided that it's not in my PCS. So I now know a contract with the key I requested does exist, has ID `#51:2`, but it has not been disclosed to me.
That's more than merely knowing that I don't know of any contract with that key so I consider this a leak.

**Comment by gerolf-da** [comment]
You are right of course. I missed the `fetchByKey` bit.  Yes this definitely leaks more information than necessary.

**Comment by gerolf-da** [comment]
I tried to reproduce the error you are seeing, but I'm not able to.

Given 
```
daml 1.2
module Main where

template AppSemaphore
  with
    operator : Party
    users : [Party]
  where
    signatory operator

    key operator : Party
    maintainer key

template AppFetch
  with
    owner : Party
  where
    signatory owner

    controller owner can
      FetchIt : ()
        with
          party : Party
        do
          fetchByKey @AppSemaphore party
          return ()

setup = scenario do
  alice <- getParty "Alice"
  bob <- getParty "Bob"

  submit alice do
    create AppSemaphore with
      operator = alice
      users = [alice, bob]

  submit bob do
    create AppFetch with
      owner = bob
```
When I exercise `AppFetch.FetchIt` as `Bob` with the choice parameter `Alice`, I get the following error:
```
Submission of command ff3b85c27d069c23 has failed.
com.digitalasset.platform.server.api.ApiException: INVALID_ARGUMENT: Command interpretation error in LF-DAMLe: dependency error: couldn't find key GlobalKey(Identifier(dc923bae286f35618a63693e86b9aba6bc16d1337f6621c7454eeabc6eeed63c,Main:AppSemaphore),VersionedValue(ValueVersion(1),ValueParty(Alice))). Details: N/A.
```
How do I reproduce the leaky error message?

**Comment by stefanobaghino-da** [comment]
@bame-da can you follow up on @gerolf-da's question, please?

**Comment by bame-da** [comment]
Can no longer reproduce so I'm closing it.
