### ISSUE TITLE
Ledger API shows non-stakeholder contracts.

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3254]
The JSON API shows contracts whose creation was witnessed, even if the subscriber is not a stakeholder. I think that Navigator, JSON API, (flat)Transaction Service, and Active Contract Service should only show (events on) contracts on which the subscriber is a stakeholder.

@gerolf-da , I feel like the above was agreed at some point, but please chime in if you remember otherwise.

**Comment by gerolf-da** [comment]
Yes, that's right. `Create` should only be shown to stakeholders.

**Comment by leo-da** [comment]
json-api currently returns what gRPC API gives it to you. Should we change it on the sandbox side or do you want to filter out events in the json-api?

**Comment by bame-da** [comment]
I think this should be fixed in the Active Contract Service.

**Comment by bame-da** [comment]
This is causing me more trouble than expected. In Danban a Board consists of several contracts of different types, liked by keys. The model makes sure that the observers on all contracts of a board match up and that all key constraints are maintained. The UI relies on this.

However, if you remove an observer from a board, they still see it (and all constituent contracts). Once one of the constituent contracts gets changed, it disappears, leading to incomplete data and unexpectedly failing foreign key lookups, which breaks the UI. It's also a privacy leak. A non-stakeholder should not be able to find out that a contract has changed/been archived.

**Comment by leo-da** [comment]
@bame-da I don't know why this ticket is assigned to @S11001001 and myself... this is gRPC API/sandbox issue, there is nothing to fix in JSON API. Am I wrong?

cc @gerolf-da

**Comment by S11001001** [comment]
> I think this should be fixed in the Active Contract Service.

See #164.

Aside from that we would generally filter queries [when Postgres-powered] by stakeholders, as alluded to in #3754, rather than witnessParties as is done now.

**Comment by leo-da** [comment]
JSON API only shows Active Contracts, which are always `CreatedEvents`:
https://github.com/digital-asset/daml/blob/402ae2adf2615766bd56b52b558707a024d1c2e3/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/event.proto#L60-L66

JSON API specifies only one party in the `TransactionFilter`, and it is party ID from the JWT, the ID of the JSON API user.

So, if you see an ActiveContract via JSON API, you must be its stakeholder. Else it is a bug in the Ledger API.

**Comment by hurryabit** [comment]
@leo-da can you please check if it's a bug in the Ledger API Server? Would be good to know if we can close this ticket.

**Comment by leo-da** [comment]
@bame-da can you provide steps to reproduce the issue?

**Comment by bame-da** [comment]
```

daml 1.2
module Main where

template T
  with
    a : Party
    b : Party
  where
    signatory a

    controller b can
      C
        : ContractId T
        do create this with a = b

s = scenario do
  [a, b] <- mapA getParty ["a", "b"]
  t <- submit a do
    create T with ..
  submit b do
    exercise t C
```

Run the ledger with scenario `s`, then hit the JSON API as `a`. You'll see the resulting contract even though `a` isn't even on it.

**Comment by bame-da** [comment]
wrong button, sorry

**Comment by leo-da** [comment]
@bame-da @gerolf-da the above issue is not related to JSON API.

I have run the scenario and can confirm that Alice can see the new contract, the result of the exercise. Alice is not a signatory. This needs to be fixed in the sandbox.

![Screenshot from 2020-01-07 15-08-16](https://user-images.githubusercontent.com/27688859/71925700-a221ce00-315f-11ea-8ce1-9c24a6899d01.png)

**Comment by leo-da** [comment]
> @leo-da can you please check if it's a bug in the Ledger API Server? Would be good to know if we can close this ticket.

@hurryabit It is not a JSON API issue. However I don't want to close this issue. It has to be addressed.

**Comment by hurryabit** [comment]
@leo-da Can you please agree with @gerolf-da where to bucket this issue?

**Comment by leo-da** [comment]
> @leo-da Can you please agree with @gerolf-da where to bucket this issue?

Moved it into `Maintenance` and assigned to @gerolf-da for prioritization.
