### ISSUE TITLE
LedgerClient should allow configuration of maxInboundMessageSize

### ISSUE THREAD

**Issue by andrewking-da** [digital-asset/daml#3273]
Currently there is no way to set this, and it is conceivable someone may need to.

**Comment by gerolf-da** [comment]
@andrewking-da: which language binding are you referring to?
The scala bindings have a method `forChannel` to construct the binding with a customized channel (i.e. with increased `maxInboundMessageSize`): https://github.com/digital-asset/daml/blob/bc63f2f8de9c3c6549f3d3394b162d0f15d745f0/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/LedgerClient.scala#L125
Same with the rxjava bindings:
https://github.com/digital-asset/daml/blob/bc63f2f8de9c3c6549f3d3394b162d0f15d745f0/language-support/java/bindings-rxjava/src/main/java/com/daml/ledger/rxjava/DamlLedgerClient.java#L93

**Comment by andrewking-da** [comment]
I was referring to scala bindings. Thanks, my mistake, I didn't see forChannel.
Maybe a name like createWithChannel or something would make it more obvious?
I will close.
