### ISSUE TITLE
Extractor: No events being written to the exercise table.

### ISSUE THREAD

**Issue by ivan-bernikov-da** [digital-asset/daml#3274]
Given I am running quickstart
And I have extractor running with command 
```
daml extractor postgresql --connecturl 'jdbc:postgresql://localhost:5432/extractor' --user extractor --password extractor --ledger-host localhost --ledger-port 6865 --party Alice
```

And I can see 4 tables in extractor database with 2 contracts and 2 transactions: 
```
table_name	count
"contract"	"2"
"transaction"	"2"
"state"	"2"
"exercise"	"0"
```
When I execute a choice "Iou_Split"
Then I see new 2 contracts been added by 1 transaction and 0 records in exercise table.
```
table_name	count
"contract"	"4"
"transaction"	"3"
"state"	"2"
"exercise"	"0"
```

But I should see at least one record in exercise table.

**Comment by gerolf-da** [comment]
As far as I can tell the `exercise` table has never been filled for the single table data format that ASX is running.
