### ISSUE TITLE
Ledger api test tool: Extend test framework to initialize parties on all participants

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#3380]
waiting until non-local parties are known to other participants.

@SamirTalwar , @stefanobaghino-da please rephrase as necessary or close if you are already tracking this elsewhere.

This should address the lion-share of the flaky tests listed in #3059

I can help do a multi-participant test run to try out the code beforehand if you want.

**Comment by oliverse-da** [comment]
Thanks for merging #3401 , @SamirTalwar .

You mention that PR 3401 is "Part of a solution to #3380.", i.e. can we not close this issue or were you planning do do more here?

**Comment by SamirTalwar** [comment]
Can't close it yet. #3401 is pure refactoring; it doesn't actually change anything yet. I'm working on running the ledger-api-test-tool against Canton v0.3.0 in our DAML test run, then I'll start hacking at the synchronisation.

**Comment by oliverse-da** [comment]
Got it. By the way, the interface of creating a test cluster in #3401 is really elegant.

**Comment by SamirTalwar** [comment]
Glad you like it!
