### ISSUE TITLE
json-api: replay on database consistency violation

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#3387]
In the database update, all potential concurrent update problems (with either requests originating from the same json-api daemon, or multiple daemons connected to the same database) are caught as constraint violations, so can always be solved by rereading the offset and proceeding from there (redoing ledger-api calls, &c).

If we read (and create if absent) surrogate template IDs and commit immediately up-front, we can avoid some pointless consistency violations that way, too. Since we currently do one template ID at a time, we can commit after updating the offset for each template ID; we must do the initial offset read and the final offset write for a given template ID (with contract updates in between) in the same transaction, though.

Read-committed is fine for search, because there is no problem getting newer contracts than we wrote during our own update phase. We wouldn't want to read uncommitted, because we sometimes insert on create then delete on archive in the course of a single transaction stream.

Split from #2781, followup to #3192.

**Comment by leo-da** [comment]
as we discussed we would not do immediate commit for a surrogate template ID. We would commit it as part of the larger transaction.

This should not cause too much contention, the re-try would happen only once when two users query the same template ID concurrently, and only if that template ID has not be queried before. The first successful transaction would insert the surrogate template ID.
