### ISSUE TITLE
Missing `asMap()` conversion method

### ISSUE THREAD

**Issue by pajb-da** [digital-asset/daml#341]
In class `com.daml.ledger.javaapi.data.Value` the expected conversion method `Value` -> `DamlMap` is missing.

**Comment by nicholassmith-da** [comment]
The `asMap()` is implemented.

@pajb-da Were you looking at the documentation or the code?

**Comment by pajb-da** [comment]
I don't think it's  in 10012.1. The decompile of the code does not show it, and IntelliJ won't complete it. Is the source out of sync with the JAR? I've attached the source I see in IntelliJ, and the pom as well that resolves the JAR
[Value.class.txt](https://github.com/digital-asset/daml/files/3063807/Value.class.txt)
[pom.xml.txt](https://github.com/digital-asset/daml/files/3063811/pom.xml.txt)

**Comment by gerolf-da** [comment]
Right, `TextMap` support was only added to the java bindings 2 days ago. SDK 0.12.1 has been released 6 days ago. It will be available in the next SDK release, but it also requires a full implementation in the sandbox and compiler. Closing this ticket in the meantime.
