### ISSUE TITLE
HTTP JSON - use GET for search endpoint to avoid %templateId

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/daml#3427]
This is a suggestion to change the `%templates` format in the `contracts/search` endpoint yet again. See #2964, #2777 for background.

The suggestion is to change the POST endpoint `contracts/search` and merge it with the existing GET endpoint `contracts/search`, but allowing the template filter to be passed as arguments in the URI, e.g. `https://localhost:7575/contracts/search?module=Main?name=IOU` instead of a JSON body payload.

This idea came about as one of the projects my team is working on is an external REST api adapter/translator, allowing you to create `Request` contracts on the ledger and then having a bot fetch the data through an external API and evoke a choice/callback on the `Request`. As part of this I have been looking at existing REST APIs and I noticed that most examples I found that query a service, are in the form of HTTP `GET`s, with the arguments part of the URI, rather than a POST. I was wondering whether this would be helpful for avoiding the esoteric `%templates` argument. The other advantage of this would be that we could consolidate the two POST/GET `contracts/search` into a single GET endpoint.

The disadvantage is of course that this would be a breaking change.

Also, I'm not certain whether there are any technical obstacles to this.

**Comment by leo-da** [comment]
@lucianojoublanc-da I agree that `%templates` field is confusing.

There are a few issues with supporting `GET` for `contracts/search`
1. We allow querying multiple template IDs
2. If we support `GET` with parameters for `contracts/search`, we should do the same for `contracts/lookup`.
3. Supporting query over HTTP `GET` won't be possible, at least the way it is currently designed. E.g. to send the below query you would need to base64 encode it, in order to pass it as an HTTP parameters.
```
{ person: { name: “Bob”, dob: “1956-06-21” }, city: “London”, createdAt: “2019-04-30T12:34:12Z” }
```

In any case, convince @bame-da that we need to fully support `GET` and get him to prioritize this issue.

**Comment by lucianojoublanc-da** [comment]
Hi Leo!

> 1. We allow querying multiple template IDs

Is it possible to pass repeated parameters in a REST GET?

> 3. Supporting query over HTTP GET won't be possible,

Yes, I agree. Is it not possible to combine the two, so you always have the template in the URL, but can change to a POST if you want to query fields? i.e. does a POST support passing some arguments in the URL?

**Comment by leo-da** [comment]
> Is it possible to pass repeated parameters in a REST GET?

Everything is possible, it is the question of how user-friendly it will be :)
We can accept a list of comma-separated template IDs. However you specify template ID as:
```
                "templateId": {
                    "packageId": "ac3a64908d9f6b4453329b3d7d8ddea44c83f4f5469de5f7ae19158c69bf8473",
                    "moduleName": "Iou",
                    "entityName": "Iou"
                },
```
where `packageId` is optional. So, we need to change the encoding so it is HTTP parameter friendly, or base64 encode the entire JSON command/request that is being sent over HTTP GET.

**Comment by leo-da** [comment]
> does a POST support passing some arguments in the URL?

it does.

**Comment by gerolf-da** [comment]
@lucianojoublanc-da: Closing this issue now as the URL encoding seems to be problematic and requires special logic for encoding the identifier on both server and client side.
