### ISSUE TITLE
Confusing error when imports have clashing package names

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3429]
I have two packages `danban-0.0.1` and `danban-2.0.0`. When I import both into a third project and try to use them, the one imported first is unavailable with error message

```
  Could not load module ‘Danban’
  It is a member of the hidden package ‘danban-0.0.1’.
  You can run ‘:set -package danban’ to expose it.
  (Note: this unloads all the modules in the current scope.)
```

I think duplicate package names should be supported. If that's technically too difficult, a better error message with a mitigation route is needed.

**Comment by cocreature** [comment]
I just verified that the error is reasonable now:
```
Message:  Ambiguous module name `Main':it was found in multiple packages: foobar-0.0.1 foobar-0.0.2
```
You can solve it by renaming modules.
