### ISSUE TITLE
Incorrect resolution of Party Show instance in cross SDK upgrade

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3432]
I'm running into an issue trying to upgrade Danban using latest SDK head with `Tuple2` exported from `Types.daml`.

When building what's currently on https://github.com/digital-asset/danban/tree/upgrade-v2, I get the error suggesting incorrect package resolution for show instances:

```
File:     daml/Danban/V2/Upgrade.daml
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message:
  error type checking value Danban.V2.Upgrade.$cshowsPrec1:
  type mismatch:
  * expected type:
  96bfd43793dacfe23a271123885be8e3c2fed90334725180e95abdb017f318d8:GHC.Show:Show Party
  * found type:
  a87284688f364e2cce4e0820f550931651577105563e67e6e6a685f6ddbc579e:GHC.Show:Show Party
  * expression:
  09cbdafc43489d4cc8752ff94bcdb69a48b2a78c8f72b775f159c3f0bd96bd28:DA.Internal.LF:$fShowParty
```

**Comment by robin-da** [comment]
We will have to generate instance wrappers for `Eq, Show, Choice, TemplateKey, HasField`.

**Comment by robin-da** [comment]
Why the compiler actually finds the instance at all is still a bit of a mistery to me.

**Comment by cocreature** [comment]
fixed as part of the new approach to cross-SDK deps
