### ISSUE TITLE
Refactor DAML template desugaring

### ISSUE THREAD

**Issue by shayne-fletcher-da** [digital-asset/daml#344]
- We have quite a lot of stuff in `RdrHsSyn` - is it worth having `DamlSyn` for our custom stuff?
- The mega tuple in `extractTemplateBodyDecls` probably wants to be a record one day.

**Comment by shayne-fletcher-da** [comment]
One reason against introducing `RdrDamlSyn.hs` is that induces changing `ghc.cabal` on the DA fork to include the new source file. Even that though won't be the end of the story because at this time the list of `ghc-lib-parser` modules is hard-coded into `ghc-lib-gen`. All in all, the additional complexity of managing the new file here may not be worth it.

**Comment by ndmitchell** [comment]
True, does sound like too much effort. We could write it and #include it into the other file to keep our changes separate but that's not very pleasant. Feel free to close this if you want.

**Comment by shayne-fletcher-da** [comment]
Agreed. Let me deal with the mega tuple first though.

**Comment by shayne-fletcher-da** [comment]
Mega tuple dealt with. Resolving.
