### ISSUE TITLE
Navigator and Extractor show more Active Contracts than expected

### ISSUE THREAD

**Issue by piyushbedi-da** [digital-asset/daml#3498]
**Given** the quickstart java project.

**When** I:
1. Login as Alice and exercise the IOUTransfer choice with the argument of Bob on my 1 active IOU Contract
2. Login as Bob and exercise the IOUTransfer Accept choice on the IOUTransfer contract from Alice
3. Log back in as Alice

**Then**
1. In **Navigator Console**, logged in as Alice, I see an active IOU Contract when I type: 
`Alice>sql select * from contract where archive_transaction_id is null;`
![Screen Shot 2019-11-18 at 11 45 26 am](https://user-images.githubusercontent.com/43772671/69017135-fa0e4500-09f8-11ea-8160-b341d8ba379a.png)

I transferred the IOU from Alice to Bob, so I don't expect Alice to see an Active IOU Contract anymore.
When I try to exercise a choice on this IOU contract as Alice, the Sandbox throws the following error:
```
Submission of command e45d00362bf0f69b has failed.
com.digitalasset.platform.server.api.ApiException: INVALID_ARGUMENT: Command interpretation error in LF-DAMLe: The following errors occured: node NodeId(0) (Identifier(0e070f5e735cea63f0ed08bcaff4987a236174c94a2d6fd89950db1bc34ca207,Iou:Iou)) requires authorizers Bob, but only Alice were given. Details: N/A.
```
So, while Navigator is showing this as an Active Contract and displaying the choices on it, I can't exercise them as Alice.

2. In **Extractor**, when connected as Alice, on a postgres DB:
a. The Contracts table shows the following:
`daml_export=# select event_id, archived_by_event_id, contract_id, transaction_id, archived_by_transaction_id, template, witness_parties from contract;`
![Screen Shot 2019-11-18 at 11 40 57 am](https://user-images.githubusercontent.com/43772671/69017068-5b81e400-09f8-11ea-8446-98b1b1d86824.png)

So extractor is also showing an Active IOU Contract for Alice (Contract #5:1). Similar to the expectations of Navigator above, I expect Extractor to not show a visible Active IOU contract to Alice.

Alice isn't an observer, signatory or controller on Active IOU Contract #5:1, so should not have visibility of it.

A possible lead is that extractor and Navigator are adding entries to the contract table when they see a Contract Create event within a transaction that the party has visibility of, but disregarding whether the party should have visibility of the contract. 
When looking at the events in Transaction 5 in navigator:
`Alice>sql select id, transaction_id, contract_id, witness_parties, signatories, acting_parties, observers, template_id, subclass_type, choice from event where transaction_id=5;`
It appears that Alice can see the Contract Creation event of Contract #5:1
![Screen Shot 2019-11-18 at 11 40 25 am](https://user-images.githubusercontent.com/43772671/69017078-7b190c80-09f8-11ea-86a5-1e760f417a80.png)

**Comment by piyushbedi-da** [comment]
A follow-up question: Should Alice be able to see a Create Contract Event for a Contract she should not be able to observe, even though it is in a Transaction on which she has some observability?

**Comment by rautenrieth-da** [comment]
Related to #3006

**Comment by piyushbedi-da** [comment]
After reading through #3006, it seems that Extractor is writing divulged contracts into the Contract table. I believe it should only be writing disclosed contracts. 
@rautenrieth-da is there any progress on this issue?

**Comment by cocreature** [comment]
@gerolf-da With #4594 and #4586 merged can we close this?

**Comment by gerolf-da** [comment]
Yes indeed.
