### ISSUE TITLE
Fix SDK Docs style, so headers are displayed with enough spacing

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#3516]
Here are few examples:
https://docs.daml.com/app-dev/bindings-scala/index.html#generating-scala-code
https://docs.daml.com/app-dev/grpc/proto-docs.html#com-digitalasset-ledger-api-v1-exercisecommand
https://docs.daml.com/json-api/index.html#example-session
https://docs.daml.com/app-dev/bindings-java/codegen.html#generate-the-decoder-utility-class

There is not enough space to separate a header from the above text.

**Comment by bame-da** [comment]
seems fixed
