### ISSUE TITLE
Make daml2ts feature complete

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#3518]
The following features must be supported before `daml2ts` feature complete:
- [x] enum types
- [x] variant types (depends on https://github.com/digital-asset/daml/issues/3622)
- [x] sum-of-product types, i.e., multi-part types constructor names (depends on https://github.com/digital-asset/daml/issues/3622)
- [x] the `Decimal` type
- [x] the `Numeric` types
- [x] nested `Optional`s
- [x] `Optional` record fields
  *[MH: there's nothing special about such fields in the current implementation of the JSON API]*
- [x] tuples (is there anything to do?)
  *[SF : Yes in my opinion. The wire representation of DAML-LF tuples does not conform to typescript expectations].*
 *[SF : Update : DAML-LF of course doesn't have tuples. Thus you write your DAML in terms of tuples but the typescript developer must account for that by parsing records and it seems there is some push-back on changing the wire representation of such records in DAML-LF/json-api land].*
  *[MH: We've decided to leave them as is, i.e., a pair `(a, b)` will be presented by the record `{_1: a, _2: b}`.]*
- [x] `TextMap`
- [x] `fetchByKey`
- [x] `exerciseByKey`
- [x] associated type `T.Key` for template `T`
- [x] choice return types (https://github.com/digital-asset/daml/pull/3895)

The following are nice to have:
- [x] don't produce unused imports
- [x] don't produce files without any definitions

**Comment by shayne-fletcher-da** [comment]
Typescript has tuples:
```
  const json:any = JSON.parse ('[3,"foo"]');
  const tup2: [number, string] = jtv.Result.withException(jtv.tuple([jtv.number(), jtv.string()]).run(json));
  console.log ("tup2 = " + JSON.stringify(tup2));
```
DAML does too but DAML-LF does not. One writes DAML in terms of tuples and naively the typescript developer would expect to decode them as per the code above. This mismatch has tripped at least me up before.

**Comment by S11001001** [comment]
Re tuples: For the [LF<->JSON codec](https://docs.daml.com/json-api/lf-value-specification.html), I generally favor LF fidelity and overall simplicity of mapping over convenience for one [even if major and important] downstream, e.g. daml2ts. Thus, I prefer the current encoding.

Regardless, such a thing oughtn’t be decided in a daml2ts issue.

**Comment by shayne-fletcher-da** [comment]
> Regardless, such a thing oughtn’t be decided in a daml2ts issue.

Protocol, protocol, protocol. Happy to take the discussion wherever you think best Stephen! Please advise on the forum. In any case, my position is, it's our job to give the typescript developer a natural and seamless experience regardless of the complexity it induces on us. I suggest, this nuance is neither.

**Comment by shayne-fletcher-da** [comment]
>  e.g. daml2ts. 
This isn't about `daml2ts` I agree. This is about the codec.

**Comment by S11001001** [comment]
> Please advise on the forum.

[JSON API milestone](https://github.com/digital-asset/daml/issues/new?milestone=HTTP+JSON+API+Maintenance) good.

**Comment by shayne-fletcher-da** [comment]
> JSON API milestone

Moved discussion on this to https://github.com/digital-asset/daml/issues/3909.

**Comment by hurryabit** [comment]
This is done now. Support for the future generic map type is tracked in #4188.
