### ISSUE TITLE
ledger architecture roadmap

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#353]
Notes about internal API redesign by @meiersi-da and @dajmaki:

* `ReadService`: https://github.com/digital-asset/daml/blob/05577ab2d22fa60097318d9af538955f486bf2ec/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/ReadService.scala
* `StateInit` should probably be turned into a method, since it's an event that only happens at the beginning of the stream and never again.
* Harmonize the terminology with existing terminology as much as possible -- i.e. `Update` vs. `LedgerEntry`, `Heartbeat` vs. `Checkpoint`, `UpdateId` vs. `LedgerOffset`, etc.
* Things to put in `Configuration`: at least positive and negative difference between effective time and record time, a cap on the maximum record time, and some info regarding whether the ledger is strict about these values -- we want a "testing mode" where they are not enforced. Alternatively, we can set them to be infinite.
* Should `applicationId` be private to the committer?
* `NodeId`s should be opaque enough to prevent malicious users from understanding the full structure of the blinded transaction that they get.
* `referencedContracts` contains contracts that are involved in `fetch` / `exercise` and other ledger operations, that have _not_ been created in the same transaction. It's needed because it'll contain contracts that have been divulged.
* `WriteService`: https://github.com/digital-asset/daml/blob/05577ab2d22fa60097318d9af538955f486bf2ec/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/WriteService.scala
* Right now `submitTransaction` returns `Unit` which does not let the caller apply backpressure, because it doesn't have enough info to learn when it should.
* `IndexService`: https://github.com/digital-asset/daml/blob/05577ab2d22fa60097318d9af538955f486bf2ec/ledger/participant-state-index/src/main/scala/com/daml/ledger/participant/state/index/v1/IndexService.scala
* `IndexService` is a bit misleading because it's really implementing the whole of the read end of the ledger API

**Comment by gerolf-da** [comment]
Closing this due to staleness.
