### ISSUE TITLE
Request?: JSON-API support for fetching package metadata

### ISSUE THREAD

**Issue by jkk-vmw** [digital-asset/daml#3539]
Howdy, DA folks.

Just wondering whether the new JSON-API has any plans for supporting fetching of DAR package metadata in JSON and also template interfaces in nice JSON (similar to Eth ABI).

From Ethereum's ABI, an example:

```
contract Foo {
  function bar(real[2] xy) {}
}

You can get json metadata resembling:
{
   ... // some other metadata, like userdoc, devdoc, compiler info
    abi: [
       { type:'func', name:'bar', inputs:[{type:'real[2]', name:'xy'}]}
    ]
  }
}
```

**Comment by cocreature** [comment]
Hi @jkk-vmw, there is already an open issue for this in https://github.com/digital-asset/daml/issues/3508

**Comment by cocreature** [comment]
Closing as a duplicate. Feel free to reopen if I missed something and this is different from #3508
