### ISSUE TITLE
Correctly serialize writing of transactions in the sandbox

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#3544]
Currently, commands are processed by the sandbox as follows:

- Commands are processed in parallel. During command interpretation, the DAML engine accesses the database using individual SQL queries. This means that relevant data may change between individual reads during command interpretation, or between the time of command interpretation and the time the transaction gets written into the database.
- Transactions are fed into a queue that assigns transaction offsets and manages the advancing of the ledger end.
- The queue is consumed in batches, all transactions within a batch are written to the database in parallel. This is done to increase write throughput.
- Writing a DAML transaction to the database happens in one (big) SQL transaction, which also checks that the transaction to be written is still valid.

There is a potential issue: as transactions are written in parallel, the order in which they are written is random, and they may not see each others effects.

In order to guarantee a consistent transaction (tree) stream, DAML transaction `TX_n` must see the effects of all DAML transactions `TX_m` with `m < n` while its validity is checked during serialization.

Check whether this can be achieved with the help of the database (e.g., by choosing an appropriate transaction isolation level and ordering the start/commit of the SQL transactions). If not, the batching in the SQLLedger needs to be removed.

Note: another idea is to store the whole ACS in memory and perform all validity checks serially against this in-memory data. However, this would not scale to the ACS sizes of real world ledgers.

**Comment by stefanobaghino-da** [comment]
@rautenrieth-da if I'm not mistaken, this has been fixed. Can you close the ticket if that's the case?

**Comment by stefanobaghino-da** [comment]
@rautenrieth-da (and possibly reference the PR that closed this :slightly_smiling_face: )

**Comment by rautenrieth-da** [comment]
Fixed by #5781. The new post-commit validation disabled batch processing of persistence queue items.

**Comment by stefanobaghino-da** [comment]
Uh, sorry, I thought you fixed this with your implementation, that's why I asked you to step in.
