### ISSUE TITLE
Support distributed ledger topology for DAML Script

### ISSUE THREAD

**Issue by darko-da** [digital-asset/daml#3555]
DAML Script currently is only able to connect to a single node. This means that all Parties that act in such a script have to be on that Node.

When using DAML Script for "Market or Demo Initialization" on a distributed setting like Canton, it would be great to be able to configure which Party is hosted on which Node.

**Comment by cocreature** [comment]
Here’s my proposed interface for this:

- We add a new `--participant-mapping` argument to `daml script`. If this is specified, `--ledger-host` and `--ledger-port` must not be specified.
- This argument points to a file containing the party mapping in the following JSON format
```json
{ 
  "default_participant": {"host": "localhost", "port": "8080"},
  "participants": {
   "bob’s participant": {"host": "bob.example.com", "port": "8080"},
   "alice’ participant": {"host": "alice.example.com", "port": "8080"},
  },
  "party_participants": {
    "alice": "alice’ participant",
    "bob": "bob’s participant"
  }
}
```
- The `default_participant` field is optional.
- On any DAML script command that acts as a specific party (Right now that’s `submit` and `query`), we do a (2-level) lookup to figure out the Ledger API parameters. If the party is not in the map, we use `default_participant`. If `default_participant` does not exist, we error out.
- DAML script commands that do not act as a specific party (right now that’s `allocateParty`), will get an additional argument of type `Optional Text` with the text being the participant. If it is `None`, we will use `default_participant` (or error out if that’s not set. If it is `Some participant` we will use the corresponding participant node defaulting to `default_participant`.

I don’t care much about the names, so happy to change them to something else.
