### ISSUE TITLE
Initial table rendering for scenario results in Visual Code does not display table grid

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#358]
When first running Scenario Results from a DAML file, the table view does not show visible grid lines.  When toggling to the transaction view and back, the grid lines appear

Steps to reproduce

1) Open a DAML file with scenario in Visual Code, click on Scenario results

Initially the table view results will look like so 
![image](https://user-images.githubusercontent.com/25179017/55882287-4267a980-5b72-11e9-807b-e0e0dc55204c.png)

2) Then click on `Show transaction view` (this displays correctly), and click on `Show table view`.  At this point the grid displays correctly

![image](https://user-images.githubusercontent.com/25179017/55881055-f4ea3d00-5b6f-11e9-8778-635abb5d57f1.png)

**Comment by martin-drhu-da** [comment]
Who's Emma? :D

**Comment by moritzkiefer-da** [comment]
I hope you remembered to buy a present for Emma!

**Comment by dasormeter** [comment]
> I hope you remembered to buy a present for Emma!

Indeed!  Confidential reminder removed :)

**Comment by cocreature** [comment]
Not sure where this came from but this has not been an issue in the last year so closing.
