### ISSUE TITLE
RecoveringIndexer doesn't clean up resources on recovery

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#3592]
When `RecoveringIndexer` restarts/recreates `JdbcIndexer` upon errors, it doesn't clean up the resources, which leads to a leak of database connections.

In an error case, `RecoveringIndexer` should make an attempt at closing the previously allocated resouces or manage the resources differently.

**Comment by SamirTalwar** [comment]
I think this was handled by #3871. Can you confirm?

**Comment by SamirTalwar** [comment]
If #3871 didn't handle this, #4034 probably did.
