### ISSUE TITLE
Include DAML files from DAR dependencies

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3617]
When including DAR dependencies in a DAML project, I would like the DAML files to be included in the resulting DAR file.

**Comment by hurryabit** [comment]
@bame-da Could you please elaborate why you want this?

**Comment by bame-da** [comment]
I think 2019 @bame-da wanted that because DABL shows you the DAML for the packages you upload and it seemed odd to only have _some_ of the source code available. However, with `data-dependencies` becoming the norm now, I think that's to be expected.
