### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by bethaitman-da** [digital-asset/daml#363]
I have a backlog of small docs improvements that I'd like to make, and I'm not sure exactly where to store them, so I thought I'd try an issue.

- Application development docs docs
  - [ ] Clean up proto docs and make them more clear and useful
  - [ ] Slim down docs on `trace_context`, because it's not in use
  - [ ] Recommend prerequisites for looking at the Java documentation (someone recommended: Java 8 streams api and functional programming knowledge; Reactive Java (Rx) library knowledge; Basic understanding of the ledger, transactions and events and the notion that it is an immutable stream of event;  DAML training, and understanding of contracts and choices)
- DAML docs
   - [ ] Move as many DAML snippets as possible to `literalincludes`
   - [ ] Move as many `literalincludes` as possible to use `start-after` and `endbefore`
   - [ ] Add something on `self`, which refers to (the template? the contract ID? check), and `this`, which is the data in the current contract
   - [ ] Differences between DAML and Haskell
- Troubleshooting:
   - [ ] Sandbox `Address already in use` error if you didn't shut down the Sandbox last time
- Setup
  - [ ] Any recommendations for running VMs (eg: Ubuntu not Alpine Linux; some size minimums)
  - [ ] Dependencies on netbase and ca-certificates if you're running on a really stripped-down VM
  - [ ]  list of sites accessed by 'da upgrade' so can configure these as proxy exclusions?

**Comment by cocreature** [comment]
I think all of these points have either been addressed or are not enough of an issue to be addressed. Feel free to reopen if you disagree.
