### ISSUE TITLE
Remove support for absolute contract IDs in contract keys

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3634]
The interpreter already blocks relative contract IDs in contract keys, but this behaviour is undocumented, and harms compositionally. However, this behaviour is undocumented, and not consistently enforced across the DAML toolchain.

We should completely drop support for contract ids in contract keys, statically (and, if necessary at runtime) check this, and document the restriction.

FYI @dajmaki @meiersi-da @martin-drhu-da

**Comment by meiersi-da** [comment]
Thanks for creating this @bame-da . I agree with this.

Whoever end up implementing it, please make sure that there's the following two tests:
- a test checking that one cannot create a contract of a template with a key that contains a relative-contract-id
- a test checking that one cannot create a contract of a template with a key that contains an absolute-contract-id

**Comment by stefanobaghino-da** [comment]
@remyhaemmerle-da your thoughts?

**Comment by remyhaemmerle-da** [comment]
This is mostly done by #4048.
I do not think the tests described by @meiersi-da are there.

**Comment by meiersi-da** [comment]
@remyhaemmerle-da with the removal of relative-ids, we should now fully support contract-ids in contract-keys shouldn't we? If that's the case, then we don't need the tests.

**Comment by stefanobaghino-da** [comment]
> * a test checking that one cannot create a contract of a template with a key that contains an absolute-contract-id

**Comment by remyhaemmerle-da** [comment]
@meiersi-da Unfortunately, the new contract id scheme does really solve the problem of contract ID in contract key. Some ledger implementations (e.g. canton and corda) have to suffix contract ID before committing to the ledger, so in general the contract IDs of new contracts are not fully known at evaluation time.  

Concerning the tests in the engine side: 
* I dropped the support for relative contract IDs in #5991, so we do not need a test for that.
* @oggy- removed the support of contract ID in  #4048, and added one test based on scenario (`daml-lf/tests/scenario/daml-1.dev/no-contract-ids-in-keys/Test.daml`), that checks one cannot create a contract of a template with a key that contains an absolute-contract-id.

From the test of the ledger API level, I am not sure it is worthwhile to check that. 
In general we do not want to test all the case of transaction that the engine will not validate. 

For the documentation, It seems that @bame-da updated it in #5923

To my point of view this ticket should be closed.

**Comment by stefanobaghino-da** [comment]
I've added https://github.com/digital-asset/daml/issues/6254 to track that right now it's impossible to test against a "rogue" engine.

**Comment by leonidr-da** [comment]
@bame-da I had a slack conversation with @remyhaemmerle-da about revisiting this issue. Could we please reassess the difficulty involved here? I think you understand how much easier it would be to manage "constellations" of contracts using this.
