### ISSUE TITLE
Include Maven and sbt-extras wrapper scripts in templates

### ISSUE THREAD

**Issue by circlespainter** [digital-asset/daml#3641]
It would allow template users to get up and running without installing Maven and/or sbt beforehand; it would also prescribe the versions to be used.

**Comment by gerolf-da** [comment]
Thank you for the suggestion, @circlespainter. I'm not aware that maven wrappers are widely. Regarding sbt-extras, I don't think it works on windows and SBT is rather [easy to install](https://www.scala-sbt.org/1.x/docs/Setup.html) these days on the usual platforms.

**Comment by cocreature** [comment]
Given that these templates aren’t the primary templates we recommend anymore, I’m closing this.
