### ISSUE TITLE
DAML Studio, scenario runs: table view header texts overlap with long party names

### ISSUE THREAD

**Issue by circlespainter** [digital-asset/daml#3642]
Attaching a screenshot from the Iou quickstart template ("Acme Bank" overlaps with "Alice"):

![image](https://user-images.githubusercontent.com/6113296/69699441-98349600-10f0-11ea-9c52-f5fbcc2083b9.png)

VSCode 1.40.1 on Linux Ubuntu 19.10 (x64), DAML SDK 0.13.37

**Comment by cocreature** [comment]
Thanks for the report, @rohanjr do you maybe want to look into this?
