### ISSUE TITLE
Use a single string for template ids

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#3647]
Currently, the template ids have the type
```typescript
{ packageId: string; moduleName: string; entityName: string; }
```
where the `packageId` is optional when you send a request to the API but is present in all responses.

I propose we replace this by a single string of the format
```
<packageId>:<moduleName>:<entityName>
<moduleName>:<entityName>
```
depending on whether the package id is present or not.

Using strings instead of objects has at least two advantages:
1. template ids can be used as keys in JavaScript objects
2. template ids can be used as keys for discriminated unions, as described in https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions

The latter is particularly useful in a context where you want a single UI component to display contracts of different types. This happens, for instance, during upgrading when your ledger has only been partially upgraded so far and you have contract instances of the old and the new template you need to show in a UI.

Using colons as the separator is safe since we don't allow them in identifiers, see [the DAML-LF spec of identifiers](https://github.com/digital-asset/daml/blob/master/daml-lf/spec/daml-lf-1.rst#identifiers). The spec also uses colons as separators between package ids, module names and entity names.

In case you actually need the individual components of a template id you received from the JSON API, you could now get them via
```javascript
  const [packageId, moduleName, entityName] = str.split(":");
```

**Comment by S11001001** [comment]
I don't think we should do this, because we neatly avoid all mistake or disagreement of what an appropriate delimiter is by the current encoding, for now and the future. One need only browse the LFv1 spec history to see all sorts of cases where the rug was pulled from under anyone who thought their delimiter choice was safe. That's the reason we decided not to do this when originally designing the JSON API.

> In case you actually need the individual components of a template id you received from the JSON API, you could now get them via

and likewise the inverse.

**Comment by hurryabit** [comment]
> and likewise the inverse.

That is not really true. I had types `v1.Foo` and `v2.Foo` in scope in the context of an upgrade and defined `type Foo = v1.Foo | v2.Foo`. If we follow my proposal, I can do
```
switch (foo) {
  case: v1.Foo.templateId: { ... }
  case v2.Foo.templateId: { ... }
}
```
and get exhaustiveness checking in TypeScript. If you need to mangle the `templateId` field through a function first, you don't get exhaustiveness checking. We also build a big hashmap containing all templates, indexed by their `templateId`, in the support library for the `daml2ts` codegen. Using strings as keys in a hashmap is way more pleasant than using objects.

I suppose you're referring to the fact that we used the dot as a delimiter between module and entity names. That was _obviously_ not a smart idea and I already opposed it back then but didn't have the power to stop it from happening. The colon is not allowed as a symbol in a name component and never has been. We've actually used it as a delimiter in all contexts where we need a textual representation of a fully qualified identifier for quite some time now and it hasn't caused any issues. Thus, I don't see why the historic mistake should stop us from doing something that has proven itself new.

**Comment by hurryabit** [comment]
Can we please keep this conversation going?

**Comment by S11001001** [comment]
> I can do

Would a reference to `v1.Foo.templateId.packageId` not have been an equally functional discriminator in this `switch` example?

> I suppose you're referring to the fact that we used the dot as a delimiter between module and entity names.

I am referring to _several_ extensions of allowed character sets as well.

**Comment by hurryabit** [comment]
> I am referring to _several_ extensions of allowed character sets as well.

I'm fine to extend the spec saying that colons are taboo. In fact, we don't need to add any more characters since we now have an escaping mechanism.

> Would a reference to `v1.Foo.templateId.packageId` not have been an equally functional discriminator in this `switch` example?

In _this particular_ example, I could have used the package id as the discriminator. However, what I would like to do in general, is to write something like the `getOwner` function in the code snippet below. This will become very ugly if your discriminator is a triple of strings.
```typescript
// "Expert" interface in the TypeScript bindings library:
interface Template<Payload, TemplateId> {
    templateId: TemplateId;
    validate: (payload: Payload) => boolean;
}

type Contract<Payload, TemplateId> = {
    templateId: TemplateId;
    contractId: string;
    payload: Payload;
}

const fetchAll = <Payload, TemplateId>(template: Template<Payload, TemplateId>): Contract<Payload, TemplateId>[] => {
    throw Error(`fetchAll for ${template} not yet implemented.`)
}

// Generated by the DAML to TypeScript codegen:
type Foo = {
    fooOwner: string;
}
const Foo: Template<Foo, 'pkg1:X:Foo'> = {
    templateId: 'pkg1:X:Foo',
    validate: (_) => true,
}

type Bar = {
    barOwner: string;
}
const Bar: Template<Bar, 'pkg2:Y:Bar'> = {
    templateId: 'pkg2:Y:Bar',
    validate: (_) => true,
}

// User written code:
type FooBarContract =
    Contract<Foo, typeof Foo.templateId> |
    Contract<Bar, typeof Bar.templateId>;

const fetchWorld = (): FooBarContract[] => {
    const foos: FooBarContract[] = fetchAll(Foo);
    const bars: FooBarContract[] = fetchAll(Bar);
    return foos.concat(bars);
}

const getOwner = (fooBar: FooBarContract): string => {
    switch (fooBar.templateId) {
        case Foo.templateId: return fooBar.payload.fooOwner;
        case Bar.templateId: return fooBar.payload.barOwner;
    }
}
```

**Comment by leo-da** [comment]
I get both points... but I personally prefer a structured template ID, the way we defined it right now over a plain string.

I also get what @hurryabit is going after. However, TypeScript is not the only language we are trying to target with the JSON API.

@hurryabit DDD is the answer. You already defined the domain model the way you want it, the way it fits your specific domain. Handle the conversion as part of the JSON serialization/deserialization. JSON is just a transport, so treat it that way.

**Comment by leo-da** [comment]
Played with typescript a bit... really like that TS's type guard around a singleton type figures out the correct type.

In any case, singleton type does not have to be a primitive. Here is my experiment with a non-primitive singleton type (checks for exhaustiveness), look for `enum TemplateId `. It is definitely more verbose:

```
// Interface of the TypeScript bindings library:

interface TemplateIdT {
  packageId: string;
  moduleName: string;
  entityName: string;
}

const FooTemplateId: TemplateIdT = {
  packageId: "pkg1",
  moduleName: "X",
  entityName: "Foo"
};

const BarTemplateId: TemplateIdT = {
  packageId: "pkg2",
  moduleName: "Y",
  entityName: "Bar"
};

enum TemplateId {
  FooTemplateId,
  BarTemplateId
}

interface Template<T> {
  templateId: TemplateId;
  validate: (payload: T) => boolean;
}

interface HasTemplateId<I> {
  templateId: I;
}

type Contract<T> = {
  templateId: TemplateId;
  contractId: string;
  payload: T;
};

const fetchAll = <T, I>(
  template: Template<T> & HasTemplateId<I>
): (Contract<T> & HasTemplateId<I>)[] => {
  throw Error(`fetchAll for ${template} not yet implemented.`);
};

// Generated by the DAML to TypeScript codegen:

type Foo = {
  fooOwner: string;
};

const Foo: Template<Foo> & HasTemplateId<TemplateId.FooTemplateId> = {
  templateId: TemplateId.FooTemplateId,
  validate: _ => true
};

type Bar = {
  barOwner: string;
};

const Bar: Template<Bar> & HasTemplateId<TemplateId.BarTemplateId> = {
  templateId: TemplateId.BarTemplateId,
  validate: _ => true
};

// User written code:
type FooBarContract =
  | (Contract<Foo> & HasTemplateId<TemplateId.FooTemplateId>)
  | (Contract<Bar> & HasTemplateId<TemplateId.BarTemplateId>);

const fetchWorld = (): FooBarContract[] => {
  const foos: FooBarContract[] = fetchAll(Foo);
  const bars: FooBarContract[] = fetchAll(Bar);
  return foos.concat(bars);
};

const getOwner = (fooBar: FooBarContract): string => {
  switch (fooBar.templateId) {
    case TemplateId.FooTemplateId:
      return fooBar.payload.fooOwner;
    case TemplateId.BarTemplateId:
      return fooBar.payload.barOwner;
  }
};
```

**Comment by hurryabit** [comment]
@leo-da Your example does not what you intended. In particular, the enum definition
> ```ts
> enum TemplateId {
>   FooTemplateId,
>   BarTemplateId
> }
> ```
does not define `TemplateId.FooTemplateId` to be the `FooTemplateId` you defined above but rather defines it to be the string `'FooTemplateId'`. Thus, the definition of `Foo.templateId` in
> ```ts
> const Foo: Template<Foo> & HasTemplateId<TemplateId.FooTemplateId> = {
>   templateId: TemplateId.FooTemplateId,
>   validate: _ => true
> };
>```
is not what the codegen would generate. In fact, it cannot generate something like this in an open world where we don't know all the templates in advance.

The only types for which you can do this pseudo dependently typed programming in TypeScript are strings and numbers. It does not work for objects. This is one of the main reasons why I would like to have template ids to be strings.

The other main reason is that using template ids as keys of a dictionary is otherwise unnecessarily hard since objects are compared by reference when used as keys of JavaScripts `Map` type, whereas strings are compared by value.

That said, I would like to move forward with that ticket. I'm totally aware that the approach I suggested has some dangers and I'll take responsibility if they bite us. However, we are making a trade-off between some potential problems, which I think won't bite us, and user experience. In this instance, I'm heavily leaning towards user experience and take a small risk, which we are in control of anyway.

**Comment by leo-da** [comment]
@hurryabit OK. `templaetId` will be a string in the JSON.
