### ISSUE TITLE
Enable usage of structured logging

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#3699]
We already use slf4j as the standard logging interface in the Ledger API Server. We now want to standardize the log messages so they are represented in a structured way. The format we chose is [logfmt](https://www.brandur.org/logfmt). An existing library that seems helpful: [Escalog](https://github.com/BatchLabs/escalog)

The keys used should have a consistent name (i.e. avoid using the various forms of `cmdId`, `commandId`, `commandID`, ...).

* The current log message should be logged with the key `msg`.
* IDs to log include:
  * Party
  * CommandID
  * TransactionID
  * EventID
  * Offset

**Comment by stefanobaghino-da** [comment]
I have done some research on the topic and I changed the title of the ticket to better reflect the outcome of our discussions.

More explicitly, I changed the title from:
> Use logfmt format to log

to:
> Enable usage of structured logging

After some research, `logfmt` support in the SLF4J ecosystem appears to be relatively immature.

Further conversions with @mziolekda and @miklos-da re-framed the main value as "enabling the usage of structured logging" for operators that need to deploy participants. As such, I looked into more mature and supported tools that could enable this and the [`Logstash Logback Encoder`](https://github.com/logstash/logstash-logback-encoder) seems to be:
- a mature, reliable piece of software
- actively developed
- configurable and flexible
- using well-understood and widely adopted formatting standards (mainly JSON)

In particular, one of the problems that have been identified is adding logging information that is added as key-value pair(s) when using a structured logging encoder _and_ is preserved when not using that (e.g. using a default pattern-based encode when developing). The library ships with `StructuredArguments` that are thought precisely for this use case (docs [here](https://github.com/logstash/logstash-logback-encoder/#event-specific-custom-fields)). Thanks to @miklos-da for pointing me to it.
