### ISSUE TITLE
Ledger API 2.0

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#37]
Create a `v2.0` API interface parallel to the `v1.x`. The new version should implement all the change proposals we collected [here](https://docs.google.com/document/d/1eIC57QYHr0bZ-6pI5_vY0yEwfJDuyCHvLNIOaTnNHOw/edit#heading=h.mat3sypsq7bz). For a transitional period we could support both versions.

**Comment by stefanobaghino-da** [comment]
@gerolf-da Is this still valid?

**Comment by gerolf-da** [comment]
Not at the moment. Will close.
