### ISSUE TITLE
DARs produced with SDK 0.13.32 cannot be loaded with SDK 0.13.38

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#3707]
You can reproduce it by running
```
DAML_SDK_VERSION=0.13.38 daml damlc inspect-dar ~/.daml/sdk/0.13.32/daml-libs/daml-trigger.dar
```
The error message you get is
```
damlc: user error (Cannot decode package daml-trigger-0.0.1-fafe5390509b929e3caa9ea00a84f8fa8af12279a1cc982a7f876053d5c6aa5c/daml-trigger-0.0.1.dalf
ProtobufError "DuplicateDataType (TypeConName {unTypeConName = [\"Daml\",\"Trigger\"]})"
)
```

**Comment by hurryabit** [comment]
My gut feel says this that we borked something about the protobuf encoding/decoding when we implemented string interning.

**Comment by cocreature** [comment]
I took a brief look a this and I think this is probably harmless. The issue appears to be that the trigger DAR used `1.dev` which is not supposed to be backwards compatible. I haven’t looked into what exactly is going wrong but I tested building our skeleton dar with `0.13.32` and running `damlc inspect` from `0.13.38`. If I used `daml build --target=1.dev` to build the dar and then run `damlc inspect`, things fail with an even worse error.

```
damlc: user error (Cannot decode package
ProtobufError "EmbeddedError \"Failed to parse embedded message.\" (Just (EmbeddedError \"Failed to parse embedded message.\" (Just (EmbeddedError \"Failed to parse embedded message.\" (Just (EmbeddedError \"Failed to parse embedded message.\" (Just (EmbeddedError \"Failed to parse embedded message.\" (Just (EmbeddedError \"Failed to parse embedded message.\" (Just (WireTypeError \"Wrong wiretype. Expected embedded but got VarintField 2\"))))))))))))"
)
```

Unless you have an example that is reproducible outside of `1.dev` I would suggest to close this issue.

**Comment by hurryabit** [comment]
Using 1.dev is most likely the reason here. If we run into this again, we should consider including a hash of the `.proto` used in the compiler in the produced DALF.
