### ISSUE TITLE
Add text primitives in DAML 1.dev for experiments.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#3710]
The idea is to add LF primitives for: 

- `toUpper/toLower`
- `replicate/fill`
- `break/breakOn/stripInfix`... and other missing `List` counterparts
- `containsOnlyAlphabet: Text -> Text -> Bool` (useful for `isDigital, isAlpha, isWhitespace, isAscii` and similar functions)
- `split/join`

cc @cocreature @jberthold-da

**Comment by cocreature** [comment]
Just to add a bit more context, we will first add them to DAML-LF 1.dev and then see which ones actually turn out to be useful and only stabilize those.

**Comment by associahedron** [comment]
`toUpper`, `toLower` seem quite hard to specify and implement consistently, because of Unicode. 

Possible solutions:

* A1: only convert ASCII characters to upper/lower.

  * **pro:** simple, easy to specify and implement
  * **con:** cannot deal with extended character set, e.g. á -> Á

* A2: define a more general function `mapChars : Text -> Text -> Text -> Text` (or something) where the first two inputs specify the mapping, and define `toUpper`/`toLower` in DAML using that primitive (e.g. `toUpper = mapChars "abcdefghijklmnopqrstuvwxyz" "ABCDEFGHIJKLMNOPQRSTUVWXYZ"` for example).

  * **pro:** more flexible, can deal with more characters and more mappings as needed.
  * **con:** slower than other options, less simple than A1, less comprehensive than A3.

* A3: Use a specific implementation of "toUpper/toLower" from the Java land. For instance, `String.toUpperCase()` but with a **fixed locale** such as `US`.

  * **pro:** More comprehensive.
  * **con:** Tying the behavior of DAML to another language's behavior, meaning the primitive is hard to implement without a JVM, and basically unspecifiable. Choice of locale is arbitrary. (But it has to be made, otherwise we may get different behavior on different JVM instances.)

Leaning toward **A1** or **A2** here.

**Comment by associahedron** [comment]
`break`, `span`: because of callbacks, these seem like they would be just as slow implemented as a primitive (as opposed to implementing them in DAML), so they're not really worth turning primitive.

`breakOn`, `stripInfix`: both of these can be implemented in terms of the other. `stripInfix` seems more primitive to me, and `breakOn` can easily be defined in terms of `stripInfix`. (But we'll see.)

`containsOnlyAlphabet`: seems reasonable. This has the same inherent slowness issue as pointed out in A2 (that it gets very slow as the alphabet gets large). The alternative is to add full-blown regexy primitives like character classes and such. (Having a built-in `regexMatch : Text -> Text -> Bool` isn't insane, as long as it's very well specified.)

`split`, `join`: The Haskell names for these are usually `splitOn` and `intercalate`,  but I find `split` and `join` to be more straightforward names, so I like this.

**Comment by cocreature** [comment]
I took a brief look at the unicode standard, in particular, section 4 in https://www.unicode.org/versions/Unicode12.0.0/ch04.pdf paragraph “Case Mapping”.  It looks like a nice option might be to use the data from `UnicodeData.txt` which is not dependent on weird things but not use `SpecialCasing.txt` because nobody likes special cases and that is context dependent.

However, I have no clue how easy it is to do that on the JVM or anywhere else so while this seems easy to specify and less restrictive than nly allowing ASCII, I’m not sure it is actually a reasonable option.

I don’t really like A2 and it seems to go against the spirit of those primitives which are all about performance and I agree that A3 is not a very nice specification even though it probably does what you want™ in basically all cases. So I’m leaning towards A1, what do you think @remyhaemmerle-da? @filmackay Would ASCII be sufficient for your usecases?

**Comment by associahedron** [comment]
That sounds good to me. If A1 is sufficient for now but later it turns out we need something more powerful, we can always implement that more powerful primitive later.

**Comment by associahedron** [comment]
> Just to add a bit more context, we will first add them to DAML-LF 1.dev and then see which ones actually turn out to be useful and only stabilize those.

How does this work, though, what is the criteria for "useful" here?

**Comment by cocreature** [comment]
We’ll do benchmarks to see which primitives end up bringing significant performance improvement (on a certain codebase that you can probably guess :wink: ).

**Comment by cocreature** [comment]
We confirmed that our usecase for  now only requires ASCII so let’s go with that for now to keep things simple at the very least until we know that we want to actually stabilize this primitive.

**Comment by remyhaemmerle-da** [comment]
I would like to have the benchmarks and set up the bar before doing the implementation.

**Comment by associahedron** [comment]
> I would like to have the benchmarks and set up the bar of minimum valuable speed up before doing the implementation.

I think we have to implement most of it (except maybe tests) before we can benchmark to see if it was worth it, otherwise we aren't controlling for other differences.

**Comment by dajmaki** [comment]
I'm not too happy about adding these kind of high-level primitive operations to DAML-LF. Is there currently no way to implement these in DAML itself? If not, then what is the minimum operations required to implement them in DAML? If they can be implemented, but are too slow, then we should improve the interpreter rather than creating (more) workarounds.

**Comment by cocreature** [comment]
We can implement them in DAML but we got the feedback that they are too slow. Rather than try to guess which ones are actually the problem, we want to add a whole bunch of them to `1.dev` so we can easily test which ones actually make a difference and then either add those as a primitive or see if we can optimize it. The plan is not to stabilize all of these primitives to a stable version of DAML-LF.

**Comment by dajmaki** [comment]
Why not fix the root cause?

**Comment by cocreature** [comment]
Because making a new interpreter is a lot of work whereas adding a bunch of primitives is to try out which parts actually need optimizing is very cheap.

**Comment by dajmaki** [comment]
I wasn't advocating for a new interpreter, but rather improving the current one. There's still room for improvement (tail call optimization, fold builtin etc.).

**Comment by remyhaemmerle-da** [comment]
> > I would like to have the benchmarks and set up the bar of minimum valuable speed up before doing the implementation.
> 
> I think we have to implement most of it (except maybe tests) before we can benchmark to see if it was worth it, otherwise we aren't controlling for other differences.

I do not get it.  You have use cases which are currently slow, have'nt you? If we cannot measure real speed up for those use cases, the addition is not very worthwhile anyway.

**Comment by cocreature** [comment]
Even if we improve the current interpreter, I think it’s very helpful to know which parts actually need to be optimized.

**Comment by remyhaemmerle-da** [comment]
Fine. I changed the name of the Issue to make it clear that it is for experiments only. 
We will have to come with another one, if we want to freeze any of those in DAML-LF.

**Comment by jberthold-da** [comment]
> `break`, `span`: because of callbacks, ...

Agree, difficult to implement using the predicate argument.
 
> `breakOn`, `stripInfix`: both of these can be implemented in terms of the other. `stripInfix` seems more primitive to me, and `breakOn` can easily be defined in terms of `stripInfix`. (But we'll see.)

```
breakOn x /= fmap (second (x<>)) . stripInfix x
stripInfix x == second (fromOptional [] . stripPrefix x) . breakOn x
```
:heavy_check_mark: 
I may mention that in the typical use case the `breakOn` is called with a single _character_ (but we don't have that type in LF :man_shrugging: )
 
> `containsOnlyAlphabet`: 
Yes, and the alphabet is typically not big, that is the point of it IMHO
 
> `split`, `join`: The Haskell names for these are usually `splitOn` and `intercalate`, but I find `split` and `join` to be more straightforward names, so I like this.

`join` is taken, with a different type `m (m a) -> m a` . I'd stick with the Haskell names.

Overall, the main goal is to eliminate all uses of `explode/implode` in code operating on `Text`
I think the above are good candidates to test with.

**Comment by associahedron** [comment]
@jberthold-da Thanks for the feedback! And point taken about `split/join`, they'll be `splitOn/intercalate` to match Haskell.

**Comment by associahedron** [comment]
Ok, ran into a small issue with the plan above.

Because tuples are mismatched between DAML and DAML-LF (the former are records in the latter), the types of `breakOn` and `stripInfix` aren't ideal. I'm going to replace these with a different primitive,

```
sliceIndex : Text -> Text -> Optional Int
```

that returns the index of the first argument inside the second, if it exists.

Then the others can be defined in terms of `sliceIndex`:

```
breakOn k x =
    let i = fromOptional 0 (sliceIndex k x)
    in (take i x, drop i x)

stripInfix k x = do
    i <- sliceIndex k x
    Just (take i x, drop (i + length k) x)
```

**Comment by associahedron** [comment]
@cocreature pointed out that `take` and `drop` aren't primitive, so I'm adding those.

**Comment by cocreature** [comment]
I think just making `splitAt` a primitive might be nicer but I’m happy to leave that up to you.

**Comment by jberthold-da** [comment]
> I think just making splitAt a primitive might be nicer ...

Agree, but that again returns a pair so we'd be back to square one.
Or should I say "I think just making pairs primitive might be nicer" ? ;-)

**Comment by associahedron** [comment]
These are merged.
