### ISSUE TITLE
Define ledger offset ordering in ledger-api-domain

### ISSUE THREAD

**Issue by miklos-da** [digital-asset/daml#3742]
The multiple definitions for ordering LedgerOffsets should be consolidated with appropriate test coverage:
- `language-support/java/bindings-rxjava/src/test/scala/com/daml/ledger/rxjava/grpc/helpers/TransactionsServiceImpl.scala`
- `language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/offset/LedgerOffsetOrdering.scala`

**Comment by gerolf-da** [comment]
There are multiple definitions because they are in separate languages (that coincidentally happen to share the same runtime). One wouldn't be able to consolidate the implementations across JavaScript and Python for example.
