### ISSUE TITLE
Code Snippet in documentation wrong / confusing

### ISSUE THREAD

**Issue by darko-da** [digital-asset/daml#3745]
The code snippet shown in https://docs.daml.com/app-dev/bindings-java/codegen.html#integrate-with-build-tools is confusing.
While the text says it's an excerpt it is not immediately clear that this is the case from looking at the code.
Additionally the way the snippet looks now, it is not valid as opening/closing tags don't match.

Suggestion, either make it clear that some code is missing (i.e. using ellipses) or simply adapt the range shown to be `:lines: 47-78,94-95`

https://github.com/digital-asset/daml/edit/master/docs/source/app-dev/bindings-java/codegen.rst
Line 97

**Comment by garyverhaegen-da** [comment]
Having tried to use various Maven-based tools in the past, and having had similar issues figuring the missing context from the snippet, my recommendation would be to show the snippet inline (with the correct range, as noted in the OP), but also have a clear direct link to the full, functional pom this is a snippet from.
