### ISSUE TITLE
Align http.domain.ActiveContract and http.dbbackend.Queries.DBContract

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#3754]
Related to #3254

**Comment by leo-da** [comment]
we are planning to cleanup JSON API ActiveContract format a little bit. Right now it is
```
  case class ActiveContract[+LfV](
      contractId: ContractId,
      templateId: TemplateId.RequiredPkg,
      key: Option[LfV],
      argument: LfV,
      witnessParties: Seq[Party],
      signatories: Seq[Party],
      observers: Seq[Party],
      agreementText: String)
``
is it going to cause any pain if we remove any of the following fields:
- key com.digitalasset.ledger.api.v1.event.CreatedEvent#contractKey
- signatories com.digitalasset.ledger.api.v1.event.CreatedEvent#signatories
- observers com.digitalasset.ledger.api.v1.event.CreatedEvent#observers
- agreementText com.digitalasset.ledger.api.v1.event.CreatedEvent#agreementText

**Comment by leo-da** [comment]
We agreed that:
- we would keep `key`
- remove `signatories`, `observers` and `agreementText`.
- andd `stakeholders`

**Comment by leo-da** [comment]
@bame-da is using signatories, observers and witnessParties in Danban project.
we can only remove agreementText.

**Comment by bame-da** [comment]
> we can only remove agreementText
I disagree. There's no other way to get your hands on the agreement clause.

**Comment by leo-da** [comment]
@bame-da for some reason I got the impression that nobody needs `agreementText` and it might even be removed from the DAML. cc @hurryabit

**Comment by hurryabit** [comment]
As long as DAML has the `agreement` clause, I'd prefer to keep it in the JSON API as well. If we ever decide to remove it from DAML, it's going to be a breaking change anyway.
Thus, the only remaining action seems to be to remove `witnessParties` from the API. I'm fine with that since it's a pretty leaky abstraction anyway.

**Comment by leo-da** [comment]
@bame-da are you fine with that? I thought you needed `witnessParties`
However you should be able to derive them... according to our spec:

CreatedEvent
------------------
https://github.com/digital-asset/daml/blob/402ae2adf2615766bd56b52b558707a024d1c2e3/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/event.proto#L60-L66

ArchivedEvent
--------------------
https://github.com/digital-asset/daml/blob/402ae2adf2615766bd56b52b558707a024d1c2e3/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/event.proto#L102-L110

ExercisedEvent
---------------------
https://github.com/digital-asset/daml/blob/402ae2adf2615766bd56b52b558707a024d1c2e3/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/event.proto#L152-L168

**Comment by leo-da** [comment]
We are removing `witnessParties`:
```
  case class ActiveContract[+LfV](
      contractId: ContractId,
      templateId: TemplateId.RequiredPkg,
      key: Option[LfV],
      argument: LfV,
//      witnessParties: Seq[Party],
      signatories: Seq[Party],
      observers: Seq[Party],
      agreementText: String)
```
