### ISSUE TITLE
Fix JSON API `/contracts/lookup` endpoint

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#3755]
It currently allows only `GET` requests, which is a mistake:
https://github.com/digital-asset/daml/blob/8124569cc6a25cd89f4df61887a12e50b577a038/ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala#L134

**Comment by leo-da** [comment]
@hurryabit this should give you fetch by contract ID and fetch by contract key... when it is fixed.

**Comment by hurryabit** [comment]
Can we please add documentation for this endpoint?

**Comment by leo-da** [comment]
see the TODO in the above PR.
