### ISSUE TITLE
Navigator Logs printed to stdout in SDK 0.13.39

### ISSUE THREAD

**Issue by darko-da** [digital-asset/daml#3784]
In DAML SDK 0.13.39, when running the command
```> daml ledger navigator --host [host ip] --port [host port]```

The Navigator prints out all logs on stdout instead to a file.

---------
Gerolf's comment
> this is a side effect of reducing the size of the SDK by smushing together all jars and losing the respective logging configurations in the process.

**Comment by gerolf-da** [comment]
This bug was introduced in #3678.

**Comment by garyverhaegen-da** [comment]
Fix has been merged; 0.13.38 behaviour will be restored as of next release (presumably 0.13.41).
