### ISSUE TITLE
Enable safe retry pattern upon when lost-message or rejected command are indistinguishable by app

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#3787]
The ReadService spec allows resubmitting rejected commands with the same command-id as long as MRT is larger as part "a resubmission of a transaction with a higher `maximumRecordTime` must be allowed" below:

```
    * - *rejection finality*: if there is a [[Update.CommandRejected]] update
    *   with [[SubmitterInfo]] `info`, then there is no later
    *   [[Update.TransactionAccepted]] with the same associated [[SubmitterInfo]]
    *   `info`. Note that in contrast to *no duplicate transaction acceptance*
    *   this only holds wrt the full [[SubmitterInfo]], as a resubmission of a
    *   transaction with a higher `maximumRecordTime` must be allowed.
```

But the implementation does not allow this:

```
-- This embodies the deduplication in the Ledger API.
CREATE UNIQUE INDEX idx_transactions_deduplication
  ON ledger_entries (command_id, application_id);
```

**Comment by oliverse-da** [comment]
Discussed this during upstream sync. This will be dealt with as part of the time model implementation in 2020Q1 and by the approach of moving read/indexer side validation to the write/submit path. Once that is in place, callers keep command-id unchanged and rely on the submit-time deduplication check to provide feedback on whether the command has been seen before. Once a reject-notification has been received, apps that cannot tolerate more than once writes, will have sufficient information to resubmit with a new command-id.

**Comment by stefanobaghino-da** [comment]
Is this now obsolete due to the recent changes to the time model? If you, can you close it @oliverse-da?

**Comment by oliverse-da** [comment]
Thanks for the ping, @stefanobaghino-da , indeed resolved with the new time model and the new index schema, i.e. the `participant_events` table does not have a unique index on `command_id` or `application_id`. Thanks @rautenrieth-da and @stefanobaghino-da for your work!

**Comment by stefanobaghino-da** [comment]
Thanks for the quick response. To be fair @rautenrieth-da was 100% in charge of leading and implementing the whole thing, so the credit is completely on him. :wink:
