### ISSUE TITLE
Not exported things are still documented

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#38]
I see documentation for DA.Text.parseInt_, which isn't exported (or shouldn't be).

**Comment by bethaitman** [comment]
I've just come across this again with `data Consuming` - https://github.com/digital-asset/daml/blob/master/daml-foundations/daml-ghc/daml-stdlib-src/DA/Internal/Template.daml#L124

**Comment by associahedron** [comment]
This isn't a bug, except in expectation. Damldoc does not look at export lists. The only way to hide declarations at the moment is to use `-- | HIDE`.

**Comment by neil-da** [comment]
Not a bug, but a perfectly reasonable expectation...

**Comment by associahedron** [comment]
> Not a bug, but a perfectly reasonable expectation...

Agreed. It's on my list of "ways in which damldoc should be more like haddock". (This is also a cautionary tale about reinventing the wheel...)
