### ISSUE TITLE
Installer link pop-in in the getting started docs.

### ISSUE THREAD

**Issue by fmota-da** [digital-asset/daml#380]
If you go to https://docs.daml.com/getting-started/installation.html it takes a short but noticeable while for the installer links to appear. The "empty space" where the installer links shows up gives the impression of a glitch.

(I'm on Safari. It doesn't make a difference whether or not I have Ghostery running, so I believe this is a common experience.)

It would be nicer if the empty space were something else, e.g. a static link to the installer that gets replaced by the dynamic link.

I imagine also that as it stands, if someone has javascript disabled, they never get an installer link. (They would also have a hard time navigating the website in general.)

**Comment by cocreature** [comment]
Don’t think this is going to change given that it hasn’t come up within the last year so closing. Feel free to reopen if you disagree.
