### ISSUE TITLE
implement "callable updates" as "create and exercise" Ledger API command

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#382]
Many people have expressed the desire of being able to define "top level updates" in their .daml files that they can call from their application.

While talking to @martin-drhu-da , it occurred to me that we can implement that easily with the existing infrastructure if we add a "CreateAndExercise" command to the Ledger API, which as the name suggests bundles a `CreateCommand` and `ExerciseCommand` in one go.

Then, the "top level update" can be implemented as a template that has the submitter party as only argument and signatory, and then a choice (or multiple choices) that contain the argument of the top level update.

cc @martin-drhu-da @neil-da @bame-da @andrae-da @filmackay

**Comment by gerolf-da** [comment]
@francesco-da: strictly speaking we cannot reuse the `ExerciseCommand` directly, because the user cannot fill the `contract_id` field with a sensible value.

We could add a dedicated "application service" request that ultimately will be converted to a `CreateCommand` and `ExerciseCommand`:
```
message CreateAndExerciseRequest {
  Identifier template_id = 1;
  Record create_arguments = 2;
  String choice = 3;
  Record choice_argument = 4;
}
```

How do you want to handle failure scenarios? 

Create | Exercise | Overall
------- | -------- | -------
Failed | - | Failed
Successful | Failed | Retry exercise n times (if applicable), then fail?
Successful | Successful | Successful, return the transaction tree? (trivial to implement after #406 and #479)

**Comment by gerolf-da** [comment]
Alternatively, we can implement the `CreateAndExercise` as an atomic set of LF create and exercise commands, although that means we'd need to open up [command translation](https://github.com/digital-asset/daml/blob/07858455c1dc84e58038162c9ca0c7b5aec08847/daml-lf/engine/src/main/scala/com/digitalasset/daml/lf/engine/CommandTranslation.scala#L366) to relative contract IDs.

**Comment by gerolf-da** [comment]
Conclusion, similar to [`translateExercise`](https://github.com/digital-asset/daml/blob/07858455c1dc84e58038162c9ca0c7b5aec08847/daml-lf/engine/src/main/scala/com/digitalasset/daml/lf/engine/CommandTranslation.scala#L306), we'll create a method that produces an `Update` expression for both creating the contract and exercising the choice.

**Comment by bame-da** [comment]
I'm not sold on the value of this addition. You are saving developers a simple "check for existence and create the Action contract if it doesn't" step in the automation. You still can't get return values from Updates in the application layer and still can't access pure DAML functions.

**Comment by gerolf-da** [comment]
@bame-da: Return value from exercise is implemented by #479.

**Comment by gerolf-da** [comment]
you could then execute a pure function (in a slightly round-about way) in terms of a create-and-exercise.

**Comment by bame-da** [comment]
Yeah, but you get the side-effect of writing a transaction. Would it be so difficult to flip this around and allow evaluation of functions with serializable arguments and return type `a` or `Update a`, where `a` is serializable?
The semantics would be that functions of type `Update a` are submitted as a transaction.

**Comment by bitonic** [comment]
done, see #563
