### ISSUE TITLE
Rename argument field of contracts to payload

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#3826]
Currently, the contracts you receive from the `/contracts/...` endpoint or in the events of an exercise have a field `argument` which contains the payload of the contract instance. IMO, this name is not particularly great for two reasons:
1. It is unclear what this is an argument to. (I suppose it's referring to the fact that this once was the argument to create. But by this logic almost everything is an argument.)
2. We also have an `argument` field for choices. Using the same name twice makes it harder to explain things and can possibly lead to avoidable confusion.

I suggest we rename the `argument` field of the contracts you receive from the JSON API to `payload`. I'm open to other names as well, but they must be allowed field names in surface DAML since we're sooner or later going to have something like
```haskell
data Contract a = Contract { contractId :: ContractId a, payload :: a, ... }
```
in DAML (Triggers) and I would prefer to have the same name across the board.

cc @gerolf-da @bame-da

**Comment by garyverhaegen-da** [comment]
We should also try to always refer to the data in a contract as its payload (docs, blog posts, etc.) from now on.

**Comment by leo-da** [comment]
I think `payload` for an `ActiveContract` makes sense. We just called it after `com.digitalasset.ledger.api.v1.event.CreatedEvent#createArguments`
