### ISSUE TITLE
DAML-LF: Get rid of Relative ContractId

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#3830]
We want to get rid of the relative contractId in DAML-LF:

The plan for the transition is as follow: 

1. Canton-team provides a scheme to compute the absolute contractId. This scheme should be resistant to collision. (Done)
2. Engine will use the scheme to generate *absolute* contractId. (Done)
3. The ledger implementations will be patched one by one such that they rewrite the relative contractId into absolute contractId using the identity function. (the point 2 helps us to do this migration one ledger implementation at the time). Priority are SQL and Vmware.  (Done)
4. We specified an total order on Value and reimplement GenMap as Order maps. (part of #/2256)
5. We deliver LF 1.9 (that is GenMap) for any ledger as soon it respects point 4. (part of #/2256)

 Once all the ledger implementations have enforced the point 4 we completely get rid of relative contractId in the engine.

**Comment by remyhaemmerle-da** [comment]
cc @gerolf-da @bame-da @oggy-  @andreaslochbihler-da @dajmaki  @meiersi-da

**Comment by meiersi-da** [comment]
Thank you @remyhaemmerle-da for the ping. @andreaslochbihler-da explained the concepts behind the change in further detail. Good direction!
