### ISSUE TITLE
daml-on-x-server: support and document time check configuration

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#385]
- [ ] checks to be supported
   - ledgerEffectiveTime bounds 
   - upper limit on maxRecordTime
- [ ] also document in `participant.state.impl.reference` that we don't expect `TimeProvider` to be used

(FYI: @dajmaki )

**Comment by dajmaki** [comment]
Implemented in https://github.com/digital-asset/daml/blob/master/ledger/participant-state/kvutils/src/main/scala/com/daml/ledger/participant/state/kvutils/KeyValueCommitting.scala#L143.
