### ISSUE TITLE
How to show required templates only in frontent

### ISSUE THREAD

**Issue by yashwanth2804** [digital-asset/daml#3857]
How can edit frontend-config.js file to list only selected templates instead of showing all the declared templates in daml code.Like I dont want to show completed and Rejected templates as they are auto generated.

**Comment by rautenrieth-da** [comment]
Questions about DAML are best posted on stackoverflow.

I have posted an answer to your question at https://stackoverflow.com/questions/59358718/how-can-i-display-a-custom-list-of-templates-in-navigator
