### ISSUE TITLE
participant-state implementation: deduplicate commands on (party, applicationId, commandId) triples

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#387]
- [ ] Explain to implementors correct semantics in docs. Currently the example deduplicates only on `(applicationId, commandId)` tuples
- [x] include test in `ledger-api-test` tool that checks for deduplication

**Comment by meiersi-da** [comment]
I've checked that the KV-utils deduplicate on the triples:
- check is performed here: https://github.com/digital-asset/daml/blob/master/ledger/participant-state/kvutils/src/main/scala/com/daml/ledger/participant/state/kvutils/committing/ProcessTransactionSubmission.scala#L84
- command dedup key is computed here: https://github.com/digital-asset/daml/blob/master/ledger/participant-state/kvutils/src/main/scala/com/daml/ledger/participant/state/kvutils/Conversions.scala#L147

@gerolf-da @stefanobaghino-da I could not validate that we have a test that checks that we deduplicate on the triples as explained in this ticket. Do we have one?

**Comment by stefanobaghino-da** [comment]
Not yet on `master` but there are a few on the branch where I'm porting `TransactionServiceIT` to the new test tool, e.g. [this one](https://github.com/digital-asset/daml/blob/new-test-tool-txs/ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/tests/TransactionService.scala#L64-L80).

**Comment by meiersi-da** [comment]
Nice @stefanobaghino-da . Thanks for the reference. So the other important test to validate the change is that "commands with equal party and command-id, but different application-id, are not deduplicated", as that was the old behaviour.

**Comment by gerolf-da** [comment]
Notice that the deduplication only happens on `(commandId, applicationId)` and does NOT include `party`. If the test were to submit the same tuple of commandId and applicationId for a different party, you would also see get the dedup behavior.

**Comment by gerolf-da** [comment]
See https://github.com/digital-asset/daml/blob/ecb506e8030e1fee570ea4d2aac5f1bbc6bd73fd/ledger/sandbox/src/main/resources/db/migration/postgres/V1__Init.sql#L52-L53

**Comment by meiersi-da** [comment]
Oh OK! What is the rationale for that? Isn't it confusing for users of the ledger that an unrelated party can "steal" deduplication-ids from them?

**Comment by gerolf-da** [comment]
The rationale is historic and we should definitely include `party` in the dedup index.

**Comment by gerolf-da** [comment]
@daravep: dedup-ing on `(party, application_id, command_id)` is good on your end as well?

**Comment by daravep** [comment]
@gerolf-da Given that we want idempotency for application recovery and given that applications send commands on a per `(party, application_id)` basis, I think that this is fine.

**Comment by stefanobaghino-da** [comment]
Given the change in the time model that have been implemented in the last few months, is this still relevant?

**Comment by stefanobaghino-da** [comment]
I'll close this ticket. Feel free to reopen this if necessary, adding the required details.
