### ISSUE TITLE
Remove ReadService/Indexer validation of ledger entries

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#3873]
This is slated to be done in 2020-Q1 after the Sandbox code path is removed from indexer and with the ledger api server schema rewrite.

**Comment by oliverse-da** [comment]
This is very likely resolved now that we run Canton without ledger validation. I will do a sweep over the new db schema to see if any of the db constraints might prevent writes of what Canton might generate, but as of yet am not aware of such a case outside of non-unique canton contract keys, but that is tracked in #5579 )

**Comment by stefanobaghino-da** [comment]
As you mentioned, https://github.com/digital-asset/daml/pull/5781 should have solved this (or at least allow you to solve it).

**Comment by stefanobaghino-da** [comment]
@oliverse-da thanks for having a look, I'm going through our backlog to do a bit of cleanup and triaging.

**Comment by oliverse-da** [comment]
Done with the sweep through database schema. The only unique index I found was for contract keys as mentioned in my previous comment.
