### ISSUE TITLE
Websocket service should use ContractsFetch.acsFollowingAndBoundary as transaction source, not TransactionClient#getTransactions

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#3880]
As @leo-da [mentioned](https://github.com/digital-asset/daml/pull/3796/files#r356832656) in #3796

> we probably don't want to consume all transactions from the very beginning all the time.

We want to address the other interpretation of this (not the one @lima-da originally made), in that the `WebSocketService` _should not_ use the full transaction stream, but instead the concatenation of ACS and transactions-since-ACS-end, which we've implemented as the Akka graph component `ContractsFetch.acsFollowingAndBoundary`.

Making offset a visible concept (or not) is outside the scope of this issue; please direct to #3878.

This is a prerequisite to #3878.

**Comment by leo-da** [comment]
@S11001001 the requirement was to stream both created and archived events. `ContractsFetch.acsFollowingAndBoundary` streams only active contracts (created events).

**Comment by S11001001** [comment]
@leo-da That is not true. `acsFollowingAndBoundary` elides archive events that have been paired with a create (thus mutually annihilating), but streams any others.

See #3878 for a longer semantic discussion of why this is the appropriate behavior for JSON API.
