### ISSUE TITLE
Remove `HasField` instances from doc generation

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#3952]
The doc generation via `daml damlc docs` generates all `HasField` instances. IMHO, this has two problems:
1. It is redundant information because the table already includes all fields and corresponding types.
2. `HasField` should not be used by end-users, so we probably don't want to include it in the docs.

**Comment by associahedron** [comment]
My PR above gives you the ability to pass a `--exclude-instances` option to `daml damlc docs` so you can exclude the `HasField` docs by passing `--exclude-instances=HasField`. (I think that's a better approach than baking in a filter for `HasField` specifically into damldocs.)

**Comment by tweber-da** [comment]
Makes sense. Thx.
