### ISSUE TITLE
Show reason for authorization failure in server logs

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#3955]
For a ledger instance where authorization is enabled, when a particular field of the presented JWT token is invalid or rejected, there is not detail given on which field has been rejected and why, but rather a general "Not authorized for this operation" error is given.

To aid in troubleshooting during development and integration, the fields which have caused the unauthorized message should be displayed in the server logs

Steps to reproduce
1) Generate an RSA private key and cert as per https://docs.daml.com/tools/sandbox.html#generating-tokens

`openssl req -nodes -new -x509  -keyout sandbox.key -out sandbox.crt`

2) Start up a sandbox instance with authentication enabled, passing the generated cert - nhealey@brianhealey7yhtdg ~/g/daml [ECDA512-algo-support]
`daml sandbox --auth-jwt-rs256-crt sandbox.crt --log-level DEBUG`

3) Create a JWT request on jwt.io with a dummy ledgerId and pasting in the contents of the private key
![image](https://user-images.githubusercontent.com/25179017/71862246-31c76e00-30c7-11ea-8603-ee5378076764.png)

4) save the file to `jwt.token` file and run daml ledger list-parties command in a project you have created passing that token
`daml ledger list-parties --access-token-file jwt.token`

**Comment by stefanobaghino-da** [comment]
@rautenrieth-da was this addressed at some point?
