### ISSUE TITLE
Proposal: Drop "record projections" for non-record types

### ISSUE THREAD

**Issue by martin-drhu-da** [digital-asset/daml#396]
In current DAML, when you defined a data type like
```
data Foo
  = Bar with field : Int
  | Baz
  | Quux with field : Int
```
we generate the `HasField` instance which allows you to write `foo.field` for any `foo : Foo`. I think this is a bad idea since this "record projection" is partial. It has recently also caused some trouble in #310.

Thus, I propose that we only generate the `HasField` instances for proper record types. This would be in line with what OCaml and Rust do. (Haskell does something different but Haskell's record system is not great anyway.)

@jberthold-da Can you assess how big the fallout would be for spider? Would it help if we go through an explicit deprecation phase first?

cc @neil-da @shayne-fletcher-da

**Comment by neil-da** [comment]
I'm neutral on this. If others want to go for it, I'm happy enough.

**Comment by sofusmortensen** [comment]
I am usually the partial functions fan-boy. But not here - happy to see it go.

**Comment by jberthold-da** [comment]
Such a restriction would have major impact on our code.
I agree the partiality is undesirable. 
In fact: wouldn't it be great to generate a warning if such a partial function is _used_ (not when it is created)? We should try to implement this and contribute it upstream.
However, a hard restriction of dot-syntax access to the single-constructor case throws out the baby with the bath water IMHO. Status quo is that authors can take care of not creating partial field access functions, or not use them, and enjoy the dot syntax for field accessors.

**Comment by martin-drhu-da** [comment]
@jberthold-da If spider is aiming for warning free, which I hope they are, then warning about all use sites of partial projections will eventually remove all these use sites. Hence this whole thing would be a matter of timing: We could make the warning a deprecation warning and remove the feature once spider is ready for it.

**Comment by jberthold-da** [comment]
> warning about all use sites of partial projections [...] We could make the warning a deprecation warning 

But there is a legitimate case: if all constructors provide the fields that are accessed the function is _not_ partial, so no warning should be emitted. IIUC the proposal is to forbid fields for sums, which is a lot more restrictive.

**Comment by jberthold-da** [comment]
I realise I might need some clarification of the proposal: When you say 
> we only generate the HasField instances for proper record types.
what are " _proper records_ " ?
I was somehow extrapolating from the example and the link to the other issue that only types with a single constructors would be allowed to use fields, that might be wrong. @martin-drhu-da Could you please give an example of what would be supported and unsupported in the proposed version?

**Comment by neil-da** [comment]
@martin-drhu-da - do you want to pursue this or withdraw it?

**Comment by cocreature** [comment]
Don’t see this happening so closing. Feel free to reopen if this changes.
