### ISSUE TITLE
Submitter supplied information in commands is unrestricted UTF-8

### ISSUE THREAD

**Issue by dajmaki** [digital-asset/daml#398]
The ledger-api command contains the fields workflow_id, application_id and command_id and places no restrictions on the contents of these strings. Since with the DAML-on-X approach there are going to be multiple different backend implementations that will require correctly handling these 
(serializing, storing in database), it would be safer to limit the range of these fields to an ASCII subset (for example as defined by SimpleString).

**Comment by meiersi-da** [comment]
Also: we should consider adding length restriction for these fields. Just to be prudent.

**Comment by bitonic** [comment]
@dajmaki @meiersi-da since you are the people most in touch with these alternative backends, could you provide concrete suggestions with what regards to limiting the domain of those ids?

**Comment by remyhaemmerle-da** [comment]
`TransactionId` must be a subset of `ContractId` since `ContractId` may be generated  by concatenating `TrancactionId` with an number. 

The current specification (`daml-lf/spec/value.rst`) restricts `ContractId` to `[A-Za-z0-9\._:\-#]+`

I proposed to use this for  

* TransactionId
* CommandId
* WorkflowId 
* ApplicationId
* ContractId 

We just need a good name for it.

**Comment by dajmaki** [comment]
I would suggest adding `{1,256}`. Enough or we need more?

**Comment by bitonic** [comment]
@dajmaki `{1,256}` seems misguided, there's a lot of random crap / control codes there: https://www.utf8-chartable.de/unicode-utf8-table.pl . something like `{0x20, 0x7e}` would be better.

**Comment by meiersi-da** [comment]
Make it {1,255}. This leaves one byte of the 256 for storing the length.

**Comment by remyhaemmerle-da** [comment]
All those Ids are now represented by `LedgerString`.
`LedgerString` are US-ASCII  `String` with size between 1 and 255 (bounds included) made from digits, letters  `.`, `_`, `:`, `-`, and `#`
