### ISSUE TITLE
Expose com.digitalasset.http.Endpoints partialfunction returns JsValue directly

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#3985]
DABL's API is set up to provide unified JSON request/response as http-json project while providing some extra endpoints and different payloads for its own purposes. To ease the process of DABL reflecting http-json feature update, it is necessary to provide a `PartialFunction[HttpRequest, ET[JsValue]]`

**Comment by leo-da** [comment]
DABL needs to format HTTP Response differently.
DABL upgrades to the latest DAML SDK will be simplified if we provide: `PartialFunction[HttpRequest, ET[JsValue]]` for every exposed endpoint.

**Comment by leo-da** [comment]
@lima-da

1. Will it be sufficient if HTTP JSON API would allow to override/specify a different formatting rules for HTTP Responses? So you could customize `httpResponse(et)` call.

2. Do you plan to use `PartialFunction[HttpRequest, ET[JsValue]]` in your tests directly?

**Comment by lima-da** [comment]
@leo-da 
1. Currently, these partial functions in HTTP JSON are pattern matched by Method and Uri.Path, where in DABL can be different(for example contractLookUp, we are expose as GET with contractId provided in url param), that's another reason why I want them to be directly callable.

2.  For making DABL backwards compatible, DABL does a second parse over the JsValue from your JsValue to another JsValue( the one DABL front-end is depending on) with different shape.
