### ISSUE TITLE
Decimal scaling only occurs on op vs create

### ISSUE THREAD

**Issue by briandbecker** [digital-asset/daml#399]
Disclaimer: I just started working with DAML in the last few days based on its open source release so perhaps I'm missing something.

When working with the IOU sample contract in the getting started guide I am able to do a split of Alice's 100 into an IOU of 100 and 0.00000000005.  The very small 5 value seems like it should fall outside the defined scale of decimal in the documentation (scale 10), however it doesn't; instead the result is what appears to be a valid IOU of 100 and a second of 0.00000000005.

Steps to recreate: 
1. Go through the quick start guide; after running the IOU contract and starting navigator...
2. Enter the navigator application as Alice
3. Select the 100 IOU and do a split operation. 
4. Provide the split amount value as 0.00000000005
5. You should now have two IOUs of 100 and 0.00000000005
6. Do another split the same way; you should result in 3 IOUs of 1 x 100 and 2 x 0.00000000005
<img width="945" alt="image" src="https://user-images.githubusercontent.com/2085521/55962558-23831900-5c3f-11e9-8f31-d74d3b7409c5.png">

7.  Do a merge on the 2 x 0.00000000005 IOU's which should result in a now valid IOU within the documented scale of 0.0000000001
8. This can now be merged back into the 100 IOU which results in a single IOU of 
<img width="945" alt="image" src="https://user-images.githubusercontent.com/2085521/55962638-4a414f80-5c3f-11e9-9ca5-8638a5681790.png">

Solutions:
1. Always do an op on user provided values.  For example updating the IOU (https://github.com/digital-asset/daml/blob/05e691f55852fbb207f0e43cf23bb95b95866ba3/docs/source/getting-started/quickstart/template-root/daml/Iou.daml) contract split code so an opp is forced (less than ideal because it is counter intuitive and would have to be broadly applied)
`splitCid <- create this with amount = splitAmount + 0.0`

2. I'm going way outside my comfort zone on this but Decimal appears to be defined in https://github.com/digital-asset/daml/blob/05e691f55852fbb207f0e43cf23bb95b95866ba3/daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/Decimal.scala where you can see the scale (line 36) is applied during the check op.  The check op should be applied during construction otherwise contracts that don't op user values but then use those values potentially result in BigDecimal values being valid.

**Comment by francesco-da** [comment]
@briandbecker thanks for the high quality bug report. We will take a look at this soon.

**Comment by bitonic** [comment]
@briandbecker thanks again for reporting this. If you're OK with it we will include you in the "Acknowledgements" section of https://digitalasset.com/security/ .

**Comment by briandbecker** [comment]
@bitonic I am ok with it and appreciate the recognition.
