### ISSUE TITLE
Scheduler for DAML Triggers

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#3993]
It would be great to have some kind of scheduler in daml triggers, i.e. have the possibility to specify that the trigger is called back at a certain point in time or in x seconds.

The use case for it is that some actions need to be executed at a certain point in the future, e.g. the settlement of an allocated dvp. Currently, one either has to rely on the fact that there are enough contracts the trigger listens to (and therefore anyway runs frequently) or write some additional client side code.

**Comment by aherrmann-da** [comment]
@tweber-da We could implement a timer that executes the trigger on fixed intervals. We could either add a command-line flag to the trigger runner, or a field to the `Trigger` record. E.g.
```
data Trigger s = Trigger
  { timer :: Option RelTime
  , ...
  }
```
That way the frequency could be specified right next to the code that relies on it.

Would this work for you? Do you have a preference between cli flag or record field?

**Comment by tweber-da** [comment]
This approach basically provides a heartbeat, but has the disadvantage that the trigger is called too often.  If I, e.g., want the settlement to happen close to the actual settlement time, I have to configure a small heartbeat rate, even though we know that nothing happens until the settlement time.

If that's the feasible solution, I'm in favour of a record field.
