### ISSUE TITLE
Make sure licenses are properly generated

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#4]
The NOTICE file needs to contain all third party licenses of dependencies.

- [ ] Haskell libs pull all licenses
- [ ] C static libs pull all licenses
- [ ] C dynamic libs pull all licenses
- [ ] Node pull all licenses
- [ ] Scala SBT libs pull all licenses
- [ ] Java Maven libs pull all licenses
- [ ] Python libs pull all licenses
- [ ] Ruby libs (from dev-env) pull all licenses
- [ ] Bazel Go libs
- [ ] Gradle  libs
- [ ] Check for known high sev vulnerabilities

### Steps to generate from Blackduck
1) Use latest snapshot version of Blackduck `hub-detect-5.3.0.jar` from https://repo.blackducksoftware.com/artifactory/bds-integrations-snapshot/com/blackducksoftware/integration/hub-detect/5.3.0-SNAPSHOT/

2) Run full `bazel build //...` for daml repo

3) Run full Bazel Blackduck scan from root of repo for all projects and components (that Blackduck can recognise)
`java -jar ~/Downloads/hub-detect-5.3.0-20190302.191922-36.jar --blackduck.offline.mode=false --detect.included.detector.types=bazel --detect.bazel.target=//... --logging.level.com.blackducksoftware.integration=DEBUG --blackduck.timeout=60 --detect.project.name=local/daml --detect.code.location.name=local/daml --detect.project.version.name=0.11.10 --detect.project.version.phase=development --blackduck.api.token=$BLACKDUCK_HUBDETECT_TOKEN --blackduck.url=https://digitalasset.blackducksoftware.com --detect.npm.include.dev.dependencies=false --detect.python.python3=true --detect.cleanup=false --detect.cleanup.bdio.files=false`

4) Run `da use <latest preview release>` to pull down all SDK artifacts being released

5) Run Blackduck scan against the --detect.source.path=~/.da/ directory
`java -jar ~/Downloads/hub-detect-5.3.0-20190302.191922-36.jar --blackduck.offline.mode=false --detect.project.tool=DETECTOR --logging.level.com.blackducksoftware.integration=DEBUG --blackduck.timeout=60 --detect.project.name=local/sdk --detect.code.location.name=local/sdk --detect.project.version.name=0.11.10 --detect.project.version.phase=development --blackduck.api.token=$BLACKDUCK_HUBDETECT_TOKEN --blackduck.url=https://digitalasset.blackducksoftware.com --detect.npm.include.dev.dependencies=false --detect.python.python3=true --detect.cleanup=false --detect.cleanup.bdio.files=false --detect.source.path=~/.da/ --detect.detector.search.depth=8 --detect.blackduck.signature.scanner.exclusion.pattern.search.depth=10`

6) Once scan is processed and results are viewable in Blackduck Hub https://digitalasset.blackducksoftware.com, go to relevant project, Reports tab, and generate notices file in txt format
![image](https://user-images.githubusercontent.com/25179017/54122740-43bb8000-43d4-11e9-83e0-170c8b8d326e.png)

7) Concatenate the notices file from the SDK artifact scan and the full DAML repo scan and store output in source as NOTICES file at root of daml repo

### Steps to Generate Haskell/C Dependencies
1) Bazel query to extract list of dependencies - the name of haskell licenses can either be parsed out or extracted from the --output build or --output xml formats
`bazel query 'kind("(haskell_import|haskell_library|cc_import|cc_library)", filter("@.*", deps(//...)))' --output label_kind --keep_going | sort | uniq`

2) For statically imported haskell packages that live on hackage, retrieve relevant license under various names in manner similar to this code
https://github.com/DACH-NY/daml/blob/ee3506bb2bb3c1c8e463bc05733250f5ffd7153c/daml-foundations/daml-tools/docs/daml-licenses/licenses/extract.py#L84-L88

3) For non-Haskell packages and/or dynamic libraries, a mapping of library name to relevant license file will need to be maintained manually a la https://github.com/DACH-NY/daml/blob/ee3506bb2bb3c1c8e463bc05733250f5ffd7153c/daml-foundations/daml-tools/docs/daml-licenses/licenses/extract.py#L171-L183

4) Generate output of static and dynamic Haskell and C libraries in Output in format equivalent to that of auto-generated notices file above, concat to Blackduck output and include in NOTICES file at root

They should be generated, put in the docs, and check they are not GPL. Or we should conclude its not necessary?

**Comment by cocreature** [comment]
We generate it automatically via blackduck now. While there are some issues with blackduck, I think this issue serves no purpose anymore.

**Comment by dasormeter** [comment]
> We generate it automatically via blackduck now. While there are some issues with blackduck, I think this issue serves no purpose anymore.

agreed - if there are issues with data from blackduck we chase that with blackduck, but let's stick with the generation approach we now have automated.

there are also some gaps on statically imported c libs not returned by bazel queries.
