### ISSUE TITLE
Return transaction for commands in command service

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#406]
The [`CommandService#SubmitAndWait`](https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/command_service.proto#L24) method currently only indicates whether the command submission was successful (`google.protobuf.Empty` is returned) or not (a grpc error is thrown). As a user I then have to go through hoops to observe the transaction stream for a transaction with the command ID that was used in the `SubmitAndWait` request.

A much more straight forward user experience is to return the transaction that resulted from executing the commands.

**Comment by nicholassmith-da** [comment]
Work required includes:
- [ ] Changing protobuf definitions
- [ ] Update Sandbox
- [ ] Updating Bindings API
- [ ] DAM-LF Specification
- [ ] Example

**Comment by gerolf-da** [comment]
@nicholassmith-da: Why does this need a changed DAML-LF specification? This should only be a change in the application services.

**Comment by nicholassmith-da** [comment]
@gerolf-da: It was what @francesco-da mentioned (or at least what I understood).

**Comment by gerolf-da** [comment]
I suspect @francesco-da was talking about exposing the "result of an exercise" in the transaction tree, which is a different task than this one.

**Comment by nicholassmith-da** [comment]
Ah, I'll remove it then :-/

**Comment by gerolf-da** [comment]
I created #479 for result-of-exercise-in-transaction. @francesco-da, please add more details to that ticket as needed.
