### ISSUE TITLE
union of queries

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4073]
@hurryabit would like to have multiple queries running over a single websocket `searchForever` stream. Since we already handle multiple template IDs this way (by compiling the query for each template ID and then returning the union), providing more queries up-front would be relatively straightforward.

This union doesn't belong in the query language _itself_, because for a pair of {templateId..., q1 | q2}, q1 _and_ q2 must be well-typed for every templateId, but the idea here is to have multiple pairs {tid1..., q1}, {tid2..., q2}, for which q1 is only checked against tid1..., and likewise for 2.

These pairs will be specified up front ("static multiplex"); we may consider being able to send a message to an ongoing stream to add a new query to its results delivered from now on ("dynamic multiplex") separately from this issue. Static multiplexing fits well within our current framework, whereas dynamic multiplexing would be a significant rework.

In static multiplexing case:

* `search` endpoint _may_ also support the query format, so that `search` and `searchForever` continue to have exactly the same input format
* [x] should "which query passed" be identified, or is the template ID sufficient to disambiguate in practical circumstances? (yes, all queries that passed)

In dynamic multiplexing case:

* [ ] respond starting from the beginning or just from this point on?
* [ ] possible to cancel ongoing queries, leaving the other ones running?

**Comment by hurryabit** [comment]
@S11001001 I suggest we start with static multiplexing only. For the streaming API we definitely need to be able to send queries of the form `[(1, q1), (t2, q2), ...]`. I'm fine with changing the current `/contracts/search` endpoint to the same format for the sake of consistency.

If the results indicate which particular query they match, this would free us from re-implementing the matching logic on the client-side, which removes a source of inconsistency bugs. Thus, I'm in favor of adding such an indicator.
