### ISSUE TITLE
streaming version of fetch by key

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4075]
New websocket endpoint similar to query (reporting creates/archives as they come), but where the predicate is "matches a given contract key".

* [ ] what URL to use?

Possible queries (which one should be supported?)

* [ ] one template, one key
* [ ] one template, multiple keys
* [ ] multiple templates, multiple keys (cross-product, every key must typecheck against every template)
* [x] multiple {template, key} pairs

Regardless of the query choice, we will hold a `TemplateId ==>> (Key ==>> ContractId)` of returned creates as state in the stream to avoid the [phantom archives](https://github.com/digital-asset/daml/commit/3ae0438b73683388de810db0f2bec10f1277b750#diff-acc1415ff18516eee3cce71dc3407d5cR343-R350) returned by `searchForever`, unless the query implies that set will exceed a given threshold size (500 perhaps?).

As discussed with @hurryabit .

**Comment by hurryabit** [comment]
@S11001001 I would try to make the endpoint naming scheme consistent. `/contracts/lookupForever` seems like a good name to get there.

Regarding the query format, we'll need multiple {template, key} pairs.

I would not worry about adding a threshold for the size of the query for now. I don't expect UIs to ask for too many keys.

**Comment by leo-da** [comment]
@hurryabit do you really care about archives in this particular case? You will be getting all archives and creates that matched `(TemplateId, Key)`

**Comment by leo-da** [comment]
unless you want to have exactly the same behavior as in `searchForever`, which means that it would conflate the created and archived if there is hiccup, so may never see contract with a requested `(TemplateId, Key)`.

**Comment by leo-da** [comment]
Haven't heard anything back from @hurryabit , assuming we need archives. `lookupForever` output would match the `searchForever`.

**Comment by hurryabit** [comment]
@leo-da Yes, we need to deliver archive events as well. A key might be "deleted" during a session. Matching the output format of `searchForever` would be great. Consolidation is fine.
How hard would it be to _not_ deliver archive events of contracts that don't match the contract keys we're looking for?

**Comment by leo-da** [comment]
> How hard would it be to not deliver archive events of contracts that don't match the contract keys we're looking for

@hurryabit don't know yet, need to think.

We can filter archived events by contractId. We have the ACS in DB with running with the query store enabled, else we always pre-fetch the ACS with `GetActiveContractsResponse`.

We would have to keep the ACS in memory for the duration of the stream. There will be some performance and memory footprint implications. 

Let me know if this is something we actually want to implement. We would have to implement both `searchForever` and `lookupForever` the same way. I am actually re-using most of the `searchForever` functionality for `lookupForever`.

**Comment by leo-da** [comment]
the implementation should be easy I think, it is just adding a filter to the Akka Stream, keeping the state in memory for the duration of the stream might be an issue.

**Comment by gerolf-da** [comment]
Maybe you can use akka streams' `statefulMapConcat` to build up the state of contract IDs that previously matched the contract key criteria.

**Comment by leo-da** [comment]
@gerolf-da yes we can, but it all comes with a price. We will be getting OOE on a long running stream with a large ACS. Technically we can have multiple concurrent long running streams, each stream will maintain its own state of active contracts.

**Comment by leo-da** [comment]
If we keep the state, we should introduce the threshold, that @S11001001 is talking about. Let's say we allow 500 `(TemplateId, Key)` pairs per request.

However, as @hurryabit may say I am trying to optimize for the problem that we currently don't have :)

**Comment by S11001001** [comment]
From @leo-da 

> fetchForever aka lookupForever should also report unknown templates as warnings.
