### ISSUE TITLE
Provide runner with Sandbox CLI using KV SQL Ledger

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#4084]
Given the availability of [KV SQL Ledger](https://github.com/digital-asset/daml/milestone/33), we want to provide a runner (i.e. main class) with the following properties:

- It uses the Sandbox CLI
- It uses the in-memory SQL backend if the `--sql-backend-jdbcurl` option is not specified
- It uses the existing H2 backend for the Participant Server and a KV SQL Ledger with H2 or SQLite.

**Comment by SamirTalwar-DA** [comment]
This was done in #4422.
