### ISSUE TITLE
participant-state: provide lower level bytestring based interface

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#410]
Many integrations (DAML on Sawtooth, DAML on Concord) need to serialize and deserialize the transactions over the network. The current strongly typed Scala interface for `participant.state.Read/WriteService` make this unnecessarily difficult; and will impair our ability to push out future upgrades.

We should build additional `parcipant.state.binary.Read/WriteService` interfaces that keep all data as opaque bytestrings. We should additionally provide a `participant.state.binary.transaction` package that provides a Java-compatible interface for validating serialized transactions and keeping an active-contract-set and deduplication-set up to date.

FYI: @dajmaki

**Comment by dajmaki** [comment]
Implemented in PR #637.
