### ISSUE TITLE
any ledgerId in JWT works for json api connecting to single ledger sandbox for search

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#4103]
`/contracts/search` GET / POST shouldn't work when specified ledger_id is different from the sandbox's ledger_id

however, `command/create` works as expected, erroring out ledger_id mismatch. Please investigate.

**Comment by lima-da** [comment]
This seems to be resolved after 0.13.43, can you confirm @leo-da @S11001001 ?

**Comment by S11001001** [comment]
Fixed vacuously by #3781.
