### ISSUE TITLE
Push the DAML extension to the VS Code Marketplace

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#414]
We had a discussion on Slack. Conclusions:

* Is it useful even when it doesn't install the compiler? We think so.
* Should we do it after the new da-assistant? Might be more comfortable, but can't see a technical reason, and want to decouple it.
* We should change the name. DAML seems like a good name.

**Comment by cocreature** [comment]
Repeating a comment that I mad one Slack:
We should add a check for version mismatches between damlc and the extension before we publish it.

**Comment by associahedron** [comment]
The new assistant is out (though not in general users' hands yet). Where are on publishing the extension?

**Comment by cocreature** [comment]
Not sure @sormeter started looking into it but I’m not sure where we are.

**Comment by garyverhaegen-da** [comment]
`0.13.10` is the first version automatically pushed to the marketplace at: https://marketplace.visualstudio.com/items?itemName=DigitalAssetHoldingsLLC.daml

I have verified I am able to install the extension through the marketplace. I think that means we can consider this closed; please reopen if you disagree.

**Comment by ndmitchell** [comment]
I'm not sure we're done just yet. Do we have the compat check mentioned initially? Do we want to change how we are wiring things up to take advantage of the extension? How do we install a local version such that VS Code will auto upgrade it?

**Comment by associahedron** [comment]
I think this is done
