### ISSUE TITLE
DAML executable does not stop child processes on Windows

### ISSUE THREAD

**Issue by tamaskalcza-da** [digital-asset/daml#4168]
If the DAML Sandbox is started using Java Process API (like in the functional test library) then when the DAML process is terminated it does _not_ terminate the spawned Java process.

### Example pseudo code:
```java
Process process = new ProcessBuilder("daml.cmd", "sandbox", darPath).start();
Thread.sleep(10_000); // Wait for the Sandbox process to start
process.destroy();
process.waitFor();
```

### Expected behaviour
The `daml.exe` should not be running. The spawned Java process should not be running.

### Actual behaviour
The `daml.exe` stops running. However, the spawned Java process remain alive.

**Comment by cocreature** [comment]
Some useful hints from @associahedron https://downloads.haskell.org/~ghc/latest/docs/html/libraries/base-4.13.0.0/src/GHC-ConsoleHandler.html

**Comment by cocreature** [comment]
After looking into this for a bit, it turns out that Java’s `Process::destroy` method calls Windows’ `TerminateProcess` which does not provide any way to install a signal handler, i.e., it’s the equivalent of a `SIGKILL`.

So there is no way to make this work with `Process::destroy`. The only reasonable option that I see is to provide some way to trigger a clean shutdown. E.g., we cut shut down if `stdin` is closed.

**Comment by tamaskalcza-da** [comment]
Not really a workaround, but still a useful command. Given from a `bash` shell this can be used to kill the dangling Sandbox processes.
```shell
pids=$(jps | grep daml-sdk.jar | awk -F" " '{print $1}') && for i in ${pids[*]}; do taskkill -f -pid $i; done
```

**Comment by cocreature** [comment]
Test program for how this works from Java now:
```
import java.io.IOException;
import java.lang.ProcessBuilder.Redirect;

public class Test  {
  public static void main(String[] args) {
      ProcessBuilder builder = new ProcessBuilder(args).redirectOutput(Redirect.INHERIT);
      try {
          Process process = builder.start();
          Thread.sleep(5_000);
          process.getOutputStream().close();
          process.waitFor();
      } catch (IOException e) {
          e.printStackTrace();
      } catch (InterruptedException e) {
          e.printStackTrace();
      }
  }
}
```
