### ISSUE TITLE
codegen-sbt-example should not reference damlc.jar

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#4184]
damlc.jar was never published to Maven only to Bintray and now we stopped publishing it completely.

However, the `codegen-sbt-example` (which is apparently completely untested) still references `damlc.jar` in https://github.com/digital-asset/daml/blob/master/language-support/scala/examples/codegen-sbt-example/build.sbt. This should be changed to invoke `damlc` via the assistant.

**Comment by leo-da** [comment]
@cocreature I assume Spider is fine with this. At some point they were using damlc.jar in their build and the whole example is built around their experience with scala codegen.

**Comment by cocreature** [comment]
@leo-da Yes our internal project has moved away from `damlc.jar`. @gerolf-da suggested that we might be able to just remove the whole example.

**Comment by leo-da** [comment]
@cocreature In this case this example does not make much sense it should be removed. Is it a blocker?

**Comment by cocreature** [comment]
Not a blocker but I’d rather remove it sooner than later.
