### ISSUE TITLE
Provide ability to query ledger to find supported DAML LF and running ledger versions

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#4187]
When you start a ledger, there is an informational message logged which shows the DAML-LF versions that are supported.

It would be useful if at the API level (and via DAML assistant and other tooling that queries the API) we are able to discover what DAML-LF versions are supported by a running ledger, and if you try to upload a DAR compiled to an unsupported DAML-LF version, there should be a meaningful error message returned describing why it cannot be uploaded.

**Comment by gerolf-da** [comment]
This issue will be solved as part of the DAML Platform release definition, potentially by introducing such an endpoint. Closing this for now.

**Comment by dasormeter** [comment]
@gerolf-da err can we make sure there is another ticket or issue to track the item before closing it?

**Comment by gerolf-da** [comment]
This will be tracked by KVL-413.
