### ISSUE TITLE
Make webSocketService publically accessible

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#4190]
1. make `wsConfig` public,
DABL needs the capability to fine-tune the websocket config when using json-api's websocketService
2. make `handleWebsocketRequest` public, otherwise no way to call the service.

**Comment by hurryabit** [comment]
@lima-da @da-tanabe How urgent/important is this?

**Comment by lima-da** [comment]
@hurryabit this currently blocks DABL align WebSocket with json-api ^
cc. @da-tanabe

**Comment by hurryabit** [comment]
@leo-da @S11001001 How big of a change is this? Something like changing a few `private` into `public` or way bigger?

**Comment by leo-da** [comment]
@hurryabit changing the visibility + commitment to support backward compatibility in the WebSocketService binary API. Right now we commit to support only JSON API. I assume @lima-da wants to use it as a library.

**Comment by lima-da** [comment]
@leo-da @hurryabit , for starter, I just need this line: https://github.com/digital-asset/daml/blob/00224c248094d32b65b1ec54e87e1d855e9359cb/ledger-service/http-json/src/main/scala/com/digitalasset/http/WebsocketEndpoints.scala#L98

to be public, is it possible?

**Comment by leo-da** [comment]
@lima-da I am finishing #4075, after this the binary interface should be more or less stable, I will make it public as part of the above change.

**Comment by lima-da** [comment]
@leo-da Thank you!

**Comment by S11001001** [comment]
> commitment to support backward compatibility in the WebSocketService binary API

@leo-da We don't have to do this as part of the change; making it sufficiently public (perhaps `private[digitalasset]`) is enough.

**Comment by leo-da** [comment]
@lima-da making `private[http] final case class WebsocketConfig(`  public is not a problem, however I am pretty sure that eventually someone will change it back to `private[http]` if it does not break compilation :) All JSON API related configs are package private, I can document why we are making an exception but it would not prevent any future breakage.

Can you put the logic that deals with websocket configuration in `com.digitalasset.http` and call it from  your `com.projectdabl` package?

**Comment by lima-da** [comment]
@leo-da in that case, package private is fine, we can come back to this one json-api is feature stable and address in library-alike support
