### ISSUE TITLE
Ledger time: remove LET and MRT

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#4194]
The implementation of the new ledger time model(https://github.com/digital-asset/daml/issues/4345) has made the LET and MRT fields obsolete.

Go through our main repository and remove the usage of LET and MRT where possible.

This includes, among others:
- [x] The participant state API and kvutils
- [x] All internal ledger API clients (extractor, navigator, triggers, script, ...)
- [x] All tests
- [x] [quickstart-java](https://github.com/digital-asset/daml/tree/master/docs/source/getting-started/quickstart/template-root) (@gerolf-da)
- [x] [quickstart-scala](https://github.com/digital-asset/daml/tree/master/language-support/scala/examples/quickstart-scala)

**Comment by gerolf-da** [comment]
@rautenrieth-da: can we close this?
