### ISSUE TITLE
Provide a way for a contract to be archived at the end of a consuming choice

### ISSUE THREAD

**Issue by andrae-da** [digital-asset/daml#420]
Current semantics for consuming choices archive the contract at the beginning of the choice, before the body of the choice evaluates. This is inconsistent with the intuition of a DAML contract representing an meeting-of-minds regarding some fact, which should only cease to be true at the successful completion of an agreed transition away from that state (ie. the completion of a consuming choice).

Practically this also causes trouble as we lose local reasoning within contracts if they cannot independently `fetch` their antecedents without concern to the non-local flow of control that led to their being called. This is particularly problematic when modelling workflows. "State" contracts often wish to restrict the use of certain choices to approved workflows to whom they delegate the maintenance of non-local business constraints. The only way to achieve this, without requiring global-analysis of all current and possible future code-paths within a DAML system, is to `fetch` an appropriately authorized "workflow" contract evincing an acceptable stage of an approved workflow is in progress.

The obvious and naive approach we should endeavour to support to model this is to allow the Workflow contract to pass `self` from its own consuming choice as an argument to the State contract. A slightly less naive approach involves intermediation via an ephemeral contract, but that only moves the locus of the issue. Currently `self` is archived before this can be done. This prevents the State contract from verifying its antecedents and makes the resulting code more complex.

The current standard approach taken is to switch from DAML-guaranteed consumption management to manual-lifecycle management by replacing the `consuming` choice with a `non-consuming` choice that tries to ensure that all possible execution paths result in an explicit call to `exercise self Archive` precisely once. This introduces the very real risk of contract leaks—an undesirable state of affairs.

**Comment by neil-da** [comment]
My best guess at the way to implement this is introduce `preconsuming`, `postconsuming` and `nonconsuming` as the three explicit ways to annotating consumption, with the default being `preconsuming`.

Mapping to LF, nonconsuming = nonconsuming, preconsuming = consuming and postconsuming = run the update and then call the archive in DAML land (which is just a preconsuming choice). This would have no new LF features, so is purely syntactic.

As a technical matter, I guess we'd extend `ChoiceType` with the three types above, add pre/post consuming as functions, desugar much like we do now in the GHC side with one extra alternative, and have the compiler detect one more special case and synthesise an archive call if it does. Not much work, I think.

CC @martin-drhu-da @francesco-da @shayne-fletcher-da

**Comment by martin-drhu-da** [comment]
@neil-da Are you saying `postconsuming = nonconsuming + archive self at the very end`?

**Comment by neil-da** [comment]
@martin-drhu-da yes

**Comment by shayne-fletcher-da** [comment]
This feature is "out the door". Details on the new syntax and behaviors in [this blog post](https://digitalasset.atlassian.net/wiki/spaces/DEL/blog/2019/04/18/850592229/DAML+choice+annotations+%3A+Introducing+pre-+and+post-consuming+choices?atlOrigin=eyJpIjoiYzE0NGZjZDE5MzRmNDI2ZWFkNDRiNzFkODUwMWU2ODkiLCJwIjoiYyJ9).
