### ISSUE TITLE
KV SQL Ledger health checks

### ISSUE THREAD

**Issue by SamirTalwar** [digital-asset/daml#4224]
The KV SQL Ledger always reports itself as "healthy". If there are connectivity issues with the underlying database, it should endeavor to report these by returning `Unhealthy` from `currentHealth()`.

The Sandbox provides an example of this; it polls the database with a trivial `SELECT 1` query and reports that the API server is unhealthy if there are 3 or more failed queries in a row.

**Comment by gerolf-da** [comment]
As KV SQL Ledger is only being run in sandbox-next in in-memory mode, this is not relevant anymore. Therefore closing this issue.
