### ISSUE TITLE
Remove _ledger/api-server-damlonx/reference-v2_.

### ISSUE THREAD

**Issue by SamirTalwar** [digital-asset/daml#4225]
We can now remove _reference-v2_ in favor of _ledger/ledger-on-memory_, which is a similar implementation using the simplified kvutils API.

There are at least two things that we need to preserve when removing it:

1. The `reference-ledger-dump-integrity-test`, which AFAIK ensures that a kvutils-style ledger is reproducible.
2. `IndexerIT`, which tests the `RecoveringIndexer` in combination with with the reference ledger.

**Comment by meiersi-da** [comment]
@SamirTalwar: would it be possible to even only use the daml-on-sql (kv) ledger and forego building the in-memory version.

**Comment by dasormeter** [comment]
@SamirTalwar will there be equivalent bazel targets to the existing reference v2 conformance test targets in the new ledger/ledger-on-... world or will these be updated to have the new ledger implementation run under the hood??

❯ bazel query //ledger/sandbox:                                                                                                                              
```
conformance-test-config-management-h2database
conformance-test-config-management-memory
conformance-test-config-management-postgres
conformance-test-lots-of-parties-h2database
conformance-test-lots-of-parties-memory
conformance-test-lots-of-parties-postgres
conformance-test-static-time-h2database
conformance-test-static-time-memory
conformance-test-static-time-postgres
conformance-test-wall-clock-h2database
conformance-test-wall-clock-memory
conformance-test-wall-clock-postgres
```

**Comment by SamirTalwar** [comment]
@meiersi-da: It's really useful to have at least two different implementations of KV ledgers in this repository; helps a lot with refactoring and understanding where the commonalities are.

The SQL ledger is also going to grow in complexity, whereas the in-memory version should stay the same, so I think it's better as a true "reference" implementation than the SQL one.

**Comment by SamirTalwar** [comment]
@dasormeter: Yeah, absolutely. We already run these targets:

```
//ledger/ledger-on-sql:conformance-test-sqlite-memory
//ledger/ledger-on-sql:conformance-test-sqlite-file
//ledger/ledger-on-sql:conformance-test-postgresql
//ledger/ledger-on-sql:conformance-test-h2-memory
//ledger/ledger-on-sql:conformance-test-h2-file			
```

These include `LotsOfPartiesIT`. Gotta try the config management ones soon.

**Comment by meiersi-da** [comment]
Thanks for the clarification @SamirTalwar . I rely on your judgment wrt the trade-off of the overhead of having two implementations instead of one VS having more variants of integrations to check refactoring against.

**Comment by SamirTalwar** [comment]
FYI, enabled the config management tests in #4250 and they work fine.
