### ISSUE TITLE
KV SQL Ledger: provide a "migrate and shut down" mode so that migrations can run with special privileges.

### ISSUE THREAD

**Issue by SamirTalwar** [digital-asset/daml#4235]
Often, migrations will need to run with extended database privileges (i.e. `CREATE TABLE`, `ALTER TABLE`, etc.), whereas running just needs reads and writes. In a locked-down environment, we'll need to provide a way of just running migrations and then stopping so that the operator can choose the correct user account (and appropriate privileges) for the task.

We currently have three startup modes for the indexer:
  - validate and start
  - migrate and start
  - migrate only

We probably need the same for this ledger.

We may also want to add "validate only" as an option.

**Comment by gerolf-da** [comment]
Closing as this is not relevant for Sandbox-next anymore.
