### ISSUE TITLE
GeneralizedNewtypeDeriving fails with "Coercion with typeconappco"

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#4237]
See https://github.com/digital-asset/daml/pull/4233#discussion_r371691124

```
newtype ACSBuilder = ACSBuilder [Update (AnyContractId, AnyTemplate)]
   deriving (Semigroup, Monoid)
```

falls over with

```
Severity: DsError
Message:
  Failure to process DAML program, this feature is not currently supported.
  Coercion with tyconappco.
  ([Sym (N:ACSBuilder[0])])_R
```

Haven’t looked into what exactly is going wrong but I don’t see why that shouldn’t be supported and if we really cannot support it we should have a better error message.

**Comment by cocreature** [comment]
Minimal example:
```
daml 1.2
module Test () where

class MyClass a where
  f : Optional a -> a
  f = error "unimplemented"

data X = X

instance MyClass X where

newtype Y = Y X
  deriving MyClass
```

This produces a coercion of the form `TyConAppCo … Optional […]`. This seems a bit annoying to fix not so much for `Optional` but for user-defined types. We basically have to recurse on the type and keep some mapping of type parameter to coercion (which we get from a recursive call in `go`) and then whenever we see a type parameter we apply the corresponding coercion funcitons. Not hard to do but tedious.

Surprised we did not hit this before.

**Comment by associahedron** [comment]
#4428 implements the test case above, and adds a case for lists.

Closing for now, after discussing with @cocreature. We realized that safely supporting user-defined record and variant type coercions is a significant increase in complexity for very diminishing returns, considering one must handle mutually recursive type definitions in some way.

For posterity, and in case we revisit the decision, I leave here the implementation of simple record type coercions that cannot handle recursive (or much less mutually recursive) definitions without getting into an infinite loop:

```Haskell
        | Just (tycon, cos) <- splitTyConAppCo_maybe co = do
            -- | Use this to build a coercion for each field or variant payload.
            let coercionFor :: TyCoRep.Type -> Coercion
                coercionFor ty = liftCoSubstWith Representational (tyConTyVars tycon) cos ty
            s' <- lift $ convertType env s
            t' <- lift $ convertType env t
            case (s', t', cos) of
                ...
                (TConApp qtcon sargs, TConApp _ targs, _)
                    | length cos == length (tyConTyVars tycon)
                    , isSimpleRecordTyCon tycon
                    , Just con <- tyConSingleDataCon_maybe tycon
                    , labels <- ctorLabels con
                    , (_, theta, args, _) <- dataConSig con
                    -> do
                        fgs <- mapM (go env . coercionFor) (theta ++ args)
                        let scon = TypeConApp qtcon sargs
                            tcon = TypeConApp qtcon targs
                            f' = mkRecordMap scon tcon labels (map fst fgs)
                            g' = mkRecordMap tcon scon labels (map snd fgs)
                        pure (f', g')
                _ -> do
                    lift $ unhandled "tycon app coercion" co
        | otherwise = lift $ unhandled "coercion" co

    mkRecordMap :: LF.TypeConApp -> LF.TypeConApp -> [LF.FieldName] -> [LF.Expr -> LF.Expr] -> LF.Expr -> LF.Expr
    mkRecordMap tcon1 tcon2 labels fs x =
        ERecCon tcon2
            [ (label, f (ERecProj tcon1 label x))
            | (label, f) <- zip labels fs
            ]
```
