### ISSUE TITLE
DAML docs generation includes hidden modules

### ISSUE THREAD

**Issue by aherrmann-da** [digital-asset/daml#4268]
DAML API documentation generated via `damlc docs` includes non-exposed modules. See the docs for `Daml.Trigger.Internal` in https://github.com/digital-asset/daml/pull/4264 for example. On that PR run `bazel build //triggers/daml:daml-trigger-rst-docs` and look at the generated `bazel-bin/triggers/daml/daml-trigger.rst`.

**Comment by sofiafaro-da** [comment]
@aherrmann-da To hide `Daml.Trigger.Internal` from the generated docs, it should be enough to add a `-- | HIDE` annotation before `module Daml.Trigger.Internal`. Would this be good enough for now?

(Another approach, widely used in daml-prim and daml-stdlib, is to use `-- | MOVE M` to move the docs to another module `M`, and then use `-- | HIDE` on any individual declarations that you want hidden.)

I agree in theory it shouldn't be required, and that hiding unexposed modules is a sensible default, but this is how we control docs visibility for the standard library at the moment.

**Comment by aherrmann-da** [comment]
@sofiafaro-da Thank you for the pointer! Yes, that seems sufficient. I've applied it in https://github.com/digital-asset/daml/pull/7992.
