### ISSUE TITLE
Rename JSON API endpoints

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#4289]
- `/command/create` => `/create`
- `/command/exercise` => `/exercise`
- `/contracts/lookup` => `/fetch`
- `/contracts/search` => `/query`
- `/contracts/searchForever` => `/stream/query`
- `/contracts/lookupForever` => `/stream/fetch`
- `/parties` -- no changes

Related to: #3145

CC @hurryabit

**Comment by hurryabit** [comment]
@leo-da Can you please rename `/search` to `/query` and `/searchForever` to `/queryForever`.

**Comment by leo-da** [comment]
@hurryabit how about 
`/queryForever` => `/queryStream` or `/query/stream`
`/fetchForever` => `/fetchStream` or `/fetch/stream`

Having forever in the URL does not feel right :)

**Comment by hurryabit** [comment]
> @hurryabit how about
> `/queryForever` => `/queryStream` or `/stream/query`
> `/fetchForever` => `/fetchStream` or `/stream/fetch`
> 
> Having forever in the URL does not feel right :)

I like the idea. How about
```
/stream/query
/stream/fetch
```
Then we don't have "overlapping" URLs.
