### ISSUE TITLE
Warn on unknown templates in streaming search

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4290]
As #4014 fixed #3771 for the POST search endpoint, do something similar for the searchForever endpoint.

This would take the form of an optional _object_ preceding the arrays in the normal stream, containing _only_ the `warnings` [from this example](https://github.com/digital-asset/daml/issues/3771#issuecomment-572619019).

**Comment by leo-da** [comment]
`fetchForever` aka `lookupForever` should also report unknown templates as `warnings`.

non-streaming version of `fetch` (`lookup`) should report unknown template (only one template can be passed) as an error.

**Comment by S11001001** [comment]
> `fetchForever` aka `lookupForever` should also report unknown templates as `warnings`.

Part of #4075 rather than this issue.
