### ISSUE TITLE
Make AddFriend choice non-consuming with explicit archive

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4300]
This way we can avoid teaching about both `consuming` and `nonconsuming` choices. We also avoid privacy issues with consuming choices.

**Comment by rohanjr** [comment]
I'm actually not sure about this one. I like the brevity of the `consuming` version. As the first choice the DAML user sees, it is nice if it comes across as concise as possible - they don't have to know details of the semantics. This does mean we introduce `nonconsuming` with the messaging feature, but I think it's more natural there as we don't do an archive. It could be confusing if you see a `nonconsuming` choice which archives the contract (explicitly).

**Comment by hurryabit** [comment]
@bame-da, @gerolf-da  and I are currently discussing fixing this whole consuming choice mess in Q1 2020. If we do, then `nonconsuming` + explicit archive will be the way to go. Let's wait with this ticket until we've arrived at a decision.

**Comment by hurryabit** [comment]
We've decided to follow the original approach to steer users away from consuming choices and teach them nonconsuming choices with explicit calls to `archive`.
