### ISSUE TITLE
Add timestamp to messages

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4314]

**Comment by rohanjr** [comment]
Currently mentioned in the guide as an exercise in the final "Next Steps" section. If we want to include this in the messaging feature then we should remember to explain it and remove the exercise.

**Comment by rohanjr** [comment]
I think the guide is fine and simpler without this. I propose keeping it mentioned as an exercise. Thoughts @hurryabit ?

**Comment by hurryabit** [comment]
Mentioning it as an exercise sounds good. @nemanja-da do you agree?

**Comment by cocreature** [comment]
Not planned for now.
