### ISSUE TITLE
Allow ledger-api-test-tool to be run against authenticated ledgers

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#4316]
Allow for the ledger-api-test-tool to be run against authenticated ledger by including `-access-token-file` support as is present with daml assistant (`daml ledger upload-dar --access-token-...`, etc) and with navigator (`daml navigator server...` and `daml ledger navigator...`)

At present when the ledger-api-test-tool is run against an authenticated ledger, all tests fail with an unauthorized answer.

**Comment by gerolf-da** [comment]
This is now tracked by KVL-436.
