### ISSUE TITLE
Sandbox is confused about whether not providing a ledger ID is OK.

### ISSUE THREAD

**Issue by SamirTalwar** [digital-asset/daml#4324]
Currently, our `SqlLedger` (and `ReadOnlySqlLedger`) take an _optional_ ledger ID. They follow this logic:

- there is no existing ledger ID _and_ no ledger ID is provided: **generate a new ID (typically a UUID)**
- there is no existing ledger ID _and_ a ledger ID is provided: **use the provided ID**
- there is an existing ledger ID _and_ no ledger ID is provided: **use the existing ID**
- there is an existing ledger ID _and_ a ledger ID is provided: **compare them and crash if they're different**

This seems pretty logical. However, we never pass `None` to their constructors except in tests.

Instead, if no ledger ID is provided, we generate one further up in the chain (by `SandboxServer`, or by whatever ledger implementation you're using, which will pass it to `JdbcIndex`).

This means we never trigger the case where there's an existing ID and no ID is provided: we always generate an ID, so this will fail because they will be different.

If I start Sandbox twice with no ledger ID against the same backend store (in this case an H2 database file), it fails:

```
Ledger id mismatch. Ledger id given ('sandbox-4492c9df-e886-43af-8cdd-fffde7532c74') is not equal to the existing one ('sandbox-e4a6a25c-7544-45af-bc8e-3392695235e9')! (context: {participantId=sandbox-participant})
```

I'm not sure which behavior is correct. Forcing the user to specify the ledger ID might mitigate certain classes of failure where they accidentally run against the wrong backend; on the other hand, it's far more inconvenient.

Either way, we need to delete some code; either we should propagate the `None` through to `SqlLedger` or we should make it non-optional.

Thoughts?

**Comment by gerolf-da** [comment]
You are right. If no ledger ID is provided by the user explicitly, but there is one already in the existing ledger, the server should be able to just continue from where it left off.

So yeah, we should propagate the None all the way through.

**Comment by SamirTalwar** [comment]
Just realized it's not that easy; for Sandbox, this'll work, but for KV ledgers, it'll mean they'll need to change. If we change this, they will need to store their ledger ID themselves so that they can return it as part of `ReadService#getLedgerInitialConditions`.

Of course, in the short term they can carry on generating an ID which will then be rejected.
