### ISSUE TITLE
Adapt our TS artifacts to use the newly published @daml/types and @daml/ledger

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/daml#4334]
Now that `@daml/types` and `@daml/ledger` are published to NPM, where sensible we should adapt our codebase to use them.

Off the top-of-my-head, things to look at:
-  [ ] `create-daml-app` https://github.com/digital-asset/daml/issues/4294
- [ ] The "Getting Started Guide" https://github.com/digital-asset/daml/issues/4294
- [ ] `daml2ts` https://github.com/digital-asset/daml/issues/4335
- [ ] `DAVL` https://github.com/digital-asset/davl/issues/146

**Comment by rohanjr** [comment]
For create-daml-app and the GSG the issue is captured in https://github.com/digital-asset/daml/issues/4294. I suggest individual issues for the other two pieces

**Comment by shayne-fletcher** [comment]
Good idea. Here's the one for DAVL : https://github.com/digital-asset/davl/issues/146

**Comment by shayne-fletcher** [comment]
Done
