### ISSUE TITLE
Streaming JSON API: Guarantee order of events wrt contract keys

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4354]
Currently, the streaming endpoints of the JSON API don't provide any guarantees regarding the order of events. It would simplify applications if we had a guarantee that whenever a block of events contains a create and an archive event affecting the same contract key, they are shipped in order. Since we don't send create and archive events for the same contract in one block, the only way this can arise is when we first archive a contract and then create a new contract with the same contract key. I suggest we guarantee that the archive is always sent before the create.

If we don't provide this guarantee, we need to adjust the `TemplateStore.addEvents` method in `@daml/react` accordingly.

Related to: #4075

**Comment by leo-da** [comment]
@hurryabit this should be a reasonably easy change. We can remove the conflation, and emit all events. However there is "price" :) you will be getting more short-lived creates, followed by archives and new creates.

We added conflation to allow `a faster upstream to progress independently of a slower subscriber by conflating elements into a summary until the subscriber is ready to accept them`. If we remove the conflation we would have to rely on Akka stream back-pressure.

**Comment by leo-da** [comment]
I assume you want to guarantee the order of events for both streaming endpoints?

**Comment by hurryabit** [comment]
@leo-da Yes, I want this for both all stream endpoints. The non-stream version of `query` does not deliver any archive events, hence there's no issue there.

I'd like to keep the conflation too. If don't change the order of events during conflation, we should be on the safe side. Would that work?

**Comment by leo-da** [comment]
@hurryabit 
> The non-stream version of query does not deliver any archive events, hence there's no issue there.

that is true, however we don't guaranteed the order of creates we read from the query-store. The order of creates without query-store guaranteed only withing one template ID.

**Comment by leo-da** [comment]
> I'd like to keep the conflation too. If don't change the order of events during conflation, we should be on the safe side. Would that work?

That would work, but would require a bit more changes.

**Comment by hurryabit** [comment]
> that is true, however we don't guaranteed the order of creates we read from the query-store. The order of creates without query-store is guaranteed only within one template ID.

The order of creates of active contracts doesn't matter wrt contract keys since there's at most one active contract for each contract key. Thus, I don't need any guarantees here.

**Comment by leo-da** [comment]
understood, it is the same logic that is used for streamed and non-streamed query and fetch. Wanted to make sure you don't have a use case when order of creates is important. If you do, we better address it as part of this request

**Comment by leo-da** [comment]
@S11001001 we should change
```
final case class InsertDeleteStep[+C](inserts: Vector[C], deletes: Set[String])
```
to something like:
```
final case class InsertDeleteStep[+C, +D](events: Vector[C \/ D])
```

**Comment by S11001001** [comment]
@leo-da We don't need to go that far. All we need to do to satisfy this invariant is render the deletes before the inserts.

**Comment by leo-da** [comment]
@S11001001 actually you are correct, :), we cancel (conflate) creates and archives within on step and @hurryabit wants us to keep this logic.

So for any transfer that fits in into one step, we only emit final create and if original contract create was emitted in a separate step, the consecutive step would emit archive before the create. :+1:
