### ISSUE TITLE
Docker Image with DAML SDK and code-server

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#4355]
I'd like to write some tutorials on https://www.katacoda.com/
Having gained some experience with it, I think the easiest way to do it would be to have a Docker image hosted somewhere that has the following properties:

- Has Java, and latest DAML SDK, code-server installed / available
- The image should be usable in interactive mode
- code-server should be easy to start with the DAML extension against a given port and in a given directory

**Comment by cocreature** [comment]
So it sounds like the only thing missing from our current docker images is `code-server`?

**Comment by cocreature** [comment]
Given that we have katacoda now I think we can close this. Feel free to reopen if needed.
