### ISSUE TITLE
Issues with running DAML Studio with DAML 0.13.50 on WSL2

### ISSUE THREAD

**Issue by dazraf** [digital-asset/daml#4357]
This is my configuration:

1. DAML installed on Windows Sublayer for Linux 2 (wsl2). 
2. Quickstart project created. 
3. CLI build successful.
4. Sandbox and navigator startup fine from CLI. 
5. VS Code started from WSL2. 
6. Installed DAML extension v0.13.50. 
7. Installed graphviz extension as recommended by extension README.

Test:
1. Open daml.yaml. Ran "Visualize Daml project". Get small VS toast saying "Open the daml file to visualize"
2. Try again. Same error. 
3. Try "Open Daml virtual resource". VS provides a toast with "A request has failed. See the output for more information.". The DAML Language Server has the log entry: 
```
[Error - 4:04:11 PM] haskell-lsp:parse error. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("textDocument",Object (fromList [("languageId",String ""),("text",String ""),("version",Number 0.0)]))])),("method",String "textDocument/didOpen")]) "When parsing the record TextDocumentItem of type Language.Haskell.LSP.Types.TextDocument.TextDocumentItem the key uri was not present." `stack update` and install new haskell-lsp. Or check information on https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx
```

**Comment by cocreature** [comment]
Hi @dazraf, not quite sure what is going wrong here. I would recommend that you try installing the SDK natively instead of in WSL2.

**Comment by hurryabit** [comment]
@dazraf Does this issue still exist?

**Comment by cocreature** [comment]
Closing feel free to reopen if you can reproduce.
