### ISSUE TITLE
`daml` command completion prevents native path completion

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#4369]
When I enter a `daml` command that takes a path as argument I cannot (anymore) use path completion. Somehow the `daml` command completion interferes. Eg, I enter:

> daml codegen ts .daml`<TAB>`

which doesn't complete the path as expected.

Another issue is when I have directories that have the same name as `daml` commands, it completes with the directory name on <TAB> instead of the command. Eg, when I have a build/ and codegen/ directory, and I type

  daml `<TAB>`

I see: 

>   georgschneider:src$ daml
> --help       **build/**       **codegen/**     deploy       init         json-api     navigator    sandbox      start        test         trigger      version
> -h           clean        damlc        extractor    install      ledger       new          script       studio       test-script  uninstall
> 

And the completion is done for `build/` or `codegen/` instead of `build` or `codegen`

**Comment by cocreature** [comment]
Your first point is fixed in #4375 , I’ve opened https://github.com/digital-asset/daml/issues/4379 to track the second point.
