### ISSUE TITLE
DAML completion completes command to directory if it exists

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#4379]
`daml depl<TAB>` will complete to `deploy/` instead of `deploy` if a directory called `deploy` exists. Afaict this is only in Bash and not in Zsh, not quite sure why and what we can do about this.

**Comment by cocreature** [comment]
The issue is in the bash completion script generated by `optparse-applicative`. It looks as follows
```
_daml() {
…
}
complete -o filenames -F _daml daml
```

The `-o filenames` line results in bash adding the `/`, specifically the [docs]() describe`-o filenames` as follows:

> Tell Readline that the compspec generates filenames, so it can perform any filename-specific processing (like adding a slash to directory names, quoting special characters, or suppressing trailing spaces). This option is intended to be used with shell functions specified with -F.

I think we have two options here:
1. We patch the completion script when writing it out to remove `-o filenames`.
2. Do nothing since it isn’t all that common to have directories that match the command name.

I’m leaning towards 2 for simplicity and since I’m not entirely sure if there are no cases where `-o filenames`helps. What do you think @associahedron?

**Comment by associahedron** [comment]
Thanks for investigating! I think option 2 is probably best. We could also change the commands parser in daml-assistant to accept a `/` at the end of command names, so `daml build/ ...` still works, even if it's ugly.

**Comment by cocreature** [comment]
Alright, closing for now. Let’s revisit if we get more reports for this.
