### ISSUE TITLE
JSON API: Rename events field of exercise response from "contracts" to "events"

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4385]
Currently, the result obtained from the `/commands/exercise` endpoint looks like
```
{
    "status": 200,
    "result": {
        "exerciseResult": "#201:1",
        "contracts": [ E1, E2, ... ]
    }
}
```
The field name `contracts` is quite misleading since this array does not only contain `created` events (aka contracts) but also `archived` events. Thus, we should rename this field to `events`. This will also be in line with the change in #4384.

**Comment by leo-da** [comment]
Contracts can be created or archived:
`"contracts" :[ {"created": {...}, {"archived": {...}}]`

I assumed we don't want to mention events and transactions in the JSON API.

**Comment by hurryabit** [comment]
I agree that contracts can be created and archived. But that doesn't mean that the creation of a contract is a contract nor is the archival of a contract a contract itself. Both are events that happen to contracts (or actions you can do with them). That's why I think the word `contracts` is misleading and `events` describes the intent of the field better.

The documentation of JSON API will have to talk about events at some point. There are exactly two events in the life of a contract: its birth, the `created` event, and its death, the `archived` event.

There's no need (and no desire) to talk about transactions. But events make sense even without transactions and are significantly simpler than the latter.

Let's please rename this field to `events`.
