### ISSUE TITLE
Authorization: check application ID

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#4409]
The sandbox token format includes a `applicationID` field, but the ledger API does not use it to for validation - it is currently only read by the JSON ledger API.

We should add the application ID to [Claims](https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Claims.scala#L82), then use it in the ledger API service auth validation if present.

**Comment by piyushbedi-da** [comment]
@rautenrieth-da how can I see the list of current token fields that are being validated?

**Comment by rautenrieth-da** [comment]
@piyushbedi-da This is not documented well in the public docs - the fact that not all fields are used is really a bug.

Right now, all fields except the `applicationId` should be used for validation - https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Claims.scala#L82 gives you an idea what information is used by the ledger API server.

**Comment by piyushbedi-da** [comment]
This is related to https://github.com/digital-asset/daml/issues/5683

**Comment by stefanobaghino-da** [comment]
@piyushbedi-da How should an application-specific token behave when used for requests that don't have an application identifier (e.g. any admin service)?

**Comment by stefanobaghino-da** [comment]
How should we treat command submissions that contain commands with different application identifiers? I'd say that in the current state they should automatically fail when working against a Ledger API protected by authorization.

**Comment by stefanobaghino-da** [comment]
> @piyushbedi-da How should an application-specific token behave when used for requests that don't have an application identifier (e.g. any admin service)?

I'll simply ignore that for the time being in admin endpoints, if you think we should behave differently we can talk about it later. :slightly_smiling_face:

**Comment by piyushbedi-da** [comment]
Thanks.
For now, mirror the behaviour that the other command attributes (ledgerId, participantId and expiration) do in a token. IIUC, if any of those attributes are present in a token for a ledger with auth enabled, the server-side auth module will verify them, otherwise it'll bypass them.

**Comment by stefanobaghino-da** [comment]
> Thanks.
> For now, mirror the behaviour that the other command attributes (ledgerId, participantId and expiration) do in a token. IIUC, if any of those attributes are present in a token for a ledger with auth enabled, the server-side auth module will verify them, otherwise it'll bypass them.

Those attributes are different because they can be verified against any request as they pertain to the ledger. The issue with `applicationId` is that this can only be verified only when issuing commands (or retrieving results for a command), hence my question.

**Comment by rautenrieth-da** [comment]
@stefanobaghino-da IMO the ledger should behave as follows:

```
Field in token | Field in request | Action
---------------+------------------+---------------------------
 Present       | Present          | Authorize IFF values match
 Missing       | Present          | Authorize
 Present       | Missing          | Authorize
 Missing       | Missing          | Authorize
---------------|------------------+---------------------------
```

i.e.,
- missing fields in the token mean all values are authorized
- superfluous fields in the token are ignored

**Comment by stefanobaghino-da** [comment]
My question was not regarding the missing `applicationId` from a request but the behavior of tokens with an `applicationId` against a service that does not have such a field. As I mentioned before, I will simply ignore it for the time being. If there are different requirements we can address them separately.
