### ISSUE TITLE
Streaming/non-streaming responses should be consistent when handling empty request

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#4417]
See the comment: https://github.com/digital-asset/daml/pull/4393#discussion_r375461576

1. What happens if the list is empty?
2. Do we also allow the format `{"templateId": ..., "key": ...}` if the list contains only one element, i.e., N = 1?
3. We should try to be consistent with the other endpoints in this regard.

**Comment by S11001001** [comment]
(1) We already consistently reject the empty list case.

**Comment by leo-da** [comment]
1. @S11001001 yes we are rejecting such requests, just double checked.
2. @hurryabit @S11001001 do you really think we should do this? I would rather keep it as a list and avoid any "magic" transformation... we specify it has to be a list of `{templateId: xxx, key: yyy}` pairs I think we should stick with this.

**Comment by hurryabit** [comment]
Regarding 2: I don't think this transformation is very magic. My impression is that doing transformations like this is very common in JSON/YAML based configs. What do we do for the non-streaming endpoints?

**Comment by leo-da** [comment]
TODO:

sync query:
```
    {
        "templateIds": ["Iou:Iou1"],
        "query": {"amount": 999.99}
    }
```
returns:
```
{
    "warnings": {
        "unknownTemplateIds": [
            "Iou:Iou1"
        ]
    },
    "result": [],
    "status": 200
}
```
has to be an error!

**Comment by leo-da** [comment]
TODO: report an error when looking up party details and all requested parties are unknown. This would match the search behavior.

**Comment by hurryabit** [comment]
@leo-da I missed that last TODO somehow. I left a lengthy comment on the PR why I think this is wrong behaviour.
