### ISSUE TITLE
Only build Scaladoc in CI on Linux, and make it optional for local development

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#4441]
We currently spend a lot of time and processing power building Scaladoc for all our artifacts. I believe this is because we need to publish Scaladoc to Maven Central, which is admirable, but we probably don't need to do this multiple times.

Looks like we only release to Maven Central from Linux. If this is actually the case (I could be wrong), then let's only build the Scaladoc on Linux and save ourselves some time in the other CI builds.

I propose doing this with a Bazel tag, which will also allow us to selectively disable Scaladoc builds locally to speed up development.

**Comment by cocreature** [comment]
Sounds very reasonable. I can confirm that we only release to Maven Central from Linux.

**Comment by aherrmann** [comment]
That sounds reasonable to me. A Bazel tag sounds like a good way to do this.

**Comment by garyverhaegen-da** [comment]
👍
