### ISSUE TITLE
Indicate end-of-ACS/begin-of-transaction-stream in WS endpoint response streams

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4461]
Introduce a special event (format to be determined by @hurryabit ) at this boundary, to let applications have an approximation of when they're caught up to "live data". Perhaps `{"live": true}`?

**Comment by S11001001** [comment]
Would you prefer to let the live message be conflated with preceding ACS and following transaction? e.g.

```json
[{created: ...},
 {live: true}, // ^ ACS    v transaction
 {created: ...}]
```

We can also avoid this but it wouldn't be likely to deliver the live marker any sooner.

**Comment by hurryabit** [comment]
That's what I imagine:
```
{events: [...]}
{live: true}
{events: []}
{events: []}
...
```

**Comment by leo-da** [comment]
a bit too late, but I personally would have perfered:
```
{events: [...], live: false}
{events: [...], live: true}
{events: [...], live: true}
```

**Comment by S11001001** [comment]
`live` is going to be removed entirely anyway; #4509 obsoletes this feature.
