### ISSUE TITLE
vsts_agent_linux: remove build nodes out of the pool 2 hours before they're gc'ed

### ISSUE THREAD

**Issue by flokli** [digital-asset/daml#447]
This would prevent builds from suddenly getting cancelled, as the instance group manager has no idea on how to tell azure to stop scheduling builds on a specific machine.

**Comment by jonas-chevalier-da** [comment]
actually preemptible VMs can be terminated at any time so that won't solve the problem either

**Comment by cocreature** [comment]
Hasn’t really been an issue so closing
