### ISSUE TITLE
Provide way to determine json-api version

### ISSUE THREAD

**Issue by lJoublanc** [digital-asset/daml#4479]
It would be nice to be able to determine the version of the JSON api or SDK when making requests. I can think of several ways to do this:

- add a base name to the url e.g. `v1/commands/create`. Advantage of this is that we can support multiple versions in the same SDK release, thereby allowing a window of migration.
- add an endpoint that returns the SDK version number e.g. `https://localhost:7575/version`
- require the version to be passed-in as an argument in requests, which is validated, similar to the ledger API in the GRPC bindings.

It would be useful to have this as it would be easier to diagnose programs that stop working due to breaking changes in the API.

**Comment by hurryabit** [comment]
@lJoublanc We've recently merged a PR that adds `v1` to all endpoint names. This will be part of the next SDK release. The endpoints are not stable yet but we plan do stabilize them in the next couple weeks. After that, all new features will go into different endpoints.
