### ISSUE TITLE
Dlint - suggest notElem rule

### ISSUE THREAD

**Issue by chrisnorris-da** [digital-asset/daml#4493]
In e.g. filter ( \n -> (not . (n `` `elem` ``)) [1..3]) [1..10]
can we add a dlint rule to suggest use of notElem function ?
filter ( `` `notElem` `` [1..3] ) [1..10]

**Comment by hurryabit** [comment]
The left-hand side of this rule seems way to complicated to be triggered by enough people to make any investment worthwhile.
