### ISSUE TITLE
Don't hardcode version of scala libraries in release script

### ISSUE THREAD

**Issue by martin-drhu-da** [digital-asset/daml#45]
Currently, the generation of `.pom` files uses hardcoded versions of a few Scala libraries which are taken from `rules_scala`. This is likely to break if we upgrade `rules_scala`.
- [ ] `org.scala-lang:scala-library:2.12.2`
- [ ] `org.scala-lang.modules:scala-parser-combinators_2.12:1.0.4`
- [ ] `com.thesamet.scalapb:scalapb-runtime:0.8.4`

**Comment by martin-drhu-da** [comment]
@moritzkiefer-da I think this is closed by https://github.com/digital-asset/daml/pull/374? If so, can you please close the issue.

**Comment by moritzkiefer-da** [comment]
Yep this is fixed. We still hardcode the scala version atm but not the library versions and bumping a single version number when we upgrade Scala seems reasonable.
