### ISSUE TITLE
Reimplement implicit party allocation for Sandbox-on-X

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#4500]
Currently, Sandbox will allocate parties as soon as they're mentioned in DAML code (with `getParty`). However, the Ledger Integration Kit (a.k.a. _kvutils_) doesn't support this functionality. This is an issue for people new to DAML, especially as there's no way to allocate a party in DAML code itself.

We will need to make sure that we can keep implicit party allocation, or find another way to allow users to get started quickly with DAML and Sandbox.

**Comment by cocreature** [comment]
> We will need to make sure that we can keep implicit party allocation, or find another way to allow users to get started quickly with DAML and Sandbox.

You can allocate parties from DAML script so for ledger initialization that works reasonably nicely. What that doesn’t cover is entering parties in navigator that have not been allocated as part of ledger initialization.
