### ISSUE TITLE
"ticking" up the offset in websocket streams

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4510]
While we eagerly deliver blocks in WS streams as fast as possible, only conflating when backpressured, we also filter out empty blocks. Blocks can become empty because e.g. a transaction had some template-ID-matching contracts, but we filtered them all out. However, for reconnect purposes with #4509, it might be nice to sometimes have a later offset than "the last one that included non-filtered events".

The simplest approach would be to stop filtering out empty blocks, but that would mostly be spam, in a sense. We ought to decide a good way to do it with good trade-offs first.

Depends on #4509.

cc @hurryabit @gerolf-da

**Comment by hurryabit** [comment]
My gut feel is that we should do some sort of throttling similar to the heartbeats we do right now. That is if there wasn't a non-empty event block for the heartbeat period but there was at least one empty event block within this time, we send the last empty event block. If there weren't any event blocks at all, we send a regular heartbeat message. Does that make sense?

**Comment by S11001001** [comment]
@hurryabit That makes sense. We could also resend the last offset (always emptying events) as a heartbeat; that would remove the need to special-case `heartbeat` messages in client code, but would remove the invariant that every offset is unique in a message sequence. What do you think of that?

**Comment by hurryabit** [comment]
Sending the last offset as the heartbeat sounds reasonable. We could even do it as a regular message with an empty list of events. But I assume that's what you had in mind anyway.

I think the guarantee of seeing every offset only once would not have been very useful.
