### ISSUE TITLE
"phantom archive" filtering for reconnected fetch-by-key streams

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4511]
#4509 implies that a reconnected fetch-by-key stream won't have the state to filter out phantom archives, as a stream from the ledger-begin does. In #4509 we continue filtering out phantom archives iff an offset *is not* specified.

@hurryabit , @gerolf-da to determine what kind of burden is acceptable to place on users to correctly pass in a form of the fetch stream's state when reconnecting and what that data ought to look like. We also need to decide how to explain the behavior if the data passed in is wrong, besides the usual [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out).

Depends on #4509.

**Comment by hurryabit** [comment]
> what that data ought to look like

I suggest we use the query format
```
{templateId: ..., key: ..., offsetHint: ...}
```

> We also need to decide how to explain the behavior if the data passed in is wrong

There are three ways in which the input can be wrong and we should give the following guarantees:

1. **The input claims key `K` resolves to contract id `X` when it actually does not resolve to anything:** The stream will contain all events related to `K`. In addition, it will contain the archive event for `X`, should that ever happen.
2. **The input claims `K` does not resolve to any contract id when it actually resolves to `X`:** The stream will contain all events related to `K` except for the archive event for `X`, should that ever happen.
3. **The input claims `K` resolves to contract id `X` when it actually resolves to `Y`:** The stream will contain all events related to `K` except for the archive event for `Y`, should that ever happen. In addition, it will contain the archive event for `X`, should that ever happen.

IMO, this behavior sounds very reasonable. If I understood you correct @S11001001, this is also what the current implementation would give us if we initialized the state of the "phantom archive" stream filter with the user input. Is that correct?

**Comment by S11001001** [comment]
> I suggest we use the query format
> 
> ```
> {templateId: ..., key: ..., offsetHint: ...}
> ```

Should the value in `offsetHint` be a contract ID, then, `null` meaning no contract ID was associated with the {tid, key} at time of stream termination? (I'd use absence of a hint to mean that caller doesn't trust their ability to provide this data, so phantom archive filtering should be disabled.)

**Comment by hurryabit** [comment]
> Should the value in `offsetHint` be a contract ID, then, `null` meaning no contract ID was associated with the {tid, key} at time of stream termination?

Yes.

> (I'd use absence of a hint to mean that caller doesn't trust their ability to provide this data, so phantom archive filtering should be disabled.)

That makes perfect sense. I can't imagine anything better we could do.

**Comment by S11001001** [comment]
There's one ambiguity here: the presence of no `offsetHint`s could mean one of two things:

1. the set of active contracts for these keys was empty, so phantom archive filtering should occur with the internal state set to the empty set; or
2. the client doesn't have a reliable set, so phantom archive filtering should be disabled.

How should these be represented differently?

**Comment by hurryabit** [comment]
1. should be represented by all `offsetHint`s being `null` whereas 2. should represented by the absence of `offsetHint`s. That seems consistent to me.
