### ISSUE TITLE
include parties' display names for signatories, observers when present

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#4512]
Where parties occur in the domain model (that is, _not_ in LF values such as contract payloads), we can supply their display names alongside, like

```ts
{identifier: string,
 displayName?: string}
```

One presumes that the observers and signatories of a contract ought to have access to the display names of the others.

Example event:

```json
{
    "created": {
        "observers": [],
        "agreementText": "",
        "payload": {
            "observers": [],
            "issuer": "Alice",
            "amount": "999.99",
            "currency": "USD",
            "owner": "Alice"
        },
        "signatories": [
            {
                "identifier": "Alice",
                "displayName": "Alice Baker"
            }
        ],
        "contractId": "#1:0",
        "templateId": "b70bbfbc77a4790f66d4840cb19f657dd20848f5e2f64e39ad404a6cbd98cf75:Iou:Iou"
    }
}
```

**Comment by leo-da** [comment]
@hurryabit 
we cannot enrich party in the `payload` field. Technically, we can, but there will be pretty large run-time cost for this, and this will over-complicate the solution. So you can end up with the response like this (note that `observers` in the payload are an array of party IDs:
```
    {
        "status": 200,
        "result": {
            "observers": [
                {"identifier": "Bob"}
            ],
            "agreementText": "",
            "payload": {
                "observers": ["Charlie"],
                "issuer": "Alice",
                "amount": "999.99",
                "currency": "USD",
                "owner": "Alice"
            },
            "signatories": [
                {
                    "identifier": "Alice",
                    "displayName": "Alice & Co., LLC"
                },
                {
                    "identifier": "Bob"
                }
            ],
            "contractId": "#124:0",
            "templateId": "11c8f3ace75868d28136adc5cfc1de265a9ee5ad73fe8f2db97510e3631096a2:Iou:Iou"
        }
    }
```
This is a bit inconsistent. Let me know if this is going to be acceptable.

**Comment by leo-da** [comment]
maybe we should change the JSON encoding for DAML Party, this way all parties in the `payload` will come as:
```{identifier": "..."}```
stakeholders will come in the enriched form:
```{identifier": "...", "displayName": "...."}```

This will be more consistent. @hurryabit what do you think?

**Comment by leo-da** [comment]
Or another option... we keep everything *as is* (parties as JSON strings) and enrich parties on the client side.  We already have a call that returns all known parties.

**Comment by S11001001** [comment]
@leo-da We discussed this before making this ticket; the resolution was to only do the enrichment for the signatories and stakeholders response fields, nowhere else, for this ticket. The example response body given in the description is accurate to this intent.

**Comment by hurryabit** [comment]
Another way to reach consistency would be to leave the `signatories` and `observers` fields as is and add an additional field `parties` to the response. This field will contain a lookup table from party identifiers to display names. For the time being, we only fill this table with the display names of signatories and observers. For example,
```
    {
        "status": 200,
        "result": {
            "observers": [
                "Charlie"
            ],
            "payload": {
                "observers": ["Charlie"],
                "issuer": "Alice",
                "amount": "999.99",
                "currency": "USD",
                "owner": "Alice"
            },
            "signatories": [
                "Alice",
                "Bob" 
            ],
            "parties": {
                "Alice": "Alice from Wonderland",
                "Bob": "Bob the Builder",
                "Charlie": "Charlie Chaplin"
            }
            ...
        }
    }
```

I see multiple advantages with this approach:
1. It's backward compatible and doesn't break any existing code.
2. It avoids sending display names twice if a party is both a signatory and an observer. If we ever decide to deliver display names for all parties mentioned in the payload, this benefit would become even bigger.

What do you think?

**Comment by leo-da** [comment]
> @leo-da We discussed this before making this ticket; the resolution was to only do the enrichment for the signatories and stakeholders response fields, nowhere else, for this ticket. The example response body given in the description is accurate to this intent.

@S11001001 yes we did discuss, but the proposed change does not really make sense to me... I believe encoding observer parties in the payload and outside should be the same. I like the parties lookup table proposed by @hurryabit. Let's do it.

**Comment by leo-da** [comment]
@hurryabit thinking about the `parties` lookup table. We might still end up sending the same lookup table multiple times when streaming the events. What if I give you `/parties-lookup-table` JSON call?

**Comment by leo-da** [comment]
Change of plans... Party enrichment will be done on the client side, the existing `/v1/parties` endpoint will be extended to support optional List of party IDs to lookup.

**Comment by S11001001** [comment]
@leo-da Sounds good to me, though I emphasize this line from @hurryabit 

> For the time being, we only fill this table with the display names of signatories and observers.

**Comment by leo-da** [comment]
> @leo-da Sounds good to me, though I emphasize this line from @hurryabit

we are not changing the active contract response. as agreed with @hurryabit we are extending `/v1/parties` endpoint to support lookup by by ID, the enrichment will be done on the client side.
