### ISSUE TITLE
DAR/DALF reading utilities

### ISSUE THREAD

**Issue by gleber-da** [digital-asset/daml#452]
There seem to be at least 3 implementations of an utility which can read both DARs and DALFs:

* https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/damllf/PackageParser.scala#L22
* https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/config/DamlPackageContainer.scala
* https://github.com/digital-asset/daml/blob/master/daml-lf/archive/src/main/scala/com/digitalasset/daml/lf/archive/UniversalArchiveReader.scala#L25

They all seem to be doing the same thing. Ideally our code base would implement unified DAR/DALF reading utility only once.

**Comment by robin-da** [comment]
cc @leo-da

**Comment by leo-da** [comment]
The first two lose the semantics of main DALF and dependencies.
