### ISSUE TITLE
`da run navigator` should not require a Scala version suffix

### ISSUE THREAD

**Issue by moritzkiefer-da** [digital-asset/daml#455]
When I changed POM file generation, I consistently added the Scala version suffix to all Scala targets (which seems like the right thing to do afaik). What I did not anticipate that this now means that we have to run `da run navigator_2.12`. So we should remove that suffix at least for Navigator.

**Comment by neil-da** [comment]
Alternative is to create navigator.sh which calls navigator with the version number? (Not sure which is best, just that's one I thought of)

**Comment by moritzkiefer-da** [comment]
For now, I think it’s easier to just remove the version suffix see #456. For `daml-assistant` we don’t rely on this anyway so we can reconsider adding it if it turns out to be useful (although given that we haven’t done that for ages, it’s probably harmless).
