### ISSUE TITLE
Command interpretation: output whether time was used

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#4556]
For the new time model, the ledger API server needs to know whether `getTime` was used during command interpretation

Change `CommandExecutor` to include this information.

**Comment by rautenrieth-da** [comment]
> The ledger API server needs to know the maximum ledger time of any contract on which an action was performed

There are two options to implement this:

## As part of command execution:
- The `getContract` callback of the command executor is changed so that it also returns the ledger time of the given contract.
- The command executor keeps track of the maximum used ledger time
- The command executor returns two extra pieces of information:
  - Whether the result depends on time
  - The maximum ledger time of any referenced contract

This way there is no extra database query, the existing query will just have to return an extra column.

## As an extra step
- The command executor does not know about the ledger time of contracts
- The resulting transaction is traversed, all referenced contract IDs are gathered, and then their maximum time is queried from the database.
- The command executor returns one extra piece of information:
  - Whether the result depends on time

This way there is one extra database query (`SELECT max(let) FROM contracts WHERE id in (...)`), but the interface of `CommandExecutor` remains (almost) unchanged.

After talking to @gerolf-da, I think we should implement the second option. @remyhaemmerle-da @dajmaki @stefanobaghino-da do you see issues with this? In particular, which one is preferable for kvutils?

**Comment by remyhaemmerle-da** [comment]
@rautenrieth-da, I strikethrough the second point as I understood the engine do not need to provide this information anymore.
