### ISSUE TITLE
@daml/ledger: Make Ledger.streamFetchByKey stricter

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4564]
Currently, `Ledger.streamFetchByKey` is very lenient. We should not see a create event when a current contract exists. We should also only see archive events when a current contract exists and its contract id matches the archive event.

In the future, we should at least warn when we end up in these situations that should not happen.

**Comment by hurryabit** [comment]
FYI @cocreature I'm not 100% sure anymore what this was about.

**Comment by cocreature** [comment]
Closing until this come up again. I’ve looked at the implementation and I consider it sufficiently strict.
