### ISSUE TITLE
Navigator: periodically reload the list of packages

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#4592]
Navigator will currently only reload the list of packages when it encounters an unknown template in the transaction stream.
This is not useful if the user uploads a package and wants to create the first contract with it.

Since there is no push event from the ledger API when a new package is uploaded, Navigator should periodically reload the list of packages.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
