### ISSUE TITLE
TransactionServiceIT test keeps timing out

### ISSUE THREAD

**Issue by moritzkiefer-da** [digital-asset/daml#460]
We have seen several builds fail due to this so this should be fixed soon. Afaict the timeout is in https://github.com/digital-asset/daml/blob/2f6dd7d4eef220fcd1046889974240034fe65f33/ledger/ledger-api-integration-tests/src/test/lib/scala/com/digitalasset/platform/tests/integration/ledger/api/LedgerTestingHelpers.scala#L131 but it probably makes sense for someone to look at this before I blindly bump the timeout.

**Comment by cocreature** [comment]
Closing in favor of #548
