### ISSUE TITLE
Unexperimentalizing and stabilifying DAML script

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#4615]
Given that we deprecated scenarios for ledger initialization, I think it’s time to stabilize DAML script so we don’t have to recommend people to replace something deprecated by something experimental.

Here’s the list of things I think should happen before we do that:

- [x] Add `init-script` to `daml.yaml` to replace the `scenario` field in `daml.yaml` see #4473 .
- [x] Support authentication, see #3471. The technical side of this is easy but the UX might be a bit tricky. Eventually, you probably need to allow for at least one token per participant. You also need a separate admin token. That said, moving from only allowing one token to allowing multiple tokens would not be a breaking change so we can probably do that afterwards and only allow one token at the beginning. (EDIT: We have single-token auth now, I think that’s sufficient for making it stable. Extending this should not be a breaking change).
- [x] DAML script’s `submit` function currently collides with the one from `Prelude` so every DAML script requires `import Prelude hiding (submit)`. I see two ways of fixing this:
    1. Overload `submit`. Technically a breaking change but trivially fixable by adding a type annotation.
    2. Rename `submit` to `submitCmds/submitCommands/submitScript/…`.
    I’m cleaning towards the former since it feels less clunky and it avoids name bikeshedding.

What do you think @bame-da, @hurryabit @aherrmann-da? Anything I’ve missed?

**Comment by hurryabit** [comment]
I'm fine with overloading `submit`. Let's make the corresponding multi-param type class as user-friendly as possible.

**Comment by cocreature** [comment]
We have single-token auth now which is all I want for unexperimentalizing.
