### ISSUE TITLE
Performance Tests for all Sandbox ledger implementations

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#469]
- review and change the benchmarks we have around the Sandbox and have separate cases for Memory and Sql backed implementations
- set a Baseline for them
- fail CI if performance goes below the baseline? (not sure we want to do this, considering how much our CI performance has varied recently)

**Comment by gaboraranyossy-da** [comment]
should we set a baseline and fail CI when breached? @francesco-da

**Comment by bitonic** [comment]
@garyverhaegen-da that would be ideal, but I'd first get to the point where we have stable infrastructure to do perf tests, otherwise these regression checks would be extremely flaky.

**Comment by gaboraranyossy-da** [comment]
Let's leave this ticket open then. The first bullet-point is done though.

**Comment by garyverhaegen-da** [comment]
As of #1778 the existing perf tests have been disabled for being too flaky. I suppose the first step in this stream of work would be to either get the current perf tests to a point where they are stable enough to re-enable, or conclude that we're better off deleting them and starting from scratch. Either way I'm not comfortable keeping commented code for long.
