### ISSUE TITLE
come up with DAML-LF 2, which is exactly like DAML-LF 1.x, but without recursive data type

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#47]
we need to get rid of the recursive data type in the DAML-LF proto. it causes endless trouble (see #437 for the latest in a long series of complaints). i propose to just have an array of exprs at the top level for each module, i.e.

```
message ExprTable {
  repeated Expr exprs = 1;
}
```

and then have pointers into said array instead of recursive occurrences.

however, we might as well clean up other stuff since we can:

* [ ] remove recursive data type
* [ ] remove party literals, `getParty` and the flag indicating the absence of party literals
* [ ] remove deprecated arrow type
* [ ] clean up identifier data type to be in line with what we have in Scala
* [ ] remove the variant of `exercise` which expects actors
* [ ] remove `foldl`, `foldr` and `equal_list`

@martin-drhu-da @remyhaemmerle-da please add items as you see fit.

**Comment by remyhaemmerle-da** [comment]
Added colon to list of valid simple string characters. Confer  (#701) for more details

**Comment by hurryabit** [comment]
We should not use field index `0` in combination with `oneof`s. This doesn't work well with the C# protobuf codegen.

**Comment by remyhaemmerle-da** [comment]
This has been way too long opened.
