### ISSUE TITLE
Language Haskell cabal file is missing key dependencies.

### ISSUE THREAD

**Issue by tmcgilchrist-da** [digital-asset/daml#4706]
The package.yaml file for the Haskell language bindings is missing dependencies on mtl, sorted-list and utf8-string. Making the minimal changes here https://github.com/digital-asset/daml/commit/73a6cb779ca20c8419bc8324275a693552593b15 

Curiously the dependencies declared in `BUILD.bazel` are not identical to what's required in cabal.

```
    hackage_deps = [
        "async",
        "base",
        "bytestring",
        "containers",
-- Missing dep on deepseq
        "exceptions",
        "extra",
        "mtl",
        "grpc-haskell",
        "proto3-suite",
-- Missing dep on proto3-wire
        "retry",
        "sorted-list",
        "text",
        "time",
        "transformers",
        "unliftio",
        "utf8-string",
        "vector",
    ]
```

**Comment by cocreature** [comment]
The reason why the Bazel file needs fewer dependencies is that it includes the generated proto buf code as a separate library via `/ledger-api/grpc-definitions:ledger-api-haskellpb` whereas this is inlined in the cabal file.

**Comment by tmcgilchrist-da** [comment]
Thanks @moritzkiefer-da
