### ISSUE TITLE
Freeze released Flyway steps

### ISSUE THREAD

**Issue by gaboraranyossy-da** [digital-asset/daml#471]
We need to make sure that final versions of SQL migration source files will never change after they end up in a release.

proposal: We could hash the migration files and check them into the repo. The build script could validate the integrity of those files by hashing itself and comparing the hashes.

**Comment by gaboraranyossy-da** [comment]
fyi @francesco-da

**Comment by garyverhaegen-da** [comment]
If you're willing to go for a slightly more constraining model, you could say they should never change after having been added to master (after all, we don't always know exactly when releases will happen), and then you can instead add a small script to `//build.sh` that checks that for each migration file, it's only been ever touched by a single commit (i.e. it has been created and never touched again, as far as master history is concerned). That should work quite well with our squash-and-merge approach, and would require less manual steps to add locked-down hashes to a file (which could itself be easily changed to match the new hashes).

**Comment by gaboraranyossy-da** [comment]
thanks for your idea @garyverhaegen-da! We decided to go with a more light-weight approach for now in form of a unit tests. See #943 for more details.
