### ISSUE TITLE
introduce a SQL migration test

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#472]
Write a test which checks that we can upgrade to the latest database version from any existing former versions.

**Comment by stefanobaghino-da** [comment]
Fixed by #5826. Closing in favor of more fine grained tickets in the [`runtime/stability`](https://github.com/digital-asset/daml/milestone/44) milestone.

**Comment by stefanobaghino-da** [comment]
https://github.com/digital-asset/daml/milestone/44
