### ISSUE TITLE
Error message for record/variant ambiguous types unhelpful

### ISSUE THREAD

**Issue by martin-drhu-da** [digital-asset/daml#475]
When I do
```
data Bar = Bar
```
I get the error message
```
Ambiguous data type. Please disambiguate, e.g. data Foo = Foo {} for a record type or data Foo = Foo () for a variant type.
```
which does not mention `Bar` but `Foo` instead.

The error message should use the actual definition instead of the generic `data Foo = Foo ...`.

**Comment by hurryabit** [comment]
@rohanjr My understanding is that you fixed this issue. If so, can you please close the ticket.

**Comment by rohanjr-da** [comment]
Fixed by https://github.com/digital-asset/daml/pull/518
