### ISSUE TITLE
Organize maven groupIds

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#4758]
The artifacts published to maven are currently under two `groupId` roots:
- `com.daml`
- `com.digitalasset`

1) We want to bring all artifacts under the `com.daml` groupdId.
1) This will also allow us to move away from the `100` version to be in line with the SDK release version.
1) Some artifacts additionally have changed the artifact ID as well. See the table below.

Old Maven ID | New Maven ID |
------------- | --------------- | 
com.daml:codegen-main | com.daml:codegen-jvm-main
com.daml:codegen-common_2.12 | com.daml:codegen-jvm-common_2.12
com.daml.java:codegen | com.daml:codegen-java_2.12
com.daml.java:codegen-lib_2.12 | com.daml:codegen-java-lib_2.12
com.daml.scala:bindings_2.12 | com.daml:bindings-scala_2.12
com.digitalasset.ledger-service:utils_2.12 | com.daml:http-json-utils_2.12
com.digitalasset.ledger-service:db-backend_2.12 | com.daml:http-json-db-backend_2.12
com.daml.ledger:on-sql_2.12 | com.daml:daml-on-sql
com.daml.ledger:on-memory_2.12 | com.daml:daml-on-memory
com.daml:daml-project-config_2.12 | com.daml:daml-sdk-project-config_2.12
com.digitalasset.daml.lf.engine.trigger:runner_2.12 | com.daml:trigger-runner_2.12

**Comment by garyverhaegen-da** [comment]
Since this would be changing almost all Maven coordinates already (the only unchanged one I can spot is com.daml.ledger.on-sql), could we take this opportunity to drop the +100?

**Comment by SamirTalwar-DA** [comment]
Yes please! I'm in support of changing the artifact name for that one too, so it shouldn't get in the way.

**Comment by gerolf-da** [comment]
Good catch, @garyverhaegen-da. The ledger-on-sql groupId SHOULD have changed. I'll fix that.
And yes, getting rid of the 100 version is exactly the purpose of that.

**Comment by gerolf-da** [comment]
Actually, we can keep `com.daml.ledger` and change the artifactId to `daml-on-sql`.

**Comment by gerolf-da** [comment]
@garyverhaegen-da, @moritzkiefer-da: I changed everything to groupId `com.daml` and also removed the `10` prefix wherever I found it.
