### ISSUE TITLE
Generic Error from HTTP-JSON API for all types of failures in command submissions .

### ISSUE THREAD

**Issue by Nandansv** [digital-asset/daml#4778]
When we are submitting any command through http-Json-service `http://localhost:8081/command/exercise` and if we are passing wrong parameter name or if we are calling a choice on wrong template. <br>
I will be getting below error which is not at all helpful for understanding what went wrong during command submission. <br>

**Ex:** If choice `"SumOfElements"` which takes in parameters as `"entity"` and `"elements"`
using command/exercise endpoint , i will submit a command with variable name of `"elements"` as `"elemnt"` (A significant typo). <br>

Ideally I should be getting a response something as "Strict fields `"elements"` not found in payload" or something like that.<br>
But it throws below response<br>
```
{
    "message": "Request failed with status code 400",
    "name": "Error",
    "stack": "Error: Request failed with status code 400\n    at createError (C:\\x\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\x\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\x\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)",
    "config": {
        "url": "http://localhost:8081/command/exercise",
        "method": "post",
        "data": "{\"templateId\":{\"moduleName\":\"Template.Sample.Com\",\"entity\":\"NANDAN\"},\"contractId\":\"#105:4\",\"choice\":\"SumOfElements\",\"argument\":{\"elemnt\":\"XXXYYY\",,\"entity\":\"CMLLC\"}}",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8",
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZWRnZXJJZCI6Im5hbmR1c0xlZGdlciIsImFwcGxpY2F0aW9uSWQiOiJmb29iYXIiLCJwYXJ0eSI6IkJST0FEUklER0UifQ.VQOib4fHRbOPcsq4s6aIo6MHI0n0blmLoYJs3n6djhjhhPk",
            "User-Agent": "axios/0.19.1",
            "Content-Length": 252
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1
    }
}

```

Please throw some good error message back to response if something goes wrong.

**Comment by leo-da** [comment]
@Nandansv 

I am pretty sure this is not the HTTP JSON API error, the format is not what JSON API generates on error.

Looks like the error is coming from the Javascript/Nodejs proxy:
```
C:\\x\\node_modules\\axios\\lib\\core\\createError.js:16:15
```
which I believe drops the original error. JSON API error would be formatted the way it is described here:
https://docs.daml.com/json-api/index.html#error-reporting

**Comment by Nandansv** [comment]
> @Nandansv
> 
> I am pretty sure this is not the HTTP JSON API error, the format is not what JSON API generates on error.
> 
> Looks like the error is coming from the JavaScript/Nodejs proxy, `axios` module:
> 
> ```
> C:\\x\\node_modules\\axios\\lib\\core\\createError.js:16:15
> ```
> 
> which I believe drops the original error. JSON API error would be formatted the way it is described here: https://docs.daml.com/json-api/index.html#error-reporting
> 
> You should get an error response similar to this one:
> 
> ```
> {"status": 400, "errors": ["JSON parser error: Unexpected character 'f' at input index 27 (line 1, position 28)"]}
> ```

@leo-da  thanks!! Is this not available in LedgerAPIv0.8.1 and damlv0.13.36?

**Comment by leo-da** [comment]
Hi @Nandansv,

The error format was like this since the beginning, we just did not document it until recently :).

SDK v0.13.36 was released on Nov 14, 2019 and I strongly recommend updating to the latest SDK, there are a few JSON API breaking changes and it is better to address them sooner than later (ping me if you need any help).

E.g. the responses from some of the commands changed a bit, endpoints now have `/v1` prefix. Check the release notes: https://github.com/digital-asset/daml/releases and search for `JSON API`. Ping me if you get stuck and need any clarifications.
