### ISSUE TITLE
Fetching of TextMap in HTTP-Json API

### ISSUE THREAD

**Issue by Nandansv** [digital-asset/daml#4779]
In Current JSON Api service, There is no querying capability of Text Map.
It would be helpful to provide this querying capability soon.

**Comment by leo-da** [comment]
@Nandansv can you please provide a contract template and a query that did not work.
Map queries supposed to work (at least the tests are passing, maybe something else is broken :), here is the doc explaining how DAML map has to be formatted in JSON

**Comment by Nandansv** [comment]
> @Nandansv can you please provide a contract template and a query that did not work.
> `TextMap` queries supposed to work (at least the tests are passing, maybe something else is broken :), here is the doc explaining how DAML map has to be formatted in JSON: https://docs.daml.com/json-api/lf-value-specification.html#map
> 
> `GenMap` queries are not currently supported.

@leo-da  Here is the Example 

**Coin.daml**
```
template Coin with
   issuer : Party
   coinInformation : Map Text Text
where signatory issuer
```
From LedgerAPI , I have stored below information in Coin Contract.

issuer | coinInformation.currency | coinInformation.denomination | coinInformation.quantity | coinInformation.type
-- | -- | -- | -- | --
FED | USD | 100 | 1000000 | U.S Paper
FED | USD | 1 | 1000000 | Coin
FED | USD | 500 | 1000000 | U.S Paper
FED | USD | 1000 | 1000000 | U.S Paper

From above Active Contracts, i would like to use HTTP-JSON query feature and query only coins of type Coin and denomination = 1.

For that i could use endpoint of /contracts/search (Im using 0.13.36version of DAML and 0.8.1 version of ledgerAPI)
```
http://${host}:${jsonApiPort}/contracts/search`,
{ "templateIds": [
    "Coin.Coin"
],
"query": {
    "coinInformation": {
        "type": "Coin",
        "denomination": "1"
    }
}
},auth)
```

Its giving below response.
```
{
    "status": 200,
    "result": []
}
```

Cant i search with few known keys of map and get a result if key exist and give no result if key itself is not present?

**Comment by leo-da** [comment]
+ @S11001001 

@Nandansv the current implementation of Text Map queries requires you to specify all map keys and values. You cannot query text maps based on subset of keys.

**Comment by leo-da** [comment]
You might want to replace `Map Text Text` with a record, see https://docs.daml.com/daml/reference/data-types.html#records-and-record-types

I don't think `Map` is the right type choice for the `coinInformation`.

**Comment by Nandansv** [comment]
> You might want to replace `Map Text Text` with a record, see https://docs.daml.com/daml/reference/data-types.html#records-and-record-types
> 
> You can use `Optional` type for optional fields in the `CoinInformation` record.
> 
> I don't think `Map` is the right type choice for the `coinInformation`.

@leo-da 
i have used record and got results as you mentioned.
Also,I agree about usage of record type for coinInformation . But its just an example i have given.
There are more usecases where in i wanted to use Map and store a set of values and query them on need basis.
But querying subset of text map makes life easier.

(+) @ashfaq-shaik

**Comment by Nandansv** [comment]
> You might want to replace `Map Text Text` with a record, see https://docs.daml.com/daml/reference/data-types.html#records-and-record-types
> 
> You can use `Optional` type for optional fields in the `CoinInformation` record.
> 
> I don't think `Map` is the right type choice for the `coinInformation`.

@leo-da Is there any 

> CC @S11001001
> 
> @Nandansv the current implementation of Text Map queries requires you to specify all map keys and values you are querying for. You cannot query text maps based on subset of keys.

@leo-da  
Fine. Any plan to introduce this feature?

@ashfaq-shaik

**Comment by leo-da** [comment]
> Fine. Any plan to introduce this feature?
@Nandansv we do not have plans to add support for map queries allowing to specify subset of keys.

You can submit a feature request. cc @hurryabit

**Comment by leo-da** [comment]
@Nandansv we will get back to you regarding the map query support.

**Comment by gerolf-da** [comment]
@Nandansv: We consider the query matching feature for maps and lists not very useful right now, because one has to match the entire list and map. Therefore we will actually remove support for list and map matching, which allows us to introduce a more flexible approach for queries with maps and lists at a later stage.
