### ISSUE TITLE
Add result of exercise to transaction

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#479]
Exposing the result of an exercise as part of the transaction model can be very useful.

- [x] Update DAML-LF transaction specification
- [x] Change protobuf definitions
- [x] Update Sandbox
- [x] Updating Bindings API
- [ ] Example 
- [ ] Release Notes

**Comment by gerolf-da** [comment]
Start with going through the spec and adding the field to [NodeExercise](https://github.com/digital-asset/daml/blob/master/daml-lf/spec/transaction.rst#message-nodeexercise), followed by adding the field to the respective data structures in scala and protobuf.

**Comment by nicholassmith-da** [comment]
PR at #583
