### ISSUE TITLE
Make the execution order of DAML Script more intuitive

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#4821]
Throughout, I use the minimal template:

```
template T
  with
    p : Party
  where
    signatory p
```

My first attempt is a script that just writes 1000 copies of `T` and logs while it goes:

```
pump : Script () = do
  p <- allocatePartyWithHint "P" (PartyIdHint "P")
  forA_ [1..1000] $ \n -> do
    trace (show n) (submit p do createCmd T with p)
```

The result is that it first outputs 1000 lines of logs, and then actually sends the commands.

The best fix I found was to change to the below which forces a bit more lazyness. It would be nice to make the above (and applicative in general) behave the same. Trace and debug statements are not that useful if they don't happen at the time the action is actually performed.

```
pump : Script () = do
  p <- allocatePartyWithHint "P" (PartyIdHint "P")
  foldlA (\_ n -> trace (show n) (void $ submit p do createCmd T with p)) () [1..1000]
```

**Comment by cocreature** [comment]
This isn’t actually specific to DAML script and the problem is not execution order but evaluation order. `trace` will print when it’s evaluated. For things like DAML Script where evaluation (which evaluates to some DAML AST) and execution (actually interacting with the ledger) are separate concepts, this will always be confusing.

Rather than trying to throw more hacks on this to fix `trace`, how about we add `putStrLn` and `print` to `Daml.Script` that will print when executed so evaluation order doesn’t matter?

**Comment by bame-da** [comment]
How would those be different to `debug`? Because `debug` has the same problem. The below prints first, and executes later.

```
pump : Script () = do
  p <- allocatePartyWithHint "P" (PartyIdHint "P")
  forA_ [1..100000] $ \n -> do
    debug (show n)
    submit p do createCmd T with p
```

**Comment by cocreature** [comment]
`debug` still relies on `trace` so it’s tied to `evaluation`. If I add something of type `putStrLn : Text -> Script ()` I can execute it in the script runner so evaluation order does not matter anymore.

**Comment by bame-da** [comment]
I'd prefer things to be consistent between logging in daml contracts and script. Would it make sense to make `debug` behave in the expected way in general?

**Comment by cocreature** [comment]
> Would it make sense to make `debug` behave in the expected way in general?

Note that you run into the exact same issue in scenarios, e.g.,
```
daml 1.2
module Main where

import DA.Foldable

template T
  with
    p : Party
  where
    signatory p

setup = scenario do
  alice <- getParty "Alice"
  forA_ [0,1] $ \x -> do
    traceRaw "foo" (submit alice $ create (T alice))
    traceRaw "bar" (pure ())
  ```

will print `"foo", "foo", "bar", "bar"`.

In a strict language, you cannot really abstract over control flow (such as loops) using functions without running into these kind of issues all over the place.

One option that @hurryabit proposed to try to keep things consistent would be to accept that `trace` is garbage and add a new typeclass for `Action` instances that have a somewhat sensible version of `traceM`.
