### ISSUE TITLE
Add upload-package and download-package services to the JSON API

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#4823]
For environments that have limited access to the gRPC API (eg because HTTP2 is blocked), we should proxy the admin APIs through the JSON API.

All three APIs are simple request/response models and the proposal here is to simply proxy them transparently, merely translating grpc values to JSON and vice versa. The main challenge will be to represent the mixed binary and structured payloads on the package service.

CC @moritzkiefer-da @martin-drhu-da @gerolf-da @leo-da @S11001001

**Comment by leo-da** [comment]
Related to: #4638
cc @robin-da

**Comment by leo-da** [comment]
For things like this (pass-through) that do not require any changes to the gRPC format, we should consider generating such API from protobuf definitions, e.g https://github.com/grpc-ecosystem/grpc-gateway can do this.

**Comment by S11001001** [comment]
Allocate party is covered by #4638.

**Comment by leo-da** [comment]
@da-tanabe here is the plan:

As it is stated in the ticket, the below endpoints will be pass-through for the existing gRPC services, no additional functionality planned.

GET `/v1/packages` returns a JSON list of `PackageDetails`:
https://github.com/digital-asset/daml/blob/a2d785e3ee29c56b2b06780897fc7407666767f8/ledger-api/grpc-definitions/com/daml/ledger/api/v1/admin/package_management_service.proto#L59-L80

POST `/v1/packages/upload` takes a JSON `UploadDarRequest` command, where `dar_file` is a base64-encoded string:
https://github.com/digital-asset/daml/blob/a2d785e3ee29c56b2b06780897fc7407666767f8/ledger-api/grpc-definitions/com/daml/ledger/api/v1/admin/package_management_service.proto#L82-L93

POST `/v1/packages/download` takes package ID parameter and returns `GetPackageResponse` where `archive_payload` is a base64-encoded string:
https://github.com/digital-asset/daml/blob/a2d785e3ee29c56b2b06780897fc7407666767f8/ledger-api/grpc-definitions/com/daml/ledger/api/v1/package_service.proto#L68-L82

**Comment by da-tanabe** [comment]
The base64 encoding of payloads feels a little unnecessary; why not just return the raw bytes as the response, with a mime-type of `application/dalf` or something like that? Same with upload DAR…the body should just be the DAR file, and the optional submission ID could easily be a query string too. But certainly these endpoints existing at all is a good step forward.

**Comment by leo-da** [comment]
@da-tanabe this can be done... however in case of download, the gRPC API returns:
```
message GetPackageResponse {

  // The hash function we use to calculate the hash.
  // Required
  HashFunction hash_function = 1;

  // Contains a ``daml_lf`` ArchivePayload. See further details in ``daml_lf.proto``.
  // Required
  bytes archive_payload = 2;

  // The hash of the archive payload, can also used as a ``package_id``.
  // Must be a valid PackageIdString (as described in ``value.proto``).
  // Required
  string hash = 3;
}
```

you are suggesting to return `archive_payload` bytes in the response body.

Question: what would you do with that `archive_payload`? Do you need to save it as a dalf, with the final goal of reconstructing the DAR? Can you describe your use cases please?

**Comment by cocreature** [comment]
To me it would make the most sense to send and receive multipart form data. Then we can have one part encoded as json and for requests that include binary data (e.g. DARs or DALFs) we do can include them as binary. As for what we do with the payload in `GetPackageResponse`: We already have a `daml ledger fetch-dar` command in the SDK that reconstructs a DAR using that over the gRPC API and I definitely would like to have that run over the JSON API so I can run it against DABL and whatever else.

**Comment by leo-da** [comment]
@cocreature that is implementation details... I want to know what users are planning to do the the downloaded packages and why they need HTTP JSON API to allow them download them.

**Comment by leo-da** [comment]
so here is one use case from @cocreature 's message above:
1. fetch the entire DAR file and store it on a local drive.
