### ISSUE TITLE
daml2ts: Make importing the generated packages easier

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4832]
Currently, if you have a DAML package `foo` with modules `A` and `A.B`, you need to import them along the lines of
```typescript
import * as foo_A from "@daml2ts/foo/lib/A"
import * as foo_A_B from "@daml2ts/foo/lib/A/B"
```
Ideally, we'd have only one import
```typescript
import foo from "@daml2ts/foo"
```
and use `foo.A` and `foo.A.B` instead of `foo_A` and `foo_A_B` at the call sites.

To achieve this, we need to generate an `index.ts` file which imports and re-exports all the generated modules wrapped in the correct namespaces. The name collision checks in DAML-LF make sure we don't run into any problems here.

**Comment by shayne-fletcher** [comment]
Close to the desired syntax in https://github.com/digital-asset/daml/pull/4926. Follow up PR that gives us exactly the desired syntax on its way.

**Comment by shayne-fletcher** [comment]
Exact syntax landed in https://github.com/digital-asset/daml/pull/4946.
