### ISSUE TITLE
Explain why choices need authority checks

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4857]
One could think they are already covered by the privacy guarantees. Explain why that's dangerous, potentially mentioning future additions of explicit disclosure mechanisms.

**Comment by nemanja-da** [comment]
@hurryabit Might be too much for the GSG. We can't explain everything in it.

**Comment by hurryabit** [comment]
You're probably right. Only people who already know DAML might think these checks are useless because of the privacy model. New users most likely simply trust us.
