### ISSUE TITLE
Unclutter top level of the create-daml-app repo

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4866]
Currently, there's just too much stuff that users would need to delete if they would want to use this as a starting point for their own app.

**Comment by rohanjr** [comment]
I think this is done. What say you @hurryabit ?

**Comment by hurryabit** [comment]
@rohanjr Yes, I agree this is done now. What you get with `daml new ... create-daml-app` looks vert clean. However, the readme seems quite useless now. I've created another ticket to improve that: https://github.com/digital-asset/daml/issues/5623.
