### ISSUE TITLE
Add warnings for features that cannot be reconstructed in data-dependencies.

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#4932]
Certain advanced features of DAML cannot be reconstructed in data-dependencies, at least for the time being, so using them in a DAML model will hamper cross-SDK upgrades. To prevent users from shooting themselves in the foot without realizing it, we should add warnings whenever users use the following advanced features:

- `FunctionalDependencies`
- `DeriveGeneric`

I would also like to warn users against using `DataKinds`, but it sounds pretty difficult/expensive to detect in daml-preprocessor, and looking up enabled extensions requires looking at `DynFlags`, and unfortunately doesn't help distinguish between extensions defined in a file, and extensions configured via ghc-options, so you would get a warning on every file ... so it's probably better not to look at extensions directly.

**Comment by cocreature** [comment]
We have warnings now
