### ISSUE TITLE
Move to upstream versions of Haskell grpc libraries

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#501]
At the moment we have forked proto3-wire, proto3-suite, grpc-haskell-core and grpc-haskell. We should aim to unfork them all, since we're treading much the same path the upstream is treading.

**Comment by neil-da** [comment]
First step is moving to new versions of proto3-wire and proto3-suite. Turns out that the generation changes are incompatible with the fork we have (you get a test failure), so we need to move to both simultaneously.

Francesco did a lot of performance work on the proto3-wire. Separately, upstream (specifically @gbaz) also did a lot of performance work. Comparing on the test of writing out the LF for the CDM spec, our version took 5.4s, while upstream to 4.0s. I've raised a ticket for upstream to see if they want any of our tweaks https://github.com/awakesecurity/proto3-wire/issues/50, and merged some obvious ones https://github.com/awakesecurity/proto3-suite/pull/95. I also audited the changes, finding something at least with dodgy comments: https://github.com/awakesecurity/proto3-wire/issues/51

Neil did some work on Windows fixes and I've upstreamed those https://github.com/awakesecurity/proto3-suite/pull/94.

When I actually try and move I ran into an issue with proto3-suite generating invalid code. I've raised that upstream https://github.com/awakesecurity/proto3-suite/issues/97 and will work to get that resolved upstream at some point.

**Comment by neil-da** [comment]
I patched the generation of invalid code in https://github.com/awakesecurity/proto3-suite/pull/99. The other change stopping us moving was that proto3-suite doesn't generate NFData instances. I've fixed both of those issues in https://github.com/ndmitchell/proto3-suite/tree/nfdata

**Comment by cocreature** [comment]
we’re more or less on the upstream versions now so closing
