### ISSUE TITLE
GenMap JSON format

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#5031]
Choose a JSON format for GenMap (#2256) and support reading and writing in the lf-value-json library. This will also incidentally extend GenMap support to extractor.

Note that _querying_ GenMap will _not_ be supported by this change. This has parity with #4855.

Probably useful for #4188.

**Comment by hurryabit** [comment]
I see sensible ways to encode a `GenMap { K1 => V1, ..., Kn => Vn }`:
1. `[ [K1, V1], ..., [Kn, Kn] ]`
2. `[ {key: K1, value: V1}, ..., {key: Kn, value: V1} ]`

Two advantages of 1 immediately come to my mind: It's less bytes over the wire, but more importantly, you can pass the encoding of a `GenMap` into `new Map(...)` in JS land and it will give you a JS `Map`.

The only advantage of 2 I see is that it is more obvious that is encodes some sort of key-value-structure.

In view of this, I suggest we go with 1 but I'm open to hear to arguments why we should go with 2 instead.

**Comment by S11001001** [comment]
There's a third, similar encoding:

```js
[K1, V1, ..., Kn, Vn]
```

To throw some chum in the water, we could add some special cases.

```js
{K1: V1, ..., Kn: Vn}
```

is permitted _iff_ (choose your own adventure):

1. every value of the K _type_ can always be encoded as a string (e.g. Int, Party, but not Option(a) for any a because None cannot be encoded as a string);
2. K1...Kn are all string encoded (e.g. K type = Option(Int) is allowed if no K is None);
3. either of the above, but the server will never respond with such forms, only accept them as input.

I'd also like to know what you think should happen if two equal Ks are specified in JSON. Should it be an error? Decoder picks whichever it likes?

**Comment by hurryabit** [comment]
@S11001001 I don't see any advantage of the first format you brought up over 1. Thus I'd rule it out. I'm also not a fan of the second format you proposed as there are simply too many things to get wrong.

For the time being, I would only accept requests using the format we agree on as the response format (req/res from the JSON API's point of view). I don't see a lot of benefit in supporting multiple formats for this.

Regarding duplicate keys, I suggest the request fails a key occurs more than once. Everything else can become too confusing IMO.

**Comment by S11001001** [comment]
@hurryabit Another potential reason to support the second format in some cases is that `TextMap` may be removed in favor of `GenMap` for all cases; the second format would support current clients of `TextMap`. That may or may not outweigh the complexity of supporting two concurrent formats.

**Comment by S11001001** [comment]
For now, we will only support the format

>     1. [ [K1, V1], ..., [Kn, Kn] ]

For both reading and writing. As discussed with @hurryabit @leo-da @gerolf-da
