### ISSUE TITLE
daml2ts : Consider using a pretty printing library

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/daml#5047]
We might consider using a pretty-print library in daml2ts to help extensibility and maintainability as suggested by @cocreature  in https://github.com/digital-asset/daml/pull/4975#discussion_r391871327.

**Comment by hurryabit** [comment]
@cocreature You already improved the situation quite a lot in this regard. Shall we close the ticket?

**Comment by cocreature** [comment]
:fire:
