### ISSUE TITLE
Configure/enable standard automatic keep-alive Ping support for websocket streaming API

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#5071]
https://doc.akka.io/docs/akka-http/current/server-side/websocket-support.html#automatic-keep-alive-ping-support

> This is supported in a transparent way via configuration in Akka HTTP, and you can enable it by setting the: akka.http.server.websocket.periodic-keep-alive-max-idle = 1 second to a specified max idle timeout. The keep alive triggers when no other messages are in-flight during the such configured period. Akka HTTP will then automatically send a Ping frame for each of such idle intervals.
>
> By default, the automatic keep-alive feature is disabled.

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets

### ACs
- JSON API sends keep-alive Ping
- JSON API handles incoming keep-alive Ping sending Pong back
- JSON API docs specify heartbeat Ping/Pong message format
- JSON API docs do NOT refer to empty events block as a heartbeat.

**Comment by leo-da** [comment]
Meeting notes:
- we are going to add the standard keep-alive Ping/Pong heartbeating
- if the latest seen offset changed, empty events block containing the offset will be emitted/ticked at the same interval as the standard keep-alive messages
- if the last seen offset did not change, empty events block will not be emitted.

**Comment by stefanobaghino-da** [comment]
Functional subset of what we already have (keep-alive with offset from the JSON API server), closing.
