### ISSUE TITLE
StandaloneApiServer allows no seeding opt-out

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#5077]
The `StandaloneApiServer` currently precludes X's from not yet supporting the new daml-lf seeding approach. Until we have come up with a plan in Canton, we need to opt out temporarily.

Luckily this is only the case at the "outer-most" layer, i.e. internally the api server still supports the non-seed code path.
```
final class StandaloneApiServer(
    config: ApiServerConfig,
    commandConfig: CommandConfiguration,
    submissionConfig: SubmissionConfiguration,
    readService: ReadService,
    writeService: WriteService,
    authService: AuthService,
    metrics: MetricRegistry,
    timeServiceBackend: Option[TimeServiceBackend] = None,
-    seeding: Seeding,
+    seeding: Option[Seeding],
    otherServices: immutable.Seq[BindableService] = immutable.Seq.empty,
    otherInterceptors: List[ServerInterceptor] = List.empty,
    engine: Engine = sharedEngine // allows sharing DAML engine with DAML-on-X participant
)```
from https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/apiserver/StandaloneApiServer.scala#L53

**Comment by oliverse-da** [comment]
Looks like this fix was dropped again in the last week. cc @SamirTalwar . Since we are in the process of moving to seeding (but in a modified format), I will handle this on the canton side for now, but keeping this open on the daml side as a tracking item.

**Comment by SamirTalwar-DA** [comment]
Damn. I will revert it and add a comment so I don't make this mistake again in two weeks.
