### ISSUE TITLE
Ledger API command changes around MRT/TTL to reflect in JSON API

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#5090]
Ledger API is going to deprecate required `ledger_effective_time` and `maximum_record_time` in favor of optional `deduplication_time`, `min_ledger_time_abs` and `min_ledger_time_rel`

https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/commands.proto#L50-L56
 
https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/commands.proto#L62-L78

Talk to @rautenrieth-da before starting to work on it.

Related to: #5100, #5172

**Comment by leo-da** [comment]
@rautenrieth-da @gerolf-da `ledger_effective_time` and `maximum_record_time` are required according to protobuf message doc. If we drop both fields in JSON API, do we have to populate them in the gRPC command?

**Comment by gerolf-da** [comment]
@leo-da: they are *still* required, because the new time model isn't fully implemented yet. So for the time being please populate them in the gRPC command.
