### ISSUE TITLE
introduce a Sandbox config file 

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#51]
- Introduce a config file using Typesafe config
- Put all DB / TLS related entries there
- use it for various hardcoded elements as well
- Reconsider shared uses case with CLI

**Comment by associahedron** [comment]
As mentioned in #820, this should not be a separate config file but should be part of the daml assistant configs. There are two config files of interest:

- `$DAML_PROJECT/daml.yaml`: These are project specific settings. It would be reasonable to put any project-relevant settings of the sandbox here, in a `sandbox` section in the YAML. 
- `$DAML_HOME/daml-config.yaml`: These are user specific settings, and should be used sparingly. If the sandbox has any config options that would not be appropriate at the project config level, they should go here under a `sandbox` section in the YAML.

More notes:

- `DAML_PROJECT` and `DAML_HOME` are environment variables set by the assistant, specifically for the purposes of allowing tools to be properly configured & scoped.
- Tools are not meant to modify these config files, users are supposed to edit them themselves.
- There are utility functions for reading & querying these config files in daml-assistant/daml-project-config, but that's a Haskell library.

**Comment by stefanobaghino-da** [comment]
`daml.yaml` already allows to set the relevant configuration for `sandbox`, closing. This could become relevant again for DAML-on-SQL but that's a separate topic and should be tracked separately.
