### ISSUE TITLE
Allow for deterministic contract ids in sandbox-next with static time

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#5107]
For documentation it is quite helpful to have deterministic contractIds to refer to, instead of having to describe "copy and paste the contractId you see on the screen, so that you can use it later".

To that end, the following needs to happen:
1) Add a `Static` seed generator next to `Weak` and `Strong` that is always initialized with the same seed for the RNG.
1) Add the static seed generator to the CLI config.
1) Remove fuzzing of submission time, from which the transaction seed is generated. This fuzzing is also not needed anymore in general:
https://github.com/digital-asset/daml/blob/febace739101687877a2cbb7f6ee2844e3d59983/daml-lf/engine/src/main/scala/com/digitalasset/daml/lf/engine/Engine.scala#L55-L58

**Comment by gerolf-da** [comment]
@bame-da: do we also need deterministic transaction IDs?

**Comment by bame-da** [comment]
Isn't TXId part of `ContractId`? If so, then yes.
