### ISSUE TITLE
Navigator throws error on party with spaces " "

### ISSUE THREAD

**Issue by briandbecker** [digital-asset/daml#512]
According to the documentation the party data type supports spaces.  When a party includes a space Navigator throws an error.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/2085521/56155206-5eab8200-5f88-11e9-9e54-615efd6ccc05.png">

Steps to reproduce:

1. Use the IOU getting started contract
2. Add a new party to the daml/Main.daml file with a " " (space character) in their name
```
daml 1.2
module Main where

import Iou
import IouTrade()

setup = scenario do
  alice <- getParty "Alice"
  malice <- getParty "Alice "
  bob <- getParty "Bob"
  usBank <- getParty "USD_Bank"
  eurBank <- getParty "EUR_Bank"

  -- Banks issue Iou transfers
  iouTransferAliceCid <- submit eurBank do
    iouCid <- create Iou with
      issuer = eurBank
      owner = eurBank
      currency = "EUR"
      amount = 100.0
      observers = []
    exercise iouCid Iou_Transfer with newOwner = alice

  iouTransferMaliceCid <- submit eurBank do
    iouCid <- create Iou with
      issuer = eurBank
      owner = eurBank
      currency = "EUR"
      amount = 100.0
      observers = []
    exercise iouCid Iou_Transfer with newOwner = malice

  iouTransferBobCid <- submit usBank do
    iouCid <- create Iou with
      issuer = usBank
      owner = usBank
      currency = "USD"
      amount = 110.0
      observers = []
    exercise iouCid Iou_Transfer with newOwner = bob

  -- Bob and Alice accept
  submit alice do
    exercise iouTransferAliceCid IouTransfer_Accept
  submit malice do
    exercise iouTransferMaliceCid IouTransfer_Accept
  submit bob do
    exercise iouTransferBobCid IouTransfer_Accept
```
3. Update ui-backend.conf
```
users
  {
    Alice { party = "Alice" },
    Malice { party = "Alice " },
    Bob { party = "Bob" },
    USD Bank { party = "USD_Bank" },
    EUR Bank { party = "EUR_Bank" }
  }

```

4. Update da.yaml (not sure necessary?)
```
project:
  sdk-version: 0.12.3
  scenario: Main:setup
  name: quickstart
  source: daml/Main.daml
  parties:
  - Alice
  - Alice 
  - Bob
  - USD_Bank
  - EUR_Bank
version: 2
```
5. Compile and run sandbox and navigator; everything should start just fine
```
da run damlc -- package daml/Main.daml target/daml/iou
da run sandbox -- --port 6865 --scenario Main:setup target/daml/*
da run navigator -- server localhost 6865 --port 7500
```

6. View the navigator.log file and you should see the following failue

> Invalid actor path element [party-Alice ], illegal character [ ]

The Navigator application will also no longer work for Malice ("Alice ") and EUR Bank ("EUR_Bank")

**Comment by briandbecker** [comment]
Looks like it should URL Encode party names before accessing akka 

> The name parameter is optional, but you should preferably name your actors, since that is used in log messages and for identifying actors. **The name must not be empty or start with $, but it may contain URL encoded characters (eg. %20 for a blank space)**. If the given name is already in use by another child to the same parent an InvalidActorNameException is thrown.

https://doc.akka.io/docs/akka/2.5.4/scala/actors.html

**Comment by neil-da** [comment]
Thanks @briandbecker - I confirm that Party should support spaces, as per the docs. Good catch - @rautenrieth-da - can you take a look?
