### ISSUE TITLE
Specify fixed authorization header format for Ledger API

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#5138]
While the authorization mechanism has been fairly flexible, this also leads to inconvenience on the client side.
Therefore we want to specify that the authorization header for the Ledger API must always start with `Bearer ` (notice the trailing space) followed by the authorization information (e.g. the JWT).

**Comment by da-tanabe** [comment]
Thanks @gerolf-da !

**Comment by cocreature** [comment]
Fixed in #5484, thanks @gerolf-da!
