### ISSUE TITLE
Engine: Control the transaction and value version generated.

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#5164]
## The problem

The Engine serializes its outputs according transaction and a value versions.

Different versions are / could be used for a wide range of purposes:

* Support language features, (eg. Optional, GenMap, contract keys ...)
* Support engine features
* Performance (e.g. space, speed, determinism ...)
* Enrich output with extra information needed by a specific ledger implementation.

Currently, a DAML-LF compliant engine must be able to read any version of the transactions and values, but there is no clear constraints on the version it is allowed to write. In fact currently used transaction version is often the latest one, while the value version is often the smallest possible one.

We may want to control more granularly the **maximal version**, the engine can produce, for the following reason:

* **Control Ledger Integration**.
  Since the Engine is supposed to be embedded in different Ledger implementation with different upgrade policy, it seems reasonable the ledger implementation can control the way data are serialized.
  Different Ledger implementation may have different upgrade policy. It this case it is necessary a particular implementation have some control over data serialization. For instance let's imagine, we want that all the sandboxes with the same major version used the same serialization format (+database scheme). Hence, a user could rollback to an older sandbox versions if an issued appears (e.g. a bug in the sandbox or an incompatibility in the user integration code).
  Similarly, some changes may be required in a particular ledger implementation to support a new transaction/value versions. For instance if the implement scrutinizes the data. Controlling the engine output may allow the ledger implementation to use a newer version of the engine, while giving some time to implement the changes required by the new serialization version.

* **For network upgrade.** 
   When introducing a new serialization version (let's say version 'v'), we need first:
  - upgrading the participant nodes one by one with a version of the engine able to read 'v', but configured to produce an older version (let say 'v-1'), so older nodes can understand the serialization format generated by the upgraded nodes
  - once all the nodes have been updated (or at least after some reasonable amount of time have been left to perform the upgrade), updating the configuration of the participant, so they start to produce newer format.

* **Improve development confidence.**
  Currently any new version of transaction and value are generated as soon they are introduced in the code. In order to improve the confidence we have in a particular features we may want to be able to generate a new version of transaction and/or values for testing only. We may want to test for some time (several weeks) a new feature before releasing it officially.
  We may also be able to ship several changes in a unique version (since we can control the latest version is not used in production), hence reducing the complexity to handle a large number of different versions.

We may want to control more granularly the **minimal version**, the engine can produce, for the following reason:

* **Performance Improvement**
We may introduce a new version of value/transaction, to for instance, improve storage space.
While there is currently no obligation for the engine to use this new version, it may be interesting, in a DAML network where all the nodes support this new version, to force the newest possible version in order to take advantages of the improvement this new version provides.

## The solution we choose

1.   We add to the Engine a configuration :  

```
 final case class VersionRange[V](min: V, max: V)
  final case class Config(
    languageVersions: VersionRange[LanguageVersion],
    intputTransactionVersions: VersionRange[TransactionVersion],
    outputTransactionVersions: VersionRange[TransactionVersion],
  )
```

2.  The Engine will :
  * refuse to load any `LF` whose version is not in `languageVersions`
  * refuse to handle input whose version is not in `intputTransactionVersions` 
  * produce output whose version is in `outputTransactionVersions` which exact version is unspecified 
  * crashes if there exists no such version

3. Simplify the versionning : 

  * We will bind future `ValueVersion` and `TransactionVersion`
      + `TransactionVersion` `“10”` will come with `ValueVersion` `“6”` 
      + `TransactionVersion` `“11”` will come with `ValueVersion` `“11”`
        => No need to talk about `ValueVersion`

   * Each new `LanguageVersion` will have an associate `ValueVersion`/`TransactionVersion`
    + `LF 1.6` -> `“6”`/`”10”`
    + `LF 1.7` -> `“6”`/`”10”`   
    + `LF 1.8` -> `“6”`/`”10”`
    + `LF 1.9` -> `“11”`/`”11”`

Note that since `SDK 1.0.0` the engine support only : 
*  `TransactionVersion` `“9”` or earlier are deprecated   ~(only used in sandbox classic)~
*  `TransactionVersion` `“10”` or latter for output  
*  `ValueVersion` `“5”` or earlier are deprecated   ~(only used in sandbox classic)~
*  `ValueVersion` `“6”` or latter for output  
* `LF 1.4` or earlier are deprecated   ~(only used in sandbox classic)~
(See #5220 and #5321)

**Comment by oggy-** [comment]
Thanks, this sounds like a reasonable approach in general. When we were writing up the platform requirements a couple of years ago, we settled on a similar story (the write-up ended up in Canton's high-level requirements, search for "cross-version" in https://www.canton.io/docs/stable/user-manual/architecture/requirements/requirements.html#non-functional-requirements). Obviously, interoperability between `v_i` and `v_{i+1}` is necessary. For Canton, this would be the protocol version (which would also specify the engine version), and domains would specify the acceptable versions. A major/minor scheme would make sense IMO.

A few topics I don't see covered:
- deprecation of features. As `v_i` and `v_{i+1}` need to interoperate, a deprecated feature should take at least two major version to sunset. The users would have to upgrade their contracts and packages in the meantime.
- how interpreter bug fixes should work. For example, if the interpreter is buggy in engine version `2.3`, do we retain the buggy behavior in `2.4` and `3.0`?
- (optional) more optimal handling of contracts and packages that are unaffected by version upgrades. For example, say engine `ev1` supports LF version `lfv1` and `ev5` supports only LF versions `lfv4` and `lfv5`. if I have a package `Bland` compiled for `lfv1` that doesn't use any of the deprecated features, it'd be nice to avoid having to upgrade the package or its contract instances. But I don't find this crucial.

As an aside, it might get interesting for Canton with participant nodes that are connected to multiple domains, but I think by that point we can spawn different processes out for that case.

**Comment by oggy-** [comment]
This bug (i.e., how to go about fixing it) is a good test for any proposed solution:
https://github.com/digital-asset/daml/issues/5334

**Comment by S11001001** [comment]
You won't hurt the design purposes of how versioning is done now if all you do is put optional floors and ceilings on the current decision paths, which is what it sounds like you are doing.

> In fact currently used transaction version is often the latest one, while the value version is often the smallest possible one.

The chosen transaction version is also the smallest possible one; it so happens that changes to the transaction format often introduce features intended to be pervasive.

Because the goal is always to choose an older version over a newer one (see [governance document](https://github.com/digital-asset/daml/blob/master/daml-lf/governance.rst#engine)), the only valid thing for many transactions and values for which a too-new version is chosen will be to crash. I assume this behavior is preferable. In fact, the proper outcome of this proposal should be that this is the only thing that can happen when the assigned version is too new. To elaborate:

1. There are times when we choose a newer version to support an optional but highly desirable feature, because we otherwise don't think there will be other motivations to choose that newer version and thus coincidentally gain the benefits of the optional feature.
2. Under this design change, the proper way to get those benefits is to tighten the minimum output version.
3. As such, the only remaining floors in `assignVersion` should be for required features, for which "graceful degradation" is not possible.

In a sense, this returns `assignVersion` to its original intent.

**Comment by S11001001** [comment]
> A few topics I don't see covered:

@oggy- [Existing LF governance rules](https://github.com/digital-asset/daml/blob/b9933398440db02e975c883f8d3545cb49c3038a/daml-lf/governance.rst), which this proposal extends, should address or moot all of these topics; let me know if you would like elaborations.

**Comment by remyhaemmerle-da** [comment]
update thanks to #7344 Sandbox classic does not use any-more deprecated value format.

**Comment by remyhaemmerle-da** [comment]
replaced by #7788
