### ISSUE TITLE
Create standalone SDK package for offline installation

### ISSUE THREAD

**Issue by georg-da** [digital-asset/daml#52]
We expect many of our users to work in locked-down environments, where the assistant won't be able to download from external sites. For these situations we need to provide a zip / tarball with the latest SDK version, that can installed following some instructions (where to unzip, which things to put on path, etc.)

**Comment by associahedron** [comment]
We have this now, with the new daml assistant and releases, which should work offline out of the box. The one caveat is that maven dependencies for e.g. the ledger bindings are not offline but hosted on bintray. I don't know what the plan is wrt those. cc @bitonic @cocreature

**Comment by cocreature** [comment]
It doesn’t really make sense to put maven dependencies in the tarball. They should be published to a package repository (whether that is Bintray or Maven central doesn’t really matter) and companies can then host their own mirrors if they want to.

**Comment by bitonic** [comment]
@cocreature agreed, @nicholassmith-da is working on publishing them to maven.
