### ISSUE TITLE
Drop support form old version of LF and serialization

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#5220]
With the release of SDK 1.0, we want to drop the support of old LF version and old transaction/value version for any ledger, except the sandbox. 

The plan is to support the following version (and following): 
- LF Version 1.6 (main feature: string internalization)
- Value version 6 (main feature: Numeric)
- Transaction version 10 (main feature: maintainers in fetch nodes)

In practice, for SDK 1.0 
- We deprecate LF Version older that 1.6 (in the spec) 
- We force the engine to produce at least value version 6 and transaction 10 as output. 
- We let the support when reading for older version of value and transaction until the legacy sandbox is not supported. 
- (Optionally) we forbid kvutils to read older version. 

This means **we will not guarantee any data continuation for ledgers other than than sandbox**.

**Comment by remyhaemmerle-da** [comment]
cc @gerolf-da @hurryabit

**Comment by remyhaemmerle-da** [comment]
cc @S11001001

**Comment by S11001001** [comment]
Be aware that _all_ ledgers prior to this change will likely become unreadable.

**Comment by remyhaemmerle-da** [comment]
cc @gerolf-da

**Comment by remyhaemmerle-da** [comment]
> Be aware that _all_ ledgers prior to this change will likely become unreadable. That includes the ones created after the transaction and value versions stated above were available.
Thanks Stephen for the comment. 
You are indeed right. That mean, we will **not** guarantee any data continuity for ledger except the legacy Sandbox  (I adapt the description above).
@gerolf-da can you confirm that is fine.

**Comment by remyhaemmerle-da** [comment]
cc @bame-da

**Comment by gerolf-da** [comment]
Looks good to me.
Let's also check with @da-tanabe: will this be a problem for you?

**Comment by bame-da** [comment]
Am I right in thinking this is done? If so, please close. @remyhaemmerle-da @gerolf-da
