### ISSUE TITLE
Docs: ping-pong example uses old API versions

### ISSUE THREAD

**Issue by oggy-** [digital-asset/daml#524]
The ping-pong example used in the docs uses old versions of the SDK APIs (bindings, archive). It does not compile when the dependency versions are bumped (in `pom.xml`). FIY @bethaitman-da

**Comment by gerolf-da** [comment]
@oggy-: Could you provide a link to the examples you are referring to please?

**Comment by oggy-** [comment]
@gerolf-da I'm referring to:
https://github.com/digital-asset/ex-java-bindings/blob/master/pom.xml

(which is the example linked to from the SDK docs, or at least was at the time)

**Comment by cocreature** [comment]
This is on a somewhat recent SDK now (1.0.0) so closing
