### ISSUE TITLE
Enable ledger backends to retire workflow-ids

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#5303]
Ledger backends have no means on the ledger API to signal the completion of a workflow, thus removing it from the map of workflow locations. Originally tracked in https://github.com/DACH-NY/canton/issues/720 .

**Comment by gerolf-da** [comment]
@oliverse-da: is this still relevant?

**Comment by oliverse-da** [comment]
I think we can close this as this is not anything canton is blocked by.
