### ISSUE TITLE
Sandbox: separate read and write concern in the database and above

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#531]
The motivation for this change would be to rethink the SQL schema we have, so we can separate the implementation of writers of the ledger from the readers. Essentially it would need to be compatible with these interfaces:

• ReadService: https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/ReadService.scala
• WriteService: https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/WriteService.scala
• IndexService: https://github.com/digital-asset/daml/blob/master/ledger/participant-state-index/src/main/scala/com/daml/ledger/participant/state/index/v1/IndexService.scala 

As a first step, we should focus on the splitting the SQL schema, later on we can work on moving the internal architecture closer this new model.

Tasks:
- split the schema into two, denormalisation allowed
- introduce connection pools, jdbcurls, flyway etc for the second schema
- introduce another decoupling to feed the Index layer from the already populated write store

**Comment by gaboraranyossy-da** [comment]
After doing some analysis, it seems that the `IndexService` would need practically all the data we have in our schema. We could potentially discard some fields for the `Write/ReadService`, but it wouldn't worth the trouble having to evolve two separate schemas for this. 

My take is that we should have all the above mentioned interfaces implemented by the existing database layer we already have. Putting this on hold, as this task in not a priority right now. 

@francesco-da FYI ^

**Comment by gerolf-da** [comment]
This is now complete and was done as part of implementing the `ReadService`,  `WriteService`, and `IndexService` interfaces.
