### ISSUE TITLE
DAML bug when following the tutorial

### ISSUE THREAD

**Issue by dportabella** [digital-asset/daml#5324]
Hi @gerolf-da, @meiersi-da,

I download the last version of the DAML SDJ, I followed the DAML tutorial, and it seems that there is a bug:

https://docs.daml.com/getting-started/quickstart.html#try-out-the-application

> Try creating a contract from a template. Issue an Iou to yourself by
> clicking on the Iou:Iou row, filling it out as shown below and
> clicking Submit.
> http://localhost:4000/templates/Iou:Iou@f7592b50015725110188fe00bea8373fdcdceaeea90a1664682df422a9853b6e/

After filling out the form and clicking Submit, I get this error:
> Error: Network error: Network request failed with status 500 -
> "Internal Server Error"

**Comment by meiersi-da** [comment]
Thanks @dportabella . Could you please also post the logs of the Sandbox and Navigator commands output on their console?

**Comment by meiersi-da** [comment]
@martin-drhu-da who's the right person in your team to debug this getting started guide problem?

**Comment by cocreature** [comment]
Hi @dportabella, I just went through the example on SDK version 0.13.55 (the latest stable release as of today) and it worked as expected for me. As @meiersi-da already said, it would be great if you could show us the `sandbox.log` file and the `navigator.log` file as well as the terminal output.

**Comment by dportabella** [comment]
I just went through the example again, and it worked fine.
I don't manage to reproduce the problem, so I'll close the ticket.
Thanks for your support.
