### ISSUE TITLE
Reenable build-and-lint-test on Mac OS

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#5382]
The `//language-support/ts/codegen/tests:build-and-lint-test` test currently only run on Linux. Once https://github.com/digital-asset/daml/issues/4483 has landed, we should switch it to that mechanism and reenable it on Mac OS.

We should also take that opportunity to let the Sandbox and the JSON API pick their ports and unmark the test as being exclusive.

**Comment by cocreature** [comment]
You might want to switch to filtering them out via a tag so they are still run locally but not on CI.

**Comment by hurryabit** [comment]
> You might want to switch to filtering them out via a tag so they are still run locally but not on CI.

Is there any precedence for this I can blindly copy? Or do I need to be creative?

**Comment by cocreature** [comment]
https://github.com/digital-asset/daml/blob/1bedfaa151d053a88832b091d8416a47edb3348a/build.sh#L18 has the list of tags that we filter. If you grep for those you should find the corresponding targets. I would recommend to add a new tag to your tests and then add that to the list of tags to be filtered (I know we have the `dont-run-on-darwin` tag but that is too generic imho).

**Comment by hurryabit** [comment]
@shayne-fletcher Can you please implement @cocreature's suggestion for an interim improvement of the situation?

**Comment by shayne-fletcher** [comment]
PR https://github.com/digital-asset/daml/issues/4483 has landed and PR https://github.com/digital-asset/daml/pull/5550 switches build-and-lint-test to use it. Accordingly, the test has been re-enabled on macOS.  We do now however go far yet as to letting the sandbox and json-api pick their own ports and mark the tests non-exclusive.
