### ISSUE TITLE
Split the Sandbox Bazel package into multiple Bazel packages and Maven artifacts.

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#5399]
Right now, the Sandbox package actually contains multiple components:

- the index
- the Ledger API Server
- the Indexer
- participant configuration classes
- in-memory package management
- the Sandbox itself

Splitting this into different Bazel packages and Maven artifacts would provide a couple of advantages, namely fewer dependencies for packages such as _kvutils_ and the DAML Ledger Integration Kit, and faster compile times when developing.

**Comment by gerolf-da** [comment]
This split has mostly been done now, therefore closing this issue.
