### ISSUE TITLE
Functional tests flake with `Key: entityId1, Already exists in the store` when no such key should be present

### ISSUE THREAD

**Issue by raphael-speyer-da** [digital-asset/daml#54]
We get an occasional error where a functional test complains that a key is already present in the value store, when it should not be.

The value was being set in a "CAPTURE" of an egress message, during the execution of the XmlMessageComparator.

The test failure can be seen under the "Functional Test 0" step on https://ci2.da-int.net/blue/organizations/jenkins/spider%2Fsolution%2Fbuild/detail/PR-1637/4/pipeline/34

and the feature test is 
https://github.com/DACH-NY/solution-spider/blob/fac022c71f90a7c968640a05b89da537b9713bc8/func-test/src/test/resources/features/Entity%20and%20Actor%20Master/Entity%20Management/Remaining%20Roles%20and%20Relationships.feature#L882

**Comment by cocreature** [comment]
Given that this hasn’t come up in months, I’m closing this. If this comes up again, feel free to reopen.
