### ISSUE TITLE
Release LF and API Proto files in Github Releases alongside the SDK

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#5403]
We want to stop releasing to Bintray so the Protos need to go somewhere else. The preferred solution is a zip file on GitHub releases.

**Comment by bame-da** [comment]
@cocreature you may want to grep for Bintray references in the docs. I found a relevant one here by chance: https://docs.daml.com/app-dev/grpc/index.html#getting-started

**Comment by cocreature** [comment]
This has been fixed and I made a snapshot release to test it.
