### ISSUE TITLE
Improve the throughput of kvutils and Sandbox.

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#5425]
Currently, kvutils (and by extension Sandbox) are bottlenecked in a few areas. We now have the metrics in place to figure out what's going on. It's time to fix them.

This issue serves as a single point to track the various efforts in improving kvutils performance.

**Comment by cocreature** [comment]
@SamirTalwar-DA randomly stumbled upon this, does this still have any meaning or can we close it?

**Comment by SamirTalwar-DA** [comment]
Purge.
