### ISSUE TITLE
Support for streams in UniversalArchiveReader

### ISSUE THREAD

**Issue by gleber-da** [digital-asset/daml#547]
Currently `UniversalArchiveReader` supports only reading from `File` objects. In some cases - e.g. when reading DARs from resources embedded in jars - this is not suitable.

As mentioned in #452 there are many classes able to read DARs and DALFs, some from files and some from streams, but not a single one can do both.

**Comment by leo-da** [comment]
@francesco-da @bitonic please prioritize.
Don't know how easy it is to implement stream support for DARs. There is `java.util.zip.ZipInputStream` though: https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipInputStream.html

**Comment by leo-da** [comment]
@gleber-da  Is that nice to have or do you really need `UniversalArhiveReader` to support streams? What is the use case that you are trying to automate with that?

**Comment by gleber-da** [comment]
It will help to make this code less clunky:
https://github.com/digital-asset/daml/blob/eb23a846511f6d0b4a6a1b7329b1ba61daa6f5d3/ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/LedgerApiTestTool.scala#L125
ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/LedgerApiTestTool.scala:125

The tool is bundling a set of DAR files as resources. Currently I have to copy the file out of a resource world into a temporary file on disk and consume it afterwards. I'd prefer to consume it immediately as a stream of a resource
