### ISSUE TITLE
Incremental rebuilds in "daml build"

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#550]
At the moment we rebuild projects from scratch everytime in "daml build". We should fix this and only rebuild parts that have changed. That requires persisting some information to disk between runs.

**Comment by fmota-da** [comment]
This makes sense to me. Keeping build artifacts in a .daml or .daml-build folder (or something) in the project path is a common pattern for build tools.

**Comment by neil-da** [comment]
Even if we just didn't do any building if nothing had changed that would provide some initial value.

Certain irony is that our entire thing is based around a build system...

**Comment by hurryabit** [comment]
We have `--incremental` now.
