### ISSUE TITLE
ConfigManagementService.SetTimeModel internal error

### ISSUE THREAD

**Issue by tristan-da** [digital-asset/daml#5512]
The endpoint `ConfigManagementService.SetTimeModel` reports in internal error:

`Task scheduled with [1546400756] seconds delay, which is too far in future, maximum delay is [21474835] seconds`

Observed in `0.13.56-snapshot.20200408.3877.0.1ddcd3c0` on both `sandbox` and `sandbox-classic`.

The number `1546400756` matches the `maximum_record_time` supplied which suggest that this is being treated as a relative offset rather than an absolute offset as it was previously (i.e. in `0.13.55` and before).

```
  // Deadline for the configuration change after which the change is rejected.
  google.protobuf.Timestamp maximum_record_time = 2;
```

**Comment by gerolf-da** [comment]
@tristan-da: Are you running sandbox with `--static-time` and supplying the current wall-clock time as `maximum_record_time` by any chance?

**Comment by tristan-da** [comment]
@gerolf-da That is correct.  I can made it work by using a timestamp shortly after unix epoch as the value of `maximum_record_time`. 

Arguably the new behaviour is more sensible than the old behaviour (prior SDKs seems happy with any arbitrary timestamp into the future, perhaps they simply ignored it?) and so I will close this issue.

**Comment by gerolf-da** [comment]
Thanks for the confirmation.
