### ISSUE TITLE
JS Codegen: only recompile / regenerate packages that have changed

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#5530]
When I run `daml codegen js` it generates and compiles all packages, including the standard library dependencies, which usually don't change. It would speed up the step massively, if after an initial compilation only my own project gets regenerated and recompiled. This would make the combined DAML and UI development workflow a lot faster and convenient.

**Comment by cocreature** [comment]
I took a brief look at whether we can just emit `tsconfig.json` files with `incremental: true` and sadly that doesn’t really seem to be useful. That only incrementalizes typechecking but not parsing and binding. While this helps a tiny bit, TypeScript still spends about 0.5-1s per package just doing parsing and binding (which seems ridiculous but that’s a separate discussion). So overall this just doesn’t improve thing significantly and we will have to make that incremental ourselves which has the benefit that we can also incrementalize generating the packages (although that seems to be sufficiently fast).

**Comment by cocreature** [comment]
I’ve merged a PR yesterday that makes the JS codegen _significantly_ faster (basically the whole `building` stuff is gone and it only does the `generating` step). On my machine this is roughly a 40x speedup from 20-25s to ~0.5s on the GSG. That seems fast enough that doing things incrementally is not worth it atm so I’m closing this. If you still have a project where the codegen is super slow, I’m happy to take a look at it.
