### ISSUE TITLE
Document metrics

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#5573]
Metrics are currently not documented.

It would probably make sense to collect all metrics exposed by component of the Ledger API server and DAML-on-SQL, including those exposed by underlying components (like HikariCP) and document them.

**Comment by SamirTalwar-DA** [comment]
Agreed. And while we're at it, we should probably make sure they live in sensible places. Right now you can't push more than one set of metrics to a Graphite server because they'll clobber each other. Perhaps using the participant ID would help.

**Comment by GeorgSchneider** [comment]
And while at it, also document the ones exposed by the JSON API service (if any). Danke ;)

**Comment by stefanobaghino-da** [comment]
> And while at it, also document the ones exposed by the JSON API service (if any).

There are none.
