### ISSUE TITLE
Auto completion feature of daml assistant introduced in 0.13.52 not working in 0.13.55.

### ISSUE THREAD

**Issue by Nandansv** [digital-asset/daml#5582]
As part of https://docs.daml.com/support/release-notes.html#daml-assistant , there is an auto completion feature mentioned.
**Ex:** daml ledger upl-_TAB_- <br>  **Expected :** will complete to daml ledger upload-dar. <br> 
But, when i tried this feature in 0.13.55 , its not working in my windows machine.

**Comment by cocreature** [comment]
The auto completion only works for bash and zsh. It does not work for Powershell which you are probably using on Windows.

**Comment by Nandansv** [comment]
@cocreature  I don't see that information on documentation site . So, tried it.

**Comment by cocreature** [comment]
Terminal completions are documented at https://docs.daml.com/tools/assistant.html#terminal-command-completion which mentions that they are only for bash and zsh.

**Comment by Nandansv** [comment]
> Terminal completions are documented at https://docs.daml.com/tools/assistant.html#terminal-command-completion which mentions that they are only for bash and zsh.

Thank You @cocreature .
