### ISSUE TITLE
Archived contracts showing up on JSON-API query from a ledger migrated from pre-1.0.0

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#5659]
*Scenario:*

Ledger was running on sandbox classic with postgres, upgraded from 0.13.55 to 1.0.0 on sandbox classic.
`/v1/query`  returning contract that has been archived before the upgrade. Using navigator these contract are shown inside include archived.

**Comment by leo-da** [comment]
@lima-da are you running JSON-API with PostreSQL index enabled?

**Comment by leo-da** [comment]
@lima-da

1. what about the contracts that were archived after the upgrade? Are you also receiving those?
2. does this affect only one specific template or you see multiple archived contracts from different templates?
3. can you also attach the DAML for the contract template that was archived, but returned by `/v1/query` after the upgrade.

**Comment by lima-da** [comment]
@leo-da 
1. after upgrade new contracts are acting fine, create/archive are normal for new contract with new contractId
2. I only tried `asset.dar` from quickstart, but I think it will reproduce with other contracts
3. it's from quickstart Main:Asset

**Comment by lima-da** [comment]
@leo-da  It's running without json api postgres index enabled

**Comment by leo-da** [comment]
this issue is blocking DABL upgrade, bumping up the priority.

**Comment by leo-da** [comment]
1. DABL sandbox DB has 3 contracts that were created and archived on SDK 0.13.55
here are the contracts:
> select * from contracts where id in ('#39:0', '#42:0', '#43:0')

<table border="1"><tr BGCOLOR="#CCCCFF"><th>id</th><th>transaction_id</th><th>workflow_id</th><th>package_id</th><th>name</th><th>create_offset</th><th>archive_offset</th><th>key</th><th>create_event_id</th></tr>
<tr><td>#43:0</td><td>43</td><td>&lt;null&gt;</td><td>b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe</td><td>Main:Asset</td><td>00  00  00  00  00  00  00  2b  </td><td>00  00  00  00  00  00  00  32  </td><td>&lt;null&gt;</td><td>#43:0</td></tr>
<tr><td>#39:0</td><td>39</td><td>&lt;null&gt;</td><td>b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe</td><td>Main:Asset</td><td>00  00  00  00  00  00  00  27  </td><td>00  00  00  00  00  00  00  39  </td><td>&lt;null&gt;</td><td>#39:0</td></tr>
<tr><td>#42:0</td><td>42</td><td>&lt;null&gt;</td><td>b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe</td><td>Main:Asset</td><td>00  00  00  00  00  00  00  2a  </td><td>00  00  00  00  00  00  00  35  </td><td>&lt;null&gt;</td><td>#42:0</td></tr>
</table>

Note that `archive_offset` is not null, so the contracts have been archived.

1. Switching to sandbox-classic on SDK 1.0.0

2. JSON API calls `com.daml.ledger.client.services.acs.ActiveContractSetClient#getActiveContracts` and it gets the following `GetActiveContractsResponse`s in the stream:

15:46:22.456 [http-json-ledger-api-akka.actor.default-dispatcher-6] DEBUG com.daml.http.LedgerClientJwt$ - getActiveContracts: GetActiveContractsResponse(0000000000000027,,Vector(CreatedEvent(#39:0,#39:0,Some(Identifier(b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe,Main,Asset)),None,Some(Record(Some(Identifier(b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe,Main,Asset)),Vector(RecordField(issuer,Some(Value(Party(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e)))), RecordField(owner,Some(Value(Party(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e)))), RecordField(name,Some(Value(Text(AAA))))))),Vector(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e),Vector(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e),Vector(),Some())),None)
15:46:22.457 [http-json-ledger-api-akka.actor.default-dispatcher-6] DEBUG com.daml.http.LedgerClientJwt$ - getActiveContracts: GetActiveContractsResponse(000000000000002a,,Vector(CreatedEvent(#42:0,#42:0,Some(Identifier(b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe,Main,Asset)),None,Some(Record(Some(Identifier(b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe,Main,Asset)),Vector(RecordField(issuer,Some(Value(Party(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e)))), RecordField(owner,Some(Value(Party(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e)))), RecordField(name,Some(Value(Text(AAA))))))),Vector(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e),Vector(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e),Vector(),Some())),None)
15:46:22.458 [http-json-ledger-api-akka.actor.default-dispatcher-6] DEBUG com.daml.http.LedgerClientJwt$ - getActiveContracts: GetActiveContractsResponse(000000000000002b,,Vector(CreatedEvent(#43:0,#43:0,Some(Identifier(b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe,Main,Asset)),None,Some(Record(Some(Identifier(b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe,Main,Asset)),Vector(RecordField(issuer,Some(Value(Party(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e)))), RecordField(owner,Some(Value(Party(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e)))), RecordField(name,Some(Value(Text(AAA))))))),Vector(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e),Vector(ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e),Vector(),Some())),None)
15:46:22.458 [http-json-ledger-api-akka.actor.default-dispatcher-6] DEBUG com.daml.http.LedgerClientJwt$ - getActiveContracts: GetActiveContractsResponse(0000000000000047,,Vector(),None)

4. the 2nd field in the `CreatedEvent` is `contractId`:
```
final case class CreatedEvent(val eventId : scala.Predef.String, val contractId : scala.Predef.String...
```

5. Question: why are we are receiving archived contracts in the ACS stream: `#39:0`, `#42:0` and `#43:0`.

**Comment by stefanobaghino-da** [comment]
The active contract service is served by the `participant_events` table: the [queries](https://github.com/digital-asset/daml/blob/0f75bf3fde55c45379ceb27303262fbebb1484dd/ledger/sandbox/src/main/scala/com/digitalasset/platform/store/dao/events/EventsTableFlatEventsRangeQueries.scala#L195) collects create events for contract that have not been archived and serves them.
This is a recent addition and was first introduced by [this commit](https://github.com/digital-asset/daml/commit/e2cab1c1628194adac3ff3f9c62f9d41804c612c) and released as part of version `v0.13.56-snapshot.20200404.3816.0.30f2c742`.
This seems to be a possible issue with the [migration](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/db/migration/postgres/V25__Backfill_Participant_Events.scala).

@lima-da what's the status of the `flyway_schema_history` table after the migration?

**Comment by leo-da** [comment]
> select * from flyway_schema_history


installed_rank | version | description | type | script | checksum | installed_by | installed_on | execution_time | success
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | Init | SQL | V1__Init.sql | -72965523 | postgres | 2020-04-22 20:53:16.479029 | 297 | true
2 | 2.0 | Contract divulgence | SQL | V2_0__Contract_divulgence.sql | 1461208192 | postgres | 2020-04-22 20:53:16.82314 | 49 | true
3 | 2.1 | Rebuild Acs | JDBC | db.migration.postgres.V2_1__Rebuild_Acs | <null> | postgres | 2020-04-22 20:53:16.912273 | 52 | true
4 | 3 | Recompute Key Hash | JDBC | db.migration.postgres.V3__Recompute_Key_Hash | <null> | postgres | 2020-04-22 20:53:16.993835 | 25 | true
5 | 4.0 | Add parties | SQL | V4_0__Add_parties.sql | 2091746815 | postgres | 2020-04-22 20:53:17.043624 | 44 | true
6 | 4.1 | Collect Parties | JDBC | db.migration.postgres.V4_1__Collect_Parties | <null> | postgres | 2020-04-22 20:53:17.110682 | 18 | true
7 | 5 | Add packages | SQL | V5__Add_packages.sql | 1089030748 | postgres | 2020-04-22 20:53:17.165935 | 32 | true
8 | 6 | External Ledger Offset | SQL | V6__External_Ledger_Offset.sql | 1642074148 | postgres | 2020-04-22 20:53:17.221672 | 7 | true
9 | 7 | Command deduplication | SQL | V7__Command_deduplication.sql | 478192496 | postgres | 2020-04-22 20:53:17.251705 | 45 | true
10 | 8 | Contract Divulgence | SQL | V8__Contract_Divulgence.sql | -1984400579 | postgres | 2020-04-22 20:53:17.329792 | 47 | true
11 | 9 | Contract Divulgence | SQL | V9__Contract_Divulgence.sql | -39708021 | postgres | 2020-04-22 20:53:17.399061 | 46 | true
12 | 10.0 | Extract Event Data | SQL | V10_0__Extract_Event_Data.sql | 1741793687 | postgres | 2020-04-22 20:53:17.493105 | 72 | true
13 | 10.1 | Populate Event Data | JDBC | db.migration.postgres.V10_1__Populate_Event_Data | <null> | postgres | 2020-04-22 20:53:17.597843 | 22 | true
14 | 10.2 | Extract Event Data | SQL | V10_2__Extract_Event_Data.sql | -1727099174 | postgres | 2020-04-22 20:53:17.643328 | 10 | true
15 | 11 | Disclosures index | SQL | V11__Disclosures_index.sql | 2049922513 | postgres | 2020-04-22 20:53:17.694984 | 20 | true
16 | 12 | Add configuration | SQL | V12__Add_configuration.sql | 1064393329 | postgres | 2020-04-22 20:53:17.738093 | 61 | true
17 | 13 | Party entries | SQL | V13__Party_entries.sql | 1719257450 | postgres | 2020-04-22 20:53:17.821485 | 41 | true
18 | 14 | Package entries | SQL | V14__Package_entries.sql | 2024306888 | postgres | 2020-04-22 20:53:17.907928 | 61 | true
19 | 15 | Loosen transaction check | SQL | V15__Loosen_transaction_check.sql | -955389528 | postgres | 2020-04-22 20:53:18.015604 | 32 | true
20 | 16 | Create command completions table | SQL | V16__Create_command_completions_table.sql | 1970730105 | postgres | 2020-04-22 20:53:18.090811 | 45 | true
21 | 17 | Command deduplication | SQL | V17__Command_deduplication.sql | 1107112150 | postgres | 2020-04-22 20:53:18.172541 | 51 | true
22 | 18 | Backfill completions | SQL | V18__Backfill_completions.sql | -1664109353 | postgres | 2020-04-22 20:53:18.273411 | 48 | true
23 | 19 | Fix Completions | SQL | V19__Fix_Completions.sql | 904991759 | postgres | 2020-04-23 12:58:15.943361 | 4 | true
24 | 20 | Events new schema | SQL | V20__Events_new_schema.sql | 1928761158 | postgres | 2020-04-23 12:58:15.967546 | 72 | true
25 | 21 | Stable offsets | SQL | V21__Stable_offsets.sql | 1237032852 | postgres | 2020-04-23 12:58:16.075983 | 266 | true
26 | 22 | Remove maximum record time | SQL | V22__Remove_maximum_record_time.sql | 915980718 | postgres | 2020-04-23 12:58:16.372577 | 5 | true
27 | 23 | Delete checkpoints | SQL | V23__Delete_checkpoints.sql | 1235716342 | postgres | 2020-04-23 12:58:16.396607 | 9 | true
28 | 24 | Stable offsets archival | SQL | V24__Stable_offsets_archival.sql | -1078040150 | postgres | 2020-04-23 12:58:16.412403 | 34 | true
29 | 25 | Backfill Participant Events | JDBC | db.migration.postgres.V25__Backfill_Participant_Events | <null> | postgres | 2020-04-23 12:58:16.464352 | 568 | true
30 | 26.0 | Contracts new schema | SQL | V26_0__Contracts_new_schema.sql | -1230616752 | postgres | 2020-04-23 12:58:17.041823 | 28 | true
31 | 26.1 | Fill create argument | JDBC | db.migration.postgres.V26_1__Fill_create_argument | <null> | postgres | 2020-04-23 12:58:17.074826 | 31 | true
32 | 26.2 | Contract create arg not null | SQL | V26_2__Contract_create_arg_not_null.sql | -1144271682 | postgres | 2020-04-23 12:58:17.112385 | 1 | true
33 | 27 | Events table fixes | SQL | V27__Events_table_fixes.sql | 1347117250 | postgres | 2020-04-23 12:58:17.118872 | 9 | true

**Comment by leo-da** [comment]
> select * from participant_events where contract_id in ('#39:0', '#42:0', '#43:0')


event_id | event_offset | contract_id | transaction_id | ledger_effective_time | node_index | command_id | workflow_id | application_id | submitter | create_argument | create_signatories | create_observers | create_agreement_text | create_consumed_at | create_key_value | exercise_consuming | exercise_choice | exercise_argument | exercise_result | exercise_actors | exercise_child_event_ids | template_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
#50:0 | 00  00  00  00  00  00  00  32 | #43:0 | 50 | 1969-12-31 19:00:00.0 | 0 | 61e3ad4a-783a-4ea2-bf06-ff742964c647 | 30c917a4-e590-4742-9ee1-69a6a2e51213 | rest-adapter | ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e | <null> | <null> | <null> | <null> | <null> | <null> | true | Give | 0a  01  31  12  94  01  0a  91  01  0a  4e  0a  40  62  33  34  38  38  61  39  30  34  31  62  62  37  39  39  34  65  62  39  65  63  36  32  39  63  62  37  30  30  65  37  38  63  31  63  36  31  39  65  39  62  65  37  64  37  31  31  66  66  32  32  62  30  63  61  64  66  63  63  65  33  66  62  65  12  04  4d  61  69  6e  1a  04  47  69  76  65  12  3f  0a  08  6e  65  77  4f  77  6e  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  32  66  33  34  39  65  36  61  2d  66  35  37  34  2d  34  34  32  36  2d  61  38  30  30  2d  64  65  65  38  32  33  39  37  38  35  63  38 | 0a  01  31  12  07  1a  05  23  35  30  3a  31 | {ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e} | {#50:1} | b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe:Main:Asset
#53:0 | 00  00  00  00  00  00  00  35 | #42:0 | 53 | 1969-12-31 19:00:00.0 | 0 | 7eb1a363-a2f1-49d9-a133-f336f143e6e6 | c8a6abc3-7e99-4bb6-83a9-647cb662a7d3 | rest-adapter | ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e | <null> | <null> | <null> | <null> | <null> | <null> | true | Archive | 0a  01  31  12  67  0a  65  0a  63  0a  40  38  65  62  66  63  39  35  64  30  63  34  64  65  35  65  32  31  37  37  37  36  37  37  64  33  30  65  61  61  65  32  62  34  38  36  63  38  30  66  66  31  35  31  39  35  62  61  62  33  39  31  37  30  65  36  61  36  63  37  61  39  31  63  64  12  02  44  41  12  08  49  6e  74  65  72  6e  61  6c  12  08  54  65  6d  70  6c  61  74  65  1a  07  41  72  63  68  69  76  65 | 0a  01  31  12  02  62  00 | {ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e} | {} | b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe:Main:Asset
#57:0 | 00  00  00  00  00  00  00  39 | #39:0 | 57 | 1969-12-31 19:00:00.0 | 0 | 1bc41a89-dcf4-4b56-aa9b-02a3d68b4be0 | 6669cbce-83db-4863-826f-c1f470daf352 | rest-adapter | ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e | <null> | <null> | <null> | <null> | <null> | <null> | true | Archive | 0a  01  31  12  67  0a  65  0a  63  0a  40  38  65  62  66  63  39  35  64  30  63  34  64  65  35  65  32  31  37  37  37  36  37  37  64  33  30  65  61  61  65  32  62  34  38  36  63  38  30  66  66  31  35  31  39  35  62  61  62  33  39  31  37  30  65  36  61  36  63  37  61  39  31  63  64  12  02  44  41  12  08  49  6e  74  65  72  6e  61  6c  12  08  54  65  6d  70  6c  61  74  65  1a  07  41  72  63  68  69  76  65 | 0a  01  31  12  02  62  00 | {ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e} | {} | b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe:Main:Asset
#39:0 | 00  00  00  00  00  00  00  27 | #39:0 | 39 | 1969-12-31 19:00:00.0 | 0 | d6af0fc5-3c6b-4104-a9bf-3f96585cf239 | <null> | localhost/ledger/cqbs5q0d6w7zpk1h | ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e | 0a  01  31  12  e0  01  0a  dd  01  0a  4f  0a  40  62  33  34  38  38  61  39  30  34  31  62  62  37  39  39  34  65  62  39  65  63  36  32  39  63  62  37  30  30  65  37  38  63  31  63  36  31  39  65  39  62  65  37  64  37  31  31  66  66  32  32  62  30  63  61  64  66  63  63  65  33  66  62  65  12  04  4d  61  69  6e  1a  05  41  73  73  65  74  12  3d  0a  06  69  73  73  75  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  35  36  30  36  38  66  65  31  2d  65  34  37  36  2d  34  63  33  63  2d  62  32  38  38  2d  32  62  30  33  62  66  36  62  33  36  30  65  12  3c  0a  05  6f  77  6e  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  35  36  30  36  38  66  65  31  2d  65  34  37  36  2d  34  63  33  63  2d  62  32  38  38  2d  32  62  30  33  62  66  36  62  33  36  30  65  12  0d  0a  04  6e  61  6d  65  12  05  42  03  41  41  41 | {ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e} | {} | <null> | <null> | <null> | <null> | <null> | <null> | <null> | <null> | <null> | b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe:Main:Asset
#43:0 | 00  00  00  00  00  00  00  2b | #43:0 | 43 | 1969-12-31 19:00:00.0 | 0 | 2d1beaf5-deba-44cc-a0bb-ba1688537760 | <null> | localhost/ledger/cqbs5q0d6w7zpk1h | ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e | 0a  01  31  12  e0  01  0a  dd  01  0a  4f  0a  40  62  33  34  38  38  61  39  30  34  31  62  62  37  39  39  34  65  62  39  65  63  36  32  39  63  62  37  30  30  65  37  38  63  31  63  36  31  39  65  39  62  65  37  64  37  31  31  66  66  32  32  62  30  63  61  64  66  63  63  65  33  66  62  65  12  04  4d  61  69  6e  1a  05  41  73  73  65  74  12  3d  0a  06  69  73  73  75  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  35  36  30  36  38  66  65  31  2d  65  34  37  36  2d  34  63  33  63  2d  62  32  38  38  2d  32  62  30  33  62  66  36  62  33  36  30  65  12  3c  0a  05  6f  77  6e  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  35  36  30  36  38  66  65  31  2d  65  34  37  36  2d  34  63  33  63  2d  62  32  38  38  2d  32  62  30  33  62  66  36  62  33  36  30  65  12  0d  0a  04  6e  61  6d  65  12  05  42  03  41  41  41 | {ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e} | {} | <null> | <null> | <null> | <null> | <null> | <null> | <null> | <null> | <null> | b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe:Main:Asset
#42:0 | 00  00  00  00  00  00  00  2a | #42:0 | 42 | 1969-12-31 19:00:00.0 | 0 | 3b518a75-1921-4f16-bc49-1812d259fd6a | <null> | localhost/ledger/cqbs5q0d6w7zpk1h | ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e | 0a  01  31  12  e0  01  0a  dd  01  0a  4f  0a  40  62  33  34  38  38  61  39  30  34  31  62  62  37  39  39  34  65  62  39  65  63  36  32  39  63  62  37  30  30  65  37  38  63  31  63  36  31  39  65  39  62  65  37  64  37  31  31  66  66  32  32  62  30  63  61  64  66  63  63  65  33  66  62  65  12  04  4d  61  69  6e  1a  05  41  73  73  65  74  12  3d  0a  06  69  73  73  75  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  35  36  30  36  38  66  65  31  2d  65  34  37  36  2d  34  63  33  63  2d  62  32  38  38  2d  32  62  30  33  62  66  36  62  33  36  30  65  12  3c  0a  05  6f  77  6e  65  72  12  33  52  31  6c  65  64  67  65  72  2d  70  61  72  74  79  2d  35  36  30  36  38  66  65  31  2d  65  34  37  36  2d  34  63  33  63  2d  62  32  38  38  2d  32  62  30  33  62  66  36  62  33  36  30  65  12  0d  0a  04  6e  61  6d  65  12  05  42  03  41  41  41 | {ledger-party-56068fe1-e476-4c3c-b288-2b03bf6b360e} | {} | <null> | <null> | <null> | <null> | <null> | <null> | <null> | <null> | <null> | b3488a9041bb7994eb9ec629cb700e78c1c619e9be7d711ff22b0cadfcce3fbe:Main:Asset
