### ISSUE TITLE
DAML install fails if /tmp/daml.yaml is not writeable

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#5720]
DAML installer should use a separate temp dir instead to store `/tmp/daml.yaml` .
_Reproduce:_
Alice creates `/tmp/daml.yaml` (e.g. by starting a DAML install and interrupt it). Then Bob cannot do the install DAML until Alice removes the file.
```
$ curl -sSL https://get.daml.com/ | sh
Determining latest SDK version...
Latest SDK version is 1.0.0
Downloading DAML SDK 1.0.0. This may take a while.
######################################################################## 100.0%##O=#  #                                                                      
Extracting SDK release tarball.
daml: daml.yaml is an invalid YAML file
  context: Determining SDK version and path.
  details: 
    path: /tmp/daml.yaml
    internal: YAML exception:
Yaml file not found: /tmp/daml.yaml
FAILED TO INSTALL!
```

**Comment by sofiafaro-da** [comment]
Hi Richard. I've been able to reproduce this on a Mac by creating `daml.yaml` in `/var/folders`. (Mac uses a different location for temporary folders.)

The DAML installer doesn't create or write to any `daml.yaml` file, but it does look for it (and it really shouldn't), and that causes the installation to fail if the file can't be read or its contents are invalid.

I wonder how you got into this situation in the first place. The file must have been placed there separately?

The good news is I know how to fix it.

**Comment by richardkapolnai-da** [comment]
Thanks for the good news! :)

I don't remember exactly why, but I placed a file there as another user. I like to do strange things (living on the edge :) ), so I keep running into strange bugs...

Fun fact: if I change the permissions to chmod 744, I get a different error message (because I provided an invalid daml.yaml just to test this.
```
