### ISSUE TITLE
Cache deserialized contract values

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#5754]
## Overview

When loading contracts for command interpretation/validation, the contract argument is deserialized from protobuf and then decoded into a type usable by the engine.
Investigate whether we can speed up command interpretation by caching deserialized+decoded contract values (in the format directly usable by the engine).

## Details

To avoid cache invalidation issues, only use the cache for immutable data. I.e., use the cache only to look up deserialized contract values, but not to check whether a given contract is active.

Command execution happens during submission (Ledger API submission service) and validation (kvutils transaction submission). The impact of caching on the kvutils side will be investigated separately. This issue is only about investigating the caching on the ledger API side.

## Measurement

- Add a metric that tracks the time spent deserializing and decoding values
- Add a metric measuring the cache miss rate

## References

- [ContractsReader](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/store/dao/events/ContractsReader.scala#L104) - loading contracts for command execution from the index

**Comment by meiersi-da** [comment]
@rautenrieth-da the way I'm reading the intent of this cache is that it will be caching as part of the DAML Engine instance in the format that the DAML Engine uses, *not* the deserialized protobuf values. Is that correct?

**Comment by rautenrieth-da** [comment]
@meiersi-da yes, it should cache the contract value in the format that is directly consumable by the engine (i.e., `com.daml.lf.value.VersionedValue`), eliminating as much deserialization and data transformation as possible. I have updated the issue description.

**Comment by meiersi-da** [comment]
Thank you for the clarification @rautenrieth-da . :pray:

**Comment by rautenrieth-da** [comment]
Note: measurements have shown that out of the total time spent on transaction submission, only 2-3% is spent on contract lookups during DAML execution. This issue has therefore been put on hold in favor of more promising optimizations.
