### ISSUE TITLE
Ports cannot be specified via 'daml start'

### ISSUE THREAD

**Issue by tamaskalcza-da** [digital-asset/daml#5777]
Starting an app with `daml start` neither the sandbox port nor the navigator port can be specified. 

For example:

```shell
daml start --sandbox-option --port=6262
daml start --navigator-option --port=7575
```
Results in `Error: Unknown option --port=6262` or `Error: Unknown option --port=7575` respectively.

As a workaround for the sandbox there is the `--sandbox-port` option. There is no such workaround for the navigator.

**Comment by sofiafaro-da** [comment]
The PR #7401 adds a `--navigator-port` option.
