### ISSUE TITLE
Make equality checks on sum types less slow

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#5785]
Currently, the DAML definition
```haskell
data E = C_1 | C_2 | ... | C_n deriving (Eq)
```
compiles down to DAML-LF looking like
```
def con2tag = \a.
    case a of
        E:C_1 -> 0
        E:C_2 -> 1
        ...
        E:C_n -> n-1
def (==)E = \a b.
    let c = con2tag a
        d = con2tag b
    in EQUAL @Int64 c d
```
Since DAML-LF pattern matching is implemented by a linear search through the patterns, `(==)E` has a runtime complexity of `O(n)`. I've seen codebases with `n > 50`, where this clearly becomes an issue. Ideally, we want `(==)E` to have a runtime cost of `O(1)`.

**Comment by sofiafaro-da** [comment]
#7073 would satisfy this.

**Comment by remyhaemmerle-da** [comment]
subsumed by #5765
