### ISSUE TITLE
Implement SQL-backed participant-state-index

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#581]
This is a backlog item to track the work to provide a SQL-backed implementation of https://github.com/digital-asset/daml/blob/master/ledger/participant-state-index/src/main/scala/com/daml/ledger/participant/state/index/v1/IndexService.scala for production use of a DAML on X server. Expected benefits:
- remove limit of size of DAML ledger by memory of ledger server
- no more index recreation upon restart of ledger server

Tasks to not forget:
- [ ] update docs of DLIK to remove link to this issue and mention the option of using a SQL backed index

FYI: @francesco-da @dajmaki @mziolekda @gleber-da @gaboraranyossy-da

**Comment by gerolf-da** [comment]
Closing as not relevant anymore.
