### ISSUE TITLE
Allow the Inconsistent failure reason to have a reason.

### ISSUE THREAD

**Issue by simonmaxen-da** [digital-asset/daml#5810]
The rejection reason com.daml.ledger.participant.state.v1.RejectionReason.Inconsistent is a case object so does not allow a reason for the inconsistency to be provided (e.g. contract key unavailable).

It should allow a reason to be provided (much like RejectionReason.Disputed).

**Comment by simonmaxen-da** [comment]
Starting

**Comment by simonmaxen-da** [comment]
PR: https://github.com/digital-asset/daml/pull/5815

**Comment by stefanobaghino-da** [comment]
Closed by https://github.com/digital-asset/daml/pull/5815
