### ISSUE TITLE
Make Java Codegen Backend configurable

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#584]
It is currently hardcoded to `com.digitalasset.daml.lf.codegen.backend.java.JavaBackend`
But used to be set through `Conf.backend`. `com.digitalasset.daml.lf.codegen.conf.Conf` has been moved into a separate module `language-support/codegen-common` as part of the #166. So we can re-use the same options parser in both Java and Scala codegens.

This is probably not a high priority. We currently only have one Java Codegen Backend implementation: `com.digitalasset.daml.lf.codegen.backend.java.JavaBackend` and it was actually hardcoded in the `Conf` class. However if we are to support multiple backends this issue will need to be bumped up.

CC @gerolf-da @stefanobaghino-da @nicholassmith-da

**Comment by gerolf-da** [comment]
Closing this issue as we won't be adding multiple backends to java codegen in the foreseeable future.
