### ISSUE TITLE
Read pipeline performance investigation

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#5847]
We want to get a good understanding of the performance characteristics of the read pipeline in the KV stack. The investigation is split into 3 parts:

### 1. Transaction ingestion into the participant database
Owner: @rautenrieth-da 
1. Start Sandbox with a postgres backend
1. Create transactions (~5k)
1. Truncate all tables of the participant schema ( https://github.com/digital-asset/daml/blob/4d606689bbcbdc163c62592df714dbf97d998659/ledger/sandbox/src/main/scala/com/digitalasset/platform/store/dao/JdbcLedgerDao.scala#L995-L1007)
1. Start sandbox with the same database. Now that the ledger tables contain data but the participant doesn't, it will start reading from the ledger and storing the transactions in the participant schema.
1. Observe the metrics related to writing into the participant schema and check for anomalies or whether the performance of just writing the transactions is sufficient.

### 2. Transaction delivery over the Ledger API
Owner: @stefanobaghino-da 
1. Start Sandbox with a postgres backend
1. Create transactions (~5k)
1. Start an application that consumes all transactions
1. Measure the time it takes to stream all transactions to the application
1. Observe the metrics related to reading from the participant database and check for anomalies.

**Comment by shaul-da** [comment]
Is this still open? My understanding is that we've seen ~150 tx/sec on the read pipeline, in which case we can close this investigation

**Comment by rautenrieth-da** [comment]
We have the following data points:
- 60 tx/sec on a lower end laptop for the indexer (take a large existing ledger, let the indexer push data to the index database) when using a moderately complex DAML model with non-trivial transactions
- 150 tx/sec (trivial DAML model) end-to-end performance (submission to completion) when using a trivial DAML model with tiny transactions.

Given these data, we don't expect much gain from optimizing the read pipeline.
