### ISSUE TITLE
DRY ledger-id in create-daml-app 

### ISSUE THREAD

**Issue by lJoublanc** [digital-asset/daml#5857]
At present, the quickstart create-daml-app has the ledger-id specified in three sparate places:

*  in daml.yaml
* in ui/.env
* in ui/src/config.ts

It would be nice if it could be confined to a single location, for maintainability, especially when deploying to third-party (i.e. non-sandbox) ledgers.

**Comment by cocreature** [comment]
I think you might be misunderstanding the setup:
1. The ledger id in `daml.yaml` is only used locally when you run `daml start`.
2. `ui/src/config.ts` looks at `ui/.env` or rather the env var set there.

So if you deploy to a third-party ledger you should only need to change `ui/.env`.

**Comment by lJoublanc** [comment]
Having a second look at this, it seems that `config.ts` reads the environment variable `REACT_APP_LEDGER_ID`, which is specified in `.env`, so the duplication occurs only once, not twice.

Still, would it make sense to parse the daml.yaml file instead? This way it would only have to be set in one place.

**Comment by lJoublanc** [comment]
> I think you might be misunderstanding the setup:
> So if you deploy to a third-party ledger you should only need to change `ui/.env`.

Yes thanks for clarifying @cocreature  - closing issue.
