### ISSUE TITLE
Disentangle scenario interpretation from rest of Speedy

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#5898]
The only reason why we have `KCatch` and all the complexity around it is because of the way we've implemented `submitMustFail` and scenario interpretation in general. IMO, this adds a fair bit of cognitive complexity that could be avoided.

The main problem I see is that we currently run one machine for the entire scenario including all the submissions. I've taken a slightly simpler approach in Rusty where I start a new machine (which share some caches) for every `submit` and `submitMustFail`. This makes detecting if a submission has failed fairly simple and doesn't require anything resembling `KCatch`. I would argue it's also closer to what happens in production where each submission runs in its own machine.

**Comment by garyverhaegen-da** [comment]
As I understand things (very little, from afar), this would change the way the benchmark runs to make it closer to production. Does this invalidate the current baseline for perf improvement measurements?

**Comment by hurryabit** [comment]
It might invalidate the baseline for performance but I can't tell yet. I'll do benchmarks for this change once it has happened and this will probably tell us if we changed performance.

**Comment by cocreature** [comment]
The change proposed here is roughly how DAML Script in DAML Studio works. I don’t think spending our time on scenarios is particularly useful at this point so I recommend closing this but I’ll leave it up to @hurryabit

**Comment by hurryabit** [comment]
We will most likely need to clean up things for exception handling as well. I would really like to get to a state where I fully understand how control flows through the engine. Thus, I'll leave this ticket open.

**Comment by cocreature** [comment]
split it up
