### ISSUE TITLE
Release source JARs for Scala targets.

### ISSUE THREAD

**Issue by nicholassmith-da** [digital-asset/daml#590]
Currently only Java targets have additional source JARs published. It is desireable to also publish the sources for the Scala targets.

**Comment by nicholassmith-da** [comment]
The Bazel java rules the source JAR is an _implicit output file_ added by the `java_library` rule. Note  that these targets/outputs do not show up in normal Bazel queries.
Example target would be: `//language-support/java/bindings:libbindings-java-src.jar`
For Scala the source JAR target is explicitly defined in the `bazel_tools/scala.bzl`  with a `-src` suffix i.e: `//language-support/scala/bindings:bindings_src`

**Comment by gerolf-da** [comment]
Closing this because we now create scala source jars.
