### ISSUE TITLE
Fetch by key can be authorized by stakeholders

### ISSUE THREAD

**Issue by matthiasS-da** [digital-asset/daml#5902]
The documentation of `fetchByKey` says:

> you also need authorization from one of the maintainers of the key.

https://docs.daml.com/daml/reference/updates.html#fetchbykey

When I test `fetchByKey`, I see that authorization by a stakeholder is sufficient.

```
template Foo
  with
    m : Party
    o : Party
  where
    signatory m
    observer o
    key m : Party
    maintainer key

technical = scenario do
  alice <- getParty "Alice"
  bob <- getParty "Bob"
  
  aliceFooId <- submit alice do create Foo with m = alice, o = bob
  bobFooId <- submit bob do create Foo with m = bob, o = bob

  -- Succeeds as expected
  _ <- submit alice do fetchByKey @Foo alice

  -- FIXME: Succeeds, although bob is not a maintainer.
  _ <- submit bob do fetchByKey @Foo alice
```

Expected behavior: The documentation is in sync with the implementation.

Version: 1.1.0-snapshot.20200430.4057.0.681c862d

**Comment by bame-da** [comment]
It's a documentation issue more than anything else. Closing in favour of #5921
