### ISSUE TITLE
Update contract key docs

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#5921]
The conteact key documentation https://docs.daml.com/daml/reference/contract-keys.html#contract-keys-functions currently has several false statements about authorisation an future plans. This needs to be tidied up.

**Comment by matthiasS-da** [comment]
I see there is a PR to fix the contract keys section, but note that the section on "updates" is also affected. It states that a maintainer must authorize a fetchByKey.

**Comment by bame-da** [comment]
@matthiasS-da  Could you link to the section you mean, please?
