### ISSUE TITLE
Large transactions take disproportionately long in Sandbox

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#5980]
Using the code example from #5947 in `1.2.0-snapshot.20200513.4172.0.021f4af3`, the Script with `CreateN with n = 5000` goes through in a few seconds. However, when I bump `n` to `50000`, the Sandbox keeps spinning at 100% CPU for a  _very_  long time. I don't know how much exactly but it's already at over 10 minutes so several orders of magnitude more, which means something isn't scaling linearly.  One of my thoughts was that it may be a memory issue and the JVM GC is causing massive overhead, but setting `export JAVA_TOOL_OPTIONS="-Xmx2g"` didn't resolve the issue.

**Comment by gerolf-da** [comment]
The cause for this behavior is an unfortunately placed call to `toSet` on a list of events, resulting in an O(n^2) runtime characteristic. This explains why the runtime gets worse with respect to the number of events:

https://github.com/digital-asset/daml/blob/ce98261dbc2250e81ba216e3d6070b5c6460554b/ledger/sandbox/src/main/scala/com/digitalasset/platform/store/dao/events/EventsTable.scala#L158-L162
