### ISSUE TITLE
Create fat-jar for daml-on-sql

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#5988]
Motivation:
* enable productization  of DAML on SQL

Acceptance Criteria:
* for every SDK release a daml-on-sql-.jar is released as a fat-jar to Maven central with the same cmd-line parameters the Sandbox/Next

FYI: @georg-da @dasormeter @gerolf-da @clasoncjDA

**Comment by clasoncjDA** [comment]
@timkemp-dah

**Comment by SamirTalwar-DA** [comment]
I don't believe we publish any far JARs to Maven Central right now, including Sandbox.

I'm all for generating fat JARs for standalone applications (such as Sandbox, DAML-on-SQL, the JSON API, etc.) but I'm not sure Maven Central is the right place to publish them. Perhaps we can upload them as part of the GitHub release?

**Comment by meiersi-da** [comment]
@SamirTalwar : I'm no expert on our release and release hosting infrastructure. I expect any highly-available, internet-accessible repository to work. Can you drive the decision so that we have clarity on the release location?

@timkemp-dah: can you take over from here? I guess a key information for @gerolf-da and @SamirTalwar-DA is what is the target date you have for this?

Moreover, I've heard that in principle you @timkemp-dah could provide a PR once there is clarity on what to publish where?

**Comment by cocreature** [comment]
We could just include it in github releases. We need to be somewhat careful to not make include too much stuff in there since it will get hard to find things for users but I guess one more artifact doesn’t hurt.

**Comment by gerolf-da** [comment]
> but I guess one more artifact doesn’t hurt.

Death by a thousand paper cuts 😈 

How about we publish a docker image instead?
@SamirTalwar-DA: Looks like we already have a docker image for [sandbox classsic](https://github.com/digital-asset/daml/blob/c94f7e16bde84829344b6989756d1357f436ade0/ledger/sandbox/BUILD.bazel#L189-L196). How about we modify that one to ship Sandbox instead? How much effort is it to be able to pass parameters to the dockerfile that are then passed on as CLI parameters for Sandbox?

**Comment by gerolf-da** [comment]
@cocreature: I'm actually warming up to the idea to put the fat-jar on the github releases page.

**Comment by gerolf-da** [comment]
After some further discussion, we will publish a fat jar (bazel target `ledger/sandbox/sandbox-next-binary_deploy.jar`) to the `daml-binaries` GCP bucket.

**Comment by meiersi-da** [comment]
:+1: thanks for the quick turnaround.
