### ISSUE TITLE
Wrong error code for large gRPC messages

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#5993]
The error in #5992 reads

```
RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 13155912
```

However, we use `RESOURCE_EXHAUSTED` elsewhere to signify back pressure. Should we change the error code for this message and others that don't have anything to do with back pressure, and where retrying later has to chance of succeeding?

**Comment by gerolf-da** [comment]
The error is caused by `grpc-java` itself, so there's not a lot we can change:

https://github.com/grpc/grpc-java/blob/6b9cd6d6ed2bbfea41b8605e028ad9aafffd5737/core/src/main/java/io/grpc/internal/MessageDeframer.java#L384-L387
