### ISSUE TITLE
implement sdk release process for monorepo

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#6]
we have to come up with something like the old daml-foundations ci, but for the new repo.

specifically, it should build all the artifacts that an SDK release is made of and upload them to the proper channels.

for jars, the main piece of work required is to come up with the `pom.xml` files programmatically from bazel queries.

it's not entirely clear yet what we need to do for typescript / javascript / docs.

Components we need to release because the `da` assistant will download them:
- [x] `damlc`
- [x] `daml-extension`
- [x] `navigator`
- [x] `extractor`
- [x] `ledger-api-protos`
- [x] `sandbox`
- [x] `quickstart-java`
- [ ] `quickstart-js`
- [x] `sdk`

JVM libraries pulled in via the `pom.xml` in `quickstart-java`:
- [x] `bindings-java`
- [ ] `bindings-js`
- [x] `daml-lf-archive`
- [x] `rs-grpc-bridge`

Other stuff
- [x] Add NOTICE file: https://github.com/DACH-NY/daml/issues/423
- [ ] `damlc.jar`: nice to have, but see #465

**Comment by martin-drhu-da** [comment]
This has worked for a while now.
