### ISSUE TITLE
daml test fails when build option output is set

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#6025]
I'm trying to convince DAML Assistant to put the DAR built to a custom location. I'd like all of these commands working: `daml start`, `daml build` and `daml test`. However, when I add `build-options: ["--output", "target/app.dar"]` to `daml.yaml`, `daml test` starts to fail with `Invalid option `--output'`.

Reproduce with an empty directory and a simple `daml.yaml`:
```
$ find
.
./daml.yaml
./src
$ cat daml.yaml 
sdk-version: 1.1.1
name: skeleton
source: src
version: 0.0.1
dependencies: []
build-options: ["--output", "target/app.dar"]
```

- `daml start` - works like a charm
- `daml start` - best ever
- `daml test` - fails with the error `Invalid option `--output'`
- `daml clean` - partially works, does not clean up `target/app.dar`, only `./.daml`. but this is very minor.

**Comment by cocreature** [comment]
That’s somewhat expected. `daml test` does not have an `--output` option. You should only use `build-options` for things that are shared between `daml build`, the IDE, `daml test`, ….

**Comment by richardkapolnai-da** [comment]
I'm confused, should we be able to put `build-options` in a `daml.yaml` shared between `daml build` and `daml test`? Or should we create different `daml.yaml` for `daml test`?

**Comment by cocreature** [comment]
I would recommend putting anything in `build-options` that is shared and just pass things on the command line that are specific to individual commands.

**Comment by richardkapolnai-da** [comment]
Thanks, it's clear now, so `build-options` should only contain common options. if this is expected, I think we can close this issue, I'll create another one about customizing the output of `daml test`.
