### ISSUE TITLE
Feed daml test with a separately built dar

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#6029]
It's a biased opinion, but to me it would be clearer if `daml test` would only test, and not build and test. Or at least it could have an option to work with a DAR built previously with `daml build`, this would not break existing infrastructure built on current behaviour.

I arrived this when tried to specify the DAR location, possible with `daml build`, but impossible with `daml test`.

**Comment by cocreature** [comment]
Yeah this has come up a couple of times and it is how `daml test-script` works. I fully agree that it would be a better solution but I think our time is better spent on making DAML Script work in the IDE so that there is no reason to prefer `daml test` over `daml test-script`.

**Comment by richardkapolnai-da** [comment]
Is there a plan to support testing triggers from a script too?

**Comment by cocreature** [comment]
> Is there a plan to support testing triggers from a script too?

Good point, wasn’t on my list up until now but I’ll make sure we add it. The only ties from trigger testing to scenarios atm is a call to `fetch` so you only have to pass in the contract id instead of the contract id + the data.

**Comment by richardkapolnai-da** [comment]
Sounds promising! than as far as I understand, `daml test` will be obsoleted, so let's close this too :)
Feel free to reopen if you see value keeping this.

**Comment by cocreature** [comment]
> Sounds promising! than as far as I understand, `daml test` will be obsoleted

Just to be clear, I don’t expect this to happen anytime soon and even if we get script to the point where it can replace all scenario usecases, we will keep it around for quite a while. But if we spent effort there, I’d rather spent it on getting us to the point where you don’t have to switch between script and scenarios than on improving scenarios which can never cover all script use cases.
