### ISSUE TITLE
Navigator: sorting by timestamp has no effect

### ISSUE THREAD

**Issue by vivd-da** [digital-asset/daml#6065]
Please see screenshots:

Descending:
![nav_time_desc](https://user-images.githubusercontent.com/33839227/82537931-cd232200-9b42-11ea-9a15-6dc927e3076f.png)

Ascending:
![nav_time_asc](https://user-images.githubusercontent.com/33839227/82537933-cdbbb880-9b42-11ea-92fc-9d80eedc75c3.png)

This is the same behaviour whether "Include archived" is ticked or not.

Version: 1.0.1
Application ID: Navigator-a177bb9a-f876-4a23-a03b-b6fa3db8eab0

Thanks.

**Comment by vivd-da** [comment]
Also, if we can drag the field width to widen the columns, that would be awesome too :-)

**Comment by shaul-da** [comment]
+1 on this issue
This is pretty important when demoing because sorted by Time is the way to explain the event log

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
