### ISSUE TITLE
Give instructions on stopping process in da status

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#609]
When running the da command and if there are previously running processes (like a sandbox or a navigator), you get a nice indication of this.  However, you are not told how to stop them.

Enhancement -- include in this message, 

"To stop these processes: 

sandbox
`da stop sandbox` 

navigator
`da stop navigator`

stop all processes
`da stop`
"

```example-fpml-clearing-java/ (master✗) $ da                                                                                                                                                   
Welcome to the SDK Assistant.
You are currently in the project 'fpml-clearing-demo' (/Users/brianhealey/lib-message-integration/example-fpml-clearing-java).
The following processes are running:

Sandbox ledger server
/Users/brianhealey/lib-message-integration/example-fpml-clearing-java/daml/Main.daml
with scenario Main:init and binding to port 7600
```

**Comment by neil-da** [comment]
The da assistant dies in a week or so. I believe `daml` gets this right, @cocreature ?

**Comment by cocreature** [comment]
Yep, `daml` doesn’t have `stop` or `status` commands. Instead `start` keeps running until you kill it (e.g. by pressing Ctrl-C) and at that point it will also shut down navigator and sandbox. Closing since I don’t think it makes sense to fix it in the old assistant at this point.

**Comment by cocreature** [comment]
Yep, `daml` doesn’t have `stop` or `status` commands. Instead `start` keeps running until you kill it (e.g. by pressing Ctrl-C) and at that point it will also shut down navigator and sandbox. Closing since I don’t think it makes sense to fix it in the old assistant at this point.

**Comment by dasormeter** [comment]
@cocreature is there a case you would want to set new daml assistant to run in background, or must it always stay in foreground and at the moment you kill session it kills all processes?

**Comment by cocreature** [comment]
I don’t see a usecase for that and we are deliberately trying to get out of the business of being a process manager so someone would have to make a very strong case for this to be added back.

**Comment by neil-da** [comment]
When I was doing CDM work, we had three processes you had to start. Nanobots, something else and da start/stop. All but one stayed in the foreground, so I think making it go to the background adds little use.

**Comment by dasormeter** [comment]
Okay I will look at the user experience with new DAML assistant and if anything there is untoward, we can track through a new issue.
