### ISSUE TITLE
Automatically allocate parties in Sandbox with daml start

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#6099]
When specifying a list of parties in `daml.yaml`, `daml start` should allocate these in the Sandbox. This is currently not the case and causes problems when running Sandbox with `--implicit-party-allocation=no`.

**Comment by cocreature** [comment]
I’m not a huge fan of the whole `parties` field in `daml.yaml`. You can already achieve what you want by having an init script that allocates the parties.

**Comment by bame-da** [comment]
Moving away from that is an option, but would require more work overall.

**Comment by cocreature** [comment]
It’s only more work if you don’t have an init-script already. Otherwise moving the lines from your daml.yaml to your script is almost trivial and even if you do not have the script it’s easy enough to create it. The reason why I prefer the script solution over daml.yaml is that it makes it much easier to reproduce the behavior from `daml start` if you run things separately. Otherwise you have to parse your daml.yaml and iterate over it calling `daml ledger allocate-party` in bash or something like that.

**Comment by bame-da** [comment]
I meant more work on our side. We'd need to change our examples to use init scripts, rewire the assistant to start the Navigator after the init script and query for available parties, and add backwards compatibility.

**Comment by cocreature** [comment]
> rewire the assistant to start the Navigator after the init script and query for available parties

True but that just means using `daml ledger navigator` and changing the order. The fact that we have both `daml ledger navigator` and `daml navigator` is already crappy imho

**Comment by hurryabit** [comment]
@cocreature Is that still an issue after your recent changes to the navigator?

**Comment by cocreature** [comment]
sort off, we still need to kill `daml ledger navigator` and rewire our examples but I think the requested feature here makes no sense anymore.

**Comment by hurryabit** [comment]
@cocreature What exactly do you mean by killing `daml ledger navigator`? Just remove the command and point everything to `daml navigator` instead?

@robin-da Is that something you could take over?

**Comment by cocreature** [comment]
No don’t remove it, make it a strict superset and then potentially deprecate it.

Specifically there are two things we need to do:
1. We need to pick up ledger host and port from `daml.yaml`. At least for now, I’m fine with keeping that in the wrapper.
2. `daml ledger navigator` will also use allocated parties if you have parties specified in `daml.yaml`. To be backwards compatible we should add a flag to navigator to do the same and then `daml ledger navigator` just boils down to calling `daml navigator server ${host} ${port} --please-come-up-with-a-better-flag-name-to-force-party-management`

**Comment by robin-da** [comment]
@hurryabit I'll look into it.

**Comment by robin-da** [comment]
@cocreature  should the `host` and `port` arguments to `daml navigator` become optional and overwritten by the values in `daml.yaml` (and error if none were set)?

**Comment by cocreature** [comment]
> @cocreature should the `host` and `port` arguments to `daml navigator` become optional and overwritten by the values in `daml.yaml` (and error if none were set)?

Yeah I think that would be nice but as a first step I would stick to just passing them from `daml ledger navigator`.
