### ISSUE TITLE
Any wart has too many false positives in Scala code

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#6116]
The `Any` wart has multiple false positives that are pervasive through our code. Therefore, we should disable it.

The false positives fall into a few categories.

The first category is caused by various aspects of Scalatest. The ironic outcome of this is that we substitute safe constructs like `xs shouldBe empty` for unsafe constructs like `xs shouldBe 'empty` because the latter don't trigger the `Any` wart, even though the _former_ are well-typed and the latter are not.

The second category is wartremover/wartremover#463. This is the most pervasive, and unlike the prior category can't be fixed by simply limiting the wart to main code. In fact, even code that merely _infers_ the values of higher-kinded type parameters can trigger `Any`.

The third category is the standard collections `view` construct. Again, we use it as a refactoring-safe, 2.13-safe variant of `iterator`, as in #6075. But since `view` triggers `Any` in some cases but `iterator` does not, we ironically choose the latter, less safe construct.

I have confirmed that Wartremover 2.4.8 does not fix any of these categories of false positives.

I suspect that the vast majority, albeit not all, of the 229 `warts.Any` suppressions in our codebase fall into one of these three categories. I don't suggest disabling a safety-enhancing check lightly, but make an exception in this case, as we are counterproductively drawn to less type-safe constructs as described above, as things stand. The goal is to allow us to use more safe constructs conveniently, not to expand our usage of unsafe Scala constructs (i.e. uses of `Any` "in anger" that are actually unsafe).

I _only_ suggest disabling the `Any` wart. The other warts are quite good.

**Comment by stefanobaghino-da** [comment]
I agree with your take. Do you think there are advantages that we may lose by dropping this? Do you see ways we can retain those without necessarily using the `Any` wart?

**Comment by SamirTalwar-DA** [comment]
I agree with this. I don’t like disabling warnings but I’m one of the people who ends up writing less safe code to make this checker happy.

**Comment by S11001001** [comment]
> Do you think there are advantages that we may lose by dropping this?

Yes, for sure.

> Do you see ways we can retain those without necessarily using the Any wart?

Not at all.
