### ISSUE TITLE
Add a new project template: `quickstart-scala` to DAML SDK Assistant

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#614]
```
$ daml-head new --help
Usage: daml-helper new (--list | TARGET_PATH [TEMPLATE])

Available options:
  --list                   List the available project templates.
  TARGET_PATH              Path where the new project should be located
  TEMPLATE                 Name of the template used to create the project
                           (default: quickstart-java)
  -h,--help                Show this help text

$ daml-head new --list
The following templates are available:
  quickstart-java
```

See: #110, #585
Blocked on: #615

CC @S11001001 @gerolf-da @stefanobaghino-da @nicholassmith-da

**Comment by cocreature** [comment]
Let me give a brief description of how things currently work (both for the old and the new assistant): 

- The assistant is completely independent of the codegen. It neither downloads or calls the codegen.
- For the quickstart example, the [pom.xml](https://github.com/digital-asset/daml/blob/2b3c4e76bb5662e5e139c625755a388c79455c49/docs/source/getting-started/quickstart/template-root/pom.xml#L86) is setup such that `mvn compile` will call the codegen and compile the resulting Java code.

Are you proposing that we switch away completely from integrating the codegen into Maven? Should we keep the Maven integration but also add a `codegen` command to the new assistant?

**Comment by leo-da** [comment]
@cocreature please correct me if I am wrong... The p `pom.xml` is packaged with DAML Assistant, right? The name of the module `daml-quickstart-java` is hardcoded in the `pom.xml`.

I will need to think about this, and probably split this story into 2 ore more.

*The easiest solution would be:*
1.  Add a new optional argument: `--scala | --java` to the command that creates a new DAML project: `da new`, defaulting to java
2. Package an sbt project (build.sbt + project/) in DAML Assistant
3. Modify `da new` to create either Java (pom.xml) or Scala (build.dbt + project/)

*The right solution:*
I need to think about this a little bit :)

**Comment by cocreature** [comment]
Right the quickstart example is packaged with the assistant but to the assistant it is just an opaque tarball that it copies to some location. `daml new` already accepts an optional second argument to specify a different template (ofc at the moment we only bundle one template so there is little reason to use that).

**Comment by leo-da** [comment]
```
leos@localhost:~/Projects/grokking-daml
$ /home/leos/.daml-head/bin/daml-head new --list
The following templates are available:
  quickstart-java
```
To add a new template, see: ` //release:sdk-release-tarball`

**Comment by bethaitman** [comment]
@leo-da - do we want to provide this as a template? Couldn't we just publish it in its own repo, like the Java bindings examples? https://github.com/digital-asset/ex-java-bindings
