### ISSUE TITLE
feedback in ledger server logs confirming a package has successfully uploaded

### ISSUE THREAD

**Issue by piyushbedi-da** [digital-asset/daml#6144]
@gerolf-da and @stefanobaghino-da 
Can a log entry be added in the Ledger Server to confirm that a package has successfully been uploaded and is available to use?
Can the log entry include the package filename, package ID and date/time?

At present the Ledger Server doesn't provide any feedback once a package has successfully been uploaded using the Ledger API PackageManagementService.

**Comment by stefanobaghino-da** [comment]
The filename cannot be logged as the package is passed to the API server as a stream of bytes. The PR I'm opening will log the package identifier (i.e. it's hash) and the logger framework will take care of the timestamp.
