### ISSUE TITLE
daml.git contains many DCO non-conformant commits

### ISSUE THREAD

**Issue by ryjones** [digital-asset/daml#616]
If you want a list of commit hashes, here is how you create the list:
https://gist.github.com/ryjones/07ac650dcc5e83c91e8308ec98bacda4

daml ry$ lftools dco check|grep ^ERROR |wc -l
   10870

[daml-no-dco.txt](https://github.com/digital-asset/daml/files/3095886/daml-no-dco.txt)

**Comment by ryjones** [comment]
if the plan is to bring this repo into Hyperledger, there will need to be a squash or a lot of git filter-branch to fix things up.

**Comment by neil-da** [comment]
Thanks for letting us know @ryjones - there's no plan to bring this repo into Hyperledger in the near future, but given it's a possibility one day, we might as well start following any conventions that make sense. Could you provide a link to the guidelines, which I guess might be more extensive than just missing Signed-Off? I'd also be keen to see the reasoning behind things like a requirement for Signed-Off - thus far we've gone for CLA agreements with all authors and at least one reviewer and squashed merges - meaning every commit does have a trail (but not in Signed-Off fields). We're definitely still iterating on our open source process, so all input most welcome.

**Comment by ryjones** [comment]
@neil-da which repo is this press release talking about? My apologies: https://www.hyperledger.org/blog/2019/04/16/daml-smart-contracts-coming-to-hyperledger-sawtooth

**Comment by neil-da** [comment]
@ryjones this repo holds DAML the language and the building blocks to integrate DAML with other ledgers. There's a separate repo that holds the specific Hyperledger/DAML integration repo, which is going to be open source, but isn't linked to from the press release - so I assume it isn't actually open source yet.

**Comment by ryjones** [comment]
excellent. sorry for the noise.
