### ISSUE TITLE
Default 'loading' value in React bindings.

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#6171]
I think that the default loading value in the react bindings (ex. [here](https://github.com/digital-asset/daml/blob/master/language-support/ts/daml-react/hooks.ts#L118)) should default to true. When my component renders this value, I do not want to have the state that we're not loading and the result is `null` in the beginning.

**Comment by leonidr-da** [comment]
@hurryabit @robin-da Could you please take a look?

**Comment by hurryabit** [comment]
@leonidr-da Excellent idea. Thanks!

I've changed it in https://github.com/digital-asset/daml/pull/6196.
