### ISSUE TITLE
Use A-normal form in interpreter

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#6198]
Change the internal speedy AST such that it only can represent expressions in A-normal form and transform expressions into this form during package loading.

- Distinguish between known and unknown functions at compile time: 1.03x - 1.04x
- Detect fully applied builtins at compile time: 1.03x.

**Comment by nickchapman-da** [comment]
done

**Comment by hurryabit** [comment]
We've reverted the changes since they accidentally didn't comply with the DAML-LF semantics.

**Comment by hurryabit** [comment]
I consider this done with the landing of https://github.com/digital-asset/daml/pull/6918.
