### ISSUE TITLE
Can we have a latest-rc tag for daml install?

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#6231]
Currently when we want people to install RCs we need to tell them one of two things:

1. Use `daml install snapshot` to install the latest snapshot (which is likely the RC but not always, and which will likely change in-between RCs)
1. Use `daml install 1.2.0-snapshot.20200602.4310.0.1c18058f` (which is a very long string to copy and paste, and doesn't update if a bug is found and a new RC is rolled out)

Can we add a `latest-rc` tag so that `daml install latest-rc` changes mostly monthly and gives people access to the latest RC which helps avoid the above issues?

**Comment by dasormeter** [comment]
+1 -- this would be very useful for consuming and verifying with latest snapshot rc releases

**Comment by garyverhaegen-da** [comment]
There isn't necessarily a single "current" RC. Imagine we discover a critical bug that goes back three supported versions. We'd probably create 3 separate, simultaneous RCs.

Maybe something like `daml install 1.2-snapshot` which would take the latest snapshot in the 1.2 branch?

**Comment by anthonylusardi-da** [comment]
Could do that but I was hoping for something that wasn't tied to a specific version branch and was specifically for the latest version/RC as opposed to bug fix RCs. In my mind the same way `latest` gives you the newest stable version, `latest-rc` or `latest-beta` would give you the current RC of the newest version.

Also ideally this tag would both be the 1.2.0 RC and the final 1.2.0 release once installed. Then with 1.3.0 RC it would be that. Just a way to stay on the bleeding edge release if a user wants to do that.

**Comment by garyverhaegen-da** [comment]
> Also ideally this tag would both be the 1.2.0 RC and the final 1.2.0 release once installed. Then with 1.3.0 RC it would be that.

I do not understand what that means. At the moment we have two concurrent snapshots, one for 1.2, which is the RC for 1.2.0, and one for 1.3, which is a release snapshot but not expected to become an RC just yet. The latest stable is 1.1.1. What do you expect your new command to install in that situation?

Note that this is not a hypothetical situation, as it is the current one. It's also not a "special" situation: with a weekly release cadence for snapshots and a two-week "freeze" time between snapshot and release, we do expect this about two weeks per month.

**Comment by anthonylusardi-da** [comment]
I'd expect it to be the 1.2.0 RC right now, to become 1.2.0 once it's marked stable/out of RC, and then to become 1.3.0 RC once an RC is made for 1.3.0.

**Comment by garyverhaegen-da** [comment]
RC status is not reified at the moment, and I can't think of a way to do it. I'm afraid I do not see a way to implement what you want.

**Comment by anthonylusardi-da** [comment]
> Maybe something like daml install 1.2-snapshot which would take the latest snapshot in the 1.2 branch?

`x.y-snapshot` would still be a big improvement if we could do that then.
