### ISSUE TITLE
deprecate GetLedgerEnd on the ledger api

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#625]
The rpc `GetLedgerEnd` is not necessary as one can subscribe for transactions giving a `LedgerBoundary.LEDGER_END` as a start.

The documented semantics and the way it's implemented i.e. ledger end points to a non-existing ledger entry have been causing a lot of confusion, getting rid of it will open doors to clear the misunderstandings around offsets.

**Comment by gaboraranyossy-da** [comment]
the conclusion above was made after having a long discussion with @dajmaki and @meiersi-da. Tagging @gerolf-da and @bitonic as well, so we can decide how we are going to roll this out.

**Comment by gerolf-da** [comment]
I generally agree with the conclusion. What I dislike about the current `LEDGER_BEGIN` and `LEDGER_END` is that `LEDGER_BEGIN` is an immutable offset, while `LEDGER_END` means "whatever is currently the last block at the time of execution of the request". The former is a clear boundary while the latter is more like a moving target. Can we reflect this in the names? Maybe `LEDGER_CURRENT_END`?

**Comment by gaboraranyossy-da** [comment]
How about `LEDGER_HEAD`? That would imply that it's moving.

**Comment by gerolf-da** [comment]
`LEDGER_HEAD` seems okay

**Comment by bitonic** [comment]
agreed on everything including the rename from `LEDGER_END` to `LEDGER_HEAD`

**Comment by stefanobaghino-da** [comment]
Is this still valid? The name change makes a lot of sense but I'm not sure it's worth the breaking.

**Comment by gerolf-da** [comment]
If at all, I wouldn't remove the `LEDGER_END` field but rather do this (in the name of generated code backwards compatibility):
```
enum LedgerBoundary {
    option allow_alias = true; // <----------
    // Refers to the first transaction.
    LEDGER_BEGIN = 0;

    // Refers to the currently last transaction, which is a moving target.
    LEDGER_END = 1 [deprecated = true];
    LEDGER_HEAD = 1;
  }
```
We can also deprecate the `GetLedgerEnd` call.
I don't think it's HIGH priority though, considering that we want to de-emphasize the gRPC API anyway in favor of the JSON API.

**Comment by stefanobaghino-da** [comment]
FYI the test tool uses the ledger end to limit the fetched transactions to those happened since the beginning of the test.

**Comment by gerolf-da** [comment]
That shouldn't shouldn't (but currently does) matter that much, because the transactions should be fetched in such a way that we don't load unnecessary data. This "optimization" is still pending though, so in practice it actually might matter a lot, depending on the ledger size.

**Comment by gerolf-da** [comment]
Closing this issue as `GetLedgerEnd` likely will be part of how applications handle node failover or in general reconnecting to the ledger API.
