### ISSUE TITLE
ledger-api-test-tool: ensure command-ids can be traced back to individual tests via logs

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#6252]
Acceptance Criterium:
* When using the Ledger API test tool to test a ledger implementation, I would like to be able to use the log output of the Ledger API test tool to correlate every command-id received in the ledger implementation with the individual test that gave rise to the command with that command-id.

Assumption:
The ledger implementation produces log lines with information sufficient to trace back every log line due to command processing to a specific command-id.

Technical notes:
* INFO log level seems appropriate

**Comment by meiersi-da** [comment]
@stefanobaghino-da -- created as per our discussion. Could you help with tagging and bagging the issues? ;-)

**Comment by gerolf-da** [comment]
@stefanobaghino-da: Each command ID already contains the short test identifier, which is logged in the test summary. I think this issue can be closed now.
