### ISSUE TITLE
Introduce conformance tests against rogue participants

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#6254]
Right now, the `ledger-api-test-tool` uses a benign, well-tested engine implementation to execute DAML code and send the resulting transactions to the implementation of the `WriteService` part of the DAML ledger implementation.

This means that it's very hard (and likely flaky) to test for unexpected errors (even if done in good faith, e.g. time model violations) and even impossible to test the behavior of rogue participants (e.g. what happens if an engine implementations lets an invalid transaction through).

The `ledger-api-test-tool` should include a class of tests that allows to push invalid transaction to the `WriteService` and test through the `ReadService` that those are correctly rejected.

**Comment by gerolf-da** [comment]
This is now tracked by KVL-435.
