### ISSUE TITLE
Batch ledger updates in the indexer

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#6255]
## Idea

The indexer is a single-threaded process that takes `WriteService` updates and writes them one by one to index database. This can be improved by batching updates. Benefits:

- Less query parsing
- Contracts (and witnesses) that are created AND removed within the same batch will never be written to the index

## Draft implementation

PR https://github.com/digital-asset/daml/pull/6113

## Results

The performance was tested in 
a scenario where the indexer was connected to an existing ledger with 40k DAML transactions. There were no concurrent command submissions or ledger API subscribers (i.e., the indexer was the only thread using the index database). Results:

- The "old" indexer and "batching" indexer ran at the same speed if maximum batch size is 1
- With a maximum batch size of 64, the indexer wrote updates faster up to a certain index size, then it dropped to the same speed as without batching
- Tweaking the postgres config significantly changed the results
- Two thirds of the time was spend in the SQL transaction commit

This all suggests that the bottleneck is Postgres writing data to the index database, and batching will provide any immediate benefit. 

### Non-batching ledger

Steady 40 upates per second
<img width="1440" alt="Screenshot 2020-06-04 at 15 43 33" src="https://user-images.githubusercontent.com/31539813/84007335-8ae64700-a970-11ea-98cb-dc08e71ab2e9.png">

### Batching ledger

Starts at 100 updates per second, then drops to below 40 updates per second
<img width="1440" alt="Screenshot 2020-06-04 at 15 42 35" src="https://user-images.githubusercontent.com/31539813/84007453-be28d600-a970-11ea-9cc2-7cee13f91ce9.png">

**Comment by gerolf-da** [comment]
This is now obsolete with the improved indexer on the append-only schema, where batching of updates has been built into the design from the get got.
