### ISSUE TITLE
Tracking Windows errors

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#6262]
We have seen many errors on Windows recently. This issue is trying to keep track of them, so we can have a better view on what kinds of issues we are seeing and how frequent they are, in the hope that this will help us formulate concrete plans to solve them.

**Comment by garyverhaegen-da** [comment]
## output was not created

Error message:
```
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:354:1: output 'compiler/damlc/tests/repl-functests.exe' was not created

ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:354:1: not all outputs were created or valid
```

Affected commits:
921266a926e774bd9d5e92cd9f67eade3f859f32 [[log](https://github.com/digital-asset/daml/files/4745896/112.txt)]
2a4e9dcaf3ca9b4de2070f25da4696b2f52a453c [[125.txt](https://github.com/digital-asset/daml/files/4745899/125.txt)]

Attempted resolution:
* Clearing the cache through [a separate PR](https://github.com/digital-asset/daml/pull/6261)

**Comment by garyverhaegen-da** [comment]
## undeclared inclusions

### Error message:

```
ERROR: C:/users/u/_bazel_u/igiwx5st/external/bazel_tools/tools/cpp/runfiles/BUILD:3:1: undeclared inclusion(s) in rule '@bazel_tools//tools/cpp/runfiles:runfiles':
this rule is missing dependency declarations for the following files included by 'external/bazel_tools/tools/cpp/runfiles/runfiles.cc':
```

### Affected commits:
b9fbba7fc5d4f0672764171a6d3974365d7cdb3b [[log](https://github.com/digital-asset/daml/files/4746264/77.txt)]

Note: b9fbba7fc5d4f0672764171a6d3974365d7cdb3b succeeded at the exact same build on the previous day: [[build step](https://github.com/digital-asset/daml/files/4746267/94.txt)], [[test step](https://github.com/digital-asset/daml/files/4746269/95.txt)], [[Bazel execution log (zip)](https://github.com/digital-asset/daml/files/4746274/build_execution_windows.log.zip)].

**Comment by cocreature** [comment]
### undeclared inclusions
Same error as before but this is after we reset the cache.

**Comment by cocreature** [comment]
### output was not created

#### error message
ERROR: D:/a/2/s/compiler/scenario-service/protos/BUILD.bazel:67:1: output 'compiler/scenario-service/protos/_obj/scenario_service_haskell_proto/ScenarioService.o' was not created

### Affected commits
https://dev.azure.com/digitalasset/daml/_build/results?buildId=45869&view=results

### Resolution
Rerun succeded but on a different node. Builds on the same node failed.
Bump Windows cache and take out the node.

### Notes
Caches are separated by working directories. This only seems to have affected the node that ran the daily compat check which runs in a different working directory.

**Comment by aherrmann-da** [comment]
### output was not created

#### error message
```
ERROR: D:/a/1/s/daml-assistant/integration-tests/BUILD.bazel:162:1: output 'daml-assistant/integration-tests/create-daml-app-tests.exe' was not created
ERROR: D:/a/1/s/daml-assistant/integration-tests/BUILD.bazel:162:1: not all outputs were created or valid
```
### Affected commits
https://dev.azure.com/digitalasset/daml/_build/results?buildId=46019
https://dev.azure.com/digitalasset/daml/_build/results?buildId=46019
https://dev.azure.com/digitalasset/daml/_build/results?buildId=46033&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=39c35361-d0fa-5a5b-07df-90fe37b2b8e2&l=154

### Resolution
Bump Windows cache and `clean --expunge`.

**Comment by cocreature** [comment]
## Output was not created
### error message
ERROR: D:/a/1/s/compiler/damlc/daml-package-config/BUILD.bazel:9:1: output 'compiler/damlc/daml-package-config/_obj/daml-package-config/DA/Daml/Package/Config.o' was not created
### Affected commits
https://github.com/digital-asset/daml/pull/6375
### Resolution
Given that this is a release PR, I’ll try only building that with cache disabled rather than nuking the world.

**Comment by garyverhaegen-da** [comment]
## Output was not created

### error message

```
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:549:1: output 'compiler/damlc/tests/_obj/unstable-types/DA/Test/UnstableTypes.o' was not created
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:549:1: output 'compiler/damlc/tests/_iface/unstable-types/DA/Test/UnstableTypes.hi' was not created
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:549:1: not all outputs were created or valid
```

### Affected commits

https://github.com/digital-asset/daml/pull/6381

### Resolution

Selectively cleaning the cache did not seem to help this time, so we instead bumped the cache counter (https://github.com/digital-asset/daml/pull/6383). I'll update later on whether that worked.

**Comment by garyverhaegen-da** [comment]
# Output was not created

## error message

```
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/PrettyScenario.o' was not created
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/ScenarioServiceClient.o' was not created
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/ScenarioServiceClient/LowLevel.o' was not created
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/PrettyScenario.hi' was not created
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/ScenarioServiceClient.hi' was not created
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/ScenarioServiceClient/LowLevel.hi' was not created
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:1: not all outputs were created or valid
ERROR: D:/a/1/s/compiler/damlc/daml-opts/BUILD.bazel:38:1 not all outputs were created or valid
```

## Affected commits

3e55fda66bc46c3828007842e8f1d4efefbccba5: 
[log](https://github.com/digital-asset/daml/files/4869876/108.txt)


## Resolution

https://github.com/digital-asset/daml/pull/6604

**Comment by cocreature** [comment]
## Output was not created
### Error message

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Alpha.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Base.o' was not created
ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/FreeVars.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Numeric.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Optics.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Pretty.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Recursive.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Subst.o' was not created

ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: output 'compiler/daml-lf-ast/_obj/daml-lf-ast/DA/Daml/LF/Ast/Type.o' was not created


ERROR: D:/a/1/s/compiler/daml-lf-ast/BUILD.bazel:6:1: not all outputs were created or valid

ERROR: D:/a/1/s/compiler/damlc/BUILD.bazel:10:1 not all outputs were created or valid
### Affected commits
c203cd36006d401525a586ac77d9a914029d4c54 [log](https://dev.azure.com/digitalasset/adadc18a-d7df-446a-aacb-86042c1619c6/_apis/build/builds/49614/logs/40)

### Resolution
pending

**Comment by garyverhaegen-da** [comment]
# not all outputs were created or valid

Happened on the compat build for a [1.5-snapshot update PR](https://github.com/digital-asset/daml/pull/7007). Machine was `vsts-win-q1s0`. [Full log](https://github.com/digital-asset/daml/files/5028741/39.txt).

## Resolution

Pending: trying to take out just that node for now, but may need to escalate to cache bumping.

**Comment by cocreature** [comment]
### Output was not created
Happened on #7039 
##### Resolution
Took out the affected node.

**Comment by cocreature** [comment]
### Output was not created

Happened on rerun of #7007 
```
ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/PrettyScenario.o' was not created

ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/ScenarioServiceClient.o' was not created

ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/ScenarioServiceClient/LowLevel.o' was not created

ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/PrettyScenario.hi' was not created

ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/ScenarioServiceClient.hi' was not created

ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/ScenarioServiceClient/LowLevel.hi' was not created

ERROR: D:/a/2/s/compiler/scenario-service/client/BUILD.bazel:6:19: not all outputs were created or valid
```
run in `D:/a/2/s`

#### Resolution

Going to try resetting the cache, this is too annoying.

**Comment by cocreature** [comment]
## Output was not created

https://github.com/digital-asset/daml/commit/ab8b418b7289cc5612e98b10d882d4a6c4660ea8

```
ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/PrettyScenario.o' was not created

ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/ScenarioServiceClient.o' was not created

ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/_obj/client/DA/Daml/LF/ScenarioServiceClient/LowLevel.o' was not created

ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/PrettyScenario.hi' was not created

ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/ScenarioServiceClient.hi' was not created

ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: output 'compiler/scenario-service/client/compilerZSscenario-serviceZSclientZSclient/_iface/DA/Daml/LF/ScenarioServiceClient/LowLevel.hi' was not created

ERROR: D:/a/1/s/compiler/scenario-service/client/BUILD.bazel:6:19: not all outputs were created or valid
```
## Resolution
Disabled machine, let’s see if it helps.

**Comment by garyverhaegen-da** [comment]
# Output not created

This time in the Windows job.

```
ERROR: D:/a/1/s/compiler/damlc/BUILD.bazel:78:12: output 'compiler/damlc/damlc-dist.tar.gz' was not created

ERROR: D:/a/1/s/compiler/damlc/BUILD.bazel:78:12: not all outputs were created or valid
```

Killed the machine (Q1S0).

**Comment by garyverhaegen-da** [comment]
# Output not created

Same... Machine CW68 this time. Also killed.

**Comment by garyverhaegen-da** [comment]
Note: it looks like rebasing made the above disappear. The PR on which those appeared (#7146) changes the stdlib so triggers targets we don't often rebuild.

**Comment by garyverhaegen-da** [comment]
# Output not created, master

On commit c997f5d, node PN4D

```
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: output 'compiler/damlc/tests/_obj/integration-v18/DA/Test/DamlcIntegrationMain.o' was not created

ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: output 'compiler/damlc/tests/_iface/integration-v18/DA/Test/DamlcIntegrationMain.hi' was not created

ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: not all outputs were created or valid
```

Node killed.

**Comment by garyverhaegen-da** [comment]
# Output not created, master

On commit f54e193df621ce66cd9202801c9d3dbcbbdd311c, node CW68.

```
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: output 'compiler/damlc/tests/_obj/integration-v18/DA/Test/DamlcIntegrationMain.o' was not created

ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: output 'compiler/damlc/tests/_iface/integration-v18/DA/Test/DamlcIntegrationMain.hi' was not created

ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: not all outputs were created or valid
```

Node killed.

**Comment by garyverhaegen-da** [comment]
Above kept happening so we've decided to bump the cache (#7212).

**Comment by garyverhaegen-da** [comment]
# Output not created, #7385

Machine CW68:
```

[2,824 / 2,836] checking cached actions

ERROR: D:/a/2/s/daml-assistant/BUILD.bazel:75:18: output 'daml-assistant/_obj/daml/DA/Daml/Assistant.o' was not created

ERROR: D:/a/2/s/daml-assistant/BUILD.bazel:75:18: output 'daml-assistant/_iface/daml/DA/Daml/Assistant.hi' was not created

ERROR: D:/a/2/s/daml-assistant/BUILD.bazel:75:18: not all outputs were created or valid

INFO: Elapsed time: 96.348s, Critical Path: 3.87s

INFO: 1 process: 1 local.

FAILED: Build did NOT complete successfully
```

Disabled the machine for now.

**Comment by garyverhaegen-da** [comment]
# Output not created, master

This is #7385 again, but this time after merge (d966178f470a6c390634d4ec86584598505bb5fe). I have disabled the machine (PN4D) and will try rerunning.

**Comment by cocreature** [comment]
### Output not created, master

```
Created C:/users/u/_bazel_u/vvgx3zjt/execroot/com_github_digital_asset_daml/bazel-out/x64_windows-opt/bin/triggers/daml/daml-trigger-1.8.dar
ERROR: D:/a/2/s/daml-assistant/BUILD.bazel:75:18: output 'daml-assistant/_obj/daml/DA/Daml/Assistant.o' was not created

ERROR: D:/a/2/s/daml-assistant/BUILD.bazel:75:18: output 'daml-assistant/_iface/daml/DA/Daml/Assistant.hi' was not created

ERROR: D:/a/2/s/daml-assistant/BUILD.bazel:75:18: not all outputs were created or valid

INFO: Elapsed time: 541.649s, Critical Path: 68.92s
```

This is on `/d/a/2/s` so it might just be that we have to reset the `2` cache (which the way we currently handle it also means resetting the `1` cache`).

**Comment by SamirTalwar-DA** [comment]
# Output not created, #7517

On commit [`1849b76` (#7517)](https://github.com/digital-asset/daml/pull/7517/commits/1849b766ec1190d713bd847affa9cf273e7c58d0).

```
ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: output 'compiler/damlc/tests/integration-v17.exe' was not created

ERROR: D:/a/1/s/compiler/damlc/tests/BUILD.bazel:156:20: not all outputs were created or valid
```

[Build log](https://dev.azure.com/digitalasset/daml/_build/results?buildId=56450&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=ac0b0b0f-051f-52f7-8fb3-a7e384b0dde9)

**Comment by cocreature** [comment]
## Output not created, #7542

```
ERROR: D:/a/1/s/ci/cron/BUILD.bazel:6:18: output 'ci/cron/_obj/cron/Main.o' was not created

ERROR: D:/a/1/s/ci/cron/BUILD.bazel:6:18: output 'ci/cron/_iface/cron/Main.hi' was not created

ERROR: D:/a/1/s/ci/cron/BUILD.bazel:6:18: not all outputs were created or valid
```

Interestingly this is the one that was modified in this PR.

I’ve taken out the node for now, let’s see if that helps.

**Comment by garyverhaegen-da** [comment]
# Output not created, all over the place

Loads of this one today. We decided to go for a more targeted approach for the fix and are currently trying to only force a rebuild of the one file that fails: https://github.com/digital-asset/daml/pull/7613.

**Comment by SamirTalwar-DA** [comment]
## Output not created, #7768.

On commit https://github.com/digital-asset/daml/pull/7767/commits/deb1c58376ab4a764e97d06424350bf5c782fd17.

[Full log.](https://github.com/digital-asset/daml/files/5415878/build.log)

```
ERROR: D:/a/2/s/compiler/daml-lf-reader/BUILD.bazel:6:19: output 'compiler/daml-lf-reader/_obj/daml-lf-reader/DA/Daml/LF/Reader.o' was not created

ERROR: D:/a/2/s/compiler/daml-lf-reader/BUILD.bazel:6:19: output 'compiler/daml-lf-reader/compilerZSdaml-lf-readerZSdaml-lf-reader/_iface/DA/Daml/LF/Reader.hi' was not created

ERROR: D:/a/2/s/compiler/daml-lf-reader/BUILD.bazel:6:19: not all outputs were created or valid
```

**Comment by cocreature** [comment]
Closing since it seems to have done the job. We now have a workaround for the caching issue in place via #8668. Note that this does not stop the error from happening but it stops it from breaking the cache so we can simply take out the node and move on. We could automate that part as well but atm it seems to happen once a week or so at most so not that urgent of an issue.
