### ISSUE TITLE
Highlight self like this

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#630]
In choices `self` refers to the contract id of the current contract the same way as `this` refers to the contract itself. `this` is treated special by the syntax highlighter, `self` isn't. We should remove this discrepancy by highlighting `self` the same way as `this`.

cc @neil-da @shayne-fletcher-da

**Comment by neil-da** [comment]
My suggestion was that both `self` and `this` get treated the same way, but neither gets treated as a keyword - they're reserved identifiers with default bindings. That's quite a lot less than a keyword, but a lot more than something like `map`.

**Comment by akalburgi** [comment]
as of the latest vs code plugin (we have not made a release after these changes were merged into master) `this` is marked as `source.daml` and not a keyword. And so is `self`. There is no well-defined scope for something between a `keyword` and `source` in vs code syntax highlighter.

**Comment by shayne-fletcher-da** [comment]
To clarify, what that means is, when the latest version of the highlighter is released, neither `this`, `self` or `arg` will get any distinguished treatment. Similarly, variables like `return` and so on that previously were being treated as "keywords" (via Sofus IIRC) will no longer be.

**Comment by akalburgi** [comment]
Closing this, the latest release of sdk has the fix
