### ISSUE TITLE
DAML-LF interpretation computes observers before ensures clause

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#631]
When you run the scenario in
```haskell
daml 1.2
module Ensures where

import DA.List

template Confirmation with
    confirmed : [Party]
    pending : [Party]
  where
    signatory confirmed
    ensure not (null pending)

    controller head pending can
      Skip : ContractId Confirmation
        do
          create this with pending = tail pending

test = scenario do
  alice <- getParty "Alice"
  submit alice do
    create Confirmation with
      confirmed = [alice]
      pending = []
```
the interpretation fails with
```
Scenario execution failed on commit at Ensures:20:3:
  Aborted:  head: empty list
```
This error message is slightly misleading since the `ensures` clause should ensure that we don't get that far with an empty list. In fact, if you commit out the `Skip` choice, you get a different error message
```
Scenario execution failed on commit at Ensures:20:3:
  Template pre-condition violated in:
    create Ensures:Confirmation
    with
      confirmed = ['Alice']; pending = []
```
Clearly, this error message is more helpful. IMO, we should get the same error message in the first case too.

My (educated) guess is that the DAML-LF interpreter computes the observers (and perhaps also the signatories) before it looks at the outcome of the `ensures` clause.

**Comment by hurryabit** [comment]
@dajmaki do you know _form the top of your head_ if my suspicion is correct?

**Comment by dajmaki** [comment]
Yep, looks correct. The builtin "create" is called with pre-condition as argument along with observers, so both are interpreted before the pre-condition are checked.

https://github.com/digital-asset/daml/blob/master/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Compiler.scala#L449

**Comment by remyhaemmerle-da** [comment]
#727 fixes the issue.
