### ISSUE TITLE
Remove unused requirements file for python

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#6317]
From the docs I'm reading, requirements_frozen.txt is supposed to be generated by pypi2nix based on a requirements.txt, so did we misplace the original file?
When I run it (on Linux; it refuses to run on macOS), it generates requirements.nix, which is vaguely similar to our current default.nix but different enough that I'm a bit skeptical.

Either way, this file does not seem to be used at all, so I thought I might as well reduce the confusion for future people looking at this. Happy to be told I'm wrong and this file is actually useful if I missed something, but removing it doesn't seem to phase nix-build -A tools -A cache nix.

As discussed in
https://github.com/digital-asset/daml/pull/3831 and https://github.com/digital-asset/daml/pull/3216

> I'd rather not: merging this PR will not change what actually gets run, so I prefer to keep it as a reminder that this needs fixing.

_Originally posted by @dasormeter in https://github.com/digital-asset/daml/pull/3216#issuecomment-642831720_

**Comment by garyverhaegen-da** [comment]
Removing the file is not the solution either. It's not exactly that it's unused, it's more that it's not often/automatically used. I'd much rather have kept the open PR.

**Comment by cocreature** [comment]
I suggest reverting this. You’ve removed the warning while keeping the problem: We still use the old version of `PyYAML`. That seems strictly worse than before.

**Comment by cocreature** [comment]
Actual fix in #6318
