### ISSUE TITLE
Make Trigger Services endpoints more RESTful

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/daml#6333]
See this comment https://github.com/digital-asset/daml/pull/6329#discussion_r439572928. Let's revisit our choices for trigger service endpoints and do the right thing.

**Comment by cocreature** [comment]
The other option would be to just turn it into a POST. Currently it’s in an awkard middleground where it tries to follow the REST-style DELETE for removing stuff but then also has a separate endpoint for that.

**Comment by cocreature** [comment]
Finally got around to looking through the current endpoints and here’s my proposal for revamping them:

| New endpoint              | Old endpoint       | Functionality                |
|---------------------------|--------------------|------------------------------|
| GET `/v1/triggers`        | `/v1/list`         | List triggers                |
| POST `/v1/triggers`       | `/v1/start`        | Start trigger                |
| GET `/v1/triggers/:id`    | `/v1/status/:id`   | Trigger status               |
| DELETE `/v1/triggers/:id` | `/v1/triggers/:id` | Stop/delete trigger          |
| GET `/v1/packages`        | -                  | List packages                |
| POST `/v1/packages`       | `/v1/upload_dar`   | Upload DAR                   |
| POST `/v1/packages`       | `/v1/upload_dar`   | Upload DAR                   |
| GET `/livez`              | `/v1/health`       | liveness check               |
| GET `/readyz`             | -                  | readiness check              |
| GET `/cb`                 | `/cb`              | Internal endpoint for auth   |
