### ISSUE TITLE
DAML Test Coverage

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#6370]
As [first mentioned by Asad Khan here](https://discuss.daml.com/t/daml-test-coverage/654) it would be great if DAML had a tool to report code coverage metrics.

> I haven't seen it explicitly mentioned yet, so I figured I'd ask.
> 
> Whats the view on creating some sort of reporting or coverage metrics from DAML Scripts/Scenarios for DAML code? Is there a tool that provides this today? Is this on the roadmap of the SDK?
> 
> Links for conversation:
> * [isRobo test generator](https://daml.com/marketplace/isrobo-intelligent-scenario-robot/)
> * [Haskell test coverage](https://docs.haskellstack.org/en/stable/coverage/)
> * [Go test coverage view](https://blog.golang.org/cover)

**Comment by Nandansv** [comment]
@cocreature  is there any timeline for this feature. It would be really a helpful tool for larger projects.
----------------------------
@ashfaq-shaik

**Comment by cocreature** [comment]
No timeline at the moment, sory.

**Comment by Nandansv** [comment]
> No timeline at the moment, sorry.

Okay Thank you.
