### ISSUE TITLE
Release daml on sql and JSON API fat JARs to GH releases, not GCP

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#6384]

**Comment by cocreature** [comment]
Why?

**Comment by bame-da** [comment]
So that they are more discoverable and we have more consistency in where we release our public binaries.

**Comment by cocreature** [comment]
I’m somewhat hesitant to add more and more stuff to the github releases page as it gets very messy. daml-on-sql and the JSON API are probably important enough but where do we stop?

**Comment by bame-da** [comment]
I'm not particularly fussed about it being GH Releases, but I think there should be one place where we release the binary artefacts that you need download and run. So in the future I'd see components like the Trigger Service being added to the list.

**Comment by cocreature** [comment]
That’s fair, I guess github releases is probably our best option anyway in terms of having something that is reasonably easy to discover. Do you want daml-on-sql to remain as sandbox classic? The uncertainty around that was the main reason why we did not put them on GH releases.

**Comment by bame-da** [comment]
Yes, there has been a firm decision on that.

**Comment by cocreature** [comment]
See https://github.com/digital-asset/daml/pull/6397
