### ISSUE TITLE
Deprecate SQL support in sandbox

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#6385]
Once we've done #6384 we should deprecate SQL support from the sandbox. That means in a first release, `daml sandbox` and `daml start` should no longer document the flag in the CLI help text, we should put notices in the docs, and the commands should emit a warning when started with persistence. The warning should inform the user that for any use cases requiring persistence the daml on sql binary should be used.

In a later release, the feature may be removed altogether.

**Comment by gerolf-da** [comment]
@SamirTalwar-DA: this is actually also ready. My head read `Deprecate` as `Remove`. Deprecating of course is a valid non-destructive next step.

**Comment by cocreature** [comment]
We’ve deprecated this now.
