### ISSUE TITLE
DAML Assistant User Experience Improvements

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#644]
Here are few suggestions based on my short experience with DAML Assistant.
1. `daml-head package` creates `./quickstart.dar` in the root of the project. `da` creates it in `./target/`. I think we should change DAML Assistant so it creates the DAR in a subfolder, don't care if it is `./target/`, `./bin/`, `./daml-out/`. It is a good practice to put all produced artifacts in a separate directory and we should follow this.
2. I also think DAML assistant needs `clean` command, that removes all artifacts created by `package` or `compile` (but in case of compile we don't know the directory where user puts the compiled file)
3. The name of the project/artifact is hardcoded in the `daml.yaml` as `name: quickstart`. I think we should use the name provided to `da-head new`

CC: @fmota-da 
Related to: #11

**Comment by associahedron** [comment]
1 & 3 are both done. 2 is not yet.

**Comment by associahedron** [comment]
Closing this in favor of #1223.
