### ISSUE TITLE
Simplify LF/Transaction/Value versionning. 

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#6527]
Currently the LF engine uses 3 different version: 
* 1 to version the language.
* 1 to version the transactions stored in the ledger.
* 1 to version the values that appears in the transaction.

See the [DAML-LF Governance process](https://github.com/digital-asset/daml/blob/master/daml-lf/governance.rst) for more detail.
 
This issue is concerned with simplifying the versioning scheme by merging the tree versions.
This issue replaces #5478.

### Proposal

* We "tie" language versions `1.6` and `1.7` to the transaction version `10` and value version `6`.
* each future language version `x.y` will be "tied" to its own transaction version  and value version (for simplicity we will note these version `x.y`) 
* future Transaction version `x.y` will embed values without explicit version. Those values will be encoded using value version `x.y` format. 

### Version inference

The version of the output transaction will be inferred as follows:

* Take the command `cmd₁`, ..., `cmdₙ` received from the ledger API  during one submission request.
* For each command `cmdᵢ`, get `tmplIdᵢ` the ID of the template  created or exercised by the command `cmdᵢ`
* For each `tmplIdᵢ` take `pkgIdᵢ` the ID of the package where `tmplIdᵢ` is defined.
* Infer `LangVersion` as the newest language version of the packages `pkgId₁` ...  `pkgIdₙ`, *and* all their dependencies.
* take `TxVersion` the transaction version "tied" to `LangVersion`
* In case of success, version the output transaction with `TxVersion`.
  
**example:** 

Imagine you have 3 packages
* `pkg1` compiled using LF 1.7
* `pkg2` compiled using LF 1.8
* `pkg3` compiled using LF 1.7

Additionally `pkg3` depends on `pkg1` and `pkg2`, but those two later package do not depends on other packages.

If one triggers a command on a template from pkg3, the produced transaction will use transaction version "10"
If one triggers a command on a template from pkg1 you produced transaction will use transaction version "1.8"

### Backward compatibility

Note that since release of SDK 1.0, language versions older than 1.6, transaction versions older than 10, and value versions older than 6 are deprecated. Reading older version of  language, transaction, or value is supported only for sandbox.  (see #5220)

* LF 1.6 or 1.7 will output only transaction version 10 will be all encoded using the value version 6.
* Reading of arbitrary older version of value and transaction will be supported only for sandbox.

**Comment by cocreature** [comment]
A few comments:
1. One of the 3 is user-facing (LF), the other 2 are not. (since I got confused by that myself for a bit: we are not talking about the (currently unversioned) transaction and value protobufs used on the ledger API). That’s not necessarily an issue but I think it’s worth keeping this in mind.
2. Which version do we use next? Using 1.9 seems a bit confusing if we already have 10 for the current transaction version. Maybe going to 11 is worth considering? Or some clear way to distinguish between the old and the new scheme?

**Comment by remyhaemmerle-da** [comment]
done as part of #5164
