### ISSUE TITLE
Invalid offsets returned by CompletionEnd service on an empty ledger

### ISSUE THREAD

**Issue by oggy-** [digital-asset/daml#6529]
Steps to reproduce:
1. start from an empty ledger
2. call `CompletionEnd` endpoint to get an offset
3. try to use `CompletionStream` or `GetTransactions` with the offset returned in step 2

The problem is that step 2 will return a `LedgerOffset(Absolute(()))` protobuf value, which I guess is treated as the default gRPC value, so the completion stream will complain about the missing `offset` field.

We ran into the problem in Canton when using this guy on an empty ledger:
https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/services/commands/CommandClient.scala#L110

**Comment by oliverse-da** [comment]
Thanks for tracking this down @oggy- . @simonmaxen-da , @leo-da , should `LedgerOffset(Absolute(()))` turned (back) into a `LedgerOffset(LedgerBegin)` somewhere in the stack?

**Comment by oggy-** [comment]
From what Leo told me @gerolf-da suggested the relevant parts of this change which seem to have led to the issue:

https://github.com/digital-asset/daml/commit/12c05c408af5abefad56d1135aa9d36ee1c2ea3c

So he should probably also weigh in on the resolution too, b/c I don't know what the driver of the change was.

**Comment by gerolf-da** [comment]
As @oliverse-da proposed, converting the response back to ledger begin in case it is equal to `Offset.beforeBegin` makes sense and works both for the completion service and the transaction service.
