### ISSUE TITLE
Meta: DAML Ledger Integration Kit - ALPHA Release

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#658]
This meta issue tracks the availability of the ALPHA release of the DAML Integration Kit.
- You can [watch this issue](https://help.github.com/en/articles/subscribing-to-and-unsubscribing-from-notifications#subscribing-to-issues-and-pull-requests) to be informed about the ALPHA release.
- You can use this issue's conversation to ask questions about the ALPHA release.

Note that for convenience we group the outstanding issues for the ALPHA release additionally in https://github.com/digital-asset/daml/milestone/4

**Comment by meiersi-da** [comment]
@gleber-da : please close once all other tickets are done.

**Comment by gleber-da** [comment]
All done!
