### ISSUE TITLE
Record and replay sequences of ReadService updates as tests

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#6609]
Analyzing and reconstructing the sequence of updates necessary to reproduce https://github.com/digital-asset/daml/pull/6607 took a full day of manual work.

Ideally, we'd want to be able to come up with a test case in minutes by dumping a sequence of messages in a well-known format that can be replayed on top of a standalone indexer to find issues with the indexer itself.

**Comment by gerolf-da** [comment]
Now tracked as KVL-431.
