### ISSUE TITLE
I can’t use `npx create-daml-app` or `yarn create daml-app` to create an app

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#6683]
Lots of frameworks allow you to create a JavaScript application from a template with `npx create-framework-app` or `yarn create framework-app`. This is done by creating a package on NPM named `create-framework-app` which does the magic.

For example, you can easily [create a new React app][] with `npx create-react-app` or `yarn create react-app`.

However, DAML doesn't provide this option. I'd love to be able to run `yarn create daml-app` to make a new app in the same way that I can run `daml new my-project create-daml-app`.

[create a new react app]: https://reactjs.org/docs/create-a-new-react-app.html

**Comment by cocreature** [comment]
not planning to address this. Will reopen once we get someone else ask for this.
