### ISSUE TITLE
Participant Server: Extensive logging to support troubleshooting/debugging

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#6684]
To help with investigating issues the participant server needs to log much more data.
At the very least, the following logging entries should be available on `TRACE` level:

### JdbcIndexer
- each state update delivered by the ledger backend
- all data that is actually stored in the index

### Ledger API Server
- each request coming in
- each response being sent out

**Comment by stefanobaghino-da** [comment]
> * all data that is actually stored in the

@gerolf-da In the... what? :slightly_smiling_face:

**Comment by gerolf-da** [comment]
oops, fixed.

**Comment by gerolf-da** [comment]
Now tracked in KVL-433.
