### ISSUE TITLE
SDK 1.3.0 Transaction stream from ledgerEnd receive Archived events before the offset

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#6698]
After running sandbox on `1.3.0-snapshot.20200708.4686.0.95dfa18e` and `ledgerClient` is running `0.13.55`

when calling 
```
ledgerClient.transactionClient.getTransactions(
      start = offset,
      end = None,
      transactionFilter = filter
    )
```

where `offset` always starts from `ledgerEnd`. There are archived events flow into the transaction stream before the `ledgerEnd`.
 Is this expected due to the ledgerClient/ledger version incompatible?

cc. @da-tanabe

**Comment by leo-da** [comment]
Possible culprits from the top of my head:
- https://github.com/digital-asset/daml/pull/6372
- https://github.com/digital-asset/daml/pull/6638

**Comment by leo-da** [comment]
@lima-da @da-tanabe 
was the ledger empty or contained any events before switching to sandbox 1.3.0-snapshot? Can you provide a postgres dump before the migration.
