### ISSUE TITLE
is it possible to call Ledger API with Go？

### ISSUE THREAD

**Issue by gzuhlwang** [digital-asset/daml#6719]
I have a question for you guys. The DAML SDK doc lists several ways to interact with Ledger API, such as Java bindings, Scala bindings. Due to Ledger API defined in protobuf, in principle I can use Go to call the RPC method exposed by Ledger server. 
But I am not sure about it because generated code( for example, daml file -> java code) involved in the doc.  

any replies will be thankful.

**Comment by garyverhaegen-da** [comment]
Yes, you can interact with the gRPC ledger API from any language that has gRPC bindings. You can even do it from gRPCURL.

The added value of the language bindings we provide is that they do code generation based on the DAML model, i.e. they provide a type-safe wrapper around raw gRPC access that maps types in the host language (Scala, Java) to types in the DAML code. Accessing the gRPC API from other languages will require either writing those wrappers yourself or sacrificing some type-safety through manipulating gRPC data more directly.

Note that, depending on your use-cases (and go"s support for both JSON/HTTP and gRPC), the JSON API could be easier to plug into.

**Comment by gzuhlwang** [comment]
thanks. Go has a very good support in HTTP and gRPC.  from my understanding，I will deal with more things on my own than using other provided language bindings, if using Go.

I have another puzzle. Based on the demo, such as quickstart in doc, the java code( in IouMain.java) uses the generated java code.  Is is possible for implementing a HTTP JSON API providing similar service like daml json-api  but independent on used generated code?

**Comment by garyverhaegen-da** [comment]
I'm not the most familiar with our documentation, so I may be mistaken here, but I believe we currently do not have any example or tutorial for using our APIs without code generation.

`daml json-api` starts an HTTP server that responds to most requests with a JSON payload. The full documentation can be found [here][0]. The server started by `daml json-api` knows nothing of (and does not depend on) any language bindings; it just serves JSON responses. If you're willing to manipulate raw JSON, or build up your own abstractions, it is definitely possible to build applications with no code generation.

[0]: https://docs.daml.com/json-api/index.html

**Comment by gzuhlwang** [comment]
Yes. that's what my intention. I want to build another HTTP JSON API with Java or any other language but with no generated code used anymore. thanks

**Comment by garyverhaegen-da** [comment]
I may have been unclear, so let me clarify a bit.

The `daml json-api` command will start a server written in Scala ([source here][0]). This is all hand-written Scala code, with no reliance on any kind of code generation. That seems to be what you're trying to do. If you want to do this as a learning experience, I think that would be a great project; however, if you want to address specific issues with the existing server, please consider reporting said issues so we can fix them. We're also accepting pull requests, provided you are willing to sign the CLA (so we can keep publishing the project under Apache).

[0]: https://github.com/digital-asset/daml/tree/master/ledger-service/http-json

Code generation only enters the picture when people are writing applications that talk to either the gRPC (or HTTP) API server. The generated code gets embedded in the client; in both cases (HTTP & gRPC), the server knows nothing of the generated code and is not relying on it in any capacity; the generated code is only there to make the application developer's life a bit easier. It is entirely possible to write applications without using the generated code too.

**Comment by gzuhlwang** [comment]
thanks, that's my intention,  building another server in Java, maybe plus java-bindings library or something else.
