### ISSUE TITLE
restrict the format of the configurable ledger-id in the Sandbox

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#674]
- define format
- validate it
- document it in the CLI help

**Comment by gaboraranyossy-da** [comment]
@mziolekda do you remember having any restrictions for this?

**Comment by mziolekda** [comment]
I don't. I would see the value of restricting it to alphanumeric strings with the addition of '_' and '-'

**Comment by stefanobaghino-da** [comment]
Solved by #1362

**Comment by stefanobaghino-da** [comment]
Solved by #1192
