### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by gzuhlwang** [digital-asset/daml#6772]
Hi, daml core team. I came across a problem. 

I directly run Http json API server(with standalone version) in binary form. So does the daml-on-fabric service. The http json api service works well, and I can curl or request it with postman. it will return the replies normally. 

But when I run the http json api service in docker way (also the jar of standalone), it also bootstraps well. I request it with postman, but got `Error: socket hang up`.  

The connection between HTTP json API service and daml-on-fabric, a daml ledger implementation,  is connected.

 I am stuck by that. help me out, please. thanks.

**Comment by garyverhaegen-da** [comment]
For security reasons, all of our servers bind to `localhost` by default. If you're running the json-api and fabric services on the same machine, and querying from that machine as well, that works well.

If, however, one of those components is on a separate machine, you need to explicitly bind to the network interface you want to use, using the `--address` flag. If you are running in a controlled environment and feel comfortable accepting requests from the entire network, you can use `--address 0.0.0.0` to explicitly bind to all network interfaces on the machine.

Note that, from a networking perspective, every Docker container is its own machine, so when running within a Docker container you usually do want to pass `--address 0.0.0.0`.

**Comment by gzuhlwang** [comment]
Yes, they run on the same machine. It is ok.  

The following is the docker container info:
`64d0a5dda64d        http-json-1.3.0                                                                                                                                                               "java -jar /home/dam…"   11 seconds ago      Up 11 seconds       6865/tcp, 0.0.0.0:7575->7575/tcp                   http-json-1.3.0`

Even I explicitly pass `--address=0.0.0.0` to http json api service, I got the same error.
