### ISSUE TITLE
Let evaluation order is backwards for multiple-binding lets, in DAML.

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#6788]
I found an evaluation order bug while writing tests for evaluation order.

In the block below, `X` is evaluated first, then `Y`, then `Z`:

```Haskell
do
    let x = X
    let y = Y
    Z
```

In the block below, `Y` is evaluated first, then `X`, then `Z`:

```Haskell
do
    let x = X
        y = Y
    Z
```

Although there is technically a difference between the first and second, i would expect the evaluation order to be the same, considering that DAML does not allow for self-recursive values.

In general,

```Haskell
let x = X
    y = Y
in Z
```

has the unintuitive evaluation order (`Y`, then `X`, then `Z`).

**Comment by garyverhaegen-da** [comment]
Have you by any chance tried reproducing on the ANF branch?

**Comment by cocreature** [comment]
That is somewhat annoying, it looks like this already comes from desugaring in GHC. Take the following example (`BangPatterns` produce the same result so it’s not a bug in `-XStrict`)
```
{-# LANGUAGE Strict #-}
module Test where

errX = error "x"
errY = error "y"
errZ = error "z"

x = do
    let x = errX
        y = errY
    errZ
```

GHC produces the following Core:
```
x = \ @ a_a20z ->
      case errY of { __DEFAULT -> case errX of { __DEFAULT -> errZ } }
```

So this doesn’t have anything to do with the LF conversion or speedy (and therefore ANF). If ANF “fixes” this, it’s a bug.

**Comment by cocreature** [comment]
It’s also independent of do-notation
```
x =
    let !x = errX
        !y = errY
    in errZ
```
has the exact same issue.

**Comment by cocreature** [comment]
It keeps getting worse:

The issue does not come from desugaring it comes from renaming, specifically from [depAnalBinds](https://gitlab.haskell.org/ghc/ghc/-/blob/6cf8f835267581d551ca6695b3b02c34797e2cf4/compiler/rename/RnBinds.hs#L560) which splits bindings into an ordered list of singleton groups of non-recursive bindings and recursive bindings. This order is then preserved by desugaring. Afaict, `depAnal` or rather the underlying primitives for finding SCCs don’t really guarantee anything about the order here so things get shuffled around in weird (but deterministic) ways. 

I’m not really sure what we can do here short of trying to fix this in GHC which is at the very least a huge timesink. One option would be to try to preprocess the parsed AST but that requires basically replicating the whole SCC logic that GHC has which sounds like a very bad idea.

**Comment by sofiafaro-da** [comment]
Given that we don't allow for recursive let bindings in DAML, would it be crazy to rewrite

```Haskell
let x1 = X1
    x2 = X2
    ...
    xn = Xn
in Y
```

into

```Haskell
let x1 = X1
in let x2 = X2
   in let x3 = X3
      ...
      in let xn = Xn
         in Y
```

in daml-preprocessor, without doing any dependency analysis?

**Comment by cocreature** [comment]
Oh that’s a good point, I had completely forgotten that we don’t allow for recursive bindings (I clearly should not be responding to issues before I’ve had my first coffee). However, that is still a breaking change.
```haskell
let x1 = x2
     x2 = foobar
in baz
```
is currently allowed and would fail with your proposal.

**Comment by cocreature** [comment]
Now I don’t think anyone _should_ be relying on this working in a strict language but that doesn’t mean nobody _is_ relying on this working.

**Comment by garyverhaegen-da** [comment]
> Oh that’s a good point, I had completely forgotten that we don’t allow for recursive bindings (I clearly should not be responding to issues before I’ve had my first coffee). However, that is still a breaking change.
> 
> ```haskell
> let x1 = x2
>     x2 = foobar
> in baz
> ```
> 
> is currently allowed and would fail with your proposal.

Arguably if we want to keep pretending DAML is strict this kind of forward-reference should _not_ be allowed for values, though of course

```haskell
let f x = g x + 2
    g x = 3 * x
in f 4
```
is fine.

**Comment by cocreature** [comment]
If you want to allow it for functions but not for values (ignoring that closures are values in a functional language), this becomes very hard to do at the parsing stage. And while I agree that it should not be allowed that doesn’t change the fact that it’s a breaking change but admittedly one with hopefully little impact and a clear migration path.

**Comment by sofiafaro-da** [comment]
We could do something more intense to make it non-breaking . . . like how we already do for typeclasses This preserves Moritz's & Gary's examples. We translate
 
```Haskell
let x1 = X1
    x2 = X2
    ...
in Y
```

into

```Haskell
let x1 () = X1 [x1 ()/x1, x2 ()/x2, ..., xn ()/xn]
    x2 () = X2 [x1 ()/x1, x2 ()/x2, ..., xn ()/xn]
    ...
    xn () = Xn [x1 ()/x1, x2 ()/x2, ..., xn ()/xn]
in
  let x1 = x1 ()
  in let x2 = x2 ()
     in let x3 = x3 ()
        in ...
           let xn = xn ()
           in Y

**Comment by cocreature** [comment]
Doing the substitution on the GHC AST is probably still fairly annoying and unless you optimize this away later (I believe we don’t atm) this has a performance impact and given how frequent let-bindings are probably a non-trivial one.

**Comment by sofiafaro-da** [comment]
Yeah, I was thinking this would probably have a negative impact on performance. :-( 👎

**Comment by sofiafaro-da** [comment]
At the very least we'd need the lazy primitives to make this not bad. @hurryabit

**Comment by hurryabit** [comment]
I'm open to automatically rewriting `let` bindings @sofiafaro-da suggested in https://github.com/digital-asset/daml/issues/6788#issuecomment-660871599. Although it is a breaking change I would argue that it makes DAML actually better by bringing the semantics of the surface language closer to DAML-LF and we also have a clear migration path.

However, before we dive into this, we should figure out what happens to `where` bindings. I'm assuming that the group of `where` bindings gets wrapped as one `let` binding around the enclosing scope. Do we want to enforce the dependency ordering among there `where` bindings as well? I would say "yes" although I must admit that I'm not a big fan of `where` bindings anyway.

**Comment by sofiafaro-da** [comment]
> I'm assuming that the group of `where` bindings gets wrapped as one `let` binding around the enclosing scope.

They do not! As it turns out, `where` bindings are attached to a particular pattern match and can between many right-hand-sides (e.g. guards) of the same pattern match. The `where` clause does not form an expression, but is part of a pattern match node.

I suggest leaving `where` as is, since it's not even an expression (and doesn't read like a sequence to me), and only rewrite `let` to make the sequencing explicit.

**Comment by hurryabit** [comment]
> I suggest leaving where as is, since it's not even an expression (and doesn't read like a sequence to me), and only rewrite let to make the sequencing explicit.

That sounds very reasonable. I totally agree that `where` blocks don't really suggest an evaluation order, particularly not where the whole block will be moved.

In Haskell, I _personally_ prefer to write
```haskell
do
  let x = X  -- y is not to be used here already
  let y = Y
  ...
```
to avoid accidentally bringing `y` into the scope of `X`. I guess _enforcing_ this in DAML would go a bit too far with regards to breaking existing code... 😞
