### ISSUE TITLE
question about integration daml with Hyperledger Fabric

### ISSUE THREAD

**Issue by gzuhlwang** [digital-asset/daml#6805]
hi, core daml team. I have a question about integration daml with Hyperledger Fabric.

Image a scenario, for example, I have a fabric network with three organization member(Alice,Bob,Carol). They join the same fabric channel. Now, these member wants to choose daml contract language for a new business, such as asset inssurance. they write a daml application, and upload the resulting dar file into DAML ledger, for example, [daml-on-fabric](https://github.com/digital-asset/daml-on-fabric). daml contract runs on daml ledger instead of fabric, I mean. Daml ledger will send the change taken place in daml ledger as a transaction to fabric network. I am not sure about the latter point. If misunderstood, correct me directly please.

My question is whether each of the members(Alice,Bob,Carol) has its own daml-on-fabric service available or sharing a daml-on-fabric service? if the daml-on-ledger is stateless, maybe each member has one. But if not, my understanding is sharing one service, otherwise consistency among these daml ledger may compromise. 

looking forward to u replies. thanks.

**Comment by dasormeter** [comment]
hi @gzuhlwang 

A good place to discuss such questions is the Discuss DAML forum https://discuss.daml.com

Generally if there are three parties that interact with each other in workflows and are running on the same ledger technology, they should collaborate on the same Fabric ledger (called "virtual shared ledger" in the [DAML Ledger Model](https://docs.daml.com/concepts/ledger-model/index.html) docs).

Each party should be allocated to a ledger api instance on that Fabric network  and they can either run on a shared ledger api instance or on separate physical ledger api servers, but which all belong to the same Fabric network.

If you have any further follow-up questions, I'd suggest you raise on the discuss forum.

Hope this helps to clarify

-Brian

**Comment by gzuhlwang** [comment]
@dasormeter  thanks. It's helpful to me.
