### ISSUE TITLE
Properly use LoggingContext in Participant Server

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#6837]
There are quite a few classes where we pass the `LoggingContext` to the constructor, instead of the individual methods.
This means that the log lines of the methods will use the logging context that was used during initialization. The result is that call-specific information (e.g. party, beginOffset, endOffset, ...) are not actually logged.

Basically, the logging context needs to be passed along the chain from where the request is received to where the data for the request is fetched.

Example chain:
`ApiTransactionService#getTransactions` 
  -> `IndexTransactionService#transactions` (impl: `LedgerBackedIndexService`) 
  -> `ReadOnlyLedger#flatTransactions` (impl: `BaseLedger`) 
  -> `TransactionsReader#getFlatTransactions`

Examples of where the wrong logging context (from the class' constructor) is being used:
* [`JdbcLedgerDao`](https://github.com/digital-asset/daml/blob/4b1438276c6d2c5c6f31fafdf0847a8eb20f7fb6/ledger/participant-integration-api/src/main/scala/platform/store/dao/JdbcLedgerDao.scala#L89)
* [`TransactionsReader`](https://github.com/digital-asset/daml/blob/4b1438276c6d2c5c6f31fafdf0847a8eb20f7fb6/ledger/participant-integration-api/src/main/scala/platform/store/dao/events/TransactionsReader.scala#L42)

This pattern is quite pervasive throughout the code base and requires adding an implicit logging context to the methods of internal interfaces (e.g. `Index*Service`, `LedgerDao`, `Ledger`, ...)

**Comment by stefanobaghino-da** [comment]
That was originally done on purpose to avoid spreading the logging context in every single signature.

I think it would also make sense to spend a few cycles thinking whether we want to keep this mechanism around.

Purely as food for thought, if we switch to a thread-based model (instead of using Akka to handle concurrency), we could use a simpler `ThreadLocal`-based mechanism like MDC. Alternatively, I don't know whether Akka exposes some feature to enrich logs.

**Comment by gerolf-da** [comment]
> That was originally done on purpose to avoid spreading the logging context in every single signature.

But that entirely defeats the purpose of the logging context. 

> Purely as food for thought, if we switch to a thread-based model (instead of using Akka to handle concurrency), we could use a simpler ThreadLocal-based mechanism like MDC. Alternatively, I don't know whether Akka exposes some feature to enrich logs.

I agree that it'd be worth looking into that, but fixing the logging context on the existing model is a rather straightforward mechanical change, whereas changing the thread model will take much much longer.

**Comment by stefanobaghino-da** [comment]
> But that entirely defeats the purpose of the logging context.

Not really, we have many places where we have used it. We made a conscious choice when we used that to not flood the entire codebase.

**Comment by stefanobaghino-da** [comment]
> I agree that it'd be worth looking into that, but fixing the logging context on the existing model is a rather straightforward mechanical change, whereas changing the thread model will take much much longer.

Depends on how deep we want to go. In the extreme case we may end up needing to make choices regarding signatures of public APIs that we may not want to change.

**Comment by gerolf-da** [comment]
> > But that entirely defeats the purpose of the logging context.
> 
> Not really, we have many places where we have used it. We made a conscious choice when we used that to not flood the entire codebase.

I understand the argument about not wanting to flood the code base, but if the logging context is not passed along the call chain, then building up the context in the first place seems quite pointless. For example, the context built up in `ApiTransactionService#getTransactions` is only used for a single log line. Instead of the logging context machinery, it's probably easier to simply make the additional values part of the log line itself directly. (I understand there are other benefits like consistency across logging lines):
https://github.com/digital-asset/daml/blob/7ce9748066e01cc4bb26ac1297fe091f435d91e9/ledger/participant-integration-api/src/main/scala/platform/apiserver/services/transaction/ApiTransactionService.scala#L68-L78

The value of the logging context comes from adding data to the context on the outside (e.g. after request validation), that is then automatically logged as part of subsequent log statements further down the processing pipeline (e.g. in database lookups), allowing to make a connection from the "inside" to the "outside".

The question one of the questions we need to answer is: do we want to use that mechanism and fully embrace it or do we look for a different one.

> > I agree that it'd be worth looking into that, but fixing the logging context on the existing model is a rather straightforward mechanical change, whereas changing the thread model will take much much longer.
> 
> Depends on how deep we want to go. In the extreme case we may end up needing to make choices regarding signatures of public APIs that we may not want to change.

Yes, one of the APIs where there will be a boundary is `ReadService` and `WriteService`. I'm willing to accept that for now. The rest of the participant server should really be internal private api.

**Comment by stefanobaghino-da** [comment]
Thanks for the detailed post, I found it very sensible and agree with all your arguments. I was mostly trying to persist in this conversation the historical context that lead to this situation (which I agree is sub-optimal).

> The question one of the questions we need to answer is: do we want to use that mechanism and fully embrace it or do we look for a different one.

I'm tempted to say we should embrace it fully, but let's keep the conversation open.

**Comment by gerolf-da** [comment]
Sorry, I didn't try to argue "against" you, but simply that either we use the approach properly, or just don't bother with it. It's the middle ground that doesn't provide much benefit. 👍

**Comment by stefanobaghino-da** [comment]
Kudos for writing down and detailing that we want the logging context to spread through the index service, I could refer back to the ticket while working on this. :bow:

**Comment by stefanobaghino-da** [comment]
Note that passing down the logging context to services via constructors is helpful: the logging context created when instantiating the service handler contains (at the very least) the participant identifier. Instead of creating a brand new logging context this information can be enriched by individual endpoints.
