### ISSUE TITLE
Uninhabited recursive types in daml2ts/daml-types

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6840]
Currently a type like
```
data X = X with
  f : X
```
will produce a stackoverflow in the decoder in daml2ts since the field in the record is not lazy.

While this type is pretty useless and I expect all instances to be bugs, the error is also pretty useless.
There are a few options here:

1. Make the decoders for record fields lazy. Fixes the issue but probably regresses in performance (although perhaps not in significant ways). Doesn’t address the fact that users probably didn’t intend to write this.
2. Detect this case and special case the decoder, e.g., to always fail since there is no value of this type. Like 1 but no performance impact for other types. We could also warn about this here.
3. Detect this case and error out. Clearly means that this is unsupported but I don’t see why that’s an issue.

My preference currently is for 2 or 3.

**Comment by cocreature** [comment]
I’m not aware of anyone having run into this issue so regardless of what we do, I do not consider this a high priority ticket.

**Comment by hurryabit** [comment]
Fixed by #6898.
