### ISSUE TITLE
Recommend approach for DAML applications to support participant node failover

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#6842]
# Context

Some DAML Ledgers support exposing multiple eventually consistent Ledger API endpoints hosted by separate participant nodes. This can be used to support failing over from participant nodes hosted in a primary DC to ones hosted in a  secondary DC. There seems to be a clear recommended approach for how an applications supports such a failover: the DAML Application stores the offset of the last received event from `GetTransaction(Tree)s` and resubcribes from there on the backup Ledger API endpoint while retrying on `INVALID_ARGUMENT: "offset <givenOffset> is after ledger end <ledgerEndOffset>"` errors.

The [gRPC Status Code Documention](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) hints at using `OUT_OF_RANGE` instead of `INVALID_ARGUMENT` for the error above. This way the Ledger API server clearly signals that retrying is the right action to do for the application.

# Acceptance Criteria

1. The DAML SDK docs explain this approach.
2. The status code for the above error has been changed to `OUT_OF_RANGE` 

# Related Work

This ticket addresses part of the outstanding Ledger API status code review from #1638.

FYI: @gerolf-da @daravep @mziolekda @bame-da @piyushbedida

**Comment by meiersi-da** [comment]
FYI: @piyushbedi-da

**Comment by daravep** [comment]
Please note that `OUT_OF_RANGE` is already used if a block is requested that has been pruned.
https://github.com/DACH-NY/canton/blob/master/demo/src/main/scala/com/digitalasset/canton/demo/DemoUI.scala#L277

So it is important to be able to distinguish both cases. Also, as you see from the code I've referenced, we currently struggle to properly communicate what the new `LedgerOffset.Begin` is after pruning. (@oliverse-da @oggy- )

**Comment by meiersi-da** [comment]
Given the description of gRPC status codes (see above), `OUT_OF_RANGE` seems not appropriate for blocks being requested that have been pruned, as the system is not expected to move back into a state where this error goes away.

@oliverse-da @oggy- :  Have you've had a look at the richer error model on https://grpc.io/docs/guides/error/?

**Comment by oggy-** [comment]
I haven't looked at the gRPC errors closely before. But from a cursory look, for pruned offsets, I'm not reading the guidelines the same way as you are, `OUT_OF_RANGE` is just contrasted to `INVALID_ARGUMENT` there; the latter is invalid no matter the state, the former might've been valid in some other state. Still, if we want to switch the pruning error, I guess `NOT_FOUND` and even `DATA_LOSS` are also viable candidates.

Regardless of the code, I guess the bigger question is is we want to switch to the richer error model. If we do, we should do so uniformly for all errors with data payloads.

**Comment by oliverse-da** [comment]
While the label `OUT_OF_RANGE` suggests that the error could apply a read being not just "too high" but also "too low" , the description suggests "too high", so wrt that `OUT_OF_RANGE` can be misleading. I'd say `NOT_FOUND` is less alarmist/misleading than `DATA_LOSS`, so `NOT_FOUND`.

We looked at structured grpc errors such as `ErrorInfo.metadata` (https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto#L135) - which would let us set properties. However it looks as if we are missing support by scalapb for this as of yet?

**Comment by meiersi-da** [comment]
@oliverse-da : the proposal for `OUT_OF_RANGE` stems from the guidance given on https://grpc.github.io/grpc/core/md_doc_statuscodes.html for how to retry. `OUT_OF_RANGE` is describe in language that does sound like a transient error; and the example of reading a file has exactly the same characteristics as reading from the ledger starting at a specific offset.

As for pruning, I would suggest using the `FAILED_PRECONDITION`, as this allows the pruned ledger to restore the data (if it would want so), but is explicit wrt the fact that just retrying won't work. The precondition check is exactly that 'Offset has not yet been pruned.'

What do you think?

**Comment by oliverse-da** [comment]
> @oliverse-da : the proposal for `OUT_OF_RANGE` stems from the guidance given on https://grpc.github.io/grpc/core/md_doc_statuscodes.html for how to retry. `OUT_OF_RANGE` is describe in language that does sound like a transient error; and the example of reading a file has exactly the same characteristics as reading from the ledger starting at a specific offset.
> 
> As for pruning, I would suggest using the `FAILED_PRECONDITION`, as this allows the pruned ledger to restore the data (if it would want so), but is explicit wrt the fact that just retrying won't work. The precondition check is exactly that 'Offset has not yet been pruned.'
> 
> What do you think?

Sounds plausible. I will move this discussion to the pruning design doc.
