### ISSUE TITLE
create-daml-app: Module not found: Can't resolve '@daml.js/create-daml-app'

### ISSUE THREAD

**Issue by naman1303** [digital-asset/daml#6869]
**Detail:**
I have created an application using exactly the same steps as mentioned in DAML [link](https://docs.daml.com/getting-started/index.html) but compilation fails when trying to bring up UI.

**Problem:**
On "yarn start", I am getting below error:

> Failed to compile.
> 
> ./src/components/LoginScreen.tsx
> Module not found: Can't resolve './../daml.js/create-daml-app' in '$HOME/create-daml-app/ui/src/components'
> 

Same error occurs for MainView.tsx and UserList.tsx files as well, coz it is stuck at below auto generated import statement.
```
import { User } from '@daml.js/create-daml-app';
```

**Possible Reason**

_$HOME/create-daml-app/ui_ doesn't have @daml.js in its node_modules. Rather this package is present inside daml.js folder due to below command:

> daml codegen js .daml/dist/create-daml-app-0.1.0.dar **-o daml.js**

So I instead ran below command (i.e. generated the node_modules in current dir):

> daml codegen js .daml/dist/create-daml-app-0.1.0.dar **-o .**

and corrected the tsx files (generated folder has 0.1.0 appended to it):
```
import { User } from '@daml.js/create-daml-app-0.1.0';
```

and it worked. I know this is not a solution and just a workaround. 

Please fix it in the codebase or clarify if my understanding is wrong .

**Comment by cocreature** [comment]
Hi @naman1303,
There are a few things that play together here to make this work:
1. `daml codegen js .daml/dist/create-daml-app-0.1.0.dar -o daml.js` will generate the JS code and the TypeScript declaration files in the `daml.js` directory.
2. The `package.json` file in the `ui` directory references this directory, see https://github.com/digital-asset/daml/blob/v1.3.0/templates/create-daml-app/ui/package.json.template#L6.
3. Running `yarn install` in the `ui` directory will look at the `package.json` file, see the location of `create-daml-app` and install it in `ui/node_modules`. At this point, things are setup correctly.

When you make changes to your DAML model, you have to run through the following steps:
1. `daml build` to update `.daml/dist/create-daml-app-0.1.0.dar`.
2. `daml codegen js .daml/dist/create-daml-app-0.1.0.dar -o daml.js` to update the generated JS and TypeScript declarations in `daml.js`.
3. `yarn install --force --frozen-lockfile` from the `ui` diirectory which will update the copy of the generated code in `ui/node_modules`.

The docs describe the same steps and I just tested that this still works for me. Which SDK version are you using? Maybe you missed one of the steps?

**Comment by naman1303** [comment]
Version - 1.3.0 
I understand your 3rd point and believe this is where the problem occurred. 

_3. Running yarn install in the ui directory will look at the package.json file, see the location of create-daml-app and install it in ui/node_modules. At this point, things are setup correctly._

This command failed for me, attaching the error screenshot:
> yarn install --force --frozen-lockfile  

So I explicitly ran "npm install", and so, my ui/node_modules doesn't have @daml.js/create-daml-app

![vmware_vm_error6](https://user-images.githubusercontent.com/41565380/88538397-ec4f9b80-d02c-11ea-8dc0-cb6428e43f5e.PNG)

Can you mention this detail (3rd point) on the page https://docs.daml.com/getting-started/index.html or provide a similar command in npm?

**Comment by cocreature** [comment]
You have to upgrade to NodeJS 10 or later. NodeJS 8 is no longer receiving security updates. Once you have upgraded, the command should work fine. I’ll make sure to clarify that in the documentation.

**Comment by naman1303** [comment]
Thank you for the prompt response @cocreature . I am closing the request now.
