### ISSUE TITLE
daml-assistant auto-installs and auto-upgrades.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#687]
**Background:** daml-assistant has to manage multiple SDK versions and itself. Right now there is no auto-installing and auto-updating, but we should probably figure out a good way to do this before users get the new assistant, so we can avoid the situation where users are using an old version of the assistant.

So in light of this, I would say the top priority is to decide how daml-assistant auto-upgrades should work.

**A: auto-install:**  When the user specifies an SDK version, be it in the project config or by passing the DAML_SDK_VERSION environment variable, and the SDK version is not installed, the assistant should either:

1. install the requested version automatically
2. ask the user if they want to install the requested version
3. fail, and tell the user to run the appropriate `daml install` command first

My preference is for 1 as long as the user can turn this behavior off in the user's config file (`~/.daml/daml-config.yaml`), and if they turn it off it will fall back to 3.

**B: daml-assistant auto-upgrades:** When the user is running an outdated version of daml-assistant, we should get them to upgrade. This means installing the latest stable version of the SDK whenever it is available. We can either:

1. install the latest version automatically
2. ask the user if they want to install the latest version
3. beg the user to run `daml upgrade` (not implemented yet, but it's just a special case of `daml install`)

My preference is for 1 as long as it is configurable (like above), but this is perhaps a bit rude since the download is substantial (~300MB). I wonder if we should do it in the background?

**C: project sdk-version updates:** daml projects specify an sdk version in the project config file (`daml.yaml`). This version can become outdated over time. What do we do?

1. nag the user to update the project config to a later sdk version,
2. ask the user if they want to update the sdk version for the project, and do it for them
3. have floating versions by default, i.e. the project sdk version is always the latest stable version.

My preference is for 1. I don't like the idea of changing config files in code, and 3 is scary.

**Comment by neil-da** [comment]
Why not A1, B0, C1 in that order? You auto-install for users. You never auto-upgrade, but you nag about sdk-version updates, and if they obey, the first 1 kicks in to get it for them.

I'm also a little partial to C2. It just makes it easier for them, but console UI's are also a pain. Slightly tempted to do C2 in the IDE. However, C2 can be done later.

**Comment by associahedron** [comment]
> Why not A1, B0, C1 in that order? You auto-install for users. You never auto-upgrade, but you nag about sdk-version updates, and if they obey, the first 1 kicks in to get it for them.
> 
> I'm also a little partial to C2. It just makes it easier for them, but console UI's are also a pain. Slightly tempted to do C2 in the IDE. However, C2 can be done later.

And you would upgrade daml-assistant whenever we install the latest stable version?

**Comment by neil-da** [comment]
> And you would upgrade daml-assistant whenever we install the latest stable version, which is the version we nag users to update their project configs to?

Yep. Given we have now gutted the daml-assistant, the only relevant variable is if it's still able to upgrade. And for that, if it can't, we are out of luck anyway, so I don't see any need to force them forward quicker.

**Comment by associahedron** [comment]
That's a good point :+1:

**Comment by cocreature** [comment]
Strongly in favor of A1 and C1. I don’t have particularly strong feelings about upgrading `daml-assistant` except for the fact that I don’t like fully automatic upgrades so I would go for B2 if we do it but I tend to agree with Neil that there is probably little reason to upgrade the assistant on its own.

**Comment by associahedron** [comment]
This is already done. There's always more that can be done to improve it, but should be raised as a separate issue.
