### ISSUE TITLE
Navigator: Don't use SQLite unless requested

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#6873]
Navigator has a CLI flag to use SQLite instead of the custom in-memory database: `--database`.

The SQLite database is created by the [DatabaseActions](https://github.com/digital-asset/daml/blob/master/navigator/backend/src/main/scala/com/digitalasset/navigator/data/DatabaseActions.scala) class, which is instantiated regardless of the CLI flag: [Ledger.scala#L29](https://github.com/digital-asset/daml/blob/master/navigator/backend/src/main/scala/com/digitalasset/navigator/model/Ledger.scala#L29).

This makes Navigator incompatible with all systems for which no SQLite binaries are bundled by [xerial/sqlite-jdbc](https://github.com/xerial/sqlite-jdbc/tree/master/src/main/resources/org/sqlite/native).

To fix the issue, instantiate `DatabaseActions` only if necessary.

**Comment by anthonylusardi-da** [comment]
Big thank you to arton on the forum for reporting this issue!

https://discuss.daml.com/t/error-starting-navigator/916

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
