### ISSUE TITLE
Make address trigger service listens on configurable

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6946]
Currently the trigger hardcodes localhost as the interface to listen on. That’s clearly a bad idea and we should make this configurable. Sandbox and the JSON API both call this parameter `--address` so we should follow that to be consistent.

**Comment by garyverhaegen-da** [comment]
Note that hardcoding `localhost` is a much less bad idea than hardcoding `0.0.0.0`. Whoever works on this please keep `localhost` the default when the `--address` flag is not specified, both for security reasons and for consistency with the other DAML tools we provide.

**Comment by cocreature** [comment]
Fully agree with that, I’d like this to behave like the JSON API, Sandbox and other tools in that it defaults to localhost but makes it configurable.
