### ISSUE TITLE
Speed up projection of structural records

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#6953]
Currently, projections of structural records use a linear search by field name to find the right field. Since two structural record types are only considered equal if they have the same field names in the same order and with the same types, we should be able to _statically_ determine the index of the field we're projecting onto. This would allow for constant-time field access at runtime and hence make the selection of type class methods faster.

**Comment by hurryabit** [comment]
I've done a quick prototype for this and benchmarked the function
```haskell
mysum = foldl (\x y -> x+y) aunit
```
applied to the (pre-computed) list `[1..1_000_000]`.

When I equip `mysum` with the type signature `[Int] -> Int`, i.e., when no dictionary lookups are involved, this takes ca. 174ms. When I change the signature to `Additive a => [a] -> a`, it takes ca. 460ms. That means the overhead of a single dictionary lookup (for the addition function) is ca. 286ns. Implementing the change described above, decreased the time of the version with dictionary lookups to ca. 444ms and the overhead accordingly to ca. 270ns.

I conclude that we should focus our energy on making the other aspects of dictionary lookups faster before implementing a proper version of the change proposed here.

**Comment by cocreature** [comment]
Closing for now.
