### ISSUE TITLE
Automatically add daml binaries to path in Linux/Mac

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#6991]
At the end of installation you get the message:

```
Please add /Users/nicholasho/.daml/bin to your PATH.
```

It would be great if the installer had a prompt along the lines of `Add daml to PATH in $0 [Y/n]` or a runtime option/flag that would automatically do this for the user and maybe `source ~/.their_rc` so that once installation is complete immediately running `daml` works.

Same could be done for shell completions as well (zsh seems to need an additional line added to `.zshrc`)

Thanks to Nicholas for [pointing out this issue on the forum](https://discuss.daml.com/t/command-not-found-daml/982/3)

**Comment by leo-da** [comment]
Another option is to make the output that tells user to update their PATH to stand out from all the other output.

E.g. instead of 
```...
Please add /Users/<username>/.daml/bin to your PATH.
Bash completions installed for DAML assistant.
Zsh completions installed for DAML assistant.
To use them, add '~/.daml/zsh' to your $fpath, e.g. by adding the following
to the beginning of '~/.zshrc' before you call 'compinit':
fpath=(~/.daml/zsh $fpath)
```
we can print something like this:
```...
###########################################################
Please add /Users/<username>/.daml/bin to your PATH.
###########################################################

Bash completions installed for DAML assistant.
Zsh completions installed for DAML assistant.
To use them, add '~/.daml/zsh' to your $fpath, e.g. by adding the following
to the beginning of '~/.zshrc' before you call 'compinit':
fpath=(~/.daml/zsh $fpath)
```

**Comment by hurryabit** [comment]
@robin-da That one's done now, right? If so, please feel free to close it.
