### ISSUE TITLE
Check if /tmp dir is large enough for install and fail or provide an alternative if it's not

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#6993]
As [airplatform3 encountered on the forum](https://discuss.daml.com/t/debian-buster-and-ubuntu-beaver-feedback-on-installing-daml/884) if your `/tmp` dir is too small the daml installation script will fail.

I'm not sure of the error message provided but there's some possible ways to improve this issue:

- Provide an error message that links to an alternative installation path that avoids `/tmp`. In airplatform3's post they mention that they were able to manually download the release and run `install.sh`
- Offer to use `./tmp` and cleanup afterwards

**Comment by hurryabit** [comment]
@robin-da That looks like a quick and useful one.

**Comment by robin-da** [comment]
@hurryabit I'll look into it.
