### ISSUE TITLE
TypeScript streamFetchByKey should support multiple {template, key} pairs per request

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#7034]
JSON API supports multiple `template, key` pairs per `/v1/stream/fetch` request. See the doc: https://docs.daml.com/json-api/index.html#fetch-by-key-contracts-stream

```
[
    {"templateId": "<template ID 1>", "key": <key 1>},
    {"templateId": "<template ID 2>", "key": <key 2>},
    ...
    {"templateId": "<template ID N>", "key": <key N>}
]
```

However TS bindings' `streamFetchByKey` is defined like this:
```
streamFetchByKey<T extends object, K, I extends string>(
    template: Template<T, K, I>,
    key: K,
  ): Stream<T, K, I, CreateEvent<T, K, I> | null> {
```

You are actually wrapping the pair in the array:
```
const request = [{templateId: template.templateId, key}];
```

## ACs
- API user can specify multiple `templateId, key` pairs per request

**Comment by stefanobaghino-da** [comment]
@garyverhaegen-da is this closed by https://github.com/digital-asset/daml/pull/7066?

**Comment by stefanobaghino-da** [comment]
@garyverhaegen-da I'll close this optimistically, please re-open if the issue has not been closed by the PR in the comment above.

**Comment by garyverhaegen-da** [comment]
As explained in #7066, this issue is not fully covered: we can now pass multiple queries, but not multiple template IDs.

However, it does not look like anyone wants to champion the case for multiple template IDs anymore, so I'm happy to close this as "won't fix". Same goes for #7036.
