### ISSUE TITLE
TypeScript streamQuery should support multiple {template, query} pairs per request 

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#7036]
JSON API allows specifying multiple `template, query` pairs per request, see https://docs.daml.com/json-api/index.html#fetch-by-key-contracts-stream

TypeScript bindings' `streamQuery` defined as:
```
streamQuery<T extends object, K, I extends string>(
    template: Template<T, K, I>,
    query?: Query<T>,
  )
```

## ACs
- API user can specify multiple `template, query` pairs per request

**Comment by stefanobaghino-da** [comment]
Looks like this has been closed by https://github.com/digital-asset/daml/pull/7066. @garyverhaegen-da if that's not the case, feel free to reopen.
