### ISSUE TITLE
Test participant server support for Ledger API endpoint fail-over

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#7038]
# Context

The guidance for DAML application authors provided in #6875 needs to be tested. Due to time-pressure that has not been handled as part of that merge request yet.

# Acceptance Criteria

There is a test demonstrating a DAML App running against a Ledger with two API endpoints that serve the same Ledger API content. The test MUST

- [ ] exercise the support for command deduplication across the two endpoints
- [ ] exercise the support for `OUT_OF_RANGE` errors due to the secondary endpoint being behind.

FYI: @rautenrieth-da @gerolf-da

**Comment by SamirTalwar-DA** [comment]
By "test", do you mean an automated test running as part of this repository build?

If so, which ledger would we use to allow for two API frontends?

We could use _ledger-on-memory_ or _ledger-on-sql_ if we spent some time detaching the ledger side from the API server and indexer so it can run in a separate process. I'm not aware of any open-source ledger implementation that fulfills this requirement otherwise.

**Comment by meiersi-da** [comment]
@SamirTalwar-DA thanks for looking into this! As for "test", I do mean that there is a test of this example application in CI.

I have a hunch that we have most of the components, but need some extra orchestration. The hunch is based on me seeing the mulit-participant test here (https://github.com/digital-asset/daml/blob/4b1438276c6d2c5c6f31fafdf0847a8eb20f7fb6/daml-script/test/BUILD.bazel#L251). The orchestration is what, I'd like to ask you to figure out.

Apart from the option of running two endpoints directly, there might also be the option of working with different index-dbs.

I do though not know what the cheapest option is to build and maintain a meaningful test for this failover behaviour. If you could investigate and propose an approach here, then that would be awesome!

**Comment by SamirTalwar-DA** [comment]
Oh, that's right, we can run multiple participants in the same process, sharing the in-memory ledger. That works, but I think that we'd need to introduce an artificial delay in one of the participants in order to actually trigger the `OUT_OF_RANGE` errors.

I think we can add tests to the test tool to support this, as long as you're OK with a "manual" switchover, i.e. the test queries the transaction stream from one participant, then uses the latest offset to query the other.

**Comment by meiersi-da** [comment]
Thanks @SamirTalwar . What do you mean by "manual" switchover? What do you propose as the best way forward of who does what such that ultimately a test with the properties described in the ticket is run in CI?

**Comment by SamirTalwar-DA** [comment]
I mean that rather than having some kind of automatic switchover based on failure detection, we simply ask the client to query participant 1, then query participant 2, explicitly in the code.

**Comment by rautenrieth-da** [comment]
@meiersi-da Just to clarify the acceptance criteria:

> exercise the support for OUT_OF_RANGE errors due to the secondary endpoint being behind.

There are already unit tests for this, see for example [here](https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-common/src/test/suite/scala/com/digitalasset/ledger/api/validation/CompletionServiceRequestValidatorTest.scala#L83).

I can additionally add a test to the conformance test tool that takes the ledger end, prepends a non-zero byte to it, and tries to subscribe at that offset. This would demonstrate at the ledger API level that subscribing to future offsets returns the correct error. Do you think such a test is necessary, and if yes, would it fullfill the AC?

> exercise the support for command deduplication across the two endpoints

Command deduplication is not guaranteed to work across participants, and the conformance test tool does not know whether all of the provided endpoints belong to the same participant. We can therefore not easily add this to the conformance test tool.

I propose we do the following:

- Extend the kvutils `Runner` such that it's capable of starting multiple ledger API servers for one indexer. This would simulate a "horizontal scaling" setup.
- Add a test that starts a `ledger-on-memory` with one participant/indexer and two ledger API servers, and then submits the same command to both ledger API servers at the same time. This would demonstrate that command deduplication works across two endpoints belonging to the same horizontally scaled participant.
- Add a test that starts a `ledger-on-memory` with two participants/indexers, and then submits the same command to both ledger API servers at the same time. This would demonstrate that the optional cross-participant command deduplication works on a kvutils ledger.

@gerolf-da @SamirTalwar The last point is contrary to what we discussed, but the Runner can already easily start two different participants for the same ledger, and we know that cross-party command deduplication works in kvutils, so this test would not come at any extra cost. Or am I missing anything?

@meiersi-da Would this fulfill the AC?

**Comment by SamirTalwar-DA** [comment]
That sounds great to me. Perhaps you can improve `ParticipantStateIntegrationSpecBase` to cover this behavior for all kvutils-based ledgers?

**Comment by meiersi-da** [comment]
@rautenrieth-da thanks for the detailed proposal. It does not fully satisfy the AC. The motivation for the AC as it is written (intro sentence plus the two properties) is to double-check that application authors following our guidance in the SDK will be able to build and run an application that falls over correctly. So this is much more of an integration test, than a battery of unit tests.

Findings that I could see coming up due to building this test are of two kinds: 
1. our instructions don't really work due to some oversights on how the Ledger API actually works, and/or
2. there are bugs in the Ledger API server or the kvutils backend.

So, concretely I'm looking for a proposal of how (1) to build a demo app as per our guidelines and (2) how the test would orchestrate the demo app running against a kv-ledger of your choice, such that the `OUT_OF_RANGE` and command dedup guarantees are tested.

The larger context for writing this test is that it passing successfully will also prove that duplicate participant nodes can be used for HA purposes.

@gerolf-da @rautenrieth-da : what do you think?

**Comment by gerolf-da** [comment]
The reason for the "reduced" proposal was the following:
To reliably simulate a participant being "behind", we would likely have to add some functionality to the participant server/runner to delay reading from the ledger (which kind of defeats the purpose of testing the production code path.
The second possibility I see is to build an elaborate setup of a SQL-backed KV Ledger, involving DB dumps at various stages or manually deleting data from the index DB. But even then I think one would have to generate a lot of data in the first place to ensure that there is enough time for the test to run reliably.

I agree that having such a test/demo app to show the full end-to-end behavior would be great, but I'm wondering whether it's the best investment of our time. Could we fulfill the requirements on a "smaller scale" as well?

**Comment by meiersi-da** [comment]
I agree with you @gerolf-da on both counts: it would be good, but I'm unsure as to it being the best investment of time right now.

What about the following way forward:
1. We implement the reduced proposal by @rautenrieth-da ; incl. the added check in the Ledger API test tool.
2. We capture an issue against the privacy-aware kv integration reference architecture, where building such a test using https://github.com/Shopify/toxiproxy is easier due to its distributed nature.

**Comment by rautenrieth-da** [comment]
> We capture an issue against the privacy-aware kv integration reference architecture, where building such a test using https://github.com/Shopify/toxiproxy is easier due to its distributed nature.

How would that work? Starting a ledger with two nodes hosting the same party, where network communication between the nodes is delayed?

In any case, this test would then use the ledger-side command deduplication, which means the first AC ("exercise the support for command deduplication across the two endpoints") would only be tested on this specific ledger implementation and ledger setup. I assume that is fine?

**Comment by meiersi-da** [comment]
Ye

> > We capture an issue against the privacy-aware kv integration reference architecture, where building such a test using https://github.com/Shopify/toxiproxy is easier due to its distributed nature.
> 
> How would that work? Starting a ledger with two nodes hosting the same party, where network communication between the nodes is delayed?

Yes.
> 
> In any case, this test would then use the ledger-side command deduplication, which means the first AC ("exercise the support for command deduplication across the two endpoints") would only be tested on this specific ledger implementation and ledger setup. I assume that is fine?

Yes.
