### ISSUE TITLE
Should we rate-limit triggers?

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7044]
This is related to #7043. I’m wondering, if it would make sense to add some client-side limit on commands/second emitted by the trigger or something similar.
Not sure this is necessary (assuming we handle back pressure) or a good idea so deliberately phrasing this as a question.

**Comment by S11001001** [comment]
* [ ] depends on #7753

**Comment by S11001001** [comment]
Revert 7942686506e5f5f1e1acba8a59884b3a92145ee4 for a start.

**Comment by cocreature** [comment]
Given that we handle backpressure now, I’ll close this until we get requests for this.
