### ISSUE TITLE
Proposal: Displaying Contract IDs in off-ledger DAML

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7114]
Currently, both DAML Script and DAML Triggers are unable to display (i.e., convert to Text) contract IDs. While we do have a `Show` instance, it always returns the string `"<contract-id>"` (literally) which is clearly not very useful. This makes debugging significantly harder and we have gotten feedback to that effect quite a few times (it also matches my own experience).

While there are good reasons for not being able to convert a contract id to `Text` in ledger code this does not hold for off-ledger DAML. In fact, this is something that is trivial to accomplish in all other client bindings. I don’t want to punish our users for trying to use DAML here as well and in fact we recommend it in quite a few instances so I believe we have to address this problem.

## Proposal

- Add a `contractIdToText : ContractId -> Optional Text` primitive to LF.
- Add a flag to the speedy `Machine` class to specify whether we are running on-ledger or off-ledger. In on-ledger mode we always return `None`. In off-ledger mode we return the contract id as `Text`.
- As for the spec, it’s not that hard to add a flag to that as well or alternatively we could completely ignore the off-ledger part since having a spec for that is far less crucial.
- Implement the `Show` instance of `ContractId` in terms of this new primitive keeping the behavior for the on-ledger part to return `"<contract-id>"`.

## Alternatives

- Instead of returning an `Optional Text` we could return `Text` and return an empty text or `"<contract-id>"` or whatever other magic string you come up with. I prefer the `Optional` since it moves the default used in the `Show` instance out of the LF-spec but I don’t feel strongly about this.

## Alternative Ideas that don’t work

1. Using a separate `ContractId` type for DAML Script and DAML Triggers. This seems appealing initially and works for things like `exercise` and ACS queries. But it falls apart as soon as you have a field of type `ContractId` in a template or choice argument. Since we reuse those types you now have to interact with both the builtin `ContractId` type and the one provided by the respective APIs and convert between the two and it just becomes a mess.

2. Provide a separate `contractIdToText` primitive as part of DAML Script/DAML Triggers without making it a general LF primitive. This falls into a similar trap as 1. If I call `show` on a template with a `ContractId` field I want to see the actual contract id and not have to extract it and then call `contractIdToText` on it.

**Comment by cocreature** [comment]
cc @hurryabit @remyhaemmerle-da

**Comment by hurryabit** [comment]
IIRC, one of the reasons why we didn't want a function to convert contract IDs into text was because of the split between local/relative and global/absolute contract IDs and the rewriting that happened after the transaction was built. Since we have removed this rewriting step now and there is only one notion of contract ID, we should put the option of implementing a function to convert contract IDs to text that works the same across all runtimes back on the table. Such a function could clearly be misused but I don't think that should be the only argument stopping us from adding it. Are there any other downsides I'm missing?

**Comment by cocreature** [comment]
My understanding was that ledgers are still free to change contract ids and canton does that.. What they have to do is preserve a prefix or some mapping to the original “relative” contract id. So converting to text doesn’t work.

**Comment by remyhaemmerle-da** [comment]
@cocreature is right.

**Comment by hurryabit** [comment]
Given that ledgers are still allowed to change contract IDs, I think we should go with the original proposal. From the point of view of the DAML-LF specification, which currently only captures the on-ledger use of DAML, the new primitive always returns `None`. What do you think about using this as the spec of the new primitive until we potentially extend it to also cover the triggers/script use cases?

**Comment by cocreature** [comment]
Sounds reasonable to me. Definitely the simplest option :slightly_smiling_face:
