### ISSUE TITLE
SandboxIndexAndWriteService#inMemory is public but cannot be called

### ISSUE THREAD

**Issue by curiousleo-da** [digital-asset/daml#7121]
`com.daml.platform.sandbox.stores.SandboxIndexAndWriteService#inMemory` defined in `sandbox-classic` is public. It takes an argument of type `com.daml.platform.packages.InMemoryPackageStore`, which is package-private and for which no public creation method exists (as far as I can tell). As a result, there is no way from outside the package to instantiate an `InMemoryPackageStore`; as a result, `SandboxIndexAndWriteService#inMemory` cannot be called.

Suggestions:
- Make `SandboxIndexAndWriteService` package-private
- Add a way to instantiate an `InMemoryPackageStore` from outside the package

**Comment by SamirTalwar-DA** [comment]
It's public (and probably could be package-private), but we don't expect _anything_ to depend on _sandbox_ or _sandbox-classic_; they are applications, not libraries.

If there's something you need from Sandbox, please extract it to a library. Sandbox is not a public interface to anything, and any dependents will probably break in the future.

**Comment by SamirTalwar-DA** [comment]
`SandboxIndexAndWriteService` is now private, so the inconsistency has vanished. 😉 

If there's something you need from the Sandbox Classic code, feel free to yell and I'm sure we can move it somewhere more public.

**Comment by curiousleo-da** [comment]
> `SandboxIndexAndWriteService` is now private, so the inconsistency has vanished. wink
> 
> If there's something you need from the Sandbox Classic code, feel free to yell and I'm sure we can move it somewhere more public.

Awesome, thank you @SamirTalwar-DA!
