### ISSUE TITLE
release LF 1.11

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#7139]
### this version of LF should include: 

 - [x] GenMap 
 - [x] generic equality and comparison
 - [x] TO_TEXT_CONTRACTID
 - [x] choice observers (#7709)
 - [x] minimal steps of version scheme simplification (See #7788)

**Comment by remyhaemmerle-da** [comment]
blocked by #5164

**Comment by remyhaemmerle-da** [comment]
blocked by #7083

**Comment by cocreature** [comment]
done, see #8714 for some outstanding test improvements for choice observers.
