### ISSUE TITLE
add doesContractExistForKey (maybe with a better name)

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#7143]
Users (and myself!) are routinely confused by the distinction between `fetchByKey` and `lookupByKey`. Recently, @robin-da made a great suggestion [in the middle of a thread on discuss](https://discuss.daml.com/t/lookupbykey-vs-fetchbykey-why-can-i-fetch-a-key-but-not-do-a-lookup/181/12?u=gary_verhaegen), and I wanted to capture it here so it does not get lost.

The suggestion is to add a new primitive that checks for the existence of a contract for a given key, say `doesContractExistForKey`, and explain the difference between `fetchByKey` and `lookupByKey` by the following (conceptual) equality:
```
lookupByKey k = do
  contractExists <- doesContractExistForKey k
  if contractExists
    then 
      Some <$> fetchByKey k
    else 
      return None
```
I believe this would make it much easier to dispel any confusion around this topic.

We cannot remove `lookupByKey` for obvious reasons, but if we were to introduce `doesContractExistForKey` (perhaps with a better name), we could make it less prevalent in the documentation.

I really wanted this ticket to be a bit more than "someone else should do this", so I looked into implementing that myself, but I do not know how to type `doesContractExistForKey`. @bame-da suggested (in the same discuss thread) the following implementation:
```
doesContractExistForKey = fmap isSome lookupByKey
```
but when trying to type it, I end up with:
```
(HasLookupByKey t k) => k -> Update Bool
```
and the type checker (or I, for that matter) does not seem to know how to bind `t`.

**Comment by bame-da** [comment]
You need a type annotation `forall t k .  (HasLookupByKey t k) => k -> Update Bool`, and I think you'll have to add the `AllowAmbiguousTypes` language extension.

**Comment by bame-da** [comment]
Oh, and you need type annotation for the `lookupByKey`, of course, so

```
doesContractExistForKey : forall k t . (HasLookupByKey t k) => k -> Update Bool
doesContractExistForKey k = fmap isSome (lookupByKey @t k)
```

Don't know whether it's possible to keep it point free somehow, but I don't think it really matters

**Comment by garyverhaegen-da** [comment]
Thanks! I was now able to get it to work. I mean it's really just taking your code from these and the discuss comments in a PR. And it works.

**Comment by robin-da** [comment]
@garyverhaegen-da Thanks for picking this up!

**Comment by leonidr-da** [comment]
I think that this is a fine idea, but I am not enthused by it. It will shift the confusion from `lookupByKey` to this function. But the cost is that we're stuck with a new method that we have to support. 

I'm sorry but at the moment, I do not have a better solution. I would advise caution though.
