### ISSUE TITLE
Add metrics to the JSON API

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7169]
in the process of making the JSON API more production ready, we should add some metrics for monitoring it in a production setup. These metrics should be exposed via the same interfaces as the metrics in daml-on-sql.

Go get started, 2 useful metrics could be

1. Number of requests in flight. Probably a bit more fine-grained (e.g., separate command submissions, queries, …)
2. Response time

We can expand this over time but ideally should avoid removing or changing existing metrics.

**Comment by SamirTalwar-DA** [comment]
The ledger API server now has a copious amount of metrics, which helps with some kinds of operational debugging, but not others. In order so you don't fall into the same trap, I suggest that wherever you write metrics, you also log. For example, as well as reporting metrics for the response time, also log the request start and end, with a common ID and a timestamp.

This would probably be considered "trace logging" and so would be off by default, but a prudent sysadmin would turn it on and let Kibana/Stackdriver/whatever do the filtering later.

(Also, structured JSON logs please.)

**Comment by cocreature** [comment]
We have a first stab will open a new issue for something specific.
