### ISSUE TITLE
Review and extend logging in the JSON API

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7170]
As part of making the JSON API more usable in a production setup we should review what and how we currently log and extend it as needed. A few things that come to mind:

1. Failed command and possibly also succeeding commands at some level of detail. Probably at least including the command id.
2. Token decoding failures (not validation failures, that is just a failed command to the JSON API).
3. Verify that we do not log secrets (primarily JWTs)

I’m sure there are many more things but I expect most of this can also be extended over time.

**Comment by cocreature** [comment]
See #7169 for related info

**Comment by lshlyapnikov** [comment]
Related to #5111
