### ISSUE TITLE
DA.Date.date overflows; should it?

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#7188]
This is the current behaviour as of `1.5.0-snapshot.20200818.5027.0.1b33d374`. I find it surprising, and arguably wrong with respect to the documentation.

```
module Main where

import DA.Date

convertsBack : Int -> Month -> Int -> Bool
convertsBack y m n = let d = date y m n
  in (y, m, n) == toGregorian d

test = scenario do
  assert $ convertsBack 1 Jan 1
  assert $ not $ convertsBack 2019 Feb 29
  assert $ (2019, Mar, 1) == toGregorian (date 2019 Feb 29)
  assert $ not $ convertsBack 2020 Aug 32
  assert $ (2020, Sep, 1) == toGregorian (date 2020 Aug 32)
```

For reference, here is the current documentation for `DA.Date.date`:
```
-- | Given the three values (year, month, day), constructs a `Date` value.
-- `date (y, m, d)` turns the year `y`, month `m`, and day `d` into a `Date` value.
date : Int -> Month -> Int -> Date
```

The documentation does not say what happens on invalid input. This means that we have a few options:
1. Keep the current behaviour, but document it. I think this is the wrong behaviour, but this is the option that gives us the best backwards compatibility.
1. Consider this overflow behaviour a bug, and fix it. And update the docstring to mention it. Throw an error on invalid inputs.
1. Consider this overflow behaviour a bug, but keep it around for backwards compatibility. Deprecate the function, and add a new, better one, maybe `mkDate : Int -> Month -> Int -> Maybe Date`, which would allow us to avoid one more `error`.

Perhaps other options I have not considered; feel free to add them as comments.

**Comment by cocreature** [comment]
I’d prefer 2.

**Comment by anthonylusardi-da** [comment]
Big thanks to [György for initially reporting this bug](https://discuss.daml.com/t/day-parameter-overflow-for-the-date-function-simple-leap-year-handling/1068)!
