### ISSUE TITLE
Add log-level parameter to the JSON API

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#7198]
Currently, the only way to set the log level is to [provide a custom logback file](https://discuss.daml.com/t/how-can-i-control-the-log-level-for-the-json-api/1034/2) and it defaults to quite verbose logging. The suggestion is to implement the same `--log-level` argument as the DAML-on-SQL process has.

**Comment by stefanobaghino-da** [comment]
Closed by https://github.com/digital-asset/daml/pull/9581
