### ISSUE TITLE
Can build package with version that will be rejected by tooling / code-gen

### ISSUE THREAD

**Issue by iggy-da** [digital-asset/daml#7208]
The following are valid `version` formats in the  `daml.yaml` when compiling a `.dar`:
 * `foobar`
 * ``x%`!@#`` and the like

```
> Compiling example to a DAR.
> Created .daml/dist/example-x%`!@#.dar
```

However, the Scala/Java code-generation, as well as the sandbox strictly expect a dotted numeric version format:

```
DAML LF Package Version "1.1.1-foobar" does not match regex "(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*"
```

Defined here:
https://github.com/digital-asset/daml/blob/a79377cb2d6eb488314c9468d8653b621fcb1d09/daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/IdString.scala#L241

We came across this today when we wanted/needed to generate dar versions with a pre-release suffix ([semver style](https://semver.org/)) for upgrade tooling.

- It would be helpful to have greater flexibility with version names (e.g. semver) while maintaining compatibility with above tooling.
- It may make sense for the daml assistant to uniformly restrict the supported version format to the tooling's broadest possible common denominator.

**Comment by hurryabit** [comment]
@robin-da That's one of the tickets I wanted to bring to your attention.

**Comment by robin-da** [comment]
@hurryabit While we could extend the DAML-LF version pattern, `ghc-pkg` only allows numeric versions interleaved with dots. Hence, my suggestion is to leave DAML-LF as is, but maybe sanitize the version when loading the daml.yaml file for an early and clear error.

**Comment by hurryabit** [comment]
@robin-da That makes a lot of sense. Let's do that.
