### ISSUE TITLE
No health check is exposed for the read service or other ledger-specific services

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#7237]
Currently, the Ledger API Server only exposes a health check for the write service and an internal index service. This means that the read service health checks are not exposed.

This also means that the ledger itself isn't able to provide health checks for other internal mechanisms (e.g. communication with a source of entropy).

**Comment by SamirTalwar-DA** [comment]
I propose injecting the health checks into the `StandaloneApiServer` class through its constructor, allowing the ledger integrator to decide which are useful. The index service can still be added by the API server itself.

**Comment by gerolf-da** [comment]
What about the case where the indexer is run as a standalone process? We might have to start a gRPC server just for the health check?

**Comment by SamirTalwar-DA** [comment]
Yeah, I expect so, unfortunately. I think that's beyond the scope of this though.

**Comment by tudor-da** [comment]
I would say this is fixed by https://github.com/digital-asset/daml/pull/9951 . Can we close this issue, @SamirTalwar ?

**Comment by SamirTalwar-DA** [comment]
Hell yes.
