### ISSUE TITLE
Document HA setup for the jSON API

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7271]
We should document how users can run an HA setup for the JSON API. If needed, this could also include some implementation work. There are two possible approaches and we should choose one to document (with the possibility of revising this in the future):
- achieving HA for the HTTP-JSON API server as a standalone component, with multiple instances running against a single participant to enable high availability
- achieving HA at the "Connect" level, having one HTTP-JSON API server per participant and having this behave as a single unit of deployment which can be replicated to enable high availability

---

Open question: are offsets are translatable if a fail-over happens and if not, how do users know they are connecting to a different HTTP-JSON API instance?

**Comment by stefanobaghino-da** [comment]
> one json api per participant

What do you mean here exactly? If you just make one JSON API and one participant a unit of deployment and manage that single unit to be deployed in such a way that it's highly available I'm not sure this should be documented as part of the JSON API itself.

**Comment by cocreature** [comment]
Not sure it needs to be documented as part of the JSON API itself but somewhere we need to document how we recommend running an HA connect setup.

**Comment by stefanobaghino-da** [comment]
> Not sure it needs to be documented as part of the JSON API itself but somewhere we need to document how we recommend running an HA connect setup.

Is the participant part of Connect? I thought the participant was part of the driver. It's unclear what you are trying to document in terms of high availability if you only have a single HTTP-JSON API server which is deployed alongside the participant.

**Comment by cocreature** [comment]
In canton participant = connect node so it is part of connect.

**Comment by stefanobaghino-da** [comment]
@akshayshirahatti-da I re-worded the ticket a bit. I think that documenting the first approach (HTTP-JSON API as a single unit of deployment and achieve HA at that level) is good enough of a starting point. We may want to refine this further down the road by including how this interacts with the rest of a Connect deployment but I don't think it's strictly necessary at this point.

**Comment by stefanobaghino-da** [comment]
Closed by #10903
