### ISSUE TITLE
docs: rendering bug - no space between bottom of table and next heading

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#728]
Image

![Screenshot from 2019-04-26 13-27-40](https://user-images.githubusercontent.com/13766136/56804852-617b6200-6827-11e9-9f44-b001a6f152c9.png)

Code (rename to .rst)
[index.txt](https://github.com/digital-asset/daml/files/3121106/index.txt)

FYI: @bethaitman

**Comment by stefanobaghino-da** [comment]
Doesn't appear to be a problem anymore, closing.

Please don't abuse the `broken` tag, it should be reserved for things that make the product unusable.
