### ISSUE TITLE
`debug` and `trace` statements should be output in the Transaction View of DAML Script in the IDE

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#7280]
It works for Scenarios.

**Comment by cocreature** [comment]
This needs a bit of fiddling since we probably want both trace statements from the client as well as from the ledger and we want them interleaved. It might be nice to prefix them to show users where they are coming from.

**Comment by bame-da** [comment]
Scenarios don't give you that distinction so not a must-have for me in the first version, but always happy with improvements.

**Comment by cocreature** [comment]
Agreed, just a nice to have given that we actively have to interleave them it’s pretty easy to do.
