### ISSUE TITLE
Canton conformance test is flaky

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#7316]
The tests that flake according to Oliver are:

- [ ] `TransactionServiceIT:TXInvisibleTransactionTreeByEventId`
- [ ] `TransactionServiceIT:TXFlatTransactionByIdSameAsTransactionStream`
- [ ] `TransactionServiceIT:TXTransactionTreeByIdSameAsTransactionStream`
- [ ] `TransactionServiceIT:TXSingleMultiSameTreesStakeholders`

**Comment by oliverse-da** [comment]
The flakes appear to get progressively worse after rerunning

```
bazel test -t- --runs_per_test=10 //ledger/ledger-api-test-tool-on-canton:conformance-test
```

multiple times. This makes me suspect that something is not getting cleaned up. Then I noticed multiple canton/jvm processes `/private/var/tmp/_bazel_oliver/98a055b4f8937bc778a7a69ff35e474c/sandbox/processwrapper-sandbox/7/execroot/com_github_digital_asset_daml/bazel-out/darwin-opt/bin/ledger/ledger-api-test-tool-on-canton/conformance-test.runfiles/local_jdk/bin/java -classpath ../canton/lib/HikariCP-3.2.0.jar:../canton/lib/akka-actor_2.12-2.6.1.jar:../canton/lib/akka-http-backend_2.12-2.0.2.jar:../canton/lib/akka-http-core_2.12-10.1.11.jar:../canton/lib/akka-http_2.12-10.1.11.jar:../canton/lib/akka-parsing_2.12-10.1.11.jar:../canton/lib/akka-protobuf-v3_2.12-2.6.1.jar:../canton/lib/akka-slf4j_2.12-2.6.1.jar:../canton/lib/akka-stream_2.12-2.6.1.jar:../canton/lib/alleycats-core_2.12-2.0.0.jar:../canton/lib/ammonite-interp-api_2.12.11-2.1.1.jar:../ ... ledger-api-test-tool-on-canton/bootstrap.canton` which may trigger problems.

**Comment by oliverse-da** [comment]
According to canton INFO-level logs, the transactions (the one from the `TransactionServiceIT:TXTransactionTreeByIdSameAsTransactionStream` test itself and both of the `synchronize` transactions) make it to both participants. Unfortunately the queries going through the `ApiTransactionService` don't show any logs at INFO level, so I will need to figure out how to get DEBUG logs enabled.

**Comment by oliverse-da** [comment]
I finally managed to turn on debug logging which makes visible the read requests too.

Here is the cause: Every so often the synchronize request takes longer than the max-retry to be visible on the other participant, i.e. the NOT_FOUND arises from the synchronize’s alpha.transactionTreeById eventually timing out even after 10 retries with exponential backoff of about 5 seconds. (edited)
