### ISSUE TITLE
Monadifying the low-level trigger API

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7372]
Currently, the `update` function in the trigger API is a simple function that returns the new state and a list of commands: https://github.com/digital-asset/daml/blob/f67af49044a4a4df24ecf01247cfbceada98751f/triggers/daml/Daml/Trigger/LowLevel.daml#L154

This means that we cannot hand over control to the trigger runner during the update. There are a few issues as a consequence of this:

1. We cannot generate random UUIDs when the user calls `emitCommands` and return them as a result (DAML has no random number generation). Currently we work around this by using an incrementing command id in DAML API and mapping that to random UUIDs on the Scala side. However, that is both messy and it makes it harder to debug triggers as you don’t easily get access to the command id used to submit a list of commands.

2. To add exception handling to triggers (matching the one we want to add for `Update`s and DAML Script), we need special LF primitives. This goes against the current design where triggers deliberately are not LF builtins.

3. While we provide `emitCommands` in the high-level trigger API, the commands are only sent at the end of the rule rather than immediately. This has potential for confusion (consider the case where your trigger crashes after calling `emitCommands` without those commands ever being sent). However, I haven’t seen anyone run into this so far so I think it’s a relatively small issue.

4. The API makes it hard to add new effectful features. For example, consider adding logging functionality. Our best option here is either to rely on `trace` which is notoriously confusing since it’s tied to evaluation and not execution or return a list of log messages as part of each update which is confusing since they are delayed.

1 and 2 are issues that I expect we will have to solve fairly soon. 3 and 4 are more potential issues that could cause issues down the line. Right now, we don’t have concrete plans for adding more effects but at least (user-defined) logging will almost certainly come up at some point.

DAML Script does address this by building on top of a free monad. This allows us to hand over control to the Scala side at any point to implement effects. For example, `submit` is handled that way. Not quite a free-monad but still possible with the same design is exception handling. See https://github.com/digital-asset/daml/pull/7368 for a prototype of how this could work without requiring special catching primitives in LF.

**Comment by S11001001** [comment]
#7456 fixes (3) and (4) directly, but only enables fixes for (1) and (2).

**Comment by S11001001** [comment]
Split (1) to #7549.
