### ISSUE TITLE
Separating off-ledger and on-ledger speedy

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7387]
DAML Script and DAML Triggers execute DAML outside of a ledger. However, they currently use the same speedy machine that we use for on-ledger code which makes this a bit messy. We should cleanly separate the on-ledger and off-ledger modes so that off-ledger mode will error out on ledger primitives and the API for constructing such a machine does not have to care about things that are only relevant for on-ledger code.

There is an open question of whether we want to do this for scenarios as well or whether those should stay as is until we can kill them.

**Comment by remyhaemmerle-da** [comment]
fixed by #7501
