### ISSUE TITLE
Ledger: Validate Packages as part of the package upload

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#7399]
Currently packages are validated by the Engine before Speedy compilation, but not when uploaded to the Ledger.  

The package should be validated before to be stored on the Ledger as part of the package upload process.
 This has two main advantages: 
* this avoids to store bogus data on the ledger that cannot be latter used. 
* this allowed to skip validation in the Engine, then speeding up submission when packages are not available in the Engine. 

# Proposal 

1 - The participant Node validate the packages before sending them to the ledger.  
     This prevents the ledger to validated buggy archive, since this can be very costly in a distributed system.
2 - The ledger revalidate the package before committing, reject if invalid   
3 - Drop the validation in the Engine.

**Comment by SamirTalwar-DA** [comment]
If we implement this, what should we do with packages that were previously uploaded but not validated?

**Comment by remyhaemmerle-da** [comment]
I am incline to just trust packages which are already uploaded. I will assume that all packages have been uploaded so far have been produced by a trusted compiler. 

If we are paranoic, we could mark newly uploaded packages as validated and force the validation for not marked packages before sending to the engine.

**Comment by remyhaemmerle-da** [comment]
We could also simply ask to reupload all packages after the upgrade.

**Comment by remyhaemmerle-da** [comment]
cc @martin-drhu-da @gerolf-da @bame-da

**Comment by gerolf-da** [comment]
The current proposal sounds good to me.

**Comment by remyhaemmerle-da** [comment]
#7460 provides basic blocks to implement this.
