### ISSUE TITLE
daml-ghc DAML-LF 1.1 integration tests are failing for bond-trading 

### ISSUE THREAD

**Issue by bolek-wisniewski** [digital-asset/daml#74]
most templates under `daml-foundations/daml-ghc/bond-trading` are failing (with the exception of Test.daml) when being executed with DAML-LF 1.1

The same daml pass the tests for DAML-LF 1.0

**Comment by akalburgi** [comment]
I think this can be closed now @bolek-wisniewski @neil-da @martin-drhu-da

**Comment by neil-da** [comment]
@bolek-wisniewski - can you validate and close?
