### ISSUE TITLE
~ doesn't work in PATH definition

### ISSUE THREAD

**Issue by andreolf-da** [digital-asset/daml#7451]
On @lucb-da system (vanilla Ubuntu 18.04 installation), using ~ in the PATH definition doesn’t work, when getting to the ‘Getting started > Testing your app’.
The yarn test command doesn’t succeed, because it cannot find the daml executable.
The solution on my system was to use $HOME instead of ~ :
`export PATH="$HOME/.daml/bin:$PATH`

**Comment by SamirTalwar-DA** [comment]
`~` is not expanded inside quotes, even double quotes.

You either need to use:

```
export PATH=~/.daml/bin:$PATH
```

or:

```
export PATH="$HOME/.daml/bin:$PATH"
```

Or you can use zsh and go with:

```
path=(~/.daml/bin $path)
```

**Comment by sofiafaro-da** [comment]
Hi @andreolf-da, thanks for bringing this to our attention! I pushed a PR to fix the instructions in that part of the getting started guide.
