### ISSUE TITLE
Question: daml integration with besu

### ISSUE THREAD

**Issue by theliso** [digital-asset/daml#7454]
Hi,

I was analyzing your repository, and I was wondering if you have or if you're working on integrating daml with hyperledger besu?

By the way, i'm a master's student who is researching about migration of smart contracts in heterogeneous blockchain.

**Comment by dasormeter** [comment]
Hi @theliso the DAML on Besu integration is currently available via Sextant and you can speak with our partners at BTP for details on how to get it up and running https://blockchaintp.com/sextant/support/

**Comment by theliso** [comment]
@dasormeter Thank you very much for you reply.

**Comment by cocreature** [comment]
Closing since the question seems to be answered. Feel free to reopen if I misinterpreted that @theliso
