### ISSUE TITLE
Failure to desugar recursive function with return type signature

### ISSUE THREAD

**Issue by shayne-fletcher-da** [digital-asset/daml#747]
This function definition
```haskell
fact (n : Int) : Int
   | n <= 1    = 1
   | otherwise = n * fact (n - 1)
```
generates the error,
```
  Failure to process DAML program, this feature is not currently supported.
  Local variables defined recursively - recursion can only happen at the top level.
  [fact1]
```
while, the following definition succeeds.
```haskell
fact : Int -> Int
fact n
  | n <= 1    = 1
  | otherwise = n * fact (n - 1)
```

**Comment by hurryabit** [comment]
The reason for this issue is that the first version of `fact` gets translated into
```
fact : Int -> Int
fact = letrec fact1 = ... in fact1
```
I propose we don't fix this until we fix local recursion in general.

**Comment by neil-da** [comment]
Not tempted to special case `x = letrec y = ... in y` to `x = let y = (let y = x in ...) in y`? Seems like it will be a common form if people get return type signature happy.

**Comment by hurryabit** [comment]
Actually, seems to be a cheap quick fix. I'll give it a go.

**Comment by hurryabit** [comment]
The temptation was too strong and it actually turned out to be fun to fix this. I made it even work with polymorphic functions.

**Comment by hurryabit** [comment]
Fixed.
