### ISSUE TITLE
Improve codegen UX

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#7526]
One of the major feedback from users going through the getting started guide is that they run into issues with the JavaScript code generation. This can be either that they forget to run the first code generation step or that they subsequently leave out a code generation step or don't upload a new package to the in-memory sandbox. This results in DAML code and UI code being out of sync and usually manifests in a cryptic `unknown template ID` error.

The goal of this improvement is a UX where a user going through the getting started guide does not need to touch the code generation and we have a guarantee that the JavaScript and the DAML code are in sync and that the sandbox is deployed with the newest version of the DAML code.

Achieving this goal for all supported code generations might be rather hard, but we want this UX at least for the "recommended path".

Ultimately we want the `daml start` command to have a hot-reload feature:

On keypress `r` in terminal running `daml start`:

1. compile a new dar package
2. generate new JavaScript code for the new dar package (possibly other code generation specified via an option)
3. upload and replace the current dar to the in-memory sandbox (currently not possible to delete any package from the sandbox)

The UX achieved thereby would be very similar to popular UI frameworks like `flutter` or `npm` devserver.

**Comment by cocreature** [comment]
A few comments:

1. As you mentioned most of the issues are from the JS code and the DAML code being out of sync. However, just regenerating the code is not sufficient you need to run `npm install`.
2. Your description doesn’t describe how you reload the JS code. I assume the idea is to have `npm start` running which will do this? Does `npm start` pick up a call to `npm install`? I thought that you need to restart it in this case which means that changing `daml start` on its own isn’t sufficient regardless of what you do unless it also restarts `npm start`.

**Comment by robin-da** [comment]
> A few comments:
> 
>     1. As you mentioned most of the issues are from the JS code and the DAML code being out of sync. However, just regenerating the code is not sufficient you need to run `npm install`.

When I tested this manually, it was enough to just run the codegen, without an additional `npm install` when the location or the name of the package didn't change.
> 
>     2. Your description doesn’t describe how you reload the JS code. I assume the idea is to have `npm start` running which will do this? Does `npm start` pick up a call to `npm install`? I thought that you need to restart it in this case which means that changing `daml start` on its own isn’t sufficient regardless of what you do unless it also restarts `npm start`.

**Comment by robin-da** [comment]
Just checked, `npm start` will reload automatically when we overwrite the generated JS code.

**Comment by cocreature** [comment]
Fantastic! That makes this much nicer. So given this I would suggest the following steps:

1. Change our tests and docs to no longer suggest the call to `npm install`.
2. Add the `codegen:js` section to `daml.yaml` and make `daml codegen js` read it so that you don’t need to pass the arguments.
3. Change `daml start` to call the codegens of all sections listed in `daml.yaml` (without any arguments, they read it themselves).

**Comment by robin-da** [comment]
> Fantastic! That makes this much nicer. So given this I would suggest the following steps:
> 
>     1. Change our tests and docs to no longer suggest the call to `npm install`.
You'll have to call `npm install` once. Subsequent changes will be picked up. I'll change it like that.
> 
>     2. Add the `codegen:js` section to `daml.yaml` and make `daml codegen js` read it so that you don’t need to pass the arguments.
> 
>     3. Change `daml start` to call the codegens of all sections listed in `daml.yaml` (without any arguments, they read it themselves).

Agreed with 2 and 3!

**Comment by cocreature** [comment]
Good point, I was thinking of the following calls to `npm install`, e.g., https://github.com/digital-asset/daml/blob/master/daml-assistant/integration-tests/src/DA/Daml/Assistant/CreateDamlAppTests.hs#L114

**Comment by bame-da** [comment]
Could we not call the reset service and rerun the initialization script? I think if you change your DAML, it would be OK to wipe ledger state.

**Comment by cocreature** [comment]
No reset service please :scream: The package store is also the one thing that doesn’t get reset (just confirmed that). That’s a significant reason why resets are so much faster than restarting sandbox when you have large DARs.

**Comment by bame-da** [comment]
I see, that's a shame.

**Comment by robin-da** [comment]
@cocreature Is there any chance that we will get some way to clear the packages from the in-memory sandbox for the above purpose?

**Comment by cocreature** [comment]
I’m not aware of any remotely concrete plans. My vague idea for something like this would be to have a mode similar to the scenario service where you have a single (or potentially multiple) packages with a fixed package id that you can mutate.

**Comment by robin-da** [comment]
Fixed by #7562 .
