### ISSUE TITLE
Package-prefix option for Scala codegen is not optional, while docs claim it is

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#7547]
If the Scala codegen is called without a package-prefix like

```
daml codegen scala .daml/dist/create-daml-app-0.1.0.dar -o ui/scala
```

we get an error: 

```
Error generating code: Scala Codegen expects all dars mapped to the same package name, requested: {/home/drsk/create-daml-app/.daml/dist/create-daml-app-0.1.0.dar->None,}
```

Adding a package-prefix will succeed:

```
daml codegen scala .daml/dist/create-daml-app-0.1.0.dar=com.digitalasset -o ui/scala
```

The documentation (`daml codegen scala --help`) however claims that the package prefix is optional. The codegen for Java works without a package prefix.

**Comment by stefanobaghino-da** [comment]
Scala codegen will go away  in Daml 2.0 after being long deprecated, closing.
