### ISSUE TITLE
Document differences between DAML and Haskell.

### ISSUE THREAD

**Issue by fmota-da** [digital-asset/daml#76]
(via @garyverhaegen-da) It would be nice to have a document that keeps track of the differences between the two languages & their respective standard libraries. This should help us keep track of the drift, and to be a useful resource for Haskell programmers using DAML. cc @bethaitman-da @bame-da

**Comment by gerardbosch** [comment]
Hi there, could the draft document be made public for viewing? Thx!

**Comment by garyverhaegen-da** [comment]
Hi Gerard,

That document never went past the initial draft stage. It is very incomplete and what is there is now woefully outdated. Making this document useful would require a substantial effort at this point, and we have no plan to allocate resources to it for the foreseeable future.

If you had specific questions you hoped that document could answer, please consider asking them on our [forum](https://discuss.daml.com).
