### ISSUE TITLE
daml-assistant: Pick available ports automatically when invoking daml start.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#764]
As mentioned in #740, the new `daml start` has currently hardcoded certain port numbers (cc @moritzkiefer-da : which ones? The Navigator web server?), so it will fall over if the port is already in use, such as when another `daml start` process is running.

In the short term, we should at make sure the error message is good. In the long term, we should make the error go away by picking a new port automatically.

**Comment by cocreature** [comment]
> @moritzkiefer-da : which ones? The Navigator web server?

https://github.com/digital-asset/daml/blob/8e54bf2e670f02140bd60e0ca3bb46a5c6468722/daml-assistant/daml-helper/src/DamlHelper.hs#L207 So navigator and sandbox

**Comment by hurryabit** [comment]
@associahedron Is still still an issue?

**Comment by cocreature** [comment]
yes, the ports are still fixed.

**Comment by cocreature** [comment]
@associahedron I’m closing this since I don’t recall ever having a user run into problems with this so it doesn’t seem worth the complexity. Feel free to reopen if someone runs into issues.
