### ISSUE TITLE
Support multi-party command submissions in the Java bindings

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7641]

**Comment by cocreature** [comment]
This needs some work. Specifically https://github.com/digital-asset/daml/blob/main/language-support/java/bindings-rxjava/src/main/java/com/daml/ledger/rxjava/CommandSubmissionClient.java and https://github.com/digital-asset/daml/blob/main/language-support/java/bindings-rxjava/src/main/java/com/daml/ledger/rxjava/CommandClient.java need to be extended with more overloads that accept lists of parties.

@garyverhaegen-da do you want to take a look at this?

**Comment by garyverhaegen-da** [comment]
Will do.

**Comment by garyverhaegen-da** [comment]
I believe this was fixed by #8429. @cocreature was there anything else?

**Comment by cocreature** [comment]
It is, thanks for taking care of it @garyverhaegen-da!
