### ISSUE TITLE
Support multi-party command submissions in Scala bindings

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7642]

**Comment by cocreature** [comment]
Done

**Comment by cocreature** [comment]
For the most part this already works but there are a few missing piecess

`com.daml.ledger.client.binding.LedgerClientBinding` exposes a bunch of utility functions that are limited to a single party. This file isn’t used anywhere in this repo (not even in tests) and it’s only utility functions so not an actual limitation. This also includes things referenced by this file like `CompositeCommand`. Again, this is not used anywhere although `CompositeComandAdapter` does at least have a test.

Given that the Scala bindings are deprecated and you can issue multi-party submissions without this and the Scala quickstart does not make use of the above, I would suggest to just not do anything here until we get an explicit request for this.

@bame-da @S11001001 Are you fine with this?

**Comment by bame-da** [comment]
Could you be more specific what the limitation is? Ie which utility functions don't support multi-party submissions and what do they do?

**Comment by cocreature** [comment]
Basically you cannot use https://github.com/digital-asset/daml/blob/main/language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/LedgerClientBinding.scala and have to access the underlying functions directly.

**Comment by bame-da** [comment]
But what does that class do? I don't see it being used anywhere.

**Comment by cocreature** [comment]
That’s what I said above: we don’t use it anywhere. You could use it for convenience but we always call the underlying functions instead.

**Comment by bame-da** [comment]
ok. then I'm good with your plan.
