### ISSUE TITLE
Support multi-party readAs in Navigator on command submissions

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7648]
Not sure how critical this is but we probably also need to support this in navigator. This could consist of an extra list of parties you specify on login. Queries then query for all of those parties + the actAs party and command submissions pass those parties in `readAs`. Not quite sure if we have to support multi-party `actAs` in Navigator. The usecases seem fairly limited atm (restoring ACS dumps and migration) and I don’t see Navigator being useful for this.

**Comment by cocreature** [comment]
Current plan is to not support multi-party `actAs`.

**Comment by stefanobaghino-da** [comment]
> Current plan is to not support multi-party `actAs`.

The comment seems to point out that this is not supposed to be supported by Navigator. Closing.

**Comment by cocreature** [comment]
I think you misread this. This ticket is about multi-party readAs. The comment says we do not want to support multi-party actAs.

**Comment by stefanobaghino-da** [comment]
Ok, thanks.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
