### ISSUE TITLE
broader, but still constrained, compat tests for triggers

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#7673]
We should figure out a way to compile the DAML model conditionally. We aren’t actually breaking backwards compatibility here so medium-term we shouldn’t have to change anything here.

_Originally posted by @cocreature in https://github.com/digital-asset/daml/pull/7632#discussion_r504106679_

There's a bit of a tarpit here, because we're conflating source compatibility (which e.g. this PR breaks) and SDK/runner compatibility (which e.g. this PR does not) in how we set up the cross builds. And then you consider the divergent 1.6.0 series versus the 1.7.0 series, which have different requirements for each of these categories.

**Comment by cocreature** [comment]
Fixed in #7828
