### ISSUE TITLE
use new postgres fixture for scala codegen postgres tests

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#77]
right now `SlickIntegrationPostgreSqlSpec` runs using a docker container with a postgres instance inside it. this is very heavyweight and has caused problems in the past. we should switch to use the newly defined `PostgresAroundAll`, which also offers a postgresql instance but running a postgres binary directly.

cc @gaboraranyossy-da @stephencompall-DA

**Comment by leo-da** [comment]
#294 removed this test
