### ISSUE TITLE
Submitter doesn't see transactions on the transaction stream when the transaction is empty

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#7704]
On DAML SDK 1.5 and 1.6 Sandbox (in memory, but I'm reasonably certain this happens on SQL as well as we observed similar behavior on a different set of models that caused me to go looking, and I haven't tested earlier versions of the SDK): I'm not sure if this is intended behavior or not, but there appears to be some circumstances where calling `CommandService. SubmitAndWaitForTransactionId()` returns transactions that are _not_ visible to the submitting `Party` via the transaction stream, specifically:

```haskell
template NoOp
  with
    party : Party
  where
    signatory party
    key party : Party
    maintainer key
    
    controller party can
      nonconsuming DoNothing: ()
        do
          return ()

    controller party can
      nonconsuming DoSomething: ContractId Thing
        do
          create Thing with ..
```

And then (using `SubmitAndWaitForTransactionId`):
1. create a `NoOp` contract and exercise the `DoNothing` choice (as a create-and-exercise)
2. exercise the `DoNothing` choice
3. exercise the `DoSomething` choice

Call (2) returns a transaction ID that does _not_ appear in a subsequent request to fetch all transactions (via `TransactionService.GetTransactions`); I only see transaction IDs corresponding to (1) and (3).

A full repro is here, coded against the gRPC API (using Java): https://github.com/da-tanabe/test-cases/tree/cedb5fe4b66583783ab3f3b3e3bfc7af8db2dd37/missing-txs

**Comment by cocreature** [comment]
Way ahead of you #6975 :trollface:

**Comment by cocreature** [comment]
I’ll leave it to you to judge whether this is really a duplicate or not.

**Comment by da-tanabe** [comment]
I think you're right—this looks like a duplicate.

But now I'm a little confused because we're running Classic, and we observed that behavior there before I started to try to whittle down a reproducible case (and accidentally forgot that `daml start` starts up Next instead of Classic 🤦 ).

Will drill down more and try to see if I can figure out where we seem to be observing this behavior on Classic as well (command submissions not resulting in subsequent _transactions_ observed on the stream, even though the command completion comes back with a success).

**Comment by da-tanabe** [comment]
AH I see this problem—when _package filtering_ is on, empty transactions _also_ get dropped (which I suppose makes sense).

Ok I'm ok closing this as a duplicate of #6975.

**Comment by cocreature** [comment]
What is package filtering? Do you mean filtering by template ids?

**Comment by da-tanabe** [comment]
Sorry yep, filtering by template IDs.

**Comment by cocreature** [comment]
I was still only able to observe that in sandbox next, see my comment https://github.com/digital-asset/daml/issues/6975#issuecomment-669475022

**Comment by da-tanabe** [comment]
Yup, that's the same for me. The behavior on Classic and Next look identical to me with template filtering, but again, that's sort of expected.

**Comment by cocreature** [comment]
I’m not sure if it’s expected but it’s definitely different from what I am observing. I just tried that example in the linked comment again and in Sandbox classic I do receive the empty transaction. If you don’t, it would probably be helpful if you could provide a testcase for this.

**Comment by cocreature** [comment]
@da-tanabe what I’m saying is that I _do_ see an empty transaction on a filtered transaction stream in Classic in the example linked in the comment.

**Comment by da-tanabe** [comment]
oh oh oh oh

Hmm ok then I need to dig further. The prod use case is obviously more complicated than this simple test case. I'll either reopen this if it seems like there is still a problem here, or comment.
