### ISSUE TITLE
Add choice observers

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#7709]
**TODOS** (not exhaustive)

* ~Implement feature in the engine.~ (#7139)
* ~fix transaction documentation~ (#8281)
* ~fix LF specifications~ (#8592)
* ~add test for TransactionCoder~ (#7795)
* ~add tests for archive Decoder~ (#8281)
* ~ledger-api conformance tests~ (@gerolf-da is fine we do not implement this test, because a specific ledger does not influence the computation of the choice observers. This should still be covered by tests of the blinding information computation)
* ~decide if choice observer is optional~  (#8316)
* ~remove the "early access" comments from the documentation~

**Comment by cocreature** [comment]
closing in favor of #8714
