### ISSUE TITLE
Upstream "inline function return type signatures" 

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#772]
Augment the existing `ScopedTypeVariables` extension to permit in-line function return type signatures, which are already recognized by the Happy grammar, but currently rejected. Such signatures can easily be given meaning and permit very concise in-line type signature definitions.

A proposal has been raised and is being discussed on [this PR](https://github.com/ghc-proposals/ghc-proposals/pull/185). We have an implementation of the proposal. Based on the discussion, it's not clear that the proposal/ our implementation will be accepted in its current form.

**Comment by cocreature** [comment]
I believe this has been fixed
