### ISSUE TITLE
Upstream the "new colon convention"

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#774]
Provide an extension that reverses the roles of `:` and `::` in a Haskell program. That is, allows the use of `:` to mean "of-type" and `::` to mean the list "cons" operator.

A proposal has been raised, discussed at [this PR](https://github.com/ghc-proposals/ghc-proposals/pull/118) and was withdrawn. We have an implementation of the proposal and have extended it to properly account for the display of warning/error messages that respect the convention.

**Comment by cocreature** [comment]
Not going to happen.
