### ISSUE TITLE
Upstream "no top-level field selectors"

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#775]
Remove top-level field selector generation e.g. the top-level functions `bar` and `baz` that are automatically generated by the declaration `data Foo = Foo { bar :: String, baz :: Int}`.

A proposal has been raised and is being discussed at [this PR](https://github.com/digital-asset/daml/issues/774). We do not have an implementation at this time.

**Comment by cocreature** [comment]
Not being implemented by us but by someone else.
