### ISSUE TITLE
Report contract key lookup mismatches as Inconsistent instead of Disputed

### ISSUE THREAD

**Issue by andreaslochbihler-da** [digital-asset/daml#7825]
DAML Ledgers sometimes report a wrong key lookup in a submission as `Disputed` even though the lookup is correct from the submitter's point of view at the time when it prepared the submission. It's just that the submitter had insufficient visibility or the contract key has changed between submission and commit. These errors should therefore be reported as `Inconsistent` instead.

**Comment by bame-da** [comment]
Can you explain why we need to make this change? Are you trying to distinguish dishonest and honest inconsistencies with `Disputed` and `Inconsistent`?

**Comment by andreaslochbihler-da** [comment]
`Disputed` and `Inconsistent` originate from the `RejectionReason`s on the Participant state API. The documentation for `Disputed` states that this indicates a bug in the implementation or malicious behaviour. That's not the case with contract key lookups that fail due to contention or visibility restrictions. This is what `Inconsistent` is for.

The concrete motivation for allowing `Inconsistent` is that I'm trying to get Canton to pass the conformance tests. I'd have to rearchitect quite a bit in Canton to output `Disputed` as the rejection reason for key inconsistencies just to please the conformance tests.

**Comment by bame-da** [comment]
> The documentation for Disputed states that this indicates a bug in the implementation or malicious behaviour.

Thanks, In that case I'd classify this as a bugfix and disable the compatibility tests for the Sandbox with older Ledger API Test tool versions, as suggested by @cocreature .

**Comment by cocreature** [comment]
@andreaslochbihler-da can this be closed?

**Comment by andreaslochbihler-da** [comment]
Yes. The `Disputed` cases have been removed from the ledger API test tool cases.
