### ISSUE TITLE
daml-assistant: `daml studio` doesn't find VSCode on Mac.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#785]
I have VSCode installed but `daml studio` does not find it. It's looking for the command `code` which doesn't exist. On the latest master I get the following:

```
$ daml-head studio
/bin/sh: code: command not found
```

I installed VSCode through the website and dropped it in the Applications folder, in typical Mac fashion.  So what does exist is `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`.

It may be good to find out how da-assistant finds vscode on a mac.

cc @moritzkiefer-da

**Comment by associahedron** [comment]
The second issue here is that the error message should be nicer. :)

**Comment by cocreature** [comment]
See https://github.com/digital-asset/daml/blob/master/da-assistant/DA/Sdk/Cli/Job.hs#L420 for how the old assistant handles this.
Do you want to take this one given that you are on a Mac anyway? :smile:

**Comment by associahedron** [comment]
I will :+1:
