### ISSUE TITLE
Use only a single SandboxFixture

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#79]
We have at least 3 various SandboxFixtures in our repo. Ideally we should have a single one. We need to refactor and expose the fixture used in our api-integration test so it can be reused  in other places.   

![dfeb4caceb8262e99fd6bdb8b6de94b3](https://user-images.githubusercontent.com/29858875/54342552-0c9bd780-463d-11e9-93d2-2bdd3e6c620e.jpg)

**Comment by leo-da** [comment]
Removing extractor label. This issue has nothing to do with `extractor`. There is an `com.digitalasset.extractor.services.ExtractorFixture` trait that extends from `com.digitalasset.platform.sandbox.services.SandboxFixture`. But that is expected, ExtractorFixture mixes in things needed for Extractor testing.

`sandbox-control` module is gone.

**Comment by stefanobaghino-da** [comment]
There is currently a single `SandboxFixture` in our codebase, closing this.

@gerolf-da Please feel free to re-open in case I'm missing something.
