### ISSUE TITLE
daml build output path is relative to project root instead of being relative to current directory.

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#7913]
From @tamaskalcza-da : https://discuss.daml.com/t/output-path-is-not-relative-from-current-location/1596

When running `daml build --project-root PATH1 --output PATH2` the `PATH2` seems to be relative to the project root (`PATH1`) instead of being relative to the current directory. That's unexpected and confusing for users.

**Comment by hurryabit** [comment]
@sofiafaro-da Is than an issue with the assistant or with the compiler?

**Comment by sofiafaro-da** [comment]
Compiler. This is `damlc build` related.
