### ISSUE TITLE
NPM does not update correctly when new DAML dependencies are added

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#7928]
User Xuyx on the DAML forum presented an issue in https://discuss.daml.com/t/build-success-but-excercise-error/1606/13 where `npm install` would not pull in a dependency on the package containing `Tuple2` without deleting the `package-lock.json` file and `node_modules` folder.

Of course my preferred option would be to fix this in such a way that `daml codegen` + `npm install` always lands you in a good state, but barring that, we should at least document when this occurs, how to diagnose it, and how to work around it.

**Comment by cocreature** [comment]
I looked into this a bit earlier today but I couldn’t figure out a nice way to do this. `npm install` updates the code of the newly generated package but it does not update the list of dependencies in `package-lock.json`. It seems like NPM doesn’t track `file:` dependencies properly.

**Comment by robin-da** [comment]
Do we have a sample of a typical error message that will occur in this case? The best I can think of is to add a short explanation in the 'Troubleshooting' section of the docs.

**Comment by robin-da** [comment]
@cocreature I checked this out today again and found that `npm install` did update the `package-lock.json`. I was running npm version `6.14.9`. Looks like npm solved this?

**Comment by cocreature** [comment]
@robin-da awesome! Can we get a test to make sure this keeps working? Probably easiest to just write a new test suite, maybe even an `sh_test` is sufficient.

**Comment by robin-da** [comment]
I'll add a test.

**Comment by robin-da** [comment]
Fixed by updating npm.
