### ISSUE TITLE
Confusing error message when using constraint synonyms without type signatures

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7953]
The following error complains that recursion is only supported at the top-level. However, the user has clearly not written any recursive function outside of the top-level here so this is pretty confusing. If you add the type signature, the program compiles as expected.

```
module Main where

class C a where

class D a where

type S a = (C a, D a)

f : S a => a -> a
f = identity

-- y : S a => a -> a
y a = y (f a)
```

Now what is going on here? Looking at the core reveals the culprit:

```
y : forall t1 t2. (C t1, D t1) => t1 -> t2
[GblId, Arity=2]
y = \ (@ t_a10Q)
      (@ t1_a10S)
      ($dC_a10Z : C t_a10Q)
      ($dD_a110 : D t_a10Q) ->
      let {
        $d(%,%)_a10U : S t_a10Q
        [LclId]
        $d(%,%)_a10U = ($dC_a10Z, $dD_a110) } in
      letrec {
        y1_a10K [Occ=LoopBreaker] : t_a10Q -> t1_a10S
        [LclId, Arity=1]
        y1_a10K
          = \ (a_aiv : t_a10Q) ->
              src<daml/Main2.daml:14:1-13>
              case a_aiv of a1_XiE { __DEFAULT ->
              src<daml/Main2.daml:14:7-13>
              y1_a10K
                (src<daml/Main2.daml:14:9-13>
                 f @ t_a10Q $d(%,%)_a10U (src<daml/Main2.daml:14:12> a1_XiE))
              }; } in
      y1_a10K
```

We end up building up the type synonym outside and only then define the recursive function. Interestingly, I couldn’t find any type signature that you can add that produces the same result.

At the very least the error message is crappy here but ideally this shouldn’t error in the first place.

**Comment by hurryabit** [comment]
I _guess_ this is very closely related to the code at https://github.com/digital-asset/daml/blob/4b191f81541c00eabaec152a7924048a04195eef/compiler/damlc/daml-lf-conversion/src/DA/Daml/LFConversion.hs#L739

@sofiafaro-da Is this something you could have a look at? Maybe we can simply recycle the same "trick"?

**Comment by sofiafaro-da** [comment]
Looks like it should be possible to reuse the same trick (while carrying some extra bindings around).
