### ISSUE TITLE
Expected error not returned when passing unknown service to gRPC health endpoint

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#7963]
When querying the gRPC status health endpoint for the status of a particular service, a generic Error is returned rather than expected UNKNOWN or SERVICE_UNKNOWN based on GRPC Health Checking Protocol https://github.com/grpc/grpc/blob/master/doc/health-checking.md

```
message HealthCheckResponse {
  enum ServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
    SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
  }
  ServingStatus status = 1;
}
```

Steps to reproduce

1) Startup sandbox on latest DAML SDK 1.7.0 (although I believe this problem will be true of all DAML ledgers at present)
`export DAML_SDK_VERSION=1.7.0 & DAML sandbox`

2) Hit grpc.health.v1.Health/Check endpoint passing a service that does not exist (in this example, blah) --> the only services that exist at present are read, write and index
`grpcurl -d '{"service":"blah"}' -plaintext 127.0.0.1:6865 grpc.health.v1.Health/Check`

```
expected response: 
{
  "status": "UNKNOWN"
}
```

actual response:
```
ERROR:
  Code: NotFound
  Message:
```

3) Hit grpc.health.v1.Health/Watch endpoint passing non-existent service
`grpcurl -d '{"service":"blah"}' -plaintext 127.0.0.1:6865 grpc.health.v1.Health/Watch`

```
expected response: 
{
  "status": "SERVICE_UNKNOWN"
}
```

actual response:
```
ERROR:
  Code: NotFound
  Message:
```

**Comment by SamirTalwar-DA** [comment]
I'm not convinced. From that document:

> If the service name is not registered, the server returns a `NOT_FOUND` GRPC status.

I think `UNKNOWN` is supposed to mean "I don't know the health of this (known) service", not "I don't know what this service is". Unfortunately this is pretty poorly documented, so I can't be sure.

**Comment by dasormeter** [comment]
> I'm not convinced. From that document:
> 
> > If the service name is not registered, the server returns a `NOT_FOUND` GRPC status.
> 
> I think `UNKNOWN` is supposed to mean "I don't know the health of this (known) service", not "I don't know what this service is". Unfortunately this is pretty poorly documented, so I can't be sure.

Alright I agree the narrative on the specification is ambiguous

I would think SERVICE_UNKNOWN would be the clearer one for both -- not sure why that only applies to Watch

But yeah need client to deal with GRPC NOT_FOUND error anyway so that's probably enough to say "you sent me a bad service" at the moment

**Comment by SamirTalwar-DA** [comment]
Annoyingly, I believe `NOT_FOUND` is also the response if you call a non-existent GRPC method. So either way, it sucks.

I would be happy to switch to `SERVICE_UNKNOWN`. My guess is that it's not used in this case to maintain backwards compatibility, which doesn't affect us because (AFAIK) no one is relying on these endpoints right now. [An older version of this spec](https://github.com/grpc/grpc/blob/18a9e00b333d8aa6d2a270ce229ae32657033baa/doc/health-checking.md) didn't have that at all.

**Comment by dasormeter** [comment]
Nothing to do here -- closing
