### ISSUE TITLE
Speed up compilation of ghc-lib

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#8]
Currently compiling ghc-lib is super slow. We should figure out why, and see what can be done. That may well involve profiling GHC itself and figuring out which modules take longest to compile and why.

CC @shayne-fletcher-da

**Comment by cocreature** [comment]
We’ve made it a bit faster by disabling optimizations in some modules and we split out `ghc-lib-parser` so I think for now this is fine.
