### ISSUE TITLE
make the polling-only and streaming endpoints easier to discover and compare

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#8034]
Currently the Streaming API is in the main section of the JSON API docs at the bottom below HTTP status codes which makes it hard to find.

My proposal is to:

- [x] Move the HTTP status codes to their own subsection (which indirectly moves the Streaming API up)
- [x] Add a paragraph towards the start of the JSON API mentioning both the polling-only and streaming portions of the API so it's more apparent that both options exist

Happy to do both of these myself just want to make sure this change is okay first :)

**Comment by cocreature** [comment]
Sounds reasonable to me.

**Comment by S11001001** [comment]
As the goal is

> both the polling-only and streaming portions of the API so it's more apparent that both options exist

the documentation for the individual endpoints themselves seems a better context for this mention than as front matter likely to be paged past.

This is what #13563 does.
