### ISSUE TITLE
//language-support/java/codegen:ledger-tests flaky timeout

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#808]
In [this build on master](https://dev.azure.com/digitalasset/daml/_build/results?buildId=3856) we had a timeout for `//language-support/java/codegen:ledger-tests`. Rerunning fixed it. We should not tolerate flaky tests on master.

**Comment by bitonic** [comment]
@gerolf-da @stefanobaghino-da can you look into this?

**Comment by leo-da** [comment]
Please check if it is related to https://github.com/digital-asset/daml/issues/464

**Comment by garyverhaegen-da** [comment]
Another instance: [this build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=4263) for [this commit](https://github.com/digital-asset/daml/commit/16ea1ceacd786808c4f6eeb13ad5cd15ecc6d4c1).

**Comment by bitonic** [comment]
@gaboraranyossy-da @gerolf-da do you know how to bump the timeout for `language-support/java/codegen/src/ledger-tests/scala/com/digitalasset/CodegenLedgerTest.scala`?

**Comment by bitonic** [comment]
#929 attempts to solve this, please reopen if this starts flaking out again.
