### ISSUE TITLE
Type declarations in template `let` bindings are not applied

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#8089]
I used to be able (in SDK 0.13.X) to write

```
template Foo
  with
    p : Party
  where
    signatory p

    let
      bar : ContractId Foo -> Update Foo
      bar = fetch
```

That no longer works. I get an error

```
Ambiguous type variable ‘t0’ arising from a use of ‘fetch’
      prevents the constraint ‘(HasFetch t0)’ from being solved.
```

Workaround is to write

```
    let
      bar (x : ContractId Foo) = fetch x
```

or

```
    let
      bar : (ContractId Foo -> Update Foo) = fetch
```

I would prefer to use `->` style separate type declarations as that's what I'm using top-level and what we present in most of our examples.

**Comment by bame-da** [comment]
In fact, this seems to be the only regression from SDK 0.13.12 that prevents a seamless upgrade of https://github.com/digital-asset/ex-collateral.

**Comment by hurryabit** [comment]
This is a known bug: https://github.com/digital-asset/daml/issues/7902

@nickchapman-da Given that this has come up twice in short succession now, could you please look into this after the tail call optimization stuff? I would expect this to be a rather small change.

**Comment by nickchapman-da** [comment]
The related issue ( #7902) is now fixed.
