### ISSUE TITLE
Make damlc use less memory

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#81]
> Damlc is unusually memory-hungry for a compiler. Frequently when compiling my machine grinds to a halt and I can't even move the mouse.

Need to figure out how hungry it is, and whether that's reasonable.

**Comment by cocreature** [comment]
We have made a couple of improvements (e.g. incremental on-disk builds) so I’m closing this. There is probably more we can do but then let’s open issues with specific ideas for improvements.
