### ISSUE TITLE
Give better error message if multiple versions of @daml/* are loaded

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#8101]
A user on the forum ran into an error because their SDK versions in `daml.yaml` and `package.json` didn't match. As a result, the generated code pulled in a different version of `@daml/types` to the one pulled in by `package.json` resulting in an error related to not being able to look up the template. https://discuss.daml.com/t/i-get-trying-to-look-up-template-error-in-front-end/1715/3

Maybe the message "Trying to look up template" could be made more informative, but more importantly, I think it would be nice to emit an error (or a warning) on loading the library that more than one version is around and that that will usually lead to problems.

**Comment by cocreature** [comment]
Thanks for tracking this. Fully agree, that we need to do better here. I’ll never understand why NPM allows this in the first place :disappointed:
