### ISSUE TITLE
delete contracts from sandbox for `daml start` hotreload

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#8162]
With multi-party submissions we should be able to delete all contracts on a reload for `daml start` now. The next step would be to also drop the uploaded dar files once this feature becomes available.

**Comment by cocreature** [comment]
Note that this depends on multi-party submissions, otherwise you cannot call `Archive` for multi-signatory contracts. As for package pruning, I checked that unfortunately there is no timeline for this atm :disappointed:
