### ISSUE TITLE
Make damlc output use color

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#82]
> This is a minor point, but the colorised output from damlc compile is really helpful. However, damlc test output isn't colorised, nor is damlc compile when called from a script. It'd be great to have flags --color --no-color to control this explicitly.

Sounds reasonable.

**Comment by akalburgi** [comment]
@neil-da looking into da-hs-daml-cli app I don' t see any option to enable color for -- compile. And the compile command outputs daml-lf and colorizing seems a bit odd. 
While I can understand there is some value to colorizing the test output for human consumption.

**Comment by neil-da** [comment]
Not sure. I was only thinking of colouring the output like ERROR in red or similar. I wasn't thinking of syntax highlighting of the produced output.
