### ISSUE TITLE
Document or make sandbox log level configurable, when running it as part of the DAML Assistant

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#820]
As a DAML developer I need an easy way to change log level for the sandbox that is shipped with the DAML Assistant.
Expose `logback.xml` and/or document how to override the default one.

**Comment by cocreature** [comment]
The assistant just passes the arguments passed to `daml sandbox` to the sandbox jar so this shouldn’t be specific to the assistant.

**Comment by leo-da** [comment]
@cocreature this might require some changes in the quickstart-java daml assistant template, like exposing `logback.xml` e.g.

**Comment by associahedron** [comment]
@francesco-da It would be best if the sandbox could read the daml project config `daml.yaml` in the `$DAML_PROJECT` folder to configure sandbox log levels (& other configuration).

**Comment by bitonic** [comment]
@associahedron we have long-standing plans for a sandbox config file, see #51 . however i agree that it'd be useful to integrate it somehow with the assistant. cc @gaboraranyossy-da

**Comment by associahedron** [comment]
Closing this in favor of #51.
