### ISSUE TITLE
daml build sometimes fails to delete .daml on Windows

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#8333]
Occasionally, on Windows, it seems possible to get into a situation where running `daml build` fails with the following error:

```
damlc: .daml\package-database\1.8\daml-trigger-1.7.0-bfd4ef9f797e02f1cdbb3fea941b04683089c0b627fee96106d697e61a360d83\Daml: removePathForcibly:removePathForcibly:removePathForcibly:RemoveDirectory "\\\\?\\C:\\Users\\A\\A B\\proj\\.daml\\package-database\\1.8\\daml-trigger-1.7.0-bfd4ef9f797e02f1cdbb3fea941b04683089c0b627fee96106d697e61a360d83\\Daml": unsatisfied constraints (The directory is not empty.)
```

So far we have only seen that when also running DAML Studio at the same time but it’s unclear if that’s a requirement. It is definitely flaky. On some machines it fails in something like 1 out of 10 runs, on others more frequently and on some machines (my own which is fairly close to a CI machine), I haven’t been able to reproduce this at all.

My best guess is that there is a race between DAML Studio and `daml build` but I don’t understand what is racing since DAML Studio should read the package db on startup or at the latest on typechecking if it picks up interface files.

The issue appears to be independent of the project, you can reproduce it with `create-daml-app` for example.

**Comment by hurryabit** [comment]
@cocreature I think you copied the wrong error message. Or is that really all we get to work with?

**Comment by cocreature** [comment]
it was in there somehow just hidden, I’ve dropped the version thingy.

**Comment by hurryabit** [comment]
Given that this seems hard to reproduce, how do you feel about simply printing a better error message when this happens, maybe suggesting to close DAML Studio as well? cc @robin-da

**Comment by cocreature** [comment]
We aren’t even sure if it’s actually caused by DAML Studio. I think we should at least try to understand the issue before we change error messages.

**Comment by cocreature** [comment]
don't remember seeing it but I also haven't tested anything on Windows in ages or payed attention to the Windows CI. Closing.
