### ISSUE TITLE
gRPC communication between damlc and scenario service does not seem to respect no_proxy

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#834]
We’ve had a user that ran into issues where they reproducibly get
```
DA Studio : 2019-04-29 10:41:34.59 [ERROR]  [LanguageServer]  []
Exception during scenario interpretation: Failed to start scenario service: BErrorClient (ClientIOError GRPCIOTimeout)
CallStack (from HasCallStack):
 error, called at daml-foundations/daml-ghc/src/DA/Service/Daml/Compiler/Impl/Scenario.hs:40:19 in daml-foundationsZSdaml-ghcZSdaml-ghc-lib:DA.Service.Daml.Compiler.Impl.Scenario
da-hs-damlc-app: Failed to start scenario service: BErrorClient (ClientIOError GRPCIOTimeout)
CallStack (from HasCallStack):
 error, called at daml-foundations/daml-ghc/src/DA/Service/Daml/Compiler/Impl/Scenario.hs:40:19 in daml-foundationsZSdaml-ghcZSdaml-ghc-lib:DA.Service.Daml.Compiler.Impl.Scenario
[Info  - 11:41:34] Connection to server got closed. Server will restart.
```

It looks like this is most likely caused by them using a proxy. They have set `no_proxy=qadockerhub.calastone.com, github.calastone.com, teamcity.calastone.com, localhost, 127.0.0.1/8, ::1` to localhost but it does not seem to be respected. At some point this was an issue with [gRPC](https://github.com/grpc/grpc/issues/9989) but it seems like that has been fixed since and we should be on a version that has the fix.

**Comment by AndrewDCDrummond** [comment]
This is on ubuntu 18.04 LTS.

It appears to be an issue with spaces in the no_proxy list in the environment, so 

no_proxy=qadockerhub.calastone.com,github.calastone.com,teamcity.calastone.com,localhost,127.0.0.1/8,::1

works and no more error.

As an aside, - if you amend the no proxy list in the Gui Settings tool to remove spaces, ubuntu will put the spaces back after a reboot.

**Comment by AndrewDCDrummond** [comment]
you can therefore close this...

**Comment by cocreature** [comment]
Thank you for tracking this down!
