### ISSUE TITLE
`daml install latest` installs most recent, not highest version

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#8354]
I was surprised by this:

```
$ daml install latest
Installing SDK version 1.6.1
[...]
```

**Comment by sofiafaro-da** [comment]
Good catch. This is a bug. Also `get.daml.com` / `get-daml.sh` does the same.

**Comment by garyverhaegen-da** [comment]
Immediate issue has been resolved through manual hacking; let's keep this ticket open to track fixing the root cause.
