### ISSUE TITLE
Harden the SDK against a read-only DAML_PATH

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#8396]
This has been brought up because certain installations will have ~/.daml (or the equivalent DAML_PATH) as read-only. Ideally the SDK should still work, although slightly hampered by an inability to cache or update, but right now there appears to be several problems, such as telemetry blocking `daml damlc ide` because it can't write a `.machine_id` file.

My suggestion is to try to capture some of these issues by writing an integration test that turns the DAML_PATH directory to be read-only (after installation) and running some tests with daml damlc ide, daml assistant, etc.

**Comment by cocreature** [comment]
I think part of the solution here might be to have a separate config and perhaps cache directory where we write things like the telemetry stuff but no executables. While we might still want to deal with the fact that that is read-only the more common case seems to be that executables are installed somewhere read-only but there is still a writable directory for cache and config files.
