### ISSUE TITLE
Removing dependency from daml.yaml causes daml build to fail.

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#8409]
I think we have a package database bug.

Steps to reproduce:

1. start a new project with `daml new proj1`
2. `cd proj1`
3. run `daml build` once, it compiles
4. remove `daml-script` dependency in `daml.yaml`
5. remove `init-script: Main:setup` line in `daml.yaml`
6. modify `daml/Main.daml` to remove all references to daml script
7. run `daml build` and get the following error:

```
$ daml build
Compiling proj1 to a DAR.
File:     
Hidden:   no
Range:    1:1-100001:1
Source:   compiler
Severity: DsError
Message:  <command line>: cannot satisfy --package daml-script-0.0.0(use -v for more information)
ERROR: Creation of DAR file failed.
```

Removing `.daml/package-database` clears it, so my guess is we're not initializing the package database enough, or something.

**Comment by cocreature** [comment]
:facepalm: this is a side effect of the optimization at https://github.com/digital-asset/daml/blob/c6995a9c344c85565b120d6e75b2a4802d51fbf1/compiler/damlc/lib/DA/Cli/Damlc/Packaging.hs#L74 which obviously fails if you had a dep beforehand.

**Comment by cocreature** [comment]
Rather than trying to fix this specific case, maybe the right approach here is to finally implement incremental package db initialization (as in do nothing if nothing changed, not try to do it partially). That should remove the need for this optimization.
