### ISSUE TITLE
DAML Studio shows DA.Internal.Record in breadcrumb

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#8410]
I don't know when daml studio started showing this "breadcrumb" but it always seems to point to DA.Internal.Record:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/63245722/103769149-a9521500-501b-11eb-940e-0d6065426de7.png">

This seems undesirable. I wonder if we can fix the breadcrumb, or disable it.

**Comment by robin-da** [comment]
I looked into this today. From what I understand the breadcrumbs are taken from the document symbols. Trying to fix these for Daml looks like an uphill battle. Disabling should be possible however.

**Comment by robin-da** [comment]
Fixed with #8708.
