### ISSUE TITLE
damlc build: Improve error message for missing module.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#845]
Running `build` when the source file does not exist gives a pretty bad error message (in this case `daml/Main.daml`, which is specified in `daml.yaml`, which `damlc` knows about, does not exist).

```
$ daml-head build
da-hs-damlc-app: user error (Creation of DAR file failed:
Range:    Range Start: Position Line: 0Character: 0End:   Position Line: 100000Character: 0
Source:   Ide Error
Severity: DsError
Message: 
  daml/Main.daml: getModificationTime:getFileStatus: does not exist (No such file or directory)
Code: 
)
```

**Comment by neil-da** [comment]
The messed up range is as of this yesterday. @DavidM-D is actively working on it.
The lack of filename is also fallout from the same thing.

The only other thing i that getModificationTime isn't the most beautiful - but it's 100% accurate. However, I'll fix that.
