### ISSUE TITLE
Consider a library for Workflow Patterns

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#85]
From @benl23x5-da:

http://www.workflowpatterns.com/
Catalogue of patterns in business workflows. This looks like really comprehensive work. Each of the patterns is described including a Colored Petri Network (CPN), as well as a list of business workflow systems that support it.
There are also PDF files for people who prefer more of an academic paper presentation
eg http://www.workflowpatterns.com/documentation/documents/BPM-06-22.pdf (edited) 
Some of the patterns are also quite deep and well thought out, several steps up from "how do we do multisig in DAML". eg Cancelling Partial Join http://www.workflowpatterns.com/patterns/control/new/wcp32.php
Example: "Once the picture is received, it is sent to three art dealers for the examination. Once two of the prepare condition report tasks have been completed, the remaining prepare condition report task is cancelled and the plan restoration task commences."
Motivation: "This pattern provides a means of expediting a process instance where a series of incoming branches to a join need to be synchronized but only a subset of those tasks associated with each of the branches needs to be completed."

**Comment by cocreature** [comment]
Hasn’t come up in over a year so closing. Feel free to reopen if the need for this reappears.
