### ISSUE TITLE
Type erasure for value seralization

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#8504]
In order to save space in the serialization transaction, we will not serialize
* type constructor for record, variants and enumeration value.  
* field names for record

TODO: 

- [x] do not serialize those data fir 1.dev
- [x] library to put back those data using the value type
- [ ] plug in the ACS and Transaction service the library above to populate missing data in case of verbose mode.

**Comment by cocreature** [comment]
This has been implemented.
