### ISSUE TITLE
Remove support for compiling to older versions of DAML-LF

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#853]
Currently the DAML compiler can generate any version of DAML LF from 1.0 to 1.3. We should remove 1.0 at least, and perhaps everything but 1.3. @bitonic - what's your view?

Note that removing 1.0 allows `instance Functor (-> r)` (and `Applicative`, `Action`).

- [x] 1.0: #863, SDK 0.12.12 is the latest public release supporting DAML-LF 1.0
- [x] 1.1: #1231, SDK 0.12.20
- [x] 1.2: #1428, SDK 0.12.21
- [x] 1.3: #1445, SDK 0.12.21
- [x] 1.4: #1888, SDK 0.13.7
- [x] 1.5: #2161, SDK 0.13.12
- [ ] 1.6

**Comment by bitonic** [comment]
@neil-da I do not have a strong opinion. The engine is going to keep supporting old versions, but feel free to remove the ability to generate old versions.

**Comment by hurryabit** [comment]
DAML-LF 1.0 was dropped in https://github.com/digital-asset/daml/pull/863.

I'll look into DAML-LF 1.1 and 1.2 next to figure out whether removing them saves us a lot of complexity.
