### ISSUE TITLE
Consider adding functionality allowing to inspect the health of the network backing the ledger

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#854]
See https://github.com/digital-asset/daml/issues/854#issuecomment-496868837for the current scope of this ticket.

***

Currently when consuming from one of the streams in the Ledger API there is no clear way to check if the stream is still healthy.

We should implement some form of heartbeats to allow clients to reason about the status of the stream, and disconnect if necessary.

Ideally we'd also include this logic in all our bindings (Java, JavaScript, Scala, etc.).

cc @dajmaki

**Comment by bitonic** [comment]
talked to @gerolf-da and @gaboraranyossy-da . the conclusion is that the right way to do this is to use HTTP2 keep alives, see https://grpc.io/blog/grpc_on_http2/#identifying-failed-connections and  https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-  on how to do this in Java.

**Comment by dajmaki** [comment]
We should clarify whether the application is interested about the health of the stream, or the health of the ledger, e.g. what is the exact use-case in which the behavior of the application would change. In my mind this was about the application being able to react to an issue of liveness with a specific ledger-api server and choosing to reconnect to another server. I'm specifically thinking about this from the end-to-end principle perspective.

**Comment by bitonic** [comment]
@dajmaki I'm confused by the

> choosing to reconnect to another server.

Are you talking about the case where some server behind a load balancer dies and one needs to restart the connection? Because in that case, the HTTP2 keep alive + how the gRPC code works regarding those (see page linked above).

If it's about the server actively communicating a new location to connect to, I think it's something that should not be baked into the Ledger API itself.

**Comment by dajmaki** [comment]
It is about the application having the ability to know whether the system it has connected to is functioning correctly as this is often business critical. Whether we implement this on the stream-level, or as a separate service is up for debate as far as I'm concerned.

**Comment by mziolekda** [comment]
I agree with Jussi's point of view. We should not mix the two notions of errors into one. Keep-alives are perfect to convey the information about the health of the stream itself and to some degree of the health of its source component (Ledger API server in our case). 
It is not best suited to inform the client about the health of the overall system. Two examples that come to my mind:
* loss of quorum in a BFT-type of blockchain system
* loss of mediator in canton
In both of these, the source component is perfectly fine and the stream itself can keep on emitting alive signals. The overall system, however is in a distress and ledger cannot progress.
It seems like the right approach here would be a dedicated service. I am of two minds, whether it should be another semantically enriched Ledger API service or something standard akin to kubernetes [liveness and readiness](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) probes.

**Comment by gerolf-da** [comment]
And how can a client be sure that the service itself is "alive and kicking"? I'd rather go for an approach that the server needs to be aware of its own state and reject/cancel any requests if the overall state is not trustworthy. This behaviour should possibly be configurable by the operator of the ledger.
Mixing normal application logic with operations/monitoring concerns doesn't work well in practice. Also, just because you thought the service was healthy, doesn't mean that it actually will be once the request lands at the server.

**Comment by bitonic** [comment]
To be clear, I'm not arguing that the keep alives convey any specific information about the server, just that they are the right way to detect if the stream is healthy.

I think that some endpoint delivering more specific information about the node health would be useful, but I agree with @gerolf-da -- I would not use this information to drive the reconnection logic.

**Comment by mziolekda** [comment]
A ledger system is complex enough that the patterns in which it can fail/be unhealthy are many. Going back to one of the examples I gave before. Let's assume mediator is gone and we cannot add new transactions. Should this mean that a stream with historic transactions going back 3 years which BTW takes several hours to deliver be interrupted and closed?

I think we have to ask ourselves, what could the client application do with the information that the overall system is broken. I would argue that in 99% of the cases they can't do anything more than inform a human user about the problem by raising an alarm or popping up something on his screen. For that a subscription on a dedicated service seems like a good fit.

If Ledger API server or the stream itself has problems, then there are a few more options. You may try and reconnect to another instance, you may try to close some of your connections to lower the load etc. For that a keep-alive seems ok.

**Comment by bitonic** [comment]
We've had a few more discussions, and it seems that the missing piece of infrastructure that a lot of people would desire is an endpoint that lets people inspect the health of the network that the ledger is running on.

For example, if the ledger is backed by some distributed system, the participant node could expose endpoints to communicate what it thinks about the health of the system, such as whether there were partitions, when was the last time it heard from other participants, etc.

**Comment by gaboraranyossy-da** [comment]
we have a very minimalistic template here we could start with: https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/grpc/health/v1/health_service.proto

**Comment by gerolf-da** [comment]
We now have health checks exposed by the ledger components.
