### ISSUE TITLE
damlc should error out if `dependencies` have a different LF version

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#8553]
We already have a check that `dependencies` and `data-dependencies` have a newer LF version. For `dependencies` we should error out if they have a different LF version regardless of whether it is newer or older.

**Comment by robin-da** [comment]
So `dependencies` should all have the targeted LF version?

**Comment by cocreature** [comment]
Yes, the main DALF (and only that) in a `dependency` should have the target LF version.
