### ISSUE TITLE
Repl terminal changes unicode chars input to "??" 

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#8573]
Reproduce:

1. Start `daml repl`
2. Copy and paste _without a newline_: `"á"`:
   ```
   daml repl 
   daml> "??"
   ```
   _Note:_ hitting Enter will crash Repl which may be a separate issue (see #8574)

**Comment by robin-da** [comment]
Hi @richardkapolnai-da . I can't reproduce this:
```
daml> "ش"
"ش"
```

What terminal are you using?

**Comment by richardkapolnai-da** [comment]
Strange...

> What terminal are you using?

Ubuntu 18.04, gnome-terminal, bash, LANG=en_US.UTF-8

```
$ echo "ش"
ش
$ daml repl
daml> "??"
```

**Comment by robin-da** [comment]
Where and when do you set LANG? Can you try setting it in your ~/.bashrc just to be sure it was set to support unicode? And could you also try a different unicode supporting terminal?
