### ISSUE TITLE
Repl crashes for non-English characters

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#8574]
When a non-English character has to be printed, Repl crashes.
Reproduce:

1. Start `daml repl`
2. Copy and paste: `["a", "á"]`, and hit Enter
   ```
   daml repl 
   daml> ["a", "??"]
   ["a","damlc: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
   ```
   _Note:_ Repl replaces unicode input to "??" which may be a separate issue (see #8573)

**Comment by robin-da** [comment]
Hi @richardkapolnai-da. I can't reproduce:
```daml> ["a", "ሲ"]
["a","ሲ"]
```
works just fine. I think this might be a problem with the terminal your using.

**Comment by richardkapolnai-da** [comment]
Interesting. But REPL shouldn't crash for this input...
```
$ echo ["a", "ሲ"]
[a, ሲ]
$ echo '["a", "ሲ"]' | daml repl
daml> ["a","damlc: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
$ echo $?
1
```
