### ISSUE TITLE
LF 1.13

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#8591]
Ticket for the next stable LF version after LF 1.12

Previous LF version ticket: #8369

Task:

- [x]  BigNumeric 
- [x] preview version (in SDK 1.13) 
- [x] release version (in SDK 1.14)
- [ ] default compiler output (in SDK 1.15) #9907

**Comment by cocreature** [comment]
We released LF 1.13 with BigNumeric only so this has been solved.

**Comment by remyhaemmerle-da** [comment]
The issue is close when the version is the default compiler output.
