### ISSUE TITLE
Improve error messages in scenario failures

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#86]
They should have line numbers, and the line numbers should jump to the source file.

**Comment by martin-drhu-da** [comment]
https://github.com/digital-asset/daml/pull/390 brings the location information back. The links don't work though. I'll continue working on that.

**Comment by martin-drhu-da** [comment]
The remaining thing we need to do is to make the links from the scenario view (transaction tree) into the code work again. @akalburgi can you please take this?

**Comment by hurryabit** [comment]
The broken links were the last missing bit to fix.
