### ISSUE TITLE
Navigator radio button values are not displayed

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#8691]
When mutliple radio buttons are in a choice page, they are not all displayed:

![navigator-bool-fields](https://user-images.githubusercontent.com/53859003/106288070-dc1cb100-6247-11eb-8106-05972d9ffeb4.gif)

A possible way to reproduce it is following the workflow of the [KYC](https://github.com/digital-asset/ex-know-your-customer) ref app (no need for all triggers).

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
