### ISSUE TITLE
import Daml.Script

### ISSUE THREAD

**Issue by skulos** [digital-asset/daml#8727]
Think I'm late to the discussion, but how does one solve this issue?

```
Could not find module ‘Daml.Script’
It is not a module in the current program, or in any known package.
```

**Comment by cocreature** [comment]
Hi @skulos, to fix that you need to make sure that `daml-script` is listed in the `dependencies` section in your `daml.yaml`, e.g.,
```
dependencies:
  - daml-prim
  - daml-stdlib
  - daml-script
```
Once you’ve made that change, `daml build` should work. You have to restart VSCode once you made the change. If that doesn’t help, make sure that you are starting vscode from the directory where the daml.yaml file is located.

**Comment by skulos** [comment]
@cocreature Thank you so much. It works, and I've gotten all of my colleagues to do the same. ( 👍  A really big thumbs up 👍 )
