### ISSUE TITLE
Ability to exclude .daml files from dar package

### ISSUE THREAD

**Issue by grahamewebb-da** [digital-asset/daml#876]
Ability to exclude .daml files from .dar package when building a project (currently when running `da compile`)

**Comment by neil-da** [comment]
Because of proprietory code? CC @robin-da

**Comment by hurryabit** [comment]
We currently use the `.daml` files to generate interface (`.hi`) files when installing a package. We would need to ship the `.hi` files, which contain mostly just type information, instead. This might cause trouble if you use a package that was compiled with a different version of the SDK. We'll need to investigate before we can make definitive statements on this though.

**Comment by hurryabit** [comment]
@grahamewebb-da Given the slack conversation, are you happy to close this ticket?

**Comment by grahamewebb-da** [comment]
Yes @neil-da. The use case description is as follows. Given the Slack conversation though - which I completely support - means that the steer is to consider other ways of meeting this requirement within the enterprise. Closing.

> I am a developer who codes on behalf of multiple entities within my enterprise and I have sensitivity about some of the code in my DAML that I don’t want to release to all internal parties if I can avoid it).

**Comment by grahamewebb-da** [comment]
> @grahamewebb-da Given the slack conversation, are you happy to close this ticket?

Done
