### ISSUE TITLE
Navigator: upgrade webpack version

### ISSUE THREAD

**Issue by rautenrieth-da** [digital-asset/daml#877]
Navigator uses webpack 2.x, which contains some transitive dependencies with security issues:
- tar < 4.4.2
- webpack-dev-server < 3.1.11

Latest version of webpack is 4.x. To upgrade webpack, we need to:
- Update the webpack config file
- Upgrade the versions of all webpack plugins
- Make sure the TypeScript compiler plugin is compatible with the old TypeScript version Navigator uses, in order to avoid having to upgrade the TypeScript version as well.

**Comment by stefanobaghino-da** [comment]
Closing.
```
navigator/frontend/package.json:    "webpack": "4.41.2",
navigator/frontend/package.json:    "webpack-cli": "3.3.10",
navigator/frontend/package.json:    "webpack-dev-server": "3.9.0"
```
