### ISSUE TITLE
Incorrect warning message about source of Daml version:

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#8783]
```
$ make
daml build --project-root backend/models
Warning: Using SDK version 1.10.0-snapshot.20210201.6207.0.7cf1914d from DAML_SDK_VERSION enviroment variable instead of SDK version 1.8.0 from daml.yaml config file.
Warning: Using SDK version 1.10.0-snapshot.20210201.6207.0.7cf1914d from DAML_SDK_VERSION enviroment variable instead of SDK version 1.8.0 from daml.yaml config file.
Warning: Using SDK version 1.10.0-snapshot.20210201.6207.0.7cf1914d from DAML_SDK_VERSION enviroment variable instead of SDK version 1.8.0 from daml.yaml config file.
..
$ env | grep DAML
$
```

The `daml` command must be grabbing the version from a different source, global config?

PS. "enviroment" is misspelled.

**Comment by leonidr-da** [comment]
IMO, I think this is undesired behavior and the version should default to what is in `daml.yaml`.

**Comment by cocreature** [comment]
This is unfortunately expected behavior, see https://discuss.daml.com/t/why-does-project-root-not-pick-up-the-sdk-version-of-the-project/1595/2 for details.

**Comment by leonidr-da** [comment]
I see, can the action item then be to remove `--project-root` as an argument in favor of the `DAML_PROJECT` environment variable?

**Comment by cocreature** [comment]
That’s a breaking change and there are some cases where `--project-root` is useful. What we should probably do is to change the help text to mention DAML_PROJECT and maybe eventually hide it.

**Comment by leonidr-da** [comment]
Fair enough, should I close this issue? Or we'll leave your suggestion as the action item for this issue?

**Comment by leonidr-da** [comment]
And related, did something change? I don't think that I had this issue previously. The `Makefile` that I wrote with the `--project-root` argument is from the end of 2020.

**Comment by cocreature** [comment]
Nothing changed here. I suspect you probably just didn’t hit it before because the global SDK version you had installed at the time matched what was in your project. https://github.com/digital-asset/daml/pull/8790 clarifies the docs around this to hopefully address confusion in the future.

**Comment by leonidr-da** [comment]
Looks good to me!
