### ISSUE TITLE
return relative file paths for dependencies

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#88]
Make sure that `getDependencies`  https://github.com/DACH-NY/daml/blob/master/daml-foundations/daml-ghc/src/Development/IDE/State/Rules.hs#L117 returns relative file paths instead of absolute ones. After that we don't need to make file paths absolute anymore in https://github.com/DACH-NY/daml/blob/master/daml-foundations/daml-ghc/src/DA/Service/Daml/Compiler/Impl/Dar.hs#L57.

**Comment by cocreature** [comment]
The code that was making the file paths absolute is long gone afaict.
