### ISSUE TITLE
Default signatures causing problems with data-dependencies

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#8802]
Default signatures on class functions get in the way when a package is used as a data-dependency of another.

In my example, package 1 declares a class with a function having a constrained default implementation, and an instance that uses a _different_ implementation and does not satisfy the constraint.

Package 2 declares a _data_ dependency to package 1 (does not need any code).

Compilation fails when trying to compile the stub code for package 1
```
  .daml/package-database/1.8/package1-0-f8fc4a814e4e4d776db5b4dd7e7e6d46f024b942648c06154cefdc90990e6c57/WithAClass.daml:24:10:
  error:
  • No instance for (Show MyType)
  arising from a use of ‘WithAClass.$dmf’
  • In the expression: WithAClass.$dmf @(MyType)
  In an equation for ‘f’: f = WithAClass.$dmf @(MyType)
  In the instance declaration for ‘AClass MyType’
```

### Package 1
`daml.yaml`
```
sdk-version: 1.10.0-snapshot.20210202.6218.0.c0573678
name: package1
version: "0"
source: daml

dependencies:
- daml-stdlib
- daml-prim
```
File `daml/WithAClass.daml`
```
module WithAClass where

class AClass a where
    f : a -> Text
    default f : Show a => a -> Text
    f = show

data MyType = MyType -- without show instance

instance AClass MyType where
    f = const "MyType"
```
### Package 2
daml.yaml
```
sdk-version: 1.10.0-snapshot.20210202.6218.0.c0573678
name: package2
version: "0"
source: daml

dependencies:
- daml-stdlib
- daml-prim

data-dependencies:
- ../package1/.daml/dist/package1-0.dar
```

**Comment by sofiafaro-da** [comment]
Hi @jberthold-da! Thanks for reporting this issue. I can reproduce this and have identified the problem.

**Comment by sofiafaro-da** [comment]
#8833 fixes this.
