### ISSUE TITLE
Daml Intro examples don't compile

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#8813]
As flagged up in https://discuss.daml.com/t/expected-content-of-sample-folders/2072, some of the Introduction to Daml examples don't work because they don't contain a `daml.yaml` file, and `daml-script` isn't loaded without one. There are two ways to fix this:

1. Add `daml.yaml` files to the projects that don't have one
2. Default to loading `daml-script` in the absence of a `daml.yaml`

@cocreature which of the above do you think we should do?

**Comment by cocreature** [comment]
I’d definitely do 1. I’m not opposed to doing 2 in addition to that but I think templates should all be standalone projects not single files.
