### ISSUE TITLE
Make the Java codegen examples use the Daml assistant

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#8817]
The Java codegen generation as described in the [codegen](https://docs.daml.com/app-dev/bindings-java/codegen.html)  section is a bit out of date with the way that it is described in the [quickstart example](https://docs.daml.com/app-dev/bindings-java/quickstart.html#integrate-with-the-ledger).  In particular, in the former we are issuing commands via `java` directly, whereas in the latter we use the `daml` assistant.

**Comment by anthonylusardi-da** [comment]
Related, from the forum [a user mentioned](https://discuss.daml.com/t/gradle-version-of-quickstart-java-template/2358/19) `DamlLedgerClient.forHostWithLedgerIdDiscovery()` [is deprecated](https://docs.daml.com/app-dev/bindings-java/javadocs/com/daml/ledger/rxjava/DamlLedgerClient.html) which is referenced in this section.

**Comment by stefanobaghino-da** [comment]
> forHostWithLedgerIdDiscovery

@anthonylusardi-da The user was saying that the example used a deprecated method. If there's not a ticket for that, you may want to open it in the appropriate repository.
