### ISSUE TITLE
Variance of type parameters in Scala codegen

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#8844]
Currently, the scala codegen generates all type parameters as [covariant](https://github.com/digital-asset/daml/blob/ff28059c635a71565b47ae80f121f8e3f923a23b/language-support/scala/codegen/src/main/scala/com/digitalasset/codegen/lf/DamlDataTypeGen.scala#L72). This worked fine so far: We only deal with serializable types so no way to use functions to change variance and all LF primitives had type parameters in covariant positions.

However, the introduction of GenMap changed this: We map this to `InsertOrdMap[K, V+]` which is invariant in `K`. This breaks code such as the following:

```
template Foobar
  with
    operator : Party
    things : MySet Text
  where
    signatory operator

data MySet k = MySet { unwrap : Map k () }
  deriving (Show, Eq)
```

```
bazel-out/k8-opt/bin/language-support/scala/codegen-sample-app/tmp6320987924609045777/com/daml/sample/mymain/MySet.scala:51: error: type mismatch;
 found   : com.daml.ledger.client.binding.Primitive.GenMap[?k1,com.daml.ledger.client.binding.Primitive.Unit] where type ?k1 <: k (this is a GADT skolem)
    (which expands to)  com.daml.lf.data.InsertOrdMap[?k1,Unit]
 required: com.daml.ledger.client.binding.Primitive.GenMap[k,com.daml.ledger.client.binding.Primitive.Unit]
    (which expands to)  com.daml.lf.data.InsertOrdMap[k,Unit]
Note: ?k1 <: k, but class InsertOrdMap is invariant in type K.
You may wish to define K as +K instead. (SLS 4.5)
                case _root_.com.daml.sample.MyMain.MySet(unwrap) => unwrap
                                                                    ^
com.daml.ledger.client.binding.Primitive.GenMap[?k1,com.daml.ledger.client.binding.Primitive.Unit] <: com.daml.ledger.client.binding.Primitive.GenMap[k,com.daml.ledger.client.binding.Primitive.Unit]?
false
```

I see two ways out of this:

1. Track variance of type parameters. This should work I believe but it’s annoyingly complex to implement (you need to track this through every type). However, it is non-breaking.
2. Make type parameters invariant everywhere. This also fixes the issue but at a relatively high cost: this will almost certainly break some code. We actually used to do this but switched away, see DEL-3214 for the reasoning.
3. Something else?

**Comment by iggy-da** [comment]
Minimal example: [minimal.tar.gz](https://github.com/digital-asset/daml/files/5984554/minimal.tar.gz)
