### ISSUE TITLE
daml test --with-dlint command is not checking for .dlint.yaml instead checking for dlint.yaml

### ISSUE THREAD

**Issue by Nandansv** [digital-asset/daml#8874]
When we issue a command `daml test --with-dlint .\<PROJECTFOLDER>` it has to check for `.dlint.yaml` .. instead its checking for `dlint.yaml` . If run above query .. Its throwing below error.<br>
![image](https://user-images.githubusercontent.com/9913143/108187046-12a56780-7134-11eb-96e3-91ef128a2375.png)
<br>
When i tried renaming file to `dlint.yaml` and ran query. It worked.
<br>
SDK Version: 1.9.0
<br>

**Comment by cocreature** [comment]
Hi @Nandansv. The `--with-dlint` option was only accidentally exposed and shouldn’t be used externally. In SDK 1.10, we hid the option. If you want to lint your project, use `daml damlc lint`.

**Comment by Nandansv** [comment]
Hi @cocreature , `daml damlc lint ` also doesnt seem to be working. <br> Is this the correct command? 👇
![image](https://user-images.githubusercontent.com/9913143/108227951-67f96d00-7164-11eb-8f78-7ebdcc25a420.png)

**Comment by cocreature** [comment]
`FILE` is a placeholder. You have to put in the file you want to lint.

**Comment by Nandansv** [comment]
> `FILE` is a placeholder. You have to put in the file you want to lint.

If i want to lint whole project?

**Comment by cocreature** [comment]
At the moment, there is no support for linting a whole project. I fully agree that this is a sensible feature so I’ve opened #8887 to track this.

**Comment by cocreature** [comment]
closing in favor of #8887
