### ISSUE TITLE
Switching tabs in VS Code is unpleasant

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#89]
If I change between two code panes in VS Code then the scenario tips keep animating in each time. Any way to avoid that?

If I change between two scenario panes then any changes I've made (like showing the other view) disappear. With the latest changes it also flickers, taking a little while to load (a regression relative to what it had before).

**Comment by cocreature** [comment]
I’m not entirely sure I understand the issue here but I am unable to reproduce this so closing.
