### ISSUE TITLE
Template level "spread operator" missing type-information required for disambiguation of field names

### ISSUE THREAD

**Issue by darko-da** [digital-asset/daml#8918]
I have a piece of code that works in 1.8, but throws errors on 1.9.
It seems that `let MyType{..} = var` loses some type-information required for disambiguation of field names.

Here is a minimum example
```
module SpreadOperator where

data DataTypeOne = DataTypeOne with
  partyName : Party
    deriving (Eq, Show)

data DataTypeTwo = DataTypeTwo with
  partyName : Party
    deriving (Eq, Show)

template ImportTest with
    import_var: DataTypeOne
  where
    let DataTypeOne{..} = import_var
    signatory partyName
```

The error is:
```
~/tmp/myproject/daml/SpreadOperator.daml:15:15: error:
    Ambiguous occurrence 'partyName'
    It could refer to
       either the field 'partyName',
              defined at ~/tmp/myproject/daml/SpreadOperator.daml:8:3
           or the field 'partyName',
              defined at ~/tmp/myproject/daml/SpreadOperator.daml:4:3
```

I would expect that `let DataTypeOne{..} = import_var` has enough type information do disambiguate.

The issue persists in Daml Connect 1.10.

@garyverhaegen-da mentioned that there was a change to template-level bindings that might be causing it.

**Comment by garyverhaegen-da** [comment]
Note that the issue persists without the spread operator:

```
module Main where

data DataTypeOne = DataTypeOne with
  partyName : Party
    deriving (Eq, Show)

data DataTypeTwo = DataTypeTwo with
  partyName : Party
    deriving (Eq, Show)

template ImportTest with
    import_var: DataTypeOne
  where
    let DataTypeOne{partyName} = import_var
    signatory partyName
```
still fails with the same error.

**Comment by nickchapman-da** [comment]
There is something not working with
```
let DataTypeOne{partyName} = import_var
```

Changing to the following makes the example work:
```
let DataTypeOne{partyName=partyName} = import_var
```

**Comment by garyverhaegen-da** [comment]
I've bisected this (thanks @darko-da for providing such a small reproduction), and it looks like the first commit that exhibits this behaviour is a7891a32b5c199a95afe529af3ca71364a8ac229. I don't really feel qualified to look further into it myself, but hopefully that can serve as a good starting point.

**Comment by cocreature** [comment]
@garyverhaegen-da’s example actually has two errors, the first one being much more worrying imho:

```
File:     /home/moritz/tmp/Test.daml
Hidden:   no
Range:    1:1-1:1
Source:   typecheck
Severity: DsError
Message:  /home/moritz/tmp/Test.daml:1:1: error:Variable not in scope: pun-right-hand-side
File:     /home/moritz/tmp/Test.daml
Hidden:   no
Range:    15:15-15:24
Source:   typecheck
Severity: DsError
Message:
  /home/moritz/tmp/Test.daml:15:15: error:
  Ambiguous occurrence ‘partyName’
  It could refer to
  either the field ‘partyName’,
  defined at /home/moritz/tmp/Test.daml:8:3
  or the field ‘partyName’,
  defined at /home/moritz/tmp/Test.daml:4:3
ERROR: Compilation failed.
damlc: Error when running Shake build system:
ExitFailure 1
```
The same thing holds for @nickchapman-da’s first example.

If you look under `--ghc-option=-ddump-parsed` you can get a rough idea what is going on: With the record wildcards, the binding is completely ignored!

Looking at the one with the error, we end up with
```
_templateLet_ImportTest this@ImportTest {..}
  = let DataTypeOne {partyName} = import_var in
    let _ = this in pun-right-hand-side
```
which clearly doesn’t work.

It looks like the `collectLocalBinders` stuff doesn’t work properly (it can’t! We don’t have type info to resolve all names in a record wild card). For reference, here’s how the `NamedFieldPuns` version looks

```
             (ConPatIn
              ({ /home/moritz/tmp/Test.hs:8:3 }
               (Unqual
                {OccName: X}))
              (RecCon
               (HsRecFields
                [({ /home/moritz/tmp/Test.hs:8:5 }
                  (HsRecField
                   ({ /home/moritz/tmp/Test.hs:8:5 }
                    (FieldOcc
                     (NoExt)
                     ({ /home/moritz/tmp/Test.hs:8:5 }
                      (Unqual
                       {OccName: x}))))
                   ({ <no location info> }
                    (VarPat
                     (NoExt)
                     ({ <no location info> }
                      (Unqual
                       {OccName: pun-right-hand-side}))))
                   (True)))]
```
and here’s how the `RecordWildCards` version looks:

```
             (ConPatIn
              ({ /home/moritz/tmp/Test.hs:6:3 }
               (Unqual
                {OccName: X}))
              (RecCon
               (HsRecFields
                []
                (Just
                 (0))))))
```
@nickchapman-da can you please take a look at this? Not super urgent imho given that it has a clear workaround but we should fix that. (@darko-da if you think it’s urgent, please let us know)

**Comment by darko-da** [comment]
Definitely not urgent as one can easily not use that feature.

**Comment by moisesackerman-da** [comment]
With template-let syntax gone in Daml 3.0 (https://github.com/digital-asset/daml/pull/18262), this is no longer an issue.
