### ISSUE TITLE
Make NodeExercises#controllers a boolean

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#894]
To prevent controllers from being misused, carry out the collapse of the invalid states to a boolean as described in
https://github.com/digital-asset/daml/pull/766#discussion_r280506930

Re @bitonic 
> ok, I undestand your proposal now. I'm undecisive, but in the meantime I'm going to merge this, since this only affects the internals.

**Comment by gerolf-da** [comment]
@S11001001: is this something we should still do?
