### ISSUE TITLE
Daml Studio prints warnings about non-exhaustive pattern matches on lists incorrectly

### ISSUE THREAD

**Issue by kpinter-da** [digital-asset/daml#8947]
The following code:
```
f = \case
  [] -> 0
  [a, b, c] -> 3
```
Produces this warning:
```
    Pattern match(es) are non-exhaustive
    In a case alternative:
        Patterns not matched:
            [_]
            [_, _]
            (_:_:_:_:_)
```
The last unmatched pattern uses `:` instead of `::`.

**Comment by dylant-da** [comment]
This should be in GHC's error system which generates pretty printings of warnings, and then potentially postprocessed by daml-ghcide.
