### ISSUE TITLE
Incorrect Sandbox CLI help text for log level

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#9007]
The Sandbox CLI help text reads

```
  --log-level <value>      Default logging level to use. Available values are INFO, TRACE, DEBUG, WARN, and ERROR. Defaults to INFO.
```

This is not correct. The default mode is determined by https://github.com/digital-asset/daml/blob/master/ledger/sandbox-common/src/main/resources/logback.xml, which sets different defaults for different loggers.

**Comment by cocreature** [comment]
Duplicate of https://github.com/digital-asset/daml/issues/6777
