### ISSUE TITLE
//ledger/ledger-api-test-tool:ledger-api-test-tool-ssltest flaky on master

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#906]
This seemingly unrelated [commit](https://github.com/digital-asset/daml/commit/0ebdcb961edfc0cae74fb1d92327e56d32918562) failed to [build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=4299). Rerun passed so this is flaky. @gleber-da is this related to #815?

**Comment by gleber-da** [comment]
It's a dupe of #815
