### ISSUE TITLE
Flaky Master Windows: Couldn't reserve space for cygwin's heap

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#916]
This error appears somewhat frequently as a flaky Windows build failure on master:
```
ERROR: error loading package '': Encountered error while reading extension file 'haskell/repositories.bzl': no such package '@io_tweag_rules_haskell//haskell': Traceback (most recent call last):
	File "C:/users/vssadministrator/_bazel_vssadministrator/w3d6ug6o/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
		patch(ctx)
	File "C:/users/vssadministrator/_bazel_vssadministrator/w3d6ug6o/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 84, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @com_github_digital_asset_daml//bazel_tools:haskell-static-linking.patch:
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x60EA0000, RegionSize 0x80000, State 0x10000
C:\Users\VssAdministrator\dadew\scoop\apps\patch-2.6.1\current\bin\patch.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
```

I am currently assuming this will be fixed by switching to our own Windows nodes, but would welcome any insight as to how we could solve it with the existing ones if possible.

**Comment by neil-da** [comment]
I think another way of fixing it would be to use a cygwin-free `patch`, specifically the mingw `patch` instead. Not sure how easy it is to persuade Scoop to install that one instead. @majcherm-da ?

**Comment by cocreature** [comment]
Looking at https://github.com/digital-asset/daml/blob/master/dev-env/windows/manifests/patch-2.6.1.json it seems like we already use the mingw `patch` so I’m somewhat confused how cygwin comes into play here.

**Comment by neil-da** [comment]
I just had this fail on CI. Seems to be a regular problem.

**Comment by majcherm-da** [comment]
@neil-da I'll take a look

**Comment by garyverhaegen-da** [comment]
Thanks @majcherm-da !
