### ISSUE TITLE
DA.Next.Map and DA.Next.Set instances go missing under data dependencies across SDK versions.

### ISSUE THREAD

**Issue by mjhopkins-da** [digital-asset/daml#9170]
`DA.Next.Map` and `DA.Next.Set` don't seem to get on with data dependencies when different SDK versions are being used.

The following setup illustrates the issue. We have two packages, `a` and `b`; `b` depends on two versions of `a` using data dependencies. `a` uses an SDK version _before 1.11.0_ (I've tested 1.6.0, 1.9.0, 1.10.0); `b` uses SDK 1.11.0.

### package `a`
```haskell
module A where

import DA.Next.Map

newtype A = A (Map Int Int)
  deriving (Eq, Show)
```

### package `b`
```haskell
module Convert where

import DA.Next.Map qualified as Map
import DA.Next.Map (MapKey, Map)

import New.A as New
import Old.A as Old

class Convert a b where
  convert : a -> b

instance Convert Int Int where
  convert = identity

instance (MapKey k, MapKey k', Convert k k', Convert v v') =>
  Convert (Map k v) (Map k' v') where
    convert oldMap = Map.fromList
      [ (convert k, convert v)
      | (k, v) <- Map.toList oldMap
      ]

instance Convert Old.A New.A where
  convert (Old.A m) = New.A (convert m)
```

Package `b` fails with build with

```
  No instance for (Convert
  (daml-stdlib-148dc82adc22ae5e8e26504c5c893f0c2e84667889c31e904c7ca868893e4dd0:DA.Next.Map.Map
  Int Int)
  (daml-stdlib-148dc82adc22ae5e8e26504c5c893f0c2e84667889c31e904c7ca868893e4dd0:DA.Next.Map.Map
  Int Int))
  arising from a use of ‘convert’
```

The instance it's asking for does exist, which I can prove by adding a simple test function, which on its own compiles fine:

```
testMapInstance = convert @(Map Int Int) @(Map Int Int)
```

A similar thing happens with `DA.Next.Set`, but not with `DA.Map` or `DA.Set`.
The issue doesn't arise if data dependencies aren't used, or if both packages are on the same SDK version.

Oddly, I cannot write instances for both `DA.Next.Map` and `DA.Map` (or `DA.Next.Set` and `DA.Set`); this gives an error about duplicate instance declarations (even though there are none).

**Comment by cocreature** [comment]
`DA.Next.Set` is not a stable type `Set` in SDK 1.9.0 is unrelated from `Set` in SDK 1.11.0 which is why you get this error. However, both modules are already deprecated in favor of `DA.Set` and `DA.Map` which are stable so we have no plans to spend the effort on `DA.Next.Set/Map`.

**Comment by cocreature** [comment]
Note that you can fix your example, you just have to be explicit about there being two map types:
```
module Convert where

import DA.Next.Map qualified as Map
import DA.Next.Map (MapKey, Map)

import qualified OldStdlib.DA.Next.Map

import New.A as New
import Old.A as Old

class Convert a b where
  convert : a -> b

instance Convert Int Int where
  convert = identity

instance (MapKey k, MapKey k', Convert k k', Convert v v') =>
  Convert (OldStdlib.DA.Next.Map.Map k v) (Map k' v') where
    convert oldMap = Map.fromList
      [ (convert k, convert v)
      | (k, v) <- OldStdlib.DA.Next.Map.toList oldMap
      ]

instance Convert Old.A New.A where
  convert (Old.A m) = New.A (convert m)
```
and the following in your `daml.yaml`

```
build-options:
  - "--package"
  - "daml-stdlib-e6de631e9f140f1f0bac42e2066ae96f16faaba0cfe55a7201c0ce8a16723ec7 (DA.Next.Map as OldStdlib.DA.Next.Map)"
```
