### ISSUE TITLE
Feature request: In IDE script table view remember checkbox choices

### ISSUE THREAD

**Issue by shaul-da** [digital-asset/daml#9177]
When making changes to a script, the "show archived" and "show detailed disclosure" choices get reset. Would be more convenient if these keep my last setting

**Comment by cocreature** [comment]
Agreed, the current behavior is silly.

**Comment by chrisnorris-da** [comment]
Could the initial choices be somehow configurable in VS Code? Given the detailed disclosure information has been surfaced, there is now never a time when I would want that information hidden (with 'X'); yet this default is forced upon me. The first thing I do in any script now is click the detailed disclosure box. Would be neater not to have to even do that.

**Comment by cocreature** [comment]
Reasonable feature request, please open a separate issue for that.

**Comment by garyverhaegen-da** [comment]
Should we just drop the simplified view?

**Comment by cocreature** [comment]
I think most of our users are far less experienced than @chrisnorris-da so I wouldn’t do it just based on that request. We do get confused users occasionally who don’t understand the difference on the forum but I’m not quite sure if hiding it addresses that. For now, I’d keep it.
