### ISSUE TITLE
Feature request: In IDE script table view enable configuration of default view

### ISSUE THREAD

**Issue by chrisnorris-da** [digital-asset/daml#9188]
Given the detailed disclosure information now surfaced, there is never a time when I want that information hidden (with 'X'); yet this default is forced upon me. Having to click non-persisting checkboxes to opt into the detail I need is awkward. It would be nicer if e.g. a configuration option in VS Code was made available to override this.

**Comment by cocreature** [comment]
Rather than adding a config for the default, I’d probably go to just remember the last setting used in any scenario and keep that. A bit simpler in terms of UX than adding a config field.
