### ISSUE TITLE
How do you fully uninstall daml?

### ISSUE THREAD

**Issue by joehenry087** [digital-asset/daml#9261]
Looking to fully wipe daml and all related programs, scripts, data, etc from my machine. How does one do this?

My particular OS is Mac, but it would be good to have this information for any OS. I could not find this information in the docs.

These are the instructions I followed for installation: https://docs.daml.com/getting-started/installation.html

**Comment by cocreature** [comment]
You should only need to delete `$DAML_HOME` (defaults to `~/.daml`, run `daml exec env` to verify) and remove the changes you made to `.bash_profile`/`.zprofile` to add that to PATH.

**Comment by cocreature** [comment]
Closing, feel free to reopen if that didn’t work.
