### ISSUE TITLE
Incompatible Types in conditional statement

### ISSUE THREAD

**Issue by Enthusiast-block** [digital-asset/daml#9284]
Hi,
I am using the following conditional statement in my daml code.

```
entityId = if newEntityId == "" then entityId else newEntityId
```

Here, "newEntityId" and "entityId" has a type of "Optional Text" and it gives this error when I hover over the double inverted comas :- 

Couldn't match expected type ‘Optional Text’
                  with actual type ‘Text’

Is this a bug or comparing these types is not allowed in daml (as both are text only)?

**Comment by cocreature** [comment]
Hi @Enthusiast-block, in Daml you can only compare values of the same type. There are a few different options depending on your requirements mainly around whether `None` should compare equal to `""` or not.

`None` is separate from `""`
```
entityId = if newEntityId == Some"" then entityId else newEntityId
```

`None` is identical to `""`
```
entityId = if newEntityId == Some "" || isNone newEntityId then entityId else newEntityId
```

**Comment by Enthusiast-block** [comment]
Thanks @cocreature, I went with second option and it worked
