### ISSUE TITLE
Make everything work on Alpine Linux

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#93]
Official request from @nycnewman:

> Please take this as an official request to add to the backlog a port to Alpine as this has less vulnerabilities than the default Debian/Ubuntu Docker base images

**Comment by garyverhaegen-da** [comment]
#1811 may be construed as addressing this, depending on the missing context in this issue's description.

**Comment by neil-da** [comment]
In the sense we now rebuild regularly, rather than we moved to Alpine?

**Comment by garyverhaegen-da** [comment]
The automated setup is building on the Alpine OpenJDK variant.

> On 21 Jun 2019, at 19:35, Neil Mitchell <notifications@github.com> wrote:
> 
> In the sense we now rebuild regularly, rather than we moved to Alpine?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This message, and any attachments, is for the intended recipient(s) only, 
may contain information that is privileged, confidential and/or proprietary 
and subject to important terms and conditions available at 
http://www.digitalasset.com/emaildisclaimer.html 
<http://www.digitalasset.com/emaildisclaimer.html>. If you are not the 
intended recipient, please delete this message.

**Comment by neil-da** [comment]
In that case I'd say we are 100% solved, once that is the way we produce docker images.

**Comment by garyverhaegen-da** [comment]
`0.13.10` has been automatically deployed to Docker Hub as an Alpine-based image upon release publication. All previous releases published on GitHub have also been pushed as Alpine-based images.

I think that qualifies as "this is the way we produce Docker images now"; please reopen if you disagree.
