### ISSUE TITLE
Create utilities to upload Maven packages to Artifactory

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#9306]
Right now uploading Maven packages to Artifactory is done as part of `ci/copy-unix-release-artifacts.sh` and `ci/publish-artifactory.sh`. Instead of a script, it would be more maintainable to have utilities like the ones we have for Maven Central.

_Originally posted by @cocreature in https://github.com/digital-asset/daml/pull/9305#discussion_r604790510_

**Comment by stefanobaghino-da** [comment]
@garyverhaegen-da I understand you were not initially involved in this but you probably have the best perspective to answer this question: is this ticket still relevant?

**Comment by garyverhaegen-da** [comment]
It is in the sense that the situation is still as described: we still have a Haskell program for uploading Maven artifacts and a bunch of disparate `curl` calls for Artifactory uploads.

I would dispute the premise of the ticket, though, both then and now: I have not felt that the current approach to Artifactory uploads lead to any maintainability issue, or that creating "utilities" would improve anything.

For context, uploading to Artifactory is a simple HTTP PUT call with a token in an Authorization header. It's a single operation, perfectly encapsulated by a `curl` command. Uploading to Maven, however, requires (roughly) creating a temporary storage space on Sonatype, uploading artifacts there, and then "committing" that temporary space to create a release. It's a much more involved process, which I think changes the discussion quite a bit.

So my position would be to close this as "won't fix".
