### ISSUE TITLE
Restore non-repudiation client libraries publishing on Artifactory

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#9315]
The part that publishes the non-repudiation client libraries on Artifactory has been commented out of `ci/publish-artifactory.sh`. Restore it and find out why uploading either POM causes an HTTP 409 Conflict error code.

Please coordinate with @remyhaemmerle-da who's in charge of the release next Wednesday.

Temporarily assigning to @cocreature to make sure this is tackled next week, feel free to assign it to whomever. 🙂

**Comment by cocreature** [comment]
@garyverhaegen-da could you please take a look at that? Happy to catch you up on what we tried so far but I think this needs someone with artifactory access to debug it efficiently.

**Comment by cocreature** [comment]
fixed in #9323, thanks @garyverhaegen-da!
