### ISSUE TITLE
Alpha version of daml script exports

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#9374]
This is a tracking ticket for things we have to do before releasing an alpha version of daml script exports (what used to be called daml script dumps).

1. Expose it in the assistant under `daml export script`. This addresses both feedback that `dump` doesn’t sound nice and includes `script` in the name to allow for other export formats (e.g., you could imagine a binary export for certain usecases) under the same command.
2. Add some documentation. Doesn’t have to be super detailed but should at least show the basics and document the caveats that exist at the moment.

**Comment by sofiafaro-da** [comment]
Since this is a ledger command, I think the command would be better exposed under `daml ledger`. Something like `daml ledger export script`, or `daml ledger export-script`, or ... something. Also it ought to pick up ledger.host and ledger.port options from daml.yaml automatically, like the other `daml ledger` commands.

What do you think? @aherrmann-da @cocreature

**Comment by cocreature** [comment]
@sofiafaro-da I’m slightly leaning towards agreeing with you here but where do we draw the line? daml script, daml triggers, the JSON API, … all connect to a ledger so should they also all go under `daml ledger`? The best distinction I can come up with is that `daml ledger` commands are never long-running services (that excludes the ones I mentioned before but wouldn’t exclude script exports) and perhaps maps somewhat directly to ledger API functionality (that one is a bit more fishy for script exports).

I’d probably go for your suggestion (although I have a slight preference for `daml ledger export script` but that also seems a bit longish). I agree we should infer host and port but I don’t think that should block this PR.

**Comment by sofiafaro-da** [comment]
> I’m slightly leaning towards agreeing with you here but where do we draw the line? 

That's a good question. I think that distinction makes sense (`daml ledger` commands are non-long-running commands that communicate with the ledger). I also think of it a bit like a "noun verb" sentence -- "daml ledger <verb>" means "do <verb> with a daml ledger", which is a pattern that "daml ledger export script" fits. But ultimately, I think it's something we just have to decide on a case-by-case basis.

So my argument here is that this command only works by connecting to a ledger, and we already have a series of commands that work this way that are all `daml ledger <something>`, and they all share some CLI flags / daml.yaml behavior, so I think it makes sense here.

I don't think any of this should block the PR for the alpha version of daml script exports. We can hide the export command for now, or mark it as experimental, and add the `daml ledger export` logic in daml-helper in a separate PR.

**Comment by aherrmann-da** [comment]
That sounds reasonable. I've updated https://github.com/digital-asset/daml/pull/9414 to expose it as `daml ledger export script`.

**Comment by sofiafaro-da** [comment]
Thanks @aherrmann-da!
