### ISSUE TITLE
Oracle json-api: use array types for signatories/observer, or test for duplicates

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#9388]
Unlike the PostgresQueries, OracleQueries separates signatories and observers into separate tables, doing multiple joins to ensure that every signatory and observer (including the non-matching ones) is included in the resulting structure. There are two drawbacks:

1. the insert and query significantly diverge from PostgresQueries, and entail a strange chain of joins; and
2. the result may contain duplicates that may not be fixable with `select distinct`.

You can encounter duplicates because of the party check matching the same party multiple times, or in a multiparty query, any number of parties matching multiple times. In addition, there is no guarantee that the aggregation order of signatories and observers collected up with `LISTAGG` will remain stable, hence the failure of `distinct` to deal with this.

Shifting to arrays and testing for set intersection will solve this problem. In addition, `SupportedJdbcDriver` may then pass in the correct `Get` and `Put` instances for `Array[String]`.

However, if we do not switch over to arrays, we should test that the duplicate problem does not occur, and figure out how to adjust the queries accordingly. We want to avoid adding a layer of Scala-side processing to handle this if at all possible, because we are trying to generally do _less_ processing in dbbackend, not more (e.g. #9375). In addition, in this case, we should change the types of implicits that `SupportedJdbcDriver` holds to _depend_ on the underlying `Queries` instance, so that the nonsense `Array` instance currently in place can be removed.

**Comment by cocreature** [comment]
We should make sure that we can do indices on those arrays. @sormeter ran into some issues around that iirc. If we cannot get indices, I think we’re probably better off avoiding this.

**Comment by dasormeter** [comment]
Yeah if you need indices breaking out to tables and joining probably better than dealing with varray

**Comment by S11001001** [comment]
An illustration of the duplicate contracts:

```sql
create table my_contract
  (contract_id number(19, 0) primary key not null,
   agreement_text nclob not null);
create table my_signatories
  (contract_id number(19, 0) not null references my_contract (contract_id),
   party nvarchar2(255) not null);
create table my_observers
  (contract_id number(19, 0) not null references my_contract (contract_id),
   party nvarchar2(255) not null);
insert into my_contract values (33, 'an agreement');
insert into my_signatories values (33, 'foo');
insert into my_observers values (33, 'foo');
insert into my_signatories values (33, 'bar');
insert into my_observers values (33, 'bar');
select c.contract_id, agreement_text, sd.parties, od.parties from
   my_contract c
   LEFT JOIN my_signatories sm ON (c.contract_id = sm.contract_id)
   LEFT JOIN my_observers om ON (c.contract_id = om.contract_id)
   LEFT JOIN (select contract_id, listagg(party, '%') parties
              from my_signatories group by contract_id) sd on (c.contract_id = sd.contract_id)
   LEFT JOIN (select contract_id, listagg(party, '%') parties
              from my_observers group by contract_id) od on (c.contract_id = od.contract_id)
where sm.party in ('foo', 'bar') or om.party in ('foo', 'bar');
```

You cannot fix this directly with `select distinct`:

```
ORA-00932: inconsistent datatypes: expected - got NCLOB
```

**Comment by stefanobaghino-da** [comment]
> Yeah if you need indices breaking out to tables and joining probably better than dealing with varray

In #9484 we switched to JSON arrays flattened in the contracts table and using a [JSON Search Index](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/indexes-for-json-data.html#GUID-D7A604E1-F617-4C92-A9D9-00B6AB78EFD8), as suggested by @S11001001, successfully sped up the query, showing up in the execution plan.

**Comment by dasormeter** [comment]
> > Yeah if you need indices breaking out to tables and joining probably better than dealing with varray
> 
> In #9484 we switched to JSON arrays flattened in the contracts table and using a [JSON Search Index](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/indexes-for-json-data.html#GUID-D7A604E1-F617-4C92-A9D9-00B6AB78EFD8), as suggested by @S11001001, successfully sped up the query, showing up in the execution plan.

@stefanobaghino-da can you do an or wuery which makes user of index

for example, if you have a json array or parties and you want to search for party A or party B or party C?

**Comment by stefanobaghino-da** [comment]
> > > Yeah if you need indices breaking out to tables and joining probably better than dealing with varray
> > 
> > 
> > In #9484 we switched to JSON arrays flattened in the contracts table and using a [JSON Search Index](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/indexes-for-json-data.html#GUID-D7A604E1-F617-4C92-A9D9-00B6AB78EFD8), as suggested by @S11001001, successfully sped up the query, showing up in the execution plan.
> 
> @stefanobaghino-da can you do an or wuery which makes user of index
> 
> for example, if you have a json array or parties and you want to search for party A or party B or party C?

The syntax is `JSON_EXISTS(signatories, '$[*]?(@ in ("Alice", "Bob"))')`. In Oracle's SQL/JSON query syntax that translates to: in the object being queried (`$`), for all items in the array `[*]` match each item within (`@`) with the `in` clause with a given list of strings ([documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/json-path-expressions.html#GUID-AEBAD813-99AB-418A-93AB-F96BC1658618)).

I tested the query with both individual and multiple parties and a mix of known and unknown parties and the index was queried in both cases, with no visible slowdown on the execution time in any scenario.
