### ISSUE TITLE
extend json-api perf tests to Oracle, and test 100k-contract ACS

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#9460]
As #7434 extended http-json-perf to PostgreSQL, we can do the same for Oracle, albeit in an EE-only context.

Additionally, we would like to run a matrix of perf-testing queries against a 1-million-contract ACS. We aren't too interested in the in-memory performance (we know it is linear, guaranteed), but observing performance characteristics of both PostgreSQL and Oracle under different query distributions would be valuable.

Some dimensions we might be interested in:

1. Low-to-high frequency of party matches (due to % presence in signatories/observers);
2. low-to-high frequency of party matches (due to querying by smaller-to-larger party-sets);
3. " of template ID matches;
4. " of payload value matches.

To explain the difference between (1) and (2): suppose parties {foo, bar, baz}. To alter the frequency for (1) we fix the party-set as {foo} and change the % of contracts that have the sole party foo in signatories/observers. To alter the frequency for (2) we fix the respective % of contracts as {10%, 40%, 50%} and can then reach 10, 50, 100% frequency by querying with party-sets {foo}, {foo, bar}, and {foo, bar, baz} respectively.

**Comment by stefanobaghino-da** [comment]
Lowered testing threshold to 100k, closed by https://github.com/digital-asset/daml/pull/9530.

Will return on perf testing in the future if needed.

**Comment by dasormeter** [comment]
Hiya @stefanobaghino-da client expected contracts will be more in the multi-million range : have we tested json api at those levels?

**Comment by stefanobaghino-da** [comment]
> Hiya @stefanobaghino-da client expected contracts will be more in the multi-million range : have we tested json api at those levels?

No, we'll track this in the future with a different ticket.
