### ISSUE TITLE
Inquiry to make example code used in the docs available "somewhere"

### ISSUE THREAD

**Issue by nemanja-da** [digital-asset/daml#9462]
This issue has been reported via feedback form on the docs:

> Re https://docs.daml.com/daml-script/index.html I propose that every page that has an example, like this one, has the complete code for that example, located *somewhere*. That way new users can look at the big picture and go 'Ah huh!', and get the context of it all.

**Comment by cocreature** [comment]
It already is available: `daml new script-example --template script-example`. Probably just needs to be mentioned in the docs.
