### ISSUE TITLE
Oracle Ledger API Items to Investigate

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#9493]
Items to follow-up on for Oracle which may or may not be required, but which do require further investigation

- [x] #10543
- [ ] #10542
- [x] Figure out why protected and string interpolation for limit method is not working as expected within JdbcLedgerDao, leading to repetition of limit clause inline in DB specific methods
- [x] Figure out how to get group by behaviour for BLOB columns

**Comment by dasormeter** [comment]
Oracle Array related todos moved to https://github.com/digital-asset/daml/issues/9958

**Comment by matthiasS-da** [comment]
Even more important than supporting asynchronous commits (postgres: `synchronous_commit=off`) is to support a commit level that waits until the tx has been persisted to all replicas (postgres: `synchronous_commit=on`). This commit level is quite slow, so we can't enable it by default. But we need to use this in a few places (e.g. MultiDomainEventLog) to make our DR story work.
