### ISSUE TITLE
Improve UX for setting custom navigator port in daml ledger navigator

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#9496]
It can be quite useful to customize the port on which the Navigator listens. It is not possible via the command `daml ledger navigator` (handy for debugging as it does not need a `daml.yaml`), although `daml navigator server` does support a custom port.

**Comment by cocreature** [comment]
https://discuss.daml.com/t/change-default-port-4000-when-using-daml-ledger-navigator/685/2?u=cocreature

**Comment by richardkapolnai-da** [comment]
> https://discuss.daml.com/t/change-default-port-4000-when-using-daml-ledger-navigator/685/2?u=cocreature

wow ok, I had absolutely no chance to have guessed them. (but I could have google'd for it...)

I suggest let's either close this issue, or change the title to "make it more intuitive" or "document in help message"?

**Comment by cocreature** [comment]
Changed the title. TBH, I think the proper solution here is to kill daml ledge rnavigator and subsume the functionality in daml navigator. Having two commands is stupid anyway. I think the main thing that is still missing is picking up host and port from your daml.yaml. Apart from that they should be identical.

**Comment by richardkapolnai-da** [comment]
Uniting them would make UX simpler indeed. If that's a future plan, we can close this imho. If not, perhaps worth keeping this open and add a "Good First Issue" label :smiley:

**Comment by cocreature** [comment]
It’s my plan at least but it’ll take a while until someone finds the time. No harm in keeping it open in the meantime.

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
