### ISSUE TITLE
sandbox-control references non-existent daml-prim DAR

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#950]
The DAR referenced in https://github.com/digital-asset/daml/blob/d77384bcb6842139e316e0089edc0bf70725acc9/language-support/scala/sandbox-control/src/main/scala/com/digitalasset/sandbox/SandboxFixture.scala#L15 hasn’t existed for weeks so this code never seems to be executed on CI. It either needs to be fixed and tested by CI or removed.

**Comment by bitonic** [comment]
@leo-da if nobody's using `sandbox-control` feel free to purge it. Note that if there are tests that use it that can be replaced by just using the sandbox as a library, it'd be good to make them use the sandbox as a library.
