### ISSUE TITLE
Daml Script crashes with a confusing error when the upstream is unavailable

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#9532]
Pointing Daml Script to a participant config with a host that does not exist causes a confusing stack trace that does not adequately describe the root cause:

```
daml script --participant-config participants.json ...
```

```
Exception in thread "main" com.daml.lf.engine.script.ScriptF$FailedCmd: Command submit failed: Unexpected end-of-input at input index 0 (line 1, position 1), expected JSON Value:
^
Daml stacktrace:
submit at f81527529c9343ac4d0f4bd0a934eec0112f0bf4f125628b4c2905c1c9740ee0:DA.RefApps.Bond.MarketSetup.MarketSetupScript:44
        at com.daml.lf.engine.script.Runner.$anonfun$runWithClients$6(Runner.scala:401)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at ......
```

This was also mentioned in this issue on the forums: https://discuss.daml.com/t/problem-running-daml-script-against-daml-hub/2527

(cc @chrisnorris-da @leonidr-da @bame-da , who have all run into this issue through a temporary bug in Daml Hub that caused the wrong host name to be generated in `participants.json` for a period of time)

**Comment by da-tanabe** [comment]
Oops didn't notice in the very post I linked you're already looking into this! Sorry for the spam…if this is (now) a duplicate issue happy to close.

**Comment by cocreature** [comment]
Haven’t opened an issue for it but I have a patch locally already. Just didn’t find the time to write a test so far but it’s on my list to finish it up.
