### ISSUE TITLE
Non-deterministic contracts ids on Sandbox in Wallclock mode

### ISSUE THREAD

**Issue by tristan-da** [digital-asset/daml#958]
In earlier versions of the SDK the Sandbox (in wallclock time mode) created contracts with predictable ids, even across ledger resets (i.e. the first contract id used on startup or after a reset was always `#0:0`).  

In later versions of the SDK the behaviour has changed such that (i) the first contract id used after startup differs from the first contract id used after reset and (ii) the first contract id used after a reset is non-deterministic.

Neither of these issues qualify as bugs as the sandbox makes no guarantees about the contract ids returned and clients of the API should make no assumptions regarding this.  However both issues do represent a small "paper cut" in the developer experience vs prior versions of the SDK and could be improved.

Note that contracts ids remain predictable for the Sandbox in static time mode across all versions tested.

```
0.11.3  - 1st contract is always #0:0
0.12.1  - 1st contract is #2:0 on startup and #1:0 after each ledger reset
0.12.3  - 1st contract is #3:0 on startup and #2:0 after each ledger reset
0.12.4  - 1st contract is #3:0 on startup and either #1:0 or #2:0 after each ledger reset
0.12.6  - 1st contract is #3:0 on startup and either #1:0 or #2:0 after each ledger reset
0.12.12 - 1st contract is #3:0 on startup and either #1:0 or #2:0 after each ledger reset
```

**Comment by stefanobaghino-da** [comment]
Closing as suggested off-band by OP.
