### ISSUE TITLE
Remove unused ExercisedEvent from Event oneof

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#960]
Considering that transaction trees have their own event wrapper ([TreeEvent](https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/transaction.proto#L57-L62)), we can remove `ExercisedEvent` from the [`Event`](https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/event.proto#L35) oneof.

This is 100% backwards compatible on the wire, because the `ExercisedEvent` is currently not emitted on the flat transaction stream.
It will however cause a compile error when updating for example in a switch statement or a pattern match.

**Comment by gerolf-da** [comment]
@bitonic: what do you think?

**Comment by bitonic** [comment]
@gerolf-da i think it's a good idea, feel free to go ahead.
