### ISSUE TITLE
Guard against concurrent SDK installations

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#9612]
Currently, the assistant will fall over if you try to install the same SDK version in parallel.

The most sensible solution that I see here seems to be to write out a lock file before modifying anything in `~/.daml` and deleting it afterwards.

There are two options I see for what a concurrent invocation can do:
1. Error out with a clean error.
2. Block until the first one is finished.

I think 2 probably leads to a nicer UX. E.g., consider a build system which does parallel `daml build` invocations which end up installing the same SDK version. It doesn’t really make sense to fail a build because of that. Arguably the build system should enforce that the SDK is already installed but we still want to provide a nice UX if users don’t do that.

**Comment by sofiafaro-da** [comment]
That (option #2) sounds very sensible, particularly when it comes to auto-install. 👍
