### ISSUE TITLE
Small improvements to the daml assisstant

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#965]
A bunch of things collected from various places:

- [x] Add `daml list` to list installed versions.
- [x] Running `daml` alone should give a clue about how to get started. e.g. which commands or a link to a website.
- [x] `daml init` doesn't work, would be nice if that was an alias for `new`.
- [x] `daml new` requires arguments like a target path. Why not `.`? or generate its own target path that is free?
- [x] `daml new test` prints nothing to stdout. Not hints as to where it created things or what I can do next
Fixed in https://github.com/digital-asset/daml/pull/935
- [x] `daml start` doesn’t print anything for quite a while, would be good if it started with “Compiling… done`
Fixed in https://github.com/digital-asset/daml/pull/934
- [x] Could `daml start` also open up a web browser at the port it opens? (there’s a haskell library for doing exactly that)
- [ ] Ctrl-C in daml start gives me `Terminate batch job (Y/N)?` - we need to get rid of that ideally

**Comment by cocreature** [comment]
I discussed `init` and `new` yesterday with @associahedron and here is roughly what we agreed on.

- I expect `new` to create a new directory and that seems to match what other tools (e.g. `stack new`) do.  Choosing that new directory automatically seems quite confusing to me.
- On the other hand I expect `init` to initialize something that already exists, i.e., the project in the current directory. This would also be a good place to convert `da.yaml` to `daml.yaml` (if it exists).

Does that sound reasonable to you @neil-da?

**Comment by neil-da** [comment]
To me, init and new are close enough to synonyms that I'm a little concerned about having two different semantics for them. My motivation here is "how do I create a new project" => "type `stack new`". To be required to pass extra information is not user friendly, and requires a user to think of something extra, when they'd rather not bother if give the option. If you want to go ahead, I've no objections to the plan, but if we could do better I'd prefer it.

**Comment by nickchapman-da** [comment]
The much reduced `daml new` template is nice, but the behaviour of  `daml new quickstart-java` might confuse some users, when what they meant was: `daml new quickstart quickstart-java`.

**Comment by nickchapman-da** [comment]
`daml` and `daml new` etc. could show the help text. Or at least report that `--help` is an option.

**Comment by associahedron** [comment]
> The much reduced `daml new` template is nice, but the behaviour of `daml new quickstart-java` might confuse some users, when what they meant was: `daml new quickstart quickstart-java`.

I think in case of `daml new quickstart-java` we could display a message asking the user to be more specific:

```
daml: Invalid argument: 'quickstart-java' is a template name, but here it was given as a project name.

To create a project based on the 'quickstart-java' template, use the command:

    daml new PROJECTNAME quickstart-java

To create project named 'quickstart-java' based on the default 'skeleton' template, use the command:

    daml new quickstart-java skeleton
```

**Comment by associahedron** [comment]
> I discussed `init` and `new` yesterday with @associahedron and here is roughly what we agreed on.
> 
>     * I expect `new` to create a new directory and that seems to match what other tools (e.g. `stack new`) do.  Choosing that new directory automatically seems quite confusing to me.
> 
>     * On the other hand I expect `init` to initialize something that already exists, i.e., the project in the current directory. This would also be a good place to convert `da.yaml` to `daml.yaml` (if it exists).
> 
> 
> Does that sound reasonable to you @neil-da?

I want to implement this as discussed w/ @moritzkiefer-da. I don't see the value in having two commands do the same thing, and in this case they are fulfilling different roles (`daml new` creates a new project folder from a template, `daml init` turns an existing folder into a daml project, including converting `da.yaml` if available).

**Comment by neil-da** [comment]
Fair enough, that makes some sense.

**Comment by associahedron** [comment]
#1080 implements `daml init`.

**Comment by associahedron** [comment]
#1114 implements the equivalent of `da list` as `daml version`.

The last item on the list (and the only remaining) is about suppressing Ctrl+C warning on Windows.

Based on this stackexchange post, this seems incredibly fraught if we keep using .cmds... https://superuser.com/questions/35698/how-to-supress-terminate-batch-job-y-n-confirmation

We use .cmds in place of symlinks on Windows to link the assistant executable to daml/bin. If we replace this with an executable that just redirects to the latest installed assistant every time, we can get rid of the Ctrl+C prompt. This would make the install --activate flag obsolete on Windows. (We could also do this on Mac and Linux, making the --activate flag obsolete everywhere.) It also requires special care around upgrades (can't remove or overwrite an executable that is currently running...).

Toughts @moritzkiefer-da @neil-da ?

In any case, that seems like a larger change and in the meantime our docs can just say that for Windows you need to press Ctrl+C and confirm "Y" to stop the service (or press Ctrl+C twice).

**Comment by cocreature** [comment]
Yeah that’s pretty much the conclusion I came to as well when I took a short look at this a few days back. I’d say for now let’s just go with what we have.

**Comment by neil-da** [comment]
I'd say the Ctrl-C thing leaks internal details of our implementation in a deeply unpleasant way.

Could we avoid the batch file? And have a binary `forward.exe` whose implementation is approx `system_ {getExecutableName}.txt %*`. And then copy forward.exe naming it daml.exe and generate daml.txt to say where the redirect goes to? I would imagine writing forward.exe in C to keep it nice and small.

**Comment by neil-da** [comment]
Note that `forward.exe` could spawn and exit, or could only read from the .txt file, making upgrades fine. Removing `--activate` everywhere seems like a worthwhile goal.

**Comment by cocreature** [comment]
We could certainly do that and that’s what @associahedron suggested above but it also seems like a fair amount of complexity to work around the fact that windows insists on treating batch files speciallly and it won’t allow us to get rid of `--activate`. We’ll just have to change `--activate` to modify a secondary text file instead of modifying the batch wrapper.

**Comment by cocreature** [comment]
That said, I agree that we should probably fix it at some point. I just don’t think it’s very urgent.

**Comment by neil-da** [comment]
Agreed on both fronts - worth fixing, not worth fixing with high priority.

**Comment by associahedron** [comment]
I'll create a specific, separate issue for later, and close this one.
