### ISSUE TITLE
Small improvements to the Windows installer

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#966]
- [ ] Should not emit a warning by Windows defender. This requires us to sign the installer.
- [x] Handle existing installations (e.g. prompt the user if he wants to override)
- [x] Needs an icon and branding.
- [x] Needs a page to confirm you want to install, so it doesn't immediately start installing when clicked.
- [x] Should try and detect if you have Java installed, and if not, send you to an appropriate installed. Perhaps the same with VS Code.
#1157 improves the error messages on missing Java and VSCode. Duplicating the logic in the installer is something that I would like to avoid.
- [x] Should have a final page that gives you the option to visit the website or start a new demo project.

**Comment by cocreature** [comment]
The only thing missing is signing which is tracked in #29 so I’m closing this issue.
