### ISSUE TITLE
do not mention transaction ids in SQL schema

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#981]
right now the SQL schema for the sandbox mentions both transaction ids and ledger offsets: https://github.com/digital-asset/daml/blob/bb6f21373de6eba7287f57ea6c045b7de56d423e/ledger/sandbox/src/main/resources/db/migration/V1__Init.sql .

however internally we have the constraint that the transaction id _is_ the ledger offset.

we should make this fact clear to avoid confusion regarding the semantics of ledger offset and tx id in the sql backend, something that has already arisen when implementing the fix for #784 .

**Comment by gerolf-da** [comment]
The constraint "transactionId == ledgerOffset" does not exist anymore.
