### ISSUE TITLE
Command deduplication V2 on the JSON API

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#9835]
The changes for command deduplication from https://github.com/digital-asset/daml/pull/9567 also need to be exposed on the JSON API. The error reporting part is covered in #9834, this issue covers the rest.

### Current state

On command submission the JSON API accepts an optional `meta` field in which you can specify the `commandId`. If it is not specified, the JSON API generates a random UUID. It is not possible to specify the deduplication time at the moment.

### Proposed changes

In addition to the existing `commandId` we also accept the following optional fields in `meta`:
1. `submissionId` mapping to the submission id in gRPC. If not specified, it is also not specified in gRPC.
2. `submissionRank` mapping to the submission rank in gRPC. If not specified, it is also not specified in gRPC.
3. One of `deduplicationOffset`, `deduplicationStart`, `deduplicationSince`. Specifying more than one results in `InvalidUserInput`. If none is specified, it is also not specified in gRPC. Note that we do not allow `deduplication_time`. Given that this will be deprecated and we do not support it now it seems pointless to add it.

On the read side, we include `completionOffset` in successful responses which is taken from the synchronous command submission service.

Extend the documentation accordingly: https://github.com/digital-asset/daml/blame/main/docs/source/app-dev/command-deduplication.rst#L372

### Implications

1. Users have the same amount of control that they get on the synchronous command service.
2. We expose the necessary information in the response.
3. If users do not care about it, they can still omit everything.
4. Fully backwards compatible provided users ignore extra fields on responses.
5.

**Comment by stefanobaghino-da** [comment]
See: https://github.com/digital-asset/daml/pull/9567#issuecomment-1080790781

**Comment by realvictorprm** [comment]
> One of deduplicationOffset, deduplicationStart, deduplicationSince. Specifying more than one results in InvalidUserInput. If none is specified, it is also not specified in gRPC. Note that we do not allow deduplication_time. Given that this will be deprecated and we do not support it now it seems pointless to add it.

@cocreature is it also fine if I just add a field `deduplicationOption` where the value can be one of?
```json
{
  "@type": "deduplicationOffset",
  "value": "whateverthiscanbe",
}
```
```json
{
  "@type": "deduplicationStart",
  "value": "whateverthiscanbe",
}
```
```json
{
  "@type": "deduplicationSince",
  "value": "whateverthiscanbe",
}
```

**Comment by cocreature** [comment]
I’d go for
```code
"deduplicationOffset": …
```
instead but I don’t have strong feelings here.

**Comment by realvictorprm** [comment]
> One of deduplicationOffset, deduplicationStart, deduplicationSince. Specifying more than one results in InvalidUserInput. If none is specified, it is also not specified in gRPC. Note that we do not allow deduplication_time. Given that this will be deprecated and we do not support it now it seems pointless to add it.

I can report back that there only seems to be `DeduplicationOffset` and `DeduplicationDuration` as available cases (ignoring the `Empty` case and the deprecated `DeduplicationTime` case).

**Comment by realvictorprm** [comment]
> On the read side, we include completionOffset in successful responses which is taken from the synchronous command submission service.

I'm not sure how the response should look like in this situation. Shall I add this information as another field to response object i.e. ActiveContract (in the case of a create command)?
