### ISSUE TITLE
Clarify how time works

### ISSUE THREAD

**Issue by cbaatz-da** [digital-asset/daml#986]
Documentation should clearly explain the ledger time model and what ledger effective time, maximum record time, and transaction effective at time mean, how they interact, and how they relate to the wall clocks of ledger nodes.

**Comment by hurryabit** [comment]
There is a document called "DA Ledger Time Model" in the repo:
https://github.com/digital-asset/daml/blob/master/daml-foundations/daml-tools/docs/time-model/source/index.rst

Is this related? And how up to date is it? @oggy- do you know?

**Comment by oggy-** [comment]
It's a bit out of date as it was written about a single committer implementation, but IMO otherwise discusses the relevant issues of ledger effective time and maximum record time. I'm not familiar with "transaction effective at time" that @cbaatz-da mentions?

**Comment by bethaitman** [comment]
I'm very happy to write this up into something but who should I get the information from - who has the most (up-to-date) knowledge about this?

And is this just for sandbox or does it apply more generally?

**Comment by cbaatz-da** [comment]
@bethaitman if you wanted to add an explanation of time to the external docs I think that would be great. For user-facing docs, my inclination would be to first clearly explain how it works and then optionally on why it works like that, but your call.

**Comment by oggy-** [comment]
@bethaitman actually, the sandbox is the only implementation for which the time issues aren't really relevant; it corresponds to the "ideal" model in my write-up above. However, every distributed implementation of a DAML ledger requires the dance with LET and MRT, so the sandbox must also comply with what the distributed ledgers are doing (though possibly one could also have an alternative, simplified, sandbox-only interface).

**Comment by bitonic** [comment]
Related: #1068

**Comment by bame-da** [comment]
https://docs.daml.com/daml/intro/5_Restrictions.html#time-on-daml-ledgers

**Comment by gerolf-da** [comment]
Superseded by the implementation of the [Ledger Time Model](https://github.com/digital-asset/daml/milestone/37).
