### ISSUE TITLE
Transaction is recorded AFTER the provided MRT

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#987]
It is possible to create a transaction with a record time AFTER the maximum record time provided in the original command.

![image](https://user-images.githubusercontent.com/29121423/57317232-edc73800-70f7-11e9-8afd-a0243230f0c2.png)

Reproducible by the [attached](https://github.com/digital-asset/daml/files/3153715/repro.zip) SDK project with:

```
da run damlc -- package daml/Main.daml target/daml/iou
da run sandbox -- target/daml/iou.dar -w
mvn compile exec:java@run-quickstart
```
Currently, the record time for a transaction is set in the backends at `Ledger#publishTransaction` ([InMemory](https://github.com/digital-asset/daml/blob/0489c6e0a53a0bab095b7d7c3037bd87f310e7ea/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/inmemory/InMemoryLedger.scala#L132) and [SQL](https://github.com/digital-asset/daml/blob/0489c6e0a53a0bab095b7d7c3037bd87f310e7ea/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala#L241)) .

**Comment by gerolf-da** [comment]
Sadly, this doesn't currently hold: https://github.com/digital-asset/daml/blob/05e691f55852fbb207f0e43cf23bb95b95866ba3/ledger/backend-api/src/main/scala/com/digitalasset/ledger/backend/api/v1/TransactionSubmission.scala#L12-L16

**Comment by gerolf-da** [comment]
The maximum record time (MRT) is used by applications to detect timeouts of commands. The MRT of a command is specified in the time domain of the ledger. Therefore only timestamps received from the ledger may be compared to the MRT of a command.

Can transactions have a record time (Ledger API field [`effective_at`](https://github.com/digital-asset/daml/blob/5bb0b50286a9d2192ef8c9a762f36f22fcd42ed8/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/transaction.proto#L34))? On first glance it seems this shouldn't be possible.

However, there is one scenario where a transaction's record time may be greater than the maximum record time:
The application can only conclude that a command has timed out, if it receives a [checkpoint](https://github.com/digital-asset/daml/blob/5bb0b50286a9d2192ef8c9a762f36f22fcd42ed8/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/command_completion_service.proto#L77) on the [completion stream](https://github.com/digital-asset/daml/blob/5bb0b50286a9d2192ef8c9a762f36f22fcd42ed8/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/command_completion_service.proto#L36) from the ledger with a `record_time` greater than the command's MRT without having received the [completion](https://github.com/digital-asset/daml/blob/5bb0b50286a9d2192ef8c9a762f36f22fcd42ed8/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/completion.proto#L16) for the command.
If the ledger does not send any checkpoints between the client sending the command and the completion of that command, the ledger would be free to accept the transaction with a record time after MRT.
Having said that, it is in practice more complicated to make this scenario work than to reject the transaction.

**Comment by bitonic** [comment]
@gerolf-da , thanks for explaining. This might hint at the fact that maybe we should advertise the role of the timeout differently: it's "you should try to retry after this much time" rather than "you will _not_ receive a completion after this time". This would suffice for command submission, since commands are deduplicated anyway and "useless" retries are thus harmless.

However that would mean that one cannot rely on the MRT to reliably determine that the command has failed, as the command service does.

cc @meiersi-da @dajmaki @gaboraranyossy-da what do you think?

**Comment by meiersi-da** [comment]
My expectation was that the ledger maintains both the list of committed transactions and updates to the record time.

This way it can and does *guarantees* that a transaction does not get committed after the record time has been bumped to a value strictly larger than the maximum record time in the submitted transaction. This is how I've documented the maximum record time field in the DAML Integration Kit: https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/SubmitterInfo.scala#L23

From my perspective the screenshot shows a bug in the SQL and InMemory backends of the sandbox.

Also @gerolf-da : `effective_at` is a different timestamp than the record time of a transaction. Currently the record time of transactions is not exposed on the Ledger API AFAIK. Can you clarify what you mean by your statemement

> Can transactions have a record time (Ledger API field effective_at)? On first glance it seems this shouldn't be possible.

As per my understanding, the `effective_at` field can be larger than the maximum record time, as the [`max_ttl`](https://github.com/digital-asset/daml/blob/master/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/ledger_configuration_service.proto#L41) in the configuration can allow values larger than the maximum record time. Or is there another requirement / invariant that I'm missing?

**Comment by bitonic** [comment]
@meiersi-da my comment was proposing an _alternative_ perspective, but I agree we have been advertising the semantics as you described, which is why @gerolf-da fixed the behavior exhibited here in #990.

**Comment by meiersi-da** [comment]
@francesco-da : note that it depends on where deduplication happens for deciding how harmless duplicate submissions are. I believe the current advice for users to wait for a confirmation of either a command completion or the record time having surpassed the maximum record time of their command submission until they retry is correct.

**Comment by gerolf-da** [comment]
@meiersi-da: The invariant should be: `max_ttl <= MRT - LET`.
Regarding
> Can transactions have a record time (Ledger API field effective_at)?

The current implementation uses the record time for the `effective_at` field of the emitted transactions:
https://github.com/digital-asset/daml/blob/0489c6e0a53a0bab095b7d7c3037bd87f310e7ea/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/services/transaction/SandboxTransactionService.scala#L120-L127

**Comment by bitonic** [comment]
Le't continue the discussion on #1068, to keep this issue about fixing the code in the sandbox.
