### ISSUE TITLE
DAML Assistant start command creates a DAR file in the root of the project, should not it be `./dist`

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#992]
Minor inconsistency:

`daml-head build` creates a DAR in the `./dist` folder:
```
daml-head build
Compiling daml/Main.daml to a DAR.
Created dist/scala-codegen-test.dar.
```
`daml-head start` creates the same DAR in the root of the project:
```
$ daml-head start
Compiling daml/Main.daml to a DAR.
Created scala-codegen-test.dar.
```

It would be nice if both commands created dars in the same `./dist` directory. Polluting root with build artifacts is not nice.

**Comment by associahedron** [comment]
:+1: This was a silly inconsistency.
