### ISSUE TITLE
Warn about use of divulged contracts in IDE (Scripts), Sandbox and Ledger API Server

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#9947]
As part of our rollout plan for #9283, we should start emitting warnings in IDE, Sandbox, and ideally all Ledger API Servers if a submission makes use of divulged contracts that could be pruned away.

The warning should be informative enough to identify where in the transaction or even in Daml the fetch or exercise occurred. Something like

"Warning: Use of divulged contract incompatible with Participant Pruning. 
The submission with CommandId = Foo with readAs Party/ies [Alice, Bob] makes use of contracts only known to those parties by divulgence. Contracts affected:

{
  template_id: {TEMPLATE_ID}
  contract_id: {CONTRACT_ID}
  stakeholders: [Carol, Doris]
  location: {PATH_TO_NODE}
},
{
  template_id: {TEMPLATE_ID}
  contract_id: {CONTRACT_ID}
  stakeholders: [Carol, Doris]
  location: {PATH_TO_NODE}
}
"

Since we are likely to land the change to pruning in 1.16, I would really like to get this into 1.15.

**Comment by cocreature** [comment]
For the runtime warnings during interpretation, I think it makes sense to do those directly in the engine. Then we solve this for everything at once instead of having to worry about which ledgers warn and which don’t.

There is one issue to make this work: The engine does not currently have access to the `readAs` parties which we need here. This is less of a practical problem to fix (I already hacked up a prototype for another issue at some point) but it does somewhat break our current assumption that visibility checks are handled outside the engine.

But it isn’t obvious to me that we really gain anything by having that separation and this seems like a good argument for breaking it.

**Comment by mziolekda** [comment]
I do not have any reservations for moving this check to the engine.

I am worried about something else. 
1. The format we want to use for this is very verbose. We should be able to turn it off, else it could flood the log-files of some users. 
2. Will we be able to distinguish the contracts that have been divulged vs those that have been disclosed and print this message only for the former? Again some users are relying on disclosed contracts.

**Comment by cocreature** [comment]
I don’t think we want a different error for divulgence vs disclosure. Unless I misunderstood @bame-da both are deprecated.

**Comment by cocreature** [comment]
For verbosity, I think we should at least have some way to turn off the path to the warning. The rest isn’t all that verbose.

**Comment by bame-da** [comment]
What do you mean by disclosure? Witnessed create events? The [Ledger Model](https://docs.daml.com/concepts/ledger-model/ledger-privacy.html#divulgence-when-non-stakeholders-see-contracts) makes no distinction there. 

> More precisely, every action act on c is shown to all informees of all ancestor actions of act. These informees are called the witnesses of act. If one of the witnesses W is not a stakeholder on c, then act and c are said to be divulged to W. Note that only Exercise actions can be ancestors of other actions.

I'm fine with allowing the suppression of the warnings or parts thereof.

**Comment by bame-da** [comment]
Maybe I should phrase it this way: We emit a warning during interpretation if the transaction contains an action on a contract `c` on which none of the `readAs` or `actAs` parties are a stakeholder.

**Comment by cocreature** [comment]
Our implementation (which I suspect is what @mziolekda is referring to) distinguishes divulgence of contracts via fetch, exercise,… from disclosure of creates (or really any node). The ledger model doesn’t and calls both of those divulgence.
Both of those cause the same problems with pruning so for the purposes of this issue we should treat them the same.

**Comment by bame-da** [comment]
I'd like to pass on feedback that suggest improving the current message to include a remediation:

Now
```
Tried to fetch or exercise -homePackageId-:Main:T contract ContractId(00d9637fd3efbdeff8a9b8ea4c4f966c44292204767756bed00a1ac99162a7e33f) but none of the reading parties actAs = TreeSet(p2), readAs = Set() are a stakeholder TreeSet(p1). Use of divulged contracts is deprecated and incompatible with pruning.
```

Suggestion:
```
Tried to fetch or exercise SOMEHASH:Main:T on contract 00d9637fd3efbdeff8a9b8ea4c4f966c44292204767756bed00a1ac99162a7e33f, but none of the reading parties [p2] are a member of the stakeholders [p1].

Use of divulged contracts is deprecated and incompatible with pruning. To remedy, add one of the readers [p2] as an observer to the contract.
```
