### ISSUE TITLE
Allow ledger implementations to trigger backpressure before DAMLe is invoked

### ISSUE THREAD

**Issue by matthiasS-da** [digital-asset/daml#9991]
Currently, a ledger implementation can trigger backpressure by making `WriteService#submitTransaction` return `Overloaded`. This has the drawback that ledger can abort a command only after DAMLe has been executed. The current backpressure mechanism cannot be used to shield the system from excessive use of DAMLe.

To avoid that, extend `ApiCommandSubmissionService` with a callback `isOverloaded` that allows the ledger to tell if it is overloaded. Invoke `isOverloaded` before running DAMLe.

**Comment by matthiasS-da** [comment]
I'll come up with a proposal soon.

**Comment by matthiasS-da** [comment]
My proposal is here: https://github.com/DACH-NY/canton/commit/a9c2b387507cf85c838c64f42e61db7739a61256

@oliverse-da @gerolf-da FYI

**Comment by oliverse-da** [comment]
> My proposal is here: [DACH-NY/canton@a9c2b38](https://github.com/DACH-NY/canton/commit/a9c2b387507cf85c838c64f42e61db7739a61256)
> 
> @oliverse-da @gerolf-da FYI

+ fyi @mziolekda @remyhaemmerle-da @cocreature 

also added to canton-fork doc: https://docs.google.com/document/d/17ZYvZmfFZE47MCzZ5nMOe8qu3-QhphoGq7j4Ii8iZIE
